### ISSUE TITLE
un-tested line in sets.py

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#10038]
[This line Line283](https://github.com/sympy/sympy/blob/master/sympy/sets/sets.py#L283) is not tested. An immediate example for this happening does not come to my mind. Perhaps if such a condition is not possible then it should be removed.

**Comment by Devyani-Divs** [comment]
@gxyd would like to work on it if you ain't working on it? :)

**Comment by gxyd** [comment]
You can go ahead with solving this.

**Comment by asmeurer** [comment]
That line seems wrong. It assumes that `self` is finite, but this is the `Set` base class, so the logic there should work on any possible set. It's probably not tested because no subclasses return None for _contains (is that even what it's supposed to do? The base class _contains raises NotImplementedError). I would just remove that line.

**Comment by manipalsingh013** [comment]
I'm newbie, @asmeurer  @gxyd how are checking whether line283 or some other line was checked or not.

**Comment by tyagi221295** [comment]
i have made the pull request for this issue.#10080.

**Comment by asmeurer** [comment]
Huh, apparently if you put "fixes #10038" in the merge commit message it doesn't automatically close the issue.
