### ISSUE TITLE
Inconsistency with Residue

### ISSUE THREAD

**Issue by coozmaster** [sympy/sympy#10065]
When using the residue function, I'm seeing some inconsistent behavior (this is being used to evaluate potential flow theory).

I have a complex potential:
F= m/(2 pi) (ln(z-b) + ln(z-a**2/b) - ln(z) )

Where m, b, and a are all positive. Additionally, I know that b>a and z is a complex number.

Then I evaluate the complex velocity by differentiating with respect to z:
w = diff(F,z).expand()

So far so good, now I define the square of complex velocity.
f = (w**2).expand().factor()

I find the poles to be at (0,b,a**2/b).

Which is expected, and I know the stagnation points (complex velocity = 0) exist at +/- a. Thus, the only poles that lie inside a contour of +/- a are 0 and a^2/b.

Now for the inconsistency, if I then calculate 
2 pi j (residue(f,z,0) + residue(f,z,a**2/b))

I get:
1.0 j m^2 (a^2 + b^2)/(pi a^2 b)

Now, if I simply redefine f as:
 f = (w**2).expand() 

and re-evaluate:
 2 pi j (residue(f,z,0) + residue(f,z,a^2/b)

I obtain:
1.0 j m^2/(pi b)

Which are not equal, any ideas on which is correct (or less incorrect)? Even understanding the issue so I know how to avoid it in future work would be very helpful.

Thanks,
Andrew

**Comment by jksuom** [comment]
It looks like both results are incorrect, the factored form being worse. Setting ``g = f.factor()`` we get
```
>>> residue(f, z, a**2/b)
-b*m**2/(2*pi**2*a**2)
>>> residue(g, z, a**2/b)
0
```
Neither of these results is correct. The correct residue can be extracted from the series expansion.
```
>>> f.nseries(z, a**2/b, 0)
-b*m**2/(2*pi**2*a**2*(-a**2/b + z)) + m**2/(4*pi**2*(-a**2/b + z)**2) + 2*m**2/(4*pi**2*a**2*(-a**2/b + z)/b - 4*pi**2*b*(-a**2/b + z)) + O(1, (z, a**2/b))
```
The denominator of the second term is quadratic in ``z - a**2/b``. Hence the residue is obtained from the two remaining terms whose denominators are linear. The result given above is derived from the first term alone. SymPy's ``residue`` does not recognize the third term since is is not strictly of the form constant times ``1/(z - a**2/b)``. With the factored expression ``g`` the result is even less correct.

**Comment by coozmaster** [comment]
Ah, I see. I appreciate the explanation, I believe I understand more about the residue function and its inherent limitations.

I'll be sure to pay attention to this in the future, and checking its results against f.nseries.

Thank you for the help, it is greatly appreciated!
Andrew

**Comment by jksuom** [comment]
@coozmaster , thanks for opening this issue. It is a bug that ought to be fixed. I think you should reopen the issue even if there is a workaround for finding the residues.

The code in SymPy is based on the series expansion that is probably reliable. The fix could be to extract all terms with linear denominator, not only those strictly of the form constant times ``1/(z - a)`` where ``a`` is the pole. (Actually, the difference ``z - a`` is replaced by a dummy variable in the code.) The residue can then be found by multiplying with ``z - a``.
