### ISSUE TITLE
Replace needs_brackets with parenthesize in the latex printer

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10157]
The LaTeX printer has a `_needs_brackets` method, which checks if something needs parentheses. But there is already the parenthesize module, which works more generally. Uses of `_needs_brackets` should be replaced and `_needs_brackets` should be removed or deprecated.

I've already replaced one instance of this over at https://github.com/sympy/sympy/pull/10084, but I didn't bother with the rest. 

This shouldn't be too hard to fix, as long as you have an understanding of how operator precedence works. And hopefully there should be sufficient test coverage to avoid breaking things, although whoever fixes this should probably check that each instance of `_needs_brackets` is tested to be sure.

**Comment by asmeurer** [comment]
https://github.com/asmeurer/sympy/commit/63315630e86df3b6864783e83d2d9ee83f102b76 is the relevant is the relevant commit from that PR.

**Comment by joshuacook** [comment]
I can take a look at this.

**Comment by sampadsaha5** [comment]
@asmeurer 
I went through the issue as well as your mentioned commit.
Can you please explain the use of  `PRECEDENCE['Pow']`  briefly from [here](https://github.com/asmeurer/sympy/blob/63315630e86df3b6864783e83d2d9ee83f102b76/sympy/printing/latex.py#L438)

**Comment by jailuthra** [comment]
I'd like to work on this. I'm a newbie so I might ping for help, though I've started to prepare a patch.

@sampadsaha5 See [printing/precedence.py](https://github.com/asmeurer/sympy/blob/master/sympy/printing/precedence.py) for understanding the order. Also check how the [parenthesize method](https://github.com/asmeurer/sympy/blob/master/sympy/printing/latex.py#L148) is flexible because it takes this argument.
