### ISSUE TITLE
integrate((1/sqrt(((y-x)**2 + h**2))**3), (x,0,w), (y,0,w)) is wrong

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#10211]
From http://stackoverflow.com/a/34072296/161801.

```
In [2]: var('w h')
Out[2]: (w, h)

In [3]: integrate((1/sqrt(((y-x)**2 + h**2))**3), (x,0,w), (y,0,w))
Out[3]:
          ________
         ╱      2
        ╱      w
  2⋅   ╱   1 + ──
      ╱         2
    ╲╱         h     2
- ──────────────── + ─
         h           h

```

However, the resulting integral is negative when `h` and `w` are positive, even though the integrand itself is nonnegative. It looks like this is coming from the `meijerg` algorithm.

**Comment by jksuom** [comment]
It seems that most of the wrong integration results are caused by a wrong branch choice of a multivalued indefinite integral. In this case, the first (meijerg) step appears formally correct:
```
In [2]: f = 1/sqrt(((y-x)**2 + h**2))**3

In [3]: F = integrate(f, x)

In [4]: F
Out[4]: 
           1           
───────────────────────
         ______________
        ╱     2        
 2     ╱     h         
h ⋅   ╱   ──────── + 1 
     ╱           2     
   ╲╱     (x - y)      
```
However, it is not evident from this expression that one should use the negative branch of the square root if ``x < y`` and the positive default branch only if ``x > y``. This is easier to see if both the numerator and denominator of ``F`` are multiplied by ``x - y``:
```
        x - y        
─────────────────────
      _______________
 2   ╱  2          2 
h ⋅╲╱  h  + (x - y)  
```
