### ISSUE TITLE
The helpers kwarg in autowrap method is probably broken.

### ISSUE THREAD

**Issue by tokencolour** [sympy/sympy#10274]
The helpers kwarg in autowrap method is probably broken and there are no unit tests for that. 
I get the following error:
```
>>> from sympy.utilities.autowrap import autowrap 
>>> from sympy import Eq, symbols 
>>> x, y, z=symbols("x, y, z") 
>>> expr=(x-y+z)**(13)
>>> binary_func=autowrap(expr, language='C', backend='Cython', 
... helpers=('helper',x-y+z, (x,z,y))
 ... ) 
Traceback (most recent call last): 
File "<stdin>", line 2, in <module> 
File "/home/thd/sympy/sympy/core/cache.py", line 93, in wrapper
retval = cfunc(*args, **kwargs) 
File "/usr/lib/python3.4/functools.py", line 472, in wrapper 
result = user_function(*args, **kwds) 
File "/home/thd/sympy/sympy/utilities/autowrap.py", line 522, in autowrap 
for name, expr, args in helpers: 
ValueError: too many values to unpack (expected 3)
```
The args in helpers are used to call make_routine(), so the argument sequence should be tuple or a list.

**Comment by meghana1995** [comment]
In the following line:
https://github.com/sympy/sympy/blob/master/sympy/utilities/autowrap.py#L522
helpers is a tuple, and one cannot iterate through a tuple of elements in that manner.
So I made helpers a list of tuples, so that the for loops won't show an error. I will add tests to this.

**Comment by nathanielvirgo** [comment]
Just a note: the commits mentioned above do not actually fix the serious issue here, which is that the 'helpers' argument only works with a single helper function, not a list as it's supposed to.

It is a very easy fix, basically just deleting line 599 from sympy/utilities/autowrap.py , or fixing it so that it doesn't put the variable inside a list if it's a list already.

    helpers = [helpers] if helpers else ()

**Comment by nathanielvirgo** [comment]
These changes didn't fix the helper arg - in fact they broke it! It's supposed to take a list of tuples rather than a single tuple, and the subsequent code then iterates over that list. Adding the following line makes it more convenient if you have only a single helper function (you don't have to put it inside a list), but it makes it impossible to use more than one!

    helpers = [helpers] if helpers else ()

Could this line please be either deleted or changed so that if `helpers` is a list then it won't put it inside another one? And could some unit tests be added with more than one helper function?
