### ISSUE TITLE
sympy.S handles numpy arrays incorrectly.

### ISSUE THREAD

**Issue by bjodah** [sympy/sympy#10295]
There are currently (at least) two problems:

First problem is implicit conversion to finite precision floating point values instead of `sympy.Integer` when applicable:

```
In [1]: import numpy, sympy

In [2]: print(numpy.__version__, sympy.__version__)
('1.10.1', '0.7.7.dev')

In [3]: sympy.S(numpy.array([1], dtype=numpy.int64))
Out[3]: 1.00000000000000
```

The other problem is that array data are interpreted as shapes somehow:

```
In [4]: out = sympy.S(numpy.array([1, 2, 3], dtype=numpy.int64))

In [5]: out.shape
Out[5]: (1, 2, 3)

In [6]: out
Out[6]: 
array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.]]])
```

This causes major problems when doing e.g. `rref` on a numpy integer array (which we arguably should support).

**Comment by tokencolour** [comment]
Shouldn't an array containing `int 1` be the output?

**Comment by bjodah** [comment]
Yes, I suppose, but the major problem here is the implicit conversion to finite precision floating point values: we need numpy integer types to be converted to `sympy.Integer` instances.

I discovered this when I was trying to do `rref` on a NumPy array of integers and got lot's of matrix elements of size ~1e-16 (close to epsilon of float64).

**Comment by tokencolour** [comment]
I got the same when I tried 
```
sympy.S(numpy.array([65, 55, 99], dtype=numpy.int64))
```
So there are two problems here.

**Comment by tokencolour** [comment]
It's getting type coerced [here](https://github.com/sympy/sympy/blob/master/sympy/core/sympify.py#L270).

**Comment by tokencolour** [comment]
The problem probably, is:
```
if iterable(a):
        try:
            return type(a)([sympify(x, locals=locals, convert_xor=convert_xor,
                rational=rational) for x in a])
```
(This is part of sympify.py, see [this](https://github.com/sympy/sympy/blob/master/sympy/core/sympify.py#L279).)

This made a call to numpy.ndarray(...) which by the virtue of its construction took the list of numbers as its shape and created a random numpy array as a result.

My try:
This patch does make sure that the inputs are not converted to finite precision floating point values. However, I am facing a problem here.  This patch returns a list ( which we can send as an argument when instantiating the ``Matrix`` object). I have not yet figured out how to do this inside of sympify.py. I can't import `Matrix` inside of sympify.py because the imports conflict each other. Doesn't work.

Maybe something like this can be done
``converter[np.ndarray] = lambda x: Matrix(x)``
and then we can type cast the result to a matrix this way
``return converter[cls]([sympify...and...so...on])``.
But the problem remains: can't get `Matrix` to work inside of sympify.py. 

@bjodah , Can you please suggest some way to make this work? Maybe my approach is altogether wrong. Do you suggest something different? Help me please.

**Comment by bjodah** [comment]
@tokencolour: Thanks for working on this! I will find some time later this weekend and get back to you.
