### ISSUE TITLE
solveset(sqrt(x), x, S.Complexes) don't return {0}

### ISSUE THREAD

**Issue by wxgeo** [sympy/sympy#10397]
In [12]: solveset(sqrt(x), x)
Out[12]: {x | x ∊ ℂ ∧ √x = 0}

Note that if x is real, solveset is able to find the solution.

In [13]: solveset(sqrt(x),x,S.Reals)
Out[13]: {0}

However, sqrt() is defined for non-reals too in sympy.

In [14]: sqrt(-1)
Out[14]: ⅈ

In [16]: sqrt(I)
Out[16]: 
4 ____
╲╱ -1 

So solveset(sqrt(x), x) should return 0 as solution even without assuming x is real.

**Comment by sampadsaha5** [comment]
If we use `solve()` instead of `solveset()`  we have 
```
In [4]: solve(sqrt(x), x)
Out[4]: [0]
```

**Comment by MSeeker** [comment]
The issue lies in how `solveset_complex` and `solveset_real` (both are underlying calls made by `solveset`) handles radicals differently. `solveset_real` directly inverts `sqrt(x) = g(y)` to `x = g(y)**2` (as can be seen in the implementation of `_invert_real`), while `solveset_complex` does not (probably due to the multi-valued nature of complex radicals). 
Instead, `solveset_complex` calls a subroutine `_solve_radical` whenever it detects the equation in question contains a rational power. However, it only checks the `args` of the equation, therefore `sqrt(x) - 1`, being `Add(Pow(Symbol('x'), Rational(1, 2)), Integer(-1))` internally, gets recognized and solved correctly, whereas `sqrt(x)` alone, being `Pow(Symbol('x'), Rational(1, 2))`, does not contain a rational power in either `Symbol('x')` or `Rational(1, 2)`, thus is not recognized.
Solution to this problem is simple: just add a test case for the whole equation for rational powers. I have already done a commit to address it.
Nevertheless, I believe the best way to solve this issue and improve `solveset`'s stability should be finding a way to implement a "inverse function" of sorts to complex radicals.

**Comment by aktech** [comment]
Closed via #10435
