### ISSUE TITLE
non-rational matrix powers

### ISSUE THREAD

**Issue by sn6uv** [sympy/sympy#10563]
There's some strange behaviour in the current master branch:

``` python
>>> sympy.__version__
'0.7.7.dev'
>>> A = Matrix(((0, sympy.Symbol('x')), (0, 0))
>>> A ^ sympy.Symbol('n')
Matrix([
[0**n, 0**(n - 1)*n*x],
[   0,           0**n]]
```

MMA for comparison:

``` mathematica
In[1]:= MatrixPower[{{0, x}, {0, 0}}, n]
Out[1]= {{DiscreteDelta[n], x KroneckerDelta[1 - n]}, {0, DiscreteDelta[n]}}
```

**Comment by jksuom** [comment]
For a singular matrix only positive integral powers are well defined. The given expression is valid for all positive integral values of ``n``. For other values an error is expected.

**Comment by sn6uv** [comment]
@jksuom What about `A^0 = I`?
The diagonal entries suggest this (although I'd argue it's unclear), but the off-diagonal isn't defined for `n = 0`.

**Comment by jksuom** [comment]
Powers of singular matrices should be computed with explicit numerical exponents: ``A**0``, ``A**1``, ``A**2``, etc. 

Symbolic powers are well defined only for non-singular matrices. The function computing those powers in SymPy does currently return a result also for singular matrices, but it is not guaranteed that substituting numeric values for ``n`` would necessarily succeed. 

If this becomes an issue, the function should probably be modified to return an error message in case of a singular matrix.

The MMA formula does not appear to solve this issue, since it is possible to get invalid results by substitution; for example, an inverse (``n = -1``) and a square root (``n = 1/2``), neither of which exists.

**Comment by sn6uv** [comment]
I agree, the MMA formula is not ideal either, but I think the `n=0` case is particularly important (e.g. transition/evolution matrices). 

If the formula is only valid for positive integers then can we simplify `0**n`, to `0` and `0**(n-1)` to `delta_1(n)`? I think using `0**(n-1)` for a delta seems like a bad idea.

How about returning a piecewise function if the matrix is singular; one result for positive integers, one for 0 (we could even collapse these cases), and indeterminate/undefined otherwise?

Related: is there interest more widely in implementing a functional calculus for matrices?

**Comment by jksuom** [comment]
>  I think using 0**(n-1) for a delta seems like a bad idea.

The function could probably be modified to return (Kronecker) deltas, but I'm not sure that it would be a good idea as it could allow the substitution of negative or non-integer exponents with no error message. 

> the n=0 case is particularly important

I think it has already been implemented for all (square)matrices.

**Comment by oscarbenjamin** [comment]
Looks like the power stays purely symbolic now until n is substituted for:
```
In [16]: A = Matrix(((0, x), (0, 0)))                                                                                                          

In [17]: A ** n                                                                                                                                
Out[17]: 
        n
⎛⎡0  x⎤⎞ 
⎜⎢    ⎥⎟ 
⎝⎣0  0⎦⎠ 

In [22]: (A**n).subs(n, 2)                                                                                                                     
Out[22]: 
        2
⎛⎡0  x⎤⎞ 
⎜⎢    ⎥⎟ 
⎝⎣0  0⎦⎠ 

In [23]: (A**n).subs(n, 2).doit()                                                                                                              
Out[23]: 
⎡0  0⎤
⎢    ⎥
⎣0  0⎦
```
So I guess this isn't an issue any more...
