### ISSUE TITLE
zeta(0, n) where n is negative is wrong

### ISSUE THREAD

**Issue by isuruf** [sympy/sympy#10592]
```Python
>>> n=sympy.Symbol("n", negative=True)
>>> sympy.zeta(0, n)
-n - 1/2
```
This should be `-n+1/2`

**Comment by AnishShah** [comment]
```
>>> from sympy import *
>>> n=Symbol("n", negative=True)
>>> zeta(0, -n)
n + 1/2
```

This is the output I got. I think `n + 0.5` is the correct answer.

**Comment by isuruf** [comment]
Sorry, updated the description

**Comment by jksuom** [comment]
This may be connected with https://groups.google.com/forum/#!topic/sympy/J2_bmBdisiU .

**Comment by vovapolu** [comment]
@isuruf I found this code in `zeta` class 
```
            elif z is S.Zero:
                if a.is_negative:
                    return S.Half - a - 1
                else:
                    return S.Half - a
```
I don't understrand why the result is `1/2 - a - 1` when a is negative, since [Wiki](https://en.wikipedia.org/wiki/Hurwitz_zeta_function) and [Wolfram Alpha](http://mathworld.wolfram.com/HurwitzZetaFunction.html) say that `zeta(0, a) = 1/2 - a` regardless of the sign of a. Is it a bug? I can make a pull-request for it.

**Comment by isuruf** [comment]
Please do and ping me
