### ISSUE TITLE
GitHub added issue template feature

### ISSUE THREAD

**Issue by debugger22** [sympy/sympy#10620]
e.g. https://github.com/dear-github/dear-github/issues/125

Should we have a not-so-strict issue template?

**Comment by asmeurer** [comment]
What would be in it? Most issues don't seem to be missing anything important.

**Comment by debugger22** [comment]
It'll be good to ask them to provide some code to reproduce the bug.

**Comment by rwst** [comment]
This works for PRs too using `pull_request_template.md`

**Comment by debugger22** [comment]
If we agree to have this, I can draft a PR for this. Let's close this if it's not a good idea.

**Comment by moorepants** [comment]
I think it is a good idea. We use a template in the PyDy project:

https://github.com/pydy/pydy/blob/master/CONTRIBUTING.rst

These checklists help us keep a certain standard for contributions. I like that it always reminds us to add something to the release notes, for example.

**Comment by asmeurer** [comment]
Is it possible to add text to the template that doesn't appear if the person leaves it there? If so, then we can probably do something useful here (one thing I think would be helpful would be to ask people to include a "Fixes #NNNN" in pull request descriptions). But if not, then I think the net result of this will be to make pull requests messier, because people will just leave the template there.  For issues, I can't really think of anything useful to put there. Most issues are reproducible just fine, in my experience.
