### ISSUE TITLE
inconsistency with x**(x/log(x))

### ISSUE THREAD

**Issue by rwst** [sympy/sympy#10676]
```
In [11]: 2**(2/log(2))
Out[11]:
 2
ℯ

In [12]: (-1)**(-1/log(-1))
Out[12]:
    ⅈ
    ─
    π
(-1)
```
I'm no calculus expert but pretty sure the latter is `e**(-1)`. So I think this is inconsistent.

**Comment by jksuom** [comment]
It seems that SymPy is generally very conservative with non-integer powers of negative (or complex) numbers, and leaves them unevaluated presumably because they are multi-valued.

**Comment by shivamtaji** [comment]
I think that the output is correct. 'log(z)' is undefined if z<0. But if 'z<0' then we can compute complex logarithm of 'z' which is Log(z)=log(r)+i*Q where z=r*(e**iQ).
Hence here first  log(-1) is computed which is log(1)+i*pi = i*pi . Which gives the same answer computed by sympy.

**Comment by SalilVishnuKapur** [comment]
@shivamtaji I totally agree with you
Though I have another way of expressing the same 
@rwst  I guess it is right the way it is because with logic that you are applying 
1. Inverse properties:   loga ax = x   and   a(loga x) = x
In this case 1/(log(-1)) != 1*(log-1(e))  as logrithmic base  value can never be less than 0
Please have a look at the below rule
2 logy(x)     where y>0

**Comment by rwst** [comment]
Closed as invalid. Thanks.
