### ISSUE TITLE
init_printing doesnt allow choosing of the latex printer in a standard python interpreter

### ISSUE THREAD

**Issue by jbm950** [sympy/sympy#10834]
There is no implementation of the use_latex flag in init_printing for the standard python interpreter. I am posting a pull request with the fix now.

**Comment by moorepants** [comment]
I think this is still valid. It would be nice to be able to set any arbitrary printer to work with init_printing(). For example, we have sympy.physics.vector.init_vprinting(). There could be lots of cases for this and if it was handled by the main init_printing() command instead of creating tons of custom ones, then I think that would be better.

**Comment by jbm950** [comment]
@moorepants A project write up of sorts for that can now be found at https://github.com/sympy/sympy/wiki/Allow-arbitrary-choice-of-printer-to-be-used-by-init_printing() in the wiki
