### ISSUE TITLE
sympy is  unable to solve limit for function log( x ) + asech( x ) at both point x = 0 and x = oo.

### ISSUE THREAD

**Issue by wrat** [sympy/sympy#10868]
while Calculating the limit of function  log(x)+asech(x) at two different point sympy gives unexpected result 

```
>>> limit(log(x)+asech(x),x,oo)
    ⅈ⋅π
∞ + ───
     2 
>>> limit(log(x)+asech(x),x,0)
 lim (log(x) + asech(x))
x─→0⁺                   
>>> 
```

I think that gruntz algorithm has problem while  calculating limit for  function whose two side limit is not exist .
Reference  -https://www.wolframalpha.com/input/i=limit+of+log%28x%29%2Basech%28x%29+where+x+tends+0

**Comment by Nitin216** [comment]
Hey wrat, do u want it to solve limit from right side by default or something else ??

**Comment by wrat** [comment]
yeah from any direction it not give correct answer.
if we solve limit(log(x)+asech(x),x,0,dir=' - ' ) then it show 
>>>  ∞ + ⅈ⋅π
which is also wrong . So there is bug in gruntz algorithm.

**Comment by Nitin216** [comment]
Got it.

**Comment by Nitin216** [comment]
Hey wrat, I think i got that asech(x) is not expanding right. I have already opened an issue #10885 and found the solution too.

**Comment by degeawapsh** [comment]
In the first  issue, we should have i+oo = oo but Sympy give the wrong result :
```
>>> I+oo 
∞ + ⅈ
```
It shows us that the bug is not by the limit function itself.
I'm new to this project, can anyone tell me where to fix this issue.

**Comment by Nitin216** [comment]
@degeawapsh Currently working on this issue.

**Comment by Nitin216** [comment]
@degeawapsh Sympy assumes ```oo``` as real number and ```I``` as Imaginary part. That is why it is doing so. If you want to see the difference see ```zoo + I```.

**Comment by anutosh491** [comment]
`oo.is_real `returns `False` so not sure if `oo` should be considered as a real number in the above case. Yeah the the issue doesn't seem to be fully related to series/limits as of now cause the second one has been addressed 
```
>>> limit(log(x) + asech(x) , x, 0) # oo is the correct answer
oo 
```
The first one needs decision regarding what could be done , otherwise the issue seems to have been addressed

**Comment by oscarbenjamin** [comment]
If you plot `log(x) + asech(x)` you can see that it does have a finite limit as x goes to zero from the right:
```python
In [19]: (asech(x)+log(x)).evalf(subs={x:0.00000001})
Out[19]: 0.693147180559945
```
The current result for that is incorrect:
```python
In [20]: limit(log(x)+asech(x),x,0)
Out[20]: ∞
```

**Comment by anutosh491** [comment]
Yupp, you're totally correct . I realized where I had gone . The correct answer is `log(2)` . Thanks for correcting me , gives me an issue to look into :)

**Comment by anutosh491** [comment]
Due to some reason we get ` [oo, zoo, zoo, nan, nan, nan]` , as the first 6 taylor terms for `asech(x)` , which is obviously not what we want( the following python list is being calculated in `_eval_nseries()` and it basically adds up these terms plus the order for the output) . Something like `[0, x, 0, -x**3/6, 0, 3*x**5/40]` as for `sinh(x)` is what we would like to have !

Calculating the series for the derivative and then integrating the power series gives us somewhat we would want
```
>>> (-1/(x*sqrt(1 - x**2))).series()
-1/x - x/2 - 3*x**3/8 - 5*x**5/16 + O(x**6)

>>> integrate(-1/x - x/2 - 3*x**3/8 - 5*x**5/16, x) # Obviously the + C constant here would be log(2)  
-5*x**6/96 - 3*x**4/32 - x**2/4 - log(x)            # which when added below would give us the result
```
So I think this should be done without much problem but I am somewhat stuck in how `_eval_nseries()` operates as this is my first time dealing with it . I can understand that the codeflow goes through `nseries()` of `core/expr.py` followed by `_eval_nseries()` of `core/functions.py` , multiple times one by one for `asech(x).series(x, 0, n=6)` but only uses `nseries()` for `(-1/(x*sqrt(1 - x**2))).series(x, 0, n=6)`.

I don't know why but this sets me off and I am not able to understand where the actual error would be . @jksuom I would be glad if you could maybe give me a small overview of how basically something like `f(x).series(x, 0, n, dir ='+')`  works in general and how does the code flow through functions overall before returning the output , would surely help me and other new comers for further issues too ! There is also a line for where this kind of evaluation starts 
(line 3001 of expr.py)
```
        # from here on it's x0=0 and dir='+' handling

        if x.is_positive is x.is_negative is None or x.is_Symbol is not True:
            # replace x with an x that has a positive assumption
```

**Comment by jksuom** [comment]
> where the actual error would be

Special functions are expected to have `_eval_nseries` and `_eval_as_leading_term` methods to take care of expansions at singular points (where the generic `Function._eval_nseries` does not suffice). Those methods should be added to `asech`. It seems that an attempt was made in that direction by creating  `asech.expansion_term` but that was not connected to the `nseries` code. I have not checked the code but at least its first term `log(2/x)` looks correct. It should be returned by `_eval_nseries` and `_eval_as_leading_term` in the form `log(2) - log(x)` to improve the chance that `log` terms coming from different parts of a sum would combine without the need to call special cancelling methods. It should also be noted that the (two first) arguments of `_eval_nseries` are `self` and `x` where `self` is `asech(z)` and `z` is a functions of `x`. So the expansion of `asech` is first obtained as a power series  in `z` and that has to be transformed to a series in `x`.

**Comment by anutosh491** [comment]
Thanks a lot for the help , will look into this and get back ! 

> It seems that an attempt was made in that direction by creating `asech.expansion_term` but that was not connected to the `nseries` code. I have not checked the code but at least its first term `log(2/x)` looks correct.

Ohh wasn't aware of this , If you have any idea where I could find that or where it has been listed let me know . Maybe that could give me a headstart as I'm working on this issue . Yeah `log(2/x)` is want we would want eventually !!
