### ISSUE TITLE
latex output for partial derivative to a power is wrong

### ISSUE THREAD

**Issue by ianhbell** [sympy/sympy#10926]
In sympy 1.0, this latex output is incorrect:
``` python
from __future__ import division
from sympy import *
from IPython.display import display, Math, Latex
from IPython.core.display import display_html
init_session(quiet=True)
init_printing()
x = symbols('x')
y = symbols('y', cls=Function, positive = True)(x)
diff(1/y,x,2)
```
![capture](https://cloud.githubusercontent.com/assets/11966765/14124475/ec66405e-f5c2-11e5-8c23-cf3d899000c3.PNG)

**Comment by ianhbell** [comment]
From 0.7.6 (correct):
![capture](https://cloud.githubusercontent.com/assets/11966765/14124537/4339379c-f5c3-11e5-822c-b78144c2b08a.PNG)

**Comment by gxyd** [comment]
@Upabjojr you may want to look at this. We introduced in [this commit](https://github.com/sympy/sympy/pull/10824/commits/47e5848e8ec97cf56dcb3e1df036aec8c513c28b) the line
```
not isinstance(item.doit(), Derivative)
```
which only fails [this test](https://github.com/sympy/sympy/blob/master/sympy/physics/vector/tests/test_printing.py#L132-L133) for derivative. Since derivative can also be represented using dot-notation. This dot-notation derivative doesn't necessarily require brackets around it, but the one using `d/dx` thing does require it.

**Comment by ianhbell** [comment]
Please fix this as soon as you can.  I'm stuck on 0.7.6.1 until this regression is repaired.

**Comment by Upabjojr** [comment]
Dot-notation representation of a derivative should be handled by a separate class. Using the same class was a poor design choice.

Pretty printer seems to work correctly, maybe try to debug the pretty printer and port the code to the latex printer?

**Comment by Upabjojr** [comment]
I think this is solved now.

**Comment by ianhbell** [comment]
Thank you!
