### ISSUE TITLE
Deprecated kanes_equation method

### ISSUE THREAD

**Issue by yidingjiang** [sympy/sympy#10945]
The kanes_equation() under KanesMethod will be deprecated for a more ideal api in which the order of argument is switched from (loads, body) to (body, load). The reasoning is that sometimes there is no load therefore it makes more sense to have the body first and have an optional load. For details please see #10878.

**Comment by jbm950** [comment]
The new argument order is now active and putting in the forcing list first raises the deprecation warning as desired. I'm confused though because the documentation does not reflect this change online (look for .kanes_equations() [here](http://docs.sympy.org/latest/modules/physics/mechanics/kane.html) and [here](http://docs.sympy.org/latest/modules/physics/mechanics/api/kane_lagrange.html)) Adding to the confusion though is looking in the source code you did make the correct alterations to reflect your change ([link](https://github.com/sympy/sympy/blob/master/doc/src/modules/physics/mechanics/kane.rst) and [link](https://github.com/sympy/sympy/blob/master/sympy/physics/mechanics/kane.py) are both correct) @moorepants  Why is the online documentation not reflecting the changes?

**Comment by moorepants** [comment]
The online docs do not reflect the change for one of two reasons:

1. You are looking at SymPy 1.0 docs and this is development.
2. The dev docs are updated manually and are not always in sync with the latest master.

**Comment by bjodah** [comment]
Since people will turn to this issue when upgrading SymPy I thought I could provide an easy snippet which should work both with SymPy v1.0 and later:
```
try:
    (fr, frstar) = KM.kanes_equations(bodies=BL, loads=FL)
except TypeError:
    (fr, frstar) = KM.kanes_equations(FL, BL)
```
