### ISSUE TITLE
acot(-x) evaluation

### ISSUE THREAD

**Issue by SteliosStefanatos** [sympy/sympy#10995]
In Sympy (ver. 1.0), the following input 

`var('x');
acot(-x)`

gives

> `-acot(x)`

which does not hold. (It actually holds  `acot(-x) = pi - acot(x)`.)

**Comment by leosartaj** [comment]
This appears valid. According to the wikipedia [article](https://en.wikipedia.org/wiki/Inverse_trigonometric_functions) it should be ``acot(-x) = pi - acot(x)``. @SteliosStefanatos, if you want you should go ahead and fix this. :smile:

**Comment by postvakje** [comment]
I guess it depends on how the principal branch of acot is defined.  In Wikipedia, the branch covering (0,pi) is used and thus `acot(-x) = pi - acot(x)`, but Mathematica uses the branch covering (-pi/2, pi/2) with a discontinuity at x = 0, so in that case `acot(-x) = -acot(x)`.

**Comment by gschintgen** [comment]
As explained by @postvakje there are two non-equivalent definitions for `acot`. SymPy's is aligned with DLMF and Mathematica. Since SymPy v1.5 this is properly (though tersely) documented in `acot`'s docstring:
https://github.com/sympy/sympy/blob/0639b9f7e59ed27d66bea89f4397500664975063/sympy/functions/elementary/trigonometric.py#L2563-L2564
https://docs.sympy.org/latest/modules/functions/elementary.html#acot

As a workaround, i.e. if you need the alternate definition, you may define
```
def acot2(x):
    return pi/2 - atan(x)
```
I'm closing this.
