### ISSUE TITLE
Solving equations with binomial coefficients should expand them first

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#10993]
When trying to solve an equation with a binomial coefficient with a symbol, the solver fails:

``` python
>>> solve(Eq(binomial(x, 3), 1000))
```

``` pytb
Traceback (most recent call last):
  File "<ipython-input-7-e56e9952e4b8>", line 1, in <module>
    solve(Eq(binomial(x, 3), 1000))
  File "sympy/solvers/solvers.py", line 1053, in solve
    solution = _solve(f[0], *symbols, **flags)
  File "sympy/solvers/solvers.py", line 1619, in _solve
    raise NotImplementedError('\n'.join([msg, not_impl_msg % f]))
NotImplementedError: 
No algorithms are implemented to solve equation binomial(x, 3) - 1000
```

But when expanding the binomial coefficient first, the solver succeeds:

``` python
>>> solve(Eq(binomial(x, 3).expand(func=True), 1000))[2].n()
19.1895499623678
```

Shouldn't the solver try to expand the binomial before failing?

**Comment by Shekharrajak** [comment]
I think it is expected because input for `solve` is : 
        - a single Expr or Poly that must be zero,
        - an Equality
        - a Relational expression or boolean
        - iterable of one or more of the above

**Comment by pelegm** [comment]
But `binomial` is nothing more than a polynomial, in fact. Shouldn't `solve` recognize it, and expand it instead of raising? That sounds easy enough...

**Comment by oscargus** [comment]
I think this makes sense. Could be worth noting that the current solution to the expanded equation is 
![image](https://user-images.githubusercontent.com/8114497/62460556-9a11cc80-b782-11e9-83e0-7e1b90c0c1a2.png)

Maybe one should add a list of functions that can be rewritten as polynomials and do that for instances of functions that are not solvable otherwise? (It turns out that there is no `_eval_rewrite_as_polynomial` for `binomial`, so that must be added, probably just `return self._eval_expand_func()`.)

**Comment by Alchemist98** [comment]
i want to work on this issue can anyone give me some input since i am new to this community

**Comment by mijo2** [comment]
@sylee957 @asmeurer I would like to take up this issue if no fix has been made for it.
