### ISSUE TITLE
[tensor module] incorrect evaluation of TensAdd.data

### ISSUE THREAD

**Issue by vasdommes** [sympy/sympy#11020]
The code below gives a simple example when TensAdd.data is evaluated incorrectly.
`add_1` and `add_2` are equivalent expressions, both must be equal to zero.

```python
from sympy.tensor.tensor import *
Lorentz = TensorIndexType('Lorentz', metric=False, dummy_fmt='i', dim=2)
Lorentz.data = [-1,1]

a, b, c, d = tensor_indices('a, b, c, d', Lorentz)
i_0, i_1 = tensor_indices('i_0:2', Lorentz)

Vec = TensorType([Lorentz],tensorsymmetry([1]))
S2 = TensorType([Lorentz]*2, tensorsymmetry([1]*2))

# metric tensor
g = S2('g')
g.data = Lorentz.data

u = Vec('u')
u.data = [1, 0]

# must be zero:
add_1 = g(b,c)*g(d,i0)*u(-i0) - g(b,c)*u(d)
add_1.data
# [[[0, 0], [0, 0]], [[0, 0], [0, 0]]]

# OK, that was fine.
# Now let us replace index `d` with `a`:
add_2 = g(b,c)*g(a,i0)*u(-i0) - g(b,c)*u(a)
add_2.data
# [[[0, 0], [0, 1]], [[0, 0], [-1, 0]]]
```

The cause of problem: after canonicalization free indices in first and second argument of `add_2` are stored in different order (`a, b, c` and `b, c, a`, respectively):
```python
add_2.args
# (g(a, i_0)*g(b, c)*u(-i_0), -g(b, c)*u(a))
```

**Comment by vasdommes** [comment]
@Upabjojr is it bug of `TensMul.canon_bp()` or `_TensorDataLazyEvaluator._get()`?

**Comment by Upabjojr** [comment]
I think the problem is the wrong summation: components of tensors in TensAdd are evaluated separately on each arguments, then naively summed.

Of course, in this way the the wrong components are summed, for example the component indexed by [0, 1, 1] in `a,b,c` should be summed with component indexed by [1, 1, 0] in `b,c,a`.

That is, it should be like:
```
  D     D     D                              
 ___   ___   ___                             
 ╲     ╲     ╲                               
  ╲     ╲     ╲   (C1[i, j, k] + C2[j, k, i])
  ╱     ╱     ╱                              
 ╱     ╱     ╱                               
 ‾‾‾   ‾‾‾   ‾‾‾                             
k = 0 j = 0 i = 0  
```
where _C1_ and _C2_ are the arrays of the arguments.

If I remember correctly, the code simply sums the _numpy_ arrays, therefore getting something equivalent to:
```
  D     D     D                              
 ___   ___   ___                             
 ╲     ╲     ╲                               
  ╲     ╲     ╲   (C1[i, j, k] + C2[i, j, k])
  ╱     ╱     ╱                              
 ╱     ╱     ╱                               
 ‾‾‾   ‾‾‾   ‾‾‾                             
k = 0 j = 0 i = 0  
```
That is, the order of indices in the arguments of _TensAdd_ is kept fixed.

This problem is related to a bigger one: how do you define the free index order of a _TensAdd_ object? Unlike for _TensMul_, it's undefined. A quick idea would be to force to use the lexicographical order of free indices.

In the future, we expect this problem to be extended to _TensMul_, as one may wish to represent unexpanded expressions, like, for example: `A(i) * ( B(j,k) + C(k, j) )`. This is a _TensMul_ containing a _TensAdd_. Currently such expressions get expanded to a _TensAdd_.

**Comment by Upabjojr** [comment]
Numpy has some functions that could help solve this problem:

* http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.swapaxes.html
* http://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.rollaxis.html

To determine an unambiguous order for indices, I'd suggest to use:
`sort( ... , key=default_sort_key)`
with `default_sort_key` being defined somewhere in SymPy.

**Comment by vasdommes** [comment]
@Upabjojr I tried to fix this issue without any major changes, see PR#11037

**Comment by vasdommes** [comment]
@Upabjojr I opened issue #11039 for discussion of free index ordering problem.
