### ISSUE TITLE
1-1.1+0.1=−8.32667268468867^10−17?

### ISSUE THREAD

**Issue by michaeldongyuxi** [sympy/sympy#11051]
So when I input 1-1.1+0.1, the output is −8.32667268468867^10−17

**Comment by asmeurer** [comment]
Yep, that's how Python floats (i.e., IEEE-784 floats) work. See https://docs.python.org/3.5/tutorial/floatingpoint.html.

The expression `1-1.1+0.1` is evaluated entirely by Python. To use SymPy Floats, use `Float("1") - Float("1.1") + Float("0.1")`. This still gives the same result, because of the same issues, but you can know that since the default precision is 15, a value of 1e-17 is small enough to be considered 0. If you're concerned about these issues, you can use the Decimal class in Python (see the above link). Unfortunately, SymPy does not have a Decimal class.

**Comment by asmeurer** [comment]
Or use SymPy Rational numbers,

```
In [25]: Rational("1") - Rational("1.1") + Rational("0.1")
Out[25]: 0

```
