### ISSUE TITLE
sympify (evaluate = False) gives unexpected result

### ISSUE THREAD

**Issue by XiaoranJin** [sympy/sympy#11095]
`>>> sympify('2**2 + 2010*2012', evaluate = False)`
`2**2 + 2010*2012`

`>>> sympify('2**2 - 2010*2012', evaluate = False)`
`-4044120 + 2**2`

It seems there are some issues with "-" operator.

**Comment by parsoyaarihant** [comment]
I would like to work on this issue. Any tips are welcome :)

**Comment by Nitin216** [comment]
Expression ```2010*2012``` is when passed to ```_neg``` in ```expr.py``` then it does not pass evaluate to the ```func_wrapper.py```. That it why it is evaluating. I am not able to find a workaround.

**Comment by jashan498** [comment]
This solves the issue:
```
diff --git a/sympy/core/expr.py b/sympy/core/expr.py
index 421e6cd..b0ecfeb 100644
--- a/sympy/core/expr.py
+++ b/sympy/core/expr.py
@@ -108,7 +108,11 @@ def __pos__(self):
         return self
 
     def __neg__(self):
-        return Mul(S.NegativeOne, self)
+        from sympy import Symbol
+        if len(self.atoms(Symbol)) == 0:
+            return Mul(S.NegativeOne, self, evaluate=False)
+        else:
+            return Mul(S.NegativeOne, self)
 
     def __abs__(self):
         from sympy import Abs
```
But its kinda scary to make changes in this module as it touches the whole code base.

The reason the above change work is, though for `negative` integer `S(2010*2012, evaluate=False)` was passed in `__neg__` but the `Mul` inside it transformed it to `-4044120` because of missing flag. So, I added the `evaluate=False` flag there.
The reason for `if` condition is just to eliminate the following non-stop recursion inside assumption module:
```
  File "sympy/core/assumptions.py", line 303, in _ask
    _ask(pk, obj)
  File "sympy/core/assumptions.py", line 291, in _ask
    a = evaluate(obj)
```
for few cases like: `-1 - 2*(-(-x + 1/x)/(x*(x - 1/x)**2) - 1/(x*(x - 1/x)))`, though the result was obtainable if we first evaluate `2*(-(-x + 1/x)/(x*(x - 1/x)**2) - 1/(x*(x - 1/x)))` and then afterward the former one(Maybe because `Mul` cache the results). After this `if` block all test cases of `test_sympify` got passed (with a few exceptions in other core file tests).

So should I go further in this direction to solve the remaining exceptions and create a patch or leave this idea because this can affect the whole codebase?
ping @smichr @asmeurer @jksuom

**Comment by asmeurer** [comment]
You are right to be wary about making changes to the core. Is it possible to fix this in the parser?

**Comment by jashan498** [comment]
Oh instead looking for  '(53, '-')' inside tokens, why not just separate expressions with string manipulation before this [line](https://github.com/sympy/sympy/blob/2c0a3a103baa547de12e332382d44ee3733d485f/sympy/parsing/sympy_parser.py#L947). The only condition is to break the expression before calling of [eval](https://github.com/sympy/sympy/blob/2c0a3a103baa547de12e332382d44ee3733d485f/sympy/parsing/sympy_parser.py#L862) because it is the place which initiates formation of  `Mul` object.
But again this involves more changes than the simpler(but scarier) `evaluate=False` thing.

**Comment by asmeurer** [comment]
Is it not possible to fix this in the EvaluateFalseTransformer? I'm unclear what the exact issue is here.

**Comment by jashan498** [comment]
Oh, I completely ignored that possibility (i pre-assumed it has to do with `__neg__` because it was most visible diverging behaviour between positive and negative integers `Mul`). 
I will try to understand `compile` and `eval` more deeply and see if there is a workaround.
