### ISSUE TITLE
fps should print as a formal power series

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11102]
When I first used `fps`, I didn't realize it really was a formal power series as it claims to be, because it prints like a normal series (same as `series`)

```
In [21]: fps(sin(x))
Out[21]:
     3     5
    x     x     ⎛ 6⎞
x - ── + ─── + O⎝x ⎠
    6    120
```

But if you look at the string form, you see

```
In [22]: print(fps(sin(x)))
FormalPowerSeries(sin(x), x, 0, 1, (SeqFormula(Piecewise(((-1/4)**(_k/2 - 1/2)/(RisingFactorial(3/2, _k/2 - 1/2)*factorial(_k/2 - 1/2)), Eq(Mod(_k, 2), 1)), (0, True)), (_k, 2, oo)), SeqFormula(x**_k, (_k, 0, oo)), x))
```

That is, it really does represent it as the formula `Sum((-1)**n/factorial(2*n + 1)*x**n, (n, 0, oo))` (albiet, not simplified). It out to print it like this, so you can see that that's what it's working with.

Side question: if you enter something it can't compute, it just returns the function

```
In [25]: fps(tan(x))
Out[25]: tan(x)
```

Is that intentional? It seems like it ought to raise an exception in that case. 

@leosartaj

**Comment by leosartaj** [comment]
> That is, it really does represent it as the formula Sum((-1)**n/factorial(2*n + 1)*x**n, (n, 0, oo)) (albiet, not simplified). It out to print it like this, so you can see that that's what it's working with.

I got to admit that not much discussion was done on the printing aspect of Formal Power Series.  When I first wrote the code, I tried to keep it as similar as possible to what series has to offer. Since, Formal Power Series is all about a formula computed for the series expansion, I guess this is a good idea. +1

> Side question: if you enter something it can't compute, it just returns the function

> In [25]: fps(tan(x))
> Out[25]: tan(x)
> Is that intentional? It seems like it ought to raise an exception in that case.

This is again similar to what series does. Return it in the original form, if it's unable to compute the expansion. 

```
>>> series(log(x))
log(x)
```

If we want to raise an exception, the inability to compute can be from various reasons:

1. This is simply not covered by the algorithm.
2. SymPy does not have the required capabilities(eg. we need to construct a differential equation as part of the algorithm).
3. There is some bug in the code (that can be fixed ofcourse).

I am not sure here. Should we raise an exception or keep it just like ``series``?

**Comment by asmeurer** [comment]
I guess it depends on what the use-cases for fps are.  FWIW, I think series returning expressions unchanged is not so great either (but that's somewhat part of a bigger problem, where the type of series produced by `series` is not very well-defined).
