### ISSUE TITLE
relation between is_positive and is_nonpositive

### ISSUE THREAD

**Issue by parsoyaarihant** [sympy/sympy#11127]
I ran the following code : 

>>> from sympy import *
>>> x = Symbol('x', positive = False)
>>> print(x.is_positive)
False
>>> print(x.is_nonpositive)
None
>>> 

shouldnt `x.is_nonpositive = True`?

**Comment by gxyd** [comment]
May be this is not an issue. Symbols are dealt with in `complex plane` not in `real line` by default in SymPy. Since if `positive=False`, that doesn't mean `x` lies in the real-line.
For ex.
```
>>> (4 + I).is_positive
False
```
but does that mean `(4 + I).is_nonpositive` return `True`? Infact it doesn't
```
>>> (4 + I).is_nonpositive
False
```
TLDR; `positive=False` doesn't make it to lie in the real-line, it still can be a non-real, complex-number.

**Comment by parsoyaarihant** [comment]
@gxyd, thanks.
