### ISSUE TITLE
Different result of limit after simplify

### ISSUE THREAD

**Issue by jbrea** [sympy/sympy#11526]
Hi

I just stumbled over the surprising result that the limit function
returns a different result if I apply simplify to the argument.
The full example is here:

$ python
Python 3.5.2 (default, Jun 28 2016, 08:46:01) 
[GCC 6.1.1 20160602] on linux
Type "help", "copyright", "credits" or "license" for more information.

> > > import sympy
> > > print(sympy.**version**)
> > > 1.0
> > > from sympy import *
> > > tau, J, v0, theta = symbols('tau J v0 theta')
> > > df = diff(1/(tau_log((J-v0)/(J-theta))), J)
> > > limit(df, J, oo)
> > > -1/(tau_v0)
> > > limit(simplify(df), J, oo)
> > > -1/(-tau_theta + tau_v0)

The second result (after applying the simplification) is correct.
The first one isn't.

**Comment by jksuom** [comment]
The same phenomenon is visible in this part of the computation (where `1/J` is written for `J` in order to have the limit `J -> 0` instead of `J -> oo`):
```
>>> e = log((1/J - v0)/(1/J - theta))
>>> e.as_leading_term(J)
-J*v0
>>> e.series(J, n=2)
J*(theta - v0) + O(J**2)
```
The reason for the difference in the leading terms is [this line](https://github.com/sympy/sympy/blob/master/sympy/core/add.py#L794)
```
    expr = expr.func(*[t.as_leading_term(x) for t in expr.args]).removeO()
```
If some of the leading terms in a sum cancel each other, it is necessary to consider higher order terms.

**Comment by Smit-create** [comment]
Currently on master:
```
>>> from sympy import *
>>> tau, J, v0, theta = symbols('tau J v0 theta')
>>> df = diff(1/(tau*log((J-v0)/(J-theta))), J)
>>> limit(df, J, oo)
-1/(-tau*theta + tau*v0)
>>> limit(simplify(df), J, oo)
-1/(-tau*theta + tau*v0)
>>> limit(simplify(df), J, oo) == limit(df, J, oo)
True
```
@jksuom  Is this fixed?

**Comment by jksuom** [comment]
I think so. Closing.
