### ISSUE TITLE
simplification of binomial (0,m) gives 0

### ISSUE THREAD

**Issue by mzaffalon** [sympy/sympy#11548]
If `m = symbols("m", integer=True)`, the simplification of the binomial `simplify(binomial(0,m))` return 0, which is not correct when `m=0`.

This is for SymPy 1.0 (Python 3.5.2-64-bit) installed via Anaconda 3.

**Comment by ppeluso** [comment]
I believe this has to do with the idea that when using  `binomial(n,k)`, no matter what n is if k is a negative value it will always return 0. I think in your case because m is not assigned a value it will automatically return 0. If you set m equal to 0 and run `simplify(binomial(0,m))` it will return 1.

**Comment by mzaffalon** [comment]
I was not aware of the definition for negative values of `k`.

It is unlikely that I am able to make a PR, but I would like to give it a try this weekend.

**Comment by devangkulshreshtha** [comment]
@mzaffalon do you want that the expression simplify(binomial(0,m)) should be left as it is or we should print answer for both cases(m=0 and general case) ?

**Comment by kyleabeauchamp** [comment]
I am seeing a more general error here:


```
>>> simplify(binomial(2, x))
0
```

**Comment by kyleabeauchamp** [comment]
Ping: can anyone else confirm / deny this one?

**Comment by mzaffalon** [comment]
I get your same result on sympy 1.0 and Python 3.5.
