### ISSUE TITLE
Incorrect input of Rationals

### ISSUE THREAD

**Issue by ArifAhmed1995** [sympy/sympy#11606]
I recently updated my local repository using `git pull origin master` (git remote is set correctly) and found out that Rationals are being typecast to Integer.

```
>>> 1/2
0
>>> 3/5
0
>>> 7/8
0
>>> 7/3
2
>>> 7/4
1
>>> type(6/3)
<type 'int'>
>>> type(1/2)
<type 'int'>

```

To be sure that this is an issue , I re-cloned the sympy repo into another folder and installed it by `sudo ./setup.py install`.Still the problem persists.Can anyone check if same is happening after a recent pull from the main repository ?

**Comment by asmeurer** [comment]
This is the expected behavior. In Python 2, integer/integer performs integer division. In Python 3, or in Python 2 when using `from __future__ import division`, integer/integer produces a float. 

If you want a rational, you have to explicitly use a SymPy type, like `Rational(1, 2)` or `S(1)/2`. See http://docs.sympy.org/latest/tutorial/gotchas.html#two-final-notes-and. I would recommend using Python 3 to avoid this gotcha.

**Comment by ArifAhmed1995** [comment]
Ah ! I had gone through the tutorial earlier,but forgot some parts of it.
