### ISSUE TITLE
S("2.1") == Rational("2.1") is True??

### ISSUE THREAD

**Issue by latot** [sympy/sympy#11703]
Hi, this is little weird:

```
>>> a=S("2.1")
>>> b=Rational("2.1")
>>> N(a, 100)
2.100000000000000088817841970012523233890533447265625000000000000000000000000000000000000000000000000
>>> N(b, 100)
2.100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
>>> a==b
True
```

only in case, as vpa shows, a don't is equal to b.
and this issue only happen with decimal expressions (in strings)

Thx. Cya.

**Comment by b-mcg** [comment]
S("2.1") creates a float which on my system has a precision of 53 which gives 15 digits.  When you call N(a, 100), you're asking for 100 digits which is why a is almost but not exactly correct.  Rational("2.1") creates an arbitrary precision Rational.  However, when you try to equate the two, Rational's _eq_ method is called which will set its precision to that of the float's.  Therefore, if both have the same precision it makes sense that a == b would return true in this case.  I may be wrong but I don't think this is wrong or incorrect behavior, just something that one needs to be aware of.

**Comment by asmeurer** [comment]
N(a, 100) creates a new Float, which has higher precision:

```
In [9]: a._prec
Out[9]: 53

In [10]: N(a, 100)._prec
Out[10]: 336
```

With that being said, I think there really are some inconsistencies here, but maybe not in the parts you showed. Consider this:

```
In [15]: a == N(b, 100)
Out[15]: False

In [16]: a == b == N(b, 100)
Out[16]: True
```

This shows that float equality is not transitive. `a == b` and `b == N(b, 100)` does not imply `a == N(b, 100)`.  This isn't the only issue with float inequality (https://github.com/sympy/sympy/issues/11707). 

The only way I'm seeing right now to fix these issues is to make floats not compare equal to rationals (or even to other floats with differing precision). But that would likely have far reaching consequences.

**Comment by latot** [comment]
mm, i think we can complement this to have a solution, basically if don't exist an easy fix to compare floats with rational if change the ```S()``` behavior, the idea is lock the comparison of it, and ```S('2.1')``` and  ```S('a*2.1')``` change automatically the decimals numbers to rationals.

Thx. Cya.

**Comment by asmeurer** [comment]
I'm having a hard time understanding exactly what you are saying, but if your suggestion is to make `S("2.1")` return `Rational(21, 10)`, then I think that's a bad idea.

**Comment by latot** [comment]
you understand it correctly, why its a bad idea? (sorry my bad english)

**Comment by asmeurer** [comment]
Just changing sympify doesn't solve the problem (you can still create floats in other ways). The only way it would really solve the problem would be to abolish Float entirely, which would be throwing the baby out with the bath water.

**Comment by latot** [comment]
mm, its a nice point, i think can help in some way but is true don't is a full fix.

**Comment by latot** [comment]
mm, following your idea, if add to the overload of the equal operator something like:
```a == b and hash(a) == hash(b)``` in the return?

**Comment by asmeurer** [comment]
hash(a) == hash(b) need not imply that a == b. Hash collisions are a thing.

**Comment by latot** [comment]
yes, for that reason there is a ```and``` between them.

**Comment by latot** [comment]
its like ```equal(a, b) and hash(a) == hash(b)``` where ```equal``` is the actual function of equality.

**Comment by asmeurer** [comment]
I see. That would amount to making all floats unequal unless they are exactly equal, which would solve the problem, but I suspect there would be side effects. Perhaps we should try implementing this and seeing what breaks.

**Comment by asmeurer** [comment]
This is (I believe) causing some weird issues with sorting floats. Consider the list:

```
l = [(Float('24.1454875779948820074788389252614', prec=30), Float('-13.1582418989054347999595912958504', prec=30)), (Float('24.1454875779948820074788389252614', prec=30), Float('13.1582418989054347999595912958504', prec=30)), (Float('28.4521313273431079524044764152852', prec=30), Float('7.1703413201558995749722843378984', prec=30)), (Float('28.4521313273431079524044764152884', prec=30), Float('-7.1703413201558995749722843378984', prec=30)), (Float('31.5670599860997325327818666439086', prec=30), Float('1.90549903904895421957436782713519', prec=30)), (Float('31.5670599860997325327818666439118', prec=30), Float('-1.90549903904895421957436782713282', prec=30)), (Float('38.8003048980934470143630470183736', prec=30), Integer(0)), (Float('49.9555912252305458523368277388682', prec=30), Integer(0)), (Float('67.4737936805977347477762255542516', prec=30), Integer(0)), (Float('97.7033084414679285270485154328518', prec=30), Integer(0)), (Float('157.22232009811315861177865077252', prec=30), Integer(0)), (Float('301.666990999879310674379383943103', prec=30), Integer(0)), (Float('825.739370900114745676469382669325', prec=30), Integer(0)), (Float('7376.14675855787164513195172456891', prec=30), Integer(0))]
```

We have

```
>>> l == sorted(l)
True
>>> l[2] <= l[3]
False
```

I'm not entirely sure what is going on here, but I noticed this:

```
>>> l[0][0] == l[1][0]
True
>>> l[1][0] <= l[1][0]
False
```

The [docs](https://docs.python.org/3.6/howto/sorting.html#odd-and-ends) for `sorted` say that it uses `<` only, so I'm unsure exactly if this is the source of the problem. But I do think that Floats should compare equal only when they are exactly equal (probably we have to ignore precision, because of things discussed at #11707), just like `float`.

**Comment by asmeurer** [comment]
This issue is so closely intertwined with https://github.com/sympy/sympy/issues/11707 I feel it is cleaner to just merge the two. There are strictly speaking three distinct issues (note below, Rational includes Integer as a special-case):

a. SymPy Float equality doesn't match its hashing
b. SymPy Floats and Rationals that are only approximately equal compare equal with `==`
c. SymPy Float hashing doesn't match Python float hashing

But any change to one has implications to the others, and also to other issues such as:

1. Should exactly equal SymPy Floats and SymPy Rationals compare equal (as Python's float and int do)? Currently they do.
2. Should Floats with different precisions compare unequal (even if they are exactly equal as rational numbers)?  Currently they do. But note that both this and the previous question being yes leads to inconsistencies.
3. Should SymPy Floats and/or Rationals always compare equal to their Python counterparts of the same type (Float == float, Integer == int)? 
4. Should SymPy Floats and/or Rationals always compare equal to their Python counterparts of different type (Float == int)? Note that yes here implies yes questions 1 and no to question 2, since Python types compare by numeric value only.

My proposed solution https://github.com/sympy/sympy/issues/11707#issuecomment-289592289, has 

1. No
2. Yes
3. Yes, for Floats with the default precision, no for Floats with non-default precision
4. No

And solves a, b, and c by 

a. `x == y` always implies `hash(x) == hash(y)`. This works even across SymPy/Python types because Rationals and Floats with the default precision will hash using Python's algorithm.
b. Floats and Rationals are never equal. Floats with different precisions are never equal (they may still hash the same, but hash collisions are not a big issue).
c. We use the Python hashing for Floats with default precision and Rationals.
