### ISSUE TITLE
S("float") interpret string as real float

### ISSUE THREAD

**Issue by latot** [sympy/sympy#11708]
Hi all, well, first to aclare this, this behavior is fine:

``` python
>>> N(S(2.1), 100)
2.100000000000000088817841970012523233890533447265625000000000000000000000000000000000000000000000000
>>> N(Rational(2.1), 100)
2.100000000000000088817841970012523233890533447265625000000000000000000000000000000000000000000000000
```

we are using floats so all fine, but now:

``` python
>>> N(S("2.1"), 100)
2.100000000000000088817841970012523233890533447265625000000000000000000000000000000000000000000000000
>>> N(Rational("2.1"), 100)
2.100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

as you can see Rational returns correctly the string to number, but in the S case interpret it as float.

Only as a note, should be ideal `S('2.1*a')` transform the `2.1` to rational and then multiply with the a symbol..

Thx. Cya.

**Comment by asmeurer** [comment]
I don't see the issue here. This is all expected behavior. S("2.1") creates Float("2.1") with the default precision (15). Rational("2.1") creates an exact rational number (21/10). If you want to create a float with higher precision you should use Float("2.1", 100). Perhaps it would be useful to you if sympify had a flag to control the precision of floats?

**Comment by latot** [comment]
Hi, i'll try explain this, and from this issue https://github.com/sympy/sympy/issues/11704 here, because have the same argument, basically its a concept of CAS and expected behavior, first examples of rational:
```
>>> N(Rational(2.1), 100)
2.100000000000000088817841970012523233890533447265625000000000000000000000000000000000000000000000000
>>> N(Rational("2.1"), 100)
2.100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```
Interpreting in this context, if you send to a CAS a float should it works with it, its assumed the user don't care the minimal lost precision, but in the second example, the string represent an exact number, so the expected behavior is return the best precision of it, and this case is the exact rational, here all fine, and is part of the logic and interpretation of float/string.
The conflict is when you change this concept in the sympify function, if you send to it a float there is no problem, but if you send a string i think is expected return the best approximation of it in a CAS because you are sending an exact expression (not like float), so in this case i think it should return a Rational.
This is my interpretation, and a little out of it, is little confuse don't use the same behavior and concept in the input functions user data of Sympy (functions like Rational, or sympify have the function to insert data of the user to this system).

A little question, why sympify use Float to interpret strings in this context?

Thx. Cya.

**Comment by latot** [comment]
I search in the doc: http://docs.sympy.org/dev/modules/core.html but i can't found if it says sympify use an approximation, so i think the logic has some sense.

**Comment by asmeurer** [comment]
I don't buy the argument that just because `Rational` returns a rational then so should `sympify`. You could just as well say that `S()` and `Float()` should return the same thing. I would expect passing a string to the the type constructors (`Float('2.1')`, `Rational('2.1')`) to convert it to that type. I don't think it has any interplay on what `sympify` does. 

`sympify('2.1')` returns a Float because 2.1 is in floating point notation. I think perhaps what you are really asking for here is a SymPy implementation of `Decimal`, which can represent base-10 floating point numbers exactly. This would differ from `Rational` in that it would have a fixed precision, much like `Float` (`Float` is like a base-2 version of `Decimal`). So for instance `Decimal('1e20') - Decimal('1e-20')` would produce a result different from `Decimal('100000000000000000000.00000000000000000001')` because of loss of precision. 

That is to say, there's an important distinction here between exact representation and exact arithmetic. You can't exactly represent some finite base-10 decimals as finite base-2 floats because their expansions repeat in base-2 (like `0.1` = `0b0.0001100110011001100110011001100110011001100110011...`). But a decimal representation (`integer*10^exp`) can represent any finite base-10 decimal exactly. For arithmetic, however, any fixed precision floating point representation will lose accuracy (SymPy/mpmath uses arbitrary precision, but it's fixed for each float). The problem with rational numbers, which do not lose accuracy for basic arithmetic, is that the required accuracy grows and grows with every operation (i.e., the size of the numerator and denominator). And obviously as soon as you get an irrational number you can only represent things exactly symbolically. 

So I think it would be a bad idea to make `sympify('2.1')` be the same as `nsimplify('2.1')` (although I'm not opposed to an optional flag to make it work that way). I've actually been interested in seeing a Decimal class. The problem is that all the floating point math is implemented in mpmath and uses a binary floating point representation. Would there be any value to having a `Decimal` class if we just convert it to `Float` to do any arithmetic? Also, decimal arithmetic would be slower than binary floating point arithmetic (at least I'm assuming, but maybe it doesn't matter so much for arbitrary precision math. We should test this).

**Comment by latot** [comment]
Hi, mmm, about the rational argument, is in a context, i know only thinking in it don't have to much sense, but in a precision CAS context is other thing, that point is the base of what i wrote.
To take a middle point, i think your idea of a flag to set the precision is nice, i'm imagining like:
```
S(".2", prec=10)
0.2000000000
S(".2", prec=oo) ##same as S("0.2", rational=True)
1/5
```
Now one of the main conflict points, what should be the default value of precision?, i think we can change this question to, What precision you expect Sympy should works be default?, obvs this question don't is limited to sympify, should be a base of expected behaviors of Sympy.
In my case i expect the best precision possible (a symbolic expression).

Now, remains how the user need interpret the string inputs?, this concept seems mixed in Sympy, and this have a meaning base in python or normal languages, normally the numbers in this context are represented with the type, 2.1 is a float, "2.1" is a string, so normally what is the difference?, the float represent an approximation of the number while the string normally represent a literal expression, opposite to the float expression the string don't have any variation, this is important to know because its a base of the expected for the user (this is why i can expect a symbolic return from sympify with a string input).
Obvs if your intention is work with symbolic expression you can expect big numerators and similars.
So backing to the question, what do you want to represent strings in Sympy?

Other approach to this can be make a new section in Sympy to can select a base config to work.

Sadly i can't use nsimplify, because i need interpret Sympy expressions too, like ```S("Symbol(a)")```, i can't control the input data and is mixed, i think i can open a new issue for this.

**Comment by smichr** [comment]
`sympify` allows you to select the type of the output based on the type of the string input:
```python
>>> S('2.1').is_Float
True
>>> S('21/10').is_Rational
True
```
If you want to have '2.1' become rational, pass the `rational=True` keyword:
```
>>> S('2.1', rational=True)
21/10
```
To evaluate all numbers to a given precision (post-sympify) you can use `nfloat` or `.evalf`.
