### ISSUE TITLE
ccode: allow printing rationals without L

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#11803]
See https://stackoverflow.com/questions/40391602/sympy-ccode-number-type. ccode prints rationals like `1.0L/2.0L`, but this can cause problems std::complex in C++. Why is L used at all? We should add an option to disable it, at any rate.

**Comment by Lakshya1605** [comment]
I would like to work on this issue could you please help me to get started

**Comment by SatyaPrakashDwibedi** [comment]
@asmeurer I went through the https://stackoverflow.com/questions/40391602/sympy-ccode-number-type should I add the class and function as you mentioned there.

**Comment by asmeurer** [comment]
The custom subclass is a workaround for users. To fix this in SymPy, we should add an option to disable it (or remove it entirely, if it is not actually needed, which I'm unclear about).

**Comment by SatyaPrakashDwibedi** [comment]
@asmeurer I think we should add an option

**Comment by SatyaPrakashDwibedi** [comment]
@asmeurer L is used because it is of the long type in C which is of max. size so it can handle up to max precision and as you mentioned that it may cause an error in `std:: complex` in C++, but `Language 'C++' is not supported.`. If you would like to make it compatible with C++ then we should define data types and let the user pass it as a flag.
Would that work?

**Comment by asmeurer** [comment]
We now have a separate C++ printer, so we should C++ specific things in there.

**Comment by bjodah** [comment]
Old behaviour:
```
>>> ccode(Rational(1,3))
1.0/3.0
```
And this is our new behaviour:
```
>>> ccode(Rational(1,3), type_aliases={real: float80})
1.0L/3.0L
```
closing this for now.
