### ISSUE TITLE
integration can take a _long_ time (possibly forever)

### ISSUE THREAD

**Issue by lxkain** [sympy/sympy#11856]
Hello,

When I do

```
t = symbols('t', real=True)
def nsinc(t):
    "normalized sinc function"
    return sinc(pi * t)

nsinc(t).integrate()
```

the process either takes a long time, or doesn't return.

**Comment by asmeurer** [comment]
It's (unsurprisingly) stuck in the heurisch algorithm.

**Comment by rohitrango** [comment]
This looks like a good start for something a little more advanced. I have fixed a few easy bugs but I don't feel that I have understood how SymPy works yet. Where should I start to fix this issue (and start learning more about the functioning of the framework) ?

**Comment by jksuom** [comment]
The `integrals` module makes use of several integrators which are suited for different kinds of integrands. `nsinc` can be integrated by `meijerint`, which can be seen by setting the keyword `meijerg`:
```
 In [23]: nsinc(t).integrate(meijerg=True)
Out[23]: 
Si(π⋅t)
───────
   π 
```
The integration takes a long time because `heurisch` is attempted before `meijerint` in the current implementation. (The extra `pi` in the normalized `sinc` function makes `heurisch` particularly sluggish since it then reverts to using polynomial algebra in the very slow expression domain `EX`. Integrating the unnormalized `sinc` only takes a reasonable time.)

**Comment by asmeurer** [comment]
I seem to remember that there was a good reason for it, but why is heurisch tried before meijerg? Heurisch is the slowest and hence ought to be tried last.

**Comment by rohitrango** [comment]
So, should the ordering of the algorithms be changed? That seems like a better fix than considering special functions separately.

**Comment by jksuom** [comment]
> should the ordering of the algorithms be changed?

Yes, meijerint should come before heurisch. It can integrate many functions that heurisch cannot handle. In those cases no time will be wasted with heurisch.

**Comment by rohitrango** [comment]
Yes, actually I tried integrating some non common functions and meijerint was able to solve them quicker.
