### ISSUE TITLE
sympy can't integrate sqrt(log(1/x)) for x=0..1

### ISSUE THREAD

**Issue by axil** [sympy/sympy#11876]
integrate(sqrt(log(1/x)), (x, 0, 1)) should be sqrt(pi)/2 according to reference books and Mathematica. Sympy is unable to calculate this. 

This is formula 4.215 from Gradshtein Ryzhik:

integrate(log(1/x)**(m-1), (x, 0, 1)) == gamma(m) for Re(m)>0

**Comment by aclarridge** [comment]
Hello, I'm new, I'd like to work on this if possible. It seems like a straightforward problem, possibly meriting an implementation of a new type of integral? I'm stepping through the code, trying to figure out what's going on here. Any comments welcome.

**Comment by jksuom** [comment]
This is easy to compute by hand, substituting a new variable u for log(1/x). The integral then becomes the familiar integral formula for the gamma function. Such substitutions are effected in the manualintegrate module. One only has to add functions that will recognize the (transformed) integrand and return the antiderivative (an incomplete gamma funciton).

**Comment by aclarridge** [comment]
Ok, so when I do the substitution myself by hand, the new integral is sqrt(u)*exp(-u), for u from 0 to +inf. When I try
`integrate(sqrt(x)*exp(-1*x),(x,0,oo))`, I get sqrt(pi)/2 as desired. So I think the functions that recognize the transformed integrand already exist, it's just that the substitution functionality somehow doesn't work here. Is that right?

Looking at the code, in find_substitutions, the test_subterm method is returning False even when u is set properly to log(1/x) and u_diff = -1/x.

```
def test_subterm(u, u_diff):
        substituted = integrand / u_diff
        if symbol not in substituted.free_symbols:
            # replaced everything already
            return False

        substituted = substituted.subs(u, u_var).cancel()
        if symbol not in substituted.free_symbols:
            return substituted.as_independent(u_var, as_Add=False)

        return False
```
The key step when integrating by hand is to convert the du=-1/x dx term to -exp(-u) du = dx. It seems like the above method isn't doing that. Is this the reason for the bug? Any more guidance would be greatly appreciated, thanks!

**Comment by jksuom** [comment]
> functions that recognize the transformed integrand already exist,

That is true, but manualintegrate does not know about them. A new integration rule should be added for that.

> It seems like the above method isn't doing that.

This is again a transformation for which 'manual guidance' is necessary. It should apparently be done elsewhere, probably in `manual_diff` to get `u_diff` in the proper form.

**Comment by aclarridge** [comment]
Thank you jksuom, that was very helpful.

Okay, I did some work but now I think I'm stuck.
I had to pass u_var over to `manual_diff`, in order to return a u in the substitution. In the debugger, I'm able to return u_diff = -exp(_u) where _u matches the _u in the substitution, since I pass it in the `manual_diff` call in the `find_substitutions` method. My changes are below. So I thought the job was done, since it should evaluate given the u_diff in terms of u instead of x. However, it's still not computing the integral.

Since I know `integrate(sqrt(x)*exp(-1*x),(x,0,oo))` works, I stepped through that and found that it is solved by the `try_meijerg` method. So my question now is, how can I make sure that for this case, the post-substitution integral tries meijerg? It seems like meijerg is tried way before we get to the substitution methods, so how can I go backwards after substituting? Also, am I on the right track or way off?

Any help very much appreciated, thanks in advance!

```
def manual_diff(f, symbol, u_var=None):
    """Derivative of f in form expected by find_substitutions

    SymPy's derivatives for some trig functions (like cot) aren't in a form
    that works well with finding substitutions; this replaces the
    derivatives for those particular forms with something that works better.

    """
    if f.args:
        arg = f.args[0]
        if isinstance(f, sympy.tan):
            return arg.diff(symbol) * sympy.sec(arg)**2
        elif isinstance(f, sympy.cot):
            return -arg.diff(symbol) * sympy.csc(arg)**2
        elif isinstance(f, sympy.sec):
            return arg.diff(symbol) * sympy.sec(arg) * sympy.tan(arg)
        elif isinstance(f, sympy.csc):
            return -arg.diff(symbol) * sympy.csc(arg) * sympy.cot(arg)
        elif isinstance(f, sympy.Add):
            return sum([manual_diff(arg, symbol) for arg in f.args])
        elif isinstance(f, sympy.Mul):
            if len(f.args) == 2 and isinstance(f.args[0], sympy.Number):
                return f.args[0] * manual_diff(f.args[1], symbol)
        elif isinstance(f, sympy.log):
            if len(f.args)==1:
                expr=1/arg*manual_diff(arg,symbol)
                dum=sympy.Dummy("x")
                return (expr.subs(symbol, list(sympy.solveset(symbol - f.subs(symbol,dum), dum))[0])).subs(symbol,u_var)
    return f.diff(symbol)
```

**Comment by jksuom** [comment]
We have to keep in mind that finding substitutions and evaluating antiderivatives are two independent phases of the integration process. For the evaluation, it is necessary to write a new function that returns the antiderivative as explained in the docstring of the manualintegrate module. It should not call try_meijerg or any methods belonging to other integrators. (The flow of `integrate` is convoluted as it is, perhaps too much so already. We should not make its different parts any more interdependent.)

As to the substitution process, it should also be made simple and straightforward. The use of `solveset` to invert the log expression is definitely too involved. (Besides, `solveset` may waste a long time producing a result that is not useful.)

I think that the rule in `manual_diff` should not be more complicated than what would follow from rewriting `log(arg).diff(symbol) = 1/arg*arg.diff(symbol)` in the form `exp(-u_var)*arg.diff(symbol)`.

In this example we have `arg = 1/x`, and therefore the result will contain `-1/x**2` if `symbol` is `x`, which may not be useful as such. However, it is not necessary to resolve everything in one step. it is possible to make several substitutions like `u = 1/x`, `v = log(u)`. To make that work it seems necessary to modify `possible_subterms` to recursively return `[term.args[0]] + possible_subterms(term.args[0])` instead of the first argument alone.

Once an integrand of the form `t**e*exp(-t)` turns up, its integrator rule should return an antiderivative such as `lowergamma`.

**Comment by aclarridge** [comment]
Ok so scrapped those changes, I think what you're talking about is a much better solution. Do I even need a change to manual_diff then? It seems like if we can substitute twice, then that's all we need, i.e. `u = 1/x`, `v = log(u)`.

So I tried to change `possible_subterms` as you suggest so that it recursively looks for more terms to substitute. I broke out the sympy.log case to its own elif statement:

```
        elif isinstance(term, sympy.log):
            return [term.args[0]]+possible_subterms(term.args[0])
```

and also had to modify the sympy.Pow case:

```
        elif isinstance(term, sympy.Pow):
            if term.args[1].is_constant(symbol):
                return [term.args[0]]+possible_subterms(term.args[0])
            elif term.args[0].is_constant(symbol):
                return [term.args[1]]+possible_subterms(term.args[1])
```

So I hope I didn't hurt anything by doing so.

Anyway, this works as expected, and the first substitution of 1/x is made. The new integral just needs the log(u) substitution and then it's good. But it looks like I would have to call `substitution_rule` again to get this to work. I mean, I could maybe modify `integral_steps` to get this particular case to work, but wouldn't it always be possible to find a case that's just one more substitution away from being solvable? Conversely, there are cases that can keep being substituted ad infinitum just getting more complicated and no nearer a solution. Would a max recursion depth of like 10 make sense? Or is no recursion necessary?

Again, really appreciate all your help, this is a great learning experience.

**Comment by jksuom** [comment]
> But it looks like I would have to call substitution_rule again to get this to work.

It seems to me that this would take place automatically, since `integral_steps` is called recursively [here](https://github.com/sympy/sympy/blob/master/sympy/integrals/manualintegrate.py#L811) (though I may be wrong as I have not studied the implications in detail). If that is what happens, then the main remaining tasks would be the log(u) substitution and the final 'GammaRule' for the indefinite integral.

BTW, you can study the substitutions even before constructing the integration rule by running `integral_steps`.

**Comment by aclarridge** [comment]
You are right, it does take place already, I missed that.

It turns out the issue is that even the transformed integral, integrate(sqrt(log(x))/x**2,x), does not work so yeah it's just the log(u) substitution and the final 'GammaRule' for the indefinite integral. It is interesting that in `find_substitutions`, `test_subterm` seems to stop short of "solving" for x in terms of u, instead it just goes up to the point where there are still x symbols in the substituted integrand and stops. Would it make sense to go a step further and solve for x in terms of u, and try that? I would think there might be a large class of problems solved that way.

Anyway, I will take a look at integral_steps and see if I can implement the log(x) substitution.

**Comment by jksuom** [comment]
> Would it make sense to go a step further and solve for x in terms of u, and try that?

It seems that something like that is necessary, but I'm not sure in which part of the code that should be done. `test_subterm` currently does very little, but adding to it may have unexpected consequences. (That can be tested, of course.) Another possible place might be `substitution_rule`. It already attempts to process expressions that contain `exp`, though I haven't seen an example where that would solve anything.

**Comment by aclarridge** [comment]
Okay, although it has been some time I'm still working on this.

I created a new `Rule` for this type of integral - I am calling it `PowLogRule`. It uses `integrand.match` to identify any integral of the form `a*(sympy.log(b*symbol**d))**c` (trying to make it general here). It then assigns it a value of `a*d**c/(b**(1/d)*(-1)**c)*sympy.uppergamma(c+1,-sympy.ln(b**(1/d)*symbol))` where t is a dummy variable, whenever `c<=-1`. It works for GR 4.215 item 3 and 4, which is what this issue is about specifically. I would like to make it work for the others (1,2) though which are more general. I think I need to use `Assume` though to put the proper restrictions on mu, which I'm calling `c`. I think that's doable. I'll have time to look at it later next week.

About the substitution functionality solving for x in terms of u, should it be done separately from this issue, i.e. raised as a separate issue and solved there? I think it's a much more general change.

**Comment by aclarridge** [comment]
Got some time to work on this today, finally.

I think I've got it figured out now for GR 4.215, all four items. I implemented an assumption check as well so that the integral only works if the `mu ` term has the correct property (i.e. `mu>0` in 4.215 (1)). This is the code:

```
def pow_log_rule(integral):
    integrand,symbol = integral
    mu = sympy.Wild('mu', exclude=[symbol])
    match = integrand.match(sympy.log(1/symbol)**(mu-1))
    if not match or not ask(Q.positive(re(match[mu]))):
        return
    return PowLogRule(integrand,symbol,match[mu])
```

```
@evaluates(PowLogRule)
def eval_pow_log(integrand,symbol,mu):
    return sympy.uppergamma(mu,sympy.ln(1/symbol))
```

The output is as follows:

```
x,y=symbols('x,y')
print(integrate(sqrt(log(1/x)),(x,0,1))) #sqrt(pi)/2
print(integrate(1/sqrt(log(1/x)),(x,0,1))) #sqrt(pi)

print(integrate((log(1/x))**(y-1),(x,0,1))) #Integral(log(1/x)**(y - 1), (x, 0, 1))  <--this is right, because we need that Re(y)>0
print(integrate((log(1/x))**(-y),(x,0,1))) #Integral(log(1/x)**(-y), (x, 0, 1))  <--this is right, because we need that Re(y)<1

y=symbols('y',positive=True)
print(integrate((log(1/x))**(y-1),(x,0,1))) #gamma(y)

yprime=symbols('yprime',negative=True) # make yprime = y-1, that should be negative (i.e. y<1). So the equivalent expression would be instead of -y, -(yprime+1)
print(integrate((log(1/x))**(-(yprime+1)),(x,0,1))) #gamma(-yprime) <--this is accurate. It's equivalent to gamma(1-y), which matches GR 4.215 (2) according to identity 4.4 from http://www.mat.utfsm.cl/scientia/archivos/vol15/ar5.pdf
```

Should I just commit, or is there anything obvious I'm missing? Thanks for any feedback.

**Comment by jksuom** [comment]
This rule is certainly better than nothing, but it is very special and does not reveal how it was obtained. The principal use of manualintegrate is to show (in SymPy Gamma) how integrals are computed step-wise as, for example, [here](http://www.sympygamma.com/input/?i=integrate%28exp%28x%29%20/%20%281%20%2B%20exp%282x%29%29%29). I would like to see something similar for this type of integrals if at all possible.

**Comment by oscargus** [comment]
Works in current master. Added a test in #17059
