### ISSUE TITLE
Strange output from common limit used in elementary calculus

### ISSUE THREAD

**Issue by bsdz** [sympy/sympy#11879]
I notice that the following limit expression returns output that appears to be wrong:

```python
x, h = symbols("x h")
n = symbols('n', integer=True)
limit(((x+h)**n-x**n)/h, h, 0)
```

![image](https://cloud.githubusercontent.com/assets/6608130/20554698/802d49ce-b155-11e6-9825-38a259065aa2.png)

Here's [Wolfram's result](https://goo.gl/0EiVO0)

**Comment by jksuom** [comment]
The code expanding a Pow will introduce exp and log whenever the exponent contains a symbol (https://github.com/sympy/sympy/blob/master/sympy/core/power.py#L1254). This transformation will make the limit computation fail. It would probably suffice to replace `e.has(Symbol)` with `e.has(x)`.

**Comment by bsdz** [comment]
I tried your suggestion and it does make the following test succeed:

```python
def test_issue_11879():
    assert simplify(limit(((x+y)**n-x**n)/y, y, 0)) == n*x**(n-1)
```

However, it then causes test "test_issue_5172" to fail. In particular, and I'm not a gruntz algorithm expert by any means, it fails when trying to take sign(-dummy*c,dummy) which resolves to -sign(c) which isn't 1,-1 or 0 hence breaking limitinf.

**Comment by jksuom** [comment]
It looks like that simple fix was wrong, in general. The issue is that SymPy does not automatically recognize that `exp(n*log(x)) - x**n` has value zero: 
```
In [7]: exp(n*log(x)) - x**n == 0
Out[7]: False
```
Hence gruntz is led to believe that `(exp(n*log(x)) - x**n)/y` is the dominating part of the expression and returns a nonsense result. Some additional processing like this
```
In [9]: powdenest(exp(n*log(x)) - x**n)
Out[9]: 0
```
 should probably be added to gruntz. The standard `simplify()` alone, as applied [here](https://github.com/sympy/sympy/blob/master/sympy/series/gruntz.py#L467), does not seem to suffice.

**Comment by bsdz** [comment]
I've put in a pull request following suggestion.
