### ISSUE TITLE
Sympy very slow response for this equation

### ISSUE THREAD

**Issue by tyetis** [sympy/sympy#11963]
Sympy very slow response for this equation:

solve([Eq(x**2+y/(x+y), 20)], x,y)

what is the reason ? Do you have a better method ?

**Comment by smichr** [comment]
It's a cubic equation in `x` and it takes time to check the solutions. If you don't want to verify the solutions --which in this case are the same as those obtained with verification -- send the flag `check=False`. But a better approach would be to solve for y since it's linear in that: just use `solve([Eq(x**2+y/(x+y), 20)], y)` [note that the `x` has been omitted].

A better place to raise such questions is on the discussion list at [here](https://groups.google.com/forum/#!forum/sympy).

**Comment by tyetis** [comment]
Thanks for reply
i asked for my math project. it is here http://math.webrone.com/
