### ISSUE TITLE
solveset regression: rational inequality with abs()

### ISSUE THREAD

**Issue by jondo** [sympy/sympy#12095]
Solving the inequality `abs((x-1)/(x-5)) <= 1/3` was fixed in #9565. However, with the current Git master the solution `[-1.0, 2.0]` is not found any more:
```python
>>> x = symbols('x', real=True)
>>> from sympy.solvers.solveset import solveset
>>> solveset(abs((x-1)/(x-5)) <= 1/3, domain=S.Reals)
⎧            │x - 1│                    ⎫
⎨x | x ∊ ℝ ∧ ─────── ≤ 0.333333333333333⎬
⎩            │x - 5│                    ⎭
```

FWIW, the similar inequality without `abs()` works:
```python
>>> solveset((x-1)/(x-5) <= 1/3, domain=S.Reals)
[-1.0, 5)
```

This is on `SymPy 1.0.1.dev (Python 2.7.12-64-bit)`.

**Comment by jondo** [comment]
@kshitij10496, this got broken when you applied your new `solvify` in your commit 0d6d4edd1118e5a2f17c5368d3c2c0c748244f48 during your [GSOC participation](https://github.com/sympy/sympy/wiki/GSoC-2016-Solvers-Progress#kshitijs-progress). Can you please fix it and add it to the regression tests?

Also pinging @hargup, who merged this.

**Comment by valglad** [comment]
It seems that solveset generally has trouble solving `abs(x-1)/abs(x-5)-1/3` (as an equation rather than an inequality) because it returns a ConditionSet but it can solve `abs((x-1)/(x-5))-1/3` just fine. The first equation gets modified by "together" at the beginning of _solveset to give an unpleasant-looking fraction with abs(x-5) in the denominator and then solveset gets confused. But the second one is not affected by "together" so then solveset does the sensible thing of saying "(x-1)/(x-5) is either 1/3 or -1/3". And it's this issue that gets in the way of solving the inequality because one of the first lines in solve_univariate_inequality is `expr = expr.subs(gen, d)` where gen is `x` in this case and `d` is a dummy variable, and abs(p/q) becomes abs(p)/abs(q) after the substitution.

Is there some way of telling _solveset to rewrite things like abs(p)/abs(q) as abs(p/q) before it tries to apply "together"? Pattern-matching with some expression like "abs(p)/abs(q)+r" does allow _solveset to solve `abs(x-1)/abs(x-5)-1/3` as an equation but it still wouldn't work with inequalities because when a dummy variable is used instead of `x`, abs(p/q) is always treated as abs(p)/abs(q). Besides, that sort of pattern matching doesn't seem a real solution as there would still be an issue with expressions like `abs(x-1)/(2*abs(x-5))-1/3` for example. Any suggestions? Or should we instead be looking into why _sovleset gets confused when presented with `(-1/3*abs(x-5)+abs(x-1))/abs(x-5)` in place of `abs(x-1)/abs(x-5)-1/3`?
