### ISSUE TITLE
Eval function for boolean expression

### ISSUE THREAD

**Issue by shevah** [sympy/sympy#12126]
Hi,
Assume we have the following code:
```python
from sympy import lambdify, Or, And, var
x,y,z = Symbols('x,y,z')
rule = Or(x, And(y,z))
```
I would like to see `rule.eval({x: False, y:True, z: True})` to return `True`.
Sympy has `subs()` and `xreplace` methods for this kind of behavior but they create new function/expressions internally which results in very poor performance (0.0003 seconds per `subs` call).

I would like to see a simple evaluation that given a full assignment to all variables of a boolean expression return either `True/False`.

Am I missing somethig?

**Comment by smichr** [comment]
Some answers are give at [stackoverflow](https://stackoverflow.com/questions/42024034/evaluate-sympy-boolean-expression-in-python/46489689#46489689).

Rather than compute this via eval, a Lambda of the rule can be directly evaluated:

```
>>> rule = Or(x, And(y,z))
>>> F = Lambda(x, y, z), rule)
>>> F(0, 1, 1)
True
```

**Comment by oscarbenjamin** [comment]
You can use subs for this:
```julia
In [71]: from sympy import lambdify, Or, And, var 
    ...: x,y,z = symbols('x,y,z') 
    ...: rule = Or(x, And(y,z))                                                                                                                               

In [72]: rule.subs({x: False, y:True, z: True})                                                                                                               
Out[72]: True
```

**Comment by asmeurer** [comment]
I agree, eval as requested here is just `subs` or `xreplace`. The OP suggests that they are too slow because they "create new function/expressions internally". However, it is impossible to mutate a SymPy expression, as they are immutable. `xreplace` should be as fast as it can be. If you want something faster, you can use `f = lambdify((x, y, z), rule, modules=[])`, which creates a function for `x or y and z`. For me, `rule.xreplace({x: False, y:True, z: True})` takes 101 µs and `f(False, True, True)` takes 174 ns.
