### ISSUE TITLE
Sympy numbers don't adhere to Python's numbers ABC

### ISSUE THREAD

**Issue by inducer** [sympy/sympy#12134]
I'd expect this to be `True`:

```
>>> import sympy
>>> x = sympy.numbers.Float(5)
>>> import numbers
>>> isinstance(x, numbers.Number)
False
```

https://docs.python.org/3/library/numbers.html

(Sorry if this has been considered before--a quick search didn't reveal anything.)

**Comment by asmeurer** [comment]
Should be easy to fix. I think the last time this was brought up we still supported Python versions that didn't have ABCs.

**Comment by Abdullahjavednesar** [comment]
Why does it return ```False```?

**Comment by madan96** [comment]
@Abdullahjavednesar I guess because `x` is not an instance of `Number` ABC in Python numbers.

**Comment by madan96** [comment]
@asmeurer Will inheriting the `Number` class (from numbers module) into `Number` class in sympy.core.numbers work?

**Comment by Abdullahjavednesar** [comment]
@madan96 Hopefully inheriting ```Number```class should work.

**Comment by asmeurer** [comment]
We might need to define some attributes required by the ABCs, but as far as I know it should work.

**Comment by meet7202** [comment]
```
>>> import sympy
>>> x = sympy.numbers.Float(5)
>>> isinstance(x, numbers.Number)
True
```
importing numbers changes datatype of x to string from Number that's why Number ABC returns False.
@asmeurer , This issue can be solved if I will change 
`num = str(num)`  to `num = mpf(num)` in "sympy/core/numbers.py" (Line Number 780-781) , But I am not able to figure our that it will misbehave in other cases or not please clear my doubt so I can send you PR.

**Comment by mohit3011** [comment]
@meet7202  are you working on this issue ?

**Comment by meet7202** [comment]
@mohit3011 , Yes I am. Just Needed @asmeurer's confirmation...!!

**Comment by madan96** [comment]
@meet7202 You can run `tests` locally to check if there is any anomaly for other cases.

**Comment by asmeurer** [comment]
The fix here should to add `numbers.Number` as a superclass to `Float`.

**Comment by meet7202** [comment]
@asmeurer sir, Please review PR #12152

**Comment by meet7202** [comment]
```
>>> import sympy
>>> x = sympy.numbers.Number(5)
>>> import numbers
>>> isinstance(x, numbers.Number)
False
```
`sympy.numbers.Number()` also gives WA and If I am not wrong Float is inherited from `sympy.numbers.Number()`.

**Comment by gerritholl** [comment]
I've noticed that multiplying a `sympy.Float` with an `ndarray` gives an `ndarray` with `object`-dtype.  Would this become a `float` dtype if the `sympy numbers` were to adhere to Python`s numbers ABC, or is this a separate issue?

```
In [65]: (sympy.Float(1.23) * numpy.array([.0,.1,.2])).dtype
Out[65]: dtype('O')
```

**Comment by asmeurer** [comment]
That is the correct behavior (`Float*float` is `Float`, which numpy treats as `object`). This wouldn't affect that in any case.

**Comment by m-agboola** [comment]
Please Is this issue still open?

**Comment by nikkigabbard** [comment]
I'd like to work on this issue!

**Comment by oscarbenjamin** [comment]
Does anyone know of any examples of third part libraries that work with Python's numbers ABC hierarchy? Last I checked it wasn't true for anything outside of the stdlib and wasn't true for deicmal.Decimal either.

Are there any actual advantages to using these ABCs? Testing isinstance with them is much slower than with the concrete types.

**Comment by asmeurer** [comment]
It seems to be true for decimal.

```py
>>> isinstance(decimal.Decimal(1), numbers.Number)
True
```

The only other libraries I can think of that even define numeric types are mpmath and numpy, and it looks like they both do.

```py
>>> isinstance(numpy.int64(1), numbers.Number)
True
>>> isinstance(mpmath.mpf(1), numbers.Number)
True
```

mpmath does it by registering the types, rather than subclassing. We may want to do the same, as I suspect literal subclassing could have performance implications with the additional metaclass.

**Comment by oscarbenjamin** [comment]
Okay looks like things have changed.

I'm still unclear what the purpose of these ABCs is though. I generally don't want to abstract over different numeric types. The ABC hierarchy implies that floats are a superset of ints/rationals but that isn't generally true (overflow, 1/3 etc.).

Supporting this properly would mean adding various attributes at least:
```julia
In [103]: import numbers                                                                                                                                      

In [104]: numbers.Complex.real                                                                                                                                
Out[104]: <property at 0x103ab93b8>

In [105]: (1).real                                                                                                                                            
Out[105]: 1

In [106]: (S(1)).real                                                                                                                                         
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-106-c9c00c5048fc> in <module>
----> 1 (S(1)).real

AttributeError: 'One' object has no attribute 'real'
```

**Comment by asmeurer** [comment]
> The ABC hierarchy implies that floats are a superset of ints/rationals but that isn't generally true (overflow, 1/3 etc.).

I think floats have a shared parent of Rational, which is Real. That's the same in SymPy, where Float and Rational both subclass from Number. Our number heirarchy is a bit different. We don't separate out complex numbers. Rather, inequalities selectively raise TypeError when it isn't allowed. And we use complex extensions of functions like floor and ceiling. 

I think in practice it just means adding those missing properties. Actually I don't know how to handle complex since complex numbers are Add in SymPy, but only a subset of Adds are numeric complex numbers. As far as I can tell ABCs only allow registering classes, not selective instances of a class. So I wouldn't worry about them. 

I really don't know where these are actually used. @inducer wanted them for something. Adding `Float`, `Rational`, and `Integer` to the respective registries, and adding the missing methods should be easy enough. Technically we don't even have to add the methods if we don't subclass (mpmath doesn't have `numerator` and `denominator` for instance).

**Comment by oscarbenjamin** [comment]
Okay fair point: floats are a subset of Real which doesn't imply that they are a superset of Rational..

This is described in [https://www.python.org/dev/peps/pep-3141/](https://www.python.org/dev/peps/pep-3141/)

What the hierarchy misses is exactness. I really want to know whether numbers are exact more than whether they are integer/rational/real/complex. I can't imagine a situation where I would want to write code for both SymPy objects and Python floats. Code to deal with floats needs to be written very carefully in a different way from code to deal with objects that have exact arithmetic.

The fact that mpmath doesn't have numerator and denominator suggests that these ABCs are not really useful since they are getting away with buggy support. I'm sure that there are many people suggesting (possibly just for consistency) that different libraries should support this but that doesn't mean that those people actually have a real use for it.

To be clear I'm not arguing against supporting the ABCs. I just don't see what the actual benefit is for users. My general perspective on this kind of situation is: if I knew what *real* problems I was trying to solve then I could do a better job solving them.
