### ISSUE TITLE
Upper and lower case assumptions in the Symbol() constructor are not equivalent

### ISSUE THREAD

**Issue by ooovector** [sympy/sympy#12328]
I'm trying to simplify an expression containing sin(m*pi) terms. If m is a sympy rational, everything works nicely, however, if I try

`
m = sympy.Symbol('m', Rational=True, Integer=True)
print(m.is_Rational, m.is_real, m.assumptions0, m._assumptions)

print(sympy.functions.elementary.trigonometric._peeloff_pi(sympy.pi*m+sympy.pi*sympy.nsimplify(1)))
print(sympy.sin(m*sympy.pi+sympy.pi*sympy.nsimplify(1)))
`

I get the following output:
`False None {'commutative': True, 'Rational': True, 'Integer': True} {
	Integer: True,
	Rational: True,
	algebraic: None,
	antihermitian: None,
	commutative: True,
	complex: None,
	finite: None,
	hermitian: None,
	infinite: None,
	integer: None,
	irrational: None,
	negative: None,
	nonnegative: None,
	nonpositive: None,
	positive: None,
	rational: None,
	real: None,
	zero: None}
(pi*m, pi)
-sin(pi*m)`

I'm new to looking inside the sympy code and maybe I don't really understand how it should work, but it seems that the Symbol's constructor doesn't set the _is_rational, _is_real and all the other members; at the same time, sympy.functions.elementary.trigonometric._peeloff_pi is using _is_Rational (which returns False) to check.

Maybe the constructor should somehow set these _is_rational, _is_real and so on members after settings the assumptions member?

**Comment by ooovector** [comment]
My problem got solved by changing
`
m = sympy.Symbol('m', Rational=True, Integer=True)
`
to
`
m = sympy.Symbol('m', integer=True)
`

after which the sine gets correctly evaluated to 0. Still, if this is a feature and not a bug it's not really well-documented

**Comment by jksuom** [comment]
In SymPy, upper case is generally used to denote classes, not properties in assumptions.

`e.is_Rational` means that `e` is an object of class `Rational`. For an object `x` of class `Symbol`, `x.is_Rational` will always return `False`. Adding `Rational=True` into its assumptions does not make it an object of class `Rational` and has no effect in SymPy since `Rational` is not a property in the assumptions module.

On the other hand, lower case `rational` is a property handled by assumptions.  `x.is_rational` signifies that the values that `x` ranges over are rational (even if `x` itself is not `Rational`).

**Comment by ooovector** [comment]
Then a guess this is not an issue and should be closed
