### ISSUE TITLE
sympy.solve variable name loss

### ISSUE THREAD

**Issue by JoelSjogren** [sympy/sympy#12476]
My variables get renamed in the solver for some reason. 
https://pastebin.com/LDxgtgsf

Works.
`>>> sympy.solve(eqns[:-1])`
`[{x5**2: x0,...`

Works not.
`>>> sympy.solve(eqns)`
`[{_Dummy_25: 1/36,...`

Workaround.
https://pastebin.com/sbtPjxFh
`>>> sympy.solve(eqns, x)`
`[(1,...`

Running on Ubuntu 16.10 64-bit and Python 3.5.2+.
`>>> sympy.__version__`
`'1.0'`

**Comment by Lowe-Marc** [comment]
I'm interested in taking a look into it but I'm new here. If anyone has any advice/tips I'd thoroughly appreciate it (or if this is more complicated than I think it might be). So far I've just been able to trim down the size of the argument quite a bit and have seen the dummy variables passed around in a couple places, haven't narrowed down exactly where the dummy variables are supposed to be replaced/removed yet though.

**Comment by valglad** [comment]
@Lowe-Marc I believe you should look at what happens in `_solve_system` to which the equations and symbols are passed on line 1071. The Dummy variables are added to the list of symbols on line 888, but they are not part of any of the equations so `_solve_system` shouldn't return solutions for them, and yet it does. Clearly, `x0-1` is the culprit. If you replace it by `x0*x2-x1` or something like that, the solutions are fine (but not when you replace it by `x0*x2-1`). So try to see how `x0-1` might be treated differently and make things go wrong.

**Comment by valglad** [comment]
@Lowe-Marc Now that I've looked at it more, everything goes wrong on line 1758 in `_solve_system`. `solved_syms` there is the same as `symbols` but `result` is only for variables involved in `polys` (the original equations that could be changed into polys). That would've been fine if `symbols` didn't start with all the Dummy variables. This order is imposed when `symbols` is sorted on line 951. My guess is if you change the sorting so that the Dummy variables go after everything else, the problem will be fixed and whatever the sorting is intended for shouldn't be affected. You can give it a go and see.

**Comment by Lowe-Marc** [comment]
Sorry, two of my class assignment/projects ended up eating way more time than expected and I was just getting to this. Looks like you solved it, thank you very much for the help anyway.

**Comment by valglad** [comment]
Ah, well sorry if you were looking forward to solving it yourself. I waited for a couple of days and then just went ahead with it because I was curious if modifying the sorting would work (it did but felt unsatisfactory). Still plenty of bugs to work on though
