### ISSUE TITLE
solveset_real and solveset give different answers for soln of `sqrt(x - 2) + 2`

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#12478]
```
>>> solveset_real(sqrt(x - 2) + 2, x)
FiniteSet(6)  <--- this is wrong
>>> solveset(sqrt(x - 2) + 2, x)
EmptySet()
```

**Comment by maurogaravello** [comment]
The problem is in `_invert_real` of `solveset.py`.
At some point, sympy has to solve `sqrt(x-2) = -2`. For doing that, it takes the square `x-2 = 4` and so it returns `6`. I think it is sufficient to calculate the real domain of the function and do the intersection of the solution with the domain.

**Comment by kshitij10496** [comment]
I agree with @maurogaravello about the incorrect behaviour of `_invert_real` method.
The internal call to `_invert_real(sqrt(x-2), -2, x)` is the cause of this bug. 

An approach to solve this issue can be to divide the problem of fractional powers of the kind `1/n` into two families based on the value of `n`. 
For even values of `n`, we can simply reject the equation if the RHS is negative (since we are only concerned with the principal values). 
On the other hand, when `n` is odd, we can proceed with the usual method.

For example:
```python
In [] : solveset((x-4)**(1/2) + 2, x, S.Reals)
Out[]: EmptySet

In [] : solveset((x- 32)**(1/5) + 2, x, S.Reals)
Out[]: FiniteSet(0)
```

**Comment by maurogaravello** [comment]
Exactly. I divided the cases into two subcases in the PR #12488.
