### ISSUE TITLE
Non-commutative multiply triggers inappropriate substitutions 

### ISSUE THREAD

**Issue by TobiSchluter** [sympy/sympy#12576]
I was playing around with sympy a bit, but almost immediately ran into trouble. Even though I think it's a nice tool, I ran into this too fast to trust it :(

In sympy live I enter:
```
a, b,c = symbols('a b c', commutative=False)
```
and I try two operations (x, y are symbols without further qualifications in sympy live):
```
>>> expand((a*(x*b*c+c*b*a)*y)).subs([(b*c,-a),(a*a,-1),(c*b,a)])
         3
x*y + y*a 
>>> expand((a*(x*b*c+c*b*a)*y)).subs([(b*c,-a),(a*a,-1),(c*b,a)]).subs([(b*c,-a),(a*a,-1),(c*b,a)])
x*y - I*y
```
Note how the imaginary unit appears out of nowhere when the same substitution is applied twice. I.e. ```a**3``` is replaced by the imaginary unit.

I think the bug in the implementation is that it infers from ```a*a == -1``` that ```a == I```. This is not correct because the multiplication rules for non-commutative objects are not the same as for complex numbers. To quote a familiar example, quaternion multiplication is non-commuting and one has both ```i*i == -1``` and ```j*j == -1``` -- yet both ```j``` and ```j**3``` are very different from ```i```.

I see how one could work around this by defining a special symbol 'minusOne' together with a very carefully assembled set of substitution rules that mimic multiplication by a scalar, but is that the intended use?

**Comment by valglad** [comment]
Yes, the assumption that the base of a `Pow` expression is always a complex number is made in the definition of the `_eval_power` function in `core/power.py`. It certainly shouldn't do that for symbols that are known to be non-complex (e.g. `x=Symbol('x', commutative=False)`. I think that it probably shouldn't make any assumptions in cases where it's uncertain either (so just `x=Symbol('x')`). So it can be quite easily fixed by telling `_eval_power` to check if the base is complex before it tries to do complex-specific stuff.

The problem I ran into is that a few tests for expressions involve things like `x**(1/2)` where `x` is a general symbol, not necessarily complex, and the above fix leads to failures when working with such expressions. I feel that in the case when `x` is not known to be complex `x**(1/2)` shouldn't be allowed. Typically only integer powers are used when working with non-complex objects. Theoretically, I suppose `x**(1/2)` could sort of make sense if, say, we are working modulo some `n` and `x` is a quadratic residue but generally, it doesn't. On the other hand, it doesn't feel right to modify the `Pow` constructor so that it returns an error when a user tries to raise a symbol that is not explicitly complex to a fractional power. After all people will probably want to deal with complex numbers most of the time and having to write `x = Symbol('x', complex = True)` every time they want to raise a symbol to a fractional power can be tiring - not to mention the case where someone wishes to do symbolic algebra with non-complex objects for which it does make sense to have fractional exponents which behave exactly like those for complex numbers.

I'm uncertain how to proceed. Does anyone have an opinion on the matter?

**Comment by TobiSchluter** [comment]
Hi, I just stumbled on your answer again.

Just a point: powers of complex numbers involve branch cuts. While in simple cases such as x**(1/2) one can probably fall back on a standard definition (such as the usual choice for the square root to have the branch cut along the negative real axis with the negative real axis included in the upper half) it is not really possible to naively combine complex powers without giving the branch cut(s).

To show that this arises very easily if one is careless take a very simple example: the positive square root of -i.  With the standard branch cut this is (1-i)/sqrt(2) (in other words exp(-pi/2)**(1/2) == exp(-pi/4)), but evaluating naively as (-i)**(1/2) = (-1)**(1/2) * i**(1/2) = i * (1 + i)/sqrt(2) = -(1-i)/sqrt(2) = -exp(-pi/4) (!).  The difference comes about because the multiplication of (-1) and i crosses the branch cut.

I wasn't able to reproduce this in sympy straight-away, because sqrt(-I) is not simplified, but I found another manifestation of the underlying issue (again, using sympy live):
>>> simplify(-sqrt(-I))
(-I)**(5/2)

**Comment by valglad** [comment]
Hmm, I haven't thought of the issue with branch cuts. I suppose what SymPy currently does is treating fractional powers as multivalued complex functions and returning some element of the relevant set of values. Fractional powers with even denominator in the reals are also multivalued but there it's easy to use positivity to choose an element consistently. In the complex world, however, different branch cuts for different cases have to be defined for that purpose. But it is only a matter of consistency. I suppose it would eventually be good to have SymPy be able to define suitable branch cuts and work within them but it doesn't sound like something that needs to be done urgently (at least I don't see it causing any major problems). The original issue of assuming non-commutative symbols are complex does need to be fixed soon because it's just wrong.

**Comment by smichr** [comment]
This is really unexpected. I used just the simplest replicating expression and find:

```
>>> A=Symbol("A",commutative=0)
>>> (A**3).subs(A*A,-1)
−i

>>> (x**3).subs(x**2,-1)
x**3
```

**Comment by asmeurer** [comment]
I believe the issue noted by @smichr was fixed by https://github.com/sympy/sympy/pull/13018

**Comment by asmeurer** [comment]
Actually I believe the original issue was fixed as well

```
>>> expand((a*(x*b*c+c*b*a)*y)).subs([(b*c,-a),(a*a,-1),(c*b,a)])
x*y + y*a**3
>>> expand((a*(x*b*c+c*b*a)*y)).subs([(b*c,-a),(a*a,-1),(c*b,a)]).subs([(b*c,-a),(a*a,-1),(c*b,a)])
x*y - y*a
```
