### ISSUE TITLE
Fourier transform of exponential returns 0

### ISSUE THREAD

**Issue by nicoguaro** [sympy/sympy#12591]
When I try to compute the Fourier Transform of exp(x) it returns 0.

     import sympy as sym
     x, y = sym.symbols("x y", real=True)
     fun = sym.fourier_transform(sym.exp(x), x, y)
     print(fun)

returns

    0

**Comment by jksuom** [comment]
Maybe some kind of error message should be output.

**Comment by mohit3011** [comment]
@jksuom , I think we can provide some error message whenever we find positive powers of any symbol as positive powers would give error in this case

**Comment by mvanda** [comment]
A similar problem can be found at

http://stackoverflow.com/questions/33208737/continuous-fourier-transform-with-python-sympy-analytical-solution

**Comment by jksuom** [comment]
It would probably be safe to give at least some kind of warning if the limits of the functions at `oo` and `-oo` are not zero. Strictly speaking, the Fourier integral can exist only if the function is integrable over the real line. However, it is possible to formally extend the integral to square integrable functions by a limiting process based on Parseval's theorem (integral of the square absolute value is preserved under Fourier transform). So, it is possible to define the Fourier transform of `1/sqrt(1 + x**2)`. It is not integrable since it is of order `O(1/x)` at the infinities, but its square is integrable. (Looking at the limits is not fully satisfactory since it is possible to construct integrable functions with no limits at the infinities.)

It is possible to define the Fourier transform as a distribution if the function is tempered (i.e, it and its derivatives grow at most polynomially). That is the case with the stackoverflow problem, the distribution is given by a Dirac delta (though the transform is not implemented in SymPy). But exponentially growing functions are not tempered.

**Comment by ashishkg0022** [comment]
@jksuom regarding this issue , Is it just sufficient to check limits at oo and -oo or we should check  `∫|f(x)|dx`(integration from `-oo to oo`) , I think this must exist for Fourier transform to exist.

**Comment by jksuom** [comment]
For the existence of Fourier transform in the strict sense it is necessary that `|f(x)|` be integrable. However, SymPy has often issues with integrals involving absolute values. That is why I suggested looking at the limits. Another possibility might be checking the integral of `f(x)` with no absolute values and giving a warning if that is not well defined.

**Comment by nicoguaro** [comment]
What do you mean by "in the strict sense"? What about Fourier transforms over distribution spaces?

**Comment by ashishkg0022** [comment]
ok . I will do it.

**Comment by jksuom** [comment]
> What do you mean by "in the strict sense"?

I mean the transform as given by the integral of an integrable function (wrt the Lebesgue measure).

**Comment by nicoguaro** [comment]
I doubt that sin(x)/x is Lebesgue integrable, for example

**Comment by jksuom** [comment]
I agree, it is not Lebesgue integrable. But it is square-integrable and its Fourier transform can therefore be defined by a limiting process in the space of L2-functions. ([Wikipedia](https://en.wikipedia.org/wiki/Fourier_transform#Plancherel_theorem_and_Parseval.27s_theorem): Plancherel's theorem makes it possible to extend the Fourier transform, by a continuity argument, to a unitary operator on L2(ℝ).)
