### ISSUE TITLE
as_numer_denom non-deterministically influences the state of Python’s random number generator

### ISSUE THREAD

**Issue by Wrzlprmft** [sympy/sympy#12628]
When I apply `as_numer_denom` to a power expression, this changes the state of Python’s random number generator. This happens in a non-deterministic fashion, i.e., it isn’t just that random numbers are generated for whatever reason, but the state seems to be reset using some external information (like the system time).

Here is a minimal non-working example:

``` Python

import random
from sympy.abc import x

results = set()
for _ in range(10):
	random.seed(42)
	(x**2).as_numer_denom()
	results.add(random.random())
assert len(results)==1
```

**Comment by asmeurer** [comment]
We should be using a random.Random instance so that it doesn't affect the random seed for other applications. 

As a workaround, I suggest doing the same in your own code, so that nothing else can mess with random like this.

**Comment by Wrzlprmft** [comment]
> As a workaround, I suggest doing the same in your own code, so that nothing else can mess with random like this.

That’s what I eventually did. I stumbled upon this when checking something quickly and dirtily and since I didn’t expect SymPy to use random numbers for this (let alone in a way that is not even deterministic), I was rather baffled and it took me a while to find out what happened.

**Comment by caph1993** [comment]
Same here. Spent about two hours until finding the issue.

I've written another short example because I found something that might be useful: the issue happens only at the first call of `my_test`. Subsequent calls do not affect python's random state.

```python
import sympy as sp
import random

def my_test():
    random.seed('HolaAmigo')
    # Should print -1735515812038708070 (may vary on your laptop)
    print(hash(random.getstate()))
    for i in range(100):
        x = random.randrange(2) * sp.Symbol('x')
    # Should print 3791330111857148225 (may vary on your laptop)
    print(hash(random.getstate()))
    return

my_test() # fails
my_test() # ok
my_test() # ok
my_test() # ok
```
You may comment out the sp.Symbol to check what the value would be if no intervention from sympy occurred.

**Comment by laolux** [comment]
I ran into a similar problem, using `sympy.acos`.
The following program shows different results for variable `after` for consecutive runs.

    import sympy
    import random
    random.seed(28)
    
    before = random.uniform(0,1)
    print('before: ',before)
    m0, m1= sympy.symbols('m_0 m_1', real=True)
    result = sympy.acos(-m0/m1)
    after = random.uniform(0,1)
    print('after: ',after)

What about adding a warning in the documentation about this behavior? I think the section `Gotchas and Pitfalls` would be good for this.

**Comment by asmeurer** [comment]
This is a bug. SymPy should be using its own independent random state wherever it is using random numbers. Of course, the simplest workaround is to also do the same in your own code (use `random.Random()` instead of `random`). That's recommended practice regardless, because you never know what other code will be calling the global random number generator.
