### ISSUE TITLE
I think i've found a bug??

### ISSUE THREAD

**Issue by ethan1987-2** [sympy/sympy#12879]
running the following
```
init_printing(use_latex='mathjax')
y=Symbol('y',positive=True)
x=Symbol('x',positive=True)
Z=Symbol('Z',positive=True)

r10= 2*Z**1.5*exp(-Z*x)
r21=3**-.5*(Z/2)**1.5*(Z*x)*exp(-Z*x/2)

simplify(integrate(simplify(x**3*r10*r21),(x,0,y)))
```
YIELDS:
PolynomialDivisionFailed: couldn't reduce degree in a polynomial division algorithm when dividing [0.816496580927726*(Z**4.0), 0.0, 0.0, 0.0, 0.0] by [12.0/12.0]. This can happen when it's not possible to detect zero in the coefficient domain. The domain of computation is RR(Z**4.0,Z). Zero detection is guaranteed in this coefficient domain. This may indicate a bug in SymPy or the domain is user defined and doesn't implement zero detection properly.

but if i try doing the integration without the constant factors (except for Z) it works fine:
`simplify(integrate(Z**4*x**4*exp(-3/2*Z*x),(x,0,y)))`

**Comment by jksuom** [comment]
It is a known issue that zero detection is not guaranteed in floating point domains because of rounding errors (contrary to the boilerplate claim). Another issue is that floating point exponents cannot be used to define polynomials. The expression  `RR(Z**4.0, Z)` indicates that `Z**4.0` does not denote a polynomial in `Z` but is interpreted as a new independent variable that only has a curious expression.

The solution is to avoid floating point numbers in expressions that lead to polynomials, which is what often happens in `integrate`. So, one should use `S(3)/2` instead of `1.5`, etc. (See http://docs.sympy.org/latest/gotchas.html#python-numbers-vs-sympy-numbers)

**Comment by gxyd** [comment]
I'll close this now as a non-issue. The explanation is well given in the above comment by Kalevi.
