### ISSUE TITLE
Simplify testing framework

### ISSUE THREAD

**Issue by jirikuncar** [sympy/sympy#12927]
I understand that there is a lot of work behind the custom testing framework. I have got myself to a trap in #12919 when I have naively though that PyTest markers should work.

Hence I would like to propose to use pure PyTest and few well documented plugins to simplify (and possibly speed-up) the tests.

* PyTest
* Doctests: `--doctest-glob="*.rst" --doctest-modules`
* Coverage: https://github.com/pytest-dev/pytest-cov
* Setuptools integration: https://github.com/pytest-dev/pytest-runner
* Paralelization: https://github.com/pytest-dev/pytest-xdist or https://github.com/mark-adams/pytest-test-groups
...

Following part can be later removed: http://docs.sympy.org/latest/modules/utilities/runtests.html

**Comment by jirikuncar** [comment]
An example of a subpart which is possible to "pytest":

```console
$ pytest --doctest-modules --cov=sympy.physics.units sympy/physics/units
```

**Comment by moorepants** [comment]
My guess is that improving the testing suite and making more modern pytest a dependency would be welcomed. I support it.

**Comment by bjodah** [comment]
I also think we should start using `py.test`. Last time I tried I had trouble getting `pytest.raises` to actually catch `SymPyDeprecationWarning`. I couldn't get it to work, but I didn't spend that much time on it. But I think that was the only blocking issue.

**Comment by oscarbenjamin** [comment]
I think the issues mentioned here are resolved:

1. It is now possible to use pytest for running (all of) the tests.
2. pytests markers work fine provided you use the subset provided from sympy/utilities/pytest
3. raises works fine
4. For SymPyDeprecationWarning we have the warns_deprecated_sympy context manager.

Since all problems listed here no longer apply I'll close this. If there are still problems (of course there are!) then it's best to open a new issue.
