### ISSUE TITLE
Result of sympy.factor depends on the length of the symbol names

### ISSUE THREAD

**Issue by pbtsrc** [sympy/sympy#12972]
```python
import sympy
x, y, a, b, k = sympy.symbols('x, y, a, b, k')
exp = x - y - (x - y) * (1 - a) - (x - y) * b - (x - y) * (1 - a) * k
out = sympy.factor(exp)
```
`out = (x - y)*(a*k + a - b - k) `

The same as above, just replaced "x" with "xx":

```python
import sympy
xx, y, a, b, k = sympy.symbols('xx, y, a, b, k')
exp = xx - y - (xx - y) * (1 - a) - (xx - y) * b - (xx - y) * (1 - a) * k
out = sympy.factor(exp)
```
`out = -(-xx + y)*(a*k + a - b - k) `

```
$ pip show sympy
Name: sympy
Version: 1.1
...
```

**Comment by ayush1999** [comment]
@pbtsrc The output in both cases is **same**. I don't see the problem here.

**Comment by asmeurer** [comment]
You can get the same result if you pass the variable name(s) to factor with respect to to factor, like `factor(exp, xx)`.

**Comment by pbtsrc** [comment]
Of course, the results are mathematically equivalent. But it's just quite unexpected that the output depends on the symbol names.

**Comment by asmeurer** [comment]
@pbtsrc depending on what order Poly uses for the generators, it will affect the output, because it wants to make the polynomials have positive sign in the highest order term. In the first case, they are ordered `x, y, a, b, k` (you can see this by creating `Poly(exp)`), so both `x - y` and `a*k + a - b - k` have positive sign. 

In the second case, it uses the order `y, a, b, k, xx`, so the term `-y + xx` needs a minus sign pulled out (this is further confused by the fact that the SymPy printer uses a different order for the terms than Poly). 

Poly tries to be "smart" about the default order of the generators, when none are given, so that is most like what you expect, that is, first x, y, z, the alphabetical order. You can always override this by passing the generators manually.

**Comment by pbtsrc** [comment]
@asmeurer Thank you for the detailed explanation

**Comment by oscarbenjamin** [comment]
So can this issue be closed?
