### ISSUE TITLE
factor_list fails in symbolic mode when an expression has symbolic fractions, but works fine when the same expression is given as a Poly

### ISSUE THREAD

**Issue by user234683** [sympy/sympy#13073]
```
>>> factor_list(x**3/a + y**2*x**2/b)
Traceback (most recent call last):
  File "<pyshell#111>", line 1, in <module>
    factor_list(x**3/a + y**2*x**2/b)
  File "C:\Python36\lib\site-packages\sympy-1.1.2.dev0-py3.6.egg\sympy\polys\polytools.py", line 6236, in factor_list
    return _generic_factor_list(f, gens, args, method='factor')
  File "C:\Python36\lib\site-packages\sympy-1.1.2.dev0-py3.6.egg\sympy\polys\polytools.py", line 5971, in _generic_factor_list
    raise PolynomialError("a polynomial expected, got %s" % expr)
sympy.polys.polyerrors.PolynomialError: a polynomial expected, got x**2*y**2/b + x**3/a
```

```
>>> factor_list(Poly(x**3/a + y**2*x**2/b), polys=False)
(1, [(y**2/b + x/a, 1), (x, 2)])
```
`factor` also works fine:
```
>>> factor(x**3/a + y**2*x**2/b)
x**2*(a*y**2 + b*x)/(a*b)
```

**Comment by normalhuman** [comment]
I don't think this is a bug. The method `factor_list` expects a polynomial. Passing an expression that is not a polynomial is an error and should be reported as such. 

The input referred to, `x**3/a + y**2*x**2/b`, probably means a polynomial in x and y variables, formally, `Poly(1/a*x**3 + 1/b*x**2*y**2, x, y, domain='ZZ(a,b)')`. But passing it to Poly without specifying the generators creates
```
Poly(x**3*(1/a) + x**2*y**2*(1/b), x, y, 1/a, 1/b, domain='ZZ')
```
a polynomial with four variables instead of two. SymPy cannot guess user's intent here, so it should ask the user to decide if they want `Poly(x**3/a + y**2*x**2, (x, y))` or `Poly(x**3/a + y**2*x**2)` or something else.

**Comment by gxyd** [comment]
Thanks for the explanation @normalhuman :) . Closing this as a non-issue.
