### ISSUE TITLE
Find value of 't' in an arbitrary_point()

### ISSUE THREAD

**Issue by regisin** [sympy/sympy#13075]
I have 2 entities, they are intersecting each other. I can get the point(s) where they intersect. Is there a way to find where in the perimeter that point is?

Something like:

```
p = Polygon((0, 0), (0, 2), (2, 2), (2, 1), (1, 1), (1,0))

ap = p.arbitrary_point()

Eq(expr, Point2D(0,1))
```

PS: I'm not sure I'm using `Eq()` correctly.

**Comment by smichr** [comment]
> where in the perimeter that point is

What do you mean by "where"?

Issue #12613 suggests that there is no `arbitrary_point` method; is this something you added? Or maybe it's been fixed but the issue was not updated.

In your snippets above, I am not sure what `expr` refers to.

One way you could find the location of the intersection on the original object (p?) would be to see if the intersection is one of the vertices, else see which side it intersects with.

```
if intersection in p.vertices:
  print('it is a vertex')
else:
  for s in p.sides:
      if intersection in s:
            print('it is in side', s)
            break
```

**Comment by regisin** [comment]
I have version 1.1 of Sympy (came with anaconda), and apart from issue #, it appears that the method is implemented.

But anyway, I'm sorry for the incomplete/misleading snippet, but you got it right. Now that I know which side it is I can find what the value of 't' would be, given a point in the perimeter.
