### ISSUE TITLE
solve_decomposition misses some equations

### ISSUE THREAD

**Issue by Yathartha22** [sympy/sympy#13121]
While trying to incorporate `solve_decomposition` in [this PR](https://github.com/sympy/sympy/pull/13088), I encountered with its inability to solve some equations, like

```
>>> f = abs(x) - n
>>> solve_decomposition(f, x, S.Reals)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yathartha/.local/lib/python3.5/site-packages/sympy/solvers/solveset.py", line 613, in solve_decomposition
    frange = function_range(g, symbol, domain)
  File "/home/yathartha/.local/lib/python3.5/site-packages/sympy/calculus/util.py", line 143, in function_range
    for critical_point in critical_points:
TypeError: 'ConditionSet' object is not iterable
```
Similarly `f = (a*x + b)*(exp(x) - 3)` raises similar error.

While such equations are solvable by `solveset`, `solve_decomposition` on the other hand fails.

@kshitij10496 @smichr @Shekharrajak.

**Comment by smichr** [comment]
`function_range` is required to solve `f.diff(x)` and while a solution is obtained by solve, one is not obtained by solveset. So although this issue is pertinent for equations that can't be solved, this particular example will hopefully eventually not raise an error when the derivative is solvable by solveset.
