### ISSUE TITLE
Consider converting `sympify(decimal)` to a rational number

### ISSUE THREAD

**Issue by peteroupc** [sympy/sympy#13238]
In SymPy version 1, `sympify("0.2345")` is converted to a `Float` number, that is, a binary floating-point number (presumably the 64-bit `double` -- which moreover might not represent a given decimal number exactly), so that repeated mathematical operations (especially divisions) on the number run the risk of being inexact.  This can be avoided if `sympify` were to convert "0.2345" to a rational number, just as though "0.2345" were "2345/10000" (indeed, a workaround to this issue is to do `sympify("2345/10000")`.  This way, such multiplications and divisions will remain exact and not run the risk of "corruption" due to the nature of the binary floating-point format.

**Comment by asmeurer** [comment]
`sympify` has a rational flag that does just this

```
>>> sympify("0.2345", rational=True)
469/2000
```

The default value is False because we generally assume that if someone enters a number as a float that they want to use the floating point form. Usually if you have a number in floating point format it's "inexact already" because it was output from something else that used floating point. 

You can also use the `Rational` constructor to convert a float to an exact rational.

```
>>> Rational("0.2345")
469/2000
```

Also, I should point out that SymPy's Float is not a 64-bit machine float, but an arbitrary precision float (using mpmath). `sympify` automatically sets the precision high enough to match the number of digits given

```
>>> sympify("0.23454324342343423432432432423432343242")
0.23454324342343423432432432423432343242
```

I'm closing this because the desired behavior is already implemented, and the default of the `rational` flag to `sympify` isn't going to change, but feel free to continue the discussion if you have any other questions.

**Comment by peteroupc** [comment]
Thanks for pointing me to the `rational` flag.  That part of the issue is resolved.

My new question: Does `mpmath` use binary (base-2) or decimal (base-10) arithmetic? If the former, there is the risk that the decimal number won't be representable as a binary fraction (even with arbitrary precision), so that my issue about inexact results will remain.  If the latter, this issue is fully resolved.

**Comment by asmeurer** [comment]
mpmath uses base-2 arithmetic. You can read more about it [here](http://mpmath.org/doc/current/technical.html#representation-of-numbers). There presently isn't a way to do base-10 arithmetic directly in SymPy, although you can use the Python standard library [`decimal` module](https://docs.python.org/3/library/decimal.html) if you are working just with numbers. 

If you are worried about precision, I would recommend doing things with rational and symbolically represented numbers, and converting to a float representation at the end if you need it, using `evalf`. `expr.evalf(N)` will guarantee that the first `N` decimal digits are correct. The default `N` is 15. 

Rational and symbolically represented numbers are the only way to get things completely "exact". Even the `decimal` module truncates numbers to the working precision, and of course for operations like `sqrt` where the floating point number is infinite the only way to stay exact is to use a symbolic representation, which is the whole point of SymPy.

**Comment by peteroupc** [comment]
Base-10 arithmetic in SymPy is not a priority for me, now that I know about the `rational` flag.  Thanks for your response.
