### ISSUE TITLE
TEST_ASCII is not tested

### ISSUE THREAD

**Issue by ylemkimon** [sympy/sympy#13412]
https://github.com/sympy/sympy/blob/e97e23abe86bf8bb8136c827de89b1c74550b587/bin/test_travis.sh#L35-L46

`TEST_ASCII`, ASCII-only environment testing was added in #8364, but has several issues.

* `LC_ALL` environment variable is set to UTF-8(Unicode) in Travis, which overrides `LANG` variable. As a result, Python's stdout encoding is set to UTF-8(Unicode) during `TEST_ASCII`.
* Test failure does not raise Exception and therefore does not fail the Travis build.

Is `TEST_ASCII` necessary?

**Comment by asmeurer** [comment]
See https://github.com/sympy/sympy/pull/8364. It was added because there were some test failures on Windows, which we never knew about until we did a release because we never tested on a non-Unicode lang environment. If LC_ALL takes precedence over LANG we should be setting that for the test instead.
