### ISSUE TITLE
provide a method to disambiguate symbols that print the same

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#13431]
```
>>> t=Tuple(Symbol('_x'), Dummy('x'), Dummy('x')); t
(_x, _x, _x)
>>> t.xreplace(disambiguate_symbols(t.free_symbols))
(_x, _x_1, _x_2)
```
where
```python
>>> def disambiguate_symbols(syms):
...   mapping = {}
...   for s in syms:
...     mapping.setdefault(str(s), []).append(s)
...   reps = {}
...   for k in mapping:
...     if len(mapping[k]) == 1:
...       continue
...     for i in range(1, len(mapping[k])):
...       reps[mapping[k][i]] = Symbol("%s_%i"%(k, i), **mapping[k][i].assumptions0)
...   return reps
```

**Comment by Yathartha22** [comment]
@smichr I would like to take this up.
I am concerned with two things:

- Where should this function be defined?
I think a good place would be in `core.symbols`. Not sure but since this file contains everything related to symbols, it would be a good place to put the function.

- Secondly, one improvement can be done, rather than user explicitly using `xreplace` and passing `t.free_symbols`, the function should take tuple as input and parse the parameter and return the replaced solution implicitly. Like,

```
>>> t=Tuple(Symbol('_x'), Dummy('x'), Dummy('x'))
>>> disambiguate_symbols(t)
(_x, _x_1, _x_2)
```
What do you suggest?

**Comment by smichr** [comment]
I think a good location is symbols, too. And your idea to just pass an object and get the object back with the disambiguated symbols makes sense. If the object passed is not a Basic type then perhaps if it is an iterable or sequence it could be returned as a tuple, e.g. `disambiguate_symbols([Dummy(x),Dummy(x)]) -> [_x_1, _x_2]`
