### ISSUE TITLE
Problem with sympy.physics.wigner

### ISSUE THREAD

**Issue by Kenny3141** [sympy/sympy#13468]
When using the package wigner_9j from sympy.physics.wigner it gives wrong results for some specific wigner 9j symbols. The example given below does in fact only have integer or half-integer input and furthermore fulfills the triangle rule, yet it still returns an error. I cross checked with the module given on the webpage from [Anthony Stone]( http://www-stone.ch.cam.ac.uk/cgi-bin/wigner.cgi?symbol=9j&a=1%2F2&b=1%2F2&c=0&d=1%2F2&e=3%2F2&f=1&g=0&h=1&i=1 ) where you can see that the correct result should be 1/6. I also intrinsically found the same result when comparing with contact matrix elements for the scattering in hadronic molecules. Since the code is rather complicated I could not find the bug myself.

### Reproducing code example:
```
from sympy.physics.wigner import wigner_9j

wigner_9j(1/2,1/2,0, 1/2,3/2,1, 0,1,1 ,prec=16) 

```

### Error message:
```
raise ValueError("j values must be integer or half integer and fulfill the triangle relation")

ValueError: j values must be integer or half integer and fulfill the triangle relation
```

**Comment by jksuom** [comment]
Wigner 9-j symbols are computed as sums of triple-products of Racah coefficients. I have not seen the original reference, but the expression resembles closely the sum of triple-products of 6-j symbols presented in [wikipedia](https://en.wikipedia.org/wiki/9-j_symbol). Only no particular attention is paid to this condition: "the summation extends over all x admitted by the triangle conditions in the factors". Hence the triangle conditions are not always satisfied in all factors.

One way to fix this would be to check the conditions in advance. This would mean that all the tests in `_big_delta_coeff` should be repeated for many different combinations of arguments. 

An easier fix would be catching the ValueError in the summation loop and passing to the next index value. This should give the correct result (assuming that the expression is otherwise correct).

**Comment by yashkgp** [comment]
Hey @jksuom Can i get more info on this one?

**Comment by jksuom** [comment]
Information on Wigner symbols and their variants is probably best found in wikipedia. However, that is not essential for the fix. It should be enough to embed the triple-product computations in a try-block and include in `sumres` only those terms that do not raise ValueError.

**Comment by Trave11er** [comment]
@jksuom, have tried your suggestion (see below) and it no longer gives an error by the result is wrong - my attempt with the OP's input gives the answer of 0 instead of 1/6, so something else is going on. Will have a deeper look.
```
 term = 0
    for kk in range(imin, int(imax) + 1):
        try:
            term = (2 * kk + 1) * \
            racah(j_1, j_2, j_9, j_6, j_3, kk, prec) * \
            racah(j_4, j_6, j_8, j_2, j_5, kk, prec) * \
            racah(j_1, j_4, j_9, j_8, j_7, kk, prec)
            print(kk)
        except ValueError:
            term=0
        sumres = sumres + term
```

**Comment by jksuom** [comment]
Wikipedia says that the summation should extend over *all* x satisfying the triangle conditions. I think that it should also include half-integer values. In other words, the summation should run not over 0, 1, 2, ... but over 0, 1/2, 1, 3/2, 2, ... in steps of 1/2. That can be implemented by replacing `kk` by `kk/2` in the terms and doubling the range of `kk`.

**Comment by yashkgp** [comment]
Hey @jksuom Can i work on this issue?

**Comment by Trave11er** [comment]
@jksuom, changed `int(imax)` to `2*int(imax)` and `2*kk` to `k` however that didn't help and made the answer to the docstring example wrong. Happy to go though the implementation of Wigner functions but since, @yashkgp expressed interest first, I should probably step aside.

**Comment by jksuom** [comment]
> 2*kk to k

And also `kk` to `k/2` as arguments of `racah`?

Examples (also in the docstring) could be checked with Stone's calculator. (If there is something wrong in the implementation, the answer in the docstring example could be wrong.)

If wrong answers persist, I suppose the sum expression should be carefully compared with the original source. There could be a typo in the argument lists of `racah` calls.

**Comment by yashkgp** [comment]
Hey @jksuom and @Trave11er I did the folowing changes in the code  :  
  1.Added Try block in the loop
  2.Doubled the range of kk
  3. Replaced kk by kk/2 (in arguments of ranch too )
```python
    for kk in range(imin, 2*int(imax) + 1):
        try:
            term=(kk + 1) * \
            racah(j_1, j_2, j_9, j_6, j_3, kk/2, prec) * \
            racah(j_4, j_6, j_8, j_2, j_5, kk/2, prec) * \
            racah(j_1, j_4, j_9, j_8, j_7, kk/2, prec)
        except ValueError:
            term=0
        sumres = sumres+term
    return sumres```
It gives answer 1/3 instead of 1/6 but it gives the answer of docstring example right (verfied the answer of docstring example with stone's calculator).I tried to find the problem but couldn't find it .
It would be great if you can help @jksuom

**Comment by Trave11er** [comment]
> And also kk to k/2 as arguments of racah?

Indeed - thanks, @jksuom. Can confirm @yashkgp 's finding that it gives correct answer for the docstring example (which agrees with Stone's calculator) but not for the OP's input.

**Comment by jksuom** [comment]
The wikipedia formula also contains a sign factor. Maybe that should be added to SymPy as well. I would investigate by printing out the terms and trying to figure out if correct results could be obtained by suitable choices of signs.

**Comment by smichr** [comment]
This gives `-1/6`

```python
def w(j_1, j_2, j_3, j_4, j_5, j_6, j_7, j_8, j_9, prec=None):
    imax = min(j_1 + j_9, j_2 + j_6, j_4 + j_8)
    sumres = 0
    for kk in range(0, 2*(int(imax) + 1)):
        k = S.Half*kk
        try:
            sumres +=(-1)**kk*(kk + 1) * \
            racah(j_1, j_2, j_9, j_6, j_3, k, prec) * \
            racah(j_4, j_6, j_8, j_2, j_5, k, prec) * \
            racah(j_1, j_4, j_9, j_8, j_7, k, prec)
        except:
            pass
    return sumres
```

**Comment by jksuom** [comment]
One of the arguments in OP was 3/2. What would `w` give in that case?

**Comment by Trave11er** [comment]
While implementing the fix for the bug reported above have come across a problem with racah coefficients. `racah(1/2, 1, 1/2, 1/2, 1, 3/2)` produces a `ValueError` which is raised by the following statement in sympy.physics.wigner:
`if int(aa + bb - cc) != (aa + bb - cc):
 raise ValueError("j values must be integer or half integer and fulfill the triangle relation")`

Now, if this statement is commented out then the return value of the racah(...) above is 0 instead of expected 1/3 (according to the Stone calculator). Thought I would ask here before opening an issue - does anyone any advice on dealing with it?

**Comment by jksuom** [comment]
There are 6 arguments in the Racah coefficients and they appear in slightly different form in different sources. Fano-Racah, Irreducible tensorial sets (1959), has the following expression

    _  / a b c \
    W |         |
       \ d e f /

Its defining formula looks the same as that denoted in [wikipedia](https://en.wikipedia.org/wiki/Racah_W-coefficient) by  W(a, b, c, d; e, f). I have no access to the reference [Rasch03] given in wigner.py but the code appears to be compatible with the wikipedia definition.

For the interpretation of the arguments there is a more descriptive notation in wikipedia:  

    W(j1, j2, J, j3; j12, j23)

It means that the coefficients are concerned with combining 3 angular momenta  j1, j2 and j3 to a single momentum  J  in 2 different ways:  j1 + j2 -> j12 and  j2 + j3 -> j23. The combination of  j1 and  j2  may take the following values:

    j12 = j1 + j2, j1 + j2 - 1, ..., |j1 - j2|,

and similarly for  j23. With the arguments  1/2, 1, 1/2, 1/2, 1, 3/2 we have  j1, j2, j3 = 1/2, 1, 1/2 and therefore there are 2 allowed values for j12, namely 3/2 and 1/2. The given value j12 = 1 is not acceptable and therefore `racah` raises an exception. In other words, the coefficient is undefined for these argument values. (If it is necessary to assign some value, then it could be 0.) It looks like Stone's calculator has a formula that returns a result even for unacceptable arguments, but I don't think we should rely on those.

**Comment by Trave11er** [comment]
@jksuom can see your point but not sure that j12 is indeed a sum of angular momenta. In particular, [wikipedia -> 6j symbol](https://en.wikipedia.org/wiki/6-j_symbol) gives W(j1,j2, j3, j4; j5, j6) should satisfy 
`j1 = j2 +j3...|j2 - j3|`
and similarly for three other triads. All these four triangular rules are satisfied by 
`racah(1/2, 1, 1/2, 1/2, 1, 3/2)` 
Also, two other online calculators [here](http://dentonwoods.nfshost.com/3j6j9j.html) and [there](http://plasma-gate.weizmann.ac.il/369j.html) agree with Stone for this input (and fail for the forbidden ones tried). Seems should work unless I am missing something.

**Comment by jksuom** [comment]
The ordering of arguments in Racah symbols is not W(j1,j2, j3, j4; j5, j6) but  W(j1, j2, j5, j4; j3, j6) with j3 and j5 swapped. Hence j1, j2, j3 = 1/2, 1, 1 in racah(1/2, 1, 1/2, 1/2, 1, 3/2), which does not satisfy the triangular condition. Note that the triangular condition is symmetric. It means that the sum of the three momenta is an integer and any single one of them is between the sum and the absolute value of difference of the other two (as the sides of a triangle). Hence if j1 = j2 +j3, ..., |j2 - j3|, then also  j3 = j1 + j2, ..., |j1 - j2|.

**Comment by Trave11er** [comment]
Thank you for clarifying, @jksuom, (my previous comment is wrong) - external calculators indeed fail when the correct ordering is used for input.
The function of @smichr above is correct except for the additional '(-1)' factors when we convert from wigner6j to racah coefficient ([see](https://en.wikipedia.org/wiki/6-j_symbol)). In fact we need 
`factor = j_1+j_2+j_9+j_6+j_4+j_6+j_8+j_2+j_1+j_4+j_9+j_8` 
and 
`(-1)**kk -> (-1)**(kk+factor)`
This gives the correct answer of 1/6 for the OP's input. 
This still needs a test for half integer input, but otherwise is good to go?

**Comment by jksuom** [comment]
I think your observation about the extra sign is correct and your code would be good to go. The sum `factor` (another name would be more suitable) is always an integer as it is twice `j_1 + j_2 + j_4 + j_6 + j_8 + j_9` which may be a half-integer, and therefore `(-1)**factor` is 1 or -1.

**Comment by jksuom** [comment]
I would suggest `j_sum = j_1 + j_2 + j_4 + j_6 + j_8 + j_9`.

**Comment by Trave11er** [comment]
Have changed to `j_sum`. Thank you, @jksuom and @smichr for your very generous help.
