### ISSUE TITLE
Use __all__ top-level variable in module files

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#13525]
I have seen `__all__` top-level variable set to list of objects that are imported when we do `from sympy.combinatorics.coset_table import *` I get `bisect_left` which isn't even supposed to be in the module.

Also I think this will reduce import time when doing `from sympy.combinatorics.coset_table import *` (will this also reduce import time for `from sympy import *`? after considering the files like `coset_table.py` has public available classes and functions)

I have seen this often used in scikit-learn source code. This will be easy to fix, once someone comments that it is a good decision to have this.

[Edit]: I know the existence of `__all__` in some of module `__init__` files, but still a large number of them are missing, ex. combinatorics module.

**Comment by pavel-tkachenko** [comment]
@gxyd 
Good day!
I think the `__all__` variable in the `__init__` file do not solve your problem, because you try to import particular module. In this case the `__all__` variable should be contained right in the module file.

**Comment by gxyd** [comment]
Yup, I think we should have them in the module file at the top.

**Comment by pavel-tkachenko** [comment]
@gxyd 
I would like to work on it. Is there any files that shouldn't be edited?

**Comment by asmeurer** [comment]
There are different ways of doing this. The calculus `__init__.py` has each item written out in `__all__` as well as imported, which is duplication, but it also makes pyflakes not give any warnings. You can think of it as double bookkeeping to avoid importing unwanted names. I use this for smaller projects, but I don't know how nicely it would scale to SymPy. The main `__init__.py` would have a ton of entries. On the other hand, it makes it very explicit when something is added to the `import *`. 

There is also the polys way which uses a @public decorator. It's used in a few other modules as well.  It's less explicit (you can't easily see a list of all exported names), and doesn't pass pyflakes, but is less writing. 

I don't think it will reduce the import time. If anything it will increase it (but not noticeably). The main point of `__all__` is to avoid exporting names to `import *` that you didn't mean to export.

**Comment by asmeurer** [comment]
I guess there are two separate issues here:

- `__all__` for module files. In that case, @public works fine, although it shouldn't be required for every submodule, only those for which `import *` on the specific submodule should be a supported API. This is typically those for which names are not exported to an `__init__.py` (otherwise, we should just recommend to `from sympy import` the name).

- `__all__` in `__init__.py`. For this, I think we should use the explicit version. 

I also should point out that `import *` automatically doesn't import names that start with an underscore. So another way to do this is to just make sure all private names start with an underscore, and assume the rest are public.

**Comment by pavel-tkachenko** [comment]
@asmeurer 
Is there any other reason to use `__all__` in `__init__.py` files, except pyflakes warnings?

**Comment by asmeurer** [comment]
The pyflakes warnings aren't an end unto themselves. The whole point of pyflakes is avoiding mistakes. In this case, the mistake would be exporting a name that shouldn't be exported. This is especially a worry if there is code in `__init__.py` (which we only really have in the main `sympy/__init__.py`). But beyond that it would make it very explicit exactly which names are exported, and when a new one is added. Right now there's not even an easy way to see that.

**Comment by asmeurer** [comment]
Another advantage to having `__all__` in `__init__py` is that submodule names would no longer be imported with `import *`. Right now, `from sympy import *` imports every submodule, like `expr` or `ode`. This is not intended behavior; it's incidental to the way that importing works. It's led to a lot of errors for me (especially the `expr` one, which is a variable name I use often), and I imagine it has for others as well.

**Comment by pavel-tkachenko** [comment]
@asmeurer 
Good day!
I have concluded that `from sympy import *` should import only packages (calculus, combinatorics, core, functions, sets, etc). If so, `__all__` is not suitable for this case, because there are name collisions in `__init__.py` right now.

**Comment by asmeurer** [comment]
We definitely should be using `__all__` in every `__init__.py` file, but I don't know if it is worth putting in every `.py` file as well. I only see that as worthwhile for files that aren't included in `__init__.py`, but are still usable by end users. For example, `sympy.utilities.autowrap`. In many cases we should consider whether it's better to just add the functions to `__init__.py`.

**Comment by oscarbenjamin** [comment]
On a basic level `__all__` interacts with the star-import machinery of the interpreter. On a different level though it serves to document the *public* contents of a module. That means that any changes to the public contents can be reviewed so I am in favour of using it everywhere: explicit is better than implicit.

**Comment by asmeurer** [comment]
More files aren't intended to be imported directly. Unless the functions aren't included in an `__init__.py` I would say it's actually bad to use fullly qualified imports outside of library code because it's not a part of the API. That is, we could move a function to a different file or rename a file and it wouldn't be considered an API break. 

However, inasmuch as `__all__` serves as documentation I do agree with you that it can be useful everywhere. Though again, only if we have the proper linting if it's done in a way that duplicates information.

**Comment by jksuom** [comment]
> I don't know if it is worth putting in every .py file as well

When debugging some functions in a file, I usually start with `from sympy.... import *`. Some files put only a few functions (and no classes) in  `__all__`, and then I have to write out explicitly `from sympy.... import xxx, yyy, ...`. I would prefer having no `__all__` in such files.
