### ISSUE TITLE
Geometry: `subs` not working for `arbitrary_point` expressions

### ISSUE THREAD

**Issue by ataber** [sympy/sympy#13653]
Hello,

I'm seeing the following bug in both 2D and 3D lines
```
from sympy.geometry import *
from sympy.abc import t

segment = Segment((0,1), (1,10))
point_equation = segment.arbitrary_point() # <- Point2D(t, 9*t + 1)
ex = point_equation[0] # <- t
ex.subs(t, 0) # <- t, should be 0, in general returns ex
from sympy import lambdify
lambdify(t, ex)(0) # <- t

# just for sanity check
t.subs(t, 0) # <- 0, phewph
from sympy import sympify
sympify(str(ex)).subs(t, 0) # <- 0
```

Hopefully I'm not missing something simple here...

Thanks!

**Comment by smichr** [comment]
If you want to access the point you have to pass it, otherwise a real symbol will be created for you. The `t` that you get for `ex` is not `Symbol('t')` it is `Symbol('t', real=True)`. It should work if you just do 

```python
>>> point_equation = segment.arbitrary_point(t)  # note 't' in parentheses
>>> point_equation[0].subs(t, 0)
0
```

**Comment by smichr** [comment]
Another thing you can do when you run into these issue is to see whether the symbol you are trying to replace is actually in the expression you are working with:

```
>>> point_equation[0].has(t)
False
```
You can also confirm this (in the most recent update to master) with the `disambiguate` function:
```
>>> disambiguate(point_equation, t)
(Point2D(t_1, 9*t_1 + 1), t)
```
That means the `t` in the equation is not the same as the `t` you defined.

**Comment by smichr** [comment]
ping @Yathartha22

**Comment by Yathartha22** [comment]
Agreed with @smichr , we have now `disambiguate` function that can be helpful in cases like yours. `disambiguate` funcition takes in expression with symbols that appear the same but are different(like in yours), and returns numerically subscripted symbols. 
> (Point2D(t_1, 9*t_1 + 1), t)

So since there are numerically substituted symbols, it can be said that they both are different symbols.
 
Checkout the function [here](https://github.com/sympy/sympy/blob/master/sympy/core/symbol.py#L743) and the PR #13517  for more understanding. Hope this may solve your problem, still if you have any doubts feel free to ask.

**Comment by ataber** [comment]
Great, thank you!
