### ISSUE TITLE
Rational on floats and e

### ISSUE THREAD

**Issue by Jwink3101** [sympy/sympy#13656]
I understand **why** this is an issue and that it relates to float precision, but I also think it is something that can and should be easily caught and ameliorated.

Consider the following:

````python
>>> Rational(1.0,2.0)
1/2
>>> Rational(1.1,2.1)
2476979795053773/4728779608739021
# Should read 11/21
````

Again, I understand why this happens, but it seems like an easy case to detect and correct.

**Comment by asmeurer** [comment]
This isn't really fixable. There's no way to distinguish `11/10` and `2476979795053773/2251799813685248` once Python has evaluated them. The only thing SymPy can do is to take the exact floating point number it is given. To do otherwise leads to some issues. We've actually been fixing it in some places where it tried to be "smart" with regards to this (see for instance https://github.com/sympy/sympy/issues/12045). 

The best thing to do is to give Rational strings, so that it can do the exact conversion on the decimal value, rather than the float value, like `Rational('1.1', '2.1')`. 

You can also use `nsimplify`, which has some code to try to be smart about what the float the user probably entered. 

I'm going to close this a "won't fix" because trying to make Rational be "smarter" somehow about floats would go against what it should do (convert the input to a rational exactly), and it would also go against many recent changes in this regard (like https://github.com/sympy/sympy/pull/11998).

**Comment by cbm755** [comment]
IMHO, `Rational(<float>, <float>)` should be an error or warning, at least when the floats are non-integer.  But I suppose that's not very pythonic.

(`Rational(<float>)` of course is a reasonable operation).
