### ISSUE TITLE
Integral over normal cdf evaluates inf

### ISSUE THREAD

**Issue by Ulfgard** [sympy/sympy#13733]
Version 1.1.1 (packaged with Arch Linux).

The following code:
```
from sympy import *
z,x, m = symbols('z x \mu')
s = Symbol('\sigma', positive=True)
pz=exp(-(z-m)**2/(2*s*s))/sqrt(2*pi*s*s) #normal distribution over z
pzgx=simplify(integrate(pz,(z,x,oo))) #p(z>x)
print(integrate(pzgx,(x,0,oo)))

```

returns:

`\mu*erf(sqrt(2)*\mu/(2*\sigma))/2 + sqrt(2)*\sigma*exp(-\mu**2/(2*\sigma**2))/(2*sqrt(pi)) + oo`

which is the correct result up to infinity.

**Comment by jksuom** [comment]
This is what SymPy 1.1.2.dev gives (with m and s instead of mu and sigma):
```
In [11]: integrate(pz, (z, x, oo))
Out[11]: 
     ⎛√2⋅(-m + x)⎞    
  erf⎜───────────⎟    
     ⎝    2⋅s    ⎠   1
- ──────────────── + ─
         2           2
```

**Comment by normalhuman** [comment]
While not denying this is a buggy behavior, I'll point out a workaround that yields the correct result: simplify the antiderivative before plugging in the limits. That is, change the last line to 
```
res = integrate(pzgx, x).simplify()._eval_interval(x, S(0), oo)
```
The internal `_eval_interval` method does the evaluate-and-subtract thing with the antiderivative, including taking limits when needed.  Being internal, the method expects the inputs to be SymPy objects, so plain 0 wouldn't work -- which is why I sympify it with S. The result is 
```
\mu/2 - (-sqrt(pi)*\mu*exp(\mu**2/(2*\sigma**2))*erf(sqrt(2)*\mu/(2*\sigma)) - sqrt(2)*\sigma)*exp(-\mu**2/(2*\sigma**2))/(2*sqrt(pi))
```
which is correct. Tested by numerical evaluation:
```
res.subs({m: 1.23, s: 2.34}).evalf()    #  1.67460134310619
import numpy as np
from scipy.integrate import quad
from scipy.stats import norm
quad(lambda z: 1 - norm(1.23, 2.34).cdf(z), 0, np.inf)[0]     #  1.6746013431061866
```
Simplification helps with a limit, avoiding an issue with `erf` that @symbolique has pointed out.

**Comment by Ulfgard** [comment]
cool, thank you for this workaround! I got around it myself by typing in the correct solution by hand but your way is much better, of course :)

I hope this is going to be fixed t some point!
