### ISSUE TITLE
limit(x**3 / ((b*x - sin(x))*sqrt(a + x)), x, 0) should not be 0

### ISSUE THREAD

**Issue by ethankward** [sympy/sympy#13800]
>>> from sympy import *
    >>> from sympy.abc import a,b,x
    >>> limit(x**3 / ((b*x - sin(x))*sqrt(a + x)), x, 0)
    0
    >>> limit(x**3 / ((1*x - sin(x))*sqrt(3 + x)), x, 0)
    2*sqrt(3)

Interestingly this is also what [Wolfram Alpha](https://www.wolframalpha.com/input/?i=limit+of+x%5E3+%2F+((b*x+-+sin(x))+*+sqrt(a%2Bx))+as+x+-%3E+0) thinks the limit is...

**Comment by normalhuman** [comment]
The sqrt term could be omitted. The point is that `limit(x**3 / (b*x - sin(x)), x, 0)`  is 0 whenever b is different from 1, and is 6 otherwise. When given generic b, SymPy and WA deal with the generic case. I am not sure there is a computer algebra system that will tell you "0 unless b=1, when it's 6".

**Comment by ethankward** [comment]
It's easily expressible in set notation (if limits will eventually support that type of output), or it could be left unevaluated.

**Comment by Roland-Sands** [comment]
If this has not been fixed then I don't think it should be closed
