### ISSUE TITLE
Wrong results for some definite integrals involving large numbers

### ISSUE THREAD

**Issue by TheVirtualMachine** [sympy/sympy#13813]
The following definite integral gives the wrong results in both SymPy and SymPy Gamma:

`integrate (x**9-x**2.5556-(x/(x-3.6**70)), (x,1,2))`

The correct answer is about 99.27 ([WolframAlpha](https://www.wolframalpha.com/input/?i=integrate+(x**9-x**2.5556-(x%2F(x-3.6**70)),+(x,1,2)))), but SymPy evaluates it as 0, and does so on all ranges I have tested.

I have tested this on Fedora using Python 3, and with [SymPy Live](http://live.sympy.org/?evaluate=integrate%20(x**9-x**2.5556-(x%2F(x-3.6**70))%2C%20(x%2C1%2C2))%0A%23--%0Aintegrate%20(x**9-x**2.5556-(x%2F(x-3.6**70))%2C%20(x%2C1%2C2)%2C%20manual%3DFalse)%0A%23--%0Aintegrate%20(x**9-x**2.5556-(x%2F(x-3.6**70))%2C%20(x%2C1%2C2)%2C%20manual%3DTrue)%0A%23--%0A).

Strangely, [SymPy Gamma](http://www.sympygamma.com/input/?i=integrate+%28x**9-x**2.5556-%28x%2F%28x-3.6**70%29%29%2C+%28x%2C1%2C2%29%29) gives a different answer (`- 0.281246484418945 \cdot 2^{3.5556}`), which is also wrong.

Not sure if this is useful, but while I was trying to debug this, I found that using lambdify (I evaluated it at 20 for this) on the integrated function with `math` or `numpy` results in errors, but doing it with `sympy` or `mpmath` will work. However, sympy and mpmath both evaluated the integrated function as a complex number. Both `sympy` and `mpmath` got the same result for the real component. For the imaginary component, `sympy` and `mpmath` got the same value, but `sympy` factored out `pi`.

**Comment by normalhuman** [comment]
The integration works fine, you run into [loss of significance](https://en.wikipedia.org/wiki/Loss_of_significance) due to a giant floating point constant. Inserting floating point numbers in a formula prior to symbolic manipulations is an unfortunately frequent antipattern. It's hard for CAS to do math correctly when [addition isn't associative](https://en.wikipedia.org/wiki/Associative_property#Nonassociativity_of_floating_point_calculation).  

This is the correct approach:
```
a, b = symbols('a b', positive=True)
values = {a: Rational('2.5556'), b: Rational('3.6')**70}
integrate(x**9-x**a-(x/(x-b)), (x, 1, 2)).subs(values).evalf()
```
Returns 99.2742833380370

### Explanation

The integral evaluates to 
```
-2**(a + 1)/(a + 1) + b*log(-b + 1) - b*log(-b + 2) + 1013/10 + 1/(a + 1)
```
The middle terms with b are the killers: they are huge and nearly opposite in sign,  namely `7.83068572914933e+40 + 8.73323313176212e+38*I*pi,`
` -7.83068572914933e+40 - 8.73323313176212e+38*I*pi` 
Recall that double-precision floating point math only has about 16-17 decimal digits available. So the term with e+40 completely obliterates the rest of `-2**(a + 1)/(a + 1), 1013/10, 1/(a+1)`; it's as if they never existed. And then they exactly cancel out (not mathematically but without double precision) and you are left with 0. So... Don't do that.

**Comment by TheVirtualMachine** [comment]
Okay. Is there any reason why SymPy Gamma gives a different (also wrong) result?

**Comment by normalhuman** [comment]
Same reason, essentially. It boils down to the order of terms prior to summation. If they are ordered as 
```
1013/10  +  1/(a + 1)  +  b*log(-b + 1)  -  b*log(-b + 2)   -  2**(a + 1)/(a + 1)
```
then after the aforementioned cancellation of two giant terms, which obliterate those preceding them, we are left with `- 2**(a + 1)/(a + 1)` which is about -3.3. 

This behavior is not special to SymPy. Here is a simplified example in plain Python:
```
>>> sum([42, -3, 1e20, -1e20])    # outputs 0.0
>>> sum([42, 1e20, -1e20, -3])    # outputs -3.0
```

**Comment by TheVirtualMachine** [comment]
Thanks for your help.
