### ISSUE TITLE
SparseMatrix should have its own reshape routine

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#13828]
The following should be about a million times faster with a dedicated reshape routine that just moves around existing elements and does nothing with 0s:

```
>>> s = SparseMatrix.zeros(1000, 1000)
>>> s[0] = 1
>>> s.reshape(1, 10**6)
```

**Comment by vishalg2235** [comment]
@smichr I want to work on this issue. I need some help that routine should create another zero matrix and substitute non zero element or it should modify existing one?

**Comment by vivonk** [comment]
The same thing happens with this
`>>> s = eye(10**5)`
`Traceback (most recent call last):`
`
File "<string>", line 1, in <module>`
`  File "/base/data/home/apps/s~sympy-live-hrd/49.400254913747479351/sympy/sympy/matrices/dense.py", line 1275, in eye`
    `return cls.eye(n)`
  `File "/base/data/home/apps/s~sympy-live-hrd/49.400254913747479351/sympy/sympy/matrices/dense.py", line 529, in eye`
  `  mat = [cls._sympify(0)]*n*n
MemoryError
`

Also, in this case, take very long time
`>>> M = eye(10**4)
`


should we try to improve some MemoryError so that it can be used for large data such as for machine learning problems and optimizations?

**Comment by smichr** [comment]
> The same thing happens with this
```
>>> s = eye(10**5)
Traceback (most recent call last):
 File "<string>", line 1, in <module>
  File "/base/data/home/apps/s~sympy-live-hrd/49.400254913747479351/sympy/sympy/matrices/dense.py", line 1275, in eye
return cls.eye(n)
File "/base/data/home/apps/s~sympy-live-hrd/49.400254913747479351/sympy/sympy/matrices/dense.py", line 529, in eye
 mat = [cls._sympify(0)]*n*n MemoryError
```

**Comment by asmeurer** [comment]
There is already FunctionMatrix in the matrix expressions:

```py
>>> FunctionMatrix(10**3, 10**3, Lambda((i, j), Piecewise((1, Eq(i, j)), (0, True))))
FunctionMatrix(1000, 1000, Lambda((i, j), Piecewise((1, Eq(i, j)), (0, True))))
```

Of course, matrix expressions already have Identity directly:

```py
>>> Identity(10**3)
I
```

Matrix expressions are a much better approach to this problem because they can represent the expression symbolically, meaning it's possible to construct further matrices without evaluating. They are also unevaluated by default meaning you don't have to worry about an operation accidentally trying to evaluate a million matrix entries.

**Comment by oscarbenjamin** [comment]
The OP issue is not hard to fix:
```python
In [12]: M = zeros(1000, 1000)

In [13]: M[0,0] = 1

In [14]: M.todok()
Out[14]: {(0, 0): 1}

In [15]: Matrix.from_dok(*M.shape, M.todok()) == M
Out[15]: True
```
A reshape function can be added that uses `todok`. I haven't added it at the DomainMatrix level because reshaping a matrix isn't generally useful.
