### ISSUE TITLE
Should (x <= y) == (y >= x) return True?

### ISSUE THREAD

**Issue by rbistolfi** [sympy/sympy#13841]
Hello everybody!

I was expecting this to return `True`

`sympy.sympify("x >= 9") == sympy.sympify("9 <= x")`

I have been playing with the code and this seems to do the trick:

```
class _Inequality(Relational):
    ...
    def __eq__(self, other):
        if not isinstance(other, _Inequality):
            return super(_Inequality, self).__eq__(other)
        opposites = [
            set([GreaterThan, LessThan]),
            set([StrictGreaterThan, StrictLessThan]),
        ]
        if set([type(self), type(other)]) in opposites:
            return self.args == tuple(reversed(other.args))
        return super(_Inequality, self).__eq__(other)
```
What do you think? Am I missing something? Is the behavior I expect, reasonable? What about the solution?

Thanks in advance for your time.

**Comment by normalhuman** [comment]
[`==` is meant to test structural equality, not mathematical equivalence](http://docs.sympy.org/latest/gotchas.html#double-equals-signs). For example, `x*(x+1) == x**2+x` is False, and so is x**1.0 == x. It seems undesirable (see #12942) to add special-case logic to make expression appear equal when they are not. 

`GreaterThan(Symbol('x'), Integer(9))` and `LessThan(Integer(9), Symbol('x'))` are structurally different expressions. If one wishes to rest them for _mathematical_ equivalence, some mathematical simplification can help: 
```
sympify("x >= 9").simplify() == sympify("9 <= x").simplify()
```
returns True. This is because the form `GreaterThan(Symbol('x'), Integer(9))` is considered simpler, so both expressions are brought to it by `simplify`.

**Comment by smichr** [comment]
Yes, as @normalhuman says, the `==` is behaving as it should. The `canonical` property or `equals` method are made for purposes of testing things non-structurally:

```
>>> r = x > 9
>>> r == r.reversed
False
>>> r.canonical == r.reversed.canonical
True
>>> r.equals(r.reversed)
True
```

<end of comment; friendly close>

**Comment by rbistolfi** [comment]
It is clear now, thanks a lot for pointing me in the right direction!
