### ISSUE TITLE
Rational doesn't accept Symbols

### ISSUE THREAD

**Issue by nschloe** [sympy/sympy#13883]
I have a function that contains
```python
function something(a, b)
    return sympy.Rational(a, b)
```
When invoked with integers, all is fine. If either `a` or `b`, however, is a `sympy.Symbol`, one get's the error message
```
  File "/usr/local/lib/python2.7/dist-packages/sympy/core/numbers.py", line 1485, in __new__
    raise TypeError('invalid input: %s' % p)
TypeError: invalid input: a
```
This can be worked around with
```python
frac = (
    lambda x, y: x/y
    if any([isinstance(val, sympy.Basic) for val in [x, y]])
    else sympy.Rational(x, y)
    )
```
but it feels weird that sympy functions won't accept symbols.

**Comment by normalhuman** [comment]
I don't find it weird. Rational is a numeric class, like Integer or Float. It is not meant to contain symbolic expressions. An attempt to create an instance of such a class with a symbol is an error and should be reported as such. When you do `x/y` you don't get a Rational, you get an expression (class Mul to be precise). 

What your function really should be doing is 
```
function something(a, b)
    return S(a)/S(b)    # S for sympify, in fact sympifying a is enough.  
```
Then the division happens by SymPy logic: you get a rational number if a and b are integers (or rationals), and you get an expression otherwise. Instead of things like
```
>>> Rational(1, 2/3)
9007199254740992/6004799503160661
```

The only thing I'd change in SymPy behavior here is try to have more graceful exception handling, without "During handling of the above exception, another exception occurred". The error messages are informative enough, but they shouldn't generate more exceptions themselves. 

```
>>> var('x')
>>> Float(x)

Traceback (most recent call last):
  File "/home/ubuntu/sympy/sympy/core/numbers.py", line 1061, in __new__
    _mpf_ = num._as_mpf_val(precision)
AttributeError: 'Symbol' object has no attribute '_as_mpf_val'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/sympy/sympy/core/numbers.py", line 1063, in __new__
    _mpf_ = mpmath.mpf(num, prec=precision)._mpf_
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mpmath/ctx_mp_python.py", line 77, in __new__
    v._mpf_ = mpf_pos(cls.mpf_convert_arg(val, prec, rounding), prec, rounding)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/mpmath/ctx_mp_python.py", line 96, in mpf_convert_arg
    raise TypeError("cannot create mpf from " + repr(x))

>> Integer(x)
Traceback (most recent call last):
  File "/home/ubuntu/sympy/sympy/core/numbers.py", line 1985, in __new__
    ival = int(i)
  File "/home/ubuntu/sympy/sympy/core/expr.py", line 224, in __int__
    raise TypeError("can't convert symbols to int")
TypeError: can't convert symbols to int

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/sympy/sympy/core/numbers.py", line 1988, in __new__
    'Integer can only work with integer expressions.')
TypeError: Integer can only work with integer expressions.
```

**Comment by nschloe** [comment]
```
S(a)/S(b)
```
Just what I needed. Thank you!

I'll leave the bug open in case you want to follow up to the exception simplification. Feel to close at any time.

**Comment by isuruf** [comment]
I think the exception messages are good enough

**Comment by normalhuman** [comment]
On second thought, I agree: the traceback is this way on purpose, because an exception is being raised at one level, handled and then re-raised on another. Python printing "During handling of the above exception, another exception occurred" makes it look like SymPy is falling apart when it's actually designed to work this way. Not SymPy's fault.
