### ISSUE TITLE
Problem with Sympy Integrate

### ISSUE THREAD

**Issue by srinisuja** [sympy/sympy#13898]
Hi, Can someone help with the below as it does not work? I’m not sure what mistake I’ve made. Thanks

from sympy import *
x, y = symbols('x y')
integrate((((3 * pi)/2 - atan((3 - y)/x) - atan((4 - x)/y))/(12 * pi)), (x, 0, 4), (y, 0, (12 - 3 *x)/4))

**Comment by normalhuman** [comment]
With multiple integration limits, integration proceeds from left to right. In other words, the inner integral should have its limits appear first. (And go easy on parentheses, more isn't always better.) Since the integral with y is the inner (its limits involve x) the correct order is `(y, 0, (12 - 3 *x)/4), (x, 0, 4)`. 

Also, constant factors like 12*pi sometimes confuse `integrate` although they really shouldn't. Let's pull the constant factor aside for the moment: 

```
res = integrate(3*pi/2 - atan((3 - y)/x) - atan((4 - x)/y), (y, 0, (12 - 3*x)/4), (x, 0, 4))
(res/(12*pi)).simplify()
```
Output: `(-log(298023223876953125) - 12*atan(4/3) - 12*atan(3/4) + log(84537841287168) + 18*pi)/(24*pi)` 

I didn't expect such numbers, but the answer is correct; I checked its numeric value 0.391672150408749 with SciPy: 
```
import numpy as np
from scipy.integrate import quad
quad(lambda x: quad(lambda y: (3*np.pi/2 - np.arctan((3 - y)/x) - np.arctan((4 - x)/y))/(12*np.pi), 0, (12-3*x)/4)[0], 0, 4)[0]
```
returned 0.39167215040874603

**Comment by srinisuja** [comment]
Thank you for the prompt and helpful reply!

**Comment by normalhuman** [comment]
If your issue is resolved, please indicate that by closing it.
