### ISSUE TITLE
binomial is inconsistent for negative k

### ISSUE THREAD

**Issue by ethankward** [sympy/sympy#13981]
If `k` is negative, there is inconsistency (this is a regression in the development branch, in 1.1.1 they are both 0):

```
>>> binomial(binomial(x - 3, -1), x).subs(x, S(3)/2)
0
>>> simplify(binomial(binomial(x - 3, -1), x)).subs(x, S(3)/2)
-2/(3*pi)
>>> 
```

**Comment by normalhuman** [comment]
The discrepancy is due to [this condition](https://github.com/sympy/sympy/blob/22abf8c122ae128f7188200eaac6f947dafce3bf/sympy/functions/combinatorial/factorials.py#L841), which I'm not convinced should exist at all. Removing it does not cause test failures in series of concrete modules, the only one failing is the assertion `binomial(1, -1) == 0`. 

[Wolfram definition of binomial function](http://functions.wolfram.com/GammaBetaErf/Binomial/02/) is in terms of gamma function, with one exception for integers k <= n < 0.

**Comment by Yathartha22** [comment]
Correct me if I am wrong but I think the above mention case is correct output. What @ethankward has done is substituted the value `3/2` after simplifying the binomial equation, which gets simplified to `sin(pi*x)/(pi*x)`(I guess simplify achieves by converting it to gamma function), which seems to be correct as [evaluated here](http://www.wolframalpha.com/input/?i=binomial(binomial(x-3,++-1),+x)), and therefore the result `-2/(3*pi)`.

What I think you were trying to achieve has to be done as:

```
>>> simplify(binomial(binomial(x - 3, -1), x).subs(x, S(3)/2))
0
```

@normalhuman What I see here is currently `binomial` is not able to solve for negative n and k(more specifically for k<n<0) and when k is rational or n is rational or both.

I will take up this issue.
