### ISSUE TITLE
binomial(0,k) is inconsistent for non-integer k

### ISSUE THREAD

**Issue by ethankward** [sympy/sympy#13980]
If `k` is not an integer, we have inconsistent evaluation / rewriting:

```
>>> binomial(0, x).rewrite(gamma).subs(x, S(3)/2)
-2/(3*pi)
>>> binomial(0, x).subs(x, S(3)/2)
0
```

**Comment by normalhuman** [comment]
The discrepancy is due to [this condition](https://github.com/sympy/sympy/blob/22abf8c122ae128f7188200eaac6f947dafce3bf/sympy/functions/combinatorial/factorials.py#L841), which I'm not convinced should exist at all. Removing it does not cause test failures in series of concrete modules, the only one failing is the assertion `binomial(1, -1) == 0`. 

[Wolfram definition of binomial function](http://functions.wolfram.com/GammaBetaErf/Binomial/02/) is in terms of gamma function, with one exception for integers k <= n < 0.
