### ISSUE TITLE
residue(sin(x**50)/x**51, x, 0) raises an error

### ISSUE THREAD

**Issue by ghost** [sympy/sympy#14037]
The code in residue.py has a weird loop over powers of 2, it can't possibly be correct
I ran this to confirm

**Comment by jksuom** [comment]
The loop over powers of 2 tries to work around a bug in `series`.
```
>>> (sin(x)/x**2).series(x, n=0)
1/x + O(1)
>>> (sin(x**50)/x**51).series(x, n=0)
O(1)  # should be 1/x + O(1)
```
It should be possible to remove the loop when `series` has been fixed.

**Comment by Roland-Sands** [comment]
`>>> (sin(x**50)/x**51).series(x, n=46)`
`O(x**46)`
`>>> (sin(x**50)/x**51).series(x, n=47)`
`1/x + O(x**47)`

**Comment by Roland-Sands** [comment]
When I glanced at the code for calculating the order of a power series,  it seemed to me that it may be fine when the order is a small number like 5, but can't possibly be correct for large orders

**Comment by normalhuman** [comment]
Doubling the number of terms requested seems reasonable to me. This is what `rs_series` (an alternative algorithm based on polynomial manipulations) does as well. 

Repeated differentiations of expressions involving `sin(x**50)` or something similar is not a practical way to expand them into a series. The alternative is to decompose the expression into terms, typically the arguments of Add, Mul and Pow, and request some number n of power series terms from each. When these are combined, it is inevitable that the result will sometimes have fewer than n terms, due to cancellation. So the process is repeated with double number of terms. 

The arbitrary stopping criteria in `series` and `residue` need to be replaced, but I suppose that simply removing them will risk infinite loop when the expression turns out to be a polynomial in some non-obvious way.

**Comment by Roland-Sands** [comment]
Related to #5654

**Comment by sachin-4099** [comment]
In the current master:
```
In [2]: (sin(x**50)/x**51).series(x, n=0)
Out[2]:
1
- + O(1)
x

In [3]: (sin(x)/x**2).series(x, n=0)
Out[3]:
1
- + O(1)
x

In [4]: (sin(x**50)/x**51).series(x, n=46)
Out[4]:
1    / 46\
- + O\x  /
x

In [5]: (sin(x**50)/x**51).series(x, n=47)
Out[5]:
1    / 47\
- + O\x  /
x
```
And `residue(sin(x**50)/x**51, x, 0)` no longer raises any error:
```
In [6]: residue(sin(x**50)/x**51, x, 0)
Out[6]: 1
```

**Comment by goddus** [comment]
I can add the test for this issue
