### ISSUE TITLE
integrate(x**(-1), (x, -1, 1)) gives an imaginary answer

### ISSUE THREAD

**Issue by Roland-Sands** [sympy/sympy#14040]
In [1]: from sympy import *
In [2]: x = Symbol("x")
In [3]: integrate(x**(-1), (x, -1, 1))
Out [3]: -I*pi

**Comment by normalhuman** [comment]
The answer makes sense. By default, x is complex. In the complex plane, the principal branch of log(x) has log(1)=0 and `log(-1)=I*pi`. And since `(log x)' = 1/x`, it follows that the integral should be `log(1) - log(-1) = -I*pi`.

However, it is disappointing that the answer does not change if x is declared real with `x = Symbol("x", real=True)`. Ideally this would force integration to happen within the real line, where the integral of 1/x from -1 to 1 diverges (so the answer would be NaN)

**Comment by Roland-Sands** [comment]
If a function is integrated along a path in C and only the endpoints of the path are given, then I am very surprised that it is not assumed that the path is a straight line

**Comment by Roland-Sands** [comment]
Closely related to #8440 and I think #8170 as well

**Comment by normalhuman** [comment]
Also related to #8918. 

For comparison, `integrate(1/x**2, (x, -1, 1))` returns oo and `integrate(1/x**3, (x, -1, 1))` returns nan. So there is definitely more going on than just finding an antiderivative and plugging the endpoints. The same divergence checks should be able to detect the divergence of 1/x. 

Also, it would be nice to have a "pv" flag for `integrate`, computing the Cauchy principal value.

**Comment by jksuom** [comment]
The divergence checking is done by `._eval_interval()`, which only sees the antiderivative. It tries to find its singularities but the code is currently unable to work with `log`.

A flag for the principal value looks a good idea to me.
