### ISSUE TITLE
Sum((-1)**n/sqrt(n), (n, 1, oo)).is_absolutely_convergent() not implemented

### ISSUE THREAD

**Issue by Roland-Sands** [sympy/sympy#14112]
```
>>> Sum((-1)**n/sqrt(n), (n, 1, oo)).is_absolutely_convergent()`
Traceback (most recent call last):

  File "<ipython-input-23-75eab3fe4b66>", line 1, in <module>
    Sum((-1)**n/sqrt(n), (n, 1, oo)).is_absolutely_convergent()

  File ".\sympy\concrete\summations.py", line 557, in is_absolutely_convergent
    return Sum(abs(self.function), self.limits).is_convergent()

  File ".\sympy\concrete\summations.py", line 428, in is_convergent
    order = O(sequence_term, (sym, S.Infinity))

  File ".\sympy\series\order.py", line 217, in __new__
    expr = expr.as_leading_term(*args)

  File ".\sympy\core\expr.py", line 2864, in as_leading_term
    obj = self._eval_as_leading_term(x)

  File ".\sympy\core\mul.py", line 1625, in _eval_as_leading_term
    return self.func(*[t.as_leading_term(x) for t in self.args])

  File ".\sympy\core\mul.py", line 1625, in <listcomp>
    return self.func(*[t.as_leading_term(x) for t in self.args])

  File ".\sympy\core\expr.py", line 2864, in as_leading_term
    obj = self._eval_as_leading_term(x)

  File ".\sympy\core\function.py", line 741, in _eval_as_leading_term
    '%s has no _eval_as_leading_term routine' % self.func)

NotImplementedError: Abs has no _eval_as_leading_term routine
```

**Comment by vishalg2235** [comment]
@asmeurer @normalhuman I would like to fix this issue, can you guide me how to proceed!

**Comment by normalhuman** [comment]
The method `is_absolutely_convergent` returns `Sum(abs(self.function), self.limits).is_convergent()` (incidentally, that should be Abs). The problem is this:
```
>>> a = (-1)**n / sqrt(n)
>>> Abs(a)
exp(-pi*im(n))*Abs(1/sqrt(n))
```
Even though we are talking about n being an index of a series, it is not treated as an integer (hence real) number. The logical place to enforce assumptions on the index is [here](https://github.com/sympy/sympy/blob/master/sympy/concrete/summations.py#L403), where the series is already reduced to positive-index form. Something like this:
```
sym_ = Dummy(sym.name, integer=True, positive=True)
sequence_term = sequence_term.xreplace({sym: sym_})
sym = sym_
```
should be enough. Then in the rest of computation goes as before. 

In the example given here, after that xreplace the terms will become `1/sqrt(n)` which is known to be divergent by the p-series test.

**Comment by gxyd** [comment]
> (incidentally, that should be Abs)

Documentation of `Abs` says:
```
If you pass a SymPy expression to the built-in abs(), it will
pass it automatically to Abs().
```
So I don't think it is necessary to do so. Since `self.function` is going to be a SymPy object.

**Comment by normalhuman** [comment]
It's not necessary. But using SymPy functions in SymPy expressions is a natural thing to do, and it saves the round-trip to `abs` and back.

**Comment by gxyd** [comment]
Yes, that can be done. If you do so, then do it in other places in `is_convergent` method as well.

**Comment by gxyd** [comment]
Just one more thing, I want to comment. With your suggested code-snippet, I guess the output error (in case it occurs), gives sequence term with dummy expression, like this:
```
In [4]: Sum(sin(n)/n, (n, 1, oo)).is_convergent()
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-4-a000bd8a6a22> in <module>()
----> 1 Sum(sin(n)/n, (n, 1, oo)).is_convergent()
NotImplementedError: The algorithm to find the Sum convergence of sin(_n)/_n is not yet implemented
```
Instead of simply `sin(n) / n` should be printed. I know it wouldn't be hard to do that, but I wanted to leave the comment here, in case I don't get to the PR :)
