### ISSUE TITLE
Sum(1/n, (n, -1, 1)).doit() is complex infinity

### ISSUE THREAD

**Issue by ghost** [sympy/sympy#14126]
```
>>> Sum(1/n, (n, -1, 1)).doit()
zoo
>>> Sum( 1/((n-1)*(n-2)), (n, 2, 4)).doit()
zoo
>>> Sum( 1/((n-1)*(n-2)), (n, 1, 4)).doit()
nan
```

**Comment by rwbogl** [comment]
Why is this an issue? Isn't the first sum `-1 + 1/0 + 1 = 1/0`? I think that `1 / 0` always evaluates as complex infinity in SymPy. Is there some reason that it shouldn't here?

The same is true for the second sum; it has some finite terms plus `1/0`. The third sum is `nan` because it is `-1 / 0 + 1/ 0 + ... = -zoo + zoo = nan`.

**Comment by 0sidharth** [comment]
Is there anything left to be done here? I think the answer being output is fine.

**Comment by 0sidharth** [comment]
Closing as per my previous comment
