### ISSUE TITLE
Small diop_solve bug

### ISSUE THREAD

**Issue by Roland-Sands** [sympy/sympy#14170]
```
>>> pprint(diop_solve(-123*x + 77*y - 3))
(77⋅t₀ + 15, 123⋅t₀ + 24)
>>> diop_solve(2*x + 4*y - 3)
(None, None)
>>> pprint(diop_solve(2*x - 42))
(21,)
>>> diop_solve(-123*x + 3*y + 123*x -17*y - 3)
(None,)
>>> diop_solve(2*x - 3)
(None,)
```
With nicer printing (I used init_printing()), `diop_solve(2*x - 42)` returns `(21)`

**Comment by normalhuman** [comment]
Which one of these is supposed to be a bug? What is the expected behavior? 

`diop_solve` (which, incidentally, is intended for internal use in the Diophantine module) returns a tuple of the length equal to the number of variables in the equation. In the `diop_solve(-123*x + 3*y + 123*x -17*y - 3)` the variable x cancels out before `diop_solve` sees the equation; the input is identical to `diop_solve(-14*y - 3)`. Hence the tuple has length 1 in this example.

**Comment by Roland-Sands** [comment]
You are right `diop_solve(-123*x + 3*y + 123*x -17*y - 3)` and `diop_solve(2*x - 3)` are the same

Expected behaviour is to solve it in 1 variable, which `diop_solve(2*x - 42))` does, just prints an extra comma

Also, this is wrong, there is a solution
```
>>> diop_solve(-123*x + 3*y + 88*x -17*y - 1)
(None, None)
```

**Comment by ArighnaIITG** [comment]
I would like to work on this issue.
Does this issue still exist? Do I need to remove the extra comma?

**Comment by Roland-Sands** [comment]
> I would like to work on this issue

It is not an issue, I was using the wrong function
diop_solve is a function internal to the module, not meant for printing, Diophantine is the function meant for printing
I was using `diop_solve(2*x - 3)` when I should have been using `diophantine(2*x - 3)`, and there is no problem with `diophantine(2*x - 3)`
