### ISSUE TITLE
Bug in could_extract_minus_sign()

### ISSUE THREAD

**Issue by vishalg2235** [sympy/sympy#14233]
Please check the following:
```
>>> from sympy import *
>>> x, y = symbols('x y')
>>> (x - y).could_extract_minus_sign()
False
>>> (y - x).could_extract_minus_sign()
True
>>> (-x + y).could_extract_minus_sign()
True
>>> (-y + x).could_extract_minus_sign()
False
```

**Comment by jksuom** [comment]
I don't think that it is a bug. `y - x` and `-x + y` have the same internal representation.

**Comment by vishalg2235** [comment]
Ok I didn't understood why we can extract minus from `y - x` but not from `x - y` ?

**Comment by smichr** [comment]
A True from this routine means that the minus sign is not distributed in a canonical way. It should always be true that `could_extract_minus_sign(foo) == not could_extract_minus_sign(-foo)`; which of `foo` and `-foo` is canonical is arbitrary. In the case of `x - y` and `y - x` I believe the canonical form is the one that has the first ordered symbol positive. Since x comes lexically before y, `x - y` is the canonical form.
