### ISSUE TITLE
Replace AccumBounds with SetExpr?

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#14251]
`SetExpr` is a wrapper around any set to allow to calculate the new set constructed by arithmetic and set operations on the set.

If a `SetExpr` wraps an closed interval, it works approximately like `AccumBounds`.

Shall we deprecate `AccumBounds`?

**Comment by normalhuman** [comment]
### Limits vs sets

AccumBounds(0, 1) does not quite function like the closed interval [0, 1]: 
```
>>> AccumBounds(0, 1)**oo
AccumBounds(0, oo)
```
The logic here is that if the limit of f(x) is expressed as AccumBounds(0, 1) and the limit of g(x) is oo, 
then the bounds for the limit of `f(x)**g(x)` that we can derive are 0 and oo, not 0 and 1. 

If we think of a static set, `Interval(0, 1)`,  then the logic of limits doesn't come into play, so `[0, 1]**oo` would be the finite set {0, 1}.  

For the same reason, they disagree about the meaning of adding infinity to an interval: 
```
>>> AccumBounds(-oo, 3) + oo
AccumBounds(-oo, oo)
>>> SetExpr(Interval(-oo, 3)) + oo
SetExpr(EmptySet())
>>> AccumBounds(2, oo) + oo
oo
>>> SetExpr(Interval(2, oo)) + oo
SetExpr(EmptySet())
```
The logic of AccumBounds here is: what can we say about lim(f(x)+g(x)), given that lim f(x) is described by the first AccumBounds, and g(x) -> oo?

Other examples:
```
>>> AccumBounds(0, S(1)/2)**oo
0
>>> SetExpr(Interval(0, S(1)/2))**oo
AssertionError
>>> AccumBounds(0, S(1)/2)*oo
AccumBounds(0, oo)
>>> SetExpr(Interval(0, S(1)/2))*oo
TypeError: 'Complexes' object is not iterable
```

### Inequalities

AccumBounds works with inequalities, while SetExpr does not. 
```
>>> AccumBounds(2, 4) < 5
True
>>> SetExpr(Interval(2, 4)) < 5
SetExpr(Interval(2, 4)) < 5
>>> AccumBounds(2, 4) > AccumBounds(0, 1)
True
>>> SetExpr(Interval(2, 4)) > SetExpr(Interval(0, 1))
SetExpr(Interval(2, 4)) > SetExpr(Interval(0, 1))
```

### Functions

The application of trigonometric functions is handled better by AccumBounds.
```
>>> cos(AccumBounds(-1, 2))
AccumBounds(cos(2), 1)
>>> cos(SetExpr(Interval(-1, 2)))
SetExpr(ImageSet(Lambda(x, cos(x)), Interval(-1, 2)))
```
Unless the interval is symbolic, in which case AccumBounds raises an exception.
```
>>> var('a b', real=True)
>>> sin(AccumBounds(a, b))
TypeError: input failed to evaluate
>>> sin(SetExpr(Interval(a, b)))
SetExpr(ImageSet(Lambda(x, sin(x)), Interval(a, b)))
```
SetExpr has an advantage in that reciprocal works better, since it's generally not a single interval. 
```
>>> AccumBounds(-1, 3)**(-1)
AccumBounds(-oo, oo)
>>> SetExpr(Interval(-1, 3))**(-1)
SetExpr(Union(Interval(-oo, -1), Interval(1/3, oo)))
```

**Comment by Upabjojr** [comment]
> If we think of a static set, Interval(0, 1), then the logic of limits doesn't come into play, so [0, 1]**oo would be the finite set {0, 1}.

I see your point.

> For the same reason, they disagree about the meaning of adding infinity to an interval:

I believe your examples are bugs in the current implementation. They need to be fixed.

**Comment by Upabjojr** [comment]
https://github.com/sympy/sympy/pull/14301

Added some more support for `SetExpr`.

**Comment by smichr** [comment]
closing to reopen with specific SetExpr issues; AccumBounds and SetExpr args are of different kinds per #21407
