### ISSUE TITLE
limit_seq(log(sin(n))) is log(<-1, 1>)

### ISSUE THREAD

**Issue by ghost** [sympy/sympy#14276]

**Comment by Roland-Sands** [comment]
```
>>> limit_seq(sin(log(cos(n))))
sin(log(cos(zoo)))
```

**Comment by Roland-Sands** [comment]
```
>>> limit_seq(sin(n)**(log(n)))
<-oo, oo>
>>> limit_seq(sin(n)**(cos(n)))
       <-1, 1>
<-1, 1>       
```

**Comment by Roland-Sands** [comment]
The following limit is from https://math.stackexchange.com/questions/2651471/calculating-a-limit-with-trignonometeric-and-quadratic-function, it is `E`
```
>>> limit_seq((1 + 1/(n**2 + cos(n)))**(n**2 + n))
                      2    
                     n  + n
    ⎛         1     ⎞      
lim ⎜1 + ───────────⎟      
n─→∞⎜     2         ⎟      
    ⎝    n  + cos(n)⎠      
```

**Comment by Roland-Sands** [comment]
Is there code in limit_seq for taking logs when the exponent is a function of n

**Comment by anutosh491** [comment]
> The following limit is from https://math.stackexchange.com/questions/2651471/calculating-a-limit-with-trignonometeric-and-quadratic-function, it is `E`
> 
> ```
> >>> limit_seq((1 + 1/(n**2 + cos(n)))**(n**2 + n))
>                       2    
>                      n  + n
>     ⎛         1     ⎞      
> lim ⎜1 + ───────────⎟      
> n─→∞⎜     2         ⎟      
>     ⎝    n  + cos(n)⎠      
> ```

This works correctly now on master , maybe tests needs to be added but otherwise we have 
```
>>> limit_seq((1 + 1/(n**2 + cos(n)))**(n**2 + n))
E
```
which is the correct result !

**Comment by anutosh491** [comment]
@oscarbenjamin . All results here have been fixed through a merged pr of mine some time back(https://github.com/sympy/sympy/pull/23127) . These shouldn't really be giving results as they are functions defined only periodically at infinity and remains undefined otherwise , hence we cannot really claim the limit would approach a perfect value . For eg

![image](https://user-images.githubusercontent.com/87052487/159146355-c08ea202-0893-4ccc-b2a3-4927f7999ba5.png)

Here the limit at infinity can't be claimed to be `AccumBounds(0, 1)` as it's just defined periodically and could also be `nan` otherwise , hence Kalevi and I had decided to return self for such cases . 
All cases fall into the same category .
So maybe this could be closed or a better option could be to add the Easy-to-fix label here as this only needs 4 tests currently !

Some results are as follows 
```
>>> limit(sin(n)**cos(n), n, oo)
Limit(sin(n)**cos(n), n, oo, dir='-')
>>> limit(sin(log(cos(n))), n, oo)
Limit(sin(log(cos(n))), n, oo, dir='-')
>>> limit(sin(n)**(log(n)), n, oo)
Limit(sin(n)**log(n), n, oo, dir='-')
```

**Comment by oscarbenjamin** [comment]
Marking as easy to fix. This can be closed if someone can check that all cases mentioned above have tests. For any that do not have tests some tests can be added.
