### ISSUE TITLE
Bidirectional limit of floor(sin(x)/x) at 0, is not correct

### ISSUE THREAD

**Issue by sidhantnagpal** [sympy/sympy#14355]
```python
>>> pprint(Limit(floor(sin(x)/x),x,0,'+-'))

    ⎢sin(x)⎥
lim ⎢──────⎥
x─→0⎣  x   ⎦

>>> limit(floor(sin(x)/x),x,0,'+')
1

>>> limit(floor(sin(x)/x),x,0,'-')
1
```
The correct limit should evaluate to 0.
Also confirmed from [WA](http://www.wolframalpha.com/input/?i=limit(floor(sin(x)%2Fx),x,0)).

**Comment by normalhuman** [comment]
Looks like yet another instance of "everything assumed tractable" problem with the Gruntz algorithm implementation, see #14156 and the issues linked there.

**Comment by sidhantnagpal** [comment]
Thank you, I will have a look at the issues.

**Comment by sidhantnagpal** [comment]
Similar problem with the following:
```python
In [1]: limit(floor(-tan(x)/x),x,0,'+')
Out[1]: -1

In[2]: limit(floor(-tan(x)/x),x,0,'-')
Out[2]: -1
```
Answer should be `-2`.

**Comment by 0sidharth** [comment]
The original example does not call `doit`, hence the unevaluated `Limit` object is returned. If `limit` is called, `PoleError` is raised as `gruntz` returns `nan` for both limits - 
```py
In [1]: gruntz(floor(sin(x)/x), x, 0, '+')
Out[1]: nan

In [2]: gruntz(floor(sin(x)/x), x, 0, '-')
Out[2]: nan

In [3]: limit(floor(sin(x)/x), x, 0, dir='+-')
---------------------------------------------------------------------------
PoleError                                 Traceback (most recent call last)
<ipython-input-3-0c5ec5b32524> in <module>
----> 1 limit(floor(sin(x)/x), x, 0, dir='+-')

~/sympy/sympy/series/limits.py in limit(e, z, z0, dir)
     61     """
     62 
---> 63     return Limit(e, z, z0, dir).doit(deep=False)
     64 
     65 

~/sympy/sympy/series/limits.py in doit(self, **hints)
    378                 r = gruntz(e, z, z0, dir)
    379             if r is S.NaN or l is S.NaN:
--> 380                 raise PoleError()
    381         except (PoleError, ValueError):
    382             if l is not None:

PoleError: 
```

**Comment by anutosh491** [comment]
I guess this doesn't give a `PoleError` anymore on master 
```
>>> limit(floor(sin(x)/x), x, 0, dir='+-')
1
```
This is because `(floor(sin(x)/x)).as_leading_term(x)` gives back `1` . Is this what we expect ?? I'm not sure here @jksuom

**Comment by anutosh491** [comment]
I haven't given too much thought here , but just trying to find any sort of workaround here . I thought of checking how an expression inside floor would behave . So I took the example of `cos(x)` (just because `limit(floor(cos(x)))` at `0` would be `0`)
And I'm not sure why the order term is disturbing the scenario here 
```
>>> limit(floor(1 - x**2/2 + x**4/24 + O(x**6)), x, 0)
1
>>> limit(floor(cos(x)), x, 0)
0
>>> limit(floor(1 - x**2/2 + x**4/24 - x**6/720), x, 0)
0
>>> limit(floor(1 - x**2/2 + x**4/24 - O(x**6)), x, 0)
1
```

**Comment by anutosh491** [comment]
Okay so gruntz fails because we didn't have proper implementation of series for floor at some points , check this out 
```
>>> (floor(sin(x)/x)).series(x)
nan
>>> # Therefore
>>> gruntz(floor(sin(x)/x), x, 0)
nan
```
Catching this in `_eval_nseries` of floor , I can see that we do substitute `0` in `sin(x)/x` through `arg0 = arg.subs(x, 0)` , and there is no check for `nan` cases . Now some basic intuition (through graph plotting) says that we could have something like 

```
>>> floor(expr).series(x)
floor(expr.series(x))
```
Hence this diff will give us the correct answer through gruntz ! Also addresses this comment(https://github.com/sympy/sympy/issues/14355#issuecomment-372121314)
```
--- a/sympy/functions/elementary/integers.py
+++ b/sympy/functions/elementary/integers.py
@@ -170,6 +170,10 @@ def _eval_nseries(self, x, n, logx, cdir=0):
             return s + o
         r = self.subs(x, 0)
         if arg0 == r:
+            if arg0 is S.NaN:
+                series = arg.series(x, n)
+                ndir = arg.dir(x, cdir=cdir if cdir != 0 else 1)
+                return floor(series) - 1 if ndir.is_negative else floor(series)
             ndir = arg.dir(x, cdir=cdir if cdir != 0 else 1)
             return r - 1 if ndir.is_negative else r
         else:
```

```
>>> gruntz(floor(sin(x)/x), x, 0, '-')
0
>>> gruntz(floor(sin(x)/x), x, 0, '+')
0
>>> gruntz(floor(-tan(x)/x),x,0,'+')
-2
>>> gruntz(floor(-tan(x)/x),x,0,'-')
-2
```
But limit still fails because these return wrong answers through leading term methods . I am not fully sure what's going wrong though , could you'll have a look @jksuom @0sidharth !

**Comment by jksuom** [comment]
It seems that this should be handled by `Limit.doit` without `gruntz`. `(floor(sin(x)/x)).as_leading_term(x)` should give 0.
