### ISSUE TITLE
RuntimeError in subs

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#14392]
`((-sin(1/x)**2 + 1)).subs(x,0)` raises `RuntimeError: maximum recursion depth exceeded`

**Comment by normalhuman** [comment]
Subs actually works: `expr = ((-sin(1/x)**2 + 1)).subs(x,0) ` returns a valid expression, specifically `Add(1, -sin(zoo)**2)`; or simply put, `1 - sin(zoo)**2`. 

The problem is that `expr.as_ordered_terms()` runs into infinite recursion; this method is used to produce a string representation of the expression.  So, the minimal test case is
```
(1-sin(zoo)**2).as_ordered_terms()
```
