### ISSUE TITLE
check if it is ok to use sympy in our open-sourced project

### ISSUE THREAD

**Issue by liupibm** [sympy/sympy#14428]
First, thanks for the excellent package provided to the public community.

I have built a sympy-based backends for IBM open source quantum package qiskit. 
Before we merge it, could you advise if your license allows me to do so?
Here are more details:
https://github.com/QISKit/qiskit-sdk-py/pull/217

Thanks for your attention. Not sure this is the right place to discuss the matter, feel free to close the issue if not.

**Comment by moorepants** [comment]
@liupibm You are welcome to copy and distribute SymPy as long as you follow the terms of our license.

**Comment by asmeurer** [comment]
If you have copied code from SymPy (it should not generally be necessary if you are just importing the code), then you should copy the SymPy license and include it with that code. Otherwise, there are no other requirements. The BSD license used by SymPy is very liberal. The only requirement is basically what I said above, that if you copy code, you have to indicate so by including the license somewhere. But the resulting code does not itself have to be BSD licensed, nor are there any restrictions on simply using the code (importing it).  I recommend reading the SymPy [BSD license](https://github.com/sympy/sympy/blob/master/LICENSE). It is very short and straightforward. 

Also, if you end up writing an academic paper for the software that uses SymPy, we do request that you [cite our SymPy paper](https://github.com/sympy/sympy#citation) (this is not required by the license, simply a request on our part). 

Let us know if you have any more questions. We always like to hear about people who are using SymPy.

**Comment by liupibm** [comment]
@moorepants @asmeurer Thanks a lot for the clarification!
