### ISSUE TITLE
Using `BlockMatrix` to concatenate two matrices

### ISSUE THREAD

**Issue by qnzhou** [sympy/sympy#14505]
Hi there,

My colleague and I are trying to concatenate two matrices together in a `numpy.hstack` manner.   Here is our attempts:

``` python
Python 2.7.14 (default, Sep 27 2017, 12:15:00) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sympy
>>> sympy.__version__
'1.1.1'
>>> X = sympy.MatrixSymbol('X', 2, 2)
>>> Y = sympy.MatrixSymbol('Y', 2, 1)
>>> X.shape
(2, 2)
>>> Y.shape
(2, 1)
>>> B = sympy.BlockMatrix([X, Y])
>>> B.shape
(4, 2)
>>> B = sympy.BlockMatrix([[X], [Y]])
>>> B.shape
(4, 2)
```

The correct output should have shape `(2, 3)`.  Is concatenating matrices columnwise is impossible using `sympy.BlockMatrix`?

**Comment by normalhuman** [comment]
I think you want `BlockMatrix([[X, Y]])`. 
```
>>> BlockMatrix([[X, Y]]).shape
(2, 3)
>>> BlockMatrix([[X, Y]]).as_explicit()
Matrix([
[X[0, 0], X[0, 1], Y[0, 0]],
[X[1, 0], X[1, 1], Y[1, 0]]])
```
The notation [X, Y] is a shorthand for [[X], [Y]], both mean vertical stacking.
```
>>> Matrix([1, 2])
Matrix([
[1],
[2]])
>>> Matrix([[1], [2]])
Matrix([
[1],
[2]])
```

Your matrices cannot really be stacked vertically, since they have different number of columns. BlockMatrix ought to check this at once, but it doesn't, and instead outputs strange shape parameters. That the construction is invalid becomes clear with `BlockMatrix([X, Y]).as_explicit()` which throws an error.

**Comment by normalhuman** [comment]
So I think the issue here is that BlockMatrix should check the compatibility of shapes at the time of  construction.

**Comment by andrewhalle** [comment]
Beginner here, going over issues to familiarize myself with the codebase. Since BlockMatrix instantiates itself as an ImmutableDenseMatrix, perhaps checking compatibility of shapes should occur in that class?

**Comment by normalhuman** [comment]
I don't think so, because ImmutableDenseMatrix need not look inside of the objects it is given. Forming `Matrix([a, b])` is valid for any two SymPy expressions a, b.  For example,
```
>>> a = Matrix([1, 2])
>>> b = Matrix([1, 2, 3])
>>> c = Matrix([[a, b]])
>>> c.shape
(1, 2)
```
This is valid because c is a 1 by 2 matrix with entries a, b and it has no concern about what those entries are. 

While this isn't right:
```
>>> c = BlockMatrix([[a, b]])
>>> c.shape
(2, 2)
>>> c.as_explicit()
Matrix([
[1, 1],
[2, 2]])
```
or 
```
>>> c = BlockMatrix([[b, a]])
>>> c.shape
(3, 2)
>>> c.as_explicit()
IndexError: Index out of range: a[2]
```

**Comment by smichr** [comment]
> BlockMatrix should check the compatibility of shapes at the time of construction

See also #16278

lightly tested and edited after that)
```python
@@ -47,8 +47,22 @@ class BlockMatrix(MatrixExpr):
    """
    def __new__(cls, *args):
        from sympy.matrices.immutable import ImmutableDenseMatrix
        from sympy import Matrix
        from sympy.utilities.iterables import is_sequence
        raw = lambda i: is_sequence(i) and not isinstance(i, Matrix)
        assert len(args) == 1 and raw(args[0])  # BlockMatrix([A, B]) or BlockMatrix([[A, B]])
        args = args[0]
        if args:
            if not raw(args[0]):
                args = [[i] for i in args]]  # BlockMatrix([A, B]) -> BlockMatrix([[A], [B]])
            assert all(isinstance(i, Matrix) for i in r for r in args)
            # same number of blocks in each row
            assert len(set([len(r) for r in args])) == 1
            for r in args:
                # row height of each element in row is the same
                assert len(set([i.rows for i in r])) == 1
            ncol = len(args[0])
            for i in range(ncol):
                # col width of each element in col is the same
                assert len(set([r[i].cols for r in args])) == 1
        return ImmutableDenseMatrix(args)  # do not pass as *args since it is a list of lists
```

A "PatchMatrix" comprised of blocks that cannot be partitioned into a grid can be constructed as shown in #16278 but rather than specifying ntop, the rows could be given just like BlockMatrix:
```
Matrix([
    [1, 2, 2, 2, 3, 3],
    [1, 2, 2, 2, 3, 3],
    [4, 2, 2, 2, 5, 5],
    [6, 6, 7, 7, 5, 5]])
```
would be entered as
```
PatchMatrix([
[ones(2,1), ones(3,3)*2, ones(2,2)*3], 
[ones(1)*4, ones(2,2)*5], 
[ones(1,2)*6, ones(1,2)*7]])
```
`ntop` of the `B` routine is just `len(row[0])` and `matrices = [i for r in rows for i in r]`.
