### ISSUE TITLE
Problem with limit including factorial.

### ISSUE THREAD

**Issue by slacker404** [sympy/sympy#14502]
Sympy evaluates this limit correctly

limit(factorial(x)-x**x, x, oo)
-oo

On the other hand, for this limit

 limit(factorial(x)-x**oo, x, oo)
oo

which is incorrect.
The correct answer is that the limit is indeterminate

Any ideas?

**Comment by normalhuman** [comment]
SymPy's behavior is incorrect here, but the expected answer is not correct either. 

To the extent that `x*oo` makes sense at all, it is `oo` when x is a number greater than 1. Since factorial(x) is a finite number, the expression `factorial(x) - x**oo` evaluates to `-oo` for every x. Hence, its limit would be `-oo`. 

While infinite quantities are useful to represent the outcome of a computation, limit direction, and integration limits, using them in expressions is likely to break some logic. 
```
>>> diff(x*oo, x)
oo
>>> integrate(x**oo, (x, 1, 2))
0
```

I think expressing `x**oo` as `Piecewise((0, Abs(x) < 1), (oo, x > 1), (1, x == 1), (S.NaN, True))` would be correct and avoid some (not all) of the issues. But in practice, I would go back to the point where `factorial(x)-x**oo` came from, and asked why.

**Comment by slacker404** [comment]
The factorial(x) - x** oo is just a random example. The same is true for every function that lim(f(x),x, oo)) = oo instead of the factorial . I want to find out how Sympy handles a limit like that lim (f(x) - x**g(x) , x , oo) where lim(g(x),x,oo) = oo for a random g

**Comment by normalhuman** [comment]
So, what is an actual example of a limit where you get an incorrect answer?

**Comment by slacker404** [comment]
I might have expressed it wrong. I am talking about a function that we do not actually know its formula. The only information we have is that  its limit in oo is oo and we want to do a calculation with that

**Comment by normalhuman** [comment]
Yes, there is an issue with undefined functions, #14156.

**Comment by slacker404** [comment]
I think I have an idea how to fix that. I'll try to put it in my gsoc application

**Comment by anutosh491** [comment]
Currently return the following on master which could be agreed to, maybe `x**oo` could have a piecewise implementation but others doesn't seem wrong !
```
>>> limit(factorial(x)-x**oo, x, oo)
Limit(-x**oo + factorial(x), x, oo, dir='-')
```

**Comment by anutosh491** [comment]
Closing, as this comes out of the following block , for which we already have decent amount of basic tests catering to all cases below !
```
            if coeff.has(S.Infinity, S.NegativeInfinity, S.ComplexInfinity, S.NaN):
                return self
```
The expression `limit(factorial(x)-x**oo, x, oo)` with/without the factorial or with other arguments would also return `self` , so not sure if adding this as a test adds value to the code !
