### ISSUE TITLE
limit: SymPy returns unevaluated limit

### ISSUE THREAD

**Issue by abaokar-07** [sympy/sympy#14525]
The following limit comes out unevaluated:
```
In [1]: func = sin(x)**2 - cos(x) + tan(x)*csc(x)
In [2]: limit(func, x, oo)
Out[2]:
     /   2                            \
 lim \sin (x) - cos(x) + tan(x)*csc(x)/
x->oo
```

**Comment by abaokar-07** [comment]
Can somebody review this issue, maybe @normalhuman or @jksuom ?
Is there any way to work around this or it is a valid issue?

**Comment by jksuom** [comment]
The limit of this periodic `func` does not exist. There is an open PR https://github.com/sympy/sympy/pull/13897 on this issue.

**Comment by abaokar-07** [comment]
Okay, thanks

**Comment by anutosh491** [comment]
This currently returns a not implemented error without any particular error message . I'm sure there are better ways to even give out a `NotImplementedError` than this

**Comment by anutosh491** [comment]
Currently we don't have any tests in either `test_limits.py` or `test_gruntz.py` which faces this situation ! Here `calculate_series(f, w, logx=logw)` of `gruntz.py` gives a `NotImplementedError`. This is because `expr.nseries` for some expressions used to give `PoleError` earlier but now give `NotImplementedError`. But as there are no tests for this currently I realize this will only be encountered for expressions which used to give `PoleError` earlier but now give `NotImplementedError`.

Hence this diff would do the job for us ! @jksuom what do you think ?? I propose this not that it fixes this issue . But in case of limits I feel we should just be expecting one of these 3 outputs
1) the value of the expression if sympy can compute
2) NotImplementedError (for cases returned from calculating parametric limits through gruntz, depending on sign etc)
3) or the limit object itself if nothing works ! (which is this cases)
```

diff --git a/sympy/series/gruntz.py b/sympy/series/gruntz.py
index c28a631e32..d9f3678801 100644
--- a/sympy/series/gruntz.py
+++ b/sympy/series/gruntz.py
@@ -543,7 +543,10 @@ def mrv_leadterm(e, x):
     #
     w = Dummy("w", positive=True)
     f, logw = rewrite(exps, Omega, x, w)
-    series = calculate_series(f, w, logx=logw)
+    try:
+        series = calculate_series(f, w, logx=logw)
+    except NotImplementedError:
+        raise PoleError
     try:
         lt = series.leadterm(w, logx=logw)
     except (ValueError, PoleError):
```

**Comment by anutosh491** [comment]
Trying expressions randomly It's not very tough to find cases like these. The fix makes them return self rather than the `NotImplementedError` from `_eval_nseries` . for eg
```
>>> from sympy import *
>>> x = Symbol('x')

>>> func = sin(x)**2 - cos(x) + sin(x)*cot(x)
>>> limit(func, x, oo)
Limit(sin(x)**2 + sin(x)*cot(x) - cos(x), x, oo, dir='-')

>>> func = sin(x)**2 - sin(x)*cot(x)
>>> limit(func, x, oo)
Limit(sin(x)**2 - sin(x)*cot(x), x, oo, dir='-')

>>> func = cos(x)**2 - sin(x)*cot(x)
>>> limit(func, x, oo)
Limit(-sin(x)*cot(x) + cos(x)**2, x, oo, dir='-')

>>> func = cot(x) - tan(x)**2
>>> limit(func, x, oo)
Limit(-tan(x)**2 + cot(x), x, oo, dir='-')

>>> func = sin(x)**2 - tan(x)**2
>>> limit(func, x, oo)
Limit(sin(x)**2 - tan(x)**2, x, oo, dir='-')

>>> func = sin(x)**3 - tan(x)**2
>>> limit(func, x, oo)
Limit(sin(x)**3 - tan(x)**2, x, oo, dir='-')
```
All these return `NotImplementedError` on master but previously used to return `self` before the nseries call used to return `PoleError` earlier now returns `NotImplementedError` . @jksuom could we go forward with the above reported diff ?

**Comment by jksuom** [comment]
Functions like this should be handled by `Limit.doit` *before* calling `gruntz` that cannot deal with periodic functions. It might be possible to modify the leading term methods to return an `AccumBounds` or nan that could be returned.

**Comment by anutosh491** [comment]
> Functions like this should be handled by `Limit.doit` _before_ calling `gruntz` that cannot deal with periodic functions. It might be possible to modify the leading term methods to return an `AccumBounds` or nan that could be returned.

I completely get your point here . `gruntz` should be responsible for this . I have a similar doubt in one of my prs where I would like you guidance (https://github.com/sympy/sympy/pull/22905#issuecomment-1028969731) . It would eventually help for this issue ! Thank you for your suggestions .
