### ISSUE TITLE
false error message with Eq() and quantities in log()

### ISSUE THREAD

**Issue by schymans** [sympy/sympy#14547]
I believe the below is a bug:
```python
from sympy import Eq, log
from sympy.physics.units import Quantity, mass, gram, kilogram, length, meter
m1 = Quantity('m_1', mass, kilogram)
m2 = Quantity('m_2', mass, kilogram)
m3 = Quantity('m_3', mass, kilogram)
print log(m1 + m2) - log(m3)
try:
    eq1 = Eq(log(m3), log(m1 + m2))
    print eq1
except Exception, error:
    print error
```
returns:
```python
-log(m_3) + log(m_1 + m_2)
summation of quantities of incompatible dimensions
```
`log(m_3)` has the same dimensions as `log(m1 + m2)`, so the error message is wrong. Interestingly, the error message does not pop up in the summation, so it might be something related to `Eq()`.

**Comment by czgdp1807** [comment]
I am working on this issue. I found out that the problem begins from `fin = L, R = [i.is_finite for i in (lhs, rhs)]`. Now I am unable to figure how to goes on to  `File "/home/gagandeep/anaconda3/lib/python3.6/site-packages/sympy/physics/units/quantities.py", line 173, in _Quantity_constructor_postprocessor_Add
    raise ValueError("summation of quantities of incompatible dimensions")`.
Can you please help me in fixing this issue? Any hint will be welcomed. :-)

**Comment by schymans** [comment]
`_Quantity_constructor_postprocessor_Add` should raise an exception if the dimensions of summands are incompatible. I have no idea why it raises an exception in this case, as the dimensions of `m_1`, `m_2` and `m_3` are the same. If you type `log(m1 + m2) - log(m3)`, no exception is raised, so it works correctly. The weird thing is that it raises an exception if we put the same expression in `Eq()`. Can you see what is done differently in `Eq(log(m3), log(m1 + m2))`?

**Comment by czgdp1807** [comment]
Hopefully I have found out the problem. Going to fix it as soon as possible. :-)

**Comment by czgdp1807** [comment]
While fixing the issue I found one weird thing, when I replace, `eq1 = Eq(log(m3), log(m1 + m2))` with `eq1 = Eq(log(m1), log(m2 + m3))`, it successfully executes and gives the output `Eq(log(m_1), log(m_2 + m_3))`. Can you explain the reason behind this?

**Comment by czgdp1807** [comment]
I think there is an issue with `log(m1)`. According concepts of dimensional analysis, `log(x)`, x should be dimensionless. I think the weird behavior is due to this passing a dimensional quantity into log. I have also noticed that sometimes, `eq1 = Eq(log(m3), log(m1 + m2))` executes correctly and sometimes throws errors which begin at `dif.is_zero` and sometimes at `n.is_zero`.

**Comment by schymans** [comment]
Good point about log(unit) and dimensional analysis! According to https://en.wikipedia.org/wiki/Dimensional_analysis, the basic rule ` log(a/b) = log a − log b` is only valid if both a and b are non-dimensional. Otherwise, even if a and be have the same unit, the lhs would be dimensionless, but the rhs would have units of log(unit). See also this discussion: https://physics.stackexchange.com/questions/13060/what-is-the-logarithm-of-a-kilometer-is-it-a-dimensionless-number
Does this mean that variables in log() and exponents have to be unit-less? This would also mean that derivations resulting from log-log plots do not have a physical meaning. I must have misunderstood something.

**Comment by czgdp1807** [comment]
Yes they do have as far as the knowledge I have gained from [this](https://cdn-pubs.acs.org/doi/pdfplus/10.1021/ed072p954) paper. Actually what this document says is that we should divide the quantity x by its unit dimensions so that it becomes dimensionless, like log(x) is actually log(x/units(x)), units(x) denotes the units of x. Now, what I am trying to do is, convert `arg` in `log(arg)` to symbol whenever it is an instance of class of `Quantity`. I am not sure that it would fix the issue but it would definitely strengthen the conceptuality of `log`, `exp` and `trig` methods in sympy. The problem I faced is that, when `arg = a+c+d*e/f` then it becomes tricky to convert each of a,c,d,e, and f to symbols and then reusing them again in the expression of `arg`. Can you please help me by providing hints or solutions to this problem. 
In addition, I tried to make `arg` dimensionless by redefining it as `arg = Quantity(arg.name, Dimension(1))` but `arg` returned the dimension it originally had. That's why I resorted to converting it to symbols.
Waiting for your response.

**Comment by schymans** [comment]
Awesome paper, thanks for sharing! In my understanding, the paper does not say that we should divide x by its unit, but that fundamentally terms in logarithms are unit-less, and if they are not, such as e.g. `mu_i = mu_i0 + R*T*log(p_i)` this is because we mistakenly omitted division by a standard value, i.e. this should in fact be: `mu_i = mu_i0 + R*T*log(p_i/p0)`
Thus, all we should do is allow log(Quantity) as long as Quantity is dimensionless. I would not convert to symbols, as this could get very confusing.

**Comment by czgdp1807** [comment]
Sure, I will implement the method you have agreed upon and will try to submit a PR as soon as possible. Thanks for helping me out with my queries. :-)

**Comment by schymans** [comment]
One of the challenges will be to make `print log(m1 + m2) - log(m3)` and `Eq(log(m3), log(m1 + m2))` return the same (informative) error if m1, m2 and m3 are not non-dimensional. I don't understand why only one returns an error. Thanks for looking into this!

**Comment by czgdp1807** [comment]
I have created a PR for solving the issue. My code converts any dimensional expression passed to log into dimensionless expression and then the further processing is done. However, there is no effect on the original quantities. I have verified on a local program and `Eq(log(m3), log(m1 + m2))` was executed successfully after applying the above mechanism. I can confirm by adding an appropriate test, though I am finding it quite tricky to find a good test for this issue. Can you please suggest such tests?

**Comment by smichr** [comment]
> In my understanding, the paper does not say that we should divide x by its unit, but that fundamentally terms in logarithms are unit-less

I think the author means that we must "include" the units. And there is no reason to think of logarithms as unit-less (any more than we need to think of numbers, as is mentioned in the paper, as positive).

Units multiply a numerical quantity and have the normal behavior when taking logarithms. It is perfectly fine to plot log(T) vs time where T is some thickness. The offset of the plot will depend on what units are used for T and *must be indicated* on the plot.

For example, such a plot for T measured in feet would have to be labelled 'log(T) - log(foot) vs time' so a value of "3" on the graph would correspond to log(T) - log(foot) = 3:

```
>>> var("T foot")
(T, foot)
>>> solve(Eq(log(T)-log(foot), 3), T)
[foot*exp(3)]
```

It is also natural to plot the log of ratios like `log(T/T0)` in which case the argument is dimensionless.

The first case is, with simplification, equivalent to the second by identifying T0 as "1 foot": `log(T) - log(foot) = log(T/foot)`.

There is no need to insist that arguments be dimensionless, only that we be specific. The units always take care of themselves as long as we keep track of them.

> log(a/b) = log a − log b is only valid if both a and b are non-dimensional. Otherwise, even if a and be have the same unit, the lhs would be dimensionless, but the rhs would have units of log(unit).

No, the units would cancel:

```
>>> log(3*foot) - log(2*foot)
-log(2*foot) + log(3*foot)
>>> expand(_)
-log(2) + log(3)
>>> simplify(_)
log(3/2)
>>> _==log(3*foot/(2*foot))
True
```

What if different units were used? No problem:

```
>>> var('foot inch', positive=True)
(foot, inch)
>>> expand(log(2*foot)-log(3*inch))
log(foot) - log(inch) - log(3) + log(2)
>>> _.subs(foot, 12*inch).expand()
-log(3) + log(2) + log(12)
>>> _.n()
2.07944154167984
>>> simplify(log(2*foot)-log(3*inch))
log(2*foot/(3*inch))
>>> _.subs(foot, 12*inch).n()
2.07944154167984
```

The root cause of the error described in the OP is the test to see if log(arg) is finite or not by testing to see if it is 1 or not here:

```
  File "\sympy\functions\elementary\exponential.py", line 730, in _eval_is_zero
return (self.args[0] - 1).is_zero
```

So `log(foot).is_finite` ends up requesting whether log(foot) is zero and this becomes `(foot - 1).is_zero` and the error is generated there. I don't think there is any assumption available for x that would allow one to know that log(x) is finite. You might consider this:

```diff
diff --git a/sympy/functions/elementary/exponential.py b/sympy/functions/elementary/exponential.py
index d602072..e4a1c2b 100644
--- a/sympy/functions/elementary/exponential.py
+++ b/sympy/functions/elementary/exponential.py
@@ -693,12 +693,19 @@ def as_real_imag(self, deep=True, **hints):
         else:
             return (log(abs), arg)
 
+    @property
+    def _arg_is_1(self):
+        from sympy.physics.units import Quantity
+        if self.has(Quantity):
+            return False  # it's 0 or has dimensions
+        return (self.args[0] - 1).is_zero
+
     def _eval_is_rational(self):
         s = self.func(*self.args)
         if s.func == self.func:
-            if (self.args[0] - 1).is_zero:
+            if self._arg_is_1:
                 return True
-            if s.args[0].is_rational and fuzzy_not((self.args[0] - 1).is_zero):
+            if s.args[0].is_rational and fuzzy_not(self._arg_is_1):
                 return False
         else:
             return s.is_rational
@@ -706,9 +713,9 @@ def _eval_is_rational(self):
     def _eval_is_algebraic(self):
         s = self.func(*self.args)
         if s.func == self.func:
-            if (self.args[0] - 1).is_zero:
+            if self._arg_is_1:
                 return True
-            elif fuzzy_not((self.args[0] - 1).is_zero):
+            elif fuzzy_not(self._arg_is_1):
                 if self.args[0].is_algebraic:
                     return False
         else:
@@ -724,10 +731,16 @@ def _eval_is_finite(self):
         return arg.is_finite
 
     def _eval_is_positive(self):
-        return (self.args[0] - 1).is_positive
+        from sympy.physics.units import Quantity
+        arg = self.args[0]
+        if isinstance(arg, Quantity):
+            return True
+        if arg.is_Mul and arg.has(Quantity):
+            arg = Mul._from_args([a for a in arg.args if not isinstance(a, Quantity)])
+        return (arg - 1).is_positive
 
     def _eval_is_zero(self):
-        return (self.args[0] - 1).is_zero
+        return self._arg_is_1
 
     def _eval_is_nonnegative(self):
         return (self.args[0] - 1).is_nonnegative
diff --git a/sympy/physics/units/quantities.py b/sympy/physics/units/quantities.py
index 7c6bb7c..eb13a6a 100644
--- a/sympy/physics/units/quantities.py
+++ b/sympy/physics/units/quantities.py
@@ -24,6 +24,7 @@ class Quantity(AtomicExpr):
     is_real = True
     is_number = False
     is_nonzero = True
+    is_finite = True
     _diff_wrt = True
 
     def __new__(cls, name, abbrev=None, dimension=None, scale_factor=None, **assumptions):
```

**Comment by czgdp1807** [comment]
@smichr The method you suggested is quite elegant. However, what I think is that, using statements like, log(mass) isn't conceptually correct, anything passed should be dimensionless or at least it should be processed as a dimensionless quantity. It should be conceptually correct. What's your view on this?
Please review my PR that I have made following this concept and please give your feedback on my PR that whether it was helpful to solve the issue. :-)
Waiting for your feedback and response. :-)

**Comment by smichr** [comment]
> log(mass) isn't conceptually correct, anything passed should be dimensionless or at least it should be processed as a dimensionless quantity

I tried to show  in my examples that there is nothing wrong with taking the log of a number with dimensions: log(2*foot) = log(2) + log(foot). An alternative approach (and perhaps preferred) would be to relax the constraint on when an error is raised: only consider dimensional mismatch of dimensioned numbers, don't consider something like `foot - 1` to be an error (only cases like `foot - quart`. This would allow someone to play with units and figure out what values units would have to have if an expression were to have a certain value. For example, cases where speed of light is 1.

**Comment by czgdp1807** [comment]
I got your point and may I work on the method you suggested for solving this issue, i.e., raising error only when all the addends in the addition operation are physical quantities?

**Comment by asmeurer** [comment]
To me the whole point of keeping track of units is to catch mistakes. So any fix that allows false positives to slip through would not be acceptable. 

Here's the question: should like `log(2*m) + 1` (`log(unit) + unitless`) make sense, or should they give an error? If the latter, then the only solution is to keep `log(unit)` unevaluated, as a different kind of unit which can be added to other log units (but not non-log units). Making `log` unitless forces it to be allowed.

I think it should be possible to keep `log(unit)` unevaluated, and make `log` a special kind of unit that can be added to other logarithmic units (but not to non-logarithmic units; `log(foot) + log(gram)` is fine, but `log(foot) + gram` is not).

Regarding the issue of core code checking `x - 1`, doesn't this issue apply to any unit-ed expression `x`?

**Comment by schymans** [comment]
Just to reinforce the points by @asmeurer:

-  `unit - 1` should in my opinion raise an error, and this is why we added some code with @jirikuncar to do this a while ago. If there are convincing arguments against this, we could re-think. 
- `log(unit)` should not be unit-less, as the value will depend on the units used in the expression, e.g. `log(2*kilogram)` will have a different value than `log(2000*gram)`.
- If we leave `log(unit)` unevaluated, we would allow to resolve meaningless expressions such as `log(foot) + log(gram)` algebraically  later by taking powers etc. For example, `log(velocity) = log(meter) - log(second) = log(meter/second)` and if we take the power to base e, we get  `velocity = meter/second`

**Comment by czgdp1807** [comment]
@schymans I agree partially with you and would like to explain you how my PR, https://github.com/sympy/sympy/pull/14886, accounts for the points you mentioned and solves the issue as 
well:
-`unit - 1` will raise an error since, I haven't made any changes to the mechanism which checks the compatibility of two dimensions being added.
- I don't agree here, since, `log(unit)` is dimensionless so having units is irrelevant here. I have studied in Physics that when you take `log(a*b)`, then Dimension(a) = 1/Dimension(b). Hence, if we take, `log(2*kilogram)`, the 2 should be a physical qauntity with dimensions of mass and units don't matter since we can scale `2 gram` to the appropriate unit system so that it cancels kilogram. Even, quantities like pH are unit less and it doesn't matter what was the unit of the concentration of the solution used to calculate pH. `log(unit)` should be unit less and my PR works on those grounds only.
- `log(unit)` won't be unevaluated, instead, first, a dimensionless copy of `unit` would be created and then it's `log` would be taken, which would be conceptually correct.

I have presented my views. @schymans and @asmeurer please review the PR, https://github.com/sympy/sympy/pull/14886, and present your views so that I can work further to solve this issue. :-).

**Comment by smichr** [comment]
> Here's the question: should expresions like log(2*m) + 1 (log(unit) + unitless) make sense, or should they give an error?

Let's make progress by agreeing on what is wrong and what is not.

1. unit + unitless is wrong
2. unit*unitless is not wrong
3. log(unit) is not wrong 
4. func(unit) + unit is wrong as is func1(unit) + func2(unit)

We already agree on 1 & 2. I hope we can agree on 3 or else the CAS-with-units is going to have troubles. Take the issue of pH. @czgdp1807, only units of molar will give a unitless value that can be called pH when substituted into the equation `-log(conc/molar)`. The log of non-molar concentrations will give a pH that is off by a constant (of conversion) from the true pH. The problem of an equation like `pH = -log(cH)` is that one can do `pH.subs(cH, .1)` and get a result...but then the result is not sanity checked and only the user knows if the units of cH were molar. If the equation was `pH = -log(cH/Q(molar))` (where Q(molar) represents a molar unit/quanity) then the user will only get a dimensionless pH when unit are included...and the unit system will handle any conversions via simplification and the units will cancel out. So `pH.subs(cH, .001 mol/m**3)` will give `-log(.001*mol/m**3/molar)` and log expansion before simplification will give 3 - log(mole) + 3*log(m) + log(molar). It is at this point that we should not be raising an error so we should abide by rule 3 above. After simplification, the correct (unitless) value of pH will be obtained.

Rule 1 is the source of the issue of the OP as I have already pointed out because the assumption system is trying to answer whether `log(foo)` is zero and it does so by seeing if foo is 1 by testing if `foo-1` is zero. It is at this point, if foo has dimensions, that intervention must take place and that is what the diff that I provided does. I prefer it over anything else that I have suggested.

**Comment by asmeurer** [comment]
I would argue that even func(unit1) + func(unit2) is wrong except when func is a logarithm, though I don't know if SymPy needs to check for that. It only works for logarithms because they map multiplication to addition.

**Comment by smichr** [comment]
@czgdp1807, how is `log(2*foot)` made dimensionless?

**Comment by schymans** [comment]
@czgdp1807, thanks for explaining. I actually think here is the right place to have the current discussion, as it is about a more precise definition of the issue, not about how the issue is solved, which will be discussed in the PR. I think the issue is that `log(unit)` is neither (a) false, nor (b) dimensionless, nor (c) a unit by itself. 
Arguments collected from above:
(a) This behaviour should be perfectly valid:
`eq_v = Eq(velocity, meter / second)`

`log(eq_v)`
`Eq(log(velocity), log(meter/second))`

`Eq(log(velocity), log(meter) - log(second)) == Eq(log(velocity), log(meter/second))`
`True`

(b) 

> The log of non-molar concentrations will give a pH that is off by a constant (of conversion) from the true pH

(c) See (a): ` log(meter) - log(second) == log(meter/second)`

How about leaving `func(unit)` unevaluated for all functions? This way, the user will have to either resolve the function or make its arguments non-dimensional to obtain a numerical number. Incidentally, the wikipedia definition of pH refers to activity, which is dimensionless: https://en.wikipedia.org/wiki/PH

**Comment by czgdp1807** [comment]
@asmeurer I agree with you log(meter) + log(second) is completely valid, since both are dimensionless and unit less. Let me keep my point of view with an example. Let us say we want to take the log of 2 seconds or for simplicity I would say, 2s. Now, log(2s) is not valid, since, according to dimensional analysis we can only take log of a dimensionless physical quantity. So, how can we make 2s dimensionless and unitless? The answer is by dividing 2s by 1s. Hence, log(2s/1s) is completely valid. However, the point to be raised is, we could have divided 2s by 1 hour to make it dimensionless.Here, comes in the role of definitions, like that of pH is `pH is defined as the decimal logarithm of the reciprocal of the hydrogen ion activity, aH+, in a solution`. Therefore, we have to work according to the definitions while taking log, sin and cos of various functions.
@smichr `log(2*foot)` is made dimensionless as follows:
1. First 2*foot is checked whether it's dimensionless. Clearly it's not so we will move to step 2.
2. By filtering out the `2` and `foot` from * using a pre-defined method in mul class.
3. Then 2 is checked whether it's dimensionless. Clearly, it's not so it is kept unchanged.
4. `foot` is checked whether it's dimensionless. Since, it is dimensionless, we convert this foot to dimensionless constant that is 1.
5. Then 2 and 1 are multiplied.
6. Finally log(2) is taken. 
I could have replaced foot by 1000 or some other number but choosing 1 assumes that the user wants to take the log(2 foot) that is he expects, log(2). Thus, scale remains unchanged.

**Comment by smichr** [comment]
What should be the result of the following:

```python
>> log(x/foot) -> no error
>> log(x) - log(foot) -> no error
>> log(2/foot) -> error?
>> log(2) - log(foot) -> error?
>> log(2*inch/foot) -> log(1/6)
>> log(2) + log(inch) - log(foot) -> log(2) - log(12)
```

What does this mean:

```
>>> length/foot
Dimension(length, L)
```

**Comment by czgdp1807** [comment]
@smichr  I got your point. I think introducing scale factor should be done. Converting to dimensionless is not right. What about this model:-
1. Convert `inch` to `meter`, `foot` to `meter` which would introduce a scale factor c.
2. Then multiply c with the quantity, like here 2.
`log(2/foot)` shouldn't be an error. May be the user wants 2 foot or 2 meter. Now, sin(5t + 6) is a sine wave and t is time and it is assumed that 5 is 5s^-1 and not unit less constant.

**Comment by czgdp1807** [comment]
I am not unable to understand about `length/foot`. I mean it is relevant to me to divide length by foot, dimension/unit. Can you please explain more on this?

**Comment by czgdp1807** [comment]
@smichr The modified `log` function gives the following results:
`>>> log(x/foot) -> log(x/foot)`
`>>> log(x) - log(foot) -> -log(foot) + log(x)`
`>>> log(2/foot) -> log(2/foot)`
`>>> log(2) - log(foot) -> -log(foot) + log(2)`
`>>> log(2*inch/foot) -> log(2*inch/foot)`
`>>> log(2) + log(inch) - log(foot) -> -log(foot) + log(inch) + log(2)`
@schymans @smichr Should I include a scale factor when the quantity is made dimensionless so that units get accounted and no information regarding units is list while processing the log?
Waiting for your response.

**Comment by schymans** [comment]
@czgdp1807 After looking at the whole discussion, I do not think that we need to make the terms inside a logarithm or any function dimensionless, as `exp(log(meter/second)) == meter/second` should be perfectly valid. We just need to make sure that the dimensions inside the function are consistent, e.g. `log(meter + second)` should raise an error. This is currently the case, I think. What should not happen is that `log(meter) - log(second)` raises an error, as `log(meter/second)` is valid.
Of course, if the terms inside a function are dimensionless, then the numerical value of the function has a meaning. So we can evaluate `log(x)` numerically if `x` is dimensionless, otherwise it does not make much sense. 
In this context, I do not understand why you prevent `log(x ) - log(foot)` to simplify to `log(x/foot)`.
Is there a reason behind it? 
I am thinking more and more that we may have to go away from automatic dimension checking, as this will create quite a big burden for all of sympy. See here: https://github.com/sympy/sympy/pull/14923

**Comment by czgdp1807** [comment]
@schymans Originally `log(x) - log(foot)` also doesn't simplifies to `log(x/foot)`. I am also unaware of the reason. However, I have thought of a model is, 
1. check if arg is an instance of Add class, and if it is, then check for the dimensional compatibility of addition.
2. To avoid `log(meter) - log(second)` we can assign the `log()` a dimension of 1, in this way arg will retain its original addition and is conceptually correct also.

**Comment by smichr** [comment]
> We just need to make sure that the dimensions inside the function are consistent

I'm not even convinced that we need to do this (and it sounds, from your comment in #14923) that you agree. The beauty of a CAS is that it is self-documenting in terms of keeping track of symbols/units. If you simplify an expression and it doesn't give you `x=0` as you might expect, then the expression was wrong. Similarly, if you have something like `foot + liter` as a final expression, it is up to you (the user) to identify where the conceptual mistake was made.

Regarding non-simplification of `log(x) - log(foot)`...that is a separate issue.

**Comment by schymans** [comment]
Wow, hope Issue #14932 will be solved soon. 
+1 for giving more control to the user, but we still need a way to check for dimensional consistency, as terms may be much less obvious than `foot + liter`. So, as long as units from within functions are not dropped and the above example of `eq1 = Eq(log(m3), log(m1 + m2))` does not raise an error as long as `m1` and `m2` have the same dimensions, this issue would be solved, right?

**Comment by schymans** [comment]
Actually, could PR https://github.com/sympy/sympy/pull/14923 be re-opened? I think that one would solve the initial problem here and after solving Issue #14932, we would probably have quite a consistent behaviour.

**Comment by asmeurer** [comment]
That sounds like a much better approach.
