### ISSUE TITLE
evaluate = False does not prevent evaluation

### ISSUE THREAD

**Issue by esandier** [sympy/sympy#14560]
I am using sympy for online math exercises where it is important to access the unevaluated answers.
 
The answers are strings and converted to sympy expressions using sympify, but I noticed that, for instance, 'gcd(12,9)' will always be converted to 3, even if the evaluate=False flag is used.

I just realized this is closely related to "Added evaluate flags in miscellaneous.py #14130"

**Comment by smichr** [comment]
Since you have both the string and the (evaluated) answer you know that the format was ok. What did you want to do with the unevaluated answer that you can't easily do with the string that represents that answer?

**Comment by asmeurer** [comment]
Related to https://github.com/sympy/sympy/issues/13999. The suggested fix there would most likely solve your problem for most situations (assuming said fix actually works).

**Comment by esandier** [comment]
What I want is to write online math exercises. In this example, the question is "what is the gcd of 9 and 12", say, and I want to check if the answer is right by testing equality against the correct answer. But I do not want  "gcd(9,12)" to count as a correct answer.
Of course I could check is the string is "3", but I want this to work for many different exercises involving possibly complicated answers, exercises that other peoplewould write, etc... And having an unevaluated simpy expression would be handy, for the above reason, and also to be able to provide relevant feedback in a number of cases. 
 

    Le lundi 26 mars 2018 à 19:51:27 UTC+2, Christopher Smith <notifications@github.com> a écrit :  
 
 
Since you have both the string and the (evaluated) answer you know that the format was ok. What did you want to do with the unevaluated answer that you can't easily do with the string that represents that answer?

**Comment by asmeurer** [comment]
I agree that for a grading system you want SymPy on the one hand, to automatically check if an answer is correct, but you want answers to be unevaluated so that students can't just let SymPy do the work for them. For your case, you could just whitelist the available functions to that `gcd` isn't parsed as `sympy.gcd`, but in general, it isn't that easy (say for instance, you want to differentiate `4/12` from `1/3`, or `(x + 1)/(x + 1)` from `1`).  So you want to 1. get the answer expression, as close to how the student entered it as possible, 2. evaluate it to see if it is mathematically the right answer, and 3. don't evaluate it "too much" so that the student isn't just letting SymPy do the work for them. I can't suggest too much for 3, especially in the realm of things that SymPy does automatically (like automatic term cancellation). I think what we need is an AST (effectively) that represents the expression (this is equivalent to the string input, minus whitespace), that can easily be evaluated to a full SymPy expression. A very simple method is to just do `ast.parse`, and build something on top of that, then eval it to get the results. This also makes it easier to filter bad stuff, which SymPy currently [does not do](https://github.com/sympy/sympy/pull/12524). 

What #13999 wants to do is to get what is effectively an AST, but with SymPy classes. Basically, you build up the classes but completely skip all the class constructors, so that no automatic evaluation or simplification happens. #13999 would make it convenient by putting it in the parser, so it can be done with string inputs. 

What is missing from that is a way to later evaluate the expression. You would need to rebuild the expression from scratch, to make sure every class constructor gets run. Probably `sympy.unify.rebuild` would be sufficient. 

The real danger here is that these "unevaluated" expressions look just like regular expressions (they use the same classes), but they could fail in unexpected ways, because the invariants upheld by the class constructors might not hold. So some code might assume that, for instance, the only argument of a Mul that is an integer is the first argument, but `Mul(2, 3, evaluate=False)` breaks this. It could lead to wrong results. We see this all the time in the printers, but I suspect it goes much deeper. It's not even possible to tell if an expression was created with `evaluate=False` (the flag isn't stored on the object), other than rebuilding it and seeing if it comes out the same.

The only thing to do that I know of, in this model, is to never actually "use" these unevaluated expressions, except in building larger unevaluated expressions (printing should be made to work too, but for functions that manipulate or solve expressions, it's all garbage in-garbage out). 

An alternate model would be to wrap the ast with some other classes, so that they don't look like real expressions. That means that nothing will actually work with them, unless explicitly designed to. This means that many things that might work anyway are prevented from working, until the expression is "reified" into a real, non-unevaluated expression. This is the idea behind the `UnevaluatedExpr` class. But very little work has been done with that idea so far, so I can't say very well what the tradeoffs would be.

**Comment by esandier** [comment]
I'm not sure I understand all the details (i'm a mathematician, not a computer scientist), in particular I don't know what an AST is. If I understand well, though,  from the string  input for instance (x+1)/(x+1), you could  get  the tree node 'Division" with two subnodes "Add" each with two leaves 'x' and '1', even though the simpy object is not constructed?

That would be perfect, even if the thing is not allowed be evaluated, you can always evaluate the string with 'sympify'

A less ambitious alternative would be to be able to test a string for common things like: is it a number, is it a fraction, is it a polynomial?

**Comment by asmeurer** [comment]
What I wrote above was more of a brain dump on doing unevaluated expressions in general. It may not all apply to your specific problem.

AST stands for abstract syntax tree. It's basically like you described it: a tree where the nodes are operations and the children are the operands, and the leaves are variables or numeric literals. `ast` specifically is the [Python module](https://docs.python.org/3/library/ast.html) for getting an AST from any Python source. 

> A less ambitious alternative would be to be able to test a string for common things like: is it a number, is it a fraction, is it a polynomial?

Those are relatively simple, but it starts being a slippery slope where you go from very simple computations on an AST to reinventing a CAS. So as soon as you want to start doing mathematical computations, I recommend just using SymPy, if possible. I still think the suggested fix from #13999 is the best fit for your problem.

**Comment by esandier** [comment]
Thanks.
