### ISSUE TITLE
Incorrect limit simplification  

### ISSUE THREAD

**Issue by VahanArsenyan** [sympy/sympy#14693]
`x = Symbol("x")
y = Symbol("y")
expression = limit(1/x, x, y)`

Gives me `1/y`(\frac{1}{y}) and when I evaluate it with `y = 0` I get division by Zero exception.
It is incorrect because for `limit(1/x, x, 0)` answer is infinity.

**Comment by jksuom** [comment]
`1/0` does raise a ZeroDivisionError in Python, but that is not the case with SymPy:
```
>>> from sympy.abc import y
>>> (1/y).subs(y, 0)
zoo
```

**Comment by asmeurer** [comment]
I don't think there's an issue here. `limit(f(x), x, y)` where `y` is a symbol will just replace `x` with `y`. If you then want to evaluate `y` at a more specific point *as a limit*, you have to use `limit` again, not `subs` or direct replacement. In general, SymPy only evaluates expressions at limit points correctly if you explicitly use the `limit` function. Sometimes you will get the right limiting answer just by using `subs` but in general you won't. 

Also note that limits are approached from the right by default, which is why `limit(1/x, x, 0)` is positive infinity (use `limit(1/x, x, 0, '+-')` to get the two-sided limit).
