### ISSUE TITLE
Derived unit 'volt' has scale factor of 1000 instead of 1 (because kg=1000)

### ISSUE THREAD

**Issue by tamuri** [sympy/sympy#14734]
I believe the fundamental unit for mass is the kilogram with scale factor of 1. Sympy defines it with scale factor of 1000? This has knock-on effects:

```python
# Python 3.6.5 |Anaconda, Inc.| (default, Apr 26 2018, 08:42:37)
>>> import sympy
>>> sympy.__version__
'1.1.1'
>>> import sympy.physics.units as u
>>> u.volt.args
(volt, Dimension(voltage, U), 1000, V)
>>> # derived unit scale factor of volt should be 1; volt = joule/coulomb
>>> u.joule.args
(joule, Dimension(energy, E), 1000, J)
>>> u.coulomb.args
(coulomb, Dimension(charge, Q), 1, C)
>>> # joule = newton * meter
>>> u.newton.args
(newton, Dimension(force, F), 1000, N)
>>> # newton = kg*m/second**2
>>> u.kilogram.args
(kilogram, Dimension(mass, M), 1000, g)
>>> # ???
```

**Comment by asmeurer** [comment]
Is it simply using g instead of kg for the fundamental unit? Does this produce any wrong results or is it just different from what is expected? 

I think we should use kg as the fundamental unit as that is the standard. Hopefully that wouldn't cause a backwards compatibility break to change, though.

**Comment by tamuri** [comment]
> Is it simply using g instead of kg for the fundamental unit? 

Yes, that seems to be the case. 

> Does this produce any wrong results or is it just different from what is expected?

The volt example above is one such example of an error. I guess anything using kilogram and expecting '1' rather than '1000' will be affected. Newton is another example: (1 N = 1 kg . 1 m/s^2). However, due to kg=1000 in Sympy, we have:

```
In [20]: newton.args
Out[20]: (newton, Dimension(force, F), 1000, N)
```

> I think we should use kg as the fundamental unit as that is the standard. 

Agreed.

**Comment by asmeurer** [comment]
Yes, but everything is self consistent with the fundamental unit being grams, no? Nothing is mathematically wrong, just using the wrong base definitions.

**Comment by asmeurer** [comment]
I think there is more at play than just that line. If I change `kilo` to `One`, I get some test failures that are definitely wrong results. For instance, `convert_to(joule, [centimeter, gram, second])` gives `10000*centimeter**2*gram/second**2` instead of the correct `10000000*centimeter**2*gram/second**2`. I also get some other failures. 

I can also change the scale factor of gram from `One` to `milli*kilogram`. This fixes the above test, but the other failures remain.

Isn't the point of the unit systems framework to be able to use whatever base units you want? I'm sorry I'm not highly familiar with the units module. Maybe @Upabjojr can enlighten us.

**Comment by Upabjojr** [comment]
We are not using SI as default system. Ideally the units module should support any unit system. The scale factor is (temporarily) an arbitrary value.

**Comment by Upabjojr** [comment]
Probably the error in units was not to hide `scale_factor` to end-users.

By the way, `gram` and `kilogram` are separately defined. So no surprise you get that error if you change the definition of `kilogram`.

**Comment by tamuri** [comment]
This test demonstrates a consequence of gram being the unit of mass.

https://github.com/sympy/sympy/blob/125e8863c84473636ddc94500abbd667c291961a/sympy/physics/units/tests/test_unitsystem.py#L46-L59

joule-second (Js) is a measure of action = momentum . length = (kg . m / s) . m = kg . m^2 / s

So unit joule-second is kg . m^2 / s

But in the test it's necessary to divide through by 1000 due to scale factor on kg.
