### ISSUE TITLE
Integrate should return whether the integration was successful or not.

### ISSUE THREAD

**Issue by randolf-scholz** [sympy/sympy#14755]
A bit of a hacky way is described in [this post](https://stackoverflow.com/questions/45155289/how-to-check-if-sympy-expression-contains-instance-of-integral-or-nonelementaryi)

However, this is sub-optimal since it would also trigger when the integrand contains other integrals that are treated as scalars. For example one might have

    integrate(x*Integral(y),(x,0,1))

Also, some time limit / max iteration constraint would be a good optional parameter for the method

**Comment by oscarbenjamin** [comment]
For the precise example show you can use `doit` to force evaluation of integrals (if that's what you want):
```julia
In [3]: integrate(x*Integral(y),(x,0,1))                                                                                          
Out[3]: 
⌠     
⎮ y dy
⌡     
──────
  2   

In [4]: _.doit()                                                                                                                  
Out[4]: 
 2
y 
──
4 
```

As the answer to the linked SO question says if you just want to detect whether there is an integral somewhere in an expression then `has` will do the job:
```julia
In [5]: integrate(x*Integral(y),(x,0,1))                                                                                          
Out[5]: 
⌠     
⎮ y dy
⌡     
──────
  2   

In [6]: _.has(Integral)                                                                                                           
Out[6]: True
```

You say that's suboptimal because you just want to know whether the call to integrate evaluated properly in which case I think maybe `isinstance(Integral)` does what you want:
```julia
In [21]: integrate(exp(sin(x)),(x,0,1))                                                                                           
Out[21]: 
1           
⌠           
⎮  sin(x)   
⎮ ℯ       dx
⌡           
0           

In [22]: isinstance(_, Integral)                                                                                                  
Out[22]: True

In [23]: integrate(x*Integral(y),(x,0,1))                                                                                         
Out[23]: 
⌠     
⎮ y dy
⌡     
──────
  2   

In [24]: isinstance(_, Integral)                                                                                                  
Out[24]: False
```

For your other suggestion about time limit / max iteration - that would be very difficult to implement. It's impossible for the code in the integration routines to predict how much time will be taken by any of the other routines that are called. Checking for the time limit within the integration code would also complicate things a lot. Maybe the cleanest thing would be to run the integration routine in a different process. I'm not sure that's something SymPy should directly support though.
