### ISSUE TITLE
xreplace does not replace all instances of the symbol

### ISSUE THREAD

**Issue by cristian-frincu** [sympy/sympy#14813]
I am trying to replace a function, with a matrix form, symbolically. I was getting an error when using .subs(), so I ended up using .xreplace(). The function works, but it does not make the replacements for all the instances of the variable I am trying to replace.
Does anybody have any idea why it might not work? There are no errors when the function is run.

I am not sure what portion of the code is relevant, here is a notebook with the problem:
[Link](https://drive.google.com/file/d/1PADgCk7_w1KHlWxZizsr77LJmMCHXDE4/view?usp=sharing)

I am trying to substitute all \mu and \sigma, derivatives as well, with their matrix equivalent.
sub6  should not have any \mu or \sigma in it

**Comment by asmeurer** [comment]
Your link is not publicly accessible. Can you post the code here on the issue, or on a gist if it's too large?

**Comment by asmeurer** [comment]
I think this is fixed in master. I get `(-(3/2)*(-K_*.T*K*K_* + K_**)**(-4)*(-K`_*.T*(K + K.T)*K`_* + K`_**)**2)*(y - K_*.T*K*Y)**2 + ((1/2)*(-K_*.T*K*K_* + K_**)**(-3)*(-K``_*.T*(K + K.T)*K``_* + K``_**))*(y - K_*.T*K*Y)**2 + ((1/2)*(-K_*.T*K*K_* + K_**)**(-2)*K``_*.T*K.T*Y)*(y - K_*.T*K*Y) + (-2*(-K_*.T*K*K_* + K_**)**(-3)*(-K`_*.T*(K + K.T)*K`_* + K`_**)*K`_*.T*K.T*Y)*(y - K_*.T*K*Y) + (-K_*.T*K*K_* + K_**)**(-2)*(-K`_*.T*(K + K.T)*K`_* + K`_**)**2 - (-K_*.T*K*K_* + K_**)**(-1)*(-K``_*.T*(K + K.T)*K``_* + K``_**) - (1/2)*(-K_*.T*K*K_* + K_**)**(-2)*(K`_*.T*K.T*Y)**2`

**Comment by cristian-frincu** [comment]
You are correct, I was using version 1.1.1, which is the current on pip. 
It is fixed in the 1.1.2-dev which requires install from source.
