### ISSUE TITLE
Docs tell me to see something but they don't tell me how to see it

### ISSUE THREAD

**Issue by JohnStone2017** [sympy/sympy#14924]
`help(sympy.fps)` tells me:

```
See Also
========
sympy.series.formal.compute_fps
```

but

```
help(sympy.series.formal.compute_fps)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-40-d915bd8fac6b> in <module>()
----> 1 help(sympy.series.formal.compute_fps)

AttributeError: 'function' object has no attribute 'formal'
```

Hyperlinks were invented how many decades ago, but Sympy gives no hyperlink while telling me to see something. I'm just typing my ass off trying to get Sympy to show me the docs it wants me to see, and I don't want to go back to Sympy Live, because it wasted my time last time. Losing my vision by the day, in severe pain, and Sympy makes me type so much trying to get it to show me the docs.

Sympy is not version 1.2 it is alpha. The Python language seems to inspire people to release bad software.

You should have seen it in the 80's; computers worked better, now it's 99% trying to find workarounds for bad things people have programmed. I don't do math or development anymore I'm full-time working around people's bugs and shit documentation.

Now that I'm done translating my Mathematica notebooks into Python and finding that Python has no competitive CAS, it's time to translate all my notebooks to Axiom. Or Maxima because its manual was written by someone with a brain not by a Python function telling me to see some shit I can't see.

**Comment by asmeurer** [comment]
@JohnStone2017 if you want to contribute to improve to SymPy, I suggest reading https://github.com/sympy/sympy/wiki/Introduction-to-contributing. We'd be happy to help you. 

You should also take a read of https://github.com/sympy/sympy/blob/master/CODE_OF_CONDUCT.md, and please be aware that it is not optional. Certain aspects of your report do not follow this (I think you know which ones). 

Regarding the issue at question, this is an unfortunate side effect of the way Python names work. `sympy.series` is both a module and a function, and the function here take precedence because it is imported later. Directly importing this as `from sympy.series.formal import compute_fps` does work.  Unfortunately, there's not much we can do here. The "see also" is designed to work with [Sphinx](http://docs.sympy.org/latest/modules/series/formal.html#sympy.series.formal.fps), so we do not have other options on how it is formatted. SymPy is fundamentally a Python library and there are certain aspects of the Python programming language that users need to be familiar with when using the library.

**Comment by certik** [comment]
@JohnStone2017, welcome to the SymPy community. SymPy is not perfect, but we are trying our best. Thanks for your reports.

As @asmeurer said, when you report what you think is a bug, please keep it civil in the issues, don't use swear words and please try to be constructive. Please read our Code of Conduct, and try to follow it.

**Comment by skirpichev** [comment]
@JohnStone2017, you can take look on the [diofant](https://github.com/diofant/diofant/).  I believe, it doesn't have this issue: broken hyperlinks should emit warnings while building of the sphinx docs and such warnings will break travis-ci build for the diofant. (You can see: there are no broken links in our public docs https://diofant.readthedocs.io/.)

I see no problem to fix same issue in the sympy in same way as I did it for the diofant long time ago.  But I doubt that someone in the sympy community will do this tedious task for you...

> The "see also" is designed to work with Sphinx, so we do not have other options on how it is formatted.

Oh.  You _can_ detect broken links with sphinx.  No reasons to not do it...  Of course, I agree that in the current case fixing broken link is not so trivial.  But that is a second issue and you totally miss the first one: your sphinx docs has broken links.

> Now that I'm done translating my Mathematica notebooks into Python and finding that Python has no competitive CAS

Diofant is a sympy fork (it was started from ~ 0.7.6 codebase), you could test it too.  It much more rely on automated testing and it has more strict policy on the code quality.

Oh, and it doesn't have "Code of Conduct" to ban you from any critique - feel free to say anything you do think about the diofant project.

**Comment by skirpichev** [comment]
Wow, closed.  @certik, do you also think that there is no issue at all?

**Comment by certik** [comment]
Hi @skirpichev thanks for the comment. I created a new issue for the broken links at #14925. I think that's definitely a problem. I didn't know that Sphinx can detect it. If you are interested in fixing it, please go ahead.
