### ISSUE TITLE
linear_eq_to_matrix proceeds without exception even if equations are nonlinear

### ISSUE THREAD

**Issue by jeremyherbert** [sympy/sympy#14987]
Hi,

I would expect the following code to throw an exception (or give me a warning telling me I'm silly), but it does not. `x**2=0` is not a linear equation.

```
from sympy import symbols, linear_eq_to_matrix, linsolve
x = symbols("x")
linear_eq_to_matrix([x**2], [x])
```

**Comment by cbm755** [comment]
Sure, anyone can work on any issue.

Some thoughts:

1.  Technically, there is no bug here because the docs say:
> Here `equations` must be a linear system of equations in `symbols`.

2.  But IMHO its still important to have sanity checks in place.  IIRC, there used to be bugs in ODE solvers because of this for example.

3.  It may be important (for other solvers) to have this code as fast as possible.  That might mean no calculating derivatives, for example.

4.  Worst case (if it can be done in a fast way), we can have kwarg `checklinearity=True`, and performance-critical library code could set that to False.

**Comment by czgdp1807** [comment]
I was working on this issue form the past few hours. I have made [PR](https://github.com/sympy/sympy/pull/15000). Please review and kindly give suggestions on improving it further. :-)

**Comment by cbm755** [comment]
> Please review and kindly give suggestions

Well I started too but then you closed it, see my comments in https://github.com/sympy/sympy/pull/14997

**Comment by czgdp1807** [comment]
@cbm755 I apologize for random actions of mine while making a pull request for solving this issue. Actually, I was unaware of the release notes procedure. Hence, I got confused by the sympy bot. 
I have reopened the [PR](https://github.com/sympy/sympy/pull/14999) which solves the issue to the best of my knowledge. 
I will add the changes you suggested in this PR only. 
Really sorry for the troubles. :-(

**Comment by czgdp1807** [comment]
@cbm755 
I have implemented your last suggestion, that is, `check_linearity = False`. This way the standard tests could be passed and if someone wants to confirm the linearity of equation that he or she is passing to the method can do so by setting, `check_linearity = True`.
If it passes all the tests, then I will make appropriate changes in the documentation of the method as well as add appropriate tests.
