### ISSUE TITLE
empty Piecewise fails to pretty print

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#15005]
Consider:
```
>>> f = Piecewise()
>>> print(f)
Piecewise()
```
Ok, but:
```
>>> pprint(f)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-5-dd6b50590f87> in <module>()
----> 1 pprint(f)

/home/cbm/src/sympy.git/sympy/printing/pretty/pretty.pyc in pretty_print(expr, wrap_line, num_columns, use_unicode, full_prec, order, use_unicode_sqrt_char)
   2379     print(pretty(expr, wrap_line=wrap_line, num_columns=num_columns,
   2380                  use_unicode=use_unicode, full_prec=full_prec, order=order,
-> 2381                  use_unicode_sqrt_char=use_unicode_sqrt_char))
   2382 
   2383 pprint = pretty_print

/home/cbm/src/sympy.git/sympy/printing/pretty/pretty.pyc in pretty(expr, **settings)
   2339 
   2340     try:
-> 2341         return pp.doprint(expr)
   2342     finally:
   2343         pretty_use_unicode(uflag)

/home/cbm/src/sympy.git/sympy/printing/pretty/pretty.pyc in doprint(self, expr)
     60 
     61     def doprint(self, expr):
---> 62         return self._print(expr).render(**self._settings)
     63 
     64     # empty op so _print(stringPict) returns the same

/home/cbm/src/sympy.git/sympy/printing/printer.pyc in _print(self, expr, **kwargs)
    285                 printmethod = '_print_' + cls.__name__
    286                 if hasattr(self, printmethod):
--> 287                     return getattr(self, printmethod)(expr, **kwargs)
    288             # Unknown object, fall back to the emptyPrinter.
    289             return self.emptyPrinter(expr)

/home/cbm/src/sympy.git/sympy/printing/pretty/pretty.pyc in _print_Piecewise(self, pexpr)
   1038         # max widths
   1039         maxw = [max([P[i, j].width() for i in range(len_args)])
-> 1040                 for j in range(2)]
   1041 
   1042         # FIXME: Refactor this code and matrix into some tabular environment.

ValueError: max() arg is an empty sequence

>>> latex(f)

<similar error>
```

Now maybe you think no one should make empty Piecewise but they can occur naturally:
```
>>> f = Piecewise((42, x > 0)))
>>> pprint(f)
{42  for x > 0
```
`f` is undefined for non-positive numbers:
```
>>> n = Symbol('n', negative=True)
>>> print(f.subs(z, n))
Piecewise()
>>> print(f.subs(z, n))

<error as above>
```

(Another possible resolution is that empty Piecewise raise an exception.)

More background, just FYI: `octave_code(Piecewise())` and the other code generators deal with this in a graceful way by raising exception for all Piecewise that do not have a default block.

**Comment by asmeurer** [comment]
What is an empty Piecewise? What does it mean mathematically? The best I can think of is that it's just `nan`, which is the default "otherwise". If it's not used by anything I think we should remove it.

**Comment by jksuom** [comment]
I would like to think that an empty Piecewise is a function with empty domain of definition. It has obviously no practical use, and I agree that it should be removed.

**Comment by cbm755** [comment]
Both your comments make sense.  But what does "remove" mean?  The creation of such throws an error?  Also throw when it is created, as in my example, from subs into a valid Piecewise?

> `nan`, which is the default "otherwise".

Is it though?  If that were the case, my subs example could reduce to `nan`.  and codegen would not have to ensure there is ` (..., True)` subfcn.

Or are you *proposing* that every Piecewise has an implicit `(nan, True)` subfcn?

**Comment by cbm755** [comment]
In the past, I maybe recall there was some resistance to using a `nan` as a sort of stand-in for "undefined".

`nan` does tend to result in code that needs special cases:
```
>>> f = Piecewise((42, x>7), (nan, True))
>>> f
⎧42   for x > 7
⎨              
⎩nan  otherwise
>>> octave_code(f)
'((x > 7).*(42) + (~(x > 7)).*(NaN))'
```
But this is wrong for say `x = 6` because `nan*0` is `nan`.  Maybe that's more of an `octave_code` bug but still its indicative of gotchas around using `nan`.

**Comment by jksuom** [comment]
> The creation of such throws an error? Also throw when it is created, as in my example, from subs into a valid Piecewise?

I would go for this. I think that users (also library code) should be prepared to catch exceptions instead of just letting expressions with `nan` cumulate.

**Comment by asmeurer** [comment]
I was pretty sure at some point that Piecewise always defaulted to nan. It definitely does this for the NumPy printers. But I guess I remembered incorrectly because it seems it gives an empty Piecewise, and has for some time. 

I think it should default to `nan`. The NumPy printers already have done this for some time. Possibly some other code generators as well. By "remove it" I mean `Piecewise()` with no arguments should raise `TypeError("At least one (expr, cond) pair expected.")`.

**Comment by smichr** [comment]
BTW, I think I anticipated this in some way by defining `NAN` as `Piecewise()` in the integration work that I did. If a default of NaN is added then I think that constant will be `NAN = S.NaN`.

**Comment by asmeurer** [comment]
I found de24a5102c756b326b848b5872c3c11d63912b6c which lead me to https://github.com/sympy/sympy/issues/5666

**Comment by asmeurer** [comment]
It seems the NumPy behavior was added later https://github.com/sympy/sympy/pull/9657

So it looks like:

- Piecewise with no conditions matching has given empty Piecewise for a long time. Probably since the beginning
- The printing has been broken for `Piecewise()` for a long time
- The code printers have just been using `nan` for this for a long time, since empty constructs like `Piecewise()` don't make sense in a codegen setting.
- There's been an issue at least by me to make it return nan for a long time (I don't know how many other people agreed with me, at least the people writing the codegen code did)

So I (still) think `Piecewise` when evaluated (subs) on a term that doesn't have a matching condition should return nan. And I think `Piecewise()` constructed manually with no args should give a `TypeError` (though `nan` would also be fine, but `TypeError` seems cleaner to me).

**Comment by asmeurer** [comment]
Piecewise in its current form was introduced in 4abd9df150f183cb52c6608ffead13b4496d2f4c (it also existed a little before that with a different syntax). I confirmed that in that commit `Piecewise((x, x> 1)).subs(x, 0)` gives an empty `Piecewise()`. So it has been this way for a long time. But I still think we can change it. The fact that the pretty printing has also been broken for a long time (at least since 2013) suggests to me that not many things use it.

**Comment by ramvenkat98** [comment]
@asmeurer @cbm755 

I've made relevant changes to the pull request based on the reviews. Could I get an update on how to proceed further?

Thanks
