### ISSUE TITLE
derivative of function wrt function is 0

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#15048]
The current behavior of derivatives wrt functions does not match what is given [here](https://math.stackexchange.com/questions/954073/derivative-of-a-function-with-respect-to-another-function):

```python
>>> (2*f(x) + x + log(f(x))).diff(f(x))
2 + 1/f(x)  # should be 2 + 1/f(x) + 1/Derivative(f(x), x) according to link
```

**Comment by asmeurer** [comment]
To clarify, the issue is with `x.diff(f(x))` giving `0`, instead of `1/diff(f(x), x)`. 

It's explained in the docstring of Derivative. We treat `expr.diff(f(x))` as functionally equivalent to `expr.subs(f(x), y).diff(y).subs(y, f(x))`, which is the notation used by Euler-Lagrange.

**Comment by asmeurer** [comment]
In that case your original expression would still give the same result. I think this is actually very similar to `y.diff(x)` giving 0. We treat `y` as an independent variable from `x`, rather than as something that could be `x`. Similarly, `f(x)` is an arbitrary function distinct from any explicit function like `x` or `g(x)` or `cos(x)`. (I still think `expr.diff(cos(x))` should be a ValueError by the way https://github.com/sympy/sympy/issues/7027).

**Comment by jksuom** [comment]
It might be helpful to point out that although `f(x)` looks like a function it should actually be considered as an (infinite) indexed family of variables in `expr.diff(f(x))` (a generalization of the more familiar notation `x_i`). It means that the derivative is 0 unless `f(x)`, with exactly the same index `x`, explicitly appears in `expr`. The variables `f(x)` for different values of `x` should be considered independent of each other.

**Comment by smichr** [comment]
OK, so the current behavior is documented so this looks like a non-issue for SymPy. Thanks for the feedback.
