### ISSUE TITLE
dsolve: `get_numbered_constants` should consider Functions

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#15056]
Consider:
```py
from sympy.solves.ode import get_numbered_constants
get_numbered_constants(Symbol('C1')*Function('C2')(t))
```
This should probably give `Symbol('C3')`.  Instead if gives `Symbol('C2')` which is technically ok but could lead to confusion (see `test_C1_function_9239`).

`test_C1_function_9239` in `test_ode.py` should be updated.  Also, a new test added, something like:

```py
t = Symbol('t')
C1 = Function('C1')(t)
C2 = Symbol('C2')
dsolve(Eq(C1.diff(t), C2*C1))
sol = C3*exp(C2*t)
```

Easy to fix: you need some background in ODEs, know the difference between `Symbol` and `Function`, and have attention to detail.

**Comment by asmeurer** [comment]
This also makes sense because dsolve should at some point get the ability to return constants as functions instead of symbols. For instance some PDEs can be solved by treating them as an ODE in one variable, but in that case the arbitrary constants need to be arbitrary functions in the remaining variables.

**Comment by avishrivastava11** [comment]
@cbm755 @asmeurer  I've made a correction now. Please take a look.
