### ISSUE TITLE
Wrong result when calculate  the shortest distance between a line segment and a point

### ISSUE THREAD

**Issue by zenolin** [sympy/sympy#15106]
I used sympy's geometry package, I wanna get the distance between a line segment and a point. But wherever the point, I got the distance between a line (not line segment) and a point. 

```
p1_sym = sympy.geometry.point.Point(1, 0)
p2_sym = sympy.geometry.point.Point(0, 1)
p4_sym = sympy.geometry.point.Point(10, 0)
s1_sym = sympy.geometry.line.Line(p1_sym, p2_sym)
print(s1_sym.distance(p4_sym))
```
The result was 9*sqrt(2)/2. Obviously wrong!

I debugged, found the reason was **Multiple Inheritance** ：
```
# This calss in sympy -> geometry -> line.py
class Segment2D(LinearEntity2D, Segment)
```
I changed the Inheritance order as follows. It was OK.
```
class Segment2D (Segment, LinearEntity2D,)
```
I thought it was a bug. May be someone can repair it.

I use python3.6.

**Comment by jimmygraviton** [comment]
i think answer is correct it should be 9*sqrt(2)/2=9/sqrt(2)
equation of lline is x+y-10 and Point is (10,0)

**Comment by sylee957** [comment]
https://github.com/sympy/sympy/blob/4a0f7981ddd6a611e48779bb212c151c23cd9b54/sympy/geometry/line.py#L1844

https://github.com/sympy/sympy/blob/4a0f7981ddd6a611e48779bb212c151c23cd9b54/sympy/geometry/line.py#L2372

https://github.com/sympy/sympy/blob/4a0f7981ddd6a611e48779bb212c151c23cd9b54/sympy/geometry/line.py#L2641

https://github.com/sympy/sympy/blob/4a0f7981ddd6a611e48779bb212c151c23cd9b54/sympy/geometry/line.py#L2225

If any changes are made, you would also have to make changes to the following classes because they all follow the same inheritance order.
However, I do not know about the consequences about the change, and if those classes have problems fundamentally.

**Comment by zenolin** [comment]
@sylee957  Thanks. My fault. I should use `Segment` class, not` Line `class.

But for python3, according to its the inheritance feature,  will `class Segment2D (Segment, LinearEntity2D)` is better? Using properties and methods of ` Segment` first?

**Comment by sylee957** [comment]
@zenolin

Yes. python supports multiple inheritance with orders.
But you should be sure to convince others that it is safe, and necessary to do such flips.

You can propose a pull request, so that you can hear some opinions from the people who have better knowledge of those classes, than me.

**Comment by zenolin** [comment]
OK. Thanks a million. 

I‘ll do more test to make sure whether it's necessary to do these.

**Comment by oscarbenjamin** [comment]
Closing as the result is correct. The docstring for `Line` says
```
 |  An infinite line in space.
```
so the line does not have end points and the results are correct as @normalhuman says.
