### ISSUE TITLE
Abs(sin(u))**2 + Abs(cos(u))**2 can not be simplified to 1

### ISSUE THREAD

**Issue by retsyo** [sympy/sympy#15123]
latest cloned sympy on python 3
```python
from sympy.abc import u
import sympy
from sympy import Matrix, sin, cos

print(sympy.__version__)
print(Matrix([sin(u), cos(u)]))
print(Matrix([sin(u), cos(u)]).norm())
print(Matrix([sin(u), cos(u)]).norm().simplify())

print(sin(u)*sin(u) + cos(u)*cos(u))
print((sin(u)*sin(u) + cos(u)*cos(u)).simplify())
```
outputs
```
1.2.1.dev
Matrix([[sin(u)], [cos(u)]])
sqrt(Abs(sin(u))**2 + Abs(cos(u))**2)
sqrt(Abs(sin(u))**2 + Abs(cos(u))**2)
sin(u)**2 + cos(u)**2
1
```

the underline is 
```python
print((abs(u)**2))
print((abs(u)**2).simplify())
```
prints
```
Abs(u)**2
Abs(u)**2
```

**Comment by cbm755** [comment]
Thanks for your careful report.  However, I think these results are correct because `u` could be a complex number.  Try it with `u = Symbol('u', real=True)` and it should do what you expect.

(Consider the vector `w = Matrix([I, 1])`.  The 2-norm should be `sqrt(2)`.  It is certainly not `sqrt(I^2 + 1^2) = sqrt(-1 + 1) = 0`.)

I think it could also have given you the following, if that helps explain what is going on here:
```
     _______________________________
    ╱           ⎛_⎞             ⎛_⎞ 
  ╲╱  sin(v)⋅sin⎝v⎠ + cos(v)⋅cos⎝v⎠ 

```

**Comment by retsyo** [comment]
thank you for pointing out the possible complex argument
