### ISSUE TITLE
Provide guidance to 3rd part library devs on SymPyDeprecationWarning

### ISSUE THREAD

**Issue by bjodah** [sympy/sympy#15130]
We should try to find (and document) an easy way for 3rd parties to **selectively** turn `SymPyDeprecationWarning`s into errors. This will be helpful for people trying to hunt down where in a large codebase they are using deprecated sympy features.

Python 3.7 should offer [quite fine granularity](https://docs.python.org/3.7/library/warnings.html#describing-warning-filters) in `PYTHONWARNINGS` (or the `-W` flag).

Here is an example (test.py):
```python
import imp  # we don't want to turn this import into an error
from sympy import Matrix
Matrix([[1, 0], [0, 1]]).dot([2, 3])
```
running the above file using python3.7 gives the following output:
```
test.py:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/home/bjorn/vc/sympy/sympy/matrices/matrices.py:2494: SymPyDeprecationWarning: 

Dot product of non row/column vectors has been deprecated since SymPy
1.2. Use * to take matrix products instead. See
https://github.com/sympy/sympy/issues/13815 for more info.

  useinstead="* to take matrix products").warn()
```
if we use:
```bash
$ PYTHONWARNINGS='error::DeprecationWarning' python3.7 test.py
```
we get
```
Traceback (most recent call last):
...
DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
```
which is not helpful.

Here are a few things I've tried (none of which have been successful)

- `PYTHONWARNINGS='error:::sympy[.*]' python3.7 test.py`
- `python3.7 -W"error::sympy.utilities.exceptions.SymPyDeprecationWarning" test.py`

**Comment by asmeurer** [comment]
A good blog post about this from @nedbat. https://nedbatchelder.com/blog/201810/why_warnings_is_mysterious.html. 

It looks like

- The module isn't actually a regular expression
- You can't actually use third-party warnings. 

However, if you use pytest there is a way directly in pytest to configure the warnings which apparently works.

**Comment by bjodah** [comment]
Thanks, coincidentally I have just started using pytest's warning-filtering-feature in another project.
We should probably make this pass:
```
python3 -c "from sympy import SymPyDeprecationWarning"
```
so that people can run:
```
pytest -W error::sympy.SymPyDeprecationWarning
```
with their codes.

By the way, using upstream pytest is mostly working with sympy, last time I tried there were still problems with some tests expecting exceptions to be raised. I would like to see `sympy` working with `pytest` as a supported alternative to our `bin/test`...

**Comment by asmeurer** [comment]
I agree we should add `SymPyDeprecationWarning` to `__init__.py`, but would that make it work? Ned's post seems to imply that any third-party module can't be used because it is run before sys.path is properly built.

**Comment by asmeurer** [comment]
I played with this a bit and I don't think it's actually possible to use PYTHONWARNINGS or -W to filter SymPy deprecation warnings. The filters do not allow importing external modules to get the warning class as Ned's post outlines. The message doesn't accept regular expressions, unlike with `warnings.filterwarnings`, so there's no way to use that. Even if you did want to copy the entire multiline warning message into there, it wouldn't work because the URL in the message has colons, which it thinks are separators. I wasn't even able to get the module bit to work. 

One thing I noticed is that we insert a warnings filter to always enable the SymPyDeprecationWarning into the front of the warnings filter list: https://github.com/sympy/sympy/blob/c4e836cdf73fc6aa7bab6a86719a0f08861ffb1d/sympy/utilities/exceptions.py#L186

This means that if you use something like `python -We -c 'import sympy'` the error filter from `-We` won't apply to SymPy deprecation warnings, because the filter from SymPy will be added in front of the one from the `-We`. We could work around this by injecting the SymPyDeprecationWarning filter just in front of the DeprecationWarning filter it is trying to override, like

```diff
diff --git a/sympy/utilities/exceptions.py b/sympy/utilities/exceptions.py
index c36c8a00c8..d88f1c0c45 100644
--- a/sympy/utilities/exceptions.py
+++ b/sympy/utilities/exceptions.py
@@ -184,4 +184,6 @@ def warn(self, stacklevel=2):
         warnings.warn(self, stacklevel=stacklevel)

 # Python by default hides DeprecationWarnings, which we do not want.
-warnings.simplefilter("once", SymPyDeprecationWarning)
+deprecation_idx = warnings.filters.index(('ignore', None, DeprecationWarning, None, 0))
+warnings.filters.insert(deprecation_idx,
+                        ('once', None, SymPyDeprecationWarning, None, 0))
```

But I'm not sure that's a good idea, especially given that even with this there doesn't seem to be an effective way to make `-W` filter only SymPy deprecation warnings. This isn't really a problem specific to SymPy. In any instance, `-We` would be overridden by code that calls `warning.filterwarning`. 

(a side note for anyone playing with this, you will want to comment out the filter in [`sympy/__init__.py`](https://github.com/sympy/sympy/blob/c4e836cdf73fc6aa7bab6a86719a0f08861ffb1d/sympy/__init__.py#L31-L37) that enables deprecation warnings in sympy code in development versions, or else it will also affect things).

My conclusion is that best approach here is to simply not use `-W` or `PYTHONWARNINGS`. Instead, insert the filter in Python using `warnings.filterwarnings` or `warnings.simplefilter`, and do so *after* you import SymPy so that it overrides the default filter that SymPy itself adds for SymPyDeprecationWarning (although if you use `category=SymPyDeprecationWarning` this is necessary anyway). For pytest, it seems that adding the filters to the pytest configuration just works as expected, because pytest adds the filters after SymPy is imported.

**Comment by asmeurer** [comment]
I've added documentation on how to use `filterwarnings` at https://github.com/sympy/sympy/pull/22900 (even that is not trivial because you have to prefix your message regex `(?s).*` to match something inside the warning message. 

As far as I can tell, it is basically impossible to use `-W` or `PYTHONWARNINGS` to filter SymPyDeprecationWarnings, except from pytest, so I am going to close this issue (once that PR is merged). If anyone knows how to make them work, please comment here. Otherwise, it seems that the upstream CPython will need to be improved first (I saw in one of the Python issues that there were some security concerns in making `PYTHONWARNINGS` do more, so I'm honestly not hopeful).
