### ISSUE TITLE
Sympify's kernS hangs

### ISSUE THREAD

**Issue by emetor** [sympy/sympy#15132]
The following block of code works fine in Python3:

    from sympy.core.sympify import kernS
    formula = '(1-F)/(1-F*(1-K))'
    kernS(formula)

It produces the correct output:

    (-F + 1)/(-F*(-K + 1) + 1)

However, since I do not always have the control over the exact order of the formula string, it could look like (which is mathematically the same):

    formula = '(1-F)/(1-(1-K)*F)'

Now, running kernS(formula) just hangs. No output, no error, nothing. Any idea how this could be avoided?

**Comment by asmeurer** [comment]
It gets stuck in this loop https://github.com/sympy/sympy/blob/af7b5b23c8ecffeefa1e3452f5aec87a2d863e10/sympy/core/sympify.py#L452-L465

The string `s` gets longer and longer like `'(1-F_kern2_kern2_kern2_kern2_kern2_kern2_kern2_kern2_kern2_kern2_kern2_kern2_kern2_kern2_kern2_kern2_kern2_kern2)/(1_kern-_kern*(1-K)*F)'`

I'm not quite sure where the bug is. According to the commend, `_kern2` should be added after the `)`, but it is added before. Also, should it really be added after the last `)` (that is, should `s` be modified based on this `j`)? https://github.com/sympy/sympy/blob/af7b5b23c8ecffeefa1e3452f5aec87a2d863e10/sympy/core/sympify.py#L453

CC @smichr

**Comment by smichr** [comment]
The last change is critical, the first two are tweaks:
```python
def k(s):
     import re
     from sympy.core.symbol import Symbol
     hit = False
     if '(' in s:
        if s.count('(') != s.count(")"):
            raise SympifyError('unmatched left parenthesis')

        kern = '_kern'
        while kern in s:
            kern += "_"
        olds = s
        # digits*( -> digits*kern*(
        s = re.sub(r'(\d+)( *\* *)\(', r'\1*%s\2(' % kern, s)
        # negated parenthetical
        kern2 = kern + "2"
        while kern2 in s:
            kern2 += "_"
        # step 1:  -(...)  -->  kern-kern*(...)
        target = r'%s-%s*(' % (kern, kern)
        s = re.sub(r'- *\(', target, s)
        # step 2: double the matching closing parenthesis
        # kern-kern*(...)  -->  kern-kern*(...)kern2
        i = nest = 0
        while True:
            j = s.find(target, i)
            if j == -1:
                break
            j = s.find('(', j + len(target) - 1)  #<----
            for j in range(j, len(s)):
                if s[j] == "(":
                    nest += 1
                elif s[j] == ")":
                    nest -= 1
                if nest == 0:
                    break
            s = s[:j] + kern2 + s[j:]
            i = j + 1 #<----
        # step 3: put in the parentheses
        # kern-kern*(...)kern2  -->  -(kern*(...))
        s = s.replace(target, target.replace(kern, "", 1).replace(kern, "("+kern, 1))  #<----
        s = s.replace(kern2, ')')
...
```

I've only tested this with the expression in question and it gives '(1-F)/(1-(_kern*(1-K))*F)'
