### ISSUE TITLE
UndefinedFunction.__hash__()'s use of class_key() broke existing code

### ISSUE THREAD

**Issue by mehrdadn** [sympy/sympy#15170]
Hi, I just learned that commit e210a762d (_"Allow Function('f', is_real=True) != Function('f')"_) broke my code, and I'm not sure if this is a bug in SymPy or not. The problem appears to have been caused by this change:

	class UndefinedFunction(FunctionClass):
	+    def __hash__(self):
	+        return hash((self.class_key(), frozenset(self._extra_kwargs)))

The behavior change is as follows. If I had code such as

	temp = sympy.Function(
		'temp',
		fdiff=lambda self, argindex=1: sympy.cos(self.args[argindex - 1]),
		eval=classmethod(lambda cls, t: None),
		_imp_=classmethod(lambda cls, t: sympy.sin(t))
	)
	print(sympy.diff(temp(sympy.abc.t), sympy.abc.t))

it would print

	cos(t)

under the old implementation of `__hash__`, but under the new implementation, it merely prints

	Derivative(temp(t), t)

which is undesired behavior.

It appears to me that this is a **bug** caused by the value of `_nargs` changing between successive invocations of `__hash__`, which causes the exact _same_ object to hash to two different values. However, I don't really understand the change and I'm entirely sure what the fix would be.

Would you know if this is a bug or not, and what the solution might be? Thank you.

**Comment by asmeurer** [comment]
I don't know why it worked before. The issue is this:

```py
>>> expr = temp(t)
>>> expr.fdiff
<bound method <lambda> of temp(t)>
>>> expr = sympify(expr)
>>> expr.fdiff
<bound method Function.fdiff of temp(t)>
```

The reason is that sympify doesn't recognize `temp(t)` as a SymPy object, and so eventually falls back to parsing `str(temp(t))`, which removes all the custom attributes. 

We shouldn't be using [`sympy_classes`](https://github.com/sympy/sympy/blob/f4984def9f735823411bc5d5b0d9bcb322738303/sympy/core/sympify.py#L266) to determine if an object is a SymPy class. It will eventually be removed. sympify should probably short circuit and return the object as is if it's an instance of a Basic subclass, but I don't know if that will break anything. 

Assuming it does, a less drastic fix to this would be go automatically define `_sympy_` on Function objects that define custom methods.

**Comment by asmeurer** [comment]
OK, I guess `temp` actually is added to sympy_classes from the `BasicMeta.__init__`. 

I think you must be right about the hash changing. That is the only thing that can explain this behavior (from debugging `sympify`).

```py
>>> [i for i in sympy_classes if str(i) == 'temp'][0]
temp
>>> cls
temp
>>> [i for i in sympy_classes if str(i) == 'temp'][0] == cls
True
>>> [i for i in sympy_classes if str(i) == 'temp'][0] is cls
True
>>> hash([i for i in sympy_classes if str(i) == 'temp'][0])
7991973985617563503
>>> hash(cls)
7991973985617563503
>>> cls in sympy_classes
False
>>> [i for i in sympy_classes if str(i) == 'temp'][0] in sympy_classes
False
```

`sympy_classes` is a Python `set`.

**Comment by asmeurer** [comment]
I see what is happening. The very adding of the class to sympy_classes in the metaclasses causes the hash to be calculated before _nargs is computed, because _nargs is added in `__init__`, which gets called at the top of the function. before _nargs is set https://github.com/sympy/sympy/blob/f4984def9f735823411bc5d5b0d9bcb322738303/sympy/core/function.py#L148

I think it should be enough to just move the `super` call to the end of the function. Let's see if that breaks anything.

**Comment by asmeurer** [comment]
Fix at https://github.com/sympy/sympy/pull/15174

**Comment by asmeurer** [comment]
By the way, I believe a workaround that should work is to manually add the class to `sympy.core.core.all_classes`.

**Comment by mehrdadn** [comment]
Oh wow, that was fast! Awesome, thank you!
