### ISSUE TITLE
replacing count in Derivative shouldn't create Subs

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#15194]
```python
>>> Derivative(f(y, g(x)), (x, n)).subs(n, x)
Subs(Derivative(f(y, g(x)), (x, n)), (n,), (x,))
```
This can just be
```
Derivative(f(y, g(x)), (x, x))
```

**Comment by oscarbenjamin** [comment]
That does seem to be what happens now:
```julia
In [1]: Derivative(f(y, g(x)), (x, n)).subs(n, x)                                                                                              
Out[1]: 
  x            
 ∂             
───(f(y, g(x)))
  x            
∂x             

In [2]: Derivative(f(y, g(x)), (x, x))                                                                                                         
Out[2]: 
  x            
 ∂             
───(f(y, g(x)))
  x            
∂x 
```
But what does that mean? You're taking the xth derivative with respect to x?

**Comment by RituRajSingh878** [comment]
```




> In [2]: Derivative(f(y, g(x)), (x, x))                                                                                                         
> Out[2]: 
>   x            
>  ∂             
> ───(f(y, g(x)))
>   x            
> ∂x 
> ```
> 
> But what does that mean? You're taking the xth derivative with respect to x?


```
I think here it should raise some error because it is meaningless and for that, there should be some conditions in the argument of `Derivative` like in` (x, x)` second argument should be a constant else it should raise an error.

**Comment by asmeurer** [comment]
The subs version makes sense (it means replace the variable x with the number n after differentiating). So should we allow the non-subs version as well?

**Comment by asmeurer** [comment]
Actually never mind I was think of the reverse substitution.

**Comment by smichr** [comment]
> You're taking the xth derivative with respect to x?

Think of the wrt variable as a bound symbol and the count as a free symbol, so `(x**2).diff((x,x)) == (y**2).diff((y, x))`; when you substitution x->2 you should get the 2nd derivative. The `_eval_subs` method of Derivative should sort out the details.

This was [tested here](https://github.com/sympy/sympy/pull/15049 but it wasn't tested whether the result would accept a number for x:
```python
>> Derivative(f(x).diff((x,x)).subs(x,3)
Subs(Derivative(f(x),(x,3)),x,3)
```

**Comment by asmeurer** [comment]
I had thought we disallowed fractional derivatives, since they are ambiguous, but I just tested it and they don't raise any exceptions. I guess we leave them unevaluated in case someone wants to manipulate them formally. 

Assuming we did, then the expression is a bit odd since `x` should be a continuous variable, but `n` can only be a nonnegative integer. Even so I don't see a reason to disallow it. Formally it can make sense if we replace `x` with a nonnegative number, assuming it is done in the correct order as you say (actually the correct order should be the reverse of the Subs that you show in the OP). In other words, `diff(f(n), (n, n))` means differentiate `f` `n` times, then evaluate it at `n`. 

And even if it didn't make sense I would apply the Garbage in-garbage out principle.
