### ISSUE TITLE
Integral and Sum (and similar) should compare equal ignoring dummy

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#15240]
Subs has an `__eq__` method that allows trivial differences in equality comparisons to be ignored. Integral and Sum do not. The same could apply to Product, I suspect:
```python
>>> Subs(x+y,x,a)==Subs(z+y,z,a)
True
>>> Integral(x,(x,1,a))==Integral(y,(y,1,a))
False
>>> Sum(x,(x,1,a)) == Sum(y,(y,1,a))
False
```

**Comment by ayushmankoul** [comment]
Hello @smichr I reciprocated your code to understand the issue.And as you suspected the same happens with `Product` method also. I would like to work on this issue. Can you please guide me how to proceed on this ? And do we need to alter `__eq__` method to catch the trivial differences and return False for it ?

**Comment by asmeurer** [comment]
Lots of discussions about this at https://github.com/sympy/sympy/issues/5539 (and see also the xrefed issues and PRs). I agree that we should not do dummy comparison with ==. I believe Lambda also has the same behavior.

**Comment by asmeurer** [comment]
Oh I misread what you were suggesting. I think we should **not** compare with dummies. It leads to problems. For instance one version gets put in the cache and others get replaced with it.

**Comment by smichr** [comment]
The reason that I think this is a good idea is that it shouldn't matter what version of the expression is used and any code that depends on knowing what the dummy symbol is is probably doing the wrong thing (i.e. they should be considering free symbols, not bound symbols).  Subs already collapses:

```
>>> Subs(x, x, 1) + Subs(y, y, 1)
2*Subs(x, x, 1)
```
Is there any reason to keep `Sum(x, (x, 1, 2)) + Sum(y, (y, 1, 2)` from being `2*Sum(z, (z, 1, 2))`?

The only reason I can think of is for representational purposes. If you don't know what the dummy symbol is going to be, how will you control what the output will look like? 

This is different from keeping `x + y` from collapsing to `2*x` since we don't know that they are equal. But when two dummy-driven objects are identical *except for dummy symbol* then they trivially represent the same thing (like 1 == 1.). If the objects happen to have different structure but arrive (after doit) at the same value they would/should compare as unequal until doit was called, e.g. `Integral(1, (x, 1, 2)) != Integral(1, (x, 2, 3)` since that is in keeping with the structural equality model.

In an old issue I think the caching of `f(x).diff(x)` had to be dropped since otherwise `f(y).diff(y)` would compare the same. But here, the x is not really a dummy symbol, it's a free variable of differentiation. Lets say `f(u) = u**2/2`. `f(x).diff(x) == x` but `f(y).diff(y) == y`...so they aren't necessarily the same.

A conservative path forward would be to have a method (as I suggested in the mentioned issue) called `fold_symbols` which would give a canonical numbered symbol to objects that use them. This would then lead to natural simplification.

Another option would be to use this folding in a `dummy_eq` method that would allow any two objects to compare with each other.

**Comment by asmeurer** [comment]
I agree mathematically they are equal. The problem is that SymPy uniformly assumes that if a == b then a can be replaced with b anywhere. The cache is one place where this happens but it also happens in other places too. 

Generally people like to specify a specific integration variable. So if `Integral(f(t)*exp(-I*pi*t*x), (t, -oo, oo))` becomes `Integral(f(y)*exp(-I*pi*x*y), (y, -oo, oo))` that would be bad because `t` has a representational meaning (like "time"), even inside the integral. 

I think the cache alone is reason not to do this. There's no predicting where the cache will "catch" a previously used integral with a different integration variable and swap it out. It would be an apparently random issue, that only happens under specific circumstances (a cached function must be used, the same integral sans dummy variable must have already been passed to it, it must still be in the LRU by then, and so on).

**Comment by smichr** [comment]
cf #14324
