### ISSUE TITLE
`linear_eq_to_matrix` on `Eq` has unevaluated results

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#15312]
@smichr @czgdp1807 I just noticed a problem with your nice work on `linear_eq_to_matrix` when combined with `Eq` inputs.  I often get results with unevaluated Adds like:
```py
b = 
  ⎡  1   ⎤
  ⎢      ⎥
  ⎣-1 + 0⎦
```

Here's a minimal example:
```py
>>> linear_eq_to_matrix(Eq(x + 2, 1), x)
(Matrix([[1]]), Matrix([[-2 + 1]]))
```
Probably this is because care was taken to prevent simplifing when doing `lhs - rhs` for `Eq` inputs.  Perhaps we should call `.doit()` to the final RHS vector?

**Comment by llucifer97** [comment]
I would like to take up his issue.

**Comment by cbm755** [comment]
Sure, go for it.

I'm not sure my doit comment is the right fix, but its a place to start.

**Comment by smichr** [comment]
similar trouble showed up with #15307

**Comment by smichr** [comment]
I would recommend replacing any rhs `foo` with `foo.func(*foo.args) if foo.args else foo` so other unevaluated things that may be lurking will not become evaluated.

**Comment by ayushmankoul** [comment]
Hello, @cbm755 I am trying to replicate this issue on my local machine, can you please share your full code so that I am able to understand it. Also, I tried to replicate your given minimal example it shows `Type Error:'Equality' object is not iterable`.
The solution which @smichr has recommended is it like the following changes in :- 

```

**Comment by cbm755** [comment]
Probably you are not running git master
