### ISSUE TITLE
Change Beam.plot_loading_results() to use the SymPy plotting module

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#15328]
`Beam.plot_loading_results()` currently uses matplotlib directly because the desired plot is a subplot. This means the plots don't look as nice and the defaults used in `sympy.plot()`. We should be able to make subplots using `sympy.plot()` but it currently is not supported. One fix is to add subplot support or use a hack in the Beam code, for example: https://stackoverflow.com/a/15834752/467314

**Comment by aionkgp** [comment]
I am a beginner here and I would really like to work on this one. would this be okay for a beginner to work on this bug?

**Comment by moorepants** [comment]
Yep, go for it.

**Comment by aionkgp** [comment]
I am bit confused here, @moorepants, are you suggesting that all the graph should come in one figure, instead of any subplots by the using `plot1.append(plot2)` or `plot1.extend(plot2)`?
If that is the case please notice that the range of `slope` and `deflection` is quite small compared to other parameters, hence the plot of `slope` and `deflection` can't be distinguished from `x-axis`
![figure_1](https://user-images.githubusercontent.com/43279204/46446762-cc861e00-c79b-11e8-99a5-b260a8153502.png)

**Comment by moorepants** [comment]
The figure should contain subplots, just like it already does, but it should make use of sympy.plot() so that we get the adaptive sampling and other niceties built into sympy.plot().

**Comment by aionkgp** [comment]
I am really having a hard time here on using `_backend`, is there anything I could take reference of? I can't find any documentation on using `_backend`.

**Comment by moorepants** [comment]
I am not familiar with the sympy.plotting module. You can use git blame to find out who last worked on code in specific files. Then you can ask them.

**Comment by jashan498** [comment]
@aionkgp we are not passing a `sympy.plot` object to `axs[x].plot` there. They are just numpy arrays containing `x` and `y` values for the subplot.
`lambdify` is simply required to convert SymPy method to numpy function (as we are directly using matplotlib here).

**Comment by aionkgp** [comment]
@Krastanov  , I am having trouble using the `backend` to use sympy plots to plot multiple objects in same file. So I took the reference from [Stack overflow : Sympy: generate figure with multiple subplots](https://stackoverflow.com/a/15834752/467314)
So hee is what I was trying :
I haven't taken multiple objects here, just for the simplicity, here I am trying to plot single sympy plot as a single subplot in matplotlib
```
>>> from sympy import plot, symbols
>>> from matplotlib import pyplot as plt
>>> x=  symbols('x')
>>> foo = x**3
>>> p = plot(foo)
>>> matplotlib_fig = plt.figure()
>>> sp = matplotlib_fig.add_subplot(111)
>>> sp.add_collection(p._backend.ax.get_children()[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aion/.local/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 1845, in add_collection
    self._set_artist_props(collection)
  File "/home/aion/.local/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 912, in _set_artist_props
    a.set_figure(self.figure)
  File "/home/aion/.local/lib/python3.6/site-packages/matplotlib/artist.py", line 644, in set_figure
    raise RuntimeError("Can not put single artist in "
RuntimeError: Can not put single artist in more than one figure
```
can you suggest something for this one?

**Comment by Krastanov** [comment]
Hello, @aionkgp, @moorepants,

It has been more than 4 years since I wrote the module or have contributed significantly, so take my comments with a grain of salt.

I would suggest extending the plotting module to support sub plots instead of abusing the `_backend.fig` object. The `_backend.fig` object seems great for one-off changes, especially when using more esoteric `matplotlib` commands, but it does not really know about anything related to adaptive sampling and other sympy specific additions.

Moreover, unlike other plotting libraries, `matplotlib` makes a very big distinction between a figure and a subplot - you can not use a figure that is already made and nest it in another figure as a subplot after the fact. However, you can add a subplot to an already created figure.

With all of this in mind, my suggestion would be to create a new class `sympy.PlotGrid` which just takes a bunch of already created `sympy.Plot`s and coordinates for where to place them (kinda like `matplotlib`'s `gridspec`). Then extend `BaseBackend` and `MatplotlibBackend` to accept both `Plot` or `PlotGrid`. In the case of `PlotGrid` we just need `MatplotlibBackend` to use `gridspec` instead of having one singe axis. Everything else should be the same (no need to modify `Plot` or any of the large family of `Series` objects). I am hopeful it is less than 50 lines of code changes.

@aionkgp, I would be happy to provide feedback on any code you might want to write. It has been a few years since I have had commit privileges for the repository, but I imagine @moorepants would be able to give the final review/approval if the code works.

**Comment by Krastanov** [comment]
P.S. Pretty much the one thing that needs to change is on this line https://github.com/sympy/sympy/blob/master/sympy/plotting/plot.py#L908

Turn it into `for s, ax in zip(self.parent._series, self.parent._axes):` and make the according changes in the rest of the code.

**Comment by moorepants** [comment]
Note that I'm ok with the "hack" in the beam code for now as quick solution. But feel free to solve it properly as @Krastanov suggests. That would be very nice if implemented.

**Comment by ishanaj** [comment]
@moorepants @jashan498  I have tried to implement `PlotGrid` as suggested by krastanov in PR #16276 
And  `plot_loading_result()` could now use `PlotGrid` to show something like the image below.
I will be opening a separate PR to change `plot_loading_results()` once this PR gets approved
Please have a look

![Screenshot - 24-03-2019 , 19_11_38](https://user-images.githubusercontent.com/29159034/54880436-8bc5b280-4e6a-11e9-9bd3-025961be0d0f.png)

**Comment by moorepants** [comment]
Looks nice, looking forward to the PR.

**Comment by ishanaj** [comment]
@moorepants PR #16276 is good to go. Can it be merged, so that I could start a new PR regarding the changes in beam `plot_loading_results()`.
