### ISSUE TITLE
factorint() leaks memory

### ISSUE THREAD

**Issue by david-r-wasserman** [sympy/sympy#15405]
I have sympy version 1.3, and ran this code: 
`from sympy.ntheory import factorint
from sympy.ntheory.primetest import isprime

for i in range(50000):
    z = factorint(10**18 + i*165757)
	
sympy.cache.clear_cache()
import pdb; pdb.set_trace()
print('done')`

The "pdb.set_trace()" is there just to make it pause before exiting. It's paused now, and my Windows Task Manager says Python is using 7920 MB of memory.

**Comment by jksuom** [comment]
Is that the amount of memory actually used by Python, or is it the amount of maximum virtual memory reserved?

**Comment by david-r-wasserman** [comment]
I don't know how to tell the difference. What I do know is that this amount
of memory gradually increases as the program runs. If I continue factoring,
I eventually get a MemoryError.

**Comment by asmeurer** [comment]
I can reproduce it as well.

**Comment by Mohitbalwani26** [comment]
I would like to work on this issue.can you please provide details?

**Comment by jksuom** [comment]
There is an lru cache decorator implemented in Python 3 library and backported to Python 2.7 in compatibility.py. Its signature is `lru_cache(maxsize=128, typed=False)` (`maxsize=100` in Python 2.7). The default parameter values would probably suffice for a gcd cache. The arguments are of one type (integer) only so `typed=False` should be correct. The size could be bigger without taking too much memory space, but that would seldom be necessary in practical applications.

There are two functions where the decorator could be applied, `igcd` and `igcd2`. The current implementation is caching the return values of `igcd2`. It is optimized to cache `gcd(a, b)` with two keys, `(a, b)` and `(b. a)`. That cannot be implemented with the library version of `lru_cache`. Therefore, there does not seem to exist an obvious reason to prefer either one of the two functions. Maybe both possibilities should be tested.

The implementation is as follows.
* Remove `sympy.core.numbers._gcdcache` and the code in `igcd` handling the cache.
* Import `lru_cache` from `sympy.core.compatibility`.
* Add one of the following:
    * `@lru_cache()` before `def igcd(*args):`.
    * `igcd2 = lru_cache()(igcd2)` after `igcd2` has been defined.

**Comment by asmeurer** [comment]
Actually it should use fastcache if it is available too. See the code in sympy.core.cache. Probably some of the code should be moved to sympy.core.compatibility so that other things can use it too aside from the global cache. 

I would also do some analysis to determine an optimal maxsize. Since each entry only stores three (albeit large) integers, it shouldn't be a big deal to increase the size. The cache_info attribute that lru_cache sets on the function can be useful for this. 

I'm also curious if the cache is actually useful for integers of a certain size. If a pair of very large integers (say 10 digits or more each) get added to the cache, does their gcd ever get computed again? This probably depends on the algorithm being used, but I suspect the answer is no for most algorithms (unless of course the user calls the same function with the same inputs twice).
