### ISSUE TITLE
`solveset(x-oo)` returns EmptySet() instead of `oo`

### ISSUE THREAD

**Issue by JMSS-Unknown** [sympy/sympy#15442]
`solveset(x-oo)` should return `oo` instead of EmptySet(). The same error occurs when using `float("inf")`.

Seems to be related to the following
```python
from sympy.solvers.solveset import _invert
from sympy.abc import x, y

>>> _invert(x-oo,0,x)
(x, EmptySet())
>>> _invert(x-y,0,x)
(x, {y})
```

**Comment by JMSS-Unknown** [comment]
Is this expected behaviour as oo-oo is an indeterminate form? Should there be a distinction between `solveset(Eq(x,oo))`?

**Comment by asmeurer** [comment]
solveset gives solutions from a specific domain, the default being Complexes. Since oo is not in the domain set, it isn't returned. 

```py
>>> oo in Complexes
False
```

`solve` can return a solution here. 

Perhaps `solveset(x - oo, domain=Union(S.Complexes, FiniteSet(oo)))` should work, but as far as I know no work has been done in solveset to support solutions like this.

**Comment by pulkit6559** [comment]
@asmeurer I would like to work on this, a little guidance would really help

**Comment by asmeurer** [comment]
I'm not sure there is anything to be done here. The current answer is correct, as I noted. `domain=Union(S.Complexes, FiniteSet(oo))` doesn't work, but that isn't supported (perhaps it should give be giving an error, but that's it).

**Comment by jksuom** [comment]
It seems that `x - oo` is different from zero for any object `x`. Therefore the empty set looks like the correct answer.

**Comment by JMSS-Unknown** [comment]
Closing, as there is nothing to be done.
