### ISSUE TITLE
Sympy does not calculate

### ISSUE THREAD

**Issue by Simarglur** [sympy/sympy#15481]
In Wolfram Mathematica 11.3:
`In[34]:=NSolve[exp (2*I*k0) - 3*exp (6*I*k0) - 1 == 0, k0]
Out[34]={{k0 -> (0. + 0.0625 I)/exp}}
`
In Sympy:
`>>>froot = solveset(exp(2*I*k0) - 3*exp(6*I*k0) - 1)
very large answer
`
In Wolfram Mathematica 11.3:
`In[33]:=NSolve[(E^(200 I k0) - 3 E^(600 I k0))/(-3 + E^(400 I k0)) == 
   1 && -0.05067731239 <= Re[k0] <= 0.05067731239, k0]
Out[33]={{k0 -> -0.0429185 + 0. I}, {k0 -> -0.0314159}, {k0 -> -0.0199133 + 
    0. I}, {k0 -> -0.0115026 + 0. I}, {k0 -> 0.}, {k0 -> 
   0.0115026 + 0. I}, {k0 -> 0.0199133 + 0. I}, {k0 -> 
   0.0314159}, {k0 -> 0.0429185 + 0. I}}
`
In Sympy:
this example does not work

**Comment by normalhuman** [comment]
It is not clear whether you want a numeric solution or a symbolic solution. You asked Mathematica for a numeric solution, then asked SymPy for a symbolic solution, and found the outcomes very different -- yes they are, because these are entirely different tasks. 

In SymPy, numerical solutions are found with `nsolve`. It returns one solution, which may depend on the starting point. 

```
>>> nsolve(exp(2*I*k0) - 3*exp(6*I*k0) - 1, 0)
0.411293336569312 + 0.234429795338556*I
>>> nsolve((exp(200*I*k0) - 3*exp(600*I*k0))/(-3 + exp(400*I*k0)) - 1, 0)
0
>>> nsolve((exp(200*I*k0) - 3*exp(600*I*k0))/(-3 + exp(400*I*k0)) - 1, 0.01)
0.262830032202293 - 8.89523424232382e-24*I
```

A symbolic solution is easier to find in terms of the quantity `y = exp(200*I*k0)` because then there are finitely many solutions in all.  
```
>>> expr = (exp(200*I*k0) - 3*exp(600*I*k0))/(-3 + exp(400*I*k0)) - 1
>>> e2 = expr.subs(exp(200*I*k0), y)
>>> solveset(e2, y)   # or solve(e2, y), same result
{1, -2/3 - sqrt(5)*I/3, -2/3 + sqrt(5)*I/3}
```
This can be turned into a symbolic description of all solutions.
```
>>> y_sol = solveset(e2, y)
>>> [solveset(exp(200*I*k0)- y) for y in y_sol]
[ImageSet(Lambda(_n, _n*pi/100), Integers), ImageSet(Lambda(_n, _n*pi/100 + atan(sqrt(5)/2)/200 + pi/200), Integers), ImageSet(Lambda(_n, _n*pi/100 - atan(sqrt(5)/2)/200 + pi/200), Integers)]
```
or in a more readable form,
```
>>> pprint([solveset(exp(200*I*k0)- y) for y in y_sol])
⎡               ⎧          ⎛√5⎞              ⎫  ⎧          ⎛√5⎞              ⎫
⎢               ⎪      atan⎜──⎟              ⎪  ⎪      atan⎜──⎟              ⎪
⎢⎧n⋅π        ⎫  ⎨n⋅π       ⎝2 ⎠    π         ⎬  ⎨n⋅π       ⎝2 ⎠    π         ⎬
⎢⎨─── | n ∊ ℤ⎬, ⎪─── + ──────── + ─── | n ∊ ℤ⎪, ⎪─── - ──────── + ─── | n ∊ ℤ⎪
⎣⎩100        ⎭  ⎩100     200      200        ⎭  ⎩100     200      200        ⎭

⎤
⎥
⎥
⎥
⎦
```

**Comment by jmig5776** [comment]
I think we should close this issue.
