### ISSUE TITLE
sympy.plot sampling issue with logarithmic axis

### ISSUE THREAD

**Issue by boffi** [sympy/sympy#15556]
It looks like `plot` is sampling in a linear space even if the plot command requested a logarithmic x-axis.
Minimum example
```
from sympy import cos, log, plot
from sympy.abc import x
plot(sin(log(x), (x, .001,10), xscale='log')
```
produces
![figure_3](https://user-images.githubusercontent.com/2244221/49146921-8795e800-f303-11e8-8b1a-37ed27b0831d.png)
while, e.g., Gnuplot 
```
gnuplot> set xrange [.001: 10]
gnuplot> set log x
gnuplot> plot sin(log(x))
```
gives
![sin](https://user-images.githubusercontent.com/2244221/49147787-e9575180-f305-11e8-952f-e1df7ef23ff6.png)

**Comment by ayushmankoul** [comment]
Hi, @moorepants @boffi I would like to work on this issue if anyone isn't working on it yet. With reference to statements and example given by @boffi, I am able to interpret that the given code should have the return logarithmic x-axis instead of the normal x-axis and as it fails to so do we need to alter the ``plot`` function in plotting module. Please correct me if I am wrong and let me know how to go about this issue.

**Comment by moorepants** [comment]
The values for the x axis need to be logarithmic instead of linear. You'll need to see how the x values are created in the plotting code and then have a check for logarithmic graphs and use np.logspace instead of np.linspace.

**Comment by ajit2704** [comment]
@ayushmankoul  are you still on this issue?

**Comment by ayushmankoul** [comment]
Yes, @ajit2704 I am working over it.
