### ISSUE TITLE
rsolve can not solve this kind of recurrences. 

### ISSUE THREAD

**Issue by Jianwei0817** [sympy/sympy#15553]
Is there any algorithm which can solve recurrences with the form of f(n+1)=2f(n)+n^2+1 f(1)=0 correctly in sympy? Note: rsolve cannot

**Comment by normalhuman** [comment]
Something is missing here. What kind of recurrences? Please add an example.

**Comment by loopxia** [comment]
> Something is missing here. What kind of recurrences? Please add an example.

I have encountered a similar issue:

u(0) = 1
u(n) = 2 u(n-1) +3 n^2

sympy gives: -2**n/2 + 3*n**2/2 + 3*n + 3/2

Mathematica gives a right answer: -18 +19*2^n -12*n - 3*n^2


Sympy version: 1.7.1

**Comment by oscarbenjamin** [comment]
A simpler example suggests the possible problem:
```python
In [36]: rsolve(Eq(f(n), 2*f(n-1) + n), f(n))
Out[36]: 
 n                
2 ⋅C₀ + C₀⋅(n + 1)
```
Here the last term should be `-n-2` and should not have any constant `C0`.

It is generated here:
https://github.com/sympy/sympy/blob/6783a0962206feab1cb361eb02ba73e01d3669dd/sympy/solvers/recurr.py#L543-L567
The `rsolve_poly` function returns `C0` which is multiplied by the inhomogeneous term.

It doesn't look like the arguments to `rsolve_poly` are right at all:
```
558  	                denoms[j] = q
559  	
560  	            for j in range(r + 1):
561  	                polys[j] *= Mul(*(denoms[:j] + denoms[j + 1:]))
562  	
563 B->	            R = rsolve_poly(polys, Mul(*denoms), n)
564  	
565  	            if not (R is None or R is S.Zero):
566  	                inhomogeneous[i] *= R
567  	            else:
568  	                return None
(Pdb) p polys
[-2*n - 2, n + 2]
(Pdb) p denoms
[1, n + 1]
```
From the docstring of `rsolve_poly` the way it should be called is with a difference operator as the first argument and a polynomial as the second argument:
https://github.com/sympy/sympy/blob/6783a0962206feab1cb361eb02ba73e01d3669dd/sympy/solvers/recurr.py#L69-L105
For example in this case I think that the expected arguments `rsolve_poly` would be
```
In [1]: rsolve_poly([-2, 1], (n+1), n)
Out[1]: -n - 2
```
I tried this:
```diff
diff --git a/sympy/solvers/recurr.py b/sympy/solvers/recurr.py
index 93cdb04741..bc61952eca 100644
--- a/sympy/solvers/recurr.py
+++ b/sympy/solvers/recurr.py
@@ -557,10 +557,10 @@ def rsolve_hyper(coeffs, f, n, **hints):
             for j in range(r + 1):
                 polys[j] *= Mul(*(denoms[:j] + denoms[j + 1:]))
 
-            R = rsolve_poly(polys, Mul(*denoms), n)
+            R = rsolve_poly(coeffs, Mul(*denoms), n)
 
             if not (R is None or R is S.Zero):
-                inhomogeneous[i] *= R
+                inhomogeneous[i] = R
             else:
                 return None
```
That gives:
```python
In [5]: rsolve(Eq(f(n), 2*f(n-1) + n), f(n))
Out[5]: 
 n           
2 ⋅C₀ - n - 2

In [6]: rsolve(Eq(f(n+1), 2*f(n) + n**2 + 1), f(n))
Out[6]: 
 n       2          
2 ⋅C₀ - n  - 2⋅n - 4

In [7]: rsolve(Eq(f(n+1), 2*f(n) + n**2 + 1), f(n), {f(1):0})
Out[7]: 
   n               
7⋅2     2          
──── - n  - 2⋅n - 4
 2   
```
There are some other cases that it doesn't work for though because it ignores any coefficients or extra terms:
```python
In [8]: rsolve(Eq(f(n), 2*f(n-1) + 3*n**2), f(n))  # not correct
Out[8]: 
 n       2          
2 ⋅C₀ - n  - 4⋅n - 6

In [9]: rsolve(Eq(f(n), 2*f(n-1) + n**2), f(n))  # correct
Out[9]: 
 n       2          
2 ⋅C₀ - n  - 4⋅n - 6
```
The diff above is not the full fix but I think it hints at where the problem is. If anyone wants to try and figure out how to make that work properly go ahead.

**Comment by Gritbadger** [comment]
I found the answer you gave is probable not right, here is I use the mathematica software , and it gives me an answer is 
![image](https://user-images.githubusercontent.com/101034640/170876930-40ed33bc-05f9-4480-b9d2-f6af1b390848.png)
My answer is right or not?

**Comment by oscarbenjamin** [comment]
The answer from Mathematica is equivalent to the one I showed but just not as simplified:
```python

In [14]: e = -2*(3 - 2**n - 3*2**(1+n) + 2*n + n**2/2) + 2**(-1 + n)*C1

In [15]: e
Out[15]: 
   n    n - 1         n + 1    2          
2⋅2  + 2     ⋅C₁ + 6⋅2      - n  - 4⋅n - 6

In [16]: e.expand()
Out[16]: 
 n                          
2 ⋅C₁       n    2          
───── + 14⋅2  - n  - 4⋅n - 6
  2                         

In [17]: e.expand().collect(2**n)
Out[17]: 
 n ⎛C₁     ⎞    2          
2 ⋅⎜── + 14⎟ - n  - 4⋅n - 6
   ⎝2      ⎠  
```
Then if the constant is redefined it's the same as what I showed.

**Comment by Gritbadger** [comment]
Another example is ,I operate in sympy, get the answer 
![image](https://user-images.githubusercontent.com/101034640/170877586-42f117bd-6902-4261-be64-20885b70ca64.png)
But when I use operate by mathematica, I get a very different answer , 
![image](https://user-images.githubusercontent.com/101034640/170877676-e5fbb1d1-83dc-41bc-807a-4e4d961af1d4.png)
Why?

**Comment by oscarbenjamin** [comment]
It's the same bug. Again if you apply the diff I showed above then `rsolve` gives:
```python
In [22]: rsolve(Eq(f(t), 2*f(t-1) + t), f(t), {f(0):1})
Out[22]: 
   t        
3⋅2  - t - 2
```
