### ISSUE TITLE
Matrix power failure

### ISSUE THREAD

**Issue by Upabjojr** [sympy/sympy#15593]
```python
rot_z_generator = Matrix([
    [0, 1, 0],
    [-1, 0, 0],
    [0, 0, 0]
])
k = symbols("k")
```

`rot_z_generator**k` raises an exception:

```
ValueError: Matrix det == 0; not invertible
```

**Comment by jksuom** [comment]
Negative powers of a non-invertible matrix are not well defined. The exception is raised as `k` can be negative.

**Comment by Upabjojr** [comment]
I believe it should raise an exception only if `k.is_negative == True`. The case `k.Is_negative == None` should still be valid, in my opinion.

**Comment by Upabjojr** [comment]
Yes, that could be a solution.

**Comment by jmig5776** [comment]
Ok  i will do it

**Comment by jmig5776** [comment]
@Upabjojr You can review it ,any suggestions would be helpful.

**Comment by asmeurer** [comment]
> I believe it should raise an exception only if k.is_negative == True. The case k.Is_negative == None should still be valid, in my opinion.

I agree with this. For things that aren't defined, the behavior on symbolic values should be to error only if the assumption is known, and remain unevaluated for `None`. This is also how most functions that require integers work as well. This works because if `k` does end up being negative, then the value is undefined, so the value is garbage in, garbage out.
