### ISSUE TITLE
Beam.apply_support() wrong result for plural fixed supports

### ISSUE THREAD

**Issue by tehen-ni-ishi** [sympy/sympy#15663]
* Beam.apply_support() clears `self.bc_deflection` in [beam.py#L343](https://github.com/sympy/sympy/blob/e3b2c4e302c05d4a438fdebb49d348010b71c882/sympy/physics/continuum_mechanics/beam.py#L343) \
`self.bc_deflection = [(loc, 0)]`
* I think this line should be \
`self.bc_deflection.append((loc, 0))`
* For example, "Left end fixed, right end fixed" fails:

```py
from sympy import *
from sympy.physics.continuum_mechanics.beam import Beam

E, I = symbols('E, I')
P, L = symbols('P, L', positive=True)
b = Beam(L, E, I)

b.apply_support(0, type='fixed')
b.apply_support(L, type='fixed')
b.apply_load(-P, L/2, -1)

b.solve_for_reaction_loads(*(i[0] for i in b.applied_loads))
b.reaction_loads
# {R_0: 3*P/4 - 2*M_L/L, M_0: -L*P/4 + M_L, R_L: P/4 + 2*M_L/L, M_L: M_L, -P: -P}
# should be: {R_0: P/2, M_0: -L*P/8, R_L: P/2, M_L: L*P/8, -P: -P}
```

* [tests/test_beam.py](https://github.com/sympy/sympy/blob/master/sympy/physics/continuum_mechanics/tests/test_beam.py) dont test such case

**Comment by moorepants** [comment]
@jashan498 fyi

**Comment by jashan498** [comment]
Thanks @tehen-ni-ishi for pointing that out. Must have been a typo as `bc_slope` under it appends `(loc, 0)` rather than overwriting itself.
You should create a Pull Request with the fix, along with your test case inside [test_apply_support](https://github.com/sympy/sympy/blob/3af6aca4c381f86d0781a393f842b7a0203573fd/sympy/physics/continuum_mechanics/tests/test_beam.py#L394) method.
