### ISSUE TITLE
Cannot plot piecewise function

### ISSUE THREAD

**Issue by s1291** [sympy/sympy#15702]
I noticed that some piecewise function cannot be plotted (i know this is an old issue and it has been solved). But for the following function I get an error:
`TypeError: '<' not supported between instances of 'complex' and 'float'`

Here is my function (using sympy v1.3):
```
from sympy import *
from sympy.abc import x
f1 = Function('f1')
f2 = Function('f2')
f3 = Function('f3)
f1 = sin(x)
f2 = Abs(x)
f3 = x**2
f = Piecewise((f1, x < -pi),(f2, x < 1.0), (f3, True)) 
plot(f)
```
**NOTE**: This works for example for [this](https://stackoverflow.com/questions/46187713/sympy-issues-with-plotting-a-piecewise-function), hat function, ...etc. but not with the function above.

**Comment by RituRajSingh878** [comment]
i think problem is with "f1 = sin(x)", because it is working fine with other function like- 
from sympy import *
from sympy.abc import x
f1 = Function('f1')
f2 = Function('f2')
f3 = Function('f3)
f1 = x
f2 = Abs(x)
f3 = x**2
f = Piecewise((f1, x < -pi),(f2, x < 1.0), (f3, True)) 
plot(f)

**Comment by adeak** [comment]
I could narrow down the bug a bit: it seems to come from `sympy.plotting.experimental_lambdify.lambdify` which [gets called here](https://github.com/sympy/sympy/blob/master/sympy/plotting/plot.py#L544-L545) during evaluation of the function:
```
from sympy import sin,pi,Abs,Piecewise,lambdify
from sympy.abc import x
from sympy.plotting.experimental_lambdify import lambdify as expt_lambdify
f1 = sin(x)
f2 = Abs(x)
f3 = x**2
f = Piecewise((f1, x < -pi), (f2, x < 1.0), (f3, True))
g = expt_lambdify([x], f)

print(g(0)) # works
print(g(0)) # breaks
```
Output:
```
0
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.7/site-packages/sympy/plotting/experimental_lambdify.py", line 194, in __call__
    result = complex(self.lambda_func(args))
  File "/home/user/.local/lib/python3.7/site-packages/sympy/plotting/experimental_lambdify.py", line 316, in __call__
    return self.lambda_func(*args, **kwargs)
  File "<string>", line 1, in <lambda>
TypeError: can't convert complex to float

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tmp2.py", line 11, in <module>
    print(g(0)) # breaks
  File "/home/user/.local/lib/python3.7/site-packages/sympy/plotting/experimental_lambdify.py", line 231, in __call__
    result = self.lambda_func(args)
  File "/home/user/.local/lib/python3.7/site-packages/sympy/plotting/experimental_lambdify.py", line 316, in __call__
    return self.lambda_func(*args, **kwargs)
  File "<string>", line 1, in <lambda>
TypeError: '<' not supported between instances of 'complex' and 'float'
```

I don't know what's going on under the hood and why I can't trigger the same behaviour by omitting any of the three functions, but the fact that the second evaluation of the lambdified function triggers the error looks really weird.

**Comment by RituRajSingh878** [comment]
Main problem is with f1=sin() .

**Comment by adeak** [comment]
I believe I've tracked down the path of the error and it's definitely a bug in `experimental_lambdify`.

What happens is that calling `experimental_lambdify.lambdify` [first calls `experimental_lambdify.experimental_lambdify`](https://github.com/sympy/sympy/blob/master/sympy/plotting/experimental_lambdify.py#L186-L187) with a `use_python_cmath=True` kwarg.

When the resulting callable is first evaluated, [its args are converted to complex and we attempt to evaluate the function](https://github.com/sympy/sympy/blob/master/sympy/plotting/experimental_lambdify.py#L191-L194):
```
    def __call__(self, args):
        args = complex(args)
        try:
            #The result can be sympy.Float. Hence wrap it with complex type.
            result = complex(self.lambda_func(args))
```
This will attempt to compare the complexified input value (say, `0j`) to `-pi` in the `Piecewise`, leading to the `TypeError: '<' not supported between instances of 'complex' and 'float'`.

This is [caught and handled right after](https://github.com/sympy/sympy/blob/master/sympy/plotting/experimental_lambdify.py#L211-L221), and `experimental_lambdify.experimental_lambdify` is called again to replace `self.lambda_func`, now with `use_python_math=True` (note the missing `c` in `math`). This will work for the first call:
```
                self.lambda_func = experimental_lambdify(self.args, self.expr,
                                                         use_evalf=True,
                                                         use_python_math=True)
                result = self.lambda_func(args.real)
                return result
```
since in effect we're passing `complex(args).real` for the original input `args` to `lambdify`, so we get a result.

Now, on the second call to the lambda we get back [here](https://github.com/sympy/sympy/blob/master/sympy/plotting/experimental_lambdify.py#L190-L194):
```
    def __call__(self, args):
        args = complex(args)
        try:
            #The result can be sympy.Float. Hence wrap it with complex type.
            result = complex(self.lambda_func(args))
```
But by now `self.lambda_func` has been replaced by the first call, to the result of `experimental_lambdify` using `math` rather than `cmath`. So when we pass the complex args we get
`TypeError: can't convert complex to float`. I believe this is the first error shown in my previous comment. This case isn't handled [here](https://github.com/sympy/sympy/blob/master/sympy/plotting/experimental_lambdify.py#L211-L221), so now we enter the ["failure" block](https://github.com/sympy/sympy/blob/master/sympy/plotting/experimental_lambdify.py#L222-L238).

Here the `self.lambda_func` is replaced yet again by `experimental_lambdify.experimental_lambdify`, now with a `complex_wrap_evalf=True` kwarg. The function is evaluated yet again with complex arguments, leading to a final  `TypeError: '<' not supported between instances of 'complex' and 'float'` (from the comparison of the `Piecewise` cases I presume) which, I believe, is the second error in my previous comment.

So somewhere down this maze of heuristics this combination of inputs doesn't get handled. This is the bug. We need `sin(x)` to be in there to trigger the bug, but we can replace it with any of the functions in `cmath` and still get the same error (OK, I only checked `sinh`, `tan` and `exp`). I don't understand why, but I suspect somehow the reason for this is that these functions return `complex`-type results in `cmath` (why this happens might have to do the internals of lambdification, especially since the error persists even for `x` inputs where `sin(x)` shouldn't even get evaluated). Consider wrapping the example in my previous comment with `sym.re`:
```
from sympy import sin,re,pi,Abs,Piecewise,lambdify
from sympy.abc import x
from sympy.plotting.experimental_lambdify import lambdify as expt_lambdify
f1 = re(sin(x)) # only change compared to my previous comment!
f2 = Abs(x)
f3 = x**2
f = Piecewise((f1, x < -pi), (f2, x < 1.0), (f3, True))
g = expt_lambdify([x], f)

print(g(0)) # works
print(g(0)) # also works; unlike without re()
```

Which also gives us a workaround for the original plotting problem:
```
from sympy import *
from sympy.abc import x
# f1 = sin(x) # bug
f1 = re(sin(x)) # no bug
f2 = Abs(x)
f3 = x**2
f = Piecewise((f1, x < -pi),(f2, x < 1.0), (f3, True))
plot(f)
```
![foo_sympy_plotbug](https://user-images.githubusercontent.com/17914410/50617366-23aba400-0eed-11e9-89fb-2264af601f76.png)

**Comment by jmig5776** [comment]
I would like to fix this issue.

**Comment by smichr** [comment]
In this function,
```
def experimental_lambdify(*args, **kwargs):
    l = Lambdifier(*args, **kwargs)
    return l
```
perhaps you can use some kwargs cleaning: if `use_python_math` is true then set `complex_wrap_evalf` to False and change the `__call__` signature to `__call__(self, args, kwargs={})` and only do the complex wrapping `if kwargs.get('complex_wrap_evalf', None) is not None:`.

**Comment by jmig5776** [comment]
@smichr Okk I got it I will do it as you suggested.

**Comment by jmig5776** [comment]
@smichr  It worked as you suggested . Please review it.
