### ISSUE TITLE
evalf hangs with expression involving CRootOf

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#15743]
The following expression arises from `test_nth_linear_constant_coeff_homogeneous_rootof_sol` and seems to cause `evalf()` to hang (I haven't waited more than an hour):

```python
sol = -2*exp(CRootOf(x**5 + 11*x - 2, 0)) + exp(CRootOf(x**5 + 11*x - 2, 0))*CRootOf(x**5 + 11*x - 2, 0)**5 + 11*exp(CRootOf(x**5 + 11*x - 2, 0))*CRootOf(x**5 + 11*x - 2, 0) + 11*exp(CRootOf(x**5 + 11*x - 2, 3))*CRootOf(x**5 + 11*x - 2, 3) + exp(CRootOf(x**5 + 11*x - 2, 4))*CRootOf(x**5 + 11*x - 2, 4)**5 - 2*exp(CRootOf(x**5 + 11*x - 2, 4)) + exp(CRootOf(x**5 + 11*x - 2, 1))*CRootOf(x**5 + 11*x - 2, 1)**5 + 11*exp(CRootOf(x**5 + 11*x - 2, 2))*CRootOf(x**5 + 11*x - 2, 2) - 2*exp(CRootOf(x**5 + 11*x - 2, 2)) - 2*exp(CRootOf(x**5 + 11*x - 2, 1)) + 11*exp(CRootOf(x**5 + 11*x - 2, 1))*CRootOf(x**5 + 11*x - 2, 1) + exp(CRootOf(x**5 + 11*x - 2, 2))*CRootOf(x**5 + 11*x - 2, 2)**5 - 2*exp(CRootOf(x**5 + 11*x - 2, 3)) + exp(CRootOf(x**5 + 11*x - 2, 3))*CRootOf(x**5 + 11*x - 2, 3)**5 + 11*exp(CRootOf(x**5 + 11*x - 2, 4))*CRootOf(x**5 + 11*x - 2, 4)

sol.evalf()
```

The expression pretty-printed is:
```julia
In [17]: pprint(sol)                                                                                                                                          
            ⎛ 5              ⎞           ⎛ 5              ⎞                          5              ⎛ 5              ⎞                                      
     CRootOf⎝x  + 11⋅x - 2, 0⎠    CRootOf⎝x  + 11⋅x - 2, 0⎠        ⎛ 5              ⎞        CRootOf⎝x  + 11⋅x - 2, 0⎠        ⎛ 5              ⎞       CRoot
- 2⋅ℯ                          + ℯ                         ⋅CRootOf⎝x  + 11⋅x - 2, 0⎠  + 11⋅ℯ                         ⋅CRootOf⎝x  + 11⋅x - 2, 0⎠ + 11⋅ℯ     

  ⎛ 5              ⎞                                     ⎛ 5              ⎞                          5             ⎛ 5              ⎞           ⎛ 5         
Of⎝x  + 11⋅x - 2, 3⎠        ⎛ 5              ⎞    CRootOf⎝x  + 11⋅x - 2, 4⎠        ⎛ 5              ⎞       CRootOf⎝x  + 11⋅x - 2, 4⎠    CRootOf⎝x  + 11⋅x -
                    ⋅CRootOf⎝x  + 11⋅x - 2, 3⎠ + ℯ                         ⋅CRootOf⎝x  + 11⋅x - 2, 4⎠  - 2⋅ℯ                          + ℯ                   

     ⎞                          5              ⎛ 5              ⎞                                       ⎛ 5              ⎞             ⎛ 5              ⎞   
 2, 1⎠        ⎛ 5              ⎞        CRootOf⎝x  + 11⋅x - 2, 2⎠        ⎛ 5              ⎞      CRootOf⎝x  + 11⋅x - 2, 2⎠      CRootOf⎝x  + 11⋅x - 2, 1⎠   
      ⋅CRootOf⎝x  + 11⋅x - 2, 1⎠  + 11⋅ℯ                         ⋅CRootOf⎝x  + 11⋅x - 2, 2⎠ - 2⋅ℯ                          - 2⋅ℯ                          + 

           ⎛ 5              ⎞                                     ⎛ 5              ⎞                          5             ⎛ 5              ⎞           ⎛ 5
    CRootOf⎝x  + 11⋅x - 2, 1⎠        ⎛ 5              ⎞    CRootOf⎝x  + 11⋅x - 2, 2⎠        ⎛ 5              ⎞       CRootOf⎝x  + 11⋅x - 2, 3⎠    CRootOf⎝x 
11⋅ℯ                         ⋅CRootOf⎝x  + 11⋅x - 2, 1⎠ + ℯ                         ⋅CRootOf⎝x  + 11⋅x - 2, 2⎠  - 2⋅ℯ                          + ℯ          

              ⎞                          5              ⎛ 5              ⎞                          
 + 11⋅x - 2, 3⎠        ⎛ 5              ⎞        CRootOf⎝x  + 11⋅x - 2, 4⎠        ⎛ 5              ⎞
               ⋅CRootOf⎝x  + 11⋅x - 2, 3⎠  + 11⋅ℯ                         ⋅CRootOf⎝x  + 11⋅x - 2, 4⎠
```

I have tried to simplify this expression for this issue but if I remove any single term then the problem no  longer occurs (`evalf` returns immediately).

**Comment by asmeurer** [comment]
The individual parts evalf fast. I guess it has to compute a lot of digits to avoid cancellation, which gets slow in the root isolation algorithm. 

For me it takes about three and a half minutes and returns `-0.e-125 + 0.e-123*I`, meaning it never gets enough digits to avoid cancellation. Is the solution supposed to be 0?

**Comment by oscarbenjamin** [comment]
I think it should be zero. It's coming from `checkodesol` here: [https://github.com/sympy/sympy/blob/sympy-1.3/sympy/solvers/tests/test_ode.py#L1743](https://github.com/sympy/sympy/blob/sympy-1.3/sympy/solvers/tests/test_ode.py#L1743)

**Comment by oscarbenjamin** [comment]
Yeah, it should be zero.

If you do:
```python
for n in range(5):
    sol = collect(sol, exp(CRootOf(x**5 + 11*x - 2, n))) 
```

Then you it factorises into zero polynomials. I can't seem tp print the resulting `sol` (it seems to hang) but looking at `.args` you can see the factors:
```julia
In [119]: sol.args[0]                                                                                                                                         
Out[119]: 
⎛                              5                               ⎞         ⎛ 5              ⎞
⎜            ⎛ 5              ⎞              ⎛ 5              ⎞⎟  CRootOf⎝x  + 11⋅x - 2, 0⎠
⎝-2 + CRootOf⎝x  + 11⋅x - 2, 0⎠  + 11⋅CRootOf⎝x  + 11⋅x - 2, 0⎠⎠⋅ℯ                         

In [120]: sol.args[1]                                                                                                                                         
Out[120]: 
⎛                                                             5⎞         ⎛ 5              ⎞
⎜               ⎛ 5              ⎞          ⎛ 5              ⎞ ⎟  CRootOf⎝x  + 11⋅x - 2, 1⎠
⎝-2 + 11⋅CRootOf⎝x  + 11⋅x - 2, 1⎠ + CRootOf⎝x  + 11⋅x - 2, 1⎠ ⎠⋅ℯ                         

In [121]: sol.args[2]                                                                                                                                         
Out[121]: 
⎛                              5                               ⎞         ⎛ 5              ⎞
⎜            ⎛ 5              ⎞              ⎛ 5              ⎞⎟  CRootOf⎝x  + 11⋅x - 2, 2⎠
⎝-2 + CRootOf⎝x  + 11⋅x - 2, 2⎠  + 11⋅CRootOf⎝x  + 11⋅x - 2, 2⎠⎠⋅ℯ                         

In [122]: sol.args[3]                                                                                                                                         
Out[122]: 
⎛                                                             5⎞         ⎛ 5              ⎞
⎜               ⎛ 5              ⎞          ⎛ 5              ⎞ ⎟  CRootOf⎝x  + 11⋅x - 2, 3⎠
⎝-2 + 11⋅CRootOf⎝x  + 11⋅x - 2, 3⎠ + CRootOf⎝x  + 11⋅x - 2, 3⎠ ⎠⋅ℯ                         

In [123]: sol.args[4]                                                                                                                                         
Out[123]: 
⎛                              5                               ⎞         ⎛ 5              ⎞
⎜            ⎛ 5              ⎞              ⎛ 5              ⎞⎟  CRootOf⎝x  + 11⋅x - 2, 4⎠
⎝-2 + CRootOf⎝x  + 11⋅x - 2, 4⎠  + 11⋅CRootOf⎝x  + 11⋅x - 2, 4⎠⎠⋅ℯ  
```
Each of those polynomial expressions should be zero.

**Comment by asmeurer** [comment]
I'm not sure if anything can be done here. If you have an expression that is identically 0 then evalf will just give you an indeterminate result because things never exactly cancel out numerically. The same thing happens with `(sin(1)**2 + cos(1)**2 - 1).evalf()`. It would be nice if CRootOf evalfed faster I guess. I don't know why it takes over an hour on your machine. That should be looked into. Do you have gmpy installed? 

It would also help if `simplify` worked on `CRootOf` instances. I think it should just replace any CRootOf power greater than or equal to its order, for instance, replace `CRootOf(x**5 + 11*x - 2, 0)**5` with `-11*CRootOf(x**5 + 11*x - 2, 0) + 2`.

**Comment by oscarbenjamin** [comment]
You're right I didn't have gmpy installed. I do now and it now runs a lot faster.

Also yes reducing the `CRootOf` powers like that would simplify everything to zero. I'll open a separate issue for that.

I'll close this issue since it doesn't hang with gmpy.

**Comment by oscarbenjamin** [comment]
Okay so I've just rerun the exact code shown above. It takes 1m30s with gmpy and 3m30s without. That seems like a fairly reasonable difference to me.

What is slow is calling checkodesol in the test:
```console
$ pytest sympy/solvers/tests/test_ode.py -k test_nth_linear_constant_coeff_homogeneous_rootof_sol
```

I have waited a long time for that to finish. I thought I diagnosed it to the evalf call in this issue but it turns out not to be the case. Presumably the 3 minutes on evalf are part of the problem but it takes a lot longer than that to run that test.

On the other hand even 1m30s seems fairly slow for `CRootOF.evalf`. I imagine that can be improved.

**Comment by asmeurer** [comment]
I think the root isolation is already being cached but if it isn't we should add that.

**Comment by asmeurer** [comment]
It definitely is being cached. 

```
In [1]: %time CRootOf(x**5 + 11*x - 2, 4).evalf(100)
CPU times: user 25.8 s, sys: 128 ms, total: 25.9 s
Wall time: 25.9 s
Out[1]:
1.240323707262242694589179539474872177930410965628403627754950900016980167898052533044322666016173403 + 1.29006698622137515259594775469302115560816916514684
2512524983867968818436613114855981832720603593408⋅ⅈ

In [2]: %time CRootOf(x**5 + 11*x - 2, 4).evalf(100)
CPU times: user 5.59 ms, sys: 538 µs, total: 6.13 ms
Wall time: 40.1 ms
Out[2]:
1.240323707262242694589179539474872177930410965628403627754950900016980167898052533044322666016173403 + 1.29006698622137515259594775469302115560816916514684
2512524983867968818436613114855981832720603593408⋅ⅈ

In [3]: %time CRootOf(x**5 + 11*x - 2, 4).evalf(101)
CPU times: user 371 ms, sys: 7.4 ms, total: 379 ms
Wall time: 1.19 s
Out[3]:
1.2403237072622426945891795394748721779304109656284036277549509000169801678980525330443226660161734028 + 1.2900669862213751525959477546930211556081691651468
425125249838679688184366131148559818327206035934079⋅ⅈ
```

**Comment by skieffer** [comment]
I think I've run into the same issue: Certain sums that equal zero take inordinately long to evalf.
It's not uniform. Some zero sums are slow, some are fast.

Here's a slow example:

```python
>>> import timeit
>>> from sympy import evalf, CRootOf, exp, I, pi, sqrt
>>> from sympy.abc import x
>>> a = CRootOf(x ** 4 + x ** 3 + x ** 2 + x + 1, 2)
>>> b = - 1 - exp(2 * I * pi / 5) - exp(4 * I * pi / 5) - exp(6 * I * pi / 5)
>>> timeit.timeit('(a - b).evalf()', number=1, globals=globals())
9.846753357000011
```

And a fast one:

```python
>>> c = CRootOf(x**2 - 2, 1)
>>> d = sqrt(2)
>>> timeit.timeit('(c - d).evalf()', number=1, globals=globals())
0.02329111999995348
```

Also, summing to zero _does_ seem to be critical. If I take the slow example and add 1 to the number, it becomes much faster:

```python
>>> timeit.timeit('(a - b + 1).evalf()', number=1, globals=globals())
0.5161114239999982
```

(Note: I did restart to clear the cache first, so it really is faster.)


It seems to me that the issue may be in [`sympy.core.evalf.add_terms()`](https://github.com/sympy/sympy/blob/52f606a503cea5e9588de14150ccb9f7f9ed4752/sympy/core/evalf.py#L501).


## Review

When we want to evalf a sum, we're going to wind up in [`sympy.core.evalf.evalf_add()`](https://github.com/sympy/sympy/blob/52f606a503cea5e9588de14150ccb9f7f9ed4752/sympy/core/evalf.py#L587).

What does this do?

1. Evalf each term individually, at the current precision level.
2. Sum these approximations, _and estimate the accuracy of the sum as a function of the accuracies of the individual terms_.
3. If not yet judged to be accurate enough, increase precision and repeat.

It is the `sympy.core.evalf.add_terms()` function that is called in order to evaluate the accuracy of the sum,
and I believe that in some cases it may be getting this wrong. This causes the loop in `evalf_add()` to repeat
many more times than necessary, resulting in the slow operation we have observed.


## `sympy.core.evalf.add_terms()`

Why does this function sometimes seem to report an erroneous accuracy measurement, on sums that add up to zero?

I can offer a partial answer.

This function attempts to compute the mantissa of the sum, a quantity which it calls `sum_man`.
For certain sums that add up to zero, `sum_man` becomes very small, and this causes the `add-terms()`
function to report a very low -- _sometimes even negative_ -- accuracy.

https://github.com/sympy/sympy/blob/95f0228c033d27731f8707cdbb5bb672e500847d/sympy/core/evalf.py#L580-L584

For instance, on the slow example above (the one that took 9.8 seconds), each of the incoming terms has mantissa with anywhere from 63 to 76 bits, and a comparable exponent (i.e. roughly -63 or -76). By the time we're done adding, `sum_man` has _8 bits_. And the reported accuracy is `-3`.

Just because a sum is totalling to a quantity near zero, that shouldn't mean it is any less accurate, should it?
If the number of bits in the mantissa is the measure of accuracy, then it shouldn't be getting small, the exponent
should just be getting largely negative, no? (Disclaimer: I don't have much experience with multi-precision arithmetic.)

**Comment by oscarbenjamin** [comment]
When I recently spoke to @fredrik-johansson about this he was of the opinion that evalf needs a complete rewrite. It should be based on rigorous ball/interval arithmetic rather than estimated significance arithmetic.
https://en.wikipedia.org/wiki/Interval_arithmetic
https://stackoverflow.com/questions/53123151/ball-arithmetic-vs-interval-arithmetic/53132255

In a case like this the RootOf algorithms can compute exact bounding intervals and it should be possible to combine polynomial functions of those bounding intervals exactly.

The problem here though is I think that the particular code for refining root intervals is just really slow. It shouldn't be expensive to refine an already isolated root of this polynomial in high precision. Here we can compute all the roots to 1000 digits much more quickly: 
```python
In [1]: %time r = nroots(x ** 4 + x ** 3 + x ** 2 + x + 1, 1000)
CPU times: user 76 ms, sys: 0 ns, total: 76 ms
Wall time: 76.2 ms
```
By contrast RootOf takes much longer just to get 100 digits:
```python
In [1]: %time r2 = CRootOf(x ** 4 + x ** 3 + x ** 2 + x + 1, 2).evalf(100)
CPU times: user 10.9 s, sys: 8 ms, total: 10.9 s
Wall time: 11 s
```
I can understand that RootOf needs an extra step to do the formal root isolation but that doesn't actually seem to be what's slowest here:
```python
In [1]: %time CRootOf(x ** 4 + x ** 3 + x ** 2 + x + 2, 2)._get_interval()
CPU times: user 156 ms, sys: 4 ms, total: 160 ms
Wall time: 159 ms
Out[1]: (1/4, 1/2) x (-5/4, -1)
```
Once we have an isolated root of a square-free polynomial it should be possible to refine quickly using either interval-Newton or even multiprecision Newton-Raphson and then just apply 1-step of interval-Newton at the end to prove a small bounding interval:
https://en.wikipedia.org/wiki/Interval_arithmetic#Interval_Newton_method

**Comment by oscarbenjamin** [comment]
I have example code here that uses interval arithmetic to find real roots:
https://github.com/sympy/sympy/issues/19164#issuecomment-671553474

It shouldn't be hard to put together something based on mpmath's interval support that can refine a bounded root.
https://mpmath.org/doc/1.0.0/contexts.html#arbitrary-precision-interval-arithmetic-iv
