### ISSUE TITLE
Is it a bug in trigonometric functions

### ISSUE THREAD

**Issue by sroopsai** [sympy/sympy#16007]
sin(2) or sin(any integer) is evaluating to sin(any integer)
For example:
![screenshot from 2019-02-17 06-06-13](https://user-images.githubusercontent.com/38998304/52906823-d86e0a80-327a-11e9-884a-d34f7c1ed300.png)
See at end math.sin(2.2) == expr.subs(x,2.2) evaluating to True. 
math.sin(2) == expr.subs(x,2) evaluating to False. I think this is because expr.subs(x,2) evaluating to a symbolic expression sin(2) but not completely to a numerical result. I think this should be fixed.

**Comment by oscarbenjamin** [comment]
The `math.sin` results just give a floating point number. Sympy does the same if you call SymPy's `sin` function with a float. That's why `expr.subs(x,2.2)==math.sin(2.2)` gives True (although I don't know that that's guaranteed because the functions might have different rounding errors).

The other case is `expr.subs(x,2)` which results in the symbolic SymPy expressions `sin(2)`. Since this is a symbolc expression rather than a float it will only be considered equal to another expression if they are *exactly* equal. However `math.sin(2)` is a floating point function so does not return an exact result meaning that they are not exactly equal.

**Comment by oscargus** [comment]
In addition,
```
In [11]: math.sin(2)==sin(2).evalf()
Out[11]: True
```
You can turn your symbolic `sin(2)` into a floating-point number through `evalf()`. For 2.2 this happens automatically since Sympy assumes that. However, doing `sin(Rational(11, 5))` or `sin(S(11)/5)` keeps it as a symbolic expression. (For `sin(11/5)`, Python evaluates 11/5 to 2.2 before submitting it to Sympy, in earlier versions to 2 as it then was an integer division.)

**Comment by ShubhamKJha** [comment]
Shouldn't the end result be the same for both the cases. ```sin(2)``` and ```sin(2.2)``` behaves differently but both can be part of a symbolic expression.

**Comment by oscargus** [comment]
Well, the current approach is that if the user starts using (Python) floats then things that can be evaluated are evaluated, rather than representing the float symbolically.

**Comment by oscargus** [comment]
One can always use `sin(2.2, evaluate=False)` if that is not wanted.

**Comment by ShubhamKJha** [comment]
Yeah, it is right. I am just suggesting that for an end user it would have been better if ```evaluate=False``` by default. 
```py
In [3]: ff = sin(2.2 + x)

In [4]: fu(ff, lambda k: -k.count_ops())
Out[4]: -0.588501117255346*sin(x) + 0.80849640381959*cos(x)
```
The user might have expected a pure symbolic result.

**Comment by sroopsai** [comment]
Yeah, end user should get either a pure symbolic result or a completely evaluated result.
End user obviously get evaluated result if the argument substituted with a float value, but does not get an evaluated value if argument substituted with an integral value.
![screenshot from 2019-02-17 22-19-01](https://user-images.githubusercontent.com/38998304/52916159-211cd680-3302-11e9-860a-25aeefa6a6c6.png)
@ShubhamKJha I think by default `evaluate=False` and because of this end user might expect an evaluated result but for integer argument you will get pure symbolic result even if `evaluate=True`
![screenshot from 2019-02-17 22-35-34](https://user-images.githubusercontent.com/38998304/52916351-5de9cd00-3304-11e9-8987-c82dfe185cde.png)

**Comment by oscargus** [comment]
Imagine how confusing it would be and how many questions there will be for `Add(x, -x, evaluate=False)` i.e., `x-x`... All expressions will explode without evaluate.

**Comment by oscargus** [comment]
You can try it out in a program by wrapping it with:
```
with evaluate(False):
```
Not sure if one can set it as default in the interactive shell.

**Comment by ShubhamKJha** [comment]
@oscargus  I get your point. But I didn't mean to stop evaluation of all the expressions. I just suggested to let ``sin`` or ```cos``` or any such function to be left unevaluated unless required. Leaving the symbolic form of ```sin``` or ```cos``` would be more representative. And it is from my perspective that I felt while working on SymPy.

**Comment by ShubhamKJha** [comment]
```
> with evaluate(False):
```
It doesn't work. Anyways I am not saying it's a necessity. It's just what might be expected by new users as a default.

**Comment by ShubhamKJha** [comment]
```
with evaluate(False):
```
It works @oscargus 
It's just what might be expected by new users as a default.

**Comment by oscarbenjamin** [comment]
The purpose of symbolic results is to be exact without e.g. rounding error. There's no way to achieve that once the user starts using floats. The number 2.2 already has a rounding error because Python converts it to a float with the exact value:
```julia
In [1]: from decimal import Decimal                                                                                                                           

In [2]: print(Decimal(2.2))                                                                                                                                   
2.20000000000000017763568394002504646778106689453125
```
That happens before the number reaches SymPy. In fact it happens immediately as the Python interpreter parses the characters `'2.2'` in your .py file before any Python code could possibly intervene.

If you use floats then your calculations can go wrong before SymPy gets a change to intervene:
```julia
In [4]: 0.1 + 0.01 - 0.1 - 0.01                                                                                                                               
Out[4]: -5.204170427930421e-18

In [5]: (0.1 + 0.01) - (0.1 + 0.01)                                                                                                                           
Out[5]: 0.0
```
This is unfortunate but it comes from the fact that SymPy tries to transparently embed itself within the Python programming language.

What this means is that in `sympy.sin(2.2)` you are giving SymPy an approximate input. That means that there is no point in pretending that it is an exact result and then for performance reasons SymPy may as well evaluate the sin and compute an approximation of that as well. If you are working with floats this gives a significant performance boost.

So the general advice is if you want exact symbolic calculations you shouldn't use float.

I suspect what most users want is something different though which is they would like to write 2.2 and have it become the *exact* number 2.2 as in 22/10. However there's nothing that SymPy can do about this. If SymPy were to try and guess that an input like `2.20000000000000017763568394002504646778106689453125` was really supposed to be 11/2 then it would also end up guessing incorrectly in other situations and creating more errors and confusion.

**Comment by ShubhamKJha** [comment]
@oscarbenjamin I know floating point rounding errors are really difficult to handle. Now I get your point and understand why it has been left this way. In such a case, nothing can be done in this regard. It would add more ambiguity. Thanks for pointing out.

**Comment by sroopsai** [comment]
K,I got your point @oscarbenjamin and now I can understand why it has been left this way.

**Comment by asmeurer** [comment]
Is there a valid issue here or should this be closed? 

Note that `==` does symbolic equality, not mathematical equality. `sin(2) == sin(2.0)` gives False because they are not equal structurally (the left-hand side is a `sin` object and the right-hand side is a `Float`).
