### ISSUE TITLE
Implementation of Strassen algorithm for multiplying large matrices

### ISSUE THREAD

**Issue by abhinav28071999** [sympy/sympy#16230]
I think there should be a method to multiply Two large matrices with strassen algorithm.

like
>>strassen(A*B)

strassen algorithm has complexity is O(n^2.807) which is less compared to naive algorithm(O(n^3)).
So a user can use strassen algorithm when he wants to multiply really large matrices.

**Comment by oscarbenjamin** [comment]
I think that the overheads mean that is only beneficial for very large matrices. Since SymPy uses symbolic calculations it is much slower than a numerical library anyway and probably can't use any algorithm to efficiently do such large dense matrices unless working with floats in which case you should just use numpy etc anyway.

I would be surprised if something like this was beneficial in SymPy.

**Comment by sidhantnagpal** [comment]
See the discussion at #15421.

**Comment by abhinav28071999** [comment]
Okay.
