### ISSUE TITLE
Naturals.is_subset(Reals) returns False

### ISSUE THREAD

**Issue by gmorenz** [sympy/sympy#16268]
This is possibly related to #9543 - but it seems likely that this is a simpler issue...

Sympy version 1.3 (installed via pip)

```
In [30]: sympy.Naturals.is_subset(sympy.Reals)
Out[30]: False
```

**Comment by ShubhamKJha** [comment]
This is happening because `oo` is not considered an integer.
But surely `Naturals` should be a subset of `Reals`.

**Comment by jksuom** [comment]
I think that `Naturals` is not a subset of `Reals` by design. Their objects have different properties.
```
>>> from sympy import Float
>>> Float(1).is_integer
False
```

**Comment by ShubhamKJha** [comment]
`oo` is considered a part of Extended Real numbers. But it seems the design of `Reals` is as Extended Reals.
Also `Float` object has some default precision hence it can't be an Integer anyways. One argument is that even in design all integers are real. So technically `Reals` is a superset of `Naturals`.
```from sympy import Integer
Integer(1).is_real
Out[21]: True
```

**Comment by gmorenz** [comment]
Surely `Float(1).is_integer` is not a demonstration that Naturals and Reals "have different properties" but that not every real is a natural (which is true) and that we for whatever reason don't consider integral floats to be integers, probably because they are an approximate type.

Note that if we use exact types sympy does the correct thing

```
In [20]: sympy.Naturals.contains(sympy.Rational(1, 1))
Out[20]: True
```

Also note that the meaning of subset is well defined as `forall x in subset, x in superset` and that relationship is obeyed.

> This is happening because `oo` is not considered an integer.

Possibly you are talking about some implementation detail I'm not aware of, but this doesn't make sense to me. An element not being in a set can never make a set not a subset of something.

**Comment by gmorenz** [comment]
> It seems the design of Reals is as Extended Reals.

Not sure what you mean by this

```
In [41]: sympy.Reals.contains(sympy.oo)
Out[41]: False
```

**Comment by asmeurer** [comment]
This looks like a wrong answer. The problem is that `x.is_subset(y)` checks if `x.intersect(y)` equals `x`. But it should be more conservative. In this case

```
>>> Naturals.intersect(Reals)
Range(1, oo, 1)
```

(side note, `pprint(Range(1, oo, 1))` gives `{1, 2, …, ∞}`, which implies that `oo` is included in the set, but that is not correct). 

is_subset shouldn't give True or False when it cannot determine exactly the answer. This would require making a symbolic Subset object (https://github.com/sympy/sympy/issues/14508).

Also, a third point, `Naturals.intersect(Reals)` should actually give Naturals, not Range(1, oo, 1). But the is_subset check should do the right thing regardless.

**Comment by asmeurer** [comment]
A fix for the Range printing is at https://github.com/sympy/sympy/pull/16270.
