### ISSUE TITLE
EmptySet and UniversalSet without S

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#16337]
I had thought we cleaned up all the S objects, but I guess not. 

Right now we have

```py
>>> from sympy import *
>>> EmptySet
<class 'sympy.sets.sets.EmptySet'>
>>> UniversalSet
UniversalSet()
```

There are two issues:

- `EmptySet` should be the instance, not the class.

- UniversalSet should not print with `()`.

**Comment by Naba7** [comment]
I am taking up the issue. Should I make a new instance that will be called from the class ``EmptySet`` ? or instead return ``EmptySet`` as the instance not the class?

**Comment by asmeurer** [comment]
Specifically `from sympy import EmptySet` should import the instance, not the class. Look at how it works for things like `UniversalSet` in `sympy/sets/__init__.py`.

**Comment by Naba7** [comment]
Ok,thank you

**Comment by Naba7** [comment]
``EmptySet`` has been registered on SymPy registry but not been installed. Since ``EmptySet`` is in _classes_to_install, in sympy/core/singleton.py _getattr_ module  `` class_to_install = self._classes_to_install[name]`` 
``value_to_install = class_to_install()``
value_to_install is EmptySet class . It has to be changed.

**Comment by Naba7** [comment]
EmptySet as well as UniversalSet has been registered on sympy register.But unlike UniversalSet, it hasn't been installed.It can be confirmed from __getattr__ module in sympy/core/singleton.py the code is

class_to_install = self._classes_to_install[name]
value_to_install = class_to_install()

 by list(S._classes_to_install) we will get
['BooleanTrue', 'BooleanFalse', 'EmptySet', 'EmptySequence']
These above classes haven't been installed although registered.

Since EmptySet hasn't been installed,during mapping of instances in Singleton class,__call__ is invoked at first 

def __call__(self, *args, **kwargs):
        # Called when application code says SomeClass(), where SomeClass is a
        # class of which Singleton is the metaclas.
        # __call__ is invoked first, before __new__() and __init__().
        if self not in Singleton._instances:
            Singleton._instances[self] = \
                super(Singleton, self).__call__(*args, **kwargs)
                # Invokes the standard constructor of SomeClass.
        return Singleton._instances[self]
which returns the class of EmptySet in sympy/sets/sets.py .

**Comment by asmeurer** [comment]
Apparently I added the `type` exception to the `test_singleton.py` `test_names_in_namespace`. But the only places where this happens are `EmptySet` and `EmptySequence`. I think we should fix both of those to be the instances, and remove the `type` check from that test.

**Comment by Naba7** [comment]
This is not a problem of S objects.
``from sympy import *
  print(S.EmptySet)``
gives output:
``EmptySet()``
``from sympy import *
   print(EmptySet)``
gives output
``<class 'sympy.sets.sets.EmptySet'>``
May be this is the problem because it has not been declared separately as ``UniversalSet`` in the ``__init__ module ``.
Because EmptySet is in all_classes and 
``from sympy.core.singleton import Singleton
print(Singleton._instances)

**Comment by asmeurer** [comment]
Yes, it needs to be added to the `__init__.py` file. `S` (`Singleton`) classes automatically have instances that are the same name as the class. However, the class name is not really needed, as it can always be accessed with `type(UniversalSet)` and so on.

**Comment by asmeurer** [comment]
We might even want to move the redefinition from `__init__py` to the files themselves. That way if someone does `from sympy.sets.sets import EmptySet` it will be the same as `from sympy import EmptySet`. And the same for ones in sympy/core.

**Comment by Naba7** [comment]
Ok sure . I am creating a pr for that

**Comment by oscargus** [comment]
Should UniversalSet print in any special way or just as "plain text"?

**Comment by asmeurer** [comment]
There's no universally used notation https://en.wikipedia.org/wiki/Universal_set#Notation.

**Comment by oscargus** [comment]
OK! Thanks! I'll sort out the printing. Soon.
