### ISSUE TITLE
Multiplying by 1.0 and -1.0 should match behavior of multiplying by 1 and -1

### ISSUE THREAD

**Issue by Strilanc** [sympy/sympy#16378]
If you multiply by 1 or -1, sympy performs a bit of simplification by ignoring the multiplication for 1 and changing to a negation for -1. But this doesn't work if they are floats instead of integers:

```python
x = sympy.Symbol('x')
print(x * 1)  # x
print(x * 1.0)  # 1.0*x
print(x * -1)  # -1
print(x * -1.0)  # -1.0*x
```

Note that `x * 1 == x * 1.0` and `x * -1 == x * -1.0` both evaluate to true, indicating that performing the substitution for floats should be acceptable.

**Comment by smichr** [comment]
I suspect `1==1.0` passes because they are the same to the given precision. It is true, however, that `Integer(1) is not Float(1)`. There are many routines that are careful not to draw a conclusion when the numbers involved are floats, e.g. `isprime(7.0)` is False. Here, knowing that the numbers is not exact precludes returning True.

**Comment by asmeurer** [comment]
This isn't a straightforward thing, and I'm not sure if it should be changed. See https://github.com/sympy/sympy/issues/11707 and the related discussions. Also https://github.com/sympy/sympy/issues/12942, where the same thing for `x**1.0` was removed (it was done in a hacky way). 

Most likely this won't be changed.
