### ISSUE TITLE
Python 'Subs' Issue Using Sympy

### ISSUE THREAD

**Issue by smarshall-spitzbart** [sympy/sympy#16466]
Hello, I am having trouble with subs and sympy (in python). Essentially, the function gives me no error message but lacks to substitute the value that is needed to be substituted. See below

![image](https://user-images.githubusercontent.com/44221603/55121836-a0e45080-50b9-11e9-8284-0b538efe89a6.png)

![image](https://user-images.githubusercontent.com/44221603/55121844-ae013f80-50b9-11e9-8612-c807a7abb3d0.png)

![image](https://user-images.githubusercontent.com/44221603/55121668-ca50ac80-50b8-11e9-9705-2f604ea2cfd0.png)

The function seems to selectively work when using solveset instead of solve. But it gives me an error when substituting my 'Qx1' function.

![image](https://user-images.githubusercontent.com/44221603/55121735-05eb7680-50b9-11e9-8f1f-0f563ed6d334.png)

The error says..
![image](https://user-images.githubusercontent.com/44221603/55121758-26b3cc00-50b9-11e9-9364-2934e63972e9.png)

Thank you for the help!

**Comment by oscarbenjamin** [comment]
It's difficult for me to investigate/help because:
1. You haven't provided all the code to reproduce whatever problem you are having and
2. You have only shown part of the traceback as an error message so I'm not sure which part is giving an error.

Can you provide complete code (including imports) to demonstrate the problem and show the full error message you see?

**Comment by smarshall-spitzbart** [comment]
Hi Oscar. Attached is the .ipynb file with the error included. Thanks again!

[Problem 6.1.zip](https://github.com/sympy/sympy/files/3016489/Problem.6.1.zip)

**Comment by sylee957** [comment]
I may not be clear about your intention,
but I guess your formula had got wrong after rewriting

<img src=https://user-images.githubusercontent.com/34944973/55168741-bc815100-51b6-11e9-8470-b8a9e68bd4c9.png width=512px>

to

<img src=https://user-images.githubusercontent.com/34944973/55168802-da4eb600-51b6-11e9-8f4b-84845ed272da.png width=512px>

Because you were trying to replace a derivative with a whole `List` or `Finiteset`, which is returned by solvers.
The brackets does not mathematically mean an arbitrary parenthesis, but a full 'set' or python 'list', and it will no longer be a valid formula after such replacement happens

You would have to replace with an element from the list, or set like using `[]` or `args[]`

<img src=https://user-images.githubusercontent.com/34944973/55169261-ce172880-51b7-11e9-8155-3651ef86b55a.png width=512px>

**Comment by sylee957** [comment]
However, I'm not sure if `subs` is supposed to work like this.

If it allows any pattern matching, actually, it should allow any arbitrary transformation even if it is not mathematically valid,
and if it should only be allowing some mathematically valid replacement, it should not allow some replacements like the OP's arbitrary success case, though.

**Comment by smarshall-spitzbart** [comment]
Using '.arg[0]' how you mentioned worked perfectly, Thank you! I did not realize that I was inputting a list into the '.sub' function.
