### ISSUE TITLE
Integrating over function

### ISSUE THREAD

**Issue by vonHardenberg** [sympy/sympy#16471]
I have stumbled upon a little problem where, when I try to integrate with a function as variable, i get a value error:

```python
from sympy import *

p = symbols('p')	
				
r = symbols('r', real=True)

r = 5.0

b = symbols('b', cls=Function) # Laufvariable in bogenmaß

b = p*r

integrate(1, b)
```

results in 
ValueError: Invalid limits given ([5.0*p],)

additional remark : it works fine, when I omitt r

**Comment by oscarbenjamin** [comment]
The line `b=symbols...` doesn't do anything because the next line is `b=p*r` so actually the value of `b` is `5.0*p`. (Also the line `r=symbols...` does nothing for the same reason.)

The second argument to integrate should be either a variable to integrate (e.g. p) or a tuple with variable and limits e.g. `(p, 1, 2)`.
