### ISSUE TITLE
integrate: neglects user-defined assumptions.

### ISSUE THREAD

**Issue by rosaceous** [sympy/sympy#16480]
```python
import sympy as s

x, y = s.symbols('x y')
a, b = s.symbols('a b', positive=True)
m, p = s.symbols('m p', nonnegative=True, integer=True)
 
expr = s.sin(s.pi * m * x / a) * s.sin(s.pi * 2 * p * x / a)
s.simplify(s.integrate(expr, (x, 0, a)))
```

This integration gives incorrect results that violates the assumption of m and p.

```
0   for m = 0 ∨ p = 0
-a / 2 for m = -2 p 
a / 2 for m = 2 p
0 otherwise
```

**Comment by oscarbenjamin** [comment]
Are you only referring to the case with m=-2p or are the others incorrect?

**Comment by rosaceous** [comment]
I means the case with m = - 2p, as the condition m = 0 & p = 0 is the only possible combination that makes m = - 2p if the assumptions are taken into consideration, and this condition also satisfy m = 0 v p = 0, it leads to the conflict that -a / 2 = 0.

**Comment by oscarbenjamin** [comment]
I'm not sure I understand the conflict. In SymPy a Piecewise should be read from top to bottom. The condition on the second row should be understood as applying only when the condition on the first row is found false.

Since the first row applies is either m or p is zero they should be understood as both nonzero in the other three cases.

**Comment by rosaceous** [comment]
Thanks, it seems I misunderstand the piecewise in SymPy.
