### ISSUE TITLE
Triangle.bisctor prohibitively memory inefficient for certain triangles

### ISSUE THREAD

**Issue by jpmaterial** [sympy/sympy#16595]
Depending on the coordinates, Triangle.bisector can take very long or even fail on an out-of-memory exception. Please see my example script below. The triangle is not colinear or unusual in any way that I noticed. In fact it uses three consecutive points from a regular hexagon, so it should be symmetrical with the wanted bisector as symmetry axis. Changing the order of vertices does not change anything. Calculating the altitude is no problem, so I'll use that as a temporary work-around.

<pre>
#!Python -u

import sys, os, time, math

sys.stderr.write(str(os.getpid())+time.strftime(': starting @ %d%b%y, %H:%M\n'))
	
from sympy.geometry import Point, Point2D, Triangle
from sympy import Rational

# not working - memory runs out before solution
# p0=Point2D(4.884400 ,  0.000000) 
# p1=Point2D(2.442200 , -4.230000)
# p2=Point2D(-2.442200, -4.230100)

# also not working - print-out of Triangle is identical to above
p0=Point2D(Rational(48844,10000) ,  Rational(0,1)) 
p1=Point2D(Rational(24422,10000) ,  Rational(-423,100))
p2=Point2D(Rational(-24422,10000),  Rational(-42301,10000))

# taking very long
# p0=Point2D(5 ,  0.000000) 
# p1=Point2D(2.5 , -4.25)
# p2=Point2D(-2.5, -4.25)

# working
# p0=Point2D(5 ,  0.000000) 
# p1=Point2D(2.5 , -4)
# p2=Point2D(-2.5, -4)

# working
# p0=Point2D(0,1) 
# p1=Point2D(1,1)
# p2=Point2D(1,0)

tri=Triangle( p0,p1,p2)
sys.stderr.write('Triangle: '+str(tri)+'\n')
alt=tri.altitudes[p1]
sys.stderr.write('Altitude: '+str(alt)+'\n')
bis=tri.bisectors()[p1]

sys.stderr.write('Bi-sector: '+str(bis)+'\n')

sys.stderr.write(str(os.getpid())+time.strftime(': done @ %d%b%y, %H:%M\n'))
</pre>

**Comment by smichr** [comment]
Please check to see that you are using th emost up-to-date SymPy. These compute for me in less than a minute. Note, too, that your points are not exactly those from a hexagon or else two of the sides would have the same length:
```python
>>> p0=Point2D(Rational(48844,10000) ,  Rational(0,1))
>>> p1=Point2D(Rational(24422,10000) ,  Rational(-423,100))
>>> p2=Point2D(Rational(-24422,10000),  Rational(-42301,10000))
>>> t=Triangle(p0,p1,p2)
>>> [i.length for i in t.sides]
[sqrt(596431021)/5000, sqrt(2385736337)/10000, sqrt(7157281357)/10000]
```
`p2.y` would be `Rational(-423, 100)` if the points were from a hexagon. (But even if the point had that value, the result would still take about the same amount of time.)

The bulk of the time is taken in doing a containment check of the intersection. triangle just uses the general `intersection` method which tries to be robust in its results. But when calculating bisectors, every bisector must pass through the opposite side so the containment check would not be needed. The containment check will not be done when an intersection between *lines* is done so the solution in this case is simple: work with lines containing the sides of the triangle when computing the intersections rather than the sides themselves:
```diff
diff --git a/sympy/geometry/polygon.py b/sympy/geometry/polygon.py
index 7643860..6186f91 100644
--- a/sympy/geometry/polygon.py
+++ b/sympy/geometry/polygon.py
@@ -2199,7 +2199,7 @@ def bisectors(self):
         True

         """
-        s = self.sides
+        s = [Line(_) for _ in self.sides]
         v = self.vertices
         c = self.incenter
         l1 = Segment(v[0], Line(v[0], c).intersection(s[1])[0])

CHRIS-LT+chriss@chris-lt MINGW32 ~/sympy (16589)
$ git diff
diff --git a/sympy/geometry/polygon.py b/sympy/geometry/polygon.py
index 7643860..9b9e89f 100644
--- a/sympy/geometry/polygon.py
+++ b/sympy/geometry/polygon.py
@@ -2199,7 +2199,9 @@ def bisectors(self):
         True

         """
-        s = self.sides
+        # use lines containing sides so containment check during
+        # intersection calculation can be avoided
+        s = [Line(_) for _ in self.sides]
         v = self.vertices
         c = self.incenter
         l1 = Segment(v[0], Line(v[0], c).intersection(s[1])[0])
```

No test other than seeing that no test fails is needed for this change, IMO, since it is simply an optimization.

**Comment by Sc0rpi0n101** [comment]
Just a curious question: 
if you have given the solution and no more tests are needed. What is the purpose of the issue and what is the wait for?

Are you waiting on someone to submit a PR?

**Comment by smichr** [comment]
> waiting on someone else to submit a PR with the change?

yes -- that's why I marked it as an easy  problem to fix. It provides a gentle introduction to git and and the workflow.

**Comment by Sc0rpi0n101** [comment]
ok cool.
I was looking if I could make some tests for it. But that won't change much as it is already tested in provided tests.
Since I already have the changes, can I get that PR?

**Comment by Sc0rpi0n101** [comment]
I have made the PR.
Also added a few tests, but they will not have much effect on the function as all of it can be covered under any one test. but I wanted to test all the triangles declared in the test module.

**Comment by jpmaterial** [comment]
I just pulled git cloned the sympy repository, the problem persists. I'm on CPython 3.7.3 under Windows.
