### ISSUE TITLE
Solving an Underdetermined System

### ISSUE THREAD

**Issue by kholdeman** [sympy/sympy#16590]
The sympy solve routine is one of the highlights of this Python symbolic library. It conveniently handles a wide class of problems.  Two examples are presented that solve handles correctly and one that solve struggles with.  However, the nullspace routine correctly finds a solution for a slightly different version of the problem.  It would be nice for sy.solve to automatically transform the problem and use the nullspace routine to find the solution, (or family of solutions).  A final example raises an issue of execution time to find the solution.

This is for sympy 1.3 and Python 3.7.1.  It is a restatement of the [sympy Issue Report #16245](https://github.com/sympy/sympy/issues/16245) problem.

For example the solve routine handles the following cases correctly:
```python
import numpy as np
import sympy as sy
from sympy.matrices.dense import Matrix
from sympy import symbols as syms
from sympy.abc import x,y,z

sy.solve([x+y], [x,y])
```
gives the answer:  {x: -y} and the following problem gives the answer: {x: 2*y}.
```python
sy.solve(Matrix([[-x+2*y],
                 [3*x-6*y]]), [x,y])
```
The following problem gives a trivial answer:  Solve= {x: nan, y: nan}
```python
M1 = Matrix([[1, 2],
            [3, 4]])
v = Matrix([[x],
            [y]])
λ = sy.Rational(1,2)*(5 - sy.sqrt(33))
M1a = M1 - λ*sy.eye(2)
Solve = sy.solve(M1a*v, [x,y])
print('Solve=', Solve)
```
However, interestingly, when the variables are removed from this problem statement, M1a*v vs M1a, the nullspace function finds the answer:
```python
Nullspace = M1a.nullspace()
print('Nullspace=', Nullspace)
print('Nullspace.evalf()=', Nullspace[0].evalf())
```
The answer reported is:
```
Nullspace= [Matrix([
[-2/(-3/2 + sqrt(33)/2)],
[                     1]])]
Nullspace.evalf()= Matrix([[-1.45742710775634], [1.00000000000000]])
```
So it would be nice if when sy.solve detected that it found a trivial answer for the sy.solve(M1a*v, [x,y]) problem, it would translate it into the M1a.nullspace() solution and return that answer.

For extra credit:  Solve takes an undetermined amount of time attempting to solve the following 3D problem using the current method.  In this case, I don't know how it can detect that the nullspace method is preferable.
```python
M2 = Matrix ([[15,-4,1],
              [-10,12,-6],
              [20, 4, -2]])
v = Matrix([[x],
            [y],
            [z]])
#
p3 = sy.Rational(1,3)
λ = 355/(9*(5*sy.sqrt(183909)/9 + sy.Rational(9280,27))**p3) + sy.Rational(25,3) + (5*sy.sqrt(183909)/9 + sy.Rational(9280,27))**p3
M2a = M2 - λ*sy.eye(3)
# Following solve statement runs an undefined length of time
# Solve = sy.solve(M2a*v, [x,y,z])
# print('Solve=', Solve)
Nullspace2 = M2a.nullspace()
print('Nullspace2=', Nullspace)
print('Nullspace2.evalf()=', Nullspace2[0].evalf())
```

**Comment by oscarbenjamin** [comment]
Thanks for the detailed and well-written issue report.

The fundamental problem as I see it is that solve does not have a well specified contract. It isn't clear which problems it should solve and which it should not.

If I was solving this problem on paper then I would write the solution in terms of an arbitrary constant, say alpha, as in
```
[-2/(-3/2 + sqrt(33)/2)*alpha,   alpha]
```
That's exactly the kind of solution that is returned by dsolve for ODEs without initial conditions. Currently solve doesn't do this in general but it does for a handful of undetermined systems giving the solution in terms of one of the unknowns instead.

There are also other issues for similar problems with overdetermined systems e.g.
```
In [70]: solve([x+y, x-y], [x])                                                                                                                
Out[70]: []
```
which has a unique solution x=0 if y=0 and no solution otherwise. On the other hand
```
In [71]: solve([x+y, y], [x])                                                                                                                  
Out[71]: {x: -y}
```
which also has a unique solution x=0 if y=0 and no solution otherwise Again there are some overdetermined systems for which solve gives a solution but mostly it does not.

It would be easy to fix each of these cases individually but the difficulty I have is that there isn't an agreed and documented statement of exactly what solve should ideally do. I think we need to define precisely when solve should or should not give a solution and what kind of a solution it should give. Then we can document that explicitly and fix the code to make it consistent one way or another.

**Comment by kholdeman** [comment]
I'm working on converting the Mathematica code used in an Introduction to Neural Networks course to Python.  I became fascinated with the code because it is much more concise than Python code I'd been writing since the professor is using high level routines that can significantly shorten code sequences.  The Mathematica Solve routine handled this undetermined system problem #16590 and others without breaking a sweat.  Thanks for your help via [Linear Algebra Solve Problem #16245](https://github.com/sympy/sympy/issues/16245)  in demonstrating how the problem can be solved in Python sympy.  Since this problem came up in solving the Eigenvector problem the long way, I now know two ways to solve it, but that doesn't eliminate the possibility that the problem won't come up in other contexts.  I was hoping I could make the professor's transition as painless as possible, but Mathematica is essentially equivalent to the sympy library merged with numpy.  I'm having trouble making that transparent in my conversion code.  I'm partway there, but since I've been programming since late '60s, at least the execution time costs bother me.  As I see it, the issue is: how much does the professor need to know Python to solve problems?  I'd vote for less, but I'm sure there's lots of changes that can be made to Python, we need to decide which are most important.  I don't have the experience to make that decision.  As far as I'm concerned with respect to my code conversion, I'm satisfied with the answer you provided and would be willing to close this issue if the alternative is to leave it open indefinitely.  Is there an issue classification that says: "Interesting idea, but too complicated a change for now?"

**Comment by oscarbenjamin** [comment]
The thing is that we need to make a decision: should solve handle underdetermined systems or should that be handled by other routines (e.g. solveset)?

At the moment solve does a hodge-podge of different things. I think that it should be tightened up so that what it actually does can be defined mathematically. That means either it does or does not solve underdetermined equations. If it does then we should try to make it solve all underdetermined equations wherever possible. Currently solve is nowhere near close to that.

The other option is to say that solve simply does not support underdetermined equations and then stick to that as a principle. The current support for such equations is so limited that I can't imagine many people are depending on it.

I asked you to open this as a separate issue in the hope that there could be some discussion of this but I guess no one else wants to talk about it :)

**Comment by sylee957** [comment]
I generally think that exact determined linear system solver, overdetermined but consistent solver, and underdetermined can co-exist in one solver routine. as it is.

Solving eigensystem may require a special routine, and I'm not sure that it can co-exist in one solver, without conflict with underdetermined solver
Though I haven't studied further about this stuff to verify, yet.

There can be some solvers which may need a separate routine. I don't think that it would be `solveset`, but something like `solve_eigen` or `solve_least_squares`, if such solvers may not co-exist in one routine.

**Comment by oscarbenjamin** [comment]
> I generally think that exact determined linear system solver, overdetermined but consistent solver, and underdetermined can co-exist in one solver routine. as it is.

I agree but:
1. If the intention is to try and solve underdetermined systems a lot of work is needed and I think it should return solutions with arbitrary constants in.
2. For over-determined systems also a lot of work is needed and we need an API that can return the conditions inherent in the solution.

Considering arbitrary constants look at:
```
In [10]: solve(x**2+y**2-1, [x, y])                                                                                                            
Out[10]: 
⎡⎛    ________   ⎞  ⎛   ________   ⎞⎤
⎢⎜   ╱      2    ⎟  ⎜  ╱      2    ⎟⎥
⎣⎝-╲╱  1 - y  , y⎠, ⎝╲╱  1 - y  , y⎠⎦
```
It would be better to return:
```
In [10]: solve(x**2+y**2-1, [x, y]) 
Out [10]: [(cos(C₁), sin(C₁))]
```

With arbitrary constants we could also do something like:
```
In [17]: solve(sin(x), x)                                                                                                                      
Out[17]: [π⋅n₁]
```

Overdetermined systems leads to the question what should we do if the solutions only exist depending on particular values of the constants. As a less obvious example:
```
In [22]: solve(a*x**2 + b*x + c, x)                                                                                                            
Out[22]: 
⎡        _____________   ⎛       _____________⎞ ⎤
⎢       ╱           2    ⎜      ╱           2 ⎟ ⎥
⎢-b + ╲╱  -4⋅a⋅c + b    -⎝b + ╲╱  -4⋅a⋅c + b  ⎠ ⎥
⎢─────────────────────, ────────────────────────⎥
⎣         2⋅a                     2⋅a           ⎦
```
However if a is zero these solutions are invalid. In general this equation can have 2, 1 or 0 solutions depending on which of a, b, c are zero. So how do we handle that? There is currently no way to return the solutions with conditions attached such as `a != 0`.

**Comment by oscarbenjamin** [comment]
The OP examples all seem to work fine. @kholdeman can you check if there is still an issue?

**Comment by kholdeman** [comment]
Took me awhile to remember what the issue were on this, but like you said, the examples in #16590 work satisfactorily.  I checked a few more cases from an old text book that agreed with all solution methods.  I did the testing on sympy 1.9.  Thanks for taking care of this.
