### ISSUE TITLE
Duplicate plots in beam_problems doc

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#16664]
From 
https://docs.sympy.org/dev/modules/physics/continuum_mechanics/beam_problems.html

I see this figure

![image](https://user-images.githubusercontent.com/34944973/56228911-b561aa80-60b3-11e9-8730-72012e6e4677.png)

duplicated in many places.

I see plot directives had been used in places where the actual plotting function is not used. If it had been a workaround to keep the context as same, is it now causing side effects?

Also, the weird thing about this issue is that, I could not reproduce this with my sphinx build (Tested on 1.8.5 and ~~ 2.0.1~~). 
But I see the figures had probably been added in the html file by the bot in  https://github.com/sympy/sympy_doc/commit/aa6d52f9b847426cd445d917cb9457c3f72ef415

**Comment by moorepants** [comment]
I wonder if there has been an update to matplotlib that is causing changes on the travis builds.

**Comment by moorepants** [comment]
Oh yeah, also sphinx has updated, so maybe a combination of matplotlib/sphinx versions?

**Comment by ishanaj** [comment]
I guess this might be because the `:context:`  is not set to `:context: close-figs`, in [`beam_problems.rst`](https://github.com/sympy/sympy/blob/master/doc/src/modules/physics/continuum_mechanics/beam_problems.rst), which would keep the context but close the previous figures before running the code. The way `:context` works can be seen [here](https://matplotlib.org/devel/plot_directive.html#options)
And since the `beam.rst` file runs first, the last plot in the `beam.rst`(which is the above mentioned plot 
[here](https://docs.sympy.org/dev/modules/physics/continuum_mechanics/beam.html#sympy.physics.continuum_mechanics.beam.Beam.plot_slope)) affects the `beam_problem.rst` file and creates this error.
 
I am not sure about it as even I can not reproduce this error with sphinx 1.8.5

**Comment by sylee957** [comment]
Okay, this can be reproduced by sphinx 2.0.0 and 2.0.1.

You would need to build the doc from the scratch, with `make clean`, because building from the existing doc can probably shadow this problem.

So, it looks like the examples in #16457 are keeping the variables afterwards, even with `close-figs`.
But I just wonder, why would they just keep showing the previous plot, even if there is no plotting command.

**Comment by sylee957** [comment]
I'm still not clear about the version combinations though.
But the original issue had also happened with
```
matplotlib                3.0.3                    py37_0    conda-forge
sphinx                    1.8.5                    py37_0    conda-forge
```
I'm going to check matplot versions for now

**Comment by moorepants** [comment]
Do you think this is a matplotlib issue? Maybe their extension broke with Sphinx 2.0.
