### ISSUE TITLE
issues with function replace and IndexedBase in sympy 1.4

### ISSUE THREAD

**Issue by XuemeiGu** [sympy/sympy#16725]
Recently I update sympy and then I run the same code which gives me errors. (I don't have such error before): 
```
import sympy as sp
a, b= sp.symbols('a b', cls=sp.IndexedBase)
l= sp.symbols('l', cls=sp.Wild)

def Bfunc(expr,p1,p2):
    if expr.base==p1:return expr.replace(p1[l],0.2*(p2[l]+p1[-l]),map=False, simultaneous=True, exact=True)
    else: return expr.replace(p2[l],0.2*(p1[l]+p2[-l]),map=False, simultaneous=True, exact=True) 
 
inputstate=a[0]*b[0]
psi0=inputstate.replace(lambda expr: expr.base in [a,b], lambda expr: Bfunc(expr,a,b))

```   
error:

![image](https://user-images.githubusercontent.com/37003667/56767046-21769980-67ab-11e9-9fc4-c582b72490a4.png)

my sympy version is 1.4. and then I reinstall the earlier version 1.3. 
I run the same code but gives me no error. I wonder what changes in the update sympy. 

here is also a link about the question:
https://stackoverflow.com/questions/55852716/how-to-get-all-bases-a-b-of-an-expression-such-as-a0b0#comment98374466_55856279

Thank you very much!

**Comment by smichr** [comment]
Not everything that `replace` encounters will be a Pow, so you have to either use something to get the base (`expr.as_base_exp()[0] in [a, b]`) or help it ignore such objects (`expr.is_Pow and expr.base in [a,b]`).

**Comment by XuemeiGu** [comment]
> Not everything that `replace` encounters will be a Pow, so you have to either use something to get the base (`expr.as_base_exp()[0] in [a, b]`) or help it ignore such objects (`expr.is_Pow and expr.base in [a,b]`).

If I use these in sympy 1.4,  (`expr.as_base_exp()[0] in [a, b]`) always gives you `False `and will not run the Bfunc.  In addition, when the `inputstate=a[0]*b[0]+a[1]*b[3]+a[1]**2*b[1]+...` (the inputs get complicated), it will give you similar error such as `AttributeError: 'Add' object has no attribute 'base'`

Hope I don't misunderstand what your comments. Thank you!

**Comment by smichr** [comment]
I left this note on the overflow page:

Your `foo` function returns None when it encounters an Attribute error and this signals to `replace` that nothing should be done at that node. When you use the lambda, there is nothing to catch the error so the process raises the error to your attention. One option would be to change `replace` so it ignores errors and just skips the node. The good thing about *not* doing that, however, is that it alerts you to the fact that you are doing something in a way that will miss objects you wanted to handle. So to use the lambda you have to help it succeed at identifying the terms of interest.
```python
    >>> L1 = lambda x: x.is_Pow and x.base in [a, b]
    >>> inputstate.replace(L1, lambda expr: Bfunc(expr,a,b))
    a[0]*b[0]
    >>> L2 = lambda x: x.as_base_exp()[0] in [a, b]
    >>> inputstate.replace(L1, lambda expr: Bfunc(expr,a,b))
    a[0]*b[0]
```
(I prefer L1 because it uses a quick `is_Pow` test to know whether one is dealing with a power or not. Your Bfunc assumes it is dealing with a power, so L2 will not work for all cases unless you also modify *it* to deal with the non-Pow case.)

One question to answer is whether you want to target actual powers or also "powers" with an exponent of 1. For example if you wanted to raise the exponents of all powers by 1 would you want `x*y**2 -> x**2*y**3` or just `x*y**3`? L1 would be good for the first case and L2 for the second.

**Comment by smichr** [comment]
I don't think anything is broken in SymPy from what you have shown but I will leave this open to see if there is more clarification of the problem.

**Comment by smichr** [comment]
There is also an error in the code given: `a` and `b` are IndexedBase so to see if `x = a[1]**2` has that base requires the test `x.base.base == a`; `x.base is a[1]` and `a[1] != a`. Also, use of `exact=True` rejects a match in which all the Wild symbols are 0. I believe this behavior is incorrect since the docstring says:

```python
problems, ``simultaneous`` can be set to False. In addition, if an
expression containing more than one Wild symbol is being used to match
                       ^--
subexpressions and  the ``exact`` flag is True, then the match will only
succeed if non-zero values are received for each Wild that appears in
the match pattern.
```

**Comment by smichr** [comment]
```diff
diff --git a/sympy/core/basic.py b/sympy/core/basic.py
index 208b1be..a72404b 100644
--- a/sympy/core/basic.py
+++ b/sympy/core/basic.py
@@ -1421,7 +1421,11 @@ def replace(self, query, value, map=False, simultaneous=True, exact=None):
                     "type or a callable")
         elif isinstance(query, Basic):
             _query = lambda expr: expr.match(query)
-            exact = len(query.atoms(Wild)) > 1 if exact is None else exact
+            nwild = len(query.atoms(Wild))
+            if exact and nwild == 1:
+                exact = False
+            elif exact is None and nwild > 1:
+                exact = True

             if isinstance(value, Basic):
                 if exact:
diff --git a/sympy/core/tests/test_expr.py b/sympy/core/tests/test_expr.py
index 6dbc4c2..9f19c9a 100644
--- a/sympy/core/tests/test_expr.py
+++ b/sympy/core/tests/test_expr.py
@@ -721,6 +721,9 @@ def test_replace():
     assert (n1*f(n2)).replace(f, lambda x: x) == n1*n2
     assert (n3*f(n2)).replace(f, lambda x: x) == n3*n2

+    # issue 16725
+    assert S(0).replace(Wild('x'), 1, exact=True) == 1
+

 def test_find():
     expr = (x + y + 2 + sin(3*x))
```
