### ISSUE TITLE
Transposing an expression of a matrix multiplied by a scalar raises AttributeError

### ISSUE THREAD

**Issue by khaledghobashy** [sympy/sympy#16807]
Transposing an expression consisting of matrices scaled by scalar quantities raises AttributeError.

Using SymPy 1.4 leads to this error.
```python
>>> import sympy as sm
>>> sm.__version__
1.4
>>> x = sm.symbols('x')
>>> c = sm.cos(x)
>>> M = sm.MatrixSymbol('M', 3, 3)
>>> N = sm.MatrixSymbol('N', 3, 3)
>>> expr = (N  +  (c * M) )
>>> expr.T
AttributeError: 'cos' object has no attribute 'shape'
>>> sm.transpose(expr)
AttributeError: 'cos' object has no attribute 'shape'
>>> sm.Transpose(expr)
(cos(x)*M + N).T
```

While SymPy 1.3 deals with it correctly.
```python
>>> import sympy as sm
>>> sm.__version__
1.3
>>> x = sm.symbols('x')
>>> c = sm.cos(x)
>>> M = sm.MatrixSymbol('M', 3, 3)
>>> N = sm.MatrixSymbol('N', 3, 3)
>>> expr = (N  +  (c * M) )
>>> expr.T
(cos(x)*M).T + N.T
>>> sm.transpose(expr)
(cos(x)*M).T + N.T
>>> sm.Transpose(expr)
(cos(x)*M + N).T
```
For SymPy 1.4, I have to set an assumption to the x = sm.symbols('x', real=True) in order to solve correctly, which leads to undesirable effects later on in my project when trying to pickle and unpickle objects that contains sympy expressions.

**Comment by sylee957** [comment]
It started not working after #16164, after it does not catch attributeerror.
But besides, I don't think there was a proper handler before.

It happens because transpose applied to scalar makes `is_Matrix==True`.

I'm not sure that transposition for scalar can return itself, because I didn't find the definition for transpose applied for a single scalar (and a scalar is not a 1*1 matrix)
https://en.wikipedia.org/wiki/Transpose
but transposition for scalar-matrix multiplication is defined.

I have worked on changes to fix the example 
```python
coeff, matrices = self.as_coeff_matrices()
return MatMul(coeff, *[transpose(arg) for arg in matrices]).doit()
```
but some problems remain like coefficients of one or identity matrix appearing.
I'm going to fix while working with the improvement of canonicalization for `MatMul`
