### ISSUE TITLE
Disparity in gamma function result for non-positive float numbers

### ISSUE THREAD

**Issue by ritesh99rakesh** [sympy/sympy#16847]
As nonpositive integers are poles for gamma function, we have the following:
```
>>> gamma(-1)
zoo
>>> gamma(0)
zoo
```
But for nonpositive integers represented as floats, we get the following error
```
>>> gamma(-1.0)
Traceback (most recent call last):
  File "/home/ritesh/Desktop/sympy/sympy/core/evalf.py", line 1308, in evalf
    rf = evalf_table[x.func]
KeyError: gamma

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ritesh/Desktop/sympy/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/ritesh/Desktop/sympy/sympy/core/function.py", line 463, in __new__
    result = result.evalf(mlib.libmpf.prec_to_dps(pr))
  File "/home/ritesh/Desktop/sympy/sympy/core/evalf.py", line 1442, in evalf
    result = evalf(self, prec + 4, options)
  File "/home/ritesh/Desktop/sympy/sympy/core/evalf.py", line 1314, in evalf
    xe = x._eval_evalf(prec)
  File "/home/ritesh/Desktop/sympy/sympy/core/function.py", line 586, in _eval_evalf
    v = func(*args)
  File "/home/ritesh/venv/lib/python3.6/site-packages/mpmath/ctx_mp_python.py", line 1012, in f
    return ctx.make_mpf(mpf_f(x._mpf_, prec, rounding))
  File "/home/ritesh/venv/lib/python3.6/site-packages/mpmath/libmp/gammazeta.py", line 1933, in mpf_gamma
    raise ValueError("gamma function pole")
ValueError: gamma function pole
```
I think there should be a check like `floor(x) == x` and then we can return `gamma(floor(x))`, this will help us to avoid the `ValueError` as:
```
>>> gamma(floor(-1.0))
zoo
```

**Comment by czgdp1807** [comment]
As said in [this document](http://mhtlab.uwaterloo.ca/courses/me755/web_chap1.pdf) and [this stackexchange thread](https://math.stackexchange.com/questions/705103/what-is-the-domain-of-gamma-function), I think we should not allow computations of gamma function for negative integers and zero.
The following should happen,
```
>>> gamma(-1)
Traceback(most recent call last):
    ...
ValueError: gamma function is not defined for non-positive integers. 
```

**Comment by ritesh99rakesh** [comment]
SymPy instead of giving the error as `gamma function is not defined for non-positive integers`, returns the result as `zoo` which is `S.ComplexInfinity` similar to [mathworld](http://mathworld.wolfram.com/ComplexInfinity.html). I believe we should return `zoo` instead of `ValueError` since a similar result is expected in other gamma function like `polygamma`.

**Comment by jksuom** [comment]
It would be easy to return `zoo` in `gamma.eval` for nonnegative integer arguments. However, Floats are currently not recognized as integers (apart from `Float(0)`). That will probably be changed when some current work in progress has been finished. Then also floating point integers could be covered by a condition like `arg.is_integer` (instead of `arg.is_Integer`). That would be preferable to `floor(arg) == arg`.

**Comment by czgdp1807** [comment]
@jksuom Please refer the PR which aims to cover floating point integers by attributes like, `is_integer`. We can refer this issue there for fixing. Moreover, I think using attributes would be better for recognising floating point integers instead of `floor(arg) == arg` as it is faster to access constant attributes than computing `floor(arg)` to the best of my knowledge of sympy till now. Please correct me in a reply if I am wrong in my argument.

**Comment by jksuom** [comment]
There is no such PR yet but the matter is related to what is done in #16770. It would be easy to update `Float.is_integer` independently. (You could send a PR.) A Float is an integer when the `exp` part (of index 2) of its `_mpf_` is nonnegative. That would be a very quick test.
