### ISSUE TITLE
is_EmptySet should be replaced by is_empty

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#16946]
There could be another property `is_empty` that could return `None` for `Interval(x, y)`. I think that `is_EmptySet` should be `True` only for `EmptySet` and `False` otherwise. (Then it would, in fact, be redundant as `is EmptySet` would have the same meaning.) So I suggest that `is_EmptySet` be replaced by `is_empty` everywhere.

_Originally posted by @jksuom in https://github.com/sympy/sympy/pull/11522#issuecomment-498056206_

**Update**: see this comment for a short discussion on when to use `is_empty`: https://github.com/sympy/sympy/issues/16946#issuecomment-524762143

**Comment by smichr** [comment]
`fuzzy_bool` should reduce all input to True, False or None. In order to successfully use an attribute you either have to use `getattr` or else confirm that you are dealing with a Set or Boolean before trying to use it.

What I would like to see is a decorator for functions that would guarantee that the output is `true, false or Basic` -- by Basic, for example, would mean an unevaluated expression like Contains --  or `true, false or None` or `True, False or None`.

**Comment by siefkenj** [comment]
@smichr Could you explain a little more? Are `true` and `false` sympy types?

**Comment by oscarbenjamin** [comment]
@smichr that seems very tangential :)

Maybe after 2.7 is dropped SymPy could start using static type checking:
http://mypy-lang.org/

For this issue though I think it's pretty much a find/replace: is_EmptySet shouldn't be a capitalised name.

**Comment by smichr** [comment]
> seems very tangential

sorry--I am in the thick of this with working on Rationals. My first hunch is that this is not necessary. Of what use would `is_empty` be? The user can see if something is an EmptySet and code that wants to know if a) something is the EmptySet can just see if `foo is S.EmptySet` (so +1 to replacing `foo.is_EmptySet` with the former) or b) whether something has evaluated or not (in which case `is_empty` being None for `Interval(x, y)` seems unnecessary in light of `fuzzy_bool(foo)` which already tells you if something evaluated to True/False or not.

@siefkenj , yes `true` is `S.true`. If a routine Boolean routine can return a SymPy type like `Contains(x, set)` then if it evaluates it should be returning `S.true` or `S.false`, too, not `True` or `False`.

**Comment by oscarbenjamin** [comment]
It doesn't look as if fuzzy_bool evaluates the emptiness of a set:
```
In [10]: print(fuzzy_bool(FiniteSet(1)))                                                                                          
None

In [11]: print(fuzzy_bool(S.EmptySet))                                                                                            
None
```

**Comment by smichr** [comment]
> It doesn't look as if fuzzy_bool evaluates the emptiness of a set:

Correct. It just tells if something is True/False or something else. In both cases you have "something else". So if you want to know if a set is empty you can use `s is S.EmptySet or None`, or have (suggested) `is_empty` routine that returns None for all but EmptySet. But when would you ever need that?

**Comment by jksuom** [comment]
> is_empty routine that returns None for all but EmptySet

Not for all sets. I think that is_empty could be implemented so that `Interval(1, 2).is_empty` is False. Similarly for many other sets. But if nothing is known of the arguments `x` and `y`, then `Interval(x, y)` should be None.

**Comment by oscarbenjamin** [comment]
I would imagine `is_empty` returning False for most sets, True for empty set and None for possibly empty sets such as `Intersection(FiniteSet(x), FiniteSet(1))`

**Comment by smichr** [comment]
> could be implemented so that `Interval(1, 2).is_empty` is False.

ahh...this is a little like Number.is_comparable

I would still like to see an example of when this would be used.

**Comment by oscarbenjamin** [comment]
I guess that in any situation where is_empty was True then ideally the set would have been simplified to the EmptySet singleton already so it would be needed for distinguishing False vs None.

Maybe in a situation like this:
```julia
In [6]: Z = FiniteSet(x) & FiniteSet(y)

In [7]: Z
Out[7]: {x} ∩ {y}

In [8]: imageset(z, 1, Z)
Out[8]: {1}
```
The last result should be something conceptually like:
```julia
In [9]: Piecewise(({1}, Eq(x, y)), (S.EmptySet, True))
Out[9]: 
⎧{1}  for x = y
⎨              
⎩ ∅   otherwise
```
The question that imageset would need to answer is whether Z is empty or not. Getting Z.is_empty->False would allow returning `{1}` whereas None should somehow lead to something like the Piecewise (or an unevaluated ImageSet).

**Comment by smichr** [comment]
So this is like the assumption system needing to know if something is 0 or not. I get it, now.

**Comment by gschintgen** [comment]
I had this actually come up internally via solveset/imageset: `Intersection(FiniteSet(atan(2)/pi), Integers)`. It's an empty set that isn't `EmptySet`. So I also find it strange that in this case `is_EmptySet` returns `None`. IMO it should return `False` and there should be an attribute `is_empty` returning `None`. Or better yet, as proposed in the OP, replace/rename `is_EmptySet` by `is_empty`. So +1 from me.

Currently it's inconsistent with other attributes.

**Comment by gschintgen** [comment]
Since the PR #17491 introduces a deprecation message for `.is_EmptySet` pointing to this issue, here's a quick recap on how and when to use the new `is_empty`:
- If only known empty sets are of interest, a direct check `if someset is S.EmptySet` is efficient and correct.
(The only set for which `is_empty` returns `True` is `S.EmptySet`. Set expressions involving `S.EmptySet`, e.g. a `ProductSet`, already evaluate automatically whenever possible. Do note that some sets are empty, even though SymPy is unable to simplify them down to `S.EmptySet`.)
- In order to act on sets that are known to be non-empty, a check for `someset.is_empty == False` should be used.

`is_empty` has three return values:
- `True` for `S.EmptySet`.
- `False` for known non-empty sets.
- `None` if unknown or undecidable.
This is in accordance to other `is_lowercase` attributes used throughout SymPy and its assumption system.
