### ISSUE TITLE
Extend singularities() to work with non-rational functions

### ISSUE THREAD

**Issue by j-c-cook** [sympy/sympy#17018]
The sympy library allows a user to generate a set of discontinuities based on a function inside of a string. 
```
import sympy as sm
from sympy.parsing.sympy_parser import parse_expr


def obj_func(f, x):
    sm.init_printing()
    print(sm.singularities(f, x))


def main():
    x = sm.symbols('x')
    f = 'y ** 2 / (2 - x)'
    a = parse_expr(f)  # make the equation into a real one
    obj_func(a, x)


if __name__ == "__main__":
    main()
```
`output: {2}`
Therefore, for the equation f(x, y) = y ^ 2 / (x - 2), there is a discontinuity at _x = 2_. This is good, however, the library **needs** to be expanded. When the function f becomes more complex, the code breaks. The following are two examples of problems that need solved
An **nth root**  (https://en.wikipedia.org/wiki/Nth_root)
`f = 'y / (x - 2) ** 0.5'`
and **trig id** (https://en.wikipedia.org/wiki/List_of_trigonometric_identities)
`f = 'cos(x)'`
For both the error code is as follows
```
output:  "Algorithms finding singularities for non-rational"
         NotImplementedError: Algorithms finding singularities for non-rational 
             functions are not yet implemented.
```
In **conclusion**, the `sympy` library needs developed now to handle "non-rational" functions.

**Comment by asmeurer** [comment]
The parsing here is unrelated. 

I believe `singularities` currently hard fails on non-rational functions as a safeguard against returning wrong results. If you remove the check, you get answers. For the first case, you don't get the simplified answer unless you use `Rational(1, 2)` instead of `0.5` for the exponent. For cos(x), it gives the empty set. All it does is call solveset on `1/expr`. 

I'm not clear why the safeguard is there. solveset should already be taking care of returning all solutions. I guess it is to guard against non-standard singularities, like removable singularities or essential singularities. For instance, after removing the rational function check, `singularities(sin(1/x), x)` returns the wrong answer EmptySet. But surely we can extend the class of functions that are safe to check against from just rational functions.

**Comment by asmeurer** [comment]
Also things like log(x) don't work. I guess the problem is that `solveset` doesn't consider 0 to be a solution to `1/log(x)`, because it's only a solution in the limit. I don't know if that should be considered a bug or intended behavior. 

`singularities` should probably be modified to recursively break up an expression piece by piece, working on known functions, and failing for functions it doesn't know how to deal with. Functions like `log`, `tan`, etc. have singularities where their arguments. Anywhere there is a division the zeros of the denominator should be added as singularities. I seem to remember there are already some functions that do this sort of thing in the solvers module.

**Comment by j-c-cook** [comment]
Yes the expression needs to be recursively solved for. However if you consider the function `g(x) = f(x)**0.5`, where `f(x) = (2 + x)` solely solving for the inside of this function would be inaccurate because if the `lim x -> P f(x) is not equal to abs(f(P)) then the value is not real. In other words, the square root of a negative number is imaginary and needs to be returned, but simply solving for f(x) inside of g(x) will not exactly provide accurate answers. I am **working** on a pdf outlining reasons like these for `nth roots`, `trig functions` and will now extend to `**log**` `**ln**` and `**e**`.

**Comment by asmeurer** [comment]
The docstring states that it does not return branch points. That's likely a harder problem to solve. We should focus on the standard singularities for now.

**Comment by j-c-cook** [comment]
Currently, I believe

**Comment by j-c-cook** [comment]
I think it would be possible to have `g(x) checks`. Where `g(x) = sin(f(x))`, there is no value of x in range of real numbers which is discontinuity. However, if the function becomes `h(x) = 1 / g(x) = 1 / (sin(f(x))`, this is now `Cosecant`. Where `lim x % (pi /2) -> 0 h(x) = \infty`.

**Comment by asmeurer** [comment]
In that case the singularities of f(x) should be returned. That is what I mean by solving recursively.

**Comment by j-c-cook** [comment]
In the case above, considering `h(x) = 1 / g(x) = 1 / (sin(f(x))`,  I think it would be a nice addition to be able to return the singularities of `f(x)` and they must, however I would like to point to a graph of Cosecant. ![csc](https://user-images.githubusercontent.com/39248734/59389308-a73aae00-8d33-11e9-9b65-c4e54a5930eb.png)

**Comment by j-c-cook** [comment]
Attached is a rough draft of the math we will need to consider to expand singularities. After step 1, recursively solving for f(x), we will not necessarily want to push that to master. The attached paper gives preliminary insight to the reasoning. I will work on making this a more readable document for the time being. 
[SingularitiesAddOn(rough).pdf](https://github.com/sympy/sympy/files/3286948/SingularitiesAddOn.rough.pdf)
