### ISSUE TITLE
Behavior of perfect_power when candidates is given but has no valid exponents

### ISSUE THREAD

**Issue by ethankward** [sympy/sympy#17048]
See #17044.

```
>>> from sympy import *
>>> print(perfect_power(216000, [2]))
(60, 3)
```

This should either be documented or the behavior should be changed to return False.

**Comment by sylee957** [comment]
It looks like the behavior had changed in https://github.com/sympy/sympy/pull/8
Before, it had checked candidates strictly, but had given `None` instead of `False`

```python
>>> from sympy import *
>>> perfect_power(60**3, candidates=[2])
>>> perfect_power(60**2, candidates=[2])
(60, 2)
>>> perfect_power(60**3, candidates=[2])==None
True
```

It had been many years since the change was not discovered, but I would vote for this to be considered a bug rather than a loose feature, because it is confusing to consider such a loose feature that giving the candidate exceeding the `max_possible` makes result different.
 
```python
>>> from sympy import *
>>> perfect_power(60**3, [20])
False
>>> perfect_power(60**3, [19])
(60, 3)
```

And there can be some advantage to set `candidates` for restricting computational domains
