### ISSUE TITLE
Latex printing issue on derivatives with superscripted symbols

### ISSUE THREAD

**Issue by JSS95** [sympy/sympy#17092]
When I display the derivatives of second-or-more order with superscipted symbols, it gives wrong latex expression and fails to print correctly with IPython environment.

For example,

```python
x_star = Symbol('x^{*}')
Derivative(x_star, x_star,2)
```

this gives `\displaystyle \frac{d^{2}}{d x^{*}^{2}} x^{*}` instead of nice latex formula.

I figure that this is because  x^{*}^{2} is wrong latex expression. It should be x^{*2}, and thus I report it as an issue.

**Comment by oscargus** [comment]
I have a fix in progress. Do you really want `x^{*2}`? I think either `{x^{*}}^{2}` or `(x^{*})^{2}` makes more sense (and is easier to implement, to the extent that I can say that  `x^{*2}` will not happen, at least not now, since it requires something of a LaTeX parser...).

Btw, using {} inside symbol names disables some parsing, so it may be better to use `x^*` as a symbol name and the printer will automatically translate it to `x^{*}` when outputting LaTeX and something similar when outputting to other formats. Using {} will leave the curly brackets there in the other output formats as well. (This works even for multi-character superscripts, so `x_foo^bar` comes out as `x_{foo}^{bar}`.)

**Comment by JSS95** [comment]
Although I'd like to use `x^{*2}` in my current programming, I agree with that `(x^{*})^{2}` would be more appropriate for general case.

And thanks for the advice on using curly brackets! :)

**Comment by oscargus** [comment]
Sorry for taking that long. I missed your reply. There is a PR in #17288 now.
