### ISSUE TITLE
Nondeterministic exception from (atan(I/(I + I*tan(1)))).as_real_imag() (InconsistentAssumptions)

### ISSUE THREAD

**Issue by ethankward** [sympy/sympy#17142]
Sometimes this works:

```
>>> from sympy import *
>>> e = atan(I/(I + I*tan(1)))
>>> e.as_real_imag()
(atan(I/(I + I*tan(1))), 0)
```

Sometimes it gives this exception:

```
>>> e.as_real_imag()
Traceback (most recent call last):
  File "/home/e/se/sympy/core/assumptions.py", line 262, in getit
    return self._assumptions[fact]
KeyError: 'extended_real'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/e/se/sympy/core/assumptions.py", line 262, in getit
    return self._assumptions[fact]
KeyError: 'rational'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "testing.py", line 114, in <module>
    print(c, e.as_real_imag())
  File "/home/e/se/sympy/core/expr.py", line 1921, in as_real_imag
    return (re(self), im(self))
  File "/home/e/se/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/e/se/sympy/core/function.py", line 462, in __new__
    result = super(Function, cls).__new__(cls, *args, **options)
  File "/home/e/se/sympy/core/cache.py", line 94, in wrapper
    retval = cfunc(*args, **kwargs)
  File "/home/e/se/sympy/core/function.py", line 277, in __new__
    evaluated = cls.eval(*args)
  File "/home/e/se/sympy/functions/elementary/complexes.py", line 58, in eval
    elif arg.is_extended_real:
  File "/home/e/se/sympy/core/assumptions.py", line 266, in getit
    return _ask(fact, self)
  File "/home/e/se/sympy/core/assumptions.py", line 321, in _ask
    _ask(pk, obj)
  File "/home/e/se/sympy/core/assumptions.py", line 309, in _ask
    a = evaluate(obj)
  File "/home/e/se/sympy/functions/elementary/trigonometric.py", line 2269, in _eval_is_rational
    if s.args[0].is_rational:
  File "/home/e/se/sympy/core/assumptions.py", line 266, in getit
    return _ask(fact, self)
  File "/home/e/se/sympy/core/assumptions.py", line 321, in _ask
    _ask(pk, obj)
  File "/home/e/se/sympy/core/assumptions.py", line 321, in _ask
    _ask(pk, obj)
  File "/home/e/se/sympy/core/assumptions.py", line 311, in _ask
    assumptions.deduce_all_facts(((fact, a),))
  File "/home/e/se/sympy/core/facts.py", line 522, in deduce_all_facts
    if not self._tell(k, v) or v is None:
  File "/home/e/se/sympy/core/facts.py", line 493, in _tell
    raise InconsistentAssumptions(self, k, v)
sympy.core.facts.InconsistentAssumptions: {
	algebraic: False,
	commutative: True,
	complex: True,
	composite: False,
	even: False,
	extended_negative: None,
	extended_nonzero: True,
	extended_positive: None,
	extended_real: True,
	finite: True,
	hermitian: True,
	imaginary: False,
	infinite: False,
	integer: False,
	irrational: False,
	negative: None,
	nonzero: True,
	odd: False,
	positive: None,
	prime: False,
	rational: False,
	real: True,
	transcendental: True,
	zero: False}, irrational=True
```

Another example is `log(I + I*pi/2)`.

**Comment by bjodah** [comment]
Does it depend on python version (e.g. later python versions have deterministic dictionary key order) -- could be a clue.

**Comment by jksuom** [comment]
It may also depend on cache contents.

**Comment by ethankward** [comment]
I get the error on both 2.7 and 3.6.

**Comment by ethankward** [comment]
There have been multiple points where the issue has disappeared and reappeared (for `log(I + I*pi/2)`):

[](url)

[67b50bc54d45cdb12744a35707c7aaa1aeaf48c6](https://github.com/sympy/sympy/commit/67b50bc54d45cdb12744a35707c7aaa1aeaf48c6) good (January 21 2015)
[6363eb2322b9c5e23bd927c4dc74d37c62541fdf](https://github.com/sympy/sympy/commit/6363eb2322b9c5e23bd927c4dc74d37c62541fdf) bad
[a5c21c71c38471b3ee2b5e6225f633a750b772fa](https://github.com/sympy/sympy/commit/a5c21c71c38471b3ee2b5e6225f633a750b772fa) good

[553238a95e96f29596991a349e9f8746c33e9f7d](https://github.com/sympy/sympy/commit/553238a95e96f29596991a349e9f8746c33e9f7d) still good (March 23 2015)
[9a563b1fb08aca2668da1d1618b1e1244eafeb05](https://github.com/sympy/sympy/commit/9a563b1fb08aca2668da1d1618b1e1244eafeb05) bad

**Comment by sylee957** [comment]
I think I've found the two reasons why the assumption is nondeterministic,
one would be `shuffle` used in `assumptions.py` and the other would be the `FactRules.prereq` being unsorted.
I couldn't figure out more about why the assumptions is failing than this, though.

**Comment by ethankward** [comment]
Are you able to control it by setting any environment variables like the random seed?

**Comment by sylee957** [comment]
I may be wrong, but I somewhat find that the changes #12924 is making this to fail.
Probably there can be something wrong about the propositional, to make an inconsistency between each proofs.
I may figure out the way to use random seed, though.

**Comment by oscarbenjamin** [comment]
The non-determinism is due to the shuffle in `_ask`. I've fixed many problems like this when working on the assumptions. The following diff can help for debugging:
```
diff --git a/sympy/core/assumptions.py b/sympy/core/assumptions.py
index 8e82a24f3c..2fed192b78 100644
--- a/sympy/core/assumptions.py
+++ b/sympy/core/assumptions.py
@@ -308,6 +308,7 @@ def _ask(fact, obj):
     else:
         a = evaluate(obj)
         if a is not None:
+            print(obj, fact, a)
             assumptions.deduce_all_facts(((fact, a),))
             return a
```
Essentially what is happening is that the `_eval_is` methods are returning results that are inconsistent with the implication rules listed in sympy/core/assumptions.py. Since the methods are called in random order the particular one that is returning an incorrect result is not always called.

This issue seems to be to do with rational/transcendental/algebraic somehow.

**Comment by oscarbenjamin** [comment]
This is the problem:
```julia
In [3]: e = I/(I + I*tan(1))

In [4]: e._eval_is_irrational()
Out[4]: False

In [5]: e._eval_is_algebraic()
Out[5]: False
```
Since `tan(1)` is irrational `I/(I+I*tan(1)) == 1/(1+tan(1))` is also irrational so there is a bug in `Mul._eval_is_irrational`.

**Comment by oscarbenjamin** [comment]
The `_eval_is_irrational` method looks broken. Simply deleting the method works.

The assumptions system can infer irrational from real and not rational. I don't know whether deleting the method will increase or decrease performance - It could potentially slow down `m.is_irrational` but it also means that we don't call this method when checking other assumptions. For example `x.is_real` might (needlessly) try `_eval_is_irrational` which is probably a more common situation then asking for `x.is_irrational`. Grepping indicates that it isn't used much in SymPy: outside of the assumptions code and tests `is_irrational` is only used four times in polys and once in solvers.

**Comment by ethankward** [comment]
Even if you delete the `_eval_is_irrational` method it's easy to find examples of expressions that are computed as both not rational and not irrational: `(-2)**(S(3)/10)`, `log(Ei(-6))`, `asin(1 + pi)`.

**Comment by sachin-4099** [comment]
Does the error still persists? @oscarbenjamin @ethankward

**Comment by asmeurer** [comment]
The code for Mul._eval_is_irrational still looks wrong. is_irrational in the assumptions system means real and not rational: https://github.com/sympy/sympy/blob/f119ab5d30e8b373dc8956d41b7c11e53c140209/sympy/core/assumptions.py#L211

This is the code for `Mul._eval_is_irrational`: https://github.com/sympy/sympy/blob/f119ab5d30e8b373dc8956d41b7c11e53c140209/sympy/core/mul.py#L1367-L1378

It goes through the arguments and checks for any irrational arguments. If it finds one, it checks if the remainder of the arguments are rational. If they are it returns True and if not it returns None. I believe this logic is fine. What's wrong is if `a.is_irrational` is False for every argument in the Mul, it assumes is_irrational is False. But because irrationals must be real, this is wrong. For instance, `(sqrt(2)*I).is_irrational` and `I.is_irrational` are both False but `(sqrt(2)*I*I).is_irrational` is True. Of course this direct example doesn't cause issues because `I` cannot appear twice in a Mul, but the above example shows how it can, with `I` in the numerator and expanded in the denominator. tan(1) can be replaced with any irrational, for instance, `I/(I + I*sqrt(2))`, which is real irrational but `_eval_is_irrational()` gives False.

**Comment by oscarbenjamin** [comment]
We can just delete the method. It's not adding anything that isn't already handled by `_eval_is_rational`.
