### ISSUE TITLE
What is the correct value of atan2(0, complex)?

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#17155]
Not really an issue, but more a discussion/information point.

What should `atan2(0, x)` give assuming that x is a complex value?

For example, `atan2(0, 1+I) = -I*log((1 - I)*(1 + I)/2) = 0`, which corresponds to the value from Wolfram Alpha. However, `atan2(0, -1+I) = -I*log((-1 - I)*(-1 + I)/2) = 0`, but Wolfram Alpha gives pi. It is stated that for complex arguments, Wolfram Alpha (or Mathematica rather, but I assume they do the same) (and SymPy) returns 
`-I*log((x + I*y)/sqrt(x**2 + y**2))` (which should be 0 for all complex x when y = 0, not for purely imaginary x though, but that case is not considered here as it already works).

Despite that, it seems like Wolfram Alpha returns 0, re(x) >0, or pi, re(x) < 0 (undefined for x = 0).

Matlab requires the arguments to be real. 
cmath does not have atan2, only atan
mpmath does not seem to support complex arguments (mpc) for atan2 (or I am just bad at using it).

I have not really found anything useful despite spending quite some time to search for an answer.

This relates to #17141 (primarily the later comments) which I believe can be solved if it is possible to return something more specific for y = 0. Right now certain arguments causes recursion errors.

**Comment by jksuom** [comment]
For real `x` and `y`, `atan2(y, x)` is expected to be equal to `arg(x + I*y)`. Hence `atan2(0, x)` is 0 for `x > 0` and `pi` for `x < 0`. It can be extended to a complex analytic function of `x` in many ways but only piecewise. I think that the most obvious extension is `pi` for `re(x) < 0` and 0 otherwise.

**Comment by oscarbenjamin** [comment]
Reading that it seems the obvious extension is to define `atan2(y, x)=arg(x+I*y)` in which case `atan2(0, x)=arg(x)`. I wouldn't want to implement that in SymPy though if it isn't used anywhere else.

**Comment by jksuom** [comment]
We would probably want to have `atan2(y, x)` complex analytic, at least piecewise. (`arg(x)` is not analytic.)

**Comment by oscarbenjamin** [comment]
Does the other suggestion amount to defining `atan2(y, x) = arg(re(x)+I*re(y))`?

**Comment by jksuom** [comment]
That is not complex analytic, either (because `re` is not). I think that we should start from the established analytic expressions for real arguments: `atan(y/x)` for `x > 0`, `pi/2 - atan(x/y)` for `y > 0`, `-pi/2 - atan(x/y)` for `y < 0`, and use the standard analytic extension of `atan` to define `atan2(y, x)` for complex values of `x` and `y`. (There are branch cuts at purely imaginary `y/x`.)

**Comment by oscarbenjamin** [comment]
How do you write that as a Piecewise like the definitions here:
https://en.wikipedia.org/wiki/Atan2#Definition_and_computation

**Comment by oscargus** [comment]
Thanks @jksuom ! I'll give it a go.

@oscarbenjamin this case is not included there unfortunately as it only deals with real numbers.

**Comment by oscargus** [comment]
I gave the comment after reading @jksuom's first comment (earlier) and @oscarbenjamin's last one now. Then I realized that there was a discussion inbetween as well. I'll try the suggestion based on Piecewise and re and see what happens.
