### ISSUE TITLE
printingMathML erroneous

### ISSUE THREAD

**Issue by Karrenbelt** [sympy/sympy#17184]
I believe I found some mathML printing errors, and noted below what I think it should be

```
sympy.printing.mathml(sympy.acoth(x))
>>> '<apply><acoth/><ci>x</ci></apply>'
```
should be:  `'<apply><arccoth/><ci>x</ci></apply>'`

```
sympy.printing.mathml(sympy.acsc(x))
>>> '<apply><acsc/><ci>x</ci></apply>'
```
should be: `'<apply><arccsc/><ci>x</ci></apply>'`

```
sympy.printing.mathml(sympy.asec(x))
>>> '<apply><asec/><ci>x</ci></apply>'
```
should be: `'<apply><arcsec/><ci>x</ci></apply>'`

**Comment by Karrenbelt** [comment]
and a more serious issue regarding the introduction of underscores when writing to mathml

```
sympy.sympify('p1 ** p_local') == sympy.sympify('p_1 ** p_local')
>>> False
sympy.mathml(sympy.sympify('p1 ** p_local')) == sympy.mathml(sympy.sympify('p_1 ** p_local'))
>>> True
```

**Comment by asmeurer** [comment]
CC @oscargus

**Comment by oscargus** [comment]
There is a fix for the trigonometric/hyperbolic stuff in #17194 (together with some more functions once I was at it).

Regarding the "more serious issue", this holds for any SymPy printing method. A trailing number is by definition expected to be printed as a subscript. The same holds for the "LaTeX-inspired" underscore approach. You will find something similar for `x__2` and `x^2` (double underscore it superscript, same for ^). I can see that it may be confusing, but I am not sure if one would should really make the name comparison for Symbol more complicated (which I believe is the correct solution since one would like the printing behavior to stay the same).

**Comment by oscarbenjamin** [comment]
Is the symbol printing behaviour documented somewhere?

**Comment by oscargus** [comment]
This is probably it:

https://github.com/sympy/sympy/blob/fec5dc5fd0d9a04cf974f733bc375bd8db853d4c/sympy/printing/conventions.py#L14-L21

(but I think that there are some special cases in different printers as well...)

**Comment by oscargus** [comment]
But the trailing digit part is not there, I note:

```
In [49]: split_super_sub('x1')
Out[49]: ('x', [], ['1'])
```

**Comment by oscarbenjamin** [comment]
I wonder if this should be highlighted at a higher level like here:
https://docs.sympy.org/latest/tutorial/printing.html
and maybe near the top of
https://docs.sympy.org/latest/modules/printing.html

There are other things like:
```julia
In [1]: Symbol('alpha')                                                                                                           
Out[1]: α
```

As a user I just discovered these things by chance. That was a while ago though...
