### ISSUE TITLE
Do Not Index Previous Documentation Versions For Search Engines

### ISSUE THREAD

**Issue by mcrowson** [sympy/sympy#17293]
When searching Google/DDG for sympy help I often encounter old (sometimes very old) versions of the documentation in the search results. 

I suggest using robots.txt or some other approach so that search engines only index the most recent version of the documentation.

**Comment by asmeurer** [comment]
I think we already tried something to make it do this. If it isn’t working,
we should just remove the old documentation as I had suggested on the
mailing list.

Can you give an example of a search phrase that returns old docs versions?

**Comment by gschintgen** [comment]
Google search: "sympy acosh":
no docs for v1.4 on the whole first page, only 0.7.1 and 0.7.2.

**Comment by mcrowson** [comment]
There is no robots file for the docs subdomain. It may be as simple as adding that file to the root and putting in the pattern for the old versions.

https://docs.sympy.org/robots.txt

**Comment by asmeurer** [comment]
This is the mailing list thread I mentioned https://groups.google.com/forum/#!msg/sympy/arUgORYqZlc/UWavuD3OAwAJ

**Comment by asmeurer** [comment]
I can confirm the "sympy acosh". A big problem is that the docs for the old versions contained the mpmath docs, which often get higher priority from Google. But the mpmath docs are completely wrong for someone looking for SymPy docs. 

I still think we should just remove all the old docs, but others were against this.

**Comment by asmeurer** [comment]
I just got a Google search engine report for sympy.org (I think it's for the month of October 2019 only) https://docs.google.com/spreadsheets/d/16LKHE9sPRJ5z9GYcYK74Qhn0ABVsBHpivv0pBh1mj68/edit?usp=sharing. 

You can see 22 of the top 100 result links in the docs are from old version URLs. A few are from linking to when the old docs had mpmath docs. I've seen this confuse people because they don't realize that they are looking at a numerical function, and `sympy.mpmath` doesn't exist anymore. 

So I still *strongly* think we should remove old versions from docs.sympy.org, and only have `latest` and `dev`.

**Comment by asmeurer** [comment]
This is basically fixed because we don't serve old versions anymore. Some other sites do mirror older versions, but we do include a canonical link to docs.sympy.org so that should help search engines refer to our site instead of theirs. Beyond that, I don't know how else to influence Google. It seems to just be bad at surfacing good results over garbage for programming related queries in general these days.
