### ISSUE TITLE
Try hoverxref Sphinx extension 

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#17456]
https://sphinx-hoverxref.readthedocs.io/en/latest/

**Comment by asmeurer** [comment]
I tried it but I couldn't get it to work. I'm not sure if I was configuring it wrong or if it doesn't support our Sphinx theme or what. Here's what I tried

```diff
diff --git a/doc/src/conf.py b/doc/src/conf.py
index 4ccc72b041..556eed2f0a 100644
--- a/doc/src/conf.py
+++ b/doc/src/conf.py
@@ -24,7 +24,11 @@
 # coming with Sphinx (named 'sphinx.addons.*') or your custom ones.
 extensions = ['sphinx.ext.autodoc', 'sphinx.ext.viewcode',
               'sphinx.ext.mathjax', 'numpydoc', 'sympylive',
-              'sphinx.ext.graphviz', 'matplotlib.sphinxext.plot_directive']
+              'sphinx.ext.graphviz', 'matplotlib.sphinxext.plot_directive',
+              'hoverxref.extension',
+]
+
+hoverxref_auto_ref = True

 # Use this to use pngmath instead
 #extensions = ['sphinx.ext.autodoc', 'sphinx.ext.viewcode', 'sphinx.ext.pngmath', ]
```

**Comment by humitos** [comment]
Hi! I'm the author of the extension. I can help you to debug your issue.

The `hoverxref_auto_ref` *only* works on `:ref:` roles. If you want to show tooltips on other custom object as well, you need register them with `hoverxref_roles`.

Finally, if you want to put tooltips on Python Domain objects, you need to use the config `hoverxref_domains = ['py']`.

See more at https://sphinx-hoverxref.readthedocs.io/en/latest/configuration.html and let me know if you still have issues. I'm happy to see this Sphinx extension in such a great project like SymPy :smile:

**Comment by asmeurer** [comment]
I tried that and it doesn't do anything for our "See also" links, which is what the majority of our cross references are. 

It seems like there are a lot of configuration options required to make this work. You also have to set some flag to make mathjax work. I would suggest enabling everything by default, so that it just works when you install the extension. Most people will want to have hover cards everywhere, and when they install the extension and don't get any, will assume the extension is broken (that's what I thought at first). 

Actually, I'm not convinced yet that the extension isn't broken somehow. I tried 

```patch
diff --git a/doc/src/conf.py b/doc/src/conf.py
index 4ccc72b041..31aa3601b2 100644
--- a/doc/src/conf.py
+++ b/doc/src/conf.py
@@ -24,7 +24,12 @@
 # coming with Sphinx (named 'sphinx.addons.*') or your custom ones.
 extensions = ['sphinx.ext.autodoc', 'sphinx.ext.viewcode',
               'sphinx.ext.mathjax', 'numpydoc', 'sympylive',
-              'sphinx.ext.graphviz', 'matplotlib.sphinxext.plot_directive']
+              'sphinx.ext.graphviz', 'matplotlib.sphinxext.plot_directive',
+              'hoverxref.extension',
+]
+
+hoverxref_auto_ref = True
+hoverxref_domains = ['py']

 # Use this to use pngmath instead
 #extensions = ['sphinx.ext.autodoc', 'sphinx.ext.viewcode', 'sphinx.ext.pngmath', ]
```

and I haven't seen a single hovercard anywhere in the built docs. Even at https://docs.sympy.org/latest/modules/solvers/ode.html, which has several `:py:` references in the `dsolve` docstring (at the top). And for https://github.com/sympy/sympy/blob/master/doc/src/modules/printing.rst which has a `:ref:` right at the top, I don't get one either. I tried changing it to `:hoverxref:` and I got an error: `hoverxref role is not fully configured.` Any idea what I am doing wrong?

**Comment by humitos** [comment]
I'm sorry that you are having this experience with the extension. I will try to clarify some aspects that I just realized.

Firstly, the initial beta release was done _today_. So, probably there are a lot of things that need to be polish --like the suggestion on the documentation that you have previously done, thanks!

Besides, the extension currently _only_ works on Read the Docs because it uses one of its feature (Public Embed API) to retrieve the content that needs to be displayed inside the tooltip. I just realize that SymPy documentation is on GitHub pages, right?

Because of these two miss-communication, I just added an explanation around this in the extension documentation trying to be clearer with the users.

> It seems like there are a lot of configuration options required to make this work. You also have to set some flag to make mathjax work. I would suggest enabling everything by default, so that it just works when you install the extension

There are some small performance drawbacks on enabling everything by default --at least in this beta release, since for each tooltip that is shown there are some Javascript that needs to be triggered to re-render extra things inside the tooltip (i.e. mathjax).

On the other hand, this could be improved writing some extra Javascript code that "auto detect" if it needs to be re-rendered or not and only triggering it when it's needed.

> I tried changing it to `:hoverxref:` and I got an error: `hoverxref role is not fully configured.` Any idea what I am doing wrong?

Yes. This is because, as I mentioned before, the extension currently works on Read the Docs only. The logging error could probably be improved to communicate this in a better way as well.

I really appreciate your feedback! I'm happy to help.

**Comment by asmeurer** [comment]
OK, I didn't realize it was Read the Docs only. That definitely wasn't clear at all in the documentation.

I am closing this for now as it seems we don't be able to use it. Please let us know if the extension later gains support for docs published outside of Read the Docs.

**Comment by humitos** [comment]
> OK, I didn't realize it was Read the Docs only. That definitely wasn't clear at all in the documentation.

Right. I realized this because you let me know.

> Please let us know if the extension later gains support for docs published outside of Read the Docs.

There are some ideas to implement the same logic that does the API endpoint into Javascript or event with Python code inside the hoverxref extension itself. 

I'll keep you posted!
