### ISSUE TITLE
test_var should use `exec` instead of calling `var` directly. 

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#17547]
test_var should also probably be using `exec` instead of calling `var` directly. The problem is that once you run the test once, the variables from var are defined globally (`var` injects names into `globals()`, not `locals()`, which is one reason why its use noninteractively is so bad). So the tests could be subtly wrong. For instance, if someone accidentally wrote

```py
def test1():
    var('x')
    assert x == Symbol('x')

def test2():
    var('xx')
    assert x == Symbol('x') # Typo: this should be assert xx == Symbol('xx')
```

the test would pass, but only if test1 is run before test2. It also could lead to unexpected behavior if someone were to run `test(subprocess=False)` twice in the same process (e.g., https://github.com/sympy/sympy/pull/15163). Generally, tests should be written in a way that they do not influence some global state so that they affect each other. It would be better to have tests in that file like

```py
def test_var():
    ns = {'var': var}
    eval("var('x')", ns)
    assert ns['x'] == Symbol('x')
```

_Originally posted by @asmeurer in https://github.com/sympy/sympy/pull/17544#issuecomment-526375244_

**Comment by sachin-4099** [comment]
I would like to work on this issue. Please guide me as to how to proceed.
@asmeurer

**Comment by deXetrous** [comment]
Hi @asmeurer this error can occur anywhere var() is used as they the variables from var are defined globally. What was the purpose of defining them globally? Can't they be defined in local scope just like variables defined in symbols() ?

**Comment by asmeurer** [comment]
Yes, that's one reason why `var` should never be used, except in interactive sessions. 

Variables cannot be injected into locals. Local scopes in Python are created statically when a function is defined and cannot be extended.

**Comment by Oktosha** [comment]
Should the tests for var be moved elsewhere after the use of `exec` is added?

Right now the comment in the beginning of the [test_var.py](https://github.com/sympy/sympy/blob/ab14b02dba5a7e3e4fb1e807fc8a954f1047a1a1/sympy/core/tests/test_var.py) says that tests for var are in their own file, because var pollutes global namespace. Is there any other good place where these tests should live given they don't pollute the namespace?

**Comment by Oktosha** [comment]
@sachin-4099, do you still want to work on this issue? I can take this issue myself or I can guide you. What are you stuck with?

**Comment by sachin-4099** [comment]
Please guide me. I just want to know what we need to do.

**Comment by Oktosha** [comment]
Ok. Have you set the development environment? Can you run the tests locally? https://github.com/sympy/sympy/wiki/Development-workflow

**Comment by asmeurer** [comment]
We can keep them in the same file.

**Comment by asmeurer** [comment]
They can also go in the test_symbol.py file. It doesn't matter either way.

**Comment by sachin-4099** [comment]
> Ok. Have you set the development environment? Can you run the tests locally? 
https://github.com/sympy/sympy/wiki/Development-workflow

Yes, extremely sorry for the late reply

**Comment by Oktosha** [comment]
> > Ok. Have you set the development environment? Can you run the tests locally?
> > https://github.com/sympy/sympy/wiki/Development-workflow
> 
> Yes, extremely sorry for the late reply

Extremely sorry for the late reply, too!

Next you have to change the file [test_var.py](https://github.com/sympy/sympy/blob/ab14b02dba5a7e3e4fb1e807fc8a954f1047a1a1/sympy/core/tests/test_var.py) in the way @asmeurer described and check that all the changes are working both in python2 and python3.

You have to wrap all the calls of the `var` with the `exec` function (statement for python2)
You can read about them in the official documentation: [python2](
https://docs.python.org/2/reference/simple_stmts.html#the-exec-statement), [python3](https://docs.python.org/3/library/functions.html#exec)

@asmeurer talked about `exec` but have written an example with `eval`. You can find the difference [here](https://stackoverflow.com/questions/2220699/whats-the-difference-between-eval-exec-and-compile) but for out purposes the most important thing is that `exec` and `eval` allow to execute code in its own sandbox. So it won't break stuff outside it i. e. insert extra global variables.

Let me give you an example.

```python
def f():
    global a
    a = 3
f()
print(a)
```

Here function `f` creates global variable that is visible outside of it. So we can print it outside the function `f`. But if we wrap this inside the `exec`

```python
exec("""
def f():
    global a
    a = 3
f()
print(a)
""", {})
print(a)
```

the second print won't see the variable `a` because it's trapped inside the exec.

You can also see that I pass an empty dictionary to `exec`. It's for telling exec which variables it can see from the outside. If the dictionary is empty, exec won't see any of them. So that's why @asmeurer passes `{"var": var}` to the `eval`.

So what you have to do is to wrap code inside each unit test (functions that begin with the `test_`) with `exec`.  Given a test:

```python
def test_var():
    var("a")
    assert a == Symbol("a")
```

You wrap it as

```python
def test_var():
    exec("""
var("a")
assert a == Symbol("a")
    """, {"var": var, "Symbol": Symbol})
```

**Comment by sachin-4099** [comment]
Actually I am getting an error:
**NameError: name 'z1' is not defined** 
for the 1st test in test_var file.
While all other tests are working fine. Can you suggest a solution?

**Comment by Oktosha** [comment]
@sachin-4099 you should define `_make_z1` inside the `exec`. When function is defined outside the `exec` its globals are outside `exec`, too, so the variable is injected into the outer globals. This code will work:

```python
import textwrap
from sympy import Symbol, var
from sympy.utilities.pytest import raises

def _make_z():
    z = var("z")

def test_var():
    exec(textwrap.dedent("""
            _make_z()
            raises(NameError, lambda: z)
        """),
        {"_make_z": _make_z, "raises": raises})
    print(z)
```

But in our tests we want something like this:

```python
import textwrap
from sympy import Symbol, var
from sympy.utilities.pytest import raises

def test_var():
    exec(textwrap.dedent("""
            def _make_z():
                z = var("z")

            raises(NameError, lambda: z)
            _make_z()
            assert z == Symbol('z')
        """),
        {"var": var, "raises": raises, "Symbol": Symbol})
```

**Comment by Oktosha** [comment]
@asmeurer after adding a simple wrap inside `exec` the code became way less readable to my taste. It's super hard for me to read lines without syntax highlighting. Is the isolation of the tests worth it? Or is it even more error-prone now? Shall we come up with more granular wrapping than is done in #17705 at the moment?

**Comment by asmeurer** [comment]
You can put much less code in a string if you use the pattern I used in the original comment, which is to just call `var` in `eval` and check the globals dictionary that is passed in outside of the eval.

**Comment by asmeurer** [comment]
For the tests that test the return value of var, you can use something like

```py
z = eval("var('z')")
assert z == Symbol('z')
```
