### ISSUE TITLE
Weird result in solveset

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#17580]
`solveset(1/(1-x**3)**2, x, S.Reals)` returns `Intersection`

**Comment by ethankward** [comment]
In latest master I get `Intersection({oo*sign(zoo)}, Reals)`.

**Comment by Smit-create** [comment]
On current master I get the following result:
```
>>> from sympy import *
>>> from sympy.abc import x
>>> solveset(1/(1-x**3)**2, x, S.Reals)
EmptySet
```

**Comment by oscargus** [comment]
Seems like EmptySet is the correct result. I'll add a test and this can be closed.

**Comment by oscarbenjamin** [comment]
This was fixed in 65b80818e0515b2967e4a93a6604a23d7b51e11e from #18426.

That suggests that the buggy result is still generated internally but then simplified away by `Intersection`.

The old result was this:
```python
In [1]: solveset(1/(1-x**3)**2, x, S.Reals)
Out[1]: ℝ ∩ {∞⋅sign(zoo)}
```
After #18426 that intersection gives the empty set:
```python
In [2]: Intersection(FiniteSet(oo*sign(zoo)), Reals, evaluate=False)
Out[2]: ℝ ∩ {∞⋅sign(zoo)}

In [3]: Intersection(FiniteSet(oo*sign(zoo)), Reals)
Out[3]: ∅
```
Wherever the `oo*sign(zoo)` comes from should probably fixed not to return that rather than depending on `Intersection` to filter it away.

**Comment by oscargus** [comment]
OK! I'll add the test but will not close this.

**Comment by oscargus** [comment]
In #21925 this is now correctly fixed.
