### ISSUE TITLE
Documentation references are not accurate

### ISSUE THREAD

**Issue by dangars** [sympy/sympy#17626]
Hi, I'm using sympy and it is a great package!

Sometimes I find it difficult to understand the documentation because the references are not "accurate"

For example if I want to use a mutable Tensor. According to:
https://docs.sympy.org/latest/modules/tensor/array.html
I would have to use `sympy.tensor.array.MutableDenseNDimArray`. It turns out that that class doesn't exist and I have to use `sympy.array.MutableDenseNDimArray` which is not documented and took me a while to figure out the right reference.

I found similar cases in other parts of the documentation. Is it me that I don't understand correctly how the documentation works?

**Comment by asmeurer** [comment]
This is due to a namespace overwriting that happens when SymPy is imported. `sympy.array` is indeed `sympy.tensor.array`, which you can see if you print it:

```
>>> sympy.array
<module 'sympy.tensor.array' from './sympy/tensor/array/__init__.py'>
```

the problem is that `sympy.tensor` is actually `sympy.tensor.tensor`

```
>>> sympy.tensor
<module 'sympy.tensor.tensor' from './sympy/tensor/tensor.py'>
```

The problem is that the directory and the .py file have the same name.

The names in the documentation are what you should use to import. For instance

```
>>> from sympy.tensor.array import MutableDenseNDimArray
```

This is something that should be fixed once https://github.com/sympy/sympy/issues/13525 is fixed.

**Comment by dangars** [comment]
Thanks a lot for your quick answer!
I close this issue
