### ISSUE TITLE
Generating circles to obtain radius using three points.

### ISSUE THREAD

**Issue by Pepin123** [sympy/sympy#17659]
I'm trying to generate circles based on coordinate data from a CSV file, but when it gets to the circleCalc Function it throws this error AttributeError: 'Segment2D' object has no attribute 'radius'.

what i am doing wrong?

def circleCalc(x1,y1,x2,y2,x3,y3):
    c1 = Circle(Point(x1,y1), Point(x2,y2), Point(x3,y3))
    print(float(c1.radius))

**Comment by oscarbenjamin** [comment]
Perhaps you have given 3 colinear points so that instead of a Circle you
get a Segment2D which represents the line between the furthest points:

In [4]: Circle((1, 1), (2, 2), (2, 2))
Out[4]: Segment2D(Point2D(1, 1), Point2D(2, 2))

I'm not sure what's really appropriate in that situation but Segment2D
doesn't seem right. I could imagine returning an infinite line with the
idea being that it is a circle of infinite radius...

You might be able to handle this in your code by checking isinstance(c1,
Circle).

Oscar

**Comment by Pepin123** [comment]
I've changed my test data set and no longer seems to be hitting me with an error.
Thank you.
