### ISSUE TITLE
integrate throws error for rational functions involving I

### ISSUE THREAD

**Issue by 78g** [sympy/sympy#17841]
Relatively simple integrals such as
```python
x = symbols('x')
f = diff(1/(x**2+x+I),x)
integrate(f,x)
```
fail with the error
```
sympy.polys.polyerrors.PolynomialDivisionFailed: couldn't reduce degree in a polynomial division algorithm when dividing [EX(-2), EX(-1)] by [EX(-(-15 + 8*I)*(15 + 8*I)/289)]. This can happen when it's not possible to detect zero in the coefficient domain. The domain of computation is EX. You may want to use a different simplification algorithm. Note that in general it's not possible to guarantee to detect zero in this domain.
```
The best workaround I have found so far is
```python
c = symbols('c',complex=True)
integrate(f.subs(I,c),x).subs(c,I)
```
but ``integrate(f,x,manual=True)`` also works.

**Comment by jksuom** [comment]
The presence of `I` makes the expression domain `EX` the coefficient domain of the denominator polynomial. This is problematic because `EX` has no reliable zero detection algorithm. The relevant polynomial division actually works correctly but the (unsimplified) coefficient expressions that are expected to be zero are not recognized as such, whence the error.

The expression domain has its own light-weight `simplify` method (the full `simplify` would be too expensive) but it does not cover this case. However, it seems that an addfitional `expand` step would suffice.
```
--- a/sympy/polys/domains/expressiondomain.py
+++ b/sympy/polys/domains/expressiondomain.py
@@ -45,7 +45,7 @@ def denom(f):
             return f.__class__(f.ex.as_numer_denom()[1])
 
         def simplify(f, ex):
-            return f.__class__(ex.cancel())
+            return f.__class__(ex.cancel().expand())
 
         def __abs__(f):
             return f.__class__(abs(f.ex))
```
In fact, not all default methods of `expand` are needed, `mul` alone would suffice in this case. This can be implemented by suitable keywords as follows, for example.
```
--- a/sympy/polys/domains/expressiondomain.py
+++ b/sympy/polys/domains/expressiondomain.py
@@ -9,6 +9,10 @@
 from sympy.polys.polyutils import PicklableWithSlots
 from sympy.utilities import public
 
+eflags = dict(mul=True, power_exp=False, power_base=False,
+              basic=False, multinomial=False, log=False)
+
+
 @public
 class ExpressionDomain(Field, CharacteristicZero, SimpleDomain):
     """A class for arbitrary expressions. """
@@ -45,7 +49,7 @@ def denom(f):
             return f.__class__(f.ex.as_numer_denom()[1])
 
         def simplify(f, ex):
-            return f.__class__(ex.cancel())
+            return f.__class__(ex.cancel().expand(**eflags))
 
         def __abs__(f):
             return f.__class__(abs(f.ex))
```
This method allows for more fine-grained control of simplification.

**Comment by asmeurer** [comment]
Better to just use expand_mul. If deep=False works too it should also use that.

**Comment by jksuom** [comment]
I'd prefer expand with explicit flags, including deep=False. expand_mul will do the same but it adds an extra function call. Besides, it may turn out that other expand methods will also be needed.

**Comment by asmeurer** [comment]
expand_mul already hard-codes those flags. And if somehow additional flags are added in the future it will stay correct. I wish we had made it so that mul=None is the default and mul=True disables the other flags.

What is the actual expression in question that needs to be expanded here? Calling expand_mul after cancel will expand the numerator over the denominator, and will generally result in a much larger expression. So we almost certainly don't want to do that.
