### ISSUE TITLE
Noninteger coefficients in cancel function

### ISSUE THREAD

**Issue by urojony** [sympy/sympy#17843]
Documentation says that in output of 'cancel' function "leading coefficients of numerator and denominator are integers" which isn't always true. For example
`>>> cancel('(x/2+1)/y')`
returns
`(x + 2)/(2*y)` 
which is fine, but
`>>> cancel('(x/2+1)')`
returns
`x/2 + 1`
and I would expect 
`(x+2)/2`

**Comment by namannimmo10** [comment]
@oscarbenjamin Can I take up this issue? And can you please give some pointers on how I should proceed to do that? Because I haven't contributed to sympy before.

**Comment by oscarbenjamin** [comment]
I'm not sure what `cancel` is supposed to do in this situation. The docstring says
```
Help on function cancel in module sympy.polys.polytools:

cancel(f, *gens, **args)
    Cancel common factors in a rational function ``f``.
    
    Examples
    ========
    
    >>> from sympy import cancel, sqrt, Symbol
    >>> from sympy.abc import x
    >>> A = Symbol('A', commutative=False)
    
    >>> cancel((2*x**2 - 2)/(x**2 - 2*x + 1))
    (2*x + 2)/(x - 1)
    >>> cancel((sqrt(3) + sqrt(15)*A)/(sqrt(2) + sqrt(10)*A))
    sqrt(6)/2
```
That suggests that `cancel` is intended to be used with a "rational function" as input but the example here `x/2 + 1` is not a rational function.

The tutorial though says something different:
https://docs.sympy.org/latest/tutorial/simplification.html#cancel
```
cancel() will take any rational function and put it into the standard canonical form, 𝑝/𝑞,
where 𝑝 and 𝑞 are expanded polynomials with no common factors, and the leading
coefficients of 𝑝 and 𝑞 do not have denominators (i.e., are integers).
```

The tutorial suggests factor can also be used for this
```
In [15]: f = x/2 + 1                                                                                                                                          

In [16]: f                                                                                                                                                    
Out[16]: 
x    
─ + 1
2    

In [17]: factor(f)                                                                                                                                            
Out[17]: 
x + 2
─────
  2 
```

That is a rational function and giving that to cancel gives:
```
In [18]: cancel(_)                                                                                                                                            
Out[18]: 
x    
─ + 1
2
```

I suspect that where this comes from is
```
In [20]: (x+2)*S.Half                                                                                                                                         
Out[20]: 
x    
─ + 1
2    

In [21]: (x+2)/2                                                                                                                                              
Out[21]: 
x    
─ + 1
2 
```
So the expression that you want here auto-simplifies. I guess factor must be creating this as
```
In [24]: Mul((x+2), S.Half, evaluate=False)                                                                                                                   
Out[24]: 
x + 2
─────
  2 
```

The auto-simplification won't happen for a non-rational:
```
In [27]: cancel(x/y + 1)                                                                                                                                      
Out[27]: 
x + y
─────
  y 
```

A momentary fix would be using `evaluate=False` in cancel but it won't last when any other operation occurs:
```
In [29]: Mul((x+2), S.Half, evaluate=False)                                                                                                                   
Out[29]: 
x + 2
─────
  2  

In [30]: _*3                                                                                                                                                  
Out[30]: 
3⋅x    
─── + 3
 2 
```

Essentially the problem here is that a 2-arg Mul distributes Rationals (this is a long-standing issue that is hard to fix).

You could try using `evaluate=False` at the appropriate place at the end of `cancel`.

**Comment by oscarbenjamin** [comment]
Possibly it is best to have the denominator first in the Mul:
```
In [54]: Mul(S.Half, (x+2), evaluate=False) * 3                                                                                                               
Out[54]: 
3⋅(x + 2)
─────────
    2

In [55]: Mul((x+2), S.Half, evaluate=False) * 3                                                                                                               
Out[55]: 
3⋅x    
─── + 3
 2  
```
I'm not sure if that should be considered a bug as well...

**Comment by namannimmo10** [comment]
Thank you so much for explaining it to me. 

> "A momentary fix would be using evaluate=False "
    Okay, I'll try that

The docstring says that  ``cancel(f, *gens, **args)`'   --> Cancel` common factors in a rational function ``f``.
And if we don't pass a rational function as an argument it should throw an error or something, no??

**Comment by oscarbenjamin** [comment]
Actually the function is a rational function. It isn't in the form of a ratio but it can be put into that form.

**Comment by namannimmo10** [comment]
Alright!

**Comment by namannimmo10** [comment]
Hey @oscarbenjamin 

The problem is indeed in the `Mul` distributing over two arguments.  But I don't know the consequences of changing it, maybe some other code will break??

In https://github.com/sympy/sympy/blob/6fca8e1c182bb84432b4d7307f8bbf0e8899598b/sympy/polys/polytools.py#L6654
instead of straightaway returning, we could do something like 
```
if G.is_Number:
    F.as_expr().__div__(G.as_expr(), evaluate=False)
else:
    F.as_expr() / G.as_expr()
```

If we do this like this, we will need to change the code in https://github.com/sympy/sympy/blob/6fca8e1c182bb84432b4d7307f8bbf0e8899598b/sympy/core/expr.py#L232 and pass another `*args` argument that will be forwarded to the `Mul` in there

-----------------------------------
I don't think it looks like an easy issue but I'm willing to move forward, just need some help!!

**Comment by oscarbenjamin** [comment]
I guess it should be:
```
return Mul(c, 1/Q.as_expr(), P.as_expr(), evaluate=False)
```
Or perhaps
```
return Mul(c, P.as_expr()/Q.as_expr(), evaluate=False)
```
Why don't you give it a try and run the tests to see whether any tests fail?

**Comment by namannimmo10** [comment]
I tried changing ` c*(P.as_expr()/Q.as_expr())`  to `Mul(c, P.as_expr()/Q.as_expr(), evaluate=False)`
and only one test failed out of 145. Unfortunately, I couldn't figure out how to fix (AssertionError) that test

https://github.com/sympy/sympy/blob/master/sympy/polys/tests/test_polytools.py#L2866

**Comment by oscarbenjamin** [comment]
If you run that code yourself what output do you get on master and what output do you get with this PR?

Also does it fix the issue?

**Comment by oscarbenjamin** [comment]
I just realised that this isn't a pull request. If you send a PR it's easier to discuss this because we can see what changes you have made and can test the code out as well.

**Comment by namannimmo10** [comment]
Can you suggest any changes?

**Comment by oscarbenjamin** [comment]
This could maybe work:
```diff
diff --git a/sympy/polys/polytools.py b/sympy/polys/polytools.py
index ec7e536e9b..97759d70d9 100644
--- a/sympy/polys/polytools.py
+++ b/sympy/polys/polytools.py
@@ -6651,7 +6651,7 @@ def cancel(f, *gens, **args):
     c, P, Q = F.cancel(G)
 
     if not isinstance(f, (tuple, Tuple)):
-        return c*(P.as_expr()/Q.as_expr())
+        return c * Mul(1/Q.as_expr(), P.as_expr(), evaluate=False)
     else:
         if not opt.polys:
             return c, P.as_expr(), Q.as_expr()
```
