### ISSUE TITLE
Adjust releasing flow, add 3-digit versioning and more frequent update.

### ISSUE THREAD

**Issue by stevenleeS0ht** [sympy/sympy#17864]
Currently sympy use 2 digit versioning model. This kind of versioning make the formal release too slow, a lot of new feature cannot be access from the common way (pip, linux distro ...).

I am wondering if sympy can use 3-digit versioning method and releasing flow. Which can be able to have a more frequent update.

**Comment by asmeurer** [comment]
@stevenleeS0ht are you volunteering to help with the release? :)

But seriously, I do think we need to release more often. There have been two issues making the releases slow

- I'm the only one who does the releases, which means they get done whenever I have enough time to do them
- Releases tend to have a lot of blocking issues, which prevent them from happening. See the [1.5 milestone](https://github.com/sympy/sympy/milestone/52) for instance (if you want the next release to come sooner, work on those issues). 

I'm looking into ways to solve issue 1. I don't know of any magic ways to fix issue 2, other than the fact that the more often we release, the fewer blocking issues there will be. If anyone has any other suggestions, let us know. 

The number of digits in the version doesn't really have anything to do with how often we release. It has to do with the issues I specified above. We actually do use the third version number whenever we have to make a bugfix release. The past few releases haven't needed those, mostly because our test processes have gotten good enough that we catch issues before the final release happens.

**Comment by stevenleeS0ht** [comment]
@asmeurer ,

Even if I am glad to make contribution, I am still lack in time, and I cannot guarantee to make steady contribution all the time. 

To resolve this issue, I think the best way to handle this is let more and more people take part in this.

I am not so familiar with GITHUB, I don't know the view of progress milestone until you provide me the link. Since this is not the essential function in GITHUB workflow. A lot of people may don't know as well.

I would like to recommend to provide this link in README.md. And let more and more people know the current demand of sympy development.

**Comment by oscarbenjamin** [comment]
I think a lot of the blocking issues are not really blocking issues (note that I already removed many of them). It would be easier to do a release if we were clearer about what should or should not be a blocking issue in the first place.

**Comment by asmeurer** [comment]
Let's start a page on the wiki for that.

**Comment by asmeurer** [comment]
I started a discussion issue about blockers https://github.com/sympy/sympy/issues/17885. 

I am closing this issue.
