### ISSUE TITLE
Unexpected AttributeError when multiplying a matrix with a polynomial

### ISSUE THREAD

**Issue by akizunx** [sympy/sympy#17988]
> Python version: 3.7.4
> sympy version: 1.4

When trying to multiply a matrix of polynomials with a polynomial, different calculation orders lead to different results.
```
>>> from sympy import poly, Matrix, symbols
>>> x = symbols('x')
>>> p = poly(x - 1)
>>> M = Matrix([[poly(x + 1), poly(x + 1)]])
>>> M * p
Matrix([[Poly(x**2 - 1, x, domain='ZZ'), Poly(x**2 - 1, x, domain='ZZ')]])
```
If change the order of this operation, an AttributeError will be thrown.
```
>>> p * M
AttributeError: MutableDenseMatrix has no attribute is_Poly.
```

**Comment by jksuom** [comment]
Polynomials and matrices do not work well together. There are several issues. In this example, `p * M` is handled by `Poly.__mul__()` that expects that the second operand has been transformed to a SymPy object by the `_sympifyit` decorator: https://github.com/sympy/sympy/blob/1c9f33b16bc8dc8fd1ce9b151080dd107c084d1f/sympy/polys/polytools.py#L4038-L4046
However, the decorator has no effect on matrices because they have the `_op_priority` attribute defined even when they are not Basic objects (contrary to what the comment claims): https://github.com/sympy/sympy/blob/1c9f33b16bc8dc8fd1ce9b151080dd107c084d1f/sympy/core/decorators.py#L87-L91
I think that the condition `not hasattr(b, '_op_priority')` should be changed to `not isinstance(b, Basic)`. That should fix the AttributeError, but there remains another issue: `__mul__()` tries to turn the matrix `g` into a polynomial on line 4042, and, unexpectedly, succeeds because `Poly.__new__()` will see the matrix as an iterable and interpret its items as the coefficients of a polynomial to be created (which is totally wrong in the matrix case). This can be fixed by using `f.__class__.new(g, *f.gens)` instead of `f.__class__(g, *f.gens)` as that will check the arguments.

**Comment by akizunx** [comment]
I followed your suggestion and modified the code. 
https://github.com/sympy/sympy/blob/1c9f33b16bc8dc8fd1ce9b151080dd107c084d1f/sympy/core/decorators.py#L89-L91 line 89 changed to`if not isinstance(b, Basic):`

https://github.com/sympy/sympy/blob/1c9f33b16bc8dc8fd1ce9b151080dd107c084d1f/sympy/polys/polytools.py#L4038-L4046 line 4042 changed to`g = f.__class__.new(g, *f.gens)`

Then I ran the test code again, and the AttributeError disappeared. But the type of elements in the matrix was not the `Poly`.
```
>>> p = poly(x - 1)
>>> M = Matrix([[poly(x + 1), poly(x + 1)]])
>>> p * M
Matrix([[(x - 1)*(x + 1), (x - 1)*(x + 1)]])
>>> type((p * M)[0, 0])
<class 'sympy.core.mul.Mul'>
```
I think this is due to `g = f.__class__.new(g, *f.gens)`  that raised `PolynomialError`. So p was converted to `Expr` on the line 4044.

**Comment by jksuom** [comment]
> So p was converted to Expr on the line 4044.

Maybe that line should also be changed.  You could try `return NotImplemented` (which is, in fact, true in `polys`).

**Comment by akizunx** [comment]
> You could try `return NotImplemented`

That `NotImplemented` is returned on the line 4044 could give the right answer and pass the following test.
```
# sympy/polys/tests/test_polytools.py
def test_issue_17988():
    from sympy import Matrix

    x = Symbol('x')
    p = poly(x - 1)
    M = Matrix([[poly(x + 1), poly(x + 1)]])
    assert p * M == M * p == Matrix([[poly(x**2 - 1), poly(x**2 - 1)]])
```
However, unfortunately, it seems that those changes I made break other tests.
```
>>> import sympy
>>> sympy.test('/polys')
# before
tests finished: 868 passed, 5 skipped, 4 expected to fail
# after
tests finished: 865 passed, 5 skipped, 4 expected to fail, 4 exceptions
```

**Comment by jksuom** [comment]
> it seems that those changes I made break other tests.

That will often happen with fixes like these. However, it should be possible to edit the failing tests to make them pass.

**Comment by jksuom** [comment]
I think that you could try another fix. Change the line 4044 to `return NotImplemented` but leave 4042 as it is. Then make `Poly.__new__()` more robust by something like this:
```
--- a/sympy/polys/polytools.py
+++ b/sympy/polys/polytools.py
@@ -111,7 +111,7 @@ def __new__(cls, rep, *gens, **args):
         if 'order' in opt:
             raise NotImplementedError("'order' keyword is not implemented yet")
 
-        if iterable(rep, exclude=str):
+        if iterable(rep, exclude=str) and not isinstance(rep, Basic):
             if isinstance(rep, dict):
                 return cls._from_dict(rep, opt)
             else:
@@ -121,8 +121,10 @@ def __new__(cls, rep, *gens, **args):
 
             if rep.is_Poly:
                 return cls._from_poly(rep, opt)
-            else:
+            elif isinstance(rep, Expr):
                 return cls._from_expr(rep, opt)
+            else:
+                raise PolynomialError
 
     @classmethod
     def new(cls, rep, *gens):
```
The current version of `Poly.__new__()` fails on matrices because a matrix is iterable. The condition `not isinstance(rep, Basic)` should solve the issue as `Matrix` does not inherit form `Basic`. It should not affect the current behaviour as iterable `rep` arguments are intended for internal use only and they are pure Python objects: lists or dicts. A matrix should raise the exception on the last line as it is not of class `Expr`.

**Comment by akizunx** [comment]
Thank you for your suggestion. I would look into it if I have more spare time.
