### ISSUE TITLE
SymPy tutorial newbie questions

### ISSUE THREAD

**Issue by thomassligon** [sympy/sympy#18014]
In the tutorial
[https://docs.sympy.org/latest/tutorial/intro.html#what-is-symbolic-computation](https://docs.sympy.org/latest/tutorial/intro.html#what-is-symbolic-computation)
the following example
```
import sympy
sympy.sqrt(3)
```
the SymPy Live Shell displays the square root of 3 in fully formatted form. However, when I run this locally, I need to call
`print(latex(sympy.sqrt(3)))`
then then I get 
```
C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\sympy\deprecated\class_registry.py:38: SymPyDeprecationWarning:

C, including its class ClassRegistry, has been deprecated since SymPy
1.0. It will be last supported in SymPy version 1.0. Use direct
imports from the defining module instead. See
https://github.com/sympy/sympy/issues/9371 for more info.

  deprecated_since_version='1.0').warn(stacklevel=2)
\sqrt{3}
```

Why do I get a warning saying that C is deprecated, even though I am not using it?

What do I need to do in order to see the LaTeX fully formatted as is done by the Live Shell?

Why does the LiveShell display the value of the square root, even though there is no print statement?

A very similar situation can be seen in this example:
```
from sympy import symbols
x, y = symbols('x y')
expr = x + 2*y
expr
```

So, the more detailed question is
Why does the first example print the square root immediately, and why does the second example require the "expr" statement?

PS: This looks very similar to MATLAB, where a statement consisting of only an expression, and with no semicolon, prints the content of the expression.

**Comment by oscarbenjamin** [comment]
When you say that you "run it locally" what do you mean? I see that you are on Windows so are you running from a normal Windows terminal (cmd.exe)? Are you running from IDLE or some other IDE?

There are many ways to use sympy but I would personally run something like that in the terminal using isympy:
```console
$ isympy
IPython console for SymPy 1.5rc1 (Python 2.7.16-64-bit) (ground types: python)

These commands were executed:
>>> from __future__ import division
>>> from sympy import *
>>> x, y, z, t = symbols('x y z t')
>>> k, m, n = symbols('k m n', integer=True)
>>> f, g, h = symbols('f g h', cls=Function)
>>> init_printing()

Documentation can be found at https://docs.sympy.org/1.5rc1/


In [1]: sqrt(3)
Out[1]: √3
```
However this makes more sense for me since I don't use Windows and OSX and Linux both have better terminals. I don't know if the Windows terminal can support symbols like sqrt.

Probably what you want is to use something like jupyter or spyder.


I'm closing this as it seems like a request for help rather than a report of a bug in SymPy. If I am wrong about that then let me know and I can reopen it.

Questions about using SymPy should go to the SymPy mailing list or StackOverflow.

**Comment by thomassligon** [comment]
Thanks for responding. Running locally meant running on my PC as opposed to the cloud. I created a project in Visual Studio and ran it there, but there is no need to bother with that. My question was about how the SymPy Live Shell does it.

**Comment by oscarbenjamin** [comment]
There are many different ways to run locally though. It sounds as if you are using the Visual Studio Code editor (different from Visual Studio itself). I haven't used that so I'm not sure how it works. You might find that calling `init_printing()` at the start of your script gives the output that you want.
