### ISSUE TITLE
Equality between sqrt(x) and x**0.5 no longer holds in sympy 1.5

### ISSUE THREAD

**Issue by ngoldbaum** [sympy/sympy#18054]
Consider the following test script:

```
import sympy
x = sympy.Symbol('x', positive=True)
print(x**0.5 == sympy.sqrt(x))
```

In sympy 1.4 this prints `True` while on sympy 1.5 this prints `False`.

This regression is causing test failures in CI for yt's unit system, see https://github.com/yt-project/yt/pull/2395.

I get the same results without `positive=True`, I just included that because that's how we create symbols for yt's unit system.

**Comment by ngoldbaum** [comment]
bisected to https://github.com/sympy/sympy/pull/16924, ping @smichr

**Comment by oscarbenjamin** [comment]
To be clear this is a deliberate change. `Basic` instances should only compare equal if they are literally interchangeable but these are not since e.g.:
```julia
In [1]: x**.5 == sqrt(x)                                                                                                          
Out[1]: False

In [2]: (x**.5).subs(x, 10)                                                                                                       
Out[2]: 3.16227766016838

In [3]: sqrt(x).subs(x, 10)                                                                                                       
Out[3]: √10
```
In SymPy 1.4 there is a bug in hashing that hides this problem:
```julia
In [1]: x**.5 == sqrt(x)                                                                                                          
Out[1]: True

In [2]: hash(x**.5) == hash(sqrt(x))                                                                                              
Out[2]: False
```
That needed to be fixed so that sets and dicts of SymPy expressions (which are used ubiquitously in SymPy's internals and elsewhere) can work reliably. Fixing that would expose the problem that then `x**.5` and `sqrt(x)` become completely interchangeable and will be swapped out by the cache etc leading to inconsistent results that depend on evaluation order. So it becomes necessary to ensure that these compare unequal with `==`.

Ultimately what this comes down to is the fact that in SymPy `==` and `!=` are for *structural equality* which means that if `a==b` then `a` and `b` need to be the *exact* same expression which is a stronger requirement than being *mathematically* equal. If you want to test for mathematical (rather than structural) equality between float/non-float then there are other ways e.g.:
```julia
In [10]: a = x**.5                                                                                                                

In [11]: b = sqrt(x)                                                                                                              

In [12]: (a.evalf()).equals(b.evalf())                                                                                            
Out[12]: True

In [13]: Eq(a, b).evalf()                                                                                                         
Out[13]: True

In [14]: (a - b).evalf()                                                                                                          
Out[14]: 0

In [20]: nfloat(Eq(a, b), exponent=True)                                                                                          
Out[20]: True

In [21]: nfloat(a - b, exponent=True)                                                                                             
Out[21]: 0
```

**Comment by oscarbenjamin** [comment]
This wasn't listed in the backward compatibility problems in the release notes but I've added it now:
https://github.com/sympy/sympy/wiki/Release-Notes-for-1.5

**Comment by ngoldbaum** [comment]
OK, unfortunately we were using this behavior in yt’s unit system quite extensively. Users often create units that involve square roots. I’m not sure what path forward we have for this to ameliorate the breakage for our users but I guess I’ll think carefully about it if there’s no interest in upstream adding a special case for this.

**Comment by oscarbenjamin** [comment]
This is a general problem in SymPy because the behaviour of `==` needs to match the expectations of sets and dicts but SymPy is both implemented in *and used from within* Python. That means that our users are exposed to the same `==` that we need to use internally.

This is almost at the top of the gotchas page:
https://docs.sympy.org/latest/gotchas.html#double-equals-signs
and
https://docs.sympy.org/latest/gotchas.html#python-numbers-vs-sympy-numbers

Perhaps we need to add something there that explains this.

**Comment by oscarbenjamin** [comment]
I don't know yt at all. Can you explain what the problem is exactly?

**Comment by ngoldbaum** [comment]
The problem is that with sympy 1.4 and earlier, if someone does:

```
from yt.units.unit_object import Unit

u1 = Unit('km**0.5')
u2 = Unit('sqrt(km)')

print(u1 == u2)
```

You'll get `True`. Currently with sympy 1.5, you get `False`. Now you're telling me that going forward we'll need to add special cases for sympy 1.5 and newer to avoid this behavior change for our users. We don't have any control over what strings users pass to the `Unit` initializer (or end up there via other user-facing APIs).

**Comment by oscarbenjamin** [comment]
Rather than adding special cases I would use canonicalisation. If you want users to be able to use either of `sqrt` or `**0.5` interchangeably then those should be made to canonicalise to the same thing. These are not generally interchangeable in SymPy but if they should be interchangeable in yt then canonicalisation can do that.

SymPy has a number of methods for doing this but none of them works on `Unit` because it is effectively an `Atom` (has no args) even though `is_Atom` is `False`. I'm not sure how to access the internal SymPy representation of `Unit` but I would imagine that you could use `nsimplify` or `nfloat` on that during object creation.

**Comment by asmeurer** [comment]
I think the best solution for you would be to normalize float powers into rationals. If that's the only possible number you can use `nsimplify(rational=True)`. Otherwise you should be able to use a custom `replace` call to do it. 

Note that 0.5 and 1/2 only compare equal because 0.5 is exactly 1/2 as a floating point number. If you had for instance, 1/5 == 0.2, it wouldn't work:

```py
>>> 1/5
0.2
>>> 1/5 == Rational(1, 5)
False
```

It might work in previous versions of SymPy because they were looser with float inequality, but we've modified it so that floats only compare equal to rationals that they are exactly equal to. 

I'm not sure where the discussions are for why we have

```py
>>> 0.5 == Rational(1, 2)
True
>>> x**0.5 == x**Rational(1, 2)
False
```

outside of the PR you linked to. I think it's related to the mega-issue https://github.com/sympy/sympy/issues/11707, although I don't see anything about it specifically when scanning through it. 

But I guess it's for the reasons that @oscarbenjamin mentioned. I think there's no inconsistency there, although it is confusing. We have to have pure numbers be equal or else it breaks transitivity with comparisons against Python floats. For larger expressions that isn't a problem. The set and dict question specifically is still somewhat muddled by the fact that https://github.com/sympy/sympy/issues/11707 is still unfixed, in terms of the hash of numeric types.

**Comment by ngoldbaum** [comment]
I don’t think we can easily use `nsimplify` for performance reasons but I will check.

**Comment by asmeurer** [comment]
If you are parsing strings with `sympify` or `parse_expr` you can also use `rational=True`. If there's a major performance issue with one of these things we should investigate if it can be improved.

**Comment by oscarbenjamin** [comment]
Also if you are only interested in powers that can be represented exactly in binary (like half-integers) then you can use:
```julia
In [63]: expr = x**0.5                                                                                                            

In [64]: expr.xreplace({a: Rational(a) for a in expr.atoms(Float)})                                                               
Out[64]: √x
```
You need `nsimplify` for something like `0.33333333333333`.

While looking at this I just found a bug that comes from allowing Floats and Rationals to compare equal:
```julia
In [67]: expr.replace(lambda e: e.is_Float, lambda e: 3)  # Fine                                                                        
Out[67]: 
 3
x 

In [68]: expr.replace(lambda e: e.is_Float, lambda e: Rational(e)) # No replacement done!
Out[68]: 
 0.5
x 
```
Here I think that replace has rejected the substitution because `Rational(0.5) == 0.5`.

**Comment by smichr** [comment]
A workaround for the replacement failure is
```python
>>> eq
>>> d=Dummy()
>>> eq.replace(
... lambda x:x.is_Float,
... lambda x:Rational(x)*d).xreplace({d:1})
sqrt(x)
```

**Comment by smichr** [comment]
> I'm not sure where the discussions are for why we have

I was a little puzzled by this, too, because I thought the rule was simply that Floats are never equal to Rational. But I believe the logic is that Rational is equal to a Float when they are exactly the same at any level of precision, i.e. when the Rational has a denominator that is a nonnegative power of 2:
```python
>>> .125==Rational(1,8)
True
```

**Comment by asmeurer** [comment]
I found some of the other conversation. https://github.com/sympy/sympy/pull/16770, particularly around https://github.com/sympy/sympy/pull/16770#issuecomment-489814987.

**Comment by oscarbenjamin** [comment]
@ngoldbaum did you work out a solution to this?

**Comment by ngoldbaum** [comment]
No I haven’t worked on this yet. I’ll let you know when I do.

**Comment by ngoldbaum** [comment]
It turns out I was using the `rationalize` transformer for `parse_expr` incorrectly. I was using `rationalize`, but I had my transformers set up so `auto_number` came after `rationalize`, so the floats never got transformed to rational numbers. I think I can adequately fix this on the unyt side of things. Sorry for all the noise on this issue :)

**Comment by oscarbenjamin** [comment]
Glad you got it sorted and thanks for letting us know!
