### ISSUE TITLE
Why pretty print of "oo - oo" has result  "nan", if the evaluation is disabled?

### ISSUE THREAD

**Issue by satels** [sympy/sympy#18052]
```python
from sympy import evaluate, oo, pretty

with evaluate(False):
    print(pretty(oo-oo))
```

**Comment by satels** [comment]
Also with oo - 5, for instance

**Comment by namannimmo10** [comment]
> Also with oo - 5, for instance

No, it prints oo in that case :)

**Comment by ShubhamKJha** [comment]
The documentation of `evaluate` says:
`Note that much of SymPy expects evaluated expressions.  This functionality is experimental and unlikely to function as intended on large expressions.`

Nonetheless, it happens because `evaluate` affects the auto-evaluations in `Add` (inherited from `Basic`) but in both the above cases `oo`(`S.Infinity`) 's `__add__` function is called, no Add object is generated, and the evaluated result is given.

One interesting case,
```py
>>> with evaluate(False):
...     print(S(5)+oo)
...     print(oo+S(5))
...
5 + oo
oo
```

One possible approach would be update the code in `__add__` (and other functions) in `S.Infinity` so that `Add` is called and `evaluate` is acknowledged. It should be easy to fix.

**Comment by namannimmo10** [comment]
Hi @ShubhamKJha . I'm willing to work on this issue 
I need some help cause this is my first time dealing with such a huge codebase. Can you explain the steps a little more?

**Comment by oscarbenjamin** [comment]
The `__add__` method here ignores `global_evaluate`. It could be made to check `global_evaluate` but I actually think a better solution would be to remove the `__add__` method and let `Add.flatten` handle (or not handle) this logic:
```julia
In [1]: with evaluate(False): 
   ...:     pprint(Add(oo, -oo)) 
   ...:                                                                                                                                                       
-∞ + ∞
```

**Comment by ShubhamKJha** [comment]
Hi @namannimmo10, if you are contributing for the first time read [this](https://github.com/sympy/sympy/wiki/Introduction-to-contributing)

And  as @oscarbenjamin suggested start with removing `__add__` method in `sympy.core.numbers.Infinity` class, [test it](https://github.com/sympy/sympy/wiki/Running-tests) and send a PR.
