### ISSUE TITLE
Add .evalf() method to sympy.physics.vector.Vector and Dyadic

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#18064]
These two classes are missing many of the core SymPy methods because they do not inherit from the core SymPy classes. It would be nice to add them, starting with `.evalf()`.

**Comment by oscarbenjamin** [comment]
Working on #18053 I've had to add methods like `expand` and `integrate` to `Relational` since it won't inherit them from `Expr` any more. That makes me wonder whether there should be a mixin class like `HasExprMixin` that defines methods for non-`Expr` classes that contain `Expr` args. Then all of `.expand`, `.evalf`, `.n`, `.simplify`, `.diff` etc can be defined there and easily inherited by the classes where those methods make sense.

**Comment by moorepants** [comment]
A mixin could be very nice to have. Sounds like a good broad solution. My long term goal is to create a immutable physics.vector too.

**Comment by oscarbenjamin** [comment]
There is already a mixin for evalf btw:
https://github.com/sympy/sympy/blob/520f0d1a77f180cf02f7f97b132f1974253dd274/sympy/core/evalf.py#L1366-L1371
That's how `Expr` gets its `evalf` method:
```julia
In [1]: Expr.mro()                                                                                                                
Out[1]: 
[sympy.core.expr.Expr,
 sympy.core.basic.Basic,
 sympy.core.evalf.EvalfMixin,
 object]
```

**Comment by oscarbenjamin** [comment]
However there are a lod of other `Expr` methods that could be useful on various non-`Expr` classes:
https://github.com/sympy/sympy/blob/520f0d1a77f180cf02f7f97b132f1974253dd274/sympy/core/expr.py#L3485-L3489

**Comment by lakshay-angrish** [comment]
What additional things are to be done after `Vector`, `ReferenceFrame` and `Dyadic` inherit the `EvalfMixin` class?

**Comment by moorepants** [comment]
ReferenceFrame should not have these methods added.

**Comment by lakshay-angrish** [comment]
Once we make `Vector` and `Dyadic` inherit the `EvalfMixin` class, what are the steps to integrate the `evalf()` method?

**Comment by oscarbenjamin** [comment]
That's probably all that is needed to make it work but you'd have to try it to see. There will also need to be some tests to see that it works as expected.

**Comment by Saanidhyavats** [comment]
I want to contribute on this issue. Is this issue still open?

**Comment by mohitacecode** [comment]
where I can find the implementation of .factor ?

**Comment by YashAgrawal0** [comment]
I want to contribute on this issue. Is this issue still open?

**Comment by Saanidhyavats** [comment]
I am interested to take up this issue, how shall I start?

**Comment by Saanidhyavats** [comment]
I am thinking to make a separate function for evalf() in `sympy.physics.vector.Vector` like in `sympy.core.function`

**Comment by oscarbenjamin** [comment]
Take a look at how `evalf` and the `EvalfMixin` works for other types if you want to work on this. 

Note that I've removed the easy to fix label because there have already been two failed attempts at fixing this issue. I suspect that it is somehow harder than it looks because of the design of the vector module.

**Comment by Saanidhyavats** [comment]
I will have a look into it.

**Comment by sylee957** [comment]
Indeed, I see this can rather be a difficult issue because I can't see a clean documentation about how `Vector.args` is structured to be.

If I am correct that vector.args should either a list of `Matrix, ReferenceFrame` or an empty list, it should be working like

```diff
diff --git a/sympy/physics/vector/vector.py b/sympy/physics/vector/vector.py
index 888e91a54c..e85dfbb57e 100644
--- a/sympy/physics/vector/vector.py
+++ b/sympy/physics/vector/vector.py
@@ -2,12 +2,13 @@
     ImmutableMatrix as Matrix)
 from sympy import trigsimp
 from sympy.core.compatibility import unicode
+from sympy.core.evalf import EvalfMixin, prec_to_dps
 from sympy.utilities.misc import filldedent

 __all__ = ['Vector']


-class Vector(object):
+class Vector(EvalfMixin):
     """The class used to define vectors.

     It along with ReferenceFrame are the building blocks of describing a
@@ -52,6 +53,21 @@ def __init__(self, inlist):
             if v != Matrix([0, 0, 0]):
                 self.args.append((v, k))

+    @property
+    def func(self):
+        return Vector
+
+    is_number = False
+
+    def _eval_evalf(self, prec):
+        if not self.args:
+            return self
+
+        new_args = []
+        for mat, frame in self.args:
+            new_args.append([mat.evalf(n=prec_to_dps(prec)), frame])
+        return Vector(new_args)
+
     def __hash__(self):
         return hash(tuple(self.args))

(END)
```
I've only tested with `(ReferenceFrame('R').x * pi).evalf()`.
But whatever, introducing `Evalf` to non-basic types would not look a clean introduction.

**Comment by sidhu1012** [comment]
Is this issue still up?

**Comment by sidhu1012** [comment]
I would like to work on this issue. I have seen previous work on this issue. This issue should be solved by inheritance or evalf function should be independently added to class?
