### ISSUE TITLE
Are `is_closed, is_open` of `S.Rationals`'s properties valid?

### ISSUE THREAD

**Issue by Cartman0** [sympy/sympy#18134]
currently, there properties `is_closed, is_open` aren't initialized .

```python
from sympy import S

S.Rationals.is_closed, S.Rationals.is_open
> True, None
```

if there properties are thought wheather Q(S.Rationals) is open or closed set in R (S.Reals), should return `is_open=False` and `is_closed=False`.
if use there properties as undefined, should return a exception `Not Implemented Error` ?

**Comment by oscarbenjamin** [comment]
Generally in SymPy `is_` properties return fuzzy-bools which use 3-way logic: True, False or None. None means that the the answer to the question is not known. Often that is because the code to answer the question has not been written/implemented.

Right now the `is_closed` property returns `self.boundary.is_subset(self)` and for rationals we have
```
In [1]: Rationals                                                                                                                                             
Out[1]: ℚ

In [2]: Rationals.boundary                                                                                                                                    
Out[2]: ℚ

In [3]: Rationals.boundary.is_subset(Rationals)                                                                                                               
Out[3]: True
```
Either Rationals.boundary should not be the Rationals or the `is_closed`
 method should be changed in general.

The `is_open` method returns True if `Intersection(self, self.boundary)` gives the empty set and None otherwise. That's why we get a None in this case.

**Comment by gschintgen** [comment]
> Either Rationals.boundary should not be the Rationals or the `is_closed`
> method should be changed in general.

I'd have expected the open/closed answers for subsets of the reals to be based on the topology on R. Otherwise (i.e. if the Rationals, Integers etc. were considered to be their own topological spaces) they'd all simply have to be considered open and closed by definition.

So that would mean `Rationals.boundary == Reals` (difference of closure(Q)=R and interior(Q)=empty).
It follows that Q is neither open nor closed.

I'm not a topologist though and my topology courses date back some time...

Do note that the docs for `is_open` and `is_closed` don't actually specify the topology, so that should be amended too.

**Comment by Cartman0** [comment]
@oscarbenjamin thx. 

>Generally in SymPy is_ properties return fuzzy-bools which use 3-way logic

i knew for first time. is it written in doc?

**Comment by Cartman0** [comment]
because of being different whether the set is closed or open  by universal set, 
there properties may have to change to methods with arg `universal_set`.

**Comment by Cartman0** [comment]
@gschintgen 
Rationals set does not have irrational numbers. can boundary of rationals set be Reals ?

**Comment by jksuom** [comment]
> can boundary of rationals set be Reals 

A boundary point does not have to belong to the set. Consider, for example, the boundary of an open interval.

**Comment by Cartman0** [comment]
ok. but i cant imagine.. 

irrational number i in Reals, then consider neighber N(i).
do neighbers holds this eq
(N(i) and Q neq emp) and (N(i) and Qc neq emp) exist?
