### ISSUE TITLE
How to find roots numerically?

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#18177]
There is no analytic algorithm for `2^x+3^x=5^x`, but there is root `x=1`. How to find it?
Preferably, without setting initial point.

**Comment by smichr** [comment]
The solution of `x=1` for `eq = 2**x + 3**x - 5**x` is trivial in this case. If you didn't know that it was the solution, however, you could plot it and see that it crosses somewhere near 1 so use that as an initial guess: `nsolve(eq, 1) -> 1.000`. You could then confirm that 1 is exactly a solution with `eq.subs(x,1) -> 0`.

It might be nicer to graph the log form of the equation: `log(2**x + 3**x) - x*log(5)`. This form is better behaved with `nsolve`, too since it is relatively far from the x axis everywhere except near the root. So whereas `nsolve(eq,0)` gives -53.49 (and a solution near 1 is not obtained until the initial guess is greater than 0.06) with the alternate "log form" the solution is found from almost any starting point.

Using bisection with the original form of the equation will work, however:
```python
>>> nsolve(eq,(0,2),solver='bisect')
1.00000000000000
```

**Comment by proy87** [comment]
@smichr , thank you.

**Comment by proy87** [comment]
@smirch , is there some approach, when we don't need to enter an interval? Because I don't know anything about it in advance.

**Comment by smichr** [comment]
Not that I know of *in general*. It all depends on how the function behaves in the vicinity of the root. The log form I showed is extremely well behaved and you could guess almost anything to get the root-solving process started. Graphing is a good first step for learning about a function.

**Comment by proy87** [comment]
@smichr , thank you very much!
