### ISSUE TITLE
SymPyExpression documentation not rendering

### ISSUE THREAD

**Issue by Sc0rpi0n101** [sympy/sympy#18219]
The documentation for SymPy Expressions is not rendering in https://docs.sympy.org/latest/modules/parsing.html as it uses 
```python
class SymPyExpression(object):
        def __init__(self, *args, **kwargs):
            raise ImportError('Module not available.')
```
as the source and not 
https://github.com/sympy/sympy/blob/7f92c96417d066700d096105282d6fe47ea085ef/sympy/parsing/sym_expr.py#L20 

Also, I think I should remove the Fortran Parsing Reference from the docs as it is a backend implementation and the users will not interact with the Module.

**Comment by sagnik-chatterjee** [comment]
can i take up this issue ?

**Comment by asmeurer** [comment]
There are some internal things in the docs. As long as we specify that is the case it is fine. But if you think we should remove it that is fine too. Otherwise, we should make sure lfortran is installed when we build the docs. This should be fixed on Travis for the dev docs and in the release script for the release docs.

**Comment by asmeurer** [comment]
Another way would be to refactor it so the class is defined at the top level. The lfortran imports would go inside the methods. Rerasing ImportError with "module not available" isn't very helpful (actually less helpful than the default message), so I don't think we need to keep that.

**Comment by Sc0rpi0n101** [comment]
I have created a PR #18741  with the fix. 
The documentation for SymPyExpression rendered correctly in my local build.
