### ISSUE TITLE
list of Union just hangs

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#18232]
`list(Union(ImageSet(Lambda(n, 2*n), Integers), ImageSet(Lambda(n, 3*n), Integers)))` hangs.

**Comment by gschintgen** [comment]
Are you sure it's stuck? I'd guess it does what is asked for: iterating through the given set in order to create a regular Python `list`. And since the set is infinite this could take a while :-)

To create a (finite) list, you could intersect the set with e.g. `Interval(-100, 100)`:
```
list(Union(ImageSet(Lambda(n, 2*n), Integers), ImageSet(Lambda(n, 3*n), Integers)).intersect(Interval(-100,100)))
```
Whenver possible Sympy sets can be iterated through. It's up to the user / the calling code to avoid an infinite loop.

**Comment by proy87** [comment]
I see. I thought it should output just two imagesets.
