### ISSUE TITLE
sympy.stats: Die distribution being treated as continuous?

### ISSUE THREAD

**Issue by Alex-Linhares** [sympy/sympy#18260]
The following code snippet suggests that the Die distribution is being treated as continuous:

```
from sympy.stats import Die, P
X, Y = Die('X', 6), Die('Y', 6)  

print (P(X+Y<7))
print (P(X+Y>7))

print (P(X+Y==7)) 
```
output is the following:

```
5/12
5/12
0
```

**Comment by gschintgen** [comment]
I've never used the stats module, but I do think that should be `P(Eq(X + Y), 7)` (which gives the correct result `1/6`) instead of `X + Y == 7` which, even by itself, evaluates to `False` and `P(False)` returns 0.

In Sympy `==` is for checking syntactic equality, while mathematical equality is expressed using `Eq()`.

**Comment by Alex-Linhares** [comment]
Sorry, my mistake! 

    print (P(Eq(X+Y,7))) 

computes correctly.  Thank you!  Closing this now.
