### ISSUE TITLE
Why powdenest deletes sing?

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#18297]
`powdenest(-sign(x), force=True)` returns `-1`. Why is that?

**Comment by Mohitbalwani26** [comment]
According to documentation, if `force = True` is written while calling `powdenest` then symbols that are not explicitly negative behave as though they are positive, resulting in more denesting. And for your example` -sign(x)` will give `-1` which then will be treated as positive due to `force = True`

**Comment by proy87** [comment]
@Mohitbalwani26 , thank you.
