### ISSUE TITLE
Assume real root in limit

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#18363]
`Limit(((x - 6)**(Integer(1)/3) + 2)/(x + 2),x,-2,'-').doit()` returns `-oo*sign(2+2*(-1)^(1/3))`. How to make it real-valued?

**Comment by gschintgen** [comment]
This is independent of `limit`.

You can use `real_root` though:
https://docs.sympy.org/1.5.1/modules/functions/elementary.html#sympy.functions.elementary.miscellaneous.real_root

```
In [1]: limit((real_root(x - 6, 3) + 2)/(x + 2), x, -2, '-')
Out[1]: 1/12
```

**Comment by proy87** [comment]
@gschintgen , got some weird answer for right-hand limit: `limit((real_root(x - 6, 3) + 2)/(x + 2), x, -2, '+')` is `2*Subs(Derivative(sign(_x - 8), _x), _x, 0) + 1/12`

**Comment by gschintgen** [comment]
Manually rewriting the root does the trick:
```
In [6]: l = Limit((-(6 - x)**(Integer(1)/3) + 2)/(x + 2),x,-2,'-'); l
Out[6]:
      ⎛    3 _______⎞
      ⎜2 - ╲╱ 6 - x ⎟
 lim  ⎜─────────────⎟
x─→-2⁻⎝    x + 2    ⎠

In [7]: _.doit()
Out[7]: 1/12
```

So the piecewise expression returned by `real_root` is not quite amenable to all operations, in particular derviatives and `sign` don't seem to mix well. For reference:
```
In [8]: real_root(x - 6, 3)
Out[8]:
⎧3 _________
⎪╲╱ │x - 6│ ⋅sign(x - 6)  for im(x) = 0
⎨
⎪       3 _______
⎩       ╲╱ x - 6            otherwise
```

I think the underlying issue is has to do with this: if `x` is real computing the diff is no problem:
```
In [16]: diff(sign(x-8))
Out[16]: 2⋅δ(x - 8)

In [17]: diff(sign(x-8)).subs(x, 0)
Out[17]: 0
```
But if I set `x` to be real before calling `limit`, this assumption is lost (or discarded on purpose?) when the `Dummy` in the diff.subs is created. And then we're left with the behavior for a general complex variable:
```
In [18]: diff(sign(y-8))
Out[18]:
d
──(sign(y - 8))
dy

In [19]: _.subs(y, 0)
Out[19]:
⎛d              ⎞│
⎜──(sign(y - 8))⎟│
⎝dy             ⎠│y=0
```
Since I'm not at all familiar with this part of the codebase that's as far as I'm going with this.

**Comment by gschintgen** [comment]
Also noteworthy:
```
In [26]: var('x', real=True)
Out[26]: x

In [27]: l = Limit((real_root(x - 6, 3) + 2)/(x + 2), x, -2, '+'); l
Out[27]:
      ⎛3 _________                ⎞
      ⎜╲╱ │x - 6│ ⋅sign(x - 6) + 2⎟
 lim  ⎜───────────────────────────⎟
x─→-2⁺⎝           x + 2           ⎠
```
A simple substitution of x = -2 would reveal that both `abs` and `sign` could be simplified even before the actual limit computation. But substitution is a dangerous idea in a limit computation, so I'm not sure if this will lead anywhere...

**Comment by proy87** [comment]
@gschintgen , thank you for the thorough answer.

**Comment by sachin-4099** [comment]
@gschintgen @jksuom Is there anything left to handle in this issue?

**Comment by gschintgen** [comment]
> 
> 
> @gschintgen @jksuom Is there anything left to handle in this issue?

Yes, this:
```
In [1]: limit((real_root(x - 6, 3) + 2)/(x + 2), x, -2, '+')
Out[1]:
  ⎛d              ⎞│      1
2⋅⎜──(sign(x - 8))⎟│    + ──
  ⎝dx             ⎠│x=0   12
```
The first term shouldn't be there: it equals zero.
