### ISSUE TITLE
Confusing test cases in test_classify_diop

### ISSUE THREAD

**Issue by ethankward** [sympy/sympy#18370]
We have these two test cases:

```
assert classify_diop(x*y + z) == (
        [x, y, z], {x*y: 1, z: 1}, 'inhomogeneous_ternary_quadratic')
assert classify_diop(x*y + z + w + x**2) == (
        [w, x, y, z], {x*y: 1, w: 1, x**2: 1, z: 1}, 'inhomogeneous_general_quadratic')
```

In what way are these equations "inhomogeneous"?

**Comment by gschintgen** [comment]
Unfortunately it would not be the first time that dubious test results made their way into the test suite...

I'd say the tests you cited are bugs in `classify_diop`. (Or at least badly chosen default names for some classes of equations that diophantine is not currently capable of solving.) IMO it should be fixed.

**Comment by mohitacecode** [comment]
hey how x*y+z & x*y + z + w + x**2 are homogeneous? I am considering this defination "A polynomial is homogeneous if all its terms have the same degree".

**Comment by gschintgen** [comment]
Oops, I retract my previous comment. I was probably thinking of linear equations where homogeneity reduces to the presence or absence of a constant term.

**Comment by mohitacecode** [comment]
is this issue still valid?

**Comment by ethankward** [comment]
`homogeneous` clearly is referring to the presence of a constant term here:

https://github.com/sympy/sympy/blob/9f98339b3344de9109f4d2780faf9822fb110848/sympy/solvers/diophantine.py#L497

Here the code checks that `homogeneous` is true and then immediately returns an inhomogeneous equation type:

https://github.com/sympy/sympy/blob/9f98339b3344de9109f4d2780faf9822fb110848/sympy/solvers/diophantine.py#L507-L509

**Comment by mohitacecode** [comment]
In general,we look for the coefficient only in the case of linear equation which look like this `a1x1+a2x2+...+anxn=b` but  ` xy+z & xy + z + w + x**2 are polynomial` in which the only thing that matters is the degree should be same for all the term.

**Comment by mohitacecode** [comment]
This is why we look for constant to be zero in linear equation 
`A homogeneous linear equation, say, 2x+3y+5z=0, is really special because it has an important property: if (x,y,z) is a solution then (λx,λy,λz) is also a solution for arbitrary constant factor λ. If you replace 0 in the right hand side of the equation by a non-zero constant, and get, say, 2x+3y+5z=1, this property is lost.`

**Comment by gschintgen** [comment]
@ethankward :
> `homogeneous` clearly is referring to the presence of a constant term here:
> 
> https://github.com/sympy/sympy/blob/9f98339b3344de9109f4d2780faf9822fb110848/sympy/solvers/diophantine.py#L497

Logically that boolean variable expresses `possibly_homogeneous` and not (definitely) `homogeneous`.

> Here the code checks that `homogeneous` is true and then immediately returns an inhomogeneous equation type:
> 
> https://github.com/sympy/sympy/blob/9f98339b3344de9109f4d2780faf9822fb110848/sympy/solvers/diophantine.py#L507-L509

As I understand it, the intersection of `set(coeff)` and `set(var)` is non-empty (hence the `if`-condition true) exactly when a "naked" element of `var` appears in the expression, i.e. a term of degree 1. But the total degree in this case is 2, so in order to have a properly homogeneous polynomial all terms would have to be of degree 2, which is not the case. Hence the equation is indeed inhomogeneous.

The naming of the `homogeneous` variable is indeed unfortunate... But the logic of that excerpt seems valid.

**Comment by asmeurer** [comment]
The ode module also makes use of both meanings of "homogeneous" and calls the uniform degree version "homogenous order" https://docs.sympy.org/1.5.1/modules/solvers/ode.html#homogeneous-order

**Comment by mohitacecode** [comment]
We can also add new things such as whether polynomia is symmetric or not?
I am not sure that whether sympy contain a module or method for `Elementary Symmetric Polynomials`
If not then I think we can add that functionality too. @asmeurer 

`Elementary Symmetric Polynomials` = https://en.wikipedia.org/wiki/Elementary_symmetric_polynomial

**Comment by jksuom** [comment]
Elementary symmetric polynomials can be generated by means of `symmetric_poly()` (implemented in `polys.special`).

**Comment by mohitacecode** [comment]
I think `symmetric_poly()` only generate symmetric polynomial which is different from elementary symmetric polynomial.

`symmetric polynomial ` = if any of the variables are interchanged, one obtains the same polynomial
`Elementary Symmetric Polynomial` =  https://wikimedia.org/api/rest_v1/media/math/render/svg/79c403b205db7fa3b12a12d3504533a231eae9be
