### ISSUE TITLE
get equation from latex

### ISSUE THREAD

**Issue by vainaijr** [sympy/sympy#18404]
When I use google colab, then it gives latex in documentation, I want to see the mathematical formula for this latex, how do I use sympy to do it.

I know how to get latex from equation, but how do I get equation from latex?

for example,
```
import torch
torch.nn.Sigmoid??
```
gives docs which includes
```
\text{Sigmoid}(x) = \frac{1}{1 + \exp(-x)}
```
now how do I convert this latex into mathematical equation using sympy?

**Comment by sylee957** [comment]
Use parse_latex
```python3
from sympy import *
from sympy.parsing.latex import parse_latex

parse_latex(r'\text{Sigmoid}(x) = \frac{1}{1 + \exp(-x)}')
```
![image](https://user-images.githubusercontent.com/34944973/72703083-fda87e80-3b97-11ea-9e3d-93edcd98c6f1.png)
```python3
parse_latex(r'\Sigmoid(x) = \frac{1}{1 + \exp(-x)}')
```
![image](https://user-images.githubusercontent.com/34944973/72703116-19138980-3b98-11ea-974b-95fd2f41443d.png)

But I cannot guarantee that it will always parse into something accurate, since LaTeX itself doesn't have well-defined syntax for every math. But if there are some bugs, let's see
