### ISSUE TITLE
Floor and ceiling functions are returning floats for zero

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#18421]
```python3
>>> floor(float(0))
0.0
>>> ceiling(float(0))
0.0
```

**Comment by oscarbenjamin** [comment]
This should return `Integer` rather than `Float`. Looks like the logic here needs to be changed:
https://github.com/sympy/sympy/blob/72cfe65d174931103781042fd8b94ba2e2290904/sympy/functions/elementary/integers.py#L21-L34
I guess that `_eval_number` should be called first.

**Comment by abhinav28071999** [comment]
I am taking this issue.

**Comment by AI-Beg** [comment]
If the output to be in integer type , we could write it as
int(floor(float(0)))
0
int(ceiling(float(0)))
0
then output is coming in integer type as zero

**Comment by YashAgrawal0** [comment]
@AI-Beg, I think we can return integer value in the "floor" class itself as floor is supposed to return integer value only, so every time after computing the result we can return int() of that result instead of doing that outside the class.

After going through the code I think another approach for the issue could be that we can put an if-else statement for the input 0.0 because for other inputs its working fine.

@oscarbenjamin, @AI-Beg  what'd you suggest?

**Comment by oscarbenjamin** [comment]
`Floor.__new__` should return `Integer` (note that this is not the same as `int`)

**Comment by YashAgrawal0** [comment]
@oscarbenjamin  
Can't we use ```Integer(returnValue)``` in Floor? 
```Integer``` in sympy has this utility to make integer for the input float like ```Integer(0.0) = 0 ```.

**Comment by ShubhamKJha** [comment]
This appear to happen because `Float(0)` is being considered an integer and hence returned as it is in the first step. This doesn't happen for other such floats.
```py
>>> k = Float(0)
>>> k.is_integer
True
>>> p = Float(1)  
>>> p.is_integer
False
```

The reason here is -  `zero` assumption eventually infers `integer` in the codebase.
```py
>>> x = symbols('x', zero=True)
>>> x.is_integer
True
>>> Float(0).is_zero
True
>>>
```
These lines should be changed. (Here `zero -> even -> integer` )
https://github.com/sympy/sympy/blob/8a7dc8ef786cccbd7dc0fe0b0e6beec4dd1f7b49/sympy/core/assumptions.py#L176
https://github.com/sympy/sympy/blob/8a7dc8ef786cccbd7dc0fe0b0e6beec4dd1f7b49/sympy/core/assumptions.py#L202

IMO, the second line should be changed to ` zero & integer -> even & finite`.
