### ISSUE TITLE
Bug in limit

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#18473]
`limit(cos (x)**(1/x),x,oo)` should give `AccumBounds` instead of `1`.

**Comment by smitgajjar** [comment]
@oscarbenjamin Can I add fail test on this issue? I am trying to learn contributing here

**Comment by smitgajjar** [comment]
No, correct answer is 1 only!

**Comment by smitgajjar** [comment]
@oscarbenjamin 
=> lim x->oo (e**(ln(cos(x)**(1/x))))
=> lim x->oo (e**(ln(cos(x)/x)))
Taking limits in denominator and numerator at the exponent,
we get limx->oo (1/x) as one of the term at the exponent making it zero
Hence, we get e**0 = 1

**Comment by Saanidhyavats** [comment]
@proy87 I think that @smitgajjar is correct as cos(x) will take the value between (-1,1) and 1/x will approach to 0 as x tends to oo hence the result will be 1

**Comment by gschintgen** [comment]
The OP may not have elaborated on it, but I do think the criticism is correct.

By definition of `f(x)**g(x)`, the given limit is equivalent to
`limit(exp(ln(cos(x))/x, x, oo)` (1)
as already pointed out by @smitgajjar .

Now consider the following sequence of reals:
`x_k = pi/2 + k*2*pi - h`,
where `h` is a fixed but very small positive real. They all have the same image by `ln(cos(x))`. As `h` is made smaller and smaller, this value `ln(cos(x_k))` can be made arbitrarily small, i.e. it can be made to approach `-oo` since `cos` goes to 0. But this is neglecting the fact that the denominator `x` in (1) is increasing as `x->oo`. So we make `h` depend on `k` such that `ln(cos(x_k))` goes faster to `-oo` than `x` goes to `+oo`. Think `h=exp(-k**2)`. (Indeed, `cos(pi/2 - eps) ~ eps` and the `ln` cancels the `exp`.)

In that case `limit(ln(cos(x_k))/x_k, k, oo) == -oo` and with `exp` it goes to 0. Hence the original limit can't be 1 and only 1. The correct answer should be `AccumBounds(0, 1)`. (Other values in (0, 1) can be proven to be accumulation points by letting `h=exp(-a*k)` for some `a`.)

P.S. I wish it was possible to write LaTeX in these comment fields...

**Comment by anutosh491** [comment]
> => lim x->oo (e ** (ln(cos(x))/x))
> Taking limits in denominator and numerator at the exponent,
> we get limx->oo (1/x) as one of the term at the exponent making it zero
> Hence, we get e**0 = 1

Well I guess you forgot to consider that ln(cos(x)) will be 0  multiple times , which won't allow you to have the exponent as 0 that easily . Yes this should be returning in terms of Accumbounds

**Comment by anutosh491** [comment]
I am failing to decipher logically what is responsible for the error but i'll still list down what I think might be involved!

Now for any expression involving exponentiation of something like suppose `exp(sin(x))` we first evaluate the leading_term of the passed argument `sin(x).as_leading_term(x)` which gives `x`, then we substitute `0` for any `x` in the output and we finally return 
`exp((x).subs(x, 0))` which gives us `1` for `exp(sin(x)).as_leading_term(x)`

Similarly in this case we encounter `exp(x*log(cos(1/x)))`
```
>>> (log(cos(1/x))).as_leading_term(x)
log(AccumBounds(-1, 1))

>>> (x*log(cos(1/x))).as_leading_term(x)
x*log(AccumBounds(-1, 1))

>>> (x*log(cos(1/x))).as_leading_term(x).subs(x, 0)
0
>>> exp(x*log(cos(1/x))).as_leading_term(x) # nothing but exp(0)
1
```
I'm not exactly able to understand where does this go wrong logically as I'm not able to accuse the results at any step . Maybe @jksuom could guide us regarding what might not be working as expected in this case

**Comment by jksuom** [comment]
It seems that the limit does not exist so 1 is not correct. On the other hand, AccumBounds cannot be the answer as it is real while log(cos(1/x)) is complex when cos(1/x) is negative. So it seems that the result should be NaN (or unevaluated). Also the leading term should be NaN.

**Comment by anutosh491** [comment]
True , I had given a thought along this direction but then I just wasn't sure how `AccumBounds` should be behaving in the case above ! For eg
```
>>> sin((AccumBounds(-1, 1))
AccumBounds(-sin(1), sin(1))

>>> log((AccumBounds(-1, 1))
log(AccumBounds(-1, 1))
```
So expressions move inside wherever they have scope and I guess `self` is returned whenever that isn't possible but something like the following would raise an error 

```
>>> AccumBounds(log(-1), log(1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\anuto\sympy\sympy\sympy\calculus\accumulationbounds.py", line 193, in __new__
    raise ValueError("Only real AccumulationBounds are supported")
ValueError: Only real AccumulationBounds are supported
```
So Shouldn't the above return a similar error too ! I guess there is a check whether log could come in and when there is an error self is returned but even that doesn't seem correct as the idea is similar to this one above . Maybe we can return the same error ?

**Comment by anutosh491** [comment]
I fixed the `as_leading_term` error to give `NaN` for the above locally but still it goes through `gruntz` to give `ValueError` and then `heuristics` from where we get 1 because we evaluate the limits for args of  `cos(1/x)**x` as `x` tends to `0` seperately and then club them!
So the following is happening
```
>>> limit(cos(1/x), x, 0)
AccumBounds(-1, 1)
>>> limit(x, x, 0)
0
```
These are appended in a list using loop (line 88 - 106)
```
        r = []
        for a in e.args:
            l = limit(a, z, z0, dir)
            ...........
            ...........
            else:
                r.append(l)
```
hence `r = [AccumBounds(-1, 1), 0]` and we finally return `e.func(*r)`
```
>>> (cos(1/x)**x).func(*[AccumBounds(-1, 1), 0])
1
```
Not sure how could we justify this ! I haven't dealt with limits which go through `heuristics` yet hence It is a bit tough to say which functions do we expect to go through heuristics and whether this should be going through it ! @jksuom @0sidharth

**Comment by anutosh491** [comment]
@jksuom could you educate me regarding when should `heuristics` not return `1` when we have when have something like 
`limit(expr1**expr2, x, 0)` when `limit(expr1, x, 0)` is `AccumBounds(-1, 1)` and `limit(expr2, x, 0)` being `0`. Like I wrote above
https://github.com/sympy/sympy/issues/18473#issuecomment-1019021992 in cases like 
`limit(cos(1/x)**x, x, 0)` and `limit(sin(1/x)**x, x, 0)` it shouldn't but I can see general cases where it can be useful . I don't think heuristics should be responsible or rather allowed to solve this but what is differentiating factor between these cases and some general ones .
As you had pointed out , I locally could address this ! but still can't create the Pr as `heuristics` isn't supporting my case 
>>It seems that the limit does not exist so 1 is not correct. On the other hand, AccumBounds cannot be the answer as it is real while log(cos(1/x)) is complex when cos(1/x) is negative. So it seems that the result should be NaN (or unevaluated). Also the leading term should be NaN.

**Comment by jksuom** [comment]
Ideally, all heuristics should come before calling `gruntz` so the current `heuristics` should not be relied upon too much.

The leading term (and limit) of a power like `cos(1/x)**x` is computed by passing to `exp(x*log(cos(1/x)))`. it seems that the leading term of `log(cos(1/x))` should be NaN, and that should probably also be the limit of `cos(1/x)**x`.
