### ISSUE TITLE
integrate((cos(x)/(4+(sin(x))**2)), manual=True) gives the wrong answer

### ISSUE THREAD

**Issue by meganly** [sympy/sympy#18527]
Integrating with manual=True incorrectly adds an absolute value sign to the answer.
```
>>> x = symbols('x', real=True)
>>> expr = (cos(x)/(4+(sin(x))**2))
>>> integrate(expr, x, manual=True)
atan(Abs(sin(x))/2)/2
>>> integrate(expr, x)
atan(sin(x)/2)/2
```

**Comment by asmeurer** [comment]
The real=True is important. Without it gives the right answer.

**Comment by smichr** [comment]
In `eval_u` a print statement reveals the following substitutions:
```
for atan(_u/2)/2, _u->sqrt(_u)
for atan(sqrt(_u)/2)/2, _u->sin(x)**2
```
And with real `x`, that last one gives `atan(Abs(sin(x))/2)/2`

**Comment by smichr** [comment]
The `Abs` is coming from `Pow._eval_power` when a base to an even power is being raised to a non-integer power, e.g. `(x**2)**(S(3)/2) -> x**2*Abs(x)`; without using `Abs` the expression would be unchanged. An alternative would be to write it as `sqrt(x**6)`. It is not ok to write it as `x**3`, however, since the original expression is never negative.
