### ISSUE TITLE
Way to define ColoredExpr?

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#18588]
In some situations I want to output `sympy` expressions in red. I have an idea of defining class `ColoredExpr`, and add `print_ColoredExpr` method in extended `LatexPrinter`. Then `ColoredExpr(sin(x))` should output `sin(x)` in red color.

The question is how do I define `ColoredExpr`? Should it be just child of `Expr`? It should be ignored during simplification or some other tree operations.

**Comment by oscarbenjamin** [comment]
If you include a `ColoredExpr` in your expression then it will break things during symbolic manipulation. It would be better to handle the colouring at the time of printing e.g. substitute a `ColoredExpr` in just before printing.

**Comment by proy87** [comment]
How do I define it?

**Comment by asmeurer** [comment]
A wrapper class won't work with any symbolic manipulation. The issue is that you won't be able to make symbolic functions to recognize that things like `ColoredExpr(sin(x)) + cos(x)` are the same as `sin(x) + cos(x)`.

If you only care about the final expression without doing any simplifications on it, subclassing Expr should work fine. You can also subclass Function, which could make things easier. For example

```py
>>> class ColoredExpr(Function):
...     nargs = 1
...
...     def _latex(self, printer):
...         return r"{\color{red} %s}" % printer.doprint(self.args[0])
>>> print(latex(ColoredExpr(sin(x)) + cos(x)))
\cos{\left(x \right)} + {\color{red} \sin{\left(x \right)}}
```

**Comment by proy87** [comment]
Thank you!
