### ISSUE TITLE
sympify evaluate=False double fraction

### ISSUE THREAD

**Issue by aliasal** [sympy/sympy#18624]
Hi

If I use
sympify("(3/2)/(4/5)", evaluate=False)
I get
3/(2 4/5) ( with no parenthesis, I wrote them for clarification)
that means the numerator is 3 (instead of 3/2)
and the denominator is 2*4/5 (instead of 4/5)
Technically it is not wrong, but why does it happen and how do I prevent this?

Thanks

**Comment by asmeurer** [comment]
This is what the expression is

```py
>>> type(sympify("(3/2)/(4/5)", evaluate=False))
<class 'sympy.core.mul.Mul'>
>>> sympify("(3/2)/(4/5)", evaluate=False).args
(3, 1/2, 1/(4/5))
```

The problem is that SymPy doesn't actually represent fractions as fractions. Rather `x/y` is represented as `Mul(x, Pow(y, -1))`. 

You can represent what you want like

```
>>> Mul(Mul(3, Rational(1, 2), evaluate=False), Pow(Mul(4, Rational(1, 5), evaluate=False), -1, evaluate=False), evaluate=False)
(3/2)/((4/5))
```

I guess the sympify evaluate=False parser should try to use unassociated Muls to more exactly represent the expression.

**Comment by aliasal** [comment]
@asmeurer Thanks for the clarification and the example.
But I get "(3/2)/(4/5)" as a string from user input and I want to represent it as unchanged as possible, but as neatly typeset as possible (if you know any javascript or python library that can handle this, I'd be pleased to know about it). 
With more "complex" expression, like  (3/2+x)/(4/5+x) sympify(evaluate=False) works great together with latex output, but in these "simple" cases the mentioned problem arises. I probably could catch these "special" cases, but of course I hoped for the "magic bullet".
On the Sympy Live-Shell your example gets printed as 15/8 which is kind of worse than 3/(2 4/5). Didn't try it on my pyodide-project though.

**Comment by asmeurer** [comment]
SymPy can struggle with this sort of thing because it wasn't really designed to represent expressions unevaluated. Basically, SymPy considers some simplifications to be so trivial that it always does them automatically (like putting numeric fractions into canonical form). `evaluate=False` was created to work around this, but it has always been somewhat of a hack.

However, I do believe this specific issue could be improved. The parser that parses this expression needs to do a better job, effectively creating the expression I noted above.

If you want to represent an expression exactly as the user wrote it without any changes, you might be better off building something on top of the Python `ast` module. Then when you want to do mathematics on it, convert that to SymPy. I've written about this here https://github.com/sympy/sympy/issues/14560#issuecomment-376316594 (I should probably move that somewhere better). This is something we want to improve on, but it's a very nontrivial problem. 

The SymPy Live problem is probably caused by whatever printer SymPy Live is using evaluating the expression. That is another issue you can run into. Sometimes an expression will be correct, but the printer will unintentionally evaluate it.

**Comment by aliasal** [comment]
Thanks for the help and information.
I bypassed my problem with ASCIIMath and catching some edge-cases myself.
