### ISSUE TITLE
Incorrect substitution on Derivative

### ISSUE THREAD

**Issue by mcpl-sympy** [sympy/sympy#18779]
Substitution on `Derivative` returns `Subs` instance in the case where substitution may affect the evaluated result.  
Here is an example of correct substitution:
```python
>>> from sympy import Derivative
>>> from sympy.abc import x,y,z
>>> d = Derivative(2*x*y, x)
>>> d.subs(y,x)
Subs(Derivative(2*x*y, x), (y,), (x,))

>>> d.doit().subs(y,x)    # Returns correct result
2*x
>>> d.subs(2*x, z).doit()    # Returns correct result
2*x
```

Therefore, the example below seems to be an error.

```python
>>> d.subs(2*x, z)    # This should result Subs object
Derivative(y*z, x)

>>> d.doit().subs(2*x, z)    # Returns correct result
2*y
>>> d.subs(2*x, z).doit()    # Returns wrong result
0
```

Similary, here is another error.
```python
>>> from sympy import exp
>>> Derivative(exp(x), x).subs(exp(x), y).doit()
0
>>> Derivative(exp(x), x).doit().subs(exp(x), y)
y
```

**Comment by smichr** [comment]
I remember it was complicated working out when subs should be done and whether the substitution should be done with pre or post-doit semantics. Proceed with caution.

**Comment by mcpl-sympy** [comment]
Maybe `Derivative` should return evaluated result in more conservative way.

**Comment by asmeurer** [comment]
Note that we explicitly allow this behavior:

```py
>>> Derivative(f(x), x).subs(f(x), y)
Derivative(y, x)
```

In fact, that is the motivation behind `Derivative.subs` not evaluating. See https://github.com/sympy/sympy/issues/5148 and the referenced issues. The reason is that some functions replace expressions with dummies to do some processing, and we don't want it to break on derivatives. The assumption is that you will replace it back before calling doit. Otherwise you have to make sure the replacement is mathematically valid if you want a mathematically equivalent result (`2*x = z` is not mathematically valid from the point of view of SymPy because SymPy treats `z` as a constant with respect to `x`). 

So I think this should be marked as WontFix.

**Comment by mcpl-sympy** [comment]
@asmeurer  Thanks!
