### ISSUE TITLE
Fix documentation in Parsing

### ISSUE THREAD

**Issue by smitgajjar** [sympy/sympy#18850]
For `sympy.parsing.mathematica.mathematica()`,
formatting of example is improper.
[Link to the doc](
https://docs.sympy.org/latest/modules/parsing.html#sympy.parsing.mathematica.mathematica)
`In [1]: mathematica(‘Log3[9]’, {‘Log3[x]’:’log(x,3)’}) Out[1]: 2`
 is written instead of usual 
`>>> mathematica(‘Log3[9]’, {‘Log3[x]’:’log(x,3)’}`
`2`
which results in flawed formatting!

**Comment by oscarbenjamin** [comment]
Can you give a link to code/docs and explain which part is broken?

**Comment by Sc0rpi0n101** [comment]
This one violates a lot of docstring styling guidelines. 

The docstring is in triple single quotes instead of double-quotes.
The example section should not be represented by `# Example`, instead by 
```
Example
=======
```
The format for doctests is wrong. 
There is no empty line before the closing quotes. 

It'll be better to rewrite the whole docstring IMO.

**Comment by dhruvmendiratta6** [comment]
I made the suggested changes but git diff is showing changes in files which weren't made.
