### ISSUE TITLE
Running sympy in Brython (Python in the browser)

### ISSUE THREAD

**Issue by PierreQuentel** [sympy/sympy#18889]
Hi,

I am the creator and main developer of [Brython](https://github.com/brython-dev/brython), an implementation of Python running in the browser. Its main focus is the development of front-end applications in Python instead of Javascript, but it is also used as a Python interpreter and as such, I try to make it as compliant with CPython as possible.

In the latest version (3.8.8) the sympy package is supported, in the sense that this simple example:

```python
from sympy import *
print(Symbol('x'))
```
gives the expected result.

The problem is that this code takes a very long time (several dozens of seconds), for 2 reasons:
- 494 modules have to be imported (most of them from sympy or mpmath + some of the standard distribution), and import is more expensive in Brython than in CPython
- during imports, some heavy computations on long integers are performed. For instance:
```
sympy/__init__.py line 19:
    import mpmath
mpmath/__init__.py line 6 :
    from .ctx_mp import MPContext
mpmath/ctx_mp.py line 11 :
    from .libmp.backend import basestring, BACKEND
mpath/libmp/__init__.py line 46 :
    from .gammazeta import (catalan_fixed, mpf_catalan,
mpmath/libmp/gammazeta.py line 1593:
    small_factorial_cache = [from_int(ifac(n)) for \
        n in range(SMALL_FACTORIAL_CACHE_SIZE+1)]
```
With SMALL_FACTORIAL_CACHE_SIZE set to 150, this means computing up to `ifac(150)`, which is 57133839564458545904789328652610540031895535786011264182548375833179829124845398393126574488675311145377107878746854204162666250198684504466355949195922066574942592095735778929325357290444962472405416790722118445437122269675520000000000000000000000000000000000000

Brython can handle such numbers, but it takes some time...

Do you think there could be solutions to reduce the number of imports and / or the computation when importing sympy ?

**Comment by Arpan612** [comment]
Hello. In order to reduce the number of imports, I suggest we bundle modules which all contribute to the same operation and implement it in the code with this new module (with a new name).

**Comment by Arpan612** [comment]
For Long Integers, if the nature of the problem is such that some amount of approximation is tolerable, a new function can be developed which rounds off the integers into a more workable number. This can reduce the computational power required to import and work with sympy.

**Comment by Arpan612** [comment]
With reference to the example of SMALL_FACTORIAL_CACHE_SIZE, we can reduce the number 150 to some double-digit number so that the time required is less. Another suggestion to reduce time taken for using sympy in Brython can be that if you observe some of the functionalities of Sympy is required frequently in Brython, it can be implemented in the core code of Brython itself. I hope this helps. 💯

**Comment by oscarbenjamin** [comment]
It would be good to reduce the number of imports but it is not easy because:

1. It is standard in sympy that almost all public API gets imported to the top-level sympy namespace. I think that's a mistake but changing it is obviously not backwards compatible since that is where most of our users access the names.

2. There are strong cyclic import links between the many packages/modules of sympy. There needs to be more discipline in deciding which packages are implemented on top of which other packages but this is not easy to disentangle.

The issue with large integers should be opened with mpmath:
https://github.com/fredrik-johansson/mpmath

Do you have other examples of excessive calculations during sympy import?

**Comment by PierreQuentel** [comment]
@oscarbenjamin 
__`mpmath.libmp`__ imports __`mpmath.libmp.libintmath`__, which has in line 190:
```python
_1_800 = 1<<800
_1_600 = 1<<600
_1_400 = 1<<400
_1_200 = 1<<200
_1_100 = 1<<100
_1_50 = 1<<50
```

The first number is 6668014432879854274079851790721257797144758322315908160396257811764037237817632071521432200871554290742929910593433240445888801654119365080363356052330830046095157579514014558463078285911814024728965016135886601981690748037476461291163877376

**Comment by Arpan612** [comment]
@oscarbenjamin I agree that the very nature of SymPy has modules interdependent on each other but the number of modules I suggest for bundling is only those which are often used in the task. It might take some time but is really important. And yes even I thought of using mpmath but as Pierre sir pointed out, it is already used.

**Comment by asmeurer** [comment]
I'm curious what is the problem exactly with large numbers? If Brython is slow in general with large numbers then it will be quite slow with SymPy, as it is very common for it to use large numbers internally in a calculation, even when the numbers in the end-user expression are not large.

Does Brython load .pyc files or only .py files? As far as I know, numeric literals such as the ones listed above are inlined by the compiler into the .pyc files, so they don't have to be computed at import time, only loaded into memory.

**Comment by PierreQuentel** [comment]
@asmeurer 
Thanks for the information about .pyc files storing the result, I will try to do the same in Brython (the equivalent of a .pyc file is the translation from Python to Javascript, stored in an indexedDB cache).

Yes, Brython is rather slow on long integers, and will be so until the Javascript `BigInt` class is widely supported by browsers (it doesn't work on Safari for the moment). I understand that they must be supported in a module such as __`mpmath`__, but I don't think it is really useful to make these calculations in the case of the simple example I mentioned.

Anyway, the number of modules to load is the main problem; calculation on big integers is an order of magnitude less important.

**Comment by Arpan612** [comment]
@PierreQuentel Sir is there any other problem Brython faces or can we close this issue?

**Comment by PierreQuentel** [comment]
@Arpan612 
If I understand correctly, there are no solutions to the problems Brython faces, so it's no use leaving the issue open. Thanks for the feedback anyway !

**Comment by Arpan612** [comment]
Very respectfully, Sir, I believe if we work on the lines we have discussed above, some aspects of the problem can be resolved. If I find a better solution to this problem I will definitely inform you.

**Comment by asmeurer** [comment]
I'm not sure if we can do much to reduce the number of loaded modules. It might be possible to play with lazy loading libraries like https://github.com/xonsh/lazyasd. I don't know if anyone has ever attempted such a thing with SymPy. Of course, once someone uses a function that requires a given object, it would have to be loaded.

**Comment by oscarbenjamin** [comment]
I think we should try to reduce the number of loaded modules in general. It is a problem that it isn't possible to `import sympy` without importing *everything*. It is a problem for CPython as well as Brython because importing sympy is relatively slow in CPython as well.

Fixing that would require a fundamental backwards incompatible change in approach though. Right now almost all public API is available with `from sympy import *` and that would have to change: I think it should though. At least we could make it so that imports are granuralised at top-level package like `from sympy.matrces import *`.
