### ISSUE TITLE
`is_cnf(to_cnf(expr))` should be True

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#18904]
As reported [here](https://stackoverflow.com/questions/60740347/sympy-logic-module-assertis-cnfto-cnfexpr-simplify-true-fails) there are expressions which are in cnf form which, when passed to `to_cnf` with `simplify=True` are returned in non-cnf form. This is a diff that addresses the issue:

```diff
diff --git a/sympy/logic/boolalg.py b/sympy/logic/boolalg.py
index dd734ce..d544ea7 100644
--- a/sympy/logic/boolalg.py
+++ b/sympy/logic/boolalg.py
@@ -1714,7 +1714,9 @@ def to_cnf(expr, simplify=False):
         return expr

     if simplify:
-        return simplify_logic(expr, 'cnf', True)
+        new = simplify_logic(expr, 'cnf', True)
+        if is_cnf(new):
+            return new

     # Don't convert unless we have to
     if is_cnf(expr):
```

cf #9949

**Comment by sschnug** [comment]
In regards to my example, i would restate:

- the input is dnf (or anything *not already cnf* in general)
- `to_cnf` is called and the output might still be non-cnf without any notification
    - e.g. due to early-stopping to counter exponential-time computation

**Comment by smichr** [comment]
If no simplification is done and the expression is not in cnf form then it gets to here (with the diff I proposed):
```python
    expr = eliminate_implications(expr)
    res = distribute_and_over_or(expr)
    return res
```
Is that sufficient to guarantee that it will be in `cnf` form? If you have a counter example that fails with the diff -- and I suspect you can think of one faster than me -- please post it here.

**Comment by sschnug** [comment]
I'm not sure if we focus on the same issues here.

Following my initial surprise to see `is_cnf(to_cnf(expr, simplify=True))` fails silently, the diff *looks* (i don't know much about sympy and i did not try it) like it shifts this towards:

- cnf is guaranteed to be returned (note: see part 2 of this comment)
- but the failing of simplification is now the hidden / silent characteristic
    - before: i expect a minimized cnf and got no cnf
    - now: i expect a minimized cnf and got a non-minimized cnf

Not sure how much better that is.

And then there is another thing about consistency:

- simplification is killed off (silently) before attempting it (due to exponential blow-up of time / memory)
- but theory guarantees us (some P/NP assumptions) that there will be cases with exponential blow-up in the non-simplification code too (general dnf -> cnf without introducing new aux-vars; which seems not to be part of sympy; e.g. tseitin-encoding)
    - this one is not killed off a-priori

It's arguably harder to build a safety against the latter. The good thing is, that it's probably going to crash non-silently (or lead to memory-trashing in the worst-case).

I don't have design-proposals and i don't know what people are doing with this module. I can't offer much help here.

When looking into it for building a SAT-model, i was just surprised to see this behavior (to_cnf which does not return a cnf) which complicates my workflow.

All i can say, that *imho* there should be at least one of the following (probably ordered by my preferences):

- exception thrown when not doing what asked for in general
- (warning when not doing what asked for)
- documentation of *incomplete* behavior including workflows
    - to_cnf followed by is_cnf to be sure
        - (alternatively: status part of return-tuple); probably too api-breaking)

**Comment by asmeurer** [comment]
We do have some ideas about Tseitin (https://github.com/sympy/sympy/issues/7174). As it is now to_cnf should just attempt the transformation without worrying about whether it will cause expression blowup. 

Regarding satisfiable() being inefficient with expressions that are already in DNF, I thought I remembered there being an issue about this, but I don't see it. I think satisfiable should recurse if the top-level expression is an Or, rather than trying to make the whole thing into CNF.
