### ISSUE TITLE
Vector Docs Using Unit Normal 

### ISSUE THREAD

**Issue by doswellf** [sympy/sympy#18995]
Small issue, mathematical in nature. The Vector docs use n_hat instead of r_hat, _hat, j_hat, k_hat for the unit vector in any direction. Normally, n_hat is reserved for the unit normal vector to a curve, plane or surface. This could confuse readers when they start to use the Vector class for Electrodynamics, Fluid Dynamics or Aerodynamics. 

The specific page I was using : https://docs.sympy.org/latest/modules/physics/vector/vectors.html

Thanks!

**Comment by Arpan612** [comment]
Can someone mention the file where the changes can be made?

**Comment by dhruvmendiratta6** [comment]
@Arpan612 I think it is in `doc/src/modules/physics/vector/vectors.rst`.
@doswellf From what I understand n_hat across the docs represents basis vector for a Reference frame `N` and I think the part you are referring to lies in https://docs.sympy.org/latest/modules/physics/vector/vectors.html#alternative-representation ,
here it could simply be mentioned that n_hat is a basis vector for the reference frame `N` or if it is preferred, as you suggested it could be changed to i_hat, j_hat and k_hat.

**Comment by moorepants** [comment]
Yes, for the physics vectors these are the orthonormal vectors associated with a given reference frame and their symbols are derived from the symbol used to create the reference frame.

**Comment by dhruvmendiratta6** [comment]
@moorepants So, in the documentation is the change from
`Alternative Representation`
`If we have three non-coplanar unit vectors \mathbf{\hat{n}_x},\mathbf{\hat{n}_y},\mathbf{\hat{n}_z}, we can represent any vector `...
to 
`Alternative Representation`
`If we have three non-coplanar unit vectors \mathbf{\hat{n}_x},\mathbf{\hat{n}_y},\mathbf{\hat{n}_z},` in the Reference frame N `we can represent any vector`...
preferred or using i_hat, j_hat, k_hat instead of their counterparts in the N Reference frame preferred?

**Comment by moorepants** [comment]
I don't see the need to change anything.
