### ISSUE TITLE
Error solving equation with zero as float

### ISSUE THREAD

**Issue by QuentiumYT** [sympy/sympy#19048]
### Hello scipy team,
I found a weird thing while solving equations using latest sympy module, using the solver with `0` it returns the right value but using with the float of `0` → `0.0` it returns an error.

![Sympy Float Error](https://quentium.fr/+Files/stackfiles/sympy_float.png)

Python version: `3.6.8`
Sympy version: `1.5.1`

**Comment by oscarbenjamin** [comment]
This happens because of this code in `solve` that tries to solve boolean equations like `Eq(x > 1, False)`:
https://github.com/sympy/sympy/blob/e007bbe0872d1477df8110b5f1a713a58e2ad41a/sympy/solvers/solvers.py#L975-L997

I think that block should probably be removed from `solve` not least because it's broken and doesn't work properly. There just isn't any need for users to pass input like `Eq(x < 1, False)` or to mix up `solve` for algebraic expressions with solving systems of logical expressions (for which there are separate functions already).

The issue here is caused because at this line
https://github.com/sympy/sympy/blob/e007bbe0872d1477df8110b5f1a713a58e2ad41a/sympy/solvers/solvers.py#L981
we compare the rhs (0.0) with S.false and:
```
In [3]: S(0) == S.false                                                                                                           
Out[3]: False

In [4]: S(0.0) == S.false                                                                                                         
Out[4]: True
```
So `Float(0)` compares equal to False. That's a behaviour that is I guess carried over from Python where
```
In [6]: 0 == False                                                                                                                
Out[6]: True
```
but I've always considered that nonsensical behaviour in Python (which inherited it from C which didn't have an explicit bool type).

We can fix this particular issue by ensuring that `Float(0.0) != S.false` but I also think that this block of code in `solve` should just be removed.

**Comment by oscarbenjamin** [comment]
I'm marking this as easy to fix. In principle this just needs to find where in e.g. `Float.__eq__` we get the erroneous `Float(0.0) == S.false -> True` behaviour from. It may be however that fixing that leads to other issues - there is no way to know without trying it and running the tests.
