### ISSUE TITLE
Overflowing graphic issues in plot3d_parametric_line

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#19106]
`plot3d_parametric_line((2*cos(x), 2*sin(x), 2*x, (x, -5, 5)), (sin(x), cos(x), x, (x, -5, 5)))`
![image](https://user-images.githubusercontent.com/34944973/79045348-91dd2b80-7c45-11ea-9123-bd29d989fc58.png)
`plot3d_parametric_line((sin(x), cos(x), x, (x, -5, 5)), (2*cos(x), 2*sin(x), 2*x, (x, -5, 5)))`
![image](https://user-images.githubusercontent.com/34944973/79045352-986ba300-7c45-11ea-866a-e3862f02cae0.png)

I see a lot of issues like #19051 happen after we had started to use `LineCollection` instead of more high level `Axes.plot` API. But I see this was deliberately done because of the limitation of coloring support for `Axes.plot`.
The problem is that we must set the limits manually if we are manipulating low level graphical primitives.

I think that each `Series` needs some helper for computing the bounds of the overall mesh
rather than doubly computing the points and overriding the limits naively like 
https://github.com/sympy/sympy/blob/d02120c1ec491fe9322f4ad35fc8040b6b6a191d/sympy/plotting/plot.py#L1091-L1094

Although #19088 claims that `autoscale_view` works, I have found that this breaks 3D plotting more worse than before.
![image](https://user-images.githubusercontent.com/34944973/79045614-0795c700-7c47-11ea-97d7-d4a9d4da4fd7.png)

**Comment by oscarbenjamin** [comment]
> But I see this was deliberately done because of the limitation of coloring support for `Axes.plot`.

What is the limitation of colouring support in `Axes.plot`? Would it not be better to fix that upstream rather than try to reimplement it in sympy?

**Comment by sylee957** [comment]
I mean about the color supports like 

```
from sympy import *
import numpy as np

x = Symbol('x')
p = plot(abs(x), (x, -10, 10), ylim=(0, 10), show=False, adaptive=False)
p[0].line_color = lambda a: np.cos(2*a)
p.show()
```
![image](https://user-images.githubusercontent.com/34944973/79048940-75e48480-7c5b-11ea-9b64-c1f35f6b5650.png)

```
from sympy import *
from sympy.plotting import plot3d
import numpy as np

x, y = symbols('x y')
p = plot3d(abs(x*y), (x, -10, 10), (y, -10, 10), show=False)
p[0].surface_color = lambda a, b: np.cos(a*b/10)
p.show()
```
![image](https://user-images.githubusercontent.com/34944973/79048945-80068300-7c5b-11ea-90b1-1042e8a20ef0.png)

When I switched them to use plot and plot3d, they don't have features like `set_array`

**Comment by oscarbenjamin** [comment]
If those are not supported by matplotlib then do they need to be supported in sympy? There don't seem to be any examples making use of this feature in the codebase.

I'm guessing that this is just something that was possible in pygletplot so when making the backend based API  it seemed useful to have it in matplotlib as well.

**Comment by sylee957** [comment]
I don’t think that they are well documented, but I have seen that they are tested a lot in the plotting tests

**Comment by oscarbenjamin** [comment]
When I say that something is used in the codebase I mean outside of the tests. Code that isn't even tested is usually broken as well as unused.

I suggest to use matplotlib's plot even if it means that the colouring isn't possible. I think it's also important to make clear to users and contributors that sympy's use of matplotlib is not doing anything special that can't be done easily in the matplotlib API.

**Comment by tacaswell** [comment]
Using line collections like this is definitely supported (and documented https://matplotlib.org/3.1.1/gallery/lines_bars_and_markers/multicolored_line.html).

**Comment by tacaswell** [comment]
Internally Matplotlib can't do anything other that look at the data you have passed in.  However, the logic around exactly what artists participate, exactly when to pay the cost of updating the limits, and even when to auto scale (do we have these limits because of our internal behavior or because the user told us to have them) can get subtle / brittle.

 If you can compute the limits and set the view manually that is going to be more reliable and be guaranteed to work on every version of Matplotlib (both historical and future).

**Comment by tacaswell** [comment]
@sylee957 Please see the changes I pushed to #19088 . What version of Matplotilb are you using and has the scaling changed between versions?

**Comment by sylee957** [comment]
I have tried versions from 2.1 to 3.2, but haven't found autoscale_view working with 3d plots.

**Comment by oscarbenjamin** [comment]
> Using line collections like this is definitely supported

Yes (and thank you for the PR to fix this) but my point is more general: I worry that sympy is trying to be too clever with plotting which is really a function to be provided by other libraries. I doubt anyone uses this multicolour line feature so I don't see why sympy's implementation should be complicated by it. If it isn't a feature of matplotlib's `plot` function then why should it be a feature of sympy's `plot` function? Users who want multicolour lines can just use matplotlib themselves.

Supporting basic plot functions from sympy that take away some of the boilerplate in bridging from a sympy expression to the inputs expected by e.g. matplotlib is useful for our users. Having a convenient `plot(expr)` function that eliminates all boilerplate is especially helpful for those who are using sympy for maths but do not otherwise use Python and don't even know what matplotlib is.

The plotting module is designed with the idea that users have a convenient frontend and there can be multiple backends of which matplotlib is one. In practice though there is only one backend (matplotlib). Sympy owns the API (e.g. `sympy.plot`) for plotting but just passes everything on to matplotlib. If we were honest with our users about this then we could point out that sympy's plotting module doesn't need any special features beyond basic convenience routines because all the features they might want (including multicolour lines) are already available in matplotlib.

From a software engineering perspective sympy has painted itself into a corner by trying to own the API while hiding matplotlib as an implementation detail. What this means longer term is that people will keep requesting and implementing features in sympy's plotting module that are rarely used or already exist in matplotlib which is a waste of time for everyone. Our users who want more advanced plotting features would benefit more from learning to use matplotlib rather than having sympy duplicate more of its implementation and API.

**Comment by sylee957** [comment]
I don't think that we should deprecate coloring for line plots, because it is important entrance to introduce domain coloring for [complex plotting](https://reference.wolfram.com/language/ref/AbsArgPlot.html)

Though I have some questions for matplotlib that why `plot_surface` is able to `set_array` while `plot` is not having features like `set_array`.

**Comment by oscarbenjamin** [comment]
Having this implemented upstream in matplotlib would definitely be better.

For now though this is probably the way forward:

> If you can compute the limits and set the view manually that is going to be more reliable and be guaranteed to work on every version of Matplotlib (both historical and future).

**Comment by sylee957** [comment]
I rather think that the autoscale_view not working with 3d plots is an upstream issue because I have this example

```
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from mpl_toolkits.mplot3d.art3d import Line3DCollection

z = np.linspace(-4 * np.pi, 4 * np.pi, 100)
x = np.sin(z)
y = np.cos(z)

segments = []
for i in range(len(z)-1):
    z0, x0, y0 = z[i], x[i], y[i]
    z1, x1, y1 = z[i+1], x[i+1], y[i+1]
    segments.append([(x0, y0, z0), (x1, y1, z1)])

collection = Line3DCollection(segments)
fig = plt.figure()
ax = fig.gca(projection='3d')
ax.add_collection3d(collection)
ax.autoscale_view()
plt.show()
```

I also think that the Line3DCollection have more fragile implementation than its 2d counterpart.

But I think that this can better be fixed in sympy to give consistent output across matplotlib versions.
