### ISSUE TITLE
solution of quintic equation raises error

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#19157]
The following (as reported in the [mailing list](https://groups.google.com/forum/#!topic/sympy/409jW3Sy5t8)) should return RootOf instances. It looks like the quintic code cannot determine `r2` and `r3` so it raises when trying to work with None.
```python
>>> from sympy.abc import x
>>> solve(x**5 - 6*x**3 - 6*x**2 + x - 6)
raises
```

**Comment by jksuom** [comment]
It looks like the fixed tolerance value `tol` is too small in this case. It should probably depend on some of the values, maybe `testplus` and `testminus`.

**Comment by smichr** [comment]
> too small in this case

Or that there is no solution in this case? When I print out the residuals and select the smallest one, the solution does not satisfy the equation.

**Comment by smichr** [comment]
I wish there were a better method of detecting non-solutions, however. I haven't done much with solving quintics.

**Comment by jksuom** [comment]
According to the paper referred to in polyquinticconst, this equation should be algebraically solvable (at least if `f20` is correct). Otherwise, the last loop would not have been executed at all. It looks like there is something wrong in the implementation, maybe a typo. I wouldn't be surprised as the expressions in polyquinticconst are really complicated.
