### ISSUE TITLE
factor(extension=sqrt(2)) hangs

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#19360]
```julia
In [1]: e = (sqrt(2)*x - y)**2                                                                                                    

In [2]: e                                                                                                                         
Out[2]: 
          2
(√2⋅x - y) 

In [3]: expand(e)                                                                                                                 
Out[3]: 
   2               2
2⋅x  - 2⋅√2⋅x⋅y + y 

In [4]: expand(e).factor(extension=[sqrt(2)]) # hangs
```

**Comment by jksuom** [comment]
There is a typo in `dmp_ext_factor`.  https://github.com/sympy/sympy/blob/3219093a5ae34abd549acf0f4c1b67d419bddc2a/sympy/polys/factortools.py#L1200-L1201
`dmp_sqf_norm` should be called on the squarefree part of the input polynomial. That is
properly extracted on the previous line and named `f`. Hence the argument of `dmp_sqf_norm`
should be `f` instead of `F`.

**Comment by vaish3496** [comment]
@jksuom I'd like to take up this issue and come with a PR soon.
