### ISSUE TITLE
sympy cannot simplify sign(x) * abs(x)

### ISSUE THREAD

**Issue by eric-wieser** [sympy/sympy#19484]
```
>>> from sympy import Symbol, sign
>>> x = Symbol('x', real=True)
>>> x_new = abs(x)*sign(x)
>>> x_new
Abs(x)*sign(x)
>>> x_new.simplify()
Abs(x)*sign(x)
```

I would expect the result to be just `x`. gh-19277 may be related.

**Comment by eric-wieser** [comment]
What's the mechanism for making simplify do this automatically?

**Comment by oscarbenjamin** [comment]
First we need `sign.eval_rewrite_as_Abs` so that you can do `sign(x).rewrite(Abs)` (#19277).

Then we need simplify to do something like `if expr.has(sign): expr.rewrite(Abs)` to see if it helps with simplifying.

Ideally I would prefer the second form of the Piecewise. That doesn't work because `piecewise_fold` is unable to detect this case so `piecewise_fold` or `Piecewise._eval_simplify` should be improved to handle that case. Specifically when we have:
```julia
In [1]: Piecewise((f(x), Ne(x, 0)), (f(0), True))                                                                                              
Out[1]: 
⎧f(x)  for x ≠ 0
⎨               
⎩f(0)  otherwise
```
It should be possible to spot that for cases after the `Ne` condition we can substitute the opposite of that condition in to the first expression and if that gives the same result as the next case we can combine the cases giving the expression from the first case with the `Or` of the conditions e.g.:
```julia
In [4]: p = Piecewise((f(x), Ne(x, 0)), (f(0), True))                                                                                          

In [5]: p                                                                                                                                      
Out[5]: 
⎧f(x)  for x ≠ 0
⎨               
⎩f(0)  otherwise

In [6]: p.args[0]                                                                                                                              
Out[6]: (f(x), x ≠ 0)

In [7]: p.args[0][0]                                                                                                                           
Out[7]: f(x)

In [8]: p.args[0][0].subs(p.args[0][1].lhs, p.args[0][1].rhs) == p.args[1][0]                                                                  
Out[8]: True

In [11]: p2 = Piecewise((p.args[0][0], Or(p.args[0][1], p.args[1][1])))                                                                        

In [12]: p2                                                                                                                                    
Out[12]: f(x)
```

**Comment by dhruvmendiratta6** [comment]
After adding `sign._eval_rewrite_as_Abs` and `if expr.has(sign): expr.rewrite(Abs)` in
` simplify()` the outputs are ;
```
>>> simplify(sign(x) * Abs(x))
x

>>> e = x**2 + sign(x**3 + 1)
>>> simplify(Abs(x**3 + 1) * e)
/     2 | 3    |            3
|    x *|x  + 1|       for x  = -1
<
| 3    2 | 3    |
\x  + x *|x  + 1| + 1   otherwise

>>> f = Function('f')
>>> e = x + sign(x + f(x)**3)
>>> simplify(Abs(x + x**3) * e)
/                 | 3    |                          3
|               x*|x  + x|                 for x + f (x) = 0
|
|                            |  / 2    \|
</  |     3   |        3   \ |x*\x  + 1/|
|\x*|x + f (x)| + x + f (x)/*|----------|      otherwise
|                            |     3    |
|                            |x + f (x) |
\

```
@oscarbenjamin should I add this to the existing PR #19487

**Comment by oscarbenjamin** [comment]
I'm not sure if those are actually simpler or not. In some parts of simplify things like this are tried and the transformation is only kept if it seems to make the result simpler so maybe the rewrite should be tested there.

**Comment by eric-wieser** [comment]
Those outputs are not fully simplified, but the first one is definitely better.

All of those long outputs are of the form
```
/ x      for y = 0
<
\ x + y  otherwise
```
This looks like a bug in simplifying `Piecewise`

**Comment by dhruvmendiratta6** [comment]
I think the problem is in the algorithm in `piecewise_simplify()`. The condition for equality cannot be checked if `Eq()` is the first condition as in the first iteration `prevexpr` is `None`.
```
>>> simplify(Piecewise((x**2*Abs(x**3 + 1), Eq(x**3, -1)), (x**3 + x**2*Abs(x**3 + 1) + 1, True)))
Piecewise((x**2*Abs(x**3 + 1), Eq(x**3, -1)), (x**3 + x**2*Abs(x**3 + 1) + 1, True))
```
but if we try 
`>>> simplify(Piecewise((x**3 + x**2*Abs(x**3 + 1) + 1, True), (x**2*Abs(x**3 + 1), Eq(x**3, -1))))`
it gives `x**3 + x**2*Abs(x**3 + 1) + 1`
I'll try and figure out what can be done here.

**Comment by dhruvmendiratta6** [comment]
I think the problem here is that expressions like `x**3 + 1` don't satisfy the `_blessed()` condition https://github.com/sympy/sympy/blob/25fbcce5b1a4c7e3956e6062930f4a44ce95a632/sympy/functions/elementary/piecewise.py#L1243
as value of `_diff_wrt` is False for such expressions. 
See #7027.

**Comment by dhruvmendiratta6** [comment]
@oscarbenjamin @eric-wieser Removing the `if _blessed()` condition works fine in this case and does not break any tests. Would it be fine to make such a change?

**Comment by oscarbenjamin** [comment]
It's hard to discuss these changes without seeing them. You can push them to the PR or to a new PR and then ask about them.
