### ISSUE TITLE
self parameter in sympy.geomtry.line

### ISSUE THREAD

**Issue by mohitshah3111999** [sympy/sympy#19480]
I came across the LinearEntity class in the mentioned module and I saw that the self parameter was missing in some of the methods. See the image below:
[](![sympyGeometry][]((https://user-images.githubusercontent.com/42018918/83563257-7d782980-a538-11ea-8291-365a885f359e.PNG)))

I think the first parameter must be self in the class methods.

**Comment by mohitshah3111999** [comment]
Can I work on this little issue?

**Comment by friyaz** [comment]
> See the image below:

You have not attached any image.

Maybe you are referring to these functions.
```python
    def angle_between(l1, l2):
        """Return the non-reflex angle formed by rays emanating from
        the origin with directions the same as the direction vectors
        of the linear entities."""

    def smallest_angle_between(l1, l2):
        """Return the smallest angle formed at the intersection of the
        lines containing the linear entities.

    def is_perpendicular(l1, l2):
        """Are two linear entities perpendicular?"""

    def is_parallel(l1, l2):
        """Are two linear entities parallel?"""
```

> I think the first parameter must be self in the class methods.

Yes, The first argument of every class method is always a reference to the current instance of the class. We can rename the first variable whatever we wish but self is the general convention.

In this case, Instead of using self, these functions use l1. I think this is for the sake of clarity.

**Comment by mohitshah3111999** [comment]
Hello there,
Yes I was asking for this.
Thanks for the clarification.
