### ISSUE TITLE
bug in is_subset(Reals)

### ISSUE THREAD

**Issue by gschintgen** [sympy/sympy#19513]
```python
In [1]: print( (1/n).is_real )
None

In [2]: imageset(Lambda(n, 1/n), Integers).is_subset(Reals)
Out[2]: True
```
`Out[2]` should also be `None`.

**Comment by smichr** [comment]
Here is a possible solution
```diff
diff --git a/sympy/sets/handlers/intersection.py b/sympy/sets/handlers/intersection.py
index 650efe0531..9558558426 100644
--- a/sympy/sets/handlers/intersection.py
+++ b/sympy/sets/handlers/intersection.py
@@ -294,10 +294,7 @@ def intersection_sets(self, other): # noqa:F811
         ifree = im.free_symbols
         lam = Lambda(n, re)
         if not im:
-            # allow re-evaluation
-            # of self in this case to make
-            # the result canonical
-            pass
+            base_set = base_set.intersect(solveset_real(f - n_, n))
         elif im.is_zero is False:
             return S.EmptySet
         elif ifree != {n}:
```

**Comment by oscarbenjamin** [comment]
Calling `solveset_real` is way too heavy for an intersection handler.

**Comment by smichr** [comment]
> way too heavy

I was basing that suggestion off of the existing use of `solveset` in the handler. Here is a lighter weight version:
```diff
diff --git a/sympy/sets/handlers/intersection.py b/sympy/sets/handlers/intersection.py
index 650efe0531..642fb3fb94 100644
--- a/sympy/sets/handlers/intersection.py
+++ b/sympy/sets/handlers/intersection.py
@@ -277,8 +277,9 @@ def intersection_sets(self, other): # noqa:F811
                 return FiniteSet(*(fn.subs(n, s[0]) for s in solns))
 
     if other == S.Reals:
-        from sympy.solvers.solveset import solveset_real
         from sympy.core.function import expand_complex
+        from sympy.core.relational import Eq
+        from sympy.solvers.solvers import denoms, solve_linear
 
         f = self.lamda.expr
         n = self.lamda.variables[0]
@@ -293,7 +294,7 @@ def intersection_sets(self, other): # noqa:F811
         im = im.subs(n_, n)
         ifree = im.free_symbols
         lam = Lambda(n, re)
-        if not im:
+        if im.is_zero:
             # allow re-evaluation
             # of self in this case to make
             # the result canonical
@@ -304,7 +305,22 @@ def intersection_sets(self, other): # noqa:F811
             return None
         else:
             # univarite imaginary part in same variable
-            base_set = base_set.intersect(solveset_real(im, n))
+            from sympy.solvers.solvers import denoms, solve_linear
+            from sympy.core.relational import Eq
+            x, xis = solve_linear(im, n)
+            if x == n:
+                base_set -= FiniteSet(xis)
+            else:
+                base_set -= ConditionSet(n, Eq(im, 0), S.Integers)
+        # exclude values that make denominators 0
+        for i in denoms(f):
+            if i.has(n):
+                x, xis = solve_linear(i, n)
+                if x == n:
+                    base_set -= FiniteSet(xis)
+                else:
+                    base_set -= ConditionSet(n, Eq(i, 0), S.Integers)
+
         return imageset(lam, base_set)
 
     elif isinstance(other, Interval):
```

**Comment by oscarbenjamin** [comment]
> I was basing that suggestion off of the existing use of `solveset` in the handler.

Oh, I see that now. That should also be removed. These pairwise handlers are called by `Intersection.__new__` in a pairwise all to all fashion so they run `N^2` times for an intersection of `N` sets. That's a bad idea in itself but if we accept that then the handlers need to be seriously lightweight.

It would be much better if these heavier operations were part of something like `simplify` rather than `__new__`. In fact `Intersection` should not be used as part of `is_subset` at all. A query like `is_subset` should lie on a level below evaluation and should be efficient since it is used as part of evaluation.

Calling something like `Intersection` leads to all kinds of things (like `solveset` apparently) being called so it should not be used there. Also calling `solveset` as part of `Intersection.__new__` is a serious risk of infinite recursion because `solveset` itself is built on top of the sets module and computes many intersections internally.

**Comment by asmeurer** [comment]
Can we move the sets to a design like the matrix expressions where creating the class directly does no evaluation, but doit() and calling a function does? 

I agree that simply creating a set object should not be an expensive operation, but I also think that sets should be able to leverage the full power of functions like solve() to simplify themselves. This is essential given that functions like solveset() exist that return sets, and can often return things that require a lot of simplification. The current state of things is that you can very easily get unwieldy set expressions which are equivalent to something much simpler, so I feel that we need stronger, not weaker set simplification, if not in the constructors then at least available by some method like `simplify()` or `doit()`.

**Comment by oscarbenjamin** [comment]
> Can we move the sets to a design like the matrix expressions where creating the class directly does no evaluation, but doit() and calling a function does?

It would be good to do this but it's not easy. Essentially `solveset` devolves a lot of the work in computing a set of solutions to the underlying set functions. All of that logic needs to move into `solveset` if the sets don't do it automatically. In the meantime we should resist the temptation to make sets any slower and focus on improving explicit simplification of sets.

The approach of putting all of the simplification in `__new__` is broken. The problem with sets right now is that there is very limited support for simplifying them in any other way so the temptation is always to add more simplification in `__new__`.

I don't think that this should be for `doit` which is about applying a more expensive form of evaluation. The distinction (as I see it) between evaluation and simplification is about whether a node in the expression tree simply queries its immediate children (evaluation) or whether it processes the entire expression tree (simplification). The best way to simplify an intersection of sets is to make special algorithms that can operate on all of the sets in the intersection together (in a linear way) rather than having pairwise handlers. Pairwise handlers are inherently quadratic so they should only be used for the fastest and most basic simplification (if at all).

**Comment by shashankks0987** [comment]
#21580

**Comment by shashankks0987** [comment]
Guys I need to convert this is the expected output of the failing test:  Complement(Integers, ConditionSet(n, Eq((n - 1)*(n + 1), 0), Integers))  I need help converting this @oscarbenjamin @smichr
