### ISSUE TITLE
is_positive_semidefinite() gives wrong result on sympy==1.6

### ISSUE THREAD

**Issue by jcpaik** [sympy/sympy#19547]
The code
```
from sympy import Matrix
A = Matrix([[0,0,0],[0,1,2],[0,2,1]])
A.is_positive_semidefinite
```
gives a wrong result `True` for sympy version 1.6. The result is `False` for version 1.5.1.
The reason for this is because the following function introduced in #19205 only checks the leading diagonal minors, thus failing to check det([[1, 2],[2,1]]) < 0.
https://github.com/sympy/sympy/blob/bfd2fa05de2db76a73c16e5c94604cdfd9d74e60/sympy/matrices/eigen.py#L744-L753

**Comment by galbwe** [comment]
Can I try fixing this one?

**Comment by oscarbenjamin** [comment]
Yes, go ahead

**Comment by galbwe** [comment]
@jcpaik @oscarbenjamin The naive approach to fix this entails computing all principal minors
```python
def _is_positive_semidefinite_minors(M):
    """A method to evaluate all principal minors for testing
    positive-semidefiniteness."""
    size = M.rows
    return all(
        M[idx, idx].det(method='berkowitz').is_nonnegative
        for order in range(1, size+1)
        for idx in itertools.combinations(range(size), order)
    )
```
I am concerned that this will become computationally infeasible for large `n`, since it is necessary to compute `n!` determinants using Sylvester's method for positive semidefiniteness, as opposed to `n` determinants for positive definiteness. Any ideas on more efficient algorithms to use here?

**Comment by galbwe** [comment]
I added a check on the eigenvalues to handle larger matrices, which seems to be much faster than computing minors.
```python
return all(eigenvalue.is_nonnegative for eigenvalue in M.eigenvals())
```
 Not sure how it will work for symbolic matrices though.

**Comment by oscarbenjamin** [comment]
Computing the eigenvalues can be very slow for symbolic matrices and is in general not possible for matrices larger than 4x4 where there are symbols in the matrix coefficients. This is because of the Abel-Ruffini theorem:
https://en.wikipedia.org/wiki/Abel%E2%80%93Ruffini_theorem

I thought that the method use here was based on this:
https://en.wikipedia.org/wiki/Sylvester%27s_criterion
So why doesn't that work already?

**Comment by galbwe** [comment]
Sylvestre's criterion does work. But this detail

> An analogous theorem holds for characterizing positive-semidefinite Hermitian matrices, except that it is no longer sufficient to consider only the leading principal minors: a Hermitian matrix M is positive-semidefinite if and only if all principal minors of M are nonnegative.

means we need to check more minors of the matrix, increasing the time complexity from polynomial to (I think) exponential. 

Maybe this is not a huge deal. I'm running some timing benchmarks to get a sense for how far this method can go, and I'll let you make a call from there.

**Comment by galbwe** [comment]
Here is some rough timing data
```python
from random import random
from sympy import Matrix
from sympy.matrices.eigen import _is_positive_semidefinite_by_minors
def check_random_positive_semidefinite_matrix(n):
     A = Matrix([[random() for i in range(n)] for j in range(n)])
     S = A.T * A
     return _is_positive_semidefinite_by_minors(S)
```
```python
>>> n_runs = 10
>>> avg_time_5 = timeit(lambda: check_random_positive_semidefinite_matrix(5), number=n_runs) / n_runs
>>> avg_time_5
0.033390344999997976
>>> avg_time_10 = timeit(lambda: check_random_positive_semidefinite_matrix(10), number=n_runs) / n_runs
>>> avg_time_10
7.595623607399989
>>> n_runs = 5
>>> avg_time_12 = timeit(lambda: check_random_positive_semidefinite_matrix(12), number=n_runs) / n_runs
>>> avg_time_12
53.047399703599964
```
`avg_time_15` did not finish running in the amount of time I was willing to let it go.

**Comment by galbwe** [comment]
Do you think this is reasonable given the size of the matrices in most use cases?

**Comment by galbwe** [comment]
For comparison, here is the time required to check the eigenvalues are non-negative:
```python
>>> from sympy.matrices.eigen import _is_positive_semidefinite_by_eigenvalues
>>> def check_random_positive_definite_matrix_by_eigenvalues(n):
...     A = Matrix([[random() for i in range(n)] for j in range(n)])
...     S = A.T * A
...     return _is_positive_semidefinite_by_eigenvalues(S)
... 
>>> check_random_positive_definite_matrix_by_eigenvalues(10)
True
>>> n_runs = 5
>>> evals_avg_time_12 = timeit(lambda: check_random_positive_definite_matrix_by_eigenvalues(12), number=n_runs) / n_runs
>>> evals_avg_time_12
0.5310900253998625
```

**Comment by galbwe** [comment]
I'm thinking maybe this is beyond the scope of the issue, and there are probably edge cases I'm not considering. I'll open a PR that just corrects Sylvestre's criterion.

**Comment by galbwe** [comment]
[Related PR](https://github.com/sympy/sympy/pull/19556)

**Comment by oscarbenjamin** [comment]
The suggestion here:
https://math.stackexchange.com/questions/13282/determining-whether-a-symmetric-matrix-is-positive-definite-algorithm
is that the Cholesky algorithm is an efficient way to determine the the positive (semi-)definiteness of a matrix.

That's already implemented although the implementation strictly requires positive definite rather than semidefinite. Maybe that could be changed.
```julia
In [5]: A = Matrix([[0,0,0],[0,1,2],[0,2,1]])                                                                                                                 

In [6]: A.cholesky()                                                                                                                                          
---------------------------------------------------------------------------
NonPositiveDefiniteMatrixError            Traceback (most recent call last)
<ipython-input-6-000abf011399> in <module>
----> 1 A.cholesky()

~/current/sympy/sympy/sympy/matrices/dense.py in cholesky(self, hermitian)
    258 
    259     def cholesky(self, hermitian=True):
--> 260         return _cholesky(self, hermitian=hermitian)
    261 
    262     def LDLdecomposition(self, hermitian=True):

~/current/sympy/sympy/sympy/matrices/decompositions.py in _cholesky(M, hermitian)
    270 
    271             if Lii2.is_positive is False:
--> 272                 raise NonPositiveDefiniteMatrixError(
    273                     "Matrix must be positive-definite")
    274 

NonPositiveDefiniteMatrixError: Matrix must be positive-definite
> /Users/enojb/current/sympy/sympy/sympy/matrices/decompositions.py(272)_cholesky()
    270 
    271             if Lii2.is_positive is False:
--> 272                 raise NonPositiveDefiniteMatrixError(
    273                     "Matrix must be positive-definite")
    274 
```
If that check for `is_positive` was relaxed to `is_nonnegative` then I think this would fail if the matrix was known to be not positive semidefinite. Maybe that could be used in `is_positive_semidefinite`.

**Comment by sylee957** [comment]
There is cholesky decomposition with pivoting that can work as an extension for the positive-definite cholesky 
http://eprints.ma.man.ac.uk/1199/1/covered/MIMS_ep2008_116.pdf

Although I'm not sure that the existance of this type of cholesky decomposition asserts that the matrix is positive semidefinite, I'd bet that it's likely.

**Comment by galbwe** [comment]
Thank you. I will take a look at those resources and the existing implementation of `_cholesky` and see what I can come up with.

**Comment by sylee957** [comment]
I’d reopen this issues about how to address the issue of slowdowns.
Unless someone finds out how to make use of gaussian elimination, everything can be expected to be slower than computing eigenvalue because computing eigenvalue involves at least one determinant evaluation while this evaluates determinant multiple times.

So I may eventually revert to eigenvalue computation if nobody comes up with a good idea about performance because at least it won’t be worse than what was there at the first place.

**Comment by galbwe** [comment]
I would suggest a mixed approach that uses Sylvestre's criterion as a fallback if another method does not work. A quick performance improvement would be to use eigenvalues like in https://github.com/sympy/sympy/pull/19556/commits/bc4f42c8eb83f863657eae96f9a08c105d8e8abd, but we would need to investigate edge cases. 

Out of curiosity, does this need to support matrix computations over a finite field?

**Comment by sylee957** [comment]
I don't think that we have any rigorous framework for finite field computation yet. So this doesn't need to be resolved in this issue.

**Comment by jcpaik** [comment]
#19573 seems to have resolved this -- correct me if I'm wrong
