### ISSUE TITLE
improve documentation of `polys` domains.

### ISSUE THREAD

**Issue by gschintgen** [sympy/sympy#19585]
I found it hard to get to grips with the `polys` module. The main reason is the deficient documentation of the available domains. I actually had to look at the source and the issues tracker to get a (limited) understanding.
IIRC there are various references to  `domain='QQ'` (with quotes), `domain=QQ` (without quotes), `domain='QQ<sqrt(2)>'` (without mentioning `QQ(sqrt(2))` vs `QQ<sqrt(2)>`), `domain=QQ.algebraic_field(sqrt(2))`, `domain=EX`. But there's neither a proper tutorial nor a synthesis of the available domains (and their syntaxes). And only later I stumbled over `RR`, `CC`, `EX` and even `GF` which does *not* represent finite fields at all (except for primes, but not prime powers; it even accepts composite numbers, #9544, #13886).

So as a user that is new to the `polys` domain, here's my personal wishlist that I'm respectfully submitting here :-)
- add more details and explanations in the "Basic concepts" section and add a reference to a new "Available domains" section in "Polynomials Manipulation Module Reference".
- also add explanations concerning the various syntaxes
- document (major) shortcomings and caveats (yes, it'd be better to fix them)

**Comment by oscarbenjamin** [comment]
I think it would be good if there was

1. A front page to the polys module that just describes the main exported public API: `Poly`, `cancel`, `factor`, `apart`, `gcd`, and `roots` (anything else?). This page would loosely explain how `Poly` is different from `Expr` but also how there isn't normally any need to use `Poly` because you can use functions like `factor` on `Expr`. There could be one or two examples of using the poly options with a clear note/link to more details.

2. A front page for the `Poly` class explaining what it is and what its generators and domain are. This page could explain how `Poly` chooses its generators and domain using the options. There could be a listing of all domains and all options (with explanations). There could be some explanation of how the string representations of domains correspond e.g. 'ZZ' and ZZ. This page could be linked to by all functions that take poly options to show examples of domain, extension etc.

3. A page that explains how to work with the Domains and DomainElements. It should begin by explaining the difference between them and then how to construct them, how to convert from one domain to another etc. This page should document the lower-level functions like `ring` etc. and could also illustrate how Poly actually uses the domains internally e.g.:
```
In [8]: p = Poly(x**2 + 1, x, domain=ZZ)

In [9]: p
Out[9]: Poly(x**2 + 1, x, domain='ZZ')

In [10]: p.rep
Out[10]: DMP([mpz(1), mpz(0), mpz(1)], ZZ, None)

In [11]: p.rep.rep
Out[11]: [mpz(1), mpz(0), mpz(1)]

In [12]: p.domain
Out[12]: ZZ
```

4. The rest of the poly docs after...

**Comment by oscarbenjamin** [comment]
There are a few deficiencies in the polys docs:

1. There isn't an introductory explanation of how/when to use the public API.

2. Many concepts/functions etc have quite formal definitions but those definitions are not explicitly stated e.g. in the docstrings.

3. The explanation of the "internals" does not particularly help to understand how to navigate/modify/improve the code.
