### ISSUE TITLE
set as input for lambdify

### ISSUE THREAD

**Issue by RobertoFranceschini** [sympy/sympy#19735]
I have seen that `lambdify` wants a list for the arguments to be treated as symbols. This list can be also give as a python `set`, e.g. `{x,y,z }`, which is exactly what would be returned by a `.free_symbol` property. If lambdify is feed a set like that of the output of .free_symbol it may change their order in the conversion from set to list. This is done silently and may cause major disfunction in the use of the lamdified function because you think x is x, but is y instead and so on. 
I would like to ask developers to check for the type of the lambdify list of arguments and throw a warning to flag that a set is being converted and that the ordering is not guaranteed.

Given that .free_symbols returns a set, not a list, this is very common pitfall in my opinion and must be prevented.

**Comment by oscarbenjamin** [comment]
I don't think it is very common because it is unusual to try and guess the symbols when using lambdify. There should be a way to get the symbols before creating the expression. As I said on SO you can get them directly from symarray:
https://stackoverflow.com/questions/62798213/keep-the-order-of-parameters-fixed-in-sympy-lambdify-from-free-symbols#comment111075099_62800716

In any case this is a reasonable suggestion and I imagine that the confusion coming from this is quite painful to debug.

It's probably an easy change to make so feel free to submit a pull request.

**Comment by RobertoFranceschini** [comment]
I have cloned sympy and made my stupid change at line 805
```
    if  type(args) is set:
         print('the list of arguments is a set. you should provide a list instead')
        return False
```

Now I'd like to try it in my notebook, but I need to import my own sympy from the local git repo. This escapes my mastery of imporlib ... [here](https://stackoverflow.com/questions/67631/how-to-import-a-module-given-the-full-path) there are a bunch of solutions but none seems to work for a complex package like sympy. Any suggestion on how to load my own sympy in a new notebook for testing?
Thanks

**Comment by Ayush-Malik** [comment]
@oscarbenjamin , Is there anyone working on this??

**Comment by Ayush-Malik** [comment]
@oscarbenjamin  Is there anyone working on this ??😀

**Comment by Ayush-Malik** [comment]
@Smit-create Hello i want to work on this , can you tell me what exactly i have to change and in which file 😀

**Comment by RobertoFranceschini** [comment]
I think there is a [pull request](https://github.com/sympy/sympy/pull/19792) ready to go, but some reviewer must merge it.

**Comment by sylee957** [comment]
Closing this since #19792 is fixed
