### ISSUE TITLE
Replace experimental lambdify in plots

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#19996]
Since experimental_lambdify is outdated a lot, it makes difficult to improve the plotting framework

In #19967 I had attempted some clean up for experimental lambdify, and I think that it can give a good start to identify what experimental_lambdify fundamentally had done before, that trying different lambdify candidates until finding one succeeds.

**Comment by Davide-sd** [comment]
Hello @sylee957 ,
I think you have much more experience than me about `lambdify` and `experimental_lambdify`. What are the blockers that are preventing the switch to `lambdify`?

**Comment by Davide-sd** [comment]
Found the answer. 

PR #20177

**Comment by asmeurer** [comment]
Is experimental_lambdify removed now? Is there a PR associated with it?

**Comment by Davide-sd** [comment]
@asmeurer It was achieved with #25469

**Comment by asmeurer** [comment]
That's great. It looks like experimental_lambdify is still intact, though. We should (possibly) [deprecate](https://docs.sympy.org/dev/contributing/deprecations.html) it and remove it. 

Also, was https://github.com/sympy/sympy/issues/23064 also fixed as part of this?

**Comment by Krastanov** [comment]
I wrote the plotting module 12 years ago, together with the rather ugly and hackish `experimental_lambdify`, which was a quick workaround for the severe limitations in `lambdify` at the time. I have not been involved lately, but had to look into this for other reasons, and I am extremely happy to see the issues that required the creation of `experimental_lambdify` have now been properly fixed in `lambdify` itself, in the years since I left the project.

As issue cleanup suggestions, I guess these can now be closed or reconsidered:

- https://github.com/sympy/sympy/issues/24524
- https://github.com/sympy/sympy/issues/23967
- https://github.com/sympy/sympy/issues/23468
- https://github.com/sympy/sympy/issues/16786
- what is happening with this rather fun one: https://github.com/sympy/sympy/issues/21751
- is this one still valid: https://github.com/sympy/sympy/issues/21542
- is this one still valid: https://github.com/sympy/sympy/issues/20382

**Comment by sylee957** [comment]
We may need to test case by case if the example works. Usually, experimental_lambdify could be indirect causes of such issues.
