### ISSUE TITLE
Are there detail steps to solve quadratic equation in one variable?

### ISSUE THREAD

**Issue by xlfsc** [sympy/sympy#20281]
I want to get the detail steps of solve quadratic equation in one variable, like x**2 - 2*x+1=0.
use:
    sympy.solve([x**2 - 2*x +1])
get the result: [{x: 1}]

how can I get the detail steps throught sympy?

Thanks

**Comment by pvshingala1997** [comment]
Shall I try it?

**Comment by oscarbenjamin** [comment]
There isn't an explicit way to get the steps but in the example you show it's just a case of factoring the polynomial
```
In [9]: p = x**2 - 2*x + 1                                                                                                                     

In [10]: p                                                                                                                                     
Out[10]: 
 2          
x  - 2⋅x + 1

In [11]: factor(p)                                                                                                                             
Out[11]: 
       2
(x - 1) 
```
From there it's pretty clear that the only root is 1.

I'm closing this because github issues are not for asking questions about using sympy. A github issue is for reporting problems with sympy or for suggesting changes.

You can use the sympy mailing list or stackoverflow to ask questions about using sympy.
