### ISSUE TITLE
Issue when using "conjugate" in solving equations

### ISSUE THREAD

**Issue by PatOnyx** [sympy/sympy#20305]
I'm not sure if I do things right as I'm pretty new to sympy but I was trying to solve an equation with complex numbers.
Here is the two simple equations to solve.
Equation 1 is correctly solved.
But equation 2 has no solution according to sympy, which is incorrect.
What is the reason ? 

```python
from sympy import init_printing, conjugate

from sympy.abc import x, y
from sympy import I, conjugate
from sympy import solve

init_printing()

print("Eq 1.")
eq1= x -3 + I
s1= solve(eq1)
print (s1)


print("Eq 2.")
eq2=conjugate(x) -3 + I 
s2= solve(eq2)
print (s2)
```
The output is
Eq 1.
[3 - I]

Eq 2.
[]

**Comment by KKVANONYMOUS** [comment]
@PatOnyx 
For solving such kind of equations you can use `nsolve()` which will return the correct solution.
```
eq2=conjugate(x) -3 + I 
s2= nsolve(eq2,I)
print (s2)
```

The above code will give you the following output
`3.0 + 1.0*I`

For more information you can check [here](https://docs.sympy.org/latest/modules/solvers/solvers.html)

Hope this solves your query :)

**Comment by Maelstrom6** [comment]
Sadly, `nsolve` is a numerical solver and can only provide 1 single numerical answer. If your equation has more than 1 solution or unknown constants, `nsolve` cannot solve it.

It seems `solve` does not like to solve for conjugates of variables. This is probably because the equation can become very complicated if you have `x`s and `conjugate(x)`s in the equation. This is still an issue.

As a work around, I would recommend substituting `x` for `a+bi` instead and then solving for `a` and `b` simultaneously. 

```python
from sympy import *
x = symbols('x', complex=True)
a, b = symbols('a b', real=True)
eq2 = conjugate(x) - 3 + I
eq2 = eq2.subs(x, a + b*I)
s2 = solve(eq2, [a, b])
print(s2[a] + s2[b]*I)
```

The second argument in `solve` tells it which variables to solve for. This way you can have other constants in the equation that it will not solve for constants like `c` or something.

**Comment by r7rohan** [comment]
Can this substitution be done inside `solve`? This would make solving easier with conjugates.

**Comment by oscarbenjamin** [comment]
I think that `solve` should be taught how to invert the conjugate function.

**Comment by Maelstrom6** [comment]
It should be pretty easy to do so if expr is only a function of `conjugate(x) `. The inverse of the conjugate is the conjugate. The main problem comes if we have something like `x/conjugate(x)`. Or something else that involves both an `x` and a `conjugate(x)`.

I haven't tried it, but maybe `solve` works better with `abs(x)` and `arg(x)`. If that is the case, then it will be way easier to rewrite `conjugate(x)` as `abs(x)exp(-I*arg(x))`.

**Comment by oscarbenjamin** [comment]
For simple cases like this adding an inverse method to conjugate works:
```diff
diff --git a/sympy/functions/elementary/complexes.py b/sympy/functions/elementary/complexes.py
index 6d7ea7c989..8b24fdb2d4 100644
--- a/sympy/functions/elementary/complexes.py
+++ b/sympy/functions/elementary/complexes.py
@@ -811,6 +811,9 @@ class conjugate(Function):
     """
     _singularities = True  # non-holomorphic
 
+    def inverse(self):
+        return conjugate
+
     @classmethod
     def eval(cls, arg):
         obj = arg._eval_conjugate()
```
