### ISSUE TITLE
Different `.evalf()` precisions with `x` and `FiniteSet(x)`

### ISSUE THREAD

**Issue by Maelstrom6** [sympy/sympy#20379]
The working precision must be different when working with expressions and sets of expressions. See the following:

```python
from sympy import *

x = pi - 3.14159265358979
print(x.evalf())  # more correct
print(FiniteSet(x).evalf())  # less correct
```
Giving
```python
3.23108914886517e-15
FiniteSet(3.10862446895044e-15)
```
That is almost a 5% error which is not good. The "correct" answer is `x.evalf()`. The `FiniteSet` version must be using a reduced precision.

Is this possible to be fixed? I'm not that familiar with the `.evalf()` source.

Is there any way to manually change this in the meantime? I don't want to write `FiniteSet(*[arg.evalf() for args in A])`.

**Comment by oscarbenjamin** [comment]
I'm sure that it can be fixed but I'm not sure where exactly the problem lies.

**Comment by oscarbenjamin** [comment]
The problem is that in the FiniteSet case evalf recurses to the args like this:
https://github.com/sympy/sympy/blob/b3cae120dad022dd83e338df69c45f60dd95efd9/sympy/sets/sets.py#L1886-L1887

Since that calls `_evalf` the call will go through to `_eval_evalf` which in the case of an `Add` means `AssocOp._eval_evalf`:
https://github.com/sympy/sympy/blob/b3cae120dad022dd83e338df69c45f60dd95efd9/sympy/core/operations.py#L354

However calling `x.evalf()` leads to `evalf(x, ...)` where the `evalf` function is the internal function here:
https://github.com/sympy/sympy/blob/b3cae120dad022dd83e338df69c45f60dd95efd9/sympy/core/evalf.py#L1321

The dispatches through the table to call `evalf_add`:
https://github.com/sympy/sympy/blob/b3cae120dad022dd83e338df69c45f60dd95efd9/sympy/core/evalf.py#L519

The `evalf_add` function has a special handler to ensure accuracy in the face of cancellation.

It seems that when recursing down the args in an evalf call the function to use should be `evalf(x, ...)` (as is done in the internal routines in the evalf module). The alternatives are all problematic:
1) The `x.evalf()` method takes the wrong kind of precision and is the public method.
2) The `x._evalf()` method just called `x._eval_evalf` and handles a `None` return. Perhaps this method isn't needed at all.
3) The `x._eval_evalf` method bypasses the table so it won't e.g. lead to `evalf_add`.

However the `evalf(x, ...)` function also isn't suitable for recursion from `x._eval_evalf` because the `_eval_evalf` method doesn't receive the arguments that should be passed to `evalf(x, ...)`. The `_eval_evalf` method is clearly the way for non-core classes to implement `evalf` but there does not seem to be a proper way for such a method to recurse to its args.

This all seems like a bit of a mess to me and indeed usage around the codebase of `.evalf`, `._evalf` and `._eval_evalf` is inconsistent.

**Comment by sidhu1012** [comment]
@oscarbenjamin  #20451 may be fix it. Please review.

**Comment by Maelstrom6** [comment]
I think I have a quick workaround for this: just use `.evalf(30)` or something similar. The difference only starts now at about the 13th decimal place.
