### ISSUE TITLE
SymPy not computing eigenvalues for 5 x 5 matrix

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#20582]
Reported from https://stackoverflow.com/questions/65170764/is-it-possible-somehow-to-find-complex-eigenvalues-using-sympy

```
>>> A = Matrix([[5, -5, -3, 2, -7], [-2, -5, 0, 2, 1], [-2, -7, -5, -2, -6], [7, 10, 3, 9, -2], [4, -10, 3, -8, -4]])
>>> A.eigenvals()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./sympy/matrices/matrices.py", line 372, in eigenvals
    return _eigenvals(self, error_when_incomplete=error_when_incomplete, **flags)
  File "./sympy/matrices/eigen.py", line 177, in _eigenvals
    **flags)
  File "./sympy/matrices/eigen.py", line 227, in _eigenvals_dict
    .format(block))
sympy.matrices.common.MatrixError: Could not compute eigenvalues for Matrix([[5, -5, 2, -3, -7], [-2, -5, 2, 0, 1], [7, 10, 9, 3, -2], [-2, -7, -2, -5, -6], [4, -10, -8, 3, -4]]). if you see this error, please report to SymPy issue tracker.
```

I believe the issue is the same as https://github.com/sympy/sympy/issues/20275. The characteristic polynomial is degree 5, so can't be solved explicitly. However, SymPy should just return a list of RootOf classes in this case, rather than an error (especially if the error is going to suggest that this is necessarily a bug).

**Comment by asmeurer** [comment]
Apparently there's a flag, `error_when_incomplete`, which when set to False causes eigenvals() to return {}. I don't see the need for this. We can represent all the eigenvalues using RootOf if necessary. Is the issue about determining the multiplicity of unknown eigenvalues, or is it just that `roots()` doesn't return RootOf?

**Comment by oscarbenjamin** [comment]
A better error message would reference the Abel-Ruffini theorem!

We could return RootOf for these (when the coefficients are Rational). RootOf is extremely slow though so it would be difficult to do anything else like find the eigenvectors, Jordan form etc. DomainMatrix can give a much more efficient implementation for working with RootOf using a quotient ring based on the minimal polynomial.

**Comment by asmeurer** [comment]
Eigenvectors are a whole other problem. That's already slow when the eigenvalues are closed form but complicated. At least a RootOf eigenvector can be computed numerically.

**Comment by oscarbenjamin** [comment]
With DomainMatrix we could also handle closed form eigenvectors much more efficiently as well. We just need to factor the characteristic polynomial into irreducibles: we don't even need to compute any formula for the roots. For each factor we can compute (once) the result of `nullspace(M - e*I)` using arithmetic over the quotient ring of the irreducible factor. That nullspace calculation would hold for each root of the factor. We also know that an irreducible factor can never have a multiple root. We could then express the whole result in terms of RootOf at the end.

**Comment by sylee957** [comment]
What if any coefficients of the polynomial are symbolic?
There is no way to determine if the polynomial like `a*x**2 + b*x + c` is actually irreducible or not, but I we should rather set an hyphothesis that the polynomial is irreducible in the nondegenerate condition. Although I believe that the polynomial algebra can handle this naturally with coefficient domain `ZZ[a, b, c]`.

**Comment by sylee957** [comment]
We may also need to decide whether using explicit cubic root or quartic root formula is bad or not for computing eigenvectors.

**Comment by oscarbenjamin** [comment]
> What if any coefficients of the polynomial are symbolic?

I was thinking of a matrix of only Rational because RootOf only works for rational coefficients. The approach probably generalises to Gaussian rationals but it becomes problematic when there are symbols. The implementation can cope with polynomial coefficients just fine but as you say the results would only be valid for the generic case.

That's true of almost everything though. If we have a matrix with symbols in it then most likely we don't know whether it is defective or not or whether there are any repeating roots etc. We already return results for those cases

**Comment by sylee957** [comment]
```python3
from sympy import *
from sympy.polys.domainmatrix import DomainMatrix
from sympy.polys.factortools import dup_factor_list


def nullspace(M, domain):
    rref, pivots = M.rref()
    rref = rref.rep
    rows, cols = M.shape

    basis = []
    for i in range(cols):
        if i in pivots:
            continue
        vec = [domain.one if i == j else domain.zero for j in range(cols)]
        
        for ii, jj in enumerate(pivots):
            vec[jj] -= rref[ii][i]

        basis.append(vec)
    
    return basis


def eigenvects(A):
    rows, cols = int(A.rows), int(A.cols)
    domain, items = DomainMatrix.get_domain(list(A), field=True)
    items = [[items[cols*r + c] for c in range(cols)] for r in range(rows)]
    A = DomainMatrix(items, (rows, cols), domain)

    charpoly = A.charpoly()
    _, factors = dup_factor_list(charpoly, domain)

    eigenvects = []
    l = Dummy('lambda')
    for base, exp in factors:
        if len(base) == 2:
            eigenvalue = -base[-1]
            
            eye = []
            for i in range(rows):
                eye.append([eigenvalue if i == j else domain.zero for j in range(cols)])
            eye = DomainMatrix(eye, (rows, cols), domain)

            eig_mat = A - eye
            vects = nullspace(eig_mat, domain)
            
            new_vects = []
            for vect in vects:
                new_vect = []
                for item in vect:
                    new_vect.append(domain.to_sympy(item))
                new_vect = Matrix(new_vect)
                new_vects.append(new_vect)
            vects = new_vects
            
            eigenvalue = domain.to_sympy(eigenvalue)
            eigenvects.append([eigenvalue, exp, vects])
        
        else:
            minpoly = Poly(base, l, domain=domain)
            
            for i in range(len(base) - 1):
                eigenvalue = CRootOf(minpoly, i)
                algebraic_field = domain.algebraic_field(eigenvalue)
                A_alg = DomainMatrix(
                    [[algebraic_field(x) for x in row] for row in items], (rows, cols), algebraic_field)

                eye = []
                for i in range(rows):
                    eye.append([algebraic_field([1, 0]) if i == j else algebraic_field.zero for j in range(cols)])
                eye = DomainMatrix(eye, (rows, cols), algebraic_field)

                eig_mat = A_alg - eye
                vects = nullspace(eig_mat, algebraic_field)

                new_vects = []
                for vect in vects:
                    new_vect = []
                    for item in vect:
                        new_vect.append(algebraic_field.to_sympy(item))
                    new_vect = Matrix(new_vect)
                    new_vects.append(new_vect)
                vects = new_vects
                
                eigenvects.append([eigenvalue, exp, vects])
    return eigenvects
        
    
A = Matrix([[5, -5, -3, 2, -7], [-2, -5, 0, 2, 1], [-2, -7, -5, -2, -6], [7, 10, 3, 9, -2], [4, -10, 3, -8, -4]])
A = Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
for val, mult, vects in eigenvects(A):
    print(f"Eigenvalue: {val.evalf()}")
    for vect in vects:
        print(f"Eigenvector: {vect.evalf()}")
```

I have a basic unoptimized implementation for this, but I think that there are too many utilities lacking that would introduce lots of boilerplates

I think that using quotient ring with final substitution is better than using algebraic number fields because it would be easier to support than rational coefficients and there would be less boilerplate to create arbitrary indexed algebraic element, but I don't think that `QuotientRing` works as a field object even with irreducible polynomials.
Is there is a way to make QuotientRing as a field?

**Comment by oscarbenjamin** [comment]
> I have a basic implementation for this that suffers from lots of boilerplates

Yes, there is plenty that can be added to DomainMatrix to make it more usable. At the moment it's a proof of concept but I think it does prove the concept. We just need to figure out how to extend it while keeping the API clean and without compromising performance. Right now only one small part of DomainMatrix is actually used but it already gives benefits e.g. #20274.

The implementation above looks good and we can add that. The pieces can be optimised later if needed. Probably it makes sense to add pieces one by one to DomainMatrix that make it more usable and then refactor later on. As long as it's still "private" I think we can change the functions/methods in incompatible ways in future. I think the main thing is just to make sure that we can expose the performance benefits while keeping the class itself buried away.

> Is there is a way to make QuotientRing as a field?

A quotient ring over a field is a field i.e. if K is a field then `K[x]/p(x)` is a field. Probably the best for this nullspace calculation would be to use `FiniteExtension` as discussed in #20608. I think some features need to be added to make it work though like `to_sympy`, `is_field` etc.

**Comment by asmeurer** [comment]
For symbolic coefficients, the difficulty is distinguishing the cases where two eigenvalues are actually equal. For example, `Matrix([[x, 1], [0, 1]]).eigenvects()` gives an answer that is wrong if `x = 1`. In DomainMatrix if the entries are part of a rational function field Q(x1, x2, ...), then x1, x2, ... are formally treated as transcendentally independent extensions, so this isn't an issue there (formally, DomainMatrix ought to only work for matrices with entries where zero equivalence is completely defined). 

But for general symbolic matrices, we can't even mathematically assume symbolic values are independent (e.g., it would be incorrect to assume `sin(x)` and `cos(x)` are independent). And there's also the problem that people usually think of symbolic constants as being able to take on any value (so in the above, x "could" be 1). 

However, I think even in this case we can still represent the eigenvalues symbolically. We just have to be careful about eigenvectors. I'm not sure how to handle them.

By the way, is DomainMatrix being used in heurisch? It looks like it is using sympy.polys.solvers, which uses it. Have there been any performance improvements there?

**Comment by oscarbenjamin** [comment]
> But for general symbolic matrices, we can't even mathematically assume symbolic values are independent (e.g., it would be incorrect to assume `sin(x)` and `cos(x)` are independent).

It would be good to be able to handle that case (hence #20608). It is something that can be handled correctly in a reasonable way but it's a bunch of work to make it happen.

> And there's also the problem that people usually think of symbolic constants as being able to take on any value (so in the above, x "could" be 1).

This is a more fundamental problem. I think at some point we have to say "this function returns results that are valid in the generic case" because even if it was computationally feasible to return a mathematically correct mess of Piecewise most users wouldn't want that. Actually that's already the de facto state of affairs for many of our functions.

This applies across everything (see #16861 - I've referred to it so many times I've memorised the issue number!):
```python
In [1]: from sympy.abc import a, b, c, x

In [2]: roots(a*x**2 + b*x + c, x)  # a might be zero
Out[2]: 
⎧           _____________                _____________   ⎫
⎪          ╱           2                ╱           2    ⎪
⎨   b    ╲╱  -4⋅a⋅c + b          b    ╲╱  -4⋅a⋅c + b     ⎬
⎪- ─── - ────────────────: 1, - ─── + ────────────────: 1⎪
⎩  2⋅a         2⋅a              2⋅a         2⋅a          ⎭
```
Currently eigenvals returns solutions that are generically correct. Moving to a polys implementation like this would continue that. If we wanted to change that to take account of these things then we could still have a better implementation if it was based on the polys domains. It would be more work either way.

> By the way, is DomainMatrix being used in heurisch? It looks like it is using sympy.polys.solvers, which uses it. Have there been any performance improvements there?

At some point I think I saw improvements in the time to run the heurisch test suite. In particular heurisch uses `solve_lin_sys` which uses `DomainMatrix`. Possibly more importantly `solve_lin_sys` uses the connected components algorithm to reduce the system (I think that's when I saw a difference). That's potentially a big optimisation for sparse systems like the ones that come up there.

Much of integrals is using PolyMatrix though which is based on Matrix even though it should clearly be based on DomainMatrix. @sylee957 looked at changing that but the difficulty is that PolyMatrix allows a mix of Expr/Poly and integrals seems to depend on that mixing.

**Comment by sylee957** [comment]
```python3
from sympy import *
from sympy.polys.domainmatrix import DomainMatrix, DDM, ddm_isub, ddm_irref
from sympy.polys.factortools import dup_factor_list
from sympy.polys.domains.quotientring import QuotientRingElement


def ddm_nullspace(M):
    rows, cols = M.shape
    domain = M.domain
    
    pivots = ddm_irref(M)
    rref = M
    
    basis = []
    for i in range(cols):
        if i in pivots:
            continue
        vec = [domain.one if i == j else domain.zero for j in range(cols)]
        for ii, jj in enumerate(pivots):
            vec[jj] -= rref[ii][i]
        basis.append(vec)
        
    return basis


def ddm_from_sympy_matrix(A):
    rows, cols = int(A.rows), int(A.cols)
    domain, items = DomainMatrix.get_domain(list(A), field=True)
    items = [[items[cols*r + c] for c in range(cols)] for r in range(rows)]
    return DDM(items, (rows, cols), domain)


def ddm_eigenvects(A, l=Dummy('lambda')):
    charpoly = A.charpoly()
    rows, cols = A.shape
    domain = A.domain
    _, factors = dup_factor_list(charpoly, domain)
    
    eigenvects = []
    for base, exp in factors:        
        ring = domain.old_poly_ring(l)
        ideal = ring.ideal(ring(base))
        field = ring.quotient_ring(ideal)
        
        AA_items = [[field([item]) for item in row] for row in A]
        AA = DDM(AA_items, (rows, cols), field)
        EE_items = [[field([domain.one, domain.zero]) if i == j else field.zero for j in range(cols)] for i in range(rows)]
        EE = DDM(EE_items, (rows, cols), field)
        
        ddm_isub(AA, EE)
        basis = ddm_nullspace(AA)

        eigenval = field([domain.one, domain.zero])
        eigenvects.append((eigenval, exp, basis))
        
    return eigenvects


def ddm_eigenvects_to_sympy(rational_eigenvects):
    algebraic_eigenvects = []
    
    for eigenvalue, multiplicity, eigenvects in rational_eigenvects:
        if isinstance(eigenvalue, QuotientRingElement):
            field = eigenvalue.ring
            ring = field.ring
            ideal = field.base_ideal
            minpoly = tuple(ideal.gens)[0]
            l = ring.symbols[0]
            
            eigenvects = [[x.data for x in vect] for vect in eigenvects]
            for idx in range(minpoly.degree()):
                eigenvalue = CRootOf(ring.to_sympy(minpoly), l, idx)
                new_eigenvects = [Matrix([ring.to_sympy(x).subs(l, eigenvalue) for x in vect]) for vect in eigenvects]
                algebraic_eigenvects.append((eigenvalue, multiplicity, new_eigenvects))
                
        else:
            assert False
    
    return tuple(algebraic_eigenvects)


    
A = Matrix([[5, -5, -3, 2, -7], [-2, -5, 0, 2, 1], [-2, -7, -5, -2, -6], [7, 10, 3, 9, -2], [4, -10, 3, -8, -4]])
#A = Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

A = ddm_from_sympy_matrix(A)
%time eigenvects = ddm_eigenvects(A)
%time algebraic_eigenvects = ddm_eigenvects_to_sympy(eigenvects)

for eigenvalue, multiplicity, eigenvects in algebraic_eigenvects:
    print(eigenvalue.evalf())
    for vect in eigenvects:
        print(vect.evalf())
```
```diff
$ git diff
diff --git a/sympy/polys/domains/quotientring.py b/sympy/polys/domains/quotientring.py
index cae78c3567..5a257f8966 100644
--- a/sympy/polys/domains/quotientring.py
+++ b/sympy/polys/domains/quotientring.py
@@ -30,6 +30,11 @@ def __str__(self):
         from sympy import sstr
         return sstr(self.data) + " + " + str(self.ring.base_ideal)

+    __repr__ = __str__
+
+    def __bool__(self):
+        return not self.ring.is_zero(self)
+
     def __add__(self, om):
         if not isinstance(om, self.__class__) or om.ring != self.ring:
             try:
@@ -71,7 +76,9 @@ def __truediv__(self, o):
         return self.ring.revert(o)*self

     def __pow__(self, oth):
-        return self.ring(self.data**oth)
+        if oth < 0:
+            return self.ring.revert(self) ** -oth
+        return self.ring(self.data ** oth)

     def __eq__(self, om):
         if not isinstance(om, self.__class__) or om.ring != self.ring:
```

I have a more efficient draft that uses quotient ring and I have avoided using DomainMatrix with DDM, but it needs some modification to quotient ring framework because it doesn't work well with `ddm_irref`

**Comment by sylee957** [comment]
The above example still hangs for computing `3x3` symbolic eigenvectors `A = Matrix(3, 3, symbols('a_0:9'))` which Mathematica is able to compute in milliseconds.
Maybe there are slowdown issues for quotient rings with symbolic coefficients, so we may need to disallow them.

**Comment by oscarbenjamin** [comment]
I think it's good to get something that works into the codebase even if it's only efficient for some domains right now.

There is a lot of potential for micro-optimisation of the domains but it doesn't need to come all at once. Ideally though we should write higher-level pieces in terms of reusable lower-level pieces that can optimised.

**Comment by oscarbenjamin** [comment]
> The above example still hangs for computing `3x3` symbolic eigenvectors `A = Matrix(3, 3, symbols('a_0:9'))`

It's worth noting the order of performance here which is that the fastest domains are those with a concrete atomic implementation e.g.: ZZ, QQ, ZZ_I, QQ_I, RR and CC.

The next fastest is an algebraic extension. Elements in an algebraic extension have a finite representation over the base field so e.g. `QQ<t>` where `t` is algebraic is a finite dimensional vector space over `QQ` which limits the possibility for complex expressions to appear.

After algebraic extensions we have polynomial rings like `QQ[x]` where since `x` is transcendental we have representations of arbitrary size that grow into long and complicated expressions.

Lastly we have rational function fields like `QQ(x)`. These are the slowest domains and they get particularly slow when there are many generators e.g. `QQ(x, y, z, ...)`. In this domain every arithmetic operation is followed by a call to cancel. This is analogous to cancelling the gcd when working in QQ. Much like ZZ is often lot faster than QQ we have that e.g. `QQ[x]` is a lot faster than `QQ(x)`. The gcd calculations for `QQ(x, y, z, ...)` are potentially very slow though.

What that means is that we should try where possible to work over rings like `Q[x]` if possible rather than the corresponding field `Q(x)`. I think that some cases where DomainMatrix.rref is slow could be improved substantially with this. In the case of rref it should be possible to bring the matrix into echelon form while working over a ring. This can be done either with division-free row reduction or fraction-free (e.g. the Bareiss algorithm). At that point if all pivots are units then it's possible to complete the rest of rref still working over the ring. Otherwise there will need to be some calculations over the field in the back substitution step but minimising those where possible is likely worth doing.

Here if you have a matrix that is `QQ[x, y, z]` with eigenvalue `t` you could use `FiniteExtension` to work over `QQ[x, y, z][t]/p(t)`. Alternately if the eigenvalue itself is algebraic in the rationals then you can use `QQ<t>[x, y, z]`. The more we can do with those rings I think the better.

The other point is that pivoting can make a big difference. Depending on pivot choice you can end up making the rest of the matrix have much more complicated expressions in the intermediate steps. How to choose a good pivot depends on the domain.

**Comment by sylee957** [comment]
I'm not sure about the technical details for ring RREF, but I'd first speculate that it first merges all the denominator together and work with much more complicated numerator, so I'm not 100% sure if this works better than field RREF. But it can be worth trying out.

**Comment by oscarbenjamin** [comment]
I'm talking about something like unimodular matrices:
https://en.wikipedia.org/wiki/Unimodular_matrix#Abstract_linear_algebra

The same sort of concept applies to non-square or non-invertible matrices in the sense that it is only necessary to divide by certain elements in row reduction calculations. If we are lucky and those turn out to be invertible in the ring (e.g.1 or -1 or I etc) then we can work entirely in the ring. Otherwise we can at least get to echelon form without needing to use a field.

**Comment by oscarbenjamin** [comment]
This changes can make `FiniteExtension` usable with `DomainMatrix`:
```diff
diff --git a/sympy/polys/agca/extensions.py b/sympy/polys/agca/extensions.py
index f0be073f1b..92668d5d2c 100644
--- a/sympy/polys/agca/extensions.py
+++ b/sympy/polys/agca/extensions.py
@@ -22,6 +22,9 @@ def __init__(self, rep, ext):
         self.rep = rep
         self.ext = ext
 
+    def __bool__(f):
+        return bool(f.rep)
+
     def __neg__(f):
         return ExtElem(-f.rep, f.ext)
 
@@ -225,10 +228,15 @@ def __init__(self, mod):
         self.basis = tuple(self.convert(gen**i)
                       for i in range(self.rank))
 
+        self.is_Field = self.domain.is_Field
+
     def convert(self, f):
         rep = self.ring.convert(f)
         return ExtElem(rep % self.mod, self)
 
+    def to_sympy(self, f):
+        return self.ring.to_sympy(f.rep)
+
     __call__ = convert
 
     def __str__(self):
```
Demo:
```python
from sympy import *
from sympy.polys.agca.extensions import FiniteExtension
from sympy.polys.domainmatrix import DomainMatrix

t = Symbol('theta')
K = FiniteExtension(Poly(sin(t)**2 + cos(t)**2 - 1, sin(t), field=True))
s = K.convert(sin(t))
c = K.convert(cos(t))
dM = DomainMatrix([[c, s], [-s, c]], (2, 2), K)

print(dM.det())
print((dM * dM.inv()).to_Matrix())
```

**Comment by sylee957** [comment]
Should FiniteExtension be recognized as field if the modulus is not irreducible?
```
x = Symbol('x')
K = FiniteExtension(Poly(x**2 - 1, x, field=True))
K(x - 1) ** -1
```

**Comment by oscarbenjamin** [comment]
> Should FiniteExtension be recognized as field if the modulus is not irreducible?

No, I don't think so. I'm not sure what the correct check should be.

**Comment by oscarbenjamin** [comment]
I guess it's not hard to check if the modulus is irreducible:
```
In [2]: Poly(x**2 - 1).is_irreducible
Out[2]: False
```

**Comment by sylee957** [comment]
It may be easy to check in usage, but it may not be easy to check in computationally cheap way since I see is_irreducible uses `dmp_factor_list` which computes the complete factorization.

**Comment by oscarbenjamin** [comment]
If the modulus polynomial is really large then everything is going to be slow. A single attempt to factor it probably won't count for much but it could at least be delayed rather than used in the constructor.

**Comment by jksuom** [comment]
If the domain of a finite extension is a field, then it is possible to divide by all nonzerodivisors, division by zerodivisors will raise. For example, if the polynomial defining the finite expression is separable, then the extension is a product of fields. Its nonzerodivisors are tuples having no zero component, and division by such elements is well defined. That will probably suffice in many (most?) applications. Should there be a new property `is_xxx` for such domains?

**Comment by oscarbenjamin** [comment]
Do you think that there is any use for such quasifields in sympy?

For the eigenvectors it should always be possible to use an irreducible poly so it would always be a field.

**Comment by jksuom** [comment]
In `densearith`, `is_Field` is checked to decide whether to use exact division or division with remainder. If the domain is a finite extension, then exact division should probably be used in case its domain is a field even if the extension itself is not a field. But maybe it will be possible to work with irreducible defining polynomials so something like `is_quasifield` won't be necessary (at least for now).

**Comment by oscarbenjamin** [comment]
I think actually in the eigenvector case we need the poly to be irreducible. Otherwise there is a possibility for a multiple root and the form of the eigenvector would not necessarily be the same for all roots of the poly. Maybe that is precisely the situation that would lead to zero divisors when computing the nullspace.

**Comment by asmeurer** [comment]
> Lastly we have rational function fields like QQ(x). These are the slowest domains and they get particularly slow when there are many generators e.g. QQ(x, y, z, ...). 

Is this using the dense or sparse representation? The dense representation is slow for many generators, but it's only because of the representation. 

> In this domain every arithmetic operation is followed by a call to cancel. This is analogous to cancelling the gcd when working in QQ. Much like ZZ is often lot faster than QQ we have that e.g. QQ[x] is a lot faster than QQ(x). The gcd calculations for QQ(x, y, z, ...) are potentially very slow though.

Maybe we need a version of field domains that don't do cancellation automatically. For RREF, you only need zero detection to work, which doesn't require cancellation. Cancellation would only be done when necessary for correctness of an algorithm, or when requested by the user. The downside is that if you don't cancel, the expressions/numbers can get large. So it's possible it could actually be slower in the full algorithm.

**Comment by sylee957** [comment]
It is a different problem than cancellation because the field we are dealing with at the crust is based on modulus, not fraction.

Of course, I believe that it's the problem of the ground domain of the extension to be a field than a ring 
(Like you may expect that gaussian integer can be used in place of gaussian rational)

But as far as I'm familiar with, algebraic extensions are mostly studied over fields and not over the rings.
I'm not sure if ![image](https://user-images.githubusercontent.com/34944973/102652834-61c13180-41b1-11eb-91b9-c4c0e308e895.png) can replace ![image](https://user-images.githubusercontent.com/34944973/102652865-70a7e400-41b1-11eb-934b-8ceffc3532e2.png), and how the former one should be computed.

**Comment by oscarbenjamin** [comment]
The algebraic extension of `Z[x, y]` by `z` is just `Z[x, y][z]/p(z)`. It's the ring of polynomials in x, y, z with integer coefficients but where higher powers of z are reduced by `p(z)`. The implementation of rref always converts it to a field just because then division is possible: the complete rref is not in general computable over a ring but it's possible to do some and sometimes all of the calculations over the ring - no attempt is made to do that though.

**Comment by asmeurer** [comment]
> The useful feature of cancellation is canonicalisation. Every possible element has a unique representation. This also tends to give simpler output. For example:

This is using normal expressions, which don't do any simplifications, except for the very simple ones that are done in the Add and Mul constructors. But for a poly representation, each polynomial would always be expanded, and the numerators and denominators would always be put under a common term. That's enough to get zero equivalence. It also avoids a large part of the expression explosion that happens with the naive RREF on expressions without simplifications. But you can still get a degree of expression explosion from common factors in the numerator and denominator, so I don't know if disabling cancellation completely until the end is a good idea or not. Cancellation can also be faster if done in intermediate stages using cross-gcd tricks (see https://github.com/sympy/sympy/issues/12602). 

The question is really about if you have an intermediate calculation where you only care about zero equivalence, is it a good idea to disable cancellation, or is it still a bad idea because of the expression explosion. To me, it isn't clear if it would be faster or slower, so it's worth testing. This discussion is also relevant for rational number matrices as well.

**Comment by oscarbenjamin** [comment]
I think that there are substantial performance gains to be made while still working with the current domains. The implementation here is still young. I'm sure there can be improvements in the domains as well. DomainMatrix pushes the Domain implementation in ways that it hasn't really been pushed before so that slowdowns emerge in places that didn't previously seem as significant e.g. https://github.com/sympy/sympy/pull/20274#issuecomment-745367609

The main point from this is that I think it is clear that DomainMatrix is the way to go for implementing matrices. The big question then is what we do from a public API perspective. We can have more PRs like the one that closed this where `Matrix` converts to `DomainMatrix` internally or we can think about something very different. Note that `DomainMatrix` is a lot faster even just for basic things like adding two matrices of integers. Switching `Matrix` to use a `DomainMatrix` all the time is not backwards compatible though because e.g. in the domains all polys get expanded.
