### ISSUE TITLE
cxxcode not setting precision for floating point values

### ISSUE THREAD

**Issue by 0sidharth** [sympy/sympy#20624]
Originally posted in sympy google groups [here](https://groups.google.com/g/sympy/c/zWfxxxAfV7I/m/MJFxU-RnBAAJ). 

Code - 
```
from sympy import *                                                             
                                                                                
T = Symbol('T')
a = 0.00437791
f = a*T
print(cxxcode(f, precision=8))
```
Output - 
```
0.0043779099999999996*T
```
Isn't the expected output 0.00437791*T? Or is the precision parameter referring to something else, and the output is as intended?

**Comment by bjodah** [comment]
The `precision` setting is quite unintuitive and, and in my experience, never worked as one might expect. Those extra decimals are nothing to worry about since their float64 representation is the same, with or without them printed (note that floating point literals without any literal suffix usually default to double precision in most C/C++ compilers for "common" systems/hardware). If you want to use lower precision, e.g. float32 (which gives you about 8 decimal digits of precision), you should look into passing `float32` as real (there is more work to be done in this area, but you can search for floa32 [in the tests](https://github.com/sympy/sympy/blob/master/sympy/printing/tests/test_c.py)).

**Comment by bjodah** [comment]
And if one actually want to change the number (e.g. use 3.14000 instead of `pi`), I'd recommend calling `.replace` on expressions, passing a function rounding to desired number of digits, before passing the expression to the printer.
