### ISSUE TITLE
Log and lambdify together create inconsistent behavior.

### ISSUE THREAD

**Issue by nathancarter** [sympy/sympy#20706]
We can write the expression `log(x)` as expected in SymPy.

```
>>> from sympy import *
>>> var('x')
x
>>> log(x)
log(x)
```

We can `lambdify` it and evaluate it on numerical inputs, also as expected.

```
>>> f = lambdify(x,log(x))
>>> f(2)
0.6931471805599453
```

But as soon as you attempt to evaluate it on a symbol, to get back the body that was originally passed to `lambdify`, an error occurs.

```
>>> f(x)
AttributeError: 'Symbol' object has no attribute 'log'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<lambdifygenerated-1>", line 2, in _lambdifygenerated
TypeError: loop of ufunc does not support argument 0 of type Symbol which has no callable log method
```

The expected behavior is that `lambdify(x,y)(x)` yields `y` for any symbolic expression `y`.

This may not seem like it matters here, because of course we could just do `f = log` instead.  But of course this is a minimal example; consider just `log(x+1)` instead, or any more complex expression involving a logarithm.

**Comment by oscarbenjamin** [comment]
The purpose of `lambdify` is to produce a function for efficient evaluation. By default it produces code that operates on numpy arrays. To that end your function has lambdified to `numpy.log` which is the most efficient way to compute this with numpy arrays. The error message that you see actually comes from numpy because numpy doesn't know how to work with sympy expressions.

You can use the modules argument to produce a callable that works with sympy expressions:
```
In [3]: func = lambdify(x, log(x), modules='sympy')

In [4]: func(x)
Out[4]: log(x)
```

**Comment by nathancarter** [comment]
Awesome, thank you!
