### ISSUE TITLE
Sympy solve returns `NoneType object not scriptable`

### ISSUE THREAD

**Issue by peteWT** [sympy/sympy#20747]
Reposting here from [StackOverflow](https://stackoverflow.com/q/65584940/1164096) per recommendation from @oscarbenjamin 

I have tested this with both `sympy==1.7.1` and `sympy==1.5.1` and get the same result.

    from sympy import *
    import inspect

    THT,HT,DBH,dib, c0,c1, c2,c3,c4  = symbols('THT HT DBH dib c0 c1 c2 c3 c4')
    init_printing()

    f = c2 + (c3*DBH) + (c4 * THT)
    rhs = 1 - (((HT-1)/(THT - 1))**c1)* (1- exp(c0/f))

    eqn = solve( dib - (DBH * (c0 - (f * ln(rhs)))), HT)

Which returns

```
# Out [37]: 
# output

TypeErrorTraceback (most recent call last)
<ipython-input-37-619e8281e2ae> in <module>
      9 # original rhs = 1 - (((HT-1)/(THT - 1))**c1)* (1- exp(c0/f))
     10 
---> 11 eqn = solve( dib - (DBH * (c0 - (f * ln(rhs)))), HT)
     12 
     13 #eqn = solve( dib - (DBH * (b1+b2 * ln(1-(lam*p)))), HT)

~/.pyenv/versions/3.7.0/lib/python3.7/site-packages/sympy/solvers/solvers.py in solve(f, *symbols, **flags)
   1095         ok = False
   1096         if fi.has(*symset):
-> 1097             ok = True
   1098         else:
   1099             if fi.is_number:

~/.pyenv/versions/3.7.0/lib/python3.7/site-packages/sympy/solvers/solvers.py in _solve(f, *symbols, **flags)
   1458         result = list(result)
   1459         if check:
-> 1460             # all solutions have been checked but now we must
   1461             # check that the solutions do not set denominators
   1462             # in any factor to zero

TypeError: 'NoneType' object is not subscriptable
:end:
```

I can solve the following paired-down version:

```
In [47]: solve( f * ln(rhs), HT)
Out[47]: 
⎡c1___       c1___    ⎤
⎣╲╱ 0 ⋅THT - ╲╱ 0  + 1⎦
```

and adding an integer in place of `c0` it will solve:

```
solve( 2-(f * ln(rhs)), HT)
```
[![enter image description here][1]][1]

But adding a symbol causes the `NoneType` error. Any suggestions would be much appreciated.

  [1]: https://i.stack.imgur.com/9Jp2e.png

**Comment by hailcpy** [comment]
@oscarbenjamin I want to contribute to sympy and have done a lot of debugging in this issue but i am stuck at debugging matches function.
I think the problem is with the matches function. The match fails in some cases as shown below. 
Here is the code to replicate that. I have used a simpler equation:
`>>> import sympy
>>> from sympy import *
>>> print(sympy.__version__)
1.7.1
>>> from sympy.abc import x
>>> THT,HT, c0,c1  = symbols('THT HT c0 c1')
>>> w=Wild('w')
>>> f_num = c1 - log(HT/THT)*(1 - exp(c0/(5)))
>>> f_num2 = c1 - log(w/THT)*(1 - exp(c0/(5)))
>>> print(f_num2.matches(f_num))
None
>>> f_num3 = 1 - log(HT/THT)*(1 - exp(c0/(5)))
>>> f_num4 = 1 - log(w/THT)*(1 - exp(c0/(5)))
>>> print(f_num4.matches(f_num3))
{w_: HT}
>>> f_num5 = c1 - log(HT/THT)*(1 - exp(2/(5)))
>>> f_num6 = c1 - log(w/THT)*(1 - exp(2/(5)))
>>> print(f_num6.matches(f_num5))
{w_: HT}
`
changing c0 to 2 or c1 to 1 gives current result.
I tried to debug and found that matches was causing problem but debugging matches was difficult. If i can understand how matches works i will debug the problem.
The issue could have a solution [https://brandonwillard.github.io/sympy-expression-tree-manipulation.html](here)

**Comment by oscarbenjamin** [comment]
That looks like it could be the cause. I agree that debugging `matches` is not easy.

**Comment by oscarbenjamin** [comment]
I think that there is a difference here:
https://github.com/sympy/sympy/blob/14c321748401864b7340f9c6c6a498b51b84adc0/sympy/core/add.py#L504-L509
The `as_coeff_add` method will return different results depending on whether or not c1 is a symbol or a pure number.

**Comment by hailcpy** [comment]
Here is one more variations which run properly. 
Just changing negative sign to positive in (1+exp(c0/5)) gives correct result.
```
>>> f_num = c1 - log(HT/THT)*(1 + exp(c0/(5)))
>>> f_num2 = c1 - log(w/THT)*(1 + exp(c0/(5)))
>>> print(f_num2.matches(f_num))
```
I will look into as_coeff_add, the problem is with multiply also so i think as_coeff_Mul also gives different results.
https://github.com/sympy/sympy/blob/219993505f88a8d6f825db1deaad939a28cbb78c/sympy/core/mul.py#L1020-L1027

**Comment by hailcpy** [comment]
@oscarbenjamin  i have found the cause of problem. It is because `signsimp()` is missing in` _combine_inverse` in mul.py which is present in `_combine_inverse` in add.py.
https://github.com/sympy/sympy/blob/219993505f88a8d6f825db1deaad939a28cbb78c/sympy/core/add.py#L535-L536
This `signsimp()` changes -(1-exp(c0/5) to (exp(c0/5)-1) which later due to  no signsimp in `_combine_inverse` in Mul results in `log(w/THT)*(exp(c0/5)-1)/(1-exp(c0/5))` rather than `log(w/THT)`. Changing `lhs/rhs` in `_combine_inverse` to `signsimp(lhs/rhs)` fixes the issue. I have checked all tests with this change and they all passed.
I have added a pull request.

**Comment by oscarbenjamin** [comment]
That sounds like a reasonable fix.

**Comment by peteWT** [comment]
Thank you @oscarbenjamin  and @hailcpy ! greatly appreciate your efforts debugging this. I will wait for the PR to be merged before attempting to test it myself.
