### ISSUE TITLE
Unique simplification of comparisson operators,  (1<a) ≠ (a>1)

### ISSUE THREAD

**Issue by ducktalez** [sympy/sympy#20765]
I really like the sympify function (`from sympy import sympify`) for the fact that it creates a unique representation of a formula:

```
>>> sympify('1+a')
a + 1
>>> sympify('a+1')
a + 1
```

However, a conversion between comparison-operators is not made, even though they should be equal:
```
>>> sympify('a<1')
a < 1
>>> sympify('1>a')
1 > a
```

Is this intended?
If yes, is there a way to force a conversion between the two symbols?

They also do not evalueate as equal with the sympy-equality:
```
>>> sympify('1+a') == sympify('a+1')
True
>>> sympify('a<1') == sympify('1>a')
False
```

**Comment by oscarbenjamin** [comment]
This is not intended but there is no way for sympy to stop this. The problem is that in both `1 < a` and `a > 1` Python calls `a.__gt__(1)` and the `__gt__` method has no way to know which direction the inequality was in:
https://docs.python.org/3.8/reference/datamodel.html#object.__lt__

You can either explicitly use `Gt` or you can use reversed:
```
In [1]: a = Symbol('a')

In [2]: (1 < a)
Out[2]: a > 1

In [3]: (1 < a).reversed
Out[3]: 1 < a

In [4]: Lt(1, a)
Out[4]: 1 < a
```

**Comment by asmeurer** [comment]
I think @ducktalez is actually asking for the reverse, for the two to be equal. This is undesired because if one always canonicalized to the other, it would be impossible to represent it. It is often more convenient to have an inequality as < or as >, depending on the specific inequality, it may be more readable. Which is why SymPy keeps them separate. Note that `==` in SymPy is structural equality only, not mathematical equality. `a == b` may be False even though `a` and `b` are both completely equivalent mathematically.

**Comment by asmeurer** [comment]
See also https://docs.sympy.org/latest/tutorial/gotchas.html#equals-signs and https://github.com/sympy/sympy/wiki/Automatic-Simplification

**Comment by ducktalez** [comment]
Thank you for your response! And, by the way, thank you for your great job with sympy, I get to enjoy more and more aspects of it every day!

I think I get your point, and it is correct that `>` or `>=` would be deprecated relations, which would be kind of sad. I am just, kind of, looking for a simplification which will create absolutely unique formulas, similar to a hasf-function function or so, which somehow contradicts with "4. The rule is so trivial that no one will ever not want it done."

Some simplifications of comparison operators thus seem to be simplified in a more complex way than one would do in school, for example:
```
>>> sympify('-1<-a')
-1 < -a
```

**Comment by asmeurer** [comment]
Very little simplification is done automatically (see the wiki page I linked to). If you want to simplify an expression, you should use a function like `simplify()` or one of the more directed simplification functions

```py
>>> simplify(sympify('-1<-a'))
a < 1
>>> simplify(sympify('1 > a'))
a < 1
```

(note the difference between simp**lify** and **symp**ify. The former simplifies a formula and the latter converts a string into a SymPy expression without any further simplification)

**Comment by ducktalez** [comment]
oh damn. Thank you, that solves the problem.
In fact, I thought the two functions were the same all along. My bad!
