### ISSUE TITLE
Derivate of this Sum returns 0

### ISSUE THREAD

**Issue by ctr26** [sympy/sympy#20777]
```
import sympy as sp
from sympy.concrete.summations import Sum
```

`Sum(sp.Derivative(sp.exp(x*sp.sin(n/m)),x),(n,1,m)).doit()
`
This works

`sp.Derivative(Sum(sp.exp(x*sp.sin(n/m)),(n,1,m)),x).doit()
`
This returns 0

**Comment by asmeurer** [comment]
This is the problem:

```py
>>> Sum(exp(x*sin(n/m)),(n,1,m))
Sum(exp(x*sin(n/m)), (n, 1, m))
>>> Sum(exp(x*sin(n/m)),(n,1,m)).doit()
Piecewise((m*exp(c3_), Eq(exp(c2_), 1)), ((exp(c2_) - exp(c2_*(m + 1)))*exp(c3_)/(1 - exp(c2_)), True))
```

It seems to not be replacing internal dummy variables with the actual variables in the expression.

**Comment by ctr26** [comment]
Is this something I'm doing wrong sorry?

**Comment by asmeurer** [comment]
The problem is here: https://github.com/sympy/sympy/blob/8f29f0350afaf49f0a1017399e5b9b37713a9c52/sympy/concrete/summations.py#L1181-L1185

It matches c2 and c3 in `wexp` and updates the matching dictionary if it matches. But in this case, `wexp` is `x*sin(n/m)` and it doesn't match. But the following lines assume that the match has all the Wild symbols. https://github.com/sympy/sympy/blob/8f29f0350afaf49f0a1017399e5b9b37713a9c52/sympy/concrete/summations.py#L1187-L1194

This patch fixes it. I'm not sure if there is something we can still do to make the sum evaluate (can this sum be computed in closed form?)

```diff
diff --git a/sympy/concrete/summations.py b/sympy/concrete/summations.py
index a8e083bc6c..8c5dfd801b 100644
--- a/sympy/concrete/summations.py
+++ b/sympy/concrete/summations.py
@@ -1183,6 +1183,8 @@ def eval_sum_symbolic(f, limits):
             e_exp = e.pop(wexp).expand().match(c2*i + c3)
             if e_exp is not None:
                 e.update(e_exp)
+            else:
+                e = None

         if e is not None:
             p = (c1**c3).subs(e)
```

```
>>> s = Sum(exp(x*sin(n/m)),(n,1,m))
>>> s.doit()
Sum(exp(x*sin(n/m)), (n, 1, m))
```

**Comment by asmeurer** [comment]
The tests seem to pass. I've submitted this as https://github.com/sympy/sympy/pull/20778

**Comment by oscarbenjamin** [comment]
See also #20523 and #20531
