### ISSUE TITLE
expand hangs

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#20956]
`v=5.0*(-103394997431911/1000000000000)**(y + 153096909707543/10000000000000)*(y + 163096909707543/10000000000000) - 264270128206571/100000000000000000000000000`
`w=5*(-39*E + 5*pi/6)**(y - 1 + 6*E)*(y + 6*E) - exp(-10*E + pi/6)`

`(v-w).expand()` hangs. If I set `deep=False`, then everything seems working.

**Comment by oscarbenjamin** [comment]
It works fine here:
```python
In [1]: v=5.0*(-103394997431911/1000000000000)**(y + 153096909707543/10000000000000)*(y + 163096909707543/10000000000000) - 264270
   ...: 128206571/100000000000000000000000000

In [2]: w=5*(-39*E + 5*pi/6)**(y - 1 + 6*E)*(y + 6*E) - exp(-10*E + pi/6)

In [3]: %time ok = (v-w).expand()
CPU times: user 22.3 ms, sys: 2.79 ms, total: 25.1 ms
Wall time: 23.2 ms
```
I guess that you meant for the numbers in `v` to be Rational e.g.:
```python
In [5]: v=5.0*(-S(103394997431911)/1000000000000)**(y + S(153096909707543)/10000000000000)*(y + S(163096909707543)/10000000000000) - S(264270128206571)/100000000000000000000000000
```
With that it hangs and I get the traceback below:
```python
In [6]: %time ok = (v-w).expand()
^C---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
```
Interrupting in the debugger I find that it hangs because it is trying to compute `10**1837162916490332`:
```
KeyboardInterrupt: 
> /Users/enojb/current/sympy/sympy/sympy/core/numbers.py(2374)_eval_power()
   2372             div_e, div_m = divmod(exponent, expt.q)
   2373             if div_e > 0:
-> 2374                 out_int *= prime**div_e
   2375             if div_m > 0:
   2376                 # see if the reduced exponent shares a gcd with e.q

ipdb> p prime
10
ipdb> p div_e
1837162916490332
```
As a Python `int` that number would need almost 1 petabyte of memory to store so it is senseless to try and compute it.

Basically this issue is #6835 so I'm going to close this one as a duplicate. See here for what needs to be fixed: https://github.com/sympy/sympy/issues/6835#issuecomment-601090358
