### ISSUE TITLE
Matrix multiplication isn't simplifying the result

### ISSUE THREAD

**Issue by hyadav2k** [sympy/sympy#21028]
In this issue, `A*B` does not get equal to `M`, but on using simplify it does so.
```
In [1]: M = Matrix(((1, x, 1), (2, y, 0), (y, 0, z)))

In [2]: A = Matrix([[1, 0, 0], [2, 1, 0], [y, x*y/(2*x - y), 1]])

In [3]: B = Matrix([[1, x, 1], [0, -2*x + y, -2], [0, 0, (2*x*z + y**2 - y*z)/(2*x - y)]])

In [4]: A*B == M
Out[4]: False

In [5]: simplify(A*B)
Out[5]:
⎡1  x  1⎤
⎢       ⎥
⎢2  y  0⎥
⎢       ⎥
⎣y  0  z⎦

In [6]: simplify(A*B) == M
Out[6]: True
```

**Comment by oscarbenjamin** [comment]
This is expected:
https://docs.sympy.org/latest/gotchas.html#double-equals-signs

**Comment by hyadav2k** [comment]
@oscarbenjamin, while Implementing `DomainMatrix` to charpoly, it failed a test case, Should I use `simplify` in the test case, because then it works fine.
Thanks.

**Comment by oscarbenjamin** [comment]
We generally want to avoid using `simplify` in tests because it's very slow. Usually there is a fast way like just using `expand` or `signsimp` or something. In the case of `charpoly` the result should not be affected by simplify because all expressions are expanded when building the polynomial representations though.

It's easiest to answer this question if you open a PR and then explain which test is failing and how the output has changed.

**Comment by hyadav2k** [comment]
Thank you for the information. 
I have opened #21035 regarding the same.

Will close the issue now.
