### ISSUE TITLE
Cannot create joint normal distribution with positive semidefinite covariance matrix

### ISSUE THREAD

**Issue by rikardn** [sympy/sympy#21057]
I want to create a joint normal distributed random variable with a covariance matrix that is positive semidefinite but not positive definite. This seems to be impossible:

```python
import sympy.stats

sympy.stats.Normal("x", [0, 0], [[0,0], [0,0]])
```
gives

```
  File "<ipython-input-28-3bd23a2d609a>", line 1, in <module>
    sympy.stats.Normal("x", [0, 0], [[0,0], [0,0]])

  File "/home/.local/lib/python3.8/site-packages/sympy/stats/crv_types.py", line 2966, in Normal
    return MultivariateNormal(name, mean, std)

  File "/home/.local/lib/python3.8/site-packages/sympy/stats/joint_rv_types.py", line 209, in MultivariateNormal
    return multivariate_rv(MultivariateNormalDistribution, name, mu, sigma)

  File "/home/.local/lib/python3.8/site-packages/sympy/stats/joint_rv_types.py", line 28, in multivariate_rv
    dist.check(*args)

  File "/home/.local/lib/python3.8/site-packages/sympy/stats/joint_rv_types.py", line 143, in check
    _value_check(sigma.is_positive_definite,

  File "/home/.local/lib/python3.8/site-packages/sympy/stats/rv.py", line 1487, in _value_check
    raise ValueError(message)

ValueError: The covariance matrix must be positive definite. 
```

I don't know if there is some implementation reason for this, but mathematically any positive semidefinite matrix should be accepted. I checked numpy and there it works to do:

```python
import numpy as np

np.random.multivariate_normal([0, 0], [[0, 0], [0, 0]])
```

with the expected output:

```
Out[30]: array([0., 0.])
```

**Comment by iam-abbas** [comment]
It seems like the fix is simply changing `sigma.is_positive_definite` to `sigma.is_positive_semidefinite`  in https://github.com/sympy/sympy/blob/2346054bb4888ef7eec2f6dad6c3dd52bf1fe927/sympy/stats/joint_rv_types.py#L138-L144

**Comment by Maelstrom6** [comment]
Reminds me of [this](https://github.com/sympy/sympy/pull/19935) PR. I haven't checked the code for the multivariate distributions but I suspect `pdf`, `cdf` and a whole lot of other functions would have to be changed as well.

It might be simpler just to work with constants (since I think their `pdf` and `cdf` are defined somewhere).

**Comment by praneethratna** [comment]
Hey , I am bit new to open source contribution and would like to work on this issue, Could you give me an headstart on how to start working on this issue?

**Comment by Maelstrom6** [comment]
I don't have any experience with the random vectors part of SymPy but there would probably be at least 4 things that need to change:
- The assertion to check if the covariance Matrix is positive should be changed to positive semidefinite.
- The pdf should also change. According to Wikipedia:
  > In the degenerate case where the covariance matrix is singular, the corresponding distribution has no density; see the section below for details. This case arises frequently in statistics; for example, in the distribution of the vector of residuals in the ordinary least squares regression.
  This means that we should probably have a piecewise or if statement in the pdf function. Considering that a piecewise expression is not what people are expecting and it slows things down a bit, an if statement to return some kind of SymPy object representing a Nan would be good.
- cdf should similarly be changed if the code defines the cdf.
- The sampling which would be the main reason why people use a positive semidefinite matrix should be changed. I'm not sure how the code looks so that could either require no change or it could be more complicated. 
- Testing should be done on every applicable function for random vectors. 

There are probably other things to figure out along the way.

**Comment by praneethratna** [comment]
@Maelstrom6 i tried on fixing this issue , but i've some queries ; is there a function to check whether a matrix is positive semidefinite like is_positive_semidefinite because i didnt find one and also could you explain a bit more about what to implement in point 2?
thanks

**Comment by oscarbenjamin** [comment]
A normal distribution with zero variance is also not permitted:
```python
In [1]: from sympy.stats import *

In [2]: X = Normal('X', 0, 0)
---------------------------------------------------------------------------
ValueError: Standard deviation must be positive 
```

**Comment by Maelstrom6** [comment]
> A normal distribution with zero variance is also not permitted

The scalar normal distribution did have a PR for zero variance but it was closed because we couldn't reach an agreement on what the PDF and CDF should be and because the Wikipedia page says that the variance must be strictly positive. 

The user could also replace `X = Normal('X', mu, sigma)` with `X = mu` to get the same functionality (except for sampling capabilities).

**Comment by rikardn** [comment]
The case of zero variance for a single variate normal distribution is analogous to the case of positive semi-definite but not positive definite for the joint normal distribution. In my opinion sympy should allow it. Some arguments as for why it should:

1. Numpy allows it

```
np.random.normal(1, 0)
Out[1]: 1.0
```

2. It arises naturally from numerical situations. For example if you have two datasets like for example

```
a = [1, 1, 1, 1, 1]
b = [1, 1, 1, 1, 2]
```

The sample variance would be 0 for ```a``` and 0.16 for ```b```. If we want to model both as normally distributed (this assumption might be wrong but it might also be correct) in sympy we only do it directly for b and not for a, which would lead to an unnecessary special case.

3. Mathematically the 0 variance case or perhaps the limit when the variance approaching zero is usually considered to be the dirac distribution.

Perhaps sympy could support it by letting `Normal('X', 1 , 0)` return a dirac distribution.

**Comment by rikardn** [comment]
Not really. Let's say we want to calculate the probability of the random variable falling in some range: `P(a < X < b)` This would then be the integral from `a` to `b` of the pdf of the distribution. If the range includes `mu` the integral should become 1 else 0. A constant expression really cannot capture this. I think the dirac distribution needs to implemented as a distribution.

**Comment by oscarbenjamin** [comment]
It seems to work as far as I can tell:
```python
In [19]: mu = Symbol('mu')

In [20]: density(mu)
Out[20]: x ↦ δ(-μ + x)

In [21]: E(mu)
Out[21]: μ

In [22]: integrate(density(mu)(z), (z, 0, 1))
Out[22]: -θ(-μ) + θ(1 - μ)

In [23]: integrate(density(mu)(z), (z, mu-1, mu+1))
Out[23]: 1

In [24]: integrate(density(mu)(z), (z, mu-1, mu-0.5))
Out[24]: 0
```
Apart from these:
```python
In [25]: variance(mu)   # <--- incorrect
Out[25]: μ

In [26]: E(mu**2) - E(mu)**2
Out[26]: 0

In [27]: P(mu < 1)
---------------------------------------------------------------------------
ValueError: Expression containing Random Variable expected, not mu < 1

In [28]: P(mu < mu+1)
---------------------------------------------------------------------------
ValueError: Expression containing Random Variable expected, not mu < mu + 1
```

> I think the dirac distribution needs to implemented as a distribution.

I'm not sure what this means. SymPy's stats module does not really provide for working with distributions rather than expressions involving random variables e.g. https://github.com/sympy/sympy/issues/20643#issuecomment-749473694 https://github.com/sympy/sympy/pull/20560#issuecomment-740792093

**Comment by rikardn** [comment]
Wow, nice! Yes @oscarbenjamin, you are right. This seems to already be supported and a specific random variable for the dirac distribution is not needed in this case because a simple constant expression works fine as a case of a https://en.wikipedia.org/wiki/Degenerate_distribution

To summarize how to support the zero variance case (and any constant expression) for the one variable `Normal`:

1. For `Normal('X', x, 0)`   return `x`
2. Correctly calculate `variance(expr)` for `expr` not having any random variable as 0
3. Correctly calculate `P(expr < n)` for `expr` being constant as `Piecewise((0, expr < n), (1, expr >=n))' and similar
4. Support sampling from constant expressions: sample(expr) should always give expr
5. Support calculation of `median(expr)` for constant expression to be `expr`

**Comment by rikardn** [comment]
#21855, which has been merged, resolved 2 and 5 in my list above. To recap the discussion in the review of that PR we would like to implement a basic `PSpace` class that can be returned by `pspace` for constant expressions. Named something like `DegeneratePSpace`, `DiracPSpace` or `ConstantPSpace`.
