### ISSUE TITLE
Evalf and replace issues

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#21102]
First issue is why `(I*(3-I)).evalf()` gives `1.0+3.0I` instead of `1+3I`.
Secondly, when I try to substitute a `Float` with `Integer`, it doesn't work, because `Float` and `Integer` are treated as equal.
`(I*(3-I)).evalf().replace(lambda e: e.is_Float, lambda e: int(e))` returns `1.0+3.0I`

**Comment by hadiya8149** [comment]
There is no file for subtraction in sympy/core that's why it's getting converted to addition

**Comment by oscarbenjamin** [comment]
You can use `nsimplify` to turn float into rational.

The purpose of `evalf` is to try and evaluate the expression to either a single `Float` or `Float + Float*I` in the non-real case so that is expected.

The replace method does not work because of this and I think that is a bug but it is already reported at https://github.com/sympy/sympy/issues/19976

**Comment by smichr** [comment]
suggestion given in #199976; this can be closed as duplicate
