### ISSUE TITLE
Different formats for pretty print of float in matrix and as scalar

### ISSUE THREAD

**Issue by rikardn** [sympy/sympy#21154]
When pretty printing a float as an element of a matrix trailing zeroes will be removed, but not when printing as a scalar. I think it would be good to not display the trailing zeroes in both cases. 

```python
import sympy

sympy.pretty(sympy.sympify(0.1))
Out[1]: '0.100000000000000'

sympy.pretty(sympy.sympify([0.1]))
Out[2]: '[0.1]'
```

Note that for regular printing the trailing zeroes will be kept in both cases which I think is fine.

```python
sympy.sympify(0.1)
Out[1]: 
0.100000000000000

sympy.sympify([0.1])
Out[2]: [0.100000000000000]
```

**Comment by golmdav** [comment]
@rikardn 

This can be fixed by changing the full_prec setting in the pretty() function, like so

`>>> import sympy
>>> sympy.pretty(sympy.sympify(0.1), full_prec=False)
0.1`

When you fail to specify full_prec it reverts to auto, which is an arbitrary setting of having anything in the first recursion be full precision and anything after that abbreviated. Thats why the list is not printed with full precision

**Comment by rikardn** [comment]
Thanks @golmdav, this was really helpful!
