### ISSUE TITLE
Results diverge when use `diff` on a matrix or its elemetns

### ISSUE THREAD

**Issue by hoshea15** [sympy/sympy#21195]
create a one-element matrix A as below:
```python
>>> from sympy import *
>>> t = symbols('t')
>>> x = Function('x')(t)
>>> dx = x.diff(t)
>>> A = Matrix([cos(x) + cos(x) * dx])
```
when use `diff` on matrix A:
```python
>>> (A.diff(x))[0,0]
-sin(x(t))
```
when use `diff` on the single element of A: 
```python
>>> A[0,0].diff(x)
-sin(x(t))*Derivative(x(t), t) - sin(x(t))
```
but if use `applyfunc` method on A, the result is the same as above:
```python
>>> A.applyfunc(lambda ij: ij.diff(x))[0,0]
-sin(x(t))*Derivative(x(t), t) - sin(x(t))
```
is this a bug or supposed behavior of matrix calculus?

**Comment by moorepants** [comment]
`.diff()` is running this internally:

```ipython

n [1]: import sympy as sm

In [2]: t = sm.symbols('t')

In [3]: x = sm.Function('x')(t)

In [4]: dx = x.diff(t)

In [19]: from sympy.tensor.array.array_derivatives import ArrayDerivative

In [26]: ArrayDerivative(sm.Matrix([sm.cos(x) + sm.cos(x)*dx]), x, evaluate=True)
Out[26]: Matrix([[-sin(x(t))]])

In [27]: ArrayDerivative(sm.cos(x) + sm.cos(x)*dx, x, evaluate=True)
Out[27]: -sin(x(t))*Derivative(x(t), t) - sin(x(t))
```

**Comment by moorepants** [comment]
I tried this in SymPy 1.0 at it works as expected. The code for `Matrix.diff()` is:

```
In [2]: t = sm.symbols('t')

In [3]: x = sm.Function('x')(t)

In [4]: dx = x.diff(t)
```

So I think that ArrayDerivative change has introduced this bug.

**Comment by moorepants** [comment]
@Upabjojr This seems like a bug tied to the introduction of tensor code into the diff() of Matrix. I'm guessing that is something you added.

**Comment by Upabjojr** [comment]
I'll assign this issue to myself for now. Will look into it when I have some time.

**Comment by moorepants** [comment]
A quick fix it to switch back to the simple .diff of each element. I couldn't make heads or tails of the ArrayDerivative code with a quick look.

**Comment by moorepants** [comment]
Switching it back causes A.diff(A) to fail:

```
________________________________________ sympy/matrices/tests/test_matrices.py:test_diff_by_matrix _________________________________________
Traceback (most recent call last):
  File "/home/moorepants/src/sympy/sympy/matrices/tests/test_matrices.py", line 1919, in test_diff_by_matrix
    assert A.diff(A) == Array([[[[1, 0], [0, 0]], [[0, 1], [0, 0]]], [[[0, 0], [1, 0]], [[0, 0], [0, 1]]]])
AssertionError

```

**Comment by akshanshbhatt** [comment]
The problem lies in the expressions submodule of the matrices. Matrix expressions are handled differently from actual expressions.

https://github.com/sympy/sympy/blob/f9badb21b01f4f52ce4d545d071086ee650cd282/sympy/core/function.py#L1456-L1462

Every derivative requested expression passes through this point. The old variable is replaced with a new dummy variable (`xi`). Due to this some of the properties of the old symbol are lost. `is_Functon` being one of them. In the `old_v` (`x(t)`) this property is `True` but for `v` it is False. That is **not** an issue here as the old variable is substituted back after the computation of derivative. All the expressions pass through this point. The problem starts when we apply `doit()` on such dummy value expressions. Instead of treating the dummy variable as a `Function`, it is treated as regular `sympy.core.symbol.Symbol`. 

The best way to avoid this is to not use `doit()` on such expressions until the derivative is calculated and the old variable is substituted back. It is therefore nowhere used in the core expression module. However, in the matexpr module it is used twice and this is where the results deviate. 

```python
In [1]: from sympy import *
        from sympy import __version__ as ver
        t = symbols('t')
        x = Function('x')(t)
        ver
Out[1]: '1.8.dev'

In [2]: xi = Dummy("xi")
        new = x.xreplace({x: xi})
        print(Derivative(x, t).doit())
        print(Derivative(new, t).doit())
Out[2]: Derivative(x(t), t)
        0
```

https://github.com/sympy/sympy/blob/f9badb21b01f4f52ce4d545d071086ee650cd282/sympy/matrices/expressions/matexpr.py#L656

and 

https://github.com/sympy/sympy/blob/f9badb21b01f4f52ce4d545d071086ee650cd282/sympy/matrices/expressions/matexpr.py#L900

These two `doit()` reduce the `-sin(_xi)*Derivative(_xi, t)` part of the derivative computed to `0` (treating `_xi` as a symbol).

I removed the `.doit()` part from both the lines and it worked. I also ran all the tests and all the tests passed. Just to check that I was not anything wrong or ignoring some important purpose of that `.doit` part. I tried with some of my own examples using both `expr.diff(x)` and `matrix.diff(x)` and the results were the same for both every single time. If `doit()` has some important purpose then please let me know. Also if everything is fine then should I open a PR?

**Comment by Upabjojr** [comment]
> Also if everything is fine then should I open a PR?

Of course! It's easier to discuss edits in PRs because you can put comments on the code there.

**Comment by moorepants** [comment]
This should be fixed in the next release. Thanks for the bug report.
