### ISSUE TITLE
1/(exp(it) - 2) integrates wrong

### ISSUE THREAD

**Issue by Akuli** [sympy/sympy#21342]
```
>>> var('t', real=True)
t
>>> (1/(exp(I*t)-2)).integrate((t, 0, 2*pi))
-ⅈ⋅π
```

Correct answer is `-pi` according to wolframalpha

**Comment by oscarbenjamin** [comment]
A wrong output comes from `risch` in this case for the antiderivative:
```python
In [16]: t = Symbol('t')

In [17]: f = 1/(exp(I*t)-2)

In [18]: f
Out[18]: 
   1    
────────
 ⅈ⋅t    
ℯ    - 2

In [19]: integrate(f, t, risch=True)
Out[19]: 
           ⎛ ⅈ⋅t    ⎞
  ⅈ⋅t   log⎝ℯ    - 2⎠
- ─── + ─────────────
   2          2      

In [20]: integrate(f, t, risch=True).diff(t).together()
Out[20]: 
   ⅈ    
────────
 ⅈ⋅t    
ℯ    - 2
```
The heurisch method gives the right result:
```python
In [21]: integrate(f, (t, 0, 2*pi), heurisch=True)
Out[21]: -π

In [22]: integrate(f, t, heurisch=True)
Out[22]: 
           ⎛ ⅈ⋅t    ⎞
  t   ⅈ⋅log⎝ℯ    - 2⎠
- ─ - ───────────────
  2          2  
```
It seems that manualintegrate also gets this wrong:
```
In [23]: integrate(f, (t, 0, 2*pi), manual=True)
Out[23]: 0

In [24]: integrate(f, t, manual=True)
Out[24]: 
⌠            
⎮    1       
⎮ ──────── dt
⎮  ⅈ⋅t       
⎮ ℯ    - 2   
⌡  
```

**Comment by jksuom** [comment]
It seems that Mack's version of Hermite reduction: https://github.com/sympy/sympy/blob/f838ea34ea875a498fae66203e7863ec5cea27bb/sympy/integrals/risch.py#L1088-L1092
implicitly assumes that if the gcd `dm` has degree 0 then it is equal to1. In this case, we have
(with `x` instead of a dummy):
```
In [1]: d, dd = Poly(x - 2, x), Poly(I*x, x)                                    

In [2]: gcd(d, dd)                                                              
Out[2]: Poly(I, x, domain='ZZ_I')
````
It is the constanr gcd polynomial `I` that turns up in the wrong result.

This could be fixed in `dup_rr_prs_gcd`: https://github.com/sympy/sympy/blob/f838ea34ea875a498fae66203e7863ec5cea27bb/sympy/polys/euclidtools.py#L990-L998
In the example at hand, we have
```
(Pdb) p h
[ZZ_I(0, 2)]
(Pdb) p dup_primitive(h, K)
(ZZ_I(2, 0), [ZZ_I(0, 1)])
```
where the primitive part still contains the Gaussian unit `ZZ_I(0, 1)` (as the gcd component `ZZ_I(2, 0)` is normalized). It looks like the lines 995-996 should be replaced by something like `c *= K.canonical_unit(dup_LC(h, K))` in order to absorb the unit in the content `c`.

**Comment by oscarbenjamin** [comment]
Yes, that seems right:
```diff
diff --git a/sympy/polys/euclidtools.py b/sympy/polys/euclidtools.py
index c0b6d13e79..7a772a012a 100644
--- a/sympy/polys/euclidtools.py
+++ b/sympy/polys/euclidtools.py
@@ -992,8 +992,7 @@ def dup_rr_prs_gcd(f, g, K):
     h = dup_subresultants(F, G, K)[-1]
     _, h = dup_primitive(h, K)
 
-    if K.is_negative(dup_LC(h, K)):
-        c = -c
+    c *= K.canonical_unit(dup_LC(h, K))
 
     h = dup_mul_ground(h, c, K)
```
There is one test failure in polys:
```
        a, b = sqrt(-2), -sqrt(-2)
>       assert gcd(a, b) in (a, b)
E       assert sqrt(2) in (sqrt(2)*I, -sqrt(2)*I)
E        +  where sqrt(2) = gcd(sqrt(2)*I, -sqrt(2)*I)

sympy/polys/tests/test_polytools.py:2055: AssertionError
```
This is because the output has changed for this:
```python
In [1]: gcd(sqrt(-2), -sqrt(-2))
Out[1]: √2
```
On master that gives:
```python
In [1]: gcd(sqrt(-2), -sqrt(-2))
Out[1]: -√2⋅ⅈ
```
I think it's reasonable that the gcd should be canonical wrt units.

**Comment by jksuom** [comment]
Actually, there are two issues involved:
>  the gcd should be canonical wrt units.

I agree. This is what most people would expect.

> if the gcd dm has degree 0 then it is equal to1

I haven't seen the original paper of Mack but I believe that the coefficient domain is assumed to be a field. In that case, the polynomial gcd will always be monic: https://github.com/sympy/sympy/blob/43df6e3b3a8cfa2ef0afc96d0cbb03cfed3a0309/sympy/polys/euclidtools.py#L1029
It seems that polynomials in `risch` should also have field coefficients in most cases.
