### ISSUE TITLE
Can sympy support matrix formula derivation

### ISSUE THREAD

**Issue by CatNofishing** [sympy/sympy#21347]
Nowadays, more and more mathematical expressions in machine learning and books and periodicals are expressed by matrix, which involves the process of matrix derivation. This process is very difficult and requires very high mathematical skills Whether the sympy support matrix derivation  nd the derivation formula can be obtained automatically. Is it possible to automatically derive the back propagation formula in machine learning use sympy

**Comment by oscarbenjamin** [comment]
Can you make the question more precise. Give an example of what exactly do you want SymPy to do?

**Comment by CatNofishing** [comment]
@oscarbenjamin  ， Can symmetry derive matrix functions? just like this，all variables are matrices
![image](https://user-images.githubusercontent.com/33288114/115819617-c9261100-a431-11eb-9e25-e46eb4b30289.png)
![image](https://user-images.githubusercontent.com/33288114/115819616-c9261100-a431-11eb-919b-4ece545301e9.png)

**Comment by asmeurer** [comment]
Yes, derivatives are implemented with respect to MatrixSymbol objects. Although I don't know if they are implemented for the norm function. @Upabjojr

**Comment by Upabjojr** [comment]
An idea would be:

```python
In [3]: k = symbols("k")

In [4]: a = MatrixSymbol("a", k, 1)

In [5]: y = MatrixSymbol("y", k, 1)

In [6]: C = (a - y).T*(a - y)/2

In [7]: C
Out[7]:
    ⎛  T    T⎞
1/2⋅⎝-y  + a ⎠⋅(-y + a)

In [9]: C.diff(a)
Out[9]: -y + a
```

Note that `matrix.diff(other_matrix)` uses an algorithm which is currently being rewritten (it does not support returning results if the results have more than 2-dimensions or cannot be trivially collapsed into 2-dimensions).

In order to use the second algorithm, just call:

```python

In [10]: from sympy.tensor.array.expressions.arrayexpr_derivatives import array_derive

In [11]: array_derive(C, a)
Out[11]:
ArrayAdd(ArrayContraction(ArrayTensorProduct(1/2, I, I, ArrayAdd(ArrayTensorProduct(-1, y), a)), (1, 4)), PermuteDims(
ArrayContraction(ArrayTensorProduct(1/2, I, I, ArrayAdd(PermuteDims(ArrayTensorProduct(-1, y), (0 1)), PermuteDims(a,
(0 1)))), (1, 5)), (2 3)))

In [12]: from sympy.tensor.array.expressions.conv_array_to_matrix import convert_array_to_matrix

In [13]: convert_array_to_matrix(array_derive(C, a))
Out[13]: -y + a
```

**Comment by Upabjojr** [comment]
@CatNofishing hope this satisfies your needs.

The current state of SymPy's algorithm can still be improved. In particular, the matrix expression should always be converted into a tensor expression, be derived, and then be converted back to a matrix expression (if it is possible, which is not always the case, e.g. `X.diff(X)` returns a 4-dimensional tensor, it cannot even be represented with tensor product operators of matrices because the dimensions are permuted).

The closed-form matrix derivation algorithm is quite complicated to implement, at present not even Wolfram Mathematica supports it.

**Comment by CatNofishing** [comment]
@Upabjojr Thanks your reply😁，it  seems that this is a very complicated problem.

**Comment by Upabjojr** [comment]
> @Upabjojr Thanks your reply😁, it seems that this is a very complicated problem.

Yes, the problem is that you cannot apply the chain rule linearly. In general, the derivative of a matrix splits the matrix multiplication lines into different parts. These two parts have to be rearranged as matrix-multiplication-lines separately, furthermore there may be operators that re-unite or crossover the matrices. Generally, the result is a 4-dimensional tensor (2 dimensions for the matrix expressions, 2 dimensions in the derivation variable), but in some cases some of these dimensions are trivial and can be suppressed, therefore expressing the results as a matrix expression.

The first algorithm (currently called by `.diff( )`) acts on matrix expressions only, this is a bit limited. The second algorithm transforms the matrix expression into an array expression (matrix multiplication is expressed as tensor products and tensor contractions), performs the derivative and then tries to re-express the tensor expression as a matrix expression.



?

**Comment by Upabjojr** [comment]
With the latest improvements to matrix and array derivation code, this issue can be closed.
