### ISSUE TITLE
Sympification of "Q"

### ISSUE THREAD

**Issue by JSS95** [sympy/sympy#21388]
Before 1.8 was released, I inadvertently made a backwards-incompatible change 8b23826867677e3442497799339264a4b1009188, which was unnoticed and included in 1.8.

Before that change, `sympify("Q")` returned `Symbol("Q")`.  Now, it returns `Q` object in assumptions module. The purpose was to make `sympify("Q.even(x)")` return the desired applied predicate instead of raising `AttributeError: 'Symbol' object has no attribute 'even'`.

My opinion is that `sympify("Q")` should return `Q` instance, since there is no other way to get the predicate by parsing. Plus, SymPy documentation has explicitly warned (https://docs.sympy.org/latest/gotchas.html#symbols) not to use `Q` for variable name [since 2010](https://github.com/sympy/sympy/commit/72d7ade8dd107474054c2f02c37a7684fbd9a98d).

However, I am aware that backwards compatibility matters, and this is a grave issue which can break many users' notebooks.

If we decide that this change is reasonable, I will add this in the release note and documents. If not, I will revert this change and we should release 1.8.1 version. I'm sorry for the trouble.

Related to #21233.

**Comment by asmeurer** [comment]
I'm surprised that it wasn't included before. I didn't realize there is a type guard in the parser. Are there other names from `from sympy import *` that aren't parsed by `sympify()`?

**Comment by JSS95** [comment]
@asmeurer 

There is a related discussion in #21291.

**Comment by asmeurer** [comment]
> Are there other names from from sympy import * that aren't parsed by sympify()?

```
>>> for name in sympy.__all__:
...     if isinstance(sympify(name), Symbol):
...         print(name)
evalf
sieve
FU
plot_backends
algebras
assumptions
calculus
concrete
discrete
external
functions
geometry
interactive
multipledispatch
ntheory
parsing
plotting
polys
printing
release
strategies
tensor
utilities
```

Looks like a bunch of modules and dictionaries. I thought modules were going to be removed from `__all__`. 

If it wasn't clear, I think this is a good change and we should keep it. sympify() should always recognize names from the default namespace. The docstring of `sympify` even mentions that `Q` is a clashing single letter name.

**Comment by oscarbenjamin** [comment]
> Looks like a bunch of modules and dictionaries. I thought modules were going to be removed from `__all__`.

https://github.com/sympy/sympy/blob/8ddf9c29e345df987e82f8c5905dd0b32ea0a4b6/sympy/__init__.py#L494-L528

They could be removed. I removed the clashing ones like `sympy.core.core` At least new packages and modules will not appear there implicitly now.

A better approach is needed in general for sympy's import namespace. I think that the main problem is putting everything in `sympy/__init__.py`. It would be much better if there was a separation between the public import interface and the internal code modules but the only separation sympy has is adding things to `sympy.__all__`. The problem is we can't add everything there and there are already too many things there. It also makes importing sympy slow and leads to import cycles because there's no way to import anything without importing everything.

**Comment by asmeurer** [comment]
I'm still in favor of removing all modules from `__all__`. Their presence is only confusing, especially names like `evalf` that look like they might be functions. And even if a user realizes that it's a module, it's not exactly the best way to access stuff. And as you noted, `module.name` might not even be a "public" function. Note that `__all__` only affects `import *`. You can always manually import anything, even if it isn't in `__all__`.

**Comment by JSS95** [comment]
If we have deprecated the module import since 1.7, I am +1 to completely removing it in 1.9

**Comment by JSS95** [comment]
I modified the wiki page, so I'm closing this issue.
