### ISSUE TITLE
Installation Bugs

### ISSUE THREAD

**Issue by SmritiAgrawal04** [sympy/sympy#21592]
1) Post trying to install sympy via cloning the repo, while running the command `python setup.py install`, I faced the following warning: 
![Screenshot from 2021-06-09 13-56-25](https://user-images.githubusercontent.com/54806047/121320236-975a0280-c92a-11eb-9098-b1c3c26496f5.png)

2) Updating the above command to `python3 setup.py install` was not sufficient and it threw the following:
![Screenshot from 2021-06-09 13-58-41](https://user-images.githubusercontent.com/54806047/121320498-dab47100-c92a-11eb-9956-885a634443e1.png)

3) Finally updating the command to `sudo python3 setup.py install` worked fine.
![Screenshot from 2021-06-09 14-01-24](https://user-images.githubusercontent.com/54806047/121320957-45fe4300-c92b-11eb-8359-deb2a27599c9.png)

**Comment by oscarbenjamin** [comment]
These are not bugs:

1. Current SymPy does not run with Python 2.7. You should use sympy 1.5 is you want to use it with Python 2.7.
2. If you try to install in the system Python on Linux then you need to use `sudo`

I recommend using virtual environments rather than installing from git into the system with `sudo`.
