### ISSUE TITLE
Bug: maximum recusion depth error when checking is_zero of cosh expression

### ISSUE THREAD

**Issue by aeflores** [sympy/sympy#21625]
The following code causes a `RecursionError: maximum recursion depth exceeded while calling a Python object` error when checked if it is zero:
```
expr =sympify("cosh(acos(-i + acosh(-g + i)))")
expr.is_zero
```

**Comment by oscarbenjamin** [comment]
The problem is with `Abs`:
```python
In [7]: e = S("im(acos(-i + acosh(-g + i)))")                                                        

In [8]: abs(e)
```
That leads to this:
https://github.com/sympy/sympy/blob/126f80578140e752ad5135aac77b8ff887eede3e/sympy/functions/elementary/complexes.py#L616-L621
and then `sqrt` leads here:
https://github.com/sympy/sympy/blob/126f80578140e752ad5135aac77b8ff887eede3e/sympy/core/power.py#L336
which goes to here:
https://github.com/sympy/sympy/blob/126f80578140e752ad5135aac77b8ff887eede3e/sympy/core/power.py#L418
And then that's trying to compute the same abs again.

I'm not sure where the cycle should be broken but the code in `Abs.eval` seems excessively complicated.

**Comment by jksuom** [comment]
We should probably never come to this test when the argument is real. There should be something like `if arg.is_extended_real` before `conj` is computed.

**Comment by smichr** [comment]
There are tests for nonnegative, nonpositive and imaginary. So an additional test before coming to this part would be
```python
if arg.is_extended_real:
    return
...
_arg = signsimp(arg, evaluate=False)
if _arg not in (conj, -conj):
...
```
