### ISSUE TITLE
is_real assumption

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#21624]
`sqrt(sin(2*x)-2).is_real` returns `None`, when it is clearly `False`.

**Comment by oscarbenjamin** [comment]
Queries in the old assumptions are not expected to resolve always. It's fine to return None if they don't because None means "don't know" which is always valid:
https://docs.sympy.org/dev/guides/assumptions.html#the-old-assumptions-system

The example you give would require being able to resolve an inequality. There is the new `is_ge` function that could be made to do this but the inference rules involved would need to be fairly simple.

Alternatively this could be handled by the new assumptions system when it gains inequality support.

Note that `x` would need to be declared real for this to be correct since:
```python
In [5]: sqrt(sin(2*I)-2).n()
Out[5]: 1.03483158521587 + 1.75239162568199⋅ⅈ
```

**Comment by smichr** [comment]
I nice way to use SymPy as a learning aid -- which is something that I appreciated about python itself -- is to see if there is any value of x that would make it true:
```python
>>> sol=solve(sqrt(sin(2*x)-2)-var('y',real=True),x)
>>> sol
[-asin(y**2 + 2)/2 + pi/2, asin(y**2 + 2)/2]
```
So either of those (non-real) values will give you a real result.
