### ISSUE TITLE
Inconsistent differentiation behaviour for functions with undeclared variables

### ISSUE THREAD

**Issue by pyr-kaboosh** [sympy/sympy#21655]
I think the image speaks for itself:

![SympyWeirdBehav](https://user-images.githubusercontent.com/80962489/123154876-b34fbf00-d467-11eb-9c54-200169542a82.png)

Different, unreasonable results for using different differentiation functions and arguments. 
Specifically the sympy.diff function seems to be having problems.

**Comment by oscarbenjamin** [comment]
This should raise an error because an uncalled function is not an expression that can be differentiated.

To be clear reasonable results are obtained if the function is called with an argument as in `diff(v(x), x)`.

**Comment by pyr-kaboosh** [comment]
Might be a jupyter error, alright thank you for the clarification.
Ill close it now.

**Comment by oscarbenjamin** [comment]
It's not a Jupyter error. Somewhere there should be a check that the argument to `diff` is an actual expression.

**Comment by pyr-kaboosh** [comment]
It the errors are clearly displayed when there is one, don't know why it doesn't here.

**Comment by waveletrider** [comment]
The error is correctly raised as "Since there are no variables in the expression f, it cannot be differentiated." in version 1.3. 

In versions 1.7.1 and 1.8, `diff` behaves as reported in OP, giving some random result 1 or 0 in first and second derivatives.  See https://stackoverflow.com/questions/68515219/why-the-derivative-of-an-unknown-function-is-1-in-sympy

In version 1.8 `Derivative` in the second variant for me correctly gives `d/dx f`.
