### ISSUE TITLE
orient vs orient_axis argument order

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#21691]
qutoing from https://github.com/sympy/sympy/issues/21659

> In .orient() for a simple rotation you supply a tuple (angle, axis). In .orient_axis() the order of arguments is "axis, angle". 

"In the face of ambiguity, refuse to guess" does not apply if there is no ambiguity or possibility of the same. So even though this design has been implemented it seems reasonable to me to either 

1) internally swap the args of `orient_axis` if they are of the right type
2) swap but warn
3) swap and warn of deprecation, and after a year only accept them in the same order as `orient`

**Comment by moorepants** [comment]
We implemented and merged suggest 1. We could do 2 but then you just annoy the user for no reason. And 3 really annoys the user, as do all deprecations! I'm good with 1. in this case. There is an option 4. also...don't deprecate just fix it due to the fact that few people may use the method and if we change in in the following release, maybe it only annoys few to no people.

**Comment by sidhu1012** [comment]
I also prefer option 1, it's the bwst solution, without the user needing to worry.

**Comment by oscarbenjamin** [comment]
Is there anything to fix here or can this be closed?

**Comment by sidhu1012** [comment]
I think it can be closed .

**Comment by moorepants** [comment]
@sidhu1012 providing the commit or PR that closes this is the ideal response.

**Comment by moorepants** [comment]
This PR https://github.com/sympy/sympy/pull/21662 closes this issue by making `orient_axis()` accept the arguments in either order with no warning.
