### ISSUE TITLE
Incorrect limit with bessel function besselj(m,z)

### ISSUE THREAD

**Issue by scimax** [sympy/sympy#21701]
Hello everyone,
I think I found a bug which was not reported yet. There are a few issues which might be related, but as I don't know the details of the background work, I'm not sure about it. The issues I'm talking about are #11776 and #7224. But they are from the user persepective different from the issue I would like to report about.

When taking the following limit
```py
limit(
    (besselj(m,z)/z**m).subs(m,7),
    z, 0 )
```
the sympy result is `1` for all values of `m`. Here, I have already substituted an arbitrary integer value. In the generic case, without `.subs(m,7)`  an exception is thrown, reporting
```
NotImplementedError: Result depends on the sign of sign(m - 2)
```

However, that's not what I'm talking about. The above result is actually wrong. The limit is not `1` but `1/(2**m * m!)`, see for instance [wolfram alpha](https://www.wolframalpha.com/input/?i=lim++BesselJ%5Bm%2C+x%5D%2Fx%5Em+as+x-%3E0). This can also be derived by hand, using the [series expansion](https://en.wikipedia.org/wiki/Bessel_function#Bessel_functions_of_the_first_kind:_J%CE%B1) from the Frobenius method. When multiplying with `x^{-m}` all terms except the first one `m=0` vanish for `x --> 0`. Any idea, what the origin for the wrong result could be? Is it related to the aforementioned issues?
Thanks in advance!

System:
- Sympy 1.8
- Python 3.8.10
- Windows 10, 20H2

**Comment by oscarbenjamin** [comment]
The expected result seems to obtained from series:
```python
In [226]: series(besselj(7,z)/z**7, z)
Out[226]: 
             2           4            
  1         z           z         ⎛ 6⎞
────── - ──────── + ────────── + O⎝z ⎠
645120   20643840   1486356480        

In [227]: limit(_, z, 0)
Out[227]: 1/645120

In [233]: 1/(2**7 * factorial(7))
Out[233]: 1/645120
```

**Comment by scimax** [comment]
Sure, the series expansion is correct and is in agreement with the analytical one I mentioned above. But it seems like the result given by sympy does not make use of the series expansion.

**Comment by 0sidharth** [comment]
It looks like a factor of `gamma(nu + 1)` was left out in `besselj._eval_as_leading_term`. https://github.com/sympy/sympy/blob/fc9acc8f1b31b4a1d7e8a3736efd4fb09d0b8bba/sympy/functions/special/bessel.py#L221-L223 This leads to a wrong leading term being returned, which is used for the limit calculation, and hence a wrong result.

**Comment by 0sidharth** [comment]
Regarding the `NotImplementedError` when calling `limit`. It seems that `(z/2)**m` does not distribute the power, and hence `(z/2)**m/z**m` does not simplify to `1/2**m`, so the `leadterm` method thinks that there is a factor of the original variable `z` in the leading term, and hence raises an error. Both the issues can be fixed by modifying like this - 
```diff
diff --git a/sympy/functions/special/bessel.py b/sympy/functions/special/bessel.py
index 196b064023..5805b09b36 100644
--- a/sympy/functions/special/bessel.py
+++ b/sympy/functions/special/bessel.py
@@ -218,9 +218,9 @@ def _eval_rewrite_as_jn(self, nu, z, **kwargs):
 
     def _eval_as_leading_term(self, x, logx=None, cdir=0):
         nu, z = self.args
-        arg = (z/2).as_leading_term(x)
+        arg = z.as_leading_term(x)
         if x in arg.free_symbols:
-            return arg**nu
+            return arg**nu/(2**nu*gamma(nu + 1))
         else:
             return self.func(nu, z.subs(x, 0))
 
```

Regarding the `NotImplementedError` in the `series` call, it is due to the ambiguity in the Order of the terms. The current code will return the series expansion terms with order less than `z**6`. Now for `besselj(m, z)`, it tries to determine the terms which have order less than `z**6` by dividing `z**6` by the term and checking if the exponent is positive, so the terms become `a*z**(6 - m) + b*z**(6 - (m + 2)) + c*z**(6 - (m + 4))`. Due to this ambiguity where the code cannot decide whether the exponents are positive (and hence whether they should be returned or not), it raises `NotImplementedError`.

**Comment by scimax** [comment]
Wow, thanks! This seems to be a quick fix for the limit! I tried to look under the hood how it works but I didn't see the `.as_leading_term()` function.

Regarding the `NotImplementedError` in the series expansion, so the error is due to the order to which the function is expanded? Following this argument the error should be slightly different for
```py
series(
    besselj(m,z)/z**m
    , z, n=8)
```  
And, indeed, I get now:
```py
NotImplementedError: Result depends on the sign of sign(m - 6)
```
For even higher orders in the expansion this continues, e.g. order `n=10` results in the error with `sign(m - 8)`, and so forth.
