### ISSUE TITLE
sympy always imports a file named "code.py" on the current directory

### ISSUE THREAD

**Issue by Diogo-Rossi** [sympy/sympy#21734]
Oddly, when  I import `sympy` into a script, and there is a file in same directory named "code.py", sympy execute that file.

Is that expected?

Steps to reproduce:
1. Create a file named "code.py" in a folder.
2. Put some traceable code in this file, like `print("some thing")`
3. Open a python REPL in this folder and execute `import sympy`: check that de "code.py" file is executed and "some thing" is printed in the REPL.
4. Rename the "code.py" file with other name, then repeat step 3. The file isn't executed anymore.

**Comment by oscarbenjamin** [comment]
The Python standard library has a module called code that sympy tries to import:
https://docs.python.org/3/library/code.html

Putting a module of the same name in your directory conflicts with that standard library module. Name clashes between local modules and the standard library are a pitfall of Python. I think the language should be improved so that you can do `from stdlib.code import X` or something like that but that's a separate topic. The solution for now is that you should avoid creating a module with the same name as any stdlib module.
