### ISSUE TITLE
evalf and Integer

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#21807]
`(sqrt(101010101).evalf(3))` outputs `10100`
`Integer(_)` outputs `10050`

How is this possible?

**Comment by oscarbenjamin** [comment]
I don't see the same:
```python
In [1]: (sqrt(101010101).evalf(3))
Out[1]: 1.01e+4

In [2]: str(sqrt(101010101).evalf(3))
Out[2]: '1.01e+4'

In [3]: repr(sqrt(101010101).evalf(3))
Out[3]: '1.01e+4'
```

**Comment by proy87** [comment]
@oscarbenjamin , did you apply Integer to the result?
`Integer((sqrt(101010101).evalf(3)))` should output `10100`, not `10050`

**Comment by oscarbenjamin** [comment]
When you do `evalf(3)` you are only asking for the result to be correct to 3 decimal digits but the actual calculation is done in binary rather than decimal so you get a result that is correct to some number of binary digits. You can see the internal representation:
```python
In [19]: f = sqrt(101010101).evalf(3)

In [20]: f._mpf_
Out[20]: (0, mpz(5025), 1, 13)

In [21]: 5025*2**1
Out[21]: 10050
```
https://mpmath.org/doc/current/technical.html

So the result of calling evalf is in fact the integer 10050.

A more accurate result is
```python
In [24]: sqrt(101010101).n()
Out[24]: 10050.3781520896
```
Why would you expect Integer with this to give 10100? Note also that Integer rounds towards zero:
```python
In [27]: Integer(0.9)
Out[27]: 0
```

If you want a correctly rounded result to 3 decimal digits then it should be possible like this:
```python
In [37]: round(sqrt(101010101), -2)
Out[37]: 10100.0000000000
```
In general you can not expect that sequencing two rounding operations like `Integer(obj.evalf())` will give the exact result because of double rounding.

As before this discussion would be better on the mailing list.

**Comment by proy87** [comment]
What I want to achieve is to return integer after applying evalf (if it is integer).
So, I want to return `10100` instead of `10100.0` when doing `evalf(sqrt(101010101), 3)`.

**Comment by oscarbenjamin** [comment]
It's easy to convert a Float to an Integer. You need to be more precise about what you are trying to do and as I said before:

This discussion should be on the mailing list rather than in a GitHub issue. An issue should only be opened once it is established that there is a bug.

**Comment by proy87** [comment]
@oscarbenjamin , closing and moving to the mailing list.
