### ISSUE TITLE
writing theta dot in sympy

### ISSUE THREAD

**Issue by Noor-Kalibbala** [sympy/sympy#21839]
I want to write theta dot in sympy using the expression below but sympy outputs peculiar result
sp.symbols("\dot{\theta}")
(, ℎ𝑒𝑡𝑎˙)
i dont know what could be the problem

**Comment by oscarbenjamin** [comment]
Use a raw-string `r"\dot{\theta}"`

**Comment by Noor-Kalibbala** [comment]
@oscarbenjamin

**Comment by Noor-Kalibbala** [comment]
thank u @oscarbenjamin

**Comment by oscarbenjamin** [comment]
To be clear this is just an aspect of Python itself and not really anything to do with SymPy. In a Python string `\t` makes a tab character. You either need to escape the slash like `"\\dot{\\theta}"` or use a raw string `r"\dot{\theta}"`. The purpose of raw strings is so that you don't have to escape backslashes and it is best to use them any time you make a string with latex code in it because latex needs a lot of backslashes. You can try this directly in a Python REPL:
```python
>>> print('\theta')
	heta
>>> print('\\theta')
\theta
>>> print(r'\\theta')
\\theta
>>> print(r'\theta')
\theta
```
