### ISSUE TITLE
Categorize SymPy Modules

### ISSUE THREAD

**Issue by nanjekyejoannah** [sympy/sympy#22006]
To avoid having a big TOC, I propose categorizing the modules in the SymPy Modules Reference section of the documentation.

cc @asmeurer @oscarbenjamin

**Comment by asmeurer** [comment]
We should try to come up with ~8 high level sections that we can organize the public API reference documentation into.

**Comment by asmeurer** [comment]
Here's the current reference documentation. It's organized by SymPy submodules, but that's not necessarily the best organization for end-users. https://docs.sympy.org/latest/modules/index.html

Here's my initial thoughts on organization, based on the headers that are there. 
This is just my initial thoughts, so please critique. 

**Main category**. I'm not sure what this should actually be called, but it's
what 90% of users of SymPy will use. It consists of anything using basic
expressions, and functions that interact with them. This might need to be
split into sub-categories. Some of the categories below may make more sense as
subcategories of this.
```
abc
Calculus
Concrete
Core
Numerical Evaluation
Functions
Inequality Solvers
Integrals
Numeric Computation
ODE
PDE
Series
Simplify
Solvers
Solveset
```

**Code Generation**
```
Code Generation
```

**Matrices** Maybe this should just be a subsection of the main category. Or alternately the subsections of the main category could be top-level sections (but there would be more than ~8 in that case).
```
Matrices
Tensor
Vector
```

**Logic**
```
Logic
Assumptions
Sets
```

**Number Theory**
```
Combinatorics
Diophantine
Number Theory
```

**Geometry**
```
Geometry
```

**Polynomials** This might need a better name too. It's anything that involves
more direct calculations on things like polynomials or rings.
```
Algebras
Discrete
Polynomial Manipulation
```

**Plotting**
```
Plotting
```

**Physics** This should have subcategories for the different sub-submodules of sympy.physics.
```
Physics
```

**Utilities** Anything that isn't directly symbolic computation.
```
Interactive
Parsing
Printing
Testing
Utilities
```

**Other** Things that are mostly orthogonal to each other and don't fit
anywhere else. We could also make other categories for some of these items. "Stats" and "differential geometry" are a little more important so maybe they shouldn't be relegated to a miscellaneous category. 
```
Category Theory
Cryptography
Differential Geometry
Holonomic
Lie Algebra
Stats
```

I didn't include the Meijer G-function sections, which are part of integrals
(and shouldn't be in the reference section), or term rewriting, which isn't a
reference section and should probably go in the user guides. 

This is very rough and it's mostly just based on reorganizing the sections that are currently there. But we should really get rid of a lot of those sections as distinct things, and think about how we can organize the functions themselves. We don't need to keep functions together in the docs just because they are together in the code, or vise versa. 

That also means that just because one of my categories is one "section" above doesn't mean it is too small to be a category, because we really should take these categories as the top-level sections and make subsections for each one, which may or may not be based on the existing sections. 

@nanjekyejoannah didn't mention it, but we will have a section "internal reference" section which will document all functions in SymPy, both public and private, and will be organized completely based on the code structure. We can use a tool like autoapi and autosummary to generate this automatically (see https://stackoverflow.com/questions/2701998/sphinx-autodoc-is-not-automatic-enough/).

**Comment by oscarbenjamin** [comment]
Before seeing the comment above I tried to make a categorisation that might make sense to users for public docs. I took a bottom up rather than top-down approach: I looked at all the public things and tried to group them together hierarchically. This is what I came up with:
```yaml
basics:
    absolute basics:
        sympify, symbols, var, S, parse_expr, E, I, nan, oo, pi, zoo, N
        Basic.subs, N, EvalfMixin.evalf, nfloat, evaluate,
        assuming, Q, ask, refine, # maybe these somewherre else
        Basic.xreplace, Basic.replace, Basic.match, Wild, WildFunction
        pretty, pprint, latex
    manipulation:
        expand: expand_mul, expand_log, expand_func, expand_trig,
                expand_complex, expand_multinomial, expand_power_base,
                expand_power_exp,
        gcd_terms, factor_terms, factor_nc
        factor, together, cancel, collect, fraction, numer, denom,
        Expr.as_numer_denom, rcollect, collect_const, logcombine, separatevars
    simplify:
        standard:
            simplify, signsimp, radsimp, ratsimp, powsimp, powdenest, sqrtdenest,
        trig:
            trigsimp, exptrigsimp, FU, fu,
        nsimplify
        bottom_up
        besselsimp, kroneckersimp, combsimp, gammasimp,
        hyperexpand, hypersimp, hypersimilar,
        posify,
        cse, use, epath, EPath,
        ratsimpmodprime (maybe in groebner?)
    operations (better name?):
        diff, product, summation, integrate, limit, series  # XXX: not sure about these here...
    exceptions:
        PrecisionExhausted, (add more exceptions?)
        SympifyError

expression types:
    Basic:
        preorder_traversal
        Atom
        Lambda
        Tuple
        Dict
        Poly, PurePoly
        Boolean:
            true, false,
            Relational (Rel?): Eq, Ne, Lt, Le, Gt, Ge
            And, Or, Not, Xor, Nand, Nor, Implies, Equivalent, ITE
        Set:
            Interval, Union, EmptySet, FiniteSet, ProductSet, Intersection,
            DisjointUnion, imageset, Complement, SymmetricDifference, ImageSet,
            Range, ComplexRegion, Reals, Contains, ConditionSet, Ordinal,
            OmegaPower, ord0, PowerSet, Naturals, Naturals0, UniversalSet,
            Integers, Rationals, Complexes
        Expr:
            AtomicExpr, UnevaluatedExpr
            Number, Float, Rational, Integer
            AlgebraicNumber, NumberSymbol, RealNumber,
            Catalan, EulerGamma, GoldenRatio, TribonacciConstant
            Symbol, Dummy, Function,
            Subs,
            Pow, Mul, Add
            Derivative, Sum, Integral, Product, Limit
    properties:
        is_zero...
        is_number...

ntheory: (Needs subdivision...)
    igcd, ilcm, mod_inverse, integer_nthroot, integer_log,
    nextprime, prevprime, prime, primepi, primerange, randprime, Sieve, sieve,
    primorial, cycle_length, composite, compositepi, isprime, divisors,
    proper_divisors, factorint, multiplicity, perfect_power, pollard_pm1,
    pollard_rho, primefactors, totient, trailing, divisor_count,
    proper_divisor_count, divisor_sigma, factorrat, reduced_totient, primenu,
    primeomega, mersenne_prime_exponent, is_perfect, is_mersenne_prime,
    is_abundant, is_deficient, is_amicable, abundance, npartitions,
    is_primitive_root, is_quad_residue, legendre_symbol, jacobi_symbol,
    n_order, sqrt_mod, quadratic_residues, primitive_root, nthroot_mod,
    is_nthpow_residue, sqrt_mod_iter, mobius, discrete_log,
    quadratic_congruence, binomial_coefficients, binomial_coefficients_list,
    multinomial_coefficients, continued_fraction_periodic,
    continued_fraction_iterator, continued_fraction_reduce,
    continued_fraction_convergents, continued_fraction, egyptian_fraction

polys:
    creation:
        Expr.as_poly, poly, poly_from_expr, parallel_poly_from_expr,
    manipulation:
        horner, together, cancel, apart, apart_list, assemble_partfrac_list
    properties:
        degree, total_degree, degree_list, LC, LM, LT,
    division:
        pdiv, prem, pquo, pexquo, div, rem, quo, exquo, half_gcdex, gcdex,
        invert, subresultants, resultant, discriminant, cofactors, gcd_list,
        gcd, lcm_list, lcm, terms_gcd, trunc, monic, content, primitive,
    roots:
        roots, real_roots, nroots, refine_root, count_roots, real_roots,
        ground_roots, nth_power_roots_poly, CRootOf, rootof, RootOf,
        ComplexRootOf, RootSum,
    groebner:
        reduced, groebner, GroebnerBasis, is_zero_dimensional, itermonomials,
        Monomial, lex, grlex, grevlex, ilex, igrlex, igrevlex
    factorisation:
        sturm, gff_list, gff, sqf_norm, sqf_part, sqf_list, sqf,
        factor, factor_list
    other:
        compose, decompose,
        intervals,
        symmetrize, viete,
        interpolate, rational_interpolate,
    number fields:
        minpoly, minimal_polynomial, primitive_element, field_isomorphism,
        to_number_field, isolate
    domains:
        classes:
            Domain, FiniteField, IntegerRing, RationalField, RealField,
            ComplexField, PythonFiniteField, GMPYFiniteField,
            PythonIntegerRing, GMPYIntegerRing, PythonRational,
            GMPYRationalField, AlgebraicField, PolynomialRing, FractionField,
            ExpressionDomain,
        domains:
            GF, FF, ZZ, QQ, ZZ_I, QQ_I, RR, CC, EX, EXRAW,
        functions:
            construct_domain, Domain.convert, Domain.convert_from,
            Domain.from_sympy, Domain.to_sympy, Domain.to_field,
        implementations:
            ring, xring, vring, sring, field, xfield, vfield, sfield
    special:
        swinnerton_dyer_poly, cyclotomic_poly,
        symmetric_poly, random_poly, interpolating_poly, jacobi_poly,
        chebyshevt_poly, chebyshevu_poly, hermite_poly, legendre_poly,
        laguerre_poly,
    exceptions:
        BasePolynomialError, ExactQuotientFailed, PolynomialDivisionFailed,
        OperationNotSupported, HeuristicGCDFailed, HomomorphismFailed,
        IsomorphismFailed, ExtraneousFactors, EvaluationFailed,
        RefinementFailed, CoercionFailed, NotInvertible, NotReversible,
        NotAlgebraic, DomainError, PolynomialError, UnificationFailed,
        GeneratorsError, GeneratorsNeeded, ComputationFailed,
        UnivariatePolynomialError, MultivariatePolynomialError,
        PolificationFailed, OptionError, FlagError
    options:
        Options, (explanation of options)

functions:
    combinatoric:
        factorial, factorial2, rf, ff, binomial,
        RisingFactorial, FallingFactorial, subfactorial, carmichael,
        fibonacci, lucas, motzkin, tribonacci, harmonic, bernoulli, bell, euler,
        catalan, genocchi, partition,
    elementary:
        sqrt, cbrt, root, real_root,
        exp_polar, exp, ln, log,
        sin, cos, tan, sec, csc, cot, sinc,
        asin, acos, atan, asec, acsc, acot, atan2,
        sinh, cosh, tanh, coth, sech, csch, asinh, acosh, atanh,
        acoth, asech, acsch
    discontinuous (better name?):
        Min, Max, Id, Mod,
        Piecewise, piecewise_fold (maybe in simplify?)
        floor, ceiling, frac, Eijk, LeviCivita,
        KroneckerDelta, SingularityFunction, DiracDelta, Heaviside,
        bspline_basis, bspline_basis_set, interpolating_spline,
    complex:
        re, im, sign, Abs, conjugate, arg, polar_lift,
        periodic_argument, unbranched_argument, principal_branch, transpose,
        adjoint, polarify, unpolarify,
    special:
        LambertW, erf, erfc, erfi, erf2, erfinv, erfcinv, erf2inv, Ei, expint,
        E1, li, Li, Si, Ci, Shi, Chi, fresnels, fresnelc, gamma, lowergamma,
        uppergamma, polygamma, loggamma, digamma, trigamma, multigamma,
        dirichlet_eta, zeta, lerchphi, polylog, stieltjes,
        besselj,
        bessely, besseli, besselk, hankel1, hankel2, jn, yn, jn_zeros, hn1,
        hn2, airyai, airybi, airyaiprime, airybiprime, marcumq
        appellf1, legendre, assoc_legendre, hermite, chebyshevt,
        chebyshevu, chebyshevu_root, chebyshevt_root, laguerre,
        assoc_laguerre, gegenbauer, jacobi, jacobi_normalized, Ynm, Ynm_c,
        Znm, elliptic_k, elliptic_f, elliptic_e, elliptic_pi, beta, mathieus,
        mathieuc, mathieusprime, mathieucprime, riemann_xi, betainc, betainc_regularized
    generalised:
        hyper, meijerg,

matrices:
    types:
        MatrixBase, Matrix, MutableMatrix, MutableSparseMatrix, banded,
        ImmutableDenseMatrix, ImmutableSparseMatrix, ImmutableMatrix,
        SparseMatrix, MutableDenseMatrix,
    functions:
        casoratian, diag, eye, hessian, jordan_cell, list2numpy, matrix2numpy,
        matrix_multiply_elementwise, ones, randMatrix, rot_axis1, rot_axis2,
        rot_axis3, symarray, wronskian, zeros, GramSchmidt,
        matrix_symbols (what is this function?),
        hadamard_product, blockcut, block_collapse,
        det, diagonalize_vector, trace, kronecker_product, per
    expressions:
        MatAdd, MatMul, MatPow, MatrixExpr, MatrixSymbol, DeferredVector,
        MatrixSlice, BlockDiagMatrix, BlockMatrix, FunctionMatrix,
        Identity, Inverse, Trace, Transpose, ZeroMatrix, OneMatrix,
        Adjoint, HadamardProduct, HadamardPower, Determinant, DiagMatrix,
        DiagonalMatrix, DiagonalOf, DotProduct, KroneckerProduct,
        PermutationMatrix, MatrixPermute, Permanent,
    exceptions:
        ShapeError, NonSquareMatrixError,

solvers:
    solve:
        solve, checksol,
        solve_linear_system, solve_linear_system_LU, solve_linear,
        solve_poly_system, decompogen, solve_triangulated,
        solve_undetermined_coeffs,
        det_quick, inv_quick, check_assumptions, failing_assumptions,
    solveset
    linsolve, linear_eq_to_matrix, nonlinsolve, substitution,
    nsolve:
        nsolve, (explanation of solving with lambdify, nroots etc)
    inequalities:
        reduce_inequalities, reduce_abs_inequality,
        reduce_abs_inequalities, solve_poly_inequality,
        solve_rational_inequalities, solve_univariate_inequality,
    diophantine
    dsolve:
        checkodesol, classify_ode, dsolve, homogeneous_order, ode_order
    rsolve:
        rsolve, rsolve_poly, rsolve_ratio, rsolve_hyper,
    pdsolve:
        pdsolve, classify_pde, checkpdesol,
        pde_separate, pde_separate_add, pde_separate_mul,

topics (better name?):

    logic:
        to_cnf, to_dnf, to_nnf, POSform, SOPform, simplify_logic, bool_map,
        satisfiable

    # maybe move this to top-level?
    series: Order, O, gruntz, approximants,
        residue, EmptySequence, SeqPer, SeqFormula, sequence, SeqAdd, SeqMul,
        fourier_series, fps, difference_delta, limit_seq

    discrete:
        fft, ifft, ntt, intt, fwht, ifwht, mobius_transform,
        inverse_mobius_transform, convolution, covering_product,
        intersecting_product

    geometry:
        Point, Point2D, Point3D, Line, Ray, Segment, Line2D, Segment2D, Ray2D,
        Line3D, Segment3D, Ray3D, Plane, Ellipse, Circle, Polygon,
        RegularPolygon, Triangle, rad, deg, are_similar, centroid, convex_hull,
        idiff, intersection, closest_points, farthest_points, GeometryError,
        Curve, Parabola

    # n.b. integrate is in basics
    integrals: line_integrate, mellin_transform,
        inverse_mellin_transform, MellinTransform, InverseMellinTransform,
        laplace_transform, inverse_laplace_transform, LaplaceTransform,
        InverseLaplaceTransform, fourier_transform, inverse_fourier_transform,
        FourierTransform, InverseFourierTransform, sine_transform,
        inverse_sine_transform, SineTransform, InverseSineTransform,
        cosine_transform, inverse_cosine_transform, CosineTransform,
        InverseCosineTransform, hankel_transform, inverse_hankel_transform,
        HankelTransform, InverseHankelTransform, singularityintegrate

    tensor:
        IndexedBase, Idx, Indexed, get_contraction_structure, get_indices,
        shape, MutableDenseNDimArray, ImmutableDenseNDimArray,
        MutableSparseNDimArray, ImmutableSparseNDimArray, NDimArray,
        tensorproduct, tensorcontraction, tensordiagonal, derive_by_array,
        permutedims, Array, DenseNDimArray, SparseNDimArray

    calculus:
        euler_equations, singularities, is_increasing, is_strictly_increasing,
        is_decreasing, is_strictly_decreasing, is_monotonic,
        finite_diff_weights, apply_finite_diff, as_finite_diff,
        differentiate_finite, periodicity, not_empty_in, AccumBounds,
        is_convex, stationary_points, minimum, maximum

    algebras:
        Quaternion

    printing:
        pager_print, pretty_print, pprint_use_unicode, pprint_try_use_unicode,
        print_latex, multiline_latex, mathml, print_mathml, python,
        print_python, pycode, ccode, print_ccode, glsl_code, print_glsl,
        cxxcode, fcode, print_fcode, rcode, print_rcode, jscode, print_jscode,
        julia_code, mathematica_code, octave_code, rust_code, print_gtk,
        preview, srepr, print_tree, StrPrinter, sstr, sstrrepr, TableForm,
        dotprint, maple_code, print_maple_code

    testing:
        test, doctest

    # These modules are not automatically imported by the main __init__.py
    # but do have many public things.

    physics:
        ...

    stats:
        ...

    combinatorics:
        ...

    # Should anything below be documented in main public docs at all?

    core:
        cacheit, seterr comp, prod, vectorize, FunctionClass, PoleError,
        count_ops, arity,

    assumptions:
        AppliedPredicate, Predicate, AssumptionsContext, register_handler, remove_handler,

    utilities:
        flatten, group, take, subsets, variations, numbered_symbols, cartes,
        capture, dict_merge, postorder_traversal, interactive_traversal,
        prefixes, postfixes, sift, topological_sort, unflatten, has_dups,
        has_variety, reshape, default_sort_key, ordered, rotations, filldedent,
        lambdify, source, threaded, xthreaded, public, memoize_property, timed
```

This gives 8 top-level items:
```
basics
expression types
ntheory
polys
functions
matrices
solvers
topics
```
Everything else is a subsection of topics:
```
logic
series
discrete
geometry
integrals
tensor
calculus
algebras
printing
testing
physics
stats
combinatorics
core
assumptions
utilities
```
I'm not entirely happy with this. I think that series should maybe be more prominent and also I don't like Physics being buried in topics. Maybe ntheory belongs in topics but other things should come out. Or maybe ntheory, polys and matrices should be grouped together in a single top-level heading. Not sure...

**Comment by asmeurer** [comment]
There's a lot of commonality, which I guess is a good sign. I like that you've organized the functions themselves. That will be useful. 

My thoughts:

- "Basics" is a good name for what I called "main category". That also makes it clear why the base class for everything in SymPy is called "Basic", which is a little opaque otherwise.
- "Special topics" is also a good name, instead of "other" or "miscellaneous". 
- What should be a top-level category vs. lower level should be guided more by what users are most likely to be looking for, rather than by what seems to fit better in some sort of logical organization. So for instance I like having matrices as a top-level category because it's a very common thing that people use. 
- "Number theory" is somewhat niche, in the sense that it usually doesn't relate to other, more "symbolic" uses of SymPy, but it also tends to be a common use case as well. The main reason is that SymPy is in many cases the only Python library that provides a lot of the number theory functions, so if you need those, it's natural to pick up SymPy. So I also think it's good to have it as a top-level category. (In fact I think that a lot of the ntheory module that is currently private (or semi-private) should be cleaned up and made public. For example, the Chinese Remainder Theorem is a very useful function, but the current API(s) for it aren't very easy to use. That's a bit of a tangent, though...)
- I'm not actually sure if "combinatorics" belongs in number theory (from my organization). Actually, most of the combinatorics module would be better named "group theory". The parts that actually are about combinatorics could be their own special topics section.
- I don't like "expression types" as a section. I don't think users think of things this way, or would clearly distinguish a function like `sin` with an expression type like `GoldenRatio`. To me those both belong in the same section, because they are both building blocks of expressions. 
- Separating Expr from non-Expr makes sense to me, but maybe I'm wrong about that. I think that if you are using some Expr subclass, you are more likely to want some other Expr subclass or function that operates on Expr than you are to want a non-Expr class like a Set, Boolean, or Matrix. That's why I put sets and logic both in a top-level "Logic" section. They are at least conceptually related.
- I should mention that my "code generation" section would include those parts of "printing" that are code printers, and "printing" in my "utilities" section would only be the non-code printers like the LaTeX printer. Code generation is "printing", but there's a certain leap in conceptual understanding that you have to make as a user to understand that.

I think the main use-case we want to aim for is someone going to the SymPy docs just to browse around and see what is there. If someone is looking for something specific, they will just Google it. So we want to maximize discoverability, without making things too overwhelming that you can't even see everything, which is the way it is now.

**Comment by oscarbenjamin** [comment]
> * I don't like "expression types" as a section. I don't think users think of things this way, or would clearly distinguish a function like `sin` with an expression type like `GoldenRatio`. To me those both belong in the same section, because they are both building blocks of expressions

The flipside of thinking about what users would think before looking at the documentation is that the documentation itself influences the way that users think about SymPy. I think a lot of users would be very interested to be able to dig in to the expression types section and learn more about the essential components that build up an expression. The organisation of the docs there in itself could help to understand the relationships between the different kinds of expressions. Some users might go to the docs looking for one thing but then end up discovering something that helps them to understand SymPy a lot more than just the quick answer to the question they had when they started googling.

**Comment by moorepants** [comment]
If there is any way to get feedback on the organization of the documentation from some people that are strictly users of SymPy, I think that would be a good idea. @nanjekyejoannah is one of those but maybe soliciting some more people would provide enlightening views.

Aaron's list looks more user friendly to me. Oscar's seems more dense developer friendly.

**Comment by asmeurer** [comment]
Should we ask about this on the mailing list?

**Comment by moorepants** [comment]
That would be worth trying. The mailing list mostly elicits helpful responses from devs though. I'm really not sure what the best way to get substantial feedback from people who are primarily users.

**Comment by asmeurer** [comment]
I think the best way is to just try something, and pay attention to whether or not it works. We might think about more general ways that we can get metrics or feedback on the documentation. It's not easy, but I think a pretty good thing is to just look at what topics people are asking questions about, especially "can sympy do this?" type questions (for things that SymPy actually can do, of course). Those are often an indication that they weren't easy to find in the documentation. It's not perfect because sometimes people don't even look at the documentation in the first place, but I think if something does end up being poorly organized, we should be able to notice it.

**Comment by moorepants** [comment]
Great point. Doing a review of the mailing list, discussions, and stack overflow systematically could give a strong picture of what is lacking.

**Comment by nanjekyejoannah** [comment]
I would say I agree with @asmeurer, let us try with an iteration of some form of categories, we can change things around when the feedback comes in, its good for initial progress at least. Let us agree tommorrow if possible on these initial 8 categories, at least we have some headway from what @oscarbenjamin and @asmeurer shared. Lets agree to move forward on something for the start.

**Comment by asmeurer** [comment]
Here's an attempt to merge my and Oscar's categorizations into one.

**Basics** The same as [Oscar's](https://github.com/sympy/sympy/issues/22006#issuecomment-912120587), except I would put some of the expressions stuff together with it

**Working with expressions** (not sure if this is the best name). This would be everything in my ""main" topic except for the basics stuff, as well as everything in oscar's "expression types" and "functions". Subcategories might be "functions", "solvers", "calculus" (like `integrate` and `limit` and so on), "simplification". Alternately we could make each of those a top-level category, if that doesn't make it too crowded.

**Matrices**

**Code Generation**

**Logic**

**Number Theory**

**Physics**

**Utilities**

**Topics** Contains everything that isn't in the above. I'm actually thinking the polynomials section should go as a subsection here, since it isn't important to most sympy users. We could also consider moving "number theory" and "logic" here if the top-level feels too crowded.

All the categories would have sub-categories. I don't know if the main page should show both levels or if users should have to click through to see the sub-categories (i.e., should the maxdepth in the toctree be 1 or 2). 

Oscar, what are your thoughts on this? It would be good to iterate our ideas into a single categorization that @nanjekyejoannah can at least start with.

**Comment by asmeurer** [comment]
Actually "basics" and "working with expressions" are maybe too similar. Let's merge them. Here's a better list.

**Basics** Subcategories: "absolute basics", "manipulation", "assumptions", "functions", "simplification", "calculus", "solvers", and some "other" subcategory

**Matrices** Subcategories: "matrices", "tensors", "vectors"

**Code Generation**

**Logic** Subcategories: "Logic functions", "Sets" (note I moved assumptions to "basics")

**Number Theory** 

**Physics** Subcategories for each of the sympy.physics submodules

**Utilities** Subcategories: "Interactive", "Parsing", "Printing", "Testing", "Utilities" (the last two are actually mostly internal functions or functions that should be in other categories, but we can move those later)

**Topics** Subcategories: "Plotting", "Polynomials", "Geometry", "Category Theory", "Cryptography", "Differential", "Holonomic", "Lie Algebra", and "Stats" (potentially "Logic" and "Number theory" above should just be subcategories here).

**Comment by oscarbenjamin** [comment]
I would plotting in utilities rather than topics. Also I think that polynomials should be at top level along with matrices.

**Comment by asmeurer** [comment]
> I would plotting in utilities rather than topics. Also I think that polynomials should be at top level along with matrices.

Both sound fine. I was a little torn on whether polynomials should be top-level or not since I'm not sure how many users should be using them directly.
