### ISSUE TITLE
 `simplify` doesn't simplify rational expression 

### ISSUE THREAD

**Issue by Sangwon91** [sympy/sympy#22473]
I have a simple expression like below
```python
t = sp.symbols('t')
k_r, k_m, k_s, k_aq = sp.symbols('k_r k_m k_s k_aq')
```
```python
k_aq/(k_aq - k_m) - k_aq*exp(-k_m*t)/(k_aq - k_m) - k_m/(k_aq - k_m) + k_m*exp(-k_aq*t)/(k_aq - k_m)
```

The first term and third term should be 1 by addition.
```python
k_aq/(k_aq - k_m) - k_m/(k_aq - k_m)
```
```python
(k_aq - k_m) / (k_aq - k_m)
```
```python
1
```

But is seems `simplify` can't handle this simplification. How can I do that?

Thank  you.

**Comment by smichr** [comment]
Perhaps a sum could automatically collect items with a similar denominator so `a/x + b/x` would combine like `1/x +2/x`. But you can simplify terms of interest:
```python
>>> collect(factor_terms(eq),(k_m,k_aq))
(k_aq*(1 - exp(-k_m*t)) + k_m*(-1 + exp(-k_aq*t)))/(k_aq - k_m)

or 

>>> nt,wt=eq.as_independent(t)
>>> nt
k_aq/(k_aq - k_m) - k_m/(k_aq - k_m)
>>> wt
-k_aq*exp(-k_m*t)/(k_aq - k_m) + k_m*exp(-k_aq*t)/(k_aq - k_m)
>>> factor_terms(nt)+factor_terms(wt)
1 + (-k_aq*exp(-k_m*t) + k_m*exp(-k_aq*t))/(k_aq - k_m)
```

**Comment by smichr** [comment]
I took a look at collecting denominators in Add.flatten, but I don't think it's a good idea because other code expects to be able to separate such terms (so it would be a non-trivial fix, having to find all the places that don't expect that behavior). Also, I'm not sure that a flat expression should prioritize the denominator over the numerator for collection, e.g.
```python
a/x+a/y+b/x+b/y -> a*(1/x + 1/y) + b*(1/x + 1/y) or (a + b)/x + (a + b)/y
```
The good news, however, is that one can collect on the denominators (and I'm not sure why that didn't occur to me yesterday):
```python
>>> a/x+b/x+a/y+b/y
a/y + a/x + b/y + b/x
>>> collect(_,denoms(_))
(a + b)/y + (a + b)/x
```
Quality of "simplification" depends on what you are looking for. The tools for separating terms with a certain symbol and then collecting those terms are available, but don't happen automatically with `simplify`. Here I work your expression into the `1 + other` form in a different way:
```python
>>> collect(eq, denoms(eq))
(k_aq - k_aq*exp(-k_m*t) - k_m + k_m*exp(-k_aq*t))/(k_aq - k_m)
>>> _.subs(k_aq,z+k_m)
(k_m*exp(-t*(k_m + z)) + z - (k_m + z)*exp(-k_m*t))/z
>>> expand_mul(_,deep=0)
k_m*exp(-t*(k_m + z))/z + 1 - (k_m + z)*exp(-k_m*t)/z
>>> collect(_,1/z)
1 + (k_m*exp(-t*(k_m + z)) - (k_m + z)*exp(-k_m*t))/z
>>> _.subs(z,k_aq-k_m)
1 + (-k_aq*exp(-k_m*t) + k_m*exp(-k_aq*t))/(k_aq - k_m)
```

**Comment by smichr** [comment]
Here is something I had in #1280 that didn't get into master. It might be helpful for you:
```python
def separatevars_additively(expr, symbols=[]):
    """return terms of expr collected by symbols and returned as None if no
    separation could be done else as a dictionary with keys the symbol and
    value the sub-expression of expr containing terms with that symbol. The
    terms that have none of the symbols are returned with key 0.

    EXAMPLES
    ========

    >>> a/(a - b) - a*exp(-b*t)/(a - b) - b/(a - b) + b*exp(-a*t)/(a - b)
    >>> separatevars_additively(_,[t])
    {t: -a*exp(-b*t)/(a - b) + b*exp(-a*t)/(a - b), 0: a/(a - b) - b/(a - b)}
    >>> Add(*[simplify(v) for v in _.values()])
    -a*exp(-b*t)/(a - b) + b*exp(-a*t)/(a - b) + 1
    """
    free = set(symbols) or expr.free_symbols
    d = {}
    while free:
        f = free.pop()
        expr, dep = expr.as_independent(f, as_Add=True)
        if dep.has(*free):
            return None
        d[f] = dep
    if expr:
        d[0] = expr
    return d
```

**Comment by Sangwon91** [comment]
This is a very helpful answer as it contains the reason, solution, and examples. 

I really appreciate your kind reply.
As it resolved all my problems, I will colse this issue.
