### ISSUE TITLE
ITE is a boolean function, is something similar required for expressions?

### ISSUE THREAD

**Issue by oscargus** [sympy/sympy#22486]
It seems like a popular enough alternative to use `ITE` in expressions that are not Boolean.

Examples include: #19373, #20850, #21945

A Piecewise can be rewritten as an ITE:

https://github.com/sympy/sympy/blob/76d72acaeeab0082fc43eee42ddc8688acd3e306/sympy/functions/elementary/piecewise.py#L953

but only if the first argument is a Boolean.

An ITE can be rewritten as Piecewise, which probably is OK in general, but it seems to be support in printers to do this in a way that indicates support for non-Boolean expressions in the ITE. Which it doesn't have.

https://github.com/sympy/sympy/blob/76d72acaeeab0082fc43eee42ddc8688acd3e306/sympy/printing/c.py#L384-L386

There is probably a scope to be able to write things like `a = ITE(x > 1, 2, 4)` (which doesn't currently work), but it shouldn't rely on the `ITE` class. One reason for this is that in some programming languages this can use a ternary conditional operator (`a = x > 1 ? 2 : 4` in C), so compact code can be generated. Also, it seems like people tend to prefer to write it in this way.

Hence, should there be new classes introduced?
* One that is a two-piece Piecewise, taking a boolean/relational and two expressions. Like ITE but for expressions.
* One that takes several Boolean conditions and expressions, like a switch/case-statement or multi-input multiplexer?

This may especially make sense if/when there is a dedicated Boolean Symbol introduced. Which is discussed in multiple issues, most recently #22454

**Comment by oscarbenjamin** [comment]
I think that there should be a generic Piecewise that is not necessarily Expr or Boolean and can also be used with things like sets e.g.:
```python
In [1]: Piecewise((Reals, Ne(x, 0)), (EmptySet, True))
Out[1]: 
⎧ℝ  for x ≠ 0
⎨            
⎩∅  otherwise
```
The Piecewise class should be refactored so that generic Piecewise logic is move to a superclass, say PiecewiseBase and then there could be:
```python
class Piecewise(PiecewiseBase, Expr):
    # Expr-specific methods

class PiecewiseBoolean(PiecewiseBase, Boolean):
    # Boolean-specific methods

class PiecewiseSet(PiecewiseBase, Set):
    # Set-specific methods
```
If the Kind system was more widely used then that could be used to make this work in a coherent way e.g. have a single `Piecewise` class where all expressions in the Piecewise should have the same kind so that the kind of the Piecewise itself is known. That's tricky though when so many places use `isinstance` checks and expect to use methods rather than functions. We probably still need the kind system just to be able to distinguish different Expr e.g. a Matrix vs a number:
```python
In [4]: M = Piecewise((Matrix([[1]]), Ne(x, 0)), (Matrix([[2]]), True))

In [5]: M
Out[5]: 
⎧[1]  for x ≠ 0
⎨              
⎩[2]  otherwise

In [6]: shape(M)
---------------------------------------------------------------------------
NoShapeError 
```

**Comment by oscargus** [comment]
I think I got a bit confused by many printers rewriting ITE as Piecewise. It seems to work out properly in most cases so I close this.
