### ISSUE TITLE
aim for "least surprise" substitutions

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#22529]
In #22052 was raised the following behavior of algebraic subs:
```python
>>> x = Symbol('x', real=True)
>>> [(x**(i*S.Half)).subs(x**2,y) for i in range(2, 9)]
[x, y**(3/4), y, y**(5/4), x**3, y**(7/4), y**2]
```
vs
```python
>>> x = Symbol('x', positive=1)
>>> [(x**(i*S.Half)).subs(x**2,y) for i in range(2, 9)]
[sqrt(y), y**(3/4), y, y**(5/4), y**(3/2), y**(7/4), y**2]
```
In the first set, given that `x**3` remains unchanged, I think it surprising that x**(3/2) is changed.

Do we really need algebraic subs like this instead of having the user specify `subs(x, sqrt(y))`? The latter is totally unambiguous.
```

**Comment by ThePauliPrinciple** [comment]
If you indicate that x is a complex, the result is
```python
>>>x = Symbol('x', complex= True)
>>>Eq(x**Rational(5,2),(x**2)**Rational(5,4)).subs(x,I)
Eq(I**(5/2), -(-1)**(1/4))
```
undertermined. 

I think such substitutions with non integer powers of negative/imaginary numbers are generally not allowed. I think the underlying problem is the same as the "standard" trick to "prove" that any number equals any other number (which we know is not true).

**Comment by smichr** [comment]
> undertermined.

It should be allowed. If you evaluate the lhs and rhs of the Eq, they are the same.



> I think such substitutions with non integer powers of negative/imaginary numbers are generally not allowed

Did you find a case that is wrong?

**Comment by smichr** [comment]
I think this is working in master, now.
