### ISSUE TITLE
Integrating DiracDelta to create a Heaviside function with H(0)=0 instead of H(0)=1/2

### ISSUE THREAD

**Issue by FeryET** [sympy/sympy#22532]
There are a couple of conventions for heaviside function, one that is used a lot in signal processing is that the heaviside step function is left continous at H(0), meaning H(0) is 0. 

Since we use dirac delta a lot, there should be a way to indicate the heaviside function created from integrating the dirac delta is based on what convention.

**Comment by oscarbenjamin** [comment]
See also the discussion in #21945, #10840 and #20411.

There is a way to specify the default value for a Heaviside e.g.:
```python
In [11]: x, H0 = symbols('x, H0')

In [12]: f = Heaviside(x, H0)

In [13]: f
Out[13]: θ(x, H₀)

In [14]: f.subs(x, 0)
Out[14]: H₀
```
However there is no way to specify what is wanted if you start with a `DiracDelta` and then integrate it:
```python
In [15]: integrate(DiracDelta(x), x)
Out[15]: θ(x)

In [16]: integrate(DiracDelta(x), (x, 0, 1))
Out[16]: 0
```
A special rule for the Laplace transform of `DiracDelta` was implemented in #21469.

I don't remember exactly where I said this but my opinion is that rather than messing around with exactly what `H(0)` is there should be a way to specify what kind of integral you want in the case of definite integrals e.g. if the integral is from `a` to `b` and we have a DiracDelta at the boundary do you want the integral to "include" the end points. Here you say that you want the Heaviside to be treated as "left-continuous" but from the perspective of definite integration that means that's like saying that you want `integral2` below:
```python
In [31]: a, b, x = symbols('a, b, x')

In [32]: integral1 = Integral(DiracDelta(x), (x, 0, 1))

In [33]: integral1
Out[33]: 
1        
⌠        
⎮ δ(x) dx
⌡        
0        

In [34]: integral1.doit()
Out[34]: 0

In [35]: integral2 = Limit(Limit(Integral(DiracDelta(x), (x, a, b)), a, 0, '-'), b, 1, '-')

In [36]: integral2
Out[36]: 
          b        
          ⌠        
 lim  lim ⎮ δ(x) dx
b─→1⁻a─→0⁻⌡        
          a        

In [37]: integral2.doit()
Out[37]: 1
```
I think that there should be a way to specify how `Integral` handles the boundaries but without needing to explicitly use `Limit` since that might not work in general.

**Comment by hanspi42** [comment]
> There are a couple of conventions for heaviside function, one that is used a lot in signal processing is that the heaviside step function is left continous at H(0), meaning H(0) is 0.

I know this is done a lot, but let me ask you the following two questions:

1. If the antiterivative of `DiracDelta(t)` should be left-continuous at 0, should the antiderivative of `DiracDelta(-t)` be right-continuous at 0? If not, why not? If yes, then:
2. Is `DiracDelta(t)==DiracDelta(-t)` true?

If you do not have good answers to these questions, you cannot say that using `Heaviside(0)==0` is safe for you ;)

> Since we use dirac delta a lot, there should be a way to indicate the heaviside function created from integrating the dirac delta is based on what convention.

Because the sign of the argument of `DiracDelta(t)` is a serious problem in such questions if you use an asymmetric definition of `Heaviside`, you should probably change it by hand on a per-case basis after integration, like so:

```
from sympy import *
t = symbols('t', real=True)
f = integrate(DiracDelta(t)+DiracDelta(t-2))
print(f)
print(f.subs(t,0))
g=f.replace(Heaviside, lambda t,k: Heaviside(t,0))
print(g)
print(g.subs(t,0))
```

The output of this is

```
Heaviside(t) + Heaviside(t - 2)
1/2
Heaviside(t, 0) + Heaviside(t - 2, 0)
0
```

**Comment by hanspi42** [comment]
@FeryET: Is this still an important issue for you, or can it be closed?

**Comment by hanspi42** [comment]
This has been stale for years, so I close it.
