### ISSUE TITLE
Integral(1/abs(x), x).doit() returns an incomplete answer as output 

### ISSUE THREAD

**Issue by anutosh491** [sympy/sympy#22533]
This was pointed out on the gitter channel a week back or two but I'm not sure if the user remembered to raise the issue on the github page and hence I am raising it before it gets lost in the chat !

On Master
```
>>> x = Symbol('x', real=True)
>>> Integral(1/abs(x), x).doit()
Piecewise((-log(x), x <= 0), (nan, True))
```
The correct answer for this should `sign(x)*log(abs(x))` for all points except 0 where it should be returning `nan` . I'm not sure where this might be going wrong due to my inexperience with the `Integrals` module but the output seems to capture one half of the number line correctly and returns `nan` for all other values of `x`

**Comment by NikhilSDate** [comment]
I would love to work on this issue! However, I'm a newbie to sympy contributing so someone might have to guide me through it. I've been playing around with the code and am trying to look at the cause of the issue.

**Comment by anutosh491** [comment]
Cool you should go forward with it , though I'm myself inexperienced with the Integrals module so I guess I might not be of much help but surely you'll find people here who could help you with this ! 
Maybe @oscarbenjamin could get you started with some basic guidance for the same

**Comment by NikhilSDate** [comment]
I think I have found the source of this problem. When you call integrate on 1/Abs(x) it internally gets converted into a piecewise function. And by default, when a piecewise function is integrated, it calls the _eval_integral method, which tries to return an output so that evaluating the output at two different points and subtracting gives the definite integral between those two points. In this case, the definite integral of 1/Abs(x) on any interval when both endpoints are negative is defined, so you get the correct answer for negative numbers. However, as soon as you cross over to positive numbers, the integral becomes infinite, causing the nan for positive numbers. You can get around this problem by rewriting 1/Abs(x) as a piecewise function and using piecewise_integrate, but I still think something should be done about this, since this does not let you use the result of integrate to evaluate definite integrals where both limits are positive. 
Perhaps there is some way to automatically detect that an infinity has been produced in _eval_integral and fall back on piecewise_integrate?

**Comment by oscarbenjamin** [comment]
It isn't generally possible to construct an antiderivative that can work for the fundamental theorem of calculus for all possible intervals because the theorem only applies if the function is continuous throughout the region which `1/Abs(x)` is not at `x=0`.

**Comment by NikhilSDate** [comment]
Is a fix even necessary for this issue then?
Perhaps, if the function has an infinite discontinuity on a particular interval, `eval_integral` should not try to make the result wok with the fundamental theorem of calculus. That way, the part of the result for positive numbers would be more helpful than `nan` while keeping the part for negative numbers preserved.

**Comment by oscarbenjamin** [comment]
Ideally an indefinite integral would at least give a locally valid antiderivative. In this case the antiderivative is not valid for positive x.

**Comment by anutosh491** [comment]
Yeah agreed . I hadn't given much thought about this, though I was initially convinced with what the user had reported in the gitter channel . Closing this as of now . Thank you !

**Comment by oscarbenjamin** [comment]
Reopening: `integrate(1/Abs(x), x)` where `x` is a real symbol should give a result that is valid for positive `x`.

**Comment by NikhilSDate** [comment]
I replaced line 519 of functions/elementary/piecewise.py on master, which is 
```args.append((sum, cond))
```
with 
```
if sum.has(oo, -oo, S.ComplexInfinity, Undefined) and not anti.has(oo, -oo, S.ComplexInfinity, Undefined):
    args.append((anti, cond))
else:
    args.append((sum, cond))
```
This seems to fix the issue. Essentially, what this does is that if `anti` evaluated on the current interval results results in a nan or an infinity (which is what causes `sum` to be `nan`), and anti itself does not contain `nan` or some type of infinity, it uses `anti` instead of `sum` for that interval. 
I ran the tests in bin/test and bin/doctest and all tests seem to be running OK. Is there something obviously wrong with this change or could it potentially cause any problems? Otherwise, would it be alright if I submitted a pull request for this issue? This is my first sympy contribution so I'm not quite sure what to do at this point.

**Comment by anutosh491** [comment]
You should maybe discuss your ideas or ask for suggestions here, but if you have a solution already consider creating a pull request and discussing the issue there ! 

People would also be able to review and acknowledge your changes whereas here people won't possibly be able to check if it is a valid solution or not .

**Comment by NikhilSDate** [comment]
Alright, I'll submit a pull request soon.

**Comment by anutosh491** [comment]
> Alright, I'll submit a pull request soon.

Also the expression should return `nan` at x = 0, take care of that too , `Piecewise((-log(x), x <= 0), (log(x), True))` might be missing out on that . The correct answer in non piecewise form for this is `x*ln(abs(x))/abs(x)` , so look out for the `nan` case too

**Comment by NikhilSDate** [comment]
log(0) is already `zoo` so does it need to explicitly have `nan` at x=0? `integrate(1/x)` does not really return `nan` specifically at x=0. It just returns log(x), not `Piecewise((log(x), x!=0), (nan, True))`. Any thoughts?

**Comment by anutosh491** [comment]
These are two seperate cases you are talking about , the case we are solving basically boils down to something like `x*ln(abs(x))/abs(x)` or `sign(x)*log(x)`  where sign stands for the signum function . yeah I agree `log(0)` is `zoo`  but what do you think `sign(0) * log(0)` should give back ???
```
>>> sign(0) *log(0)
nan
```
Well I confirmed this with Wolfram and couple other CAS libraries too !

**Comment by NikhilSDate** [comment]
Hmm, I see what you mean now. However, I cannot see an easy way to do this. Any suggestions? Otherwise, I'll submit the PR for my original solution since it's at least better than having `nan` for all x>0. 
Interestingly, if you give WolframAlpha 1/abs(x) to integrate as a piecewise function (-1/x for x<0 and 1/x for x>=0), it doesn't give you sgn(x)log(x) but instead gives -log(x) for x<=0 and log(x) for x>0.

**Comment by anutosh491** [comment]
I had referred to this and couple other libraries and I am certainly sure it should either be this or something like `x*ln(abs(x))/abs(x)`
![image](https://user-images.githubusercontent.com/87052487/142800589-fd91deae-1b77-424b-9a4f-99afed25886e.png)
As I pointed out this wasn't an issue I discovered originally and the user who found this also wanted `nan` at `0` as he reported in the gitter channel . Give it a try maybe and if you still struggle we can have a look ! 

> Hmm, I see what you mean now. However, I cannot see an easy way to do this. Any suggestions? Otherwise, I'll submit the PR for my original solution since it's at least better than having `nan` for all x>0.
I personally feel it's not that appropriate to return output if the output is not complete in any way but yeah you could open one for this

**Comment by NikhilSDate** [comment]
> I had referred to this and couple other libraries and I am certainly sure it should either be this or something like x*ln(abs(x))/abs(x)

Yes, for 1/abs(x) entered directly it gives the right answer, but what I meant is that when you enter it as a piecewise function it does not give sgn(x)log(x). 
![Screenshot (928)](https://user-images.githubusercontent.com/47920034/142804308-aed91762-ba43-446d-99bb-49c8842edbf4.png)
Currently sympy gives `nan` for positive numbers even when you enter 1/Abs(x) as a piecewise function so my solution at least fixes that. I'll still try to see if I can get it to give `nan` for x=0 though.

**Comment by anutosh491** [comment]
Ohh cool , I got your point ! Yeah go for it ! @oscarbenjamin what are your thoughts regarding the output !

**Comment by NikhilSDate** [comment]
I have created a pull request that addresses this issue.
