### ISSUE TITLE
evalf unintentionally creates Tuple with None as argument

### ISSUE THREAD

**Issue by ThePauliPrinciple** [sympy/sympy#22581]
In `terms.count` the terms get converted to `Tuple` during the comparison with `S.ComplexInfinity` but it will contain `None` as arguments
https://github.com/sympy/sympy/blob/ed0bfd1e47345c8bd45ef542eef18f6a21c55685/sympy/core/evalf.py#L599-L604
I believe this can be resolved with
```python
n = sum([term.count(S.ComplexInfinity) for term in terms])
```
to avoid the creation of `Tuple`s.

**Comment by oscarbenjamin** [comment]
I don't understand where the Tuples are created. Here `terms` is a plain Python `list` and `count` is a method of `list`. I guess it uses `==` internally to compare things. Is the bug the fact that `S.ComplexInfinity == a` sympifies `a` so that if `a` is a tuple then it becomes a `Tuple`?

Maybe there's a better way to avoid this. I haven't looked at the code in detail so not sure.

**Comment by ThePauliPrinciple** [comment]
Yes, exactly this happens in `S.ComplexInfinity`'s `__eq__` method.

**Comment by oscarbenjamin** [comment]
I would prefer it if:
- `Tuple.__new__` at least warned about non-Basic args
- The code here explicitly checked for tuple before comparing with zoo

**Comment by ThePauliPrinciple** [comment]
Currently, such a warning would lead to many warning during normal use of SymPy. See some of the remaining errors in #22445 (there are currently 43 and 42 in resp. test1 and test2). `Tuple` is abused sometimes to apply `sympify` to a bunch of variables (that potentially include `None`, which `Tuple` currently handles due to using `sympify`). I feel that this project is pretty close to getting where there is no case that `Basic.__new__` gets non-`Basic` at least as far as the tests go, so such a warning could also go there.

I'll rewrite the checking here to be more explicit.
