### ISSUE TITLE
`simplify` changes state of internal random generator

### ISSUE THREAD

**Issue by jan-philipp-hoffmann** [sympy/sympy#22592]
I'm afraid [`sympy.core.ramdom`](https://github.com/sympy/sympy/blob/4489b4c7c51a65966b1a95f2af6f7e0c8c461794/sympy/core/random.py#L1-L10) brings back an old issue with `random` in `sympy`. 

See
```
>>> from sympy import I, simplify
>>> from sympy.core.random import rng
>>> rng.getstate()[1][-1]
624
>>> simplify(-I)
-I
>>> rng.getstate()[1][-1]
497
```
actually this comes from an lazy import inside of `simplify`

```
>>> from sympy.core.random import rng
>>> rng.getstate()[1][-1]
624
>>> from sympy.physics.units.quantities import Quantity
>>> rng.getstate()[1][-1]
489
```
The actual problem seems to be deep in the units system when it comes to multiply when it comes to multiply two units like `mass * time`

https://github.com/sympy/sympy/blob/52f606a503cea5e9588de14150ccb9f7f9ed4752/sympy/physics/units/systems/length_weight_time.py#L102

**Comment by oscarbenjamin** [comment]
It's coming from here:
https://github.com/sympy/sympy/blob/52f606a503cea5e9588de14150ccb9f7f9ed4752/sympy/core/assumptions.py#L551
I'm not sure why this should be considered a problem though. It is only the state of the sympy rng that is altered so the global rng in the math module is not.

**Comment by jan-philipp-hoffmann** [comment]
issue came up, when I tried to use `sympy.core.random` as suggested to [generate random matrices](https://github.com/sympy/sympy/pull/22103#discussion_r761447247). but then many test failed, depending wether `simplify` was called or not.

Same behaviour here:
```
from sympy import simplify, I
from sympy.combinatorics import Permutation
from sympy.combinatorics.perm_groups import PermutationGroup
from sympy.core.random import rng

G = PermutationGroup(Permutation(1, 0, 2), Permutation(2, 1, 3))
rng.seed(123)
simplify(-I)
print(G.random())  # -> (0 1 3)
rng.seed(123)
print(G.random())  # -> (3)
```
maybe those `sympy` functions should not rely on the internal rng?

**Comment by ThePauliPrinciple** [comment]
Can't the tests be updated with the new numbers?

**Comment by jan-philipp-hoffmann** [comment]
that sounds a bit dirty to me.  I could avoid `-I` during testing but this doesn't seem to be a realistic test any more.

the tests choose matrix entries randomly from lists like `1, -1, I, -I`. 
but only if `-I` is chosen the problem happens since only `simplify(-I)` changes the state of `rng`. For instance `simplify(I)` does not change `rng`.

**Comment by jan-philipp-hoffmann** [comment]
see this [notebook](https://colab.research.google.com/drive/1ZPpCHChLDcyBrzNHRffjo5R8UpK_KLNh?usp=sharing) to reproduce the issue with `PermutationGroup`.

**Comment by oscarbenjamin** [comment]
Okay I see. The problem is that there are two sources of randomness:

1. Set order (varies from one run of the process to another).
2. SymPy's global RNG

Somewhere in `simplify` due to non-deterministic set order the number of samples drawn from the RNG is non-deterministic. That means that seeding the generator, then calling `simplify` and then sampling from the RNG does not give reproducible values from one process to another:
```console
$ cat t.py 
from sympy import *
from sympy.core.random import seed, randint

seed(4)
simplify(-I)
print(randint(0, 5))
$ python t.py 
3
$ python t.py 
5
```

**Comment by oscarbenjamin** [comment]
This diff can help to debug this by entering the debugger when a random function is used:
```diff
diff --git a/sympy/core/random.py b/sympy/core/random.py
index d0308c6..b91c192 100644
--- a/sympy/core/random.py
+++ b/sympy/core/random.py
@@ -26,13 +26,19 @@
 import random as _random
 rng = _random.Random()
 
-choice = rng.choice
-random = rng.random
-randint = rng.randint
-randrange = rng.randrange
-seed = rng.seed
-shuffle = rng.shuffle
-uniform = rng.uniform
+def wrapped(func):
+    def wrapper(*args, **kwargs):
+        breakpoint()
+        return func(*args, **kwargs)
+    return wrapper
+
+choice = wrapped(rng.choice)
+random = wrapped(rng.random)
+randint = wrapped(rng.randint)
+randrange = wrapped(rng.randrange)
+seed = wrapped(rng.seed)
+shuffle = wrapped(rng.shuffle)
+uniform = wrapped(rng.uniform)
 
 def random_complex_number(a=2, b=-1, c=3, d=1, rational=False, tolerance=None):
     """
```

**Comment by oscarbenjamin** [comment]
A possible fix is:
```diff
diff --git a/sympy/core/assumptions.py b/sympy/core/assumptions.py
index b8a8c19..bc81d22 100644
--- a/sympy/core/assumptions.py
+++ b/sympy/core/assumptions.py
@@ -214,7 +214,7 @@
 from .core import BasicMeta
 from .sympify import sympify
 
-from sympy.core.random import shuffle
+from sympy.core.random import rng_assumptions
 
 
 _assume_rules = FactRules([
@@ -530,7 +530,7 @@ def _ask(fact, obj):
 
     # Try assumption's prerequisites
     prereq = list(_assume_rules.prereq[fact])
-    shuffle(prereq)
+    rng_assumptions.shuffle(prereq)
     for pk in prereq:
         if pk in assumptions:
             continue
diff --git a/sympy/core/random.py b/sympy/core/random.py
index d0308c6..36ba62f 100644
--- a/sympy/core/random.py
+++ b/sympy/core/random.py
@@ -25,6 +25,7 @@
 
 import random as _random
 rng = _random.Random()
+rng_assumptions = _random.Random()
 
 choice = rng.choice
 random = rng.random
@@ -34,6 +35,12 @@
 shuffle = rng.shuffle
 uniform = rng.uniform
 
+
+def seed(intseed):
+    rng.seed(intseed)
+    rng_assumptions.seed(intseed)
+
+
 def random_complex_number(a=2, b=-1, c=3, d=1, rational=False, tolerance=None):
     """
     Return a random complex number.
```

**Comment by sylee957** [comment]
> from sympy import simplify, I
> from sympy.combinatorics import Permutation
> from sympy.combinatorics.perm_groups import PermutationGroup
> from sympy.core.random import rng
> 
> G = PermutationGroup(Permutation(1, 0, 2), Permutation(2, 1, 3))
> rng.seed(123)
> simplify(-I)
> print(G.random())  # -> (0 1 3)
> rng.seed(123)
> print(G.random())  # -> (3)

I would correct the example that it should work perfectly deterministic when you put `rng.seed` just before executing the function
```python3
G = PermutationGroup(Permutation(1, 0, 2), Permutation(2, 1, 3))
simplify(-I)
rng.seed(123)
print(G.random())
rng.seed(123)
print(G.random())
```

**Comment by oscarbenjamin** [comment]
> put rng.seed just before executing the function

The point is that you should ideally be able to seed a whole program just once and get deterministic behaviour from any functions that are pseudorandom.

The randomness in the core assumptions should not have any outwardly observable behaviour because it just calls different handlers in a different order but those handlers *should* all be consistent. Therefore seeding the assumptions system should not affect anything except in the case of reproducing bugs.

However iterating over say a set in a different order (which can happen on Linux due to address space randomisation as well as the hash-seed) might lead to assumptions queries being called in a different order. This in turn leads to the assumptions system pulling a different number of items from the RNG which then means that the use of the RNG is no longer deterministic.

The problem with the assumptions system in particular is that it is used implicitly as part of everything so if it is allowed to alter the RNG then everything alters the RNG. Of course in principle the way that the assumptions system alters the RNG should be deterministic when seeded but there are other unseedable sources of pseudo-randomness in set ordering.

There are only a few choices if we want to preserve the possibility of being able to seed the behaviour of a whole program that uses SymPy's explicitly pseudorandom functions:

1. Make sure that set order is never used for anything (even in situations where the order shouldn't matter).
2. Make sure that whenever set order is used no assumptions queries occur while iterating over the set.
3. Have the assumptions system use a different RNG.

The associated PR #24521 follows approach 3. I think that approach 2 is impossible. Approach 1 is possible and has some other benefits but requires wide changes and a deep review of the codebase. Also approach 1 implies a slowdown in some cases as a result of sorting sets that don't otherwise need to be sorted.

Outside the core assumptions pseudo-randomness is more well contained so ensuring that it doesn't interact with set order is easier (i.e. we can follow approach 2 much more easily for everything else).

**Comment by sylee957** [comment]
It looked like the problem originated from the side effects of functions interfering each other by hidden dependency
So even if the assumptions are solved, if assumptions are only stuff that gets independent RNG, then I can make other counter example like 

```python3
from sympy.combinatorics import Permutation
from sympy.combinatorics.perm_groups import PermutationGroup
from sympy.core.random import rng
from sympy.polys.domains import ZZ
from sympy.polys.galoistools import gf_random


G = PermutationGroup(Permutation(1, 0, 2), Permutation(2, 1, 3))

rng.seed(123)
gf_random(10, 5, ZZ)
print(G.random())
rng.seed(123)
print(G.random())
```
Despite the changes from https://github.com/sympy/sympy/pull/24521 because `gf_random` still shares the seed
So it means that we need global RNG for each functions, at least

**Comment by oscarbenjamin** [comment]
No, that's really not equivalent. Try running this script many lines with or without the `simplify` line:
```python
from sympy.combinatorics import Permutation
from sympy.combinatorics.perm_groups import PermutationGroup
from sympy.core.random import rng
from sympy.polys.domains import ZZ
from sympy.polys.galoistools import gf_random
from sympy import simplify, I


G = PermutationGroup(Permutation(1, 0, 2), Permutation(2, 1, 3))

rng.seed(123)
#simplify(-I)
gf_random(10, 5, ZZ)
print(G.random(), end=' ')
rng.seed(123)
print(G.random())
```
What you can see is that even though you have seeded the rng the calls are not deterministic. Without `simplify` you get:
```console
$ for i in `seq 1 100`; do python g.py; done
(0 1)(2 3) (3)
(0 1)(2 3) (3)
(0 1)(2 3) (3)
(0 1)(2 3) (3)
(0 1)(2 3) (3)
(0 1)(2 3) (3)
(0 1)(2 3) (3)
(0 1)(2 3) (3)
(0 1)(2 3) (3)
(0 1)(2 3) (3)
(0 1)(2 3) (3)
(0 1)(2 3) (3)
(0 1)(2 3) (3)
(0 1)(2 3) (3)
(0 1)(2 3) (3)
(0 1)(2 3) (3)
...
```
With the `simplify` you get:
```console
$ for i in `seq 1 100`; do python g.py; done
(3)(0 1 2) (3)
(1 2 3) (3)
(1 3 2) (3)
(1 2 3) (3)
(0 1 3) (3)
(0 2)(1 3) (3)
(0 1 3) (3)
(0 3)(1 2) (3)
(0 3 1) (3)
(1 3 2) (3)
(0 1)(2 3) (3)
(1 2 3) (3)
(0 3 2) (3)
(3)(0 1 2) (3)
(1 3 2) (3)
(3)(0 2 1) (3)
(1 3 2) (3)
(0 2 3) (3)
(3)(0 1 2) (3)
(0 2)(1 3) (3)
(0 1 3) (3)
(1 2 3) (3)
...
```
The whole program is not deterministic. The `simplify` call is not supposed to affect the RNG and does not deliberately call any values from the RNG. It does however use the assumptions system (just as everything does).

**Comment by sylee957** [comment]
I don't get the same result as yours,
In the first example, I get different result for first and second print, but same result across consecutive python runs.
And in the second example, I get different result for

I only observe that the RNG itself gets called randomized times inside `simplify`, but called in a fixed number of time inside `gf_random` though. I'm not sure if that was from implicit usage of sets, but maybe that's what you want to fix though.

**Comment by oscarbenjamin** [comment]
> I don't get the same result as yours, In the first example, I get different result for first and second print, but same result across consecutive python runs. And in the second example, I get different result for

The second sentence here is incomplete. I can't tell the difference between what you are describing and what I showed. Can you show the output that you get?

> I only observe that the RNG itself gets called randomized times inside `simplify`, but called in a fixed number of time inside `gf_random` though. I'm not sure if that was from implicit usage of sets, but maybe that's what you want to fix though.

Setting PYTHONHASHSEED makes it deterministic so yes it is caused by set iteration order (somewhere, perhaps in many places).

**Comment by sylee957** [comment]
Okay, I confirm that the result is same, but I tweaked printing function so it looked different.

**Comment by oscarbenjamin** [comment]
@sylee957 it is unclear to me right now if you are objecting to the approach in #24521.

I layed out the options above: https://github.com/sympy/sympy/issues/22592#issuecomment-1382251849

If you think that option 1 is preferable then I suggest taking a moment to grep the codebase for possible places where something might iterate over a set and consider that `simplify` is only one possible function that we might be concerned about. Parts of the codebase that depend on semantically on set order were already changed when PYTHONHASHSEED was introduced. What we are left with are some places where the set order should not matter in the same way that the assumptions ordering should not matter but the interaction between these matters if you care about the seed giving deterministic behaviour for pseudo-random things.

**Comment by sylee957** [comment]
I don't object to the approach of #24521, but I think that streamlining the global RNG to use in every parts of random module eventually ends up in vain.
Instead, I think that the designer of each random functions should be responsible that each functions they design specifically accepts own random seed, and specifically guarantee that their own sampling method is independent from other parts of sympy.  
I think that it is more hard to make sympy global random seed to be independent from such hidden nondeterminism, and can lead to adhoc changes (we specifically dealt only for assumptions, but we don't know if other parts of sympy start using set with RNG)
