### ISSUE TITLE
nonlinsolve is incorrect

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#22628]
`nonlinsolve([h - 1, k - 1, f - 2, f - 4, -2*k], h, k, f)` returns `{(1, 1, f)}`, but this system doesn't have a solution.

**Comment by oscargus** [comment]
Even smaller example: `nonlinsolve([h - 1, f - 2, f], h, f)`

**Comment by proy87** [comment]
Also `[-x - y**2/(4*z - 4*x) + 606649379/2000, -x - (183/1000 - y)**2/(4*z - 4*x) + 2068122883/5000, -x - (861457/1000000 - y)**2/(4*z - 4*x) + 3057162/5]` takes too much time, because it searches `_integer_basis`.

**Comment by oscarbenjamin** [comment]
> I just copied their string representation.

When reporting an issue it's important that code samples be copyable. It's better if you can patch up the output by changing e.g. `2/3` to `S(2)/3` so that it's clear to anyone reading it that you are using exact types and so that they can copy paste the result and see the same effect as the one that you report.

**Comment by proy87** [comment]
@oscarbenjamin, OK.

**Comment by NikhilSDate** [comment]
I was trying to investigate the cause of this issue when I noticed something odd in the code for `nonlinsolve` in the following lines
https://github.com/sympy/sympy/blob/0bdb9fee3a4e2de8c3f8dc7b440f80da8045b87c/sympy/solvers/solveset.py#L3668-L3669
According to the comment, the if statement is supposed to be checking if all the equations in the system are polynomials, but the condition actually seems to be checking if the number of polynomials and the number of symbols is the same. In particular, when calling `nonlinsolve` on @oscargus's example, even though all the equations in the system are polynomials, the condition in the if is false because there are three equations and two symbols. Does anyone have any idea why the code is written this way? 

Also, would simply using something like `checksol` in `nonlinsolve` to make sure the solutions produced are actually valid and returning `EmptySet` otherwise be an acceptable fix to this issue, even though it does not fix the root of the problem? If so, I would be happy to implement the fix.

**Comment by oscargus** [comment]
> Does anyone have any idea why the code is written this way?

I guess whoever wrote it didn't think of the opportunity to have redundant equations. In my example, adding a third symbol and keep the equations will enable this branch, but it will not change anything fundamental when it comes to the solution. So maybe one should consider <=? (Especially the comment seems to be incorrect, even if that holds it may not be the case that "all equations in the system are poly".)

**Comment by oscarbenjamin** [comment]
The system of equations is linear. It should be easy to show that there are no solutions:
```python
In [8]: h, k, f = symbols("h, k, f")

In [9]: eqs = [h - 1, k - 1, f - 2, f - 4, -2*k]

In [10]: M, b = linear_eq_to_matrix(eqs, [h, k, f])

In [11]: Maug = Matrix.hstack(M, b)

In [12]: M.rank() == Maug.rank()
Out[12]: False
```
I don't know how `nonlinsolve` does this but it should split out linear equations and use linear methods to solve them.

Also it should have a routine for identifying equations that are trivially solved or solvable like each of these examples so that they can be removed from the system before even attempting any system solution methods.

Lastly it should split the system into connected components in the same way that `solve` does.

**Comment by NikhilSDate** [comment]
@oscarbenjamin For now, I'm trying to fix the weird `if` condition. I will try to submit a PR for that soon. Would that fix have any conflicts with anything you're suggesting?

**Comment by oscarbenjamin** [comment]
It looks like this should be `<=` as @oscargus says since both `is_zero_dimensional` and `solve_poly_system` can handle systems with more equations than unknowns.

There are quite a few things that don't really make sense here. All the logic should be checked carefully and probably rewritten. 

From the looks of things `is_zero_dimensional` computes a Groebner basis and so does `solve_poly_system`. If the basis computed by `solve_poly_system` is not enough to solve the system then `NotImplementedError` is raised. It's probably better not to bother calling `is_zero_dimensional` at all but just to check whether `solve_poly_system` raises `NotImplementedError`.

The `_handle_positive_dimensional` function *also* computes a Groebner basis. All of these functions compute a Groebner basis so it would be better just to compute one right at the start. The Groebner basis can also tell straight away if there are no solutions meaning that nothing else needs to be tried and empty set can just be returned.

This line skips equations that are just numbers
https://github.com/sympy/sympy/blob/0bdb9fee3a4e2de8c3f8dc7b440f80da8045b87c/sympy/solvers/solveset.py#L3471-L3472
This means e.g.:
```python
In [27]: nonlinsolve([x + y, 1], [x, y])
Out[27]: {(-y, y)}
```
That should be the empty set.

Even if only some of the equations in the system are polynomials it would still be better to solve those using the polynomial system solving methods regardless of whether that gives a full solution for everything. Likewise if any of the equations are linear then they should be solved using a linear solver to eliminate some of the variables of the problem before using polynomial techniques.

Extending this idea we might have equations that are linear in a subset of the symbols even if they are nonlinear in others. It will sometimes be possible to identify a subset of the symbols and equations that gives a linear problem that can then be used to simplify the remaining nonlinear problem e.g.:
```python
In [21]: eqs = Tuple(x - y + exp(z), x + y + exp(2 * z), exp(z) - x * y)

In [22]: eqs
Out[22]: 
⎛         z           2⋅z          z⎞
⎝x - y + ℯ , x + y + ℯ   , -x⋅y + ℯ ⎠

In [23]: solve(eqs[:2], [x, y], dict=True)
Out[23]: 
⎡⎧      2⋅z    z        2⋅z    z⎫⎤
⎢⎪     ℯ      ℯ        ℯ      ℯ ⎪⎥
⎢⎨x: - ──── - ──, y: - ──── + ──⎬⎥
⎢⎪      2     2         2     2 ⎪⎥
⎣⎩                              ⎭⎦

In [24]: [sol] = solve(eqs[:2], [x, y], dict=True)

In [25]: eqs.subs(sol)
Out[25]: 
⎛        ⎛   2⋅z    z⎞ ⎛   2⋅z    z⎞     ⎞
⎜        ⎜  ℯ      ℯ ⎟ ⎜  ℯ      ℯ ⎟    z⎟
⎜0, 0, - ⎜- ──── - ──⎟⋅⎜- ──── + ──⎟ + ℯ ⎟
⎝        ⎝   2     2 ⎠ ⎝   2     2 ⎠     ⎠
```

All methods compute Groebner bases with the default lex order but my understanding is that lex is usually a bad choice for this:
https://en.wikipedia.org/wiki/Monomial_order#Lexicographic_order

It might be possible to optimise the order of the symbols to produce a better Groebner basis rather than using a completely arbitrary order:
https://github.com/sympy/sympy/blob/0bdb9fee3a4e2de8c3f8dc7b440f80da8045b87c/sympy/solvers/solveset.py#L3422

**Comment by NikhilSDate** [comment]
> It looks like this should be <= as @oscargus says since both is_zero_dimensional and solve_poly_system can handle systems with more equations than unknowns.

Shouldn't this be `if len(system)==len(polys)`? The following diff tries to solve systems with only polynomials using only polynomial methods as far as I know and also correctly returns `EmptySet` for polynomials with no solution. I've also tried a few cases with more symbols than equations and it seems to work fine. I might submit a PR with this change and @oscarbenjamin's suggestion of the single Groebner basis calculation if such a change makes sense.
```diff
@@ -3665,10 +3665,11 @@ def nonlinsolve(system, *symbols):
         return _solveset_work(system, symbols)

     # main code of def nonlinsolve() starts from here
+    nonconstant = [eqn for eqn in map(_sympify, system) if eqn.free_symbols & set(symbols)]
     polys, polys_expr, nonpolys, denominators = _separate_poly_nonpoly(
-        system, symbols)
+        nonconstant, symbols)

-    if len(symbols) == len(polys):
+    if len(system) == len(polys):
         # If all the equations in the system are poly
         if is_zero_dimensional(polys, symbols):
             # finite number of soln (Zero dimensional system)
```
As far as using linear methods to solve linear systems is concerned, since solving by Gauss-Jordan elimination is, in a way, just a form of substitution, would that offer any efficiency or correctness benefit compared to substitution as nonlinsolve uses it?

> Likewise if any of the equations are linear then they should be solved using a linear solver to eliminate some of the variables of the problem before using polynomial techniques.
Extending this idea we might have equations that are linear in a subset of the symbols even if they are nonlinear in others. It will sometimes be possible to identify a subset of the symbols and equations that gives a linear problem that can then be used to simplify the remaining nonlinear problem e.g.:

Maybe this could be done with a graph-theoretic approach with having each equation as a node and connecting it to all equations that are linear in the same symbols, and then identifying connected components and solving each connected component using `_linsolve`. While doing this, all symbols that do not appear in a system could be added on with zero coefficients. Do any functions already exist for determining the symbols an equation is linear in? I think such an algorithm should work if we limit ourselves to defining linear in a variable as the variable has constant coefficients in every term of the equation (maybe after the equation has been simplified), as in @oscarbenjamin's example.
The same approach might work for finding subsets of the system that are polynomial in some variables.
