### ISSUE TITLE
Incorrect LaTeX display of a determinant

### ISSUE THREAD

**Issue by dispasha** [sympy/sympy#22763]
It displays like |(A)| instead of |A|. I fixed that issue for myself in LatexPrinter like this:
```python
    def _print_Determinant(self, expr, exp=None):
        mat_delim_backup = self._settings['mat_delim']
        self._settings['mat_delim'] = ''
        tex = r"\left|{%s}\right|" % self._print(expr.args[0])
        self._settings['mat_delim'] = mat_delim_backup
        if exp is not None:
            return r"%s^{%s}" % (tex, exp)
        else:
            return tex
```
instead of `_print_Determinant = _print_Abs`, but for two reasons I didn't create the pull request: I don't have time to comply with all the requiements and I'm not sure this is the best way to solve this issue

**Comment by oscargus** [comment]
I think this is probably a good enough way to solve it. The option would be to set the delimiter to `|`, but both approaches would include modifying and restoring the delimiter, so I cannot really see any benefit of the other way, rather the opposite.

I think the only "requirement" is to add a test for it (and make sure the file ends with a single empty line in case you add the test at the end of the file). And, worst case, update any test that may use the previous formatting (but I do not know if there are any). Think about it, otherwise I can create a PR for it.

**Comment by oscargus** [comment]
I have added this and set the author to your github user. Will be closed once merged. Thanks!

**Comment by oscargus** [comment]
Turned out that a slightly different version was required to deal with e.g. determinant of a sum of a matrix and a matrixsymbol. But this works for the base case.

**Comment by dispasha** [comment]
> Turned out that a slightly different version was required to deal with e.g. determinant of a sum of a matrix and a matrixsymbol. But this works for the base case.

Yeah I noticed that later. That's why I wasn't completely sure. Thank you!
