### ISSUE TITLE
Plotting Plot 3D

### ISSUE THREAD

**Issue by KuldeepBorkar** [sympy/sympy#22786]
Why is it not possible to label the z axis the same way we label x axis and y axis?
Here is an example:
We can see the Label X, Label Y but not the Label Z,
the `zlabel` in the code here does nothing.
```
from sympy import symbols
from sympy.plotting import plot3d
x, y = symbols('x y')
plot3d(x*y, (x, -5, 5), (y, -5, 5), xlabel="Label X", ylabel="Label Y", zlabel="Label Z")
```

**Comment by MiguelAMLucero** [comment]
Hi, I run your example, but I didn't found any trouble. Here's my plot. You got a different output? I'm running on mac with  `python 3.10` and  `sympy 1.10.dev0` 
![Figure_1](https://user-images.githubusercontent.com/92400491/147954228-50656987-3d62-4305-a385-a62addeea738.png)
.

**Comment by KuldeepBorkar** [comment]
It is a version problem probably since it was working the same way as shown here by @ThePauliPrinciple ,  
after using `sympy version 1.9` and above it works fine as shown by @MiguelAMLucero .
Maybe it may not be working for the other previous releases too.

**Comment by anutosh491** [comment]
Maybe this could be closed then , if it's not really an issue ?

**Comment by KuldeepBorkar** [comment]
@anutosh491 So what you are saying is if people are using any previous release of sympy then they should just install the latest release that's the solution?

**Comment by anutosh491** [comment]
> @anutosh491 So what you are saying is if people are using any previous release of sympy then they should just install the latest release that's the solution?

Well if you think otherwise then obviously sympy's previous releases won't have the  updated code/features from the latest release right ,so like how do you fix this ? Obviously by moving to the latest release right ! 
And by closing the issue ,I meant something else . My 7-8 months of experience of contributing to sympy github  and being active on the mailing list tells me that version disputes/doubts are usually discussed on the mailing list or the gitter channel. The github issues page might not the best place to discuss this as this is not really an issue right ? Works on my setup without any concern !
