### ISSUE TITLE
Tests skipped for uniquely_named_symbol

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#22996]
This test is skipped by the `bin/test` test runner but is picked up by `pytest`:
https://github.com/sympy/sympy/blob/a2e158befc277682a0e5a46dbf8105b882d2519a/sympy/core/tests/test_symbol.py#L347
It seems that in #19074 the name of the test function was modified and without the underscore bin/test ignores it.

The test now fails on the master branch:
```python
>>> from sympy.core.tests.test_symbol import testuniquely_named_symbol_and__symbol
>>> testuniquely_named_symbol_and__symbol()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oscar/current/sympy/sympy.git/sympy/core/tests/test_symbol.py", line 363, in testuniquely_named_symbol_and__symbol
    assert F('x1', Symbol('x1'),
AssertionError
```

The test itself started failing in 8f1409a2bae36e02fb807de33856be460c9fb293 from #22669

CC @smichr @JSS95

**Comment by JSS95** [comment]
The test case seems incorrect.

IIRC, #19704 changes the default behavior of *modify*. Before then, unique name was generated by prepending underscores to *xname* (e.g. `'x'` -> `'_x'`). After #19704, incrementing number is appended to *xname* (e.g. `'x'` -> `'x0'` and `'x1'` -> `'x2'`).

The failing test checks if *compare* transforms the symbol names before comparing them. Since the lambda function strips `'1'`, *xname* `'x1'` and *exprs* `Symbol('x1')` are converted to `'x'` and `'x'` which should return `Symbol('x0')`.
