### ISSUE TITLE
Wrong axis label in bode_plot

### ISSUE THREAD

**Issue by hanspi42** [sympy/sympy#23034]
The code 

```
from sympy.abc import s
from sympy.physics.control.lti import TransferFunction
from sympy.physics.control.control_plots import bode_plot
tf = TransferFunction(1, 1+s, s)
bode_plot(tf)
```

shows that the frequency axis that is labelled with the unit Hz actually should have the unit rad/s.

This should be corrected; at the same time it would be nice to have options for:

- Frequency in Hz or rad/sec
- Amplitude in dB or just as a logarithmic axis
- Phase in rad or deg

Issue created from discussion https://groups.google.com/g/sympy/c/xGz7KB1UKAU/m/twv6AGI1BAAJ?utm_medium=email&utm_source=footer

**Comment by akshanshbhatt** [comment]
Hey! Thanks for bringing up this issue.

I was one of the key contributors to the `control_plots` module during its development. I might have unintentionally labeled the x-axis as Hz (instead of rad/s), which somehow went unnoticed during the code review. You can fix it from here -

https://github.com/sympy/sympy/blob/e074be68742a546bc47f89e46297d87a3921427e/sympy/physics/control/control_plots.py#L750

> This should be corrected; at the same time it would be nice to have options for:
> 
> * Frequency in Hz or rad/sec
> * Amplitude in dB or just as a logarithmic axis
> * Phase in rad or deg

I agree that it would be great to have these options. You can drop a PR anytime.

**Comment by AdvaitPote** [comment]
I'd like to work on this!
