### ISSUE TITLE
ast_parser: PendingDeprecationWarning: visit_Num is deprecated; add visit_Constant

### ISSUE THREAD

**Issue by jwilk** [sympy/sympy#23092]
`sympy.parsing.ast_parser` triggers `PendingDeprecationWarning` in Python ≥ 3.8:
```console
$ python3 -Wd
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sympy.parsing.ast_parser import parse_expr
>>> parse_expr('6 * 7', {})
/usr/lib/python3.8/ast.py:371: PendingDeprecationWarning: visit_Num is deprecated; add visit_Constant
  return visitor(node)
42
```

**Comment by asmeurer** [comment]
This should be easy for someone to fix. I think we still support 3.7 so it will need to have a branch.

**Comment by oscarbenjamin** [comment]
We should really run the tests in CI so that a PendingDeprecationWarning shows up as an error.

**Comment by oscarbenjamin** [comment]
Reopening because the fix in #23096 was incomplete: https://github.com/sympy/sympy/pull/23096#discussion_r810234437

**Comment by wermos** [comment]
There are two ways I can think of fixing this:
We can use the Python version info (which we can get using `sys.version_info`) to conditionally define the relevant function, C preprocessor-style.

Alternatively we can define both functions with identical code, with plans to remove `visit_Num` when we drop support for 3.7. If I understood the AST node visiting code correctly (which I think I did), the Interpreter tries to call `visit_Constant` before falling back to `visit_Num` in versions >= 3.8, so the existence of both functions won't result in a warning.

Since I'm new to the project, I am not sure which method we prefer, so I would appreciate feedback on this.

**Comment by jwilk** [comment]
> we can define both functions with identical code

They can't be literally identical, because `ast.Constant.n` is deprecated too.
(Although at the moment you don't get any warning about this: <https://bugs.python.org/issue46797>.)

**Comment by oscarbenjamin** [comment]
I would rather avoid an explicit Python version check if it isn't needed. I don't really know anything about ast parsing so I can't say what's the best approach though. Either way there should be comments making clear if something should be removed/changed in a future version of sympy.

**Comment by wermos** [comment]
I think we can close this issue now.

@jwilk, I would appreciate if you could look over the new additions and see if we overlooked something again or not, before closing (since you were the one who found the issue with #23096) 😅

**Comment by jwilk** [comment]
https://github.com/sympy/sympy/pull/23122 looks good to me.
