### ISSUE TITLE
Can we just solve the REAL results to speed up when use nonlinsolve.

### ISSUE THREAD

**Issue by findyy99** [sympy/sympy#23165]
- I have a high order and nonlinear equations to be solve. It takes lot of time complete a solution. I guess it is because the nonlinsolve also get the **complex results**, so can I ask the sympy only get the REAL results to save time?
- These is my code.

```
from sympy import *
from sympy.solvers.solveset import nonlinsolve

h_0 = 170
b = 120
Es = 205
h = 200
M = 19760400

def cal(para):
    Ec_f, As_f, ft_f = para
    vp_c, vp_s, x_n = symbols('vp_c, vp_s, x_n', real=True)
    f1 = vp_c / vp_s - x_n / (h_0 - x_n)
    f2 = 1 / 2 * Ec_f * vp_c * b * x_n - As_f * Es * vp_s - ft_f * b * (h - x_n)
    f3 = M - As_f * Es * vp_s * (h_0 - x_n / 3) - ft_f * b * (h - x_n) * (h / 2 + x_n / 6)
    re = nonlinsolve([f1, f2, f3], [vp_c, vp_s, x_n])

    print(re)

    re_t = tuple(re & Reals ** 3)
```
- these is the set of results, I just need the Real parts.
```
{(-0.469378305833599, 1.02614290514871, -143.317861965125), (1.00656308634739, 2.01548035330581, 56.6225231688573), ((-183.969547582998 - 351.920528939668*I)*(0.00608328163162871 - 0.00630805832877277*I + 4.48116677633078e-8*(-183.969547582998 - 351.920528939668*I)**2)/(2.44289841241567 + 1.15340253748558e-5*(-183.969547582998 - 351.920528939668*I)**2 + 2.76016101129151*I), -0.429603644119307*(-1.36072460310392 + 0.690040252822878*I)*(1.03415787737688 - 1.07236991589137*I + 7.61798351976232e-6*(-183.969547582998 - 351.920528939668*I)**2), -183.969547582998 - 351.920528939668*I), ((-183.969547582998 + 351.920528939668*I)*(0.00608328163162871 + 4.48116677633078e-8*(-183.969547582998 + 351.920528939668*I)**2 + 0.00630805832877277*I)/(2.44289841241567 - 2.76016101129151*I + 1.15340253748558e-5*(-183.969547582998 + 351.920528939668*I)**2), -0.429603644119307*(-1.36072460310392 - 0.690040252822878*I)*(1.03415787737688 + 7.61798351976232e-6*(-183.969547582998 + 351.920528939668*I)**2 + 1.07236991589137*I), -183.969547582998 + 351.920528939668*I)}
```

- So, can anyone give me some ideas? Should I continue use sympy or choose other modules, because there have thousands of times loop, I need speed up it. Thanks in advance!!!

**Comment by moorepants** [comment]
If you are using numbers and don't require anything beyond machine precision, you should probably be using scipy's fsolve or similar functions.

**Comment by findyy99** [comment]
> If you are using numbers and don't require anything beyond machine precision, you should probably be using scipy's fsolve or similar functions.

- Thanks for your reply!
- I tried the fsolve, it only can get one solution and it is **negative** while i need **positive** result.
```
from scipy.optimize import fsolve

h_0 = 170
b = 120
Es = 205
h = 200
M = 19760400

def cal(p):
    Ec_f, As_f, ft_f = 42.4, 226, 3
    vp_c, vp_s, x_n = p
    return vp_c / vp_s - x_n / (h_0 - x_n), 1 / 2 * Ec_f * vp_c * b * x_n - As_f * Es * vp_s - ft_f * b * (
            h - x_n), M - As_f * Es * vp_s * (h_0 - x_n / 3) - ft_f * b * (h - x_n) * (h / 2 + x_n / 6)

vp_c, vp_s, x_n = fsolve(cal, (1, 1, 1))
print(cal((vp_c, vp_s, x_n)))
```
- And this is the result.
```
(2.948752353404416e-13, -5.588517524302006e-07, 1.564621925354004e-07)
```

**Comment by oscarbenjamin** [comment]
There are two different kinds of numerical solver. If you want something like Newton's method that can find a root given a close guess then that's something like fsolve or nsolve. If you want something that can guarantee to find all solutions (real or otherwise) with no initial guess then that's a much harder problem. There are pure numerical approaches that can do this if the solution set is zero dimensional (#19164). Otherwise the basic approach for a polynomial system is to compute a Groebner basis which is always a lot slower than something like fsolve/nsolve but it allows finding all possible solutions.

Your equations aren't immediately in polynomial form but can be transformed into polynomials:
```python
from sympy import *

vp_c, vp_s, x_n = symbols('vp_c, vp_s, x_n')

eqs = [
    vp_c/vp_s - x_n/(170 - x_n),
    2544.0*vp_c*x_n - 46330*vp_s + 360*x_n - 72000,
    -46330*vp_s*(170 - x_n/3) - (72000 - 360*x_n)*(x_n/6 + 100.0) + 19760400
]

for eq in eqs:
    pprint(eq)
```
Now we can do some symbolic work to transform this into a polynomial system and we can also use `nsimplify` to turn the floats into rationals (floats and polynomials often don't mix well):
```python
In [54]: eqs2 = [nsimplify(eq.as_numer_denom()[0]) for eq in eqs]

In [55]: for eq in eqs:
    ...:     pprint(eq)
    ...: 
vp_c      xₙ   
──── - ────────
vpₛ    170 - xₙ
2544.0⋅vp_c⋅xₙ - 46330⋅vpₛ + 360⋅xₙ - 72000
            ⎛      xₙ⎞                    ⎛xₙ        ⎞           
- 46330⋅vpₛ⋅⎜170 - ──⎟ - (72000 - 360⋅xₙ)⋅⎜── + 100.0⎟ + 19760400
            ⎝      3 ⎠                    ⎝6         ⎠           
```
Now we can compute the Groebner basis:
```python
In [56]: groebner(eqs2, [vp_c, vp_s, x_n])
Out[56]: 
             ⎛⎡                                     3                  2                           
GroebnerBasis⎝⎣11311550792471200⋅vp_c - 512782632⋅xₙ  - 236134161405⋅xₙ  - 95957193724380⋅xₙ - 5102

                                         3              2                                        4 
289368662500, 784652524450⋅vpₛ - 11448⋅xₙ  - 11043135⋅xₙ  - 4661031420⋅xₙ - 1280048633100, 424⋅xₙ  

           3              2                               ⎤                                    ⎞
+ 192765⋅xₙ  + 76946010⋅xₙ  + 4530610700⋅xₙ - 542584529000⎦, vp_c, vpₛ, xₙ, domain=ℤ, order=lex⎠

In [57]: eqc, eqp, eqx = groebner(eqs2, [vp_c, vp_s, x_n])
```
The final equation of the basis is an univariate polynomial in `x_n` with rational coefficients so we can use `real_roots` to find only the real roots:
```python
In [58]: eqx
Out[58]: 
      4            3              2                               
424⋅xₙ  + 192765⋅xₙ  + 76946010⋅xₙ  + 4530610700⋅xₙ - 542584529000

In [59]: real_roots(eqx)
Out[59]: 
⎡       ⎛     4           3             2                                 ⎞         ⎛     4        
⎣CRootOf⎝424⋅x  + 192765⋅x  + 76946010⋅x  + 4530610700⋅x - 542584529000, 0⎠, CRootOf⎝424⋅x  + 19276

   3             2                                 ⎞⎤
5⋅x  + 76946010⋅x  + 4530610700⋅x - 542584529000, 1⎠⎦
```
We can then isolate only the positive roots:
```python
In [60]: [r for r in real_roots(eqx) if r > 0]
Out[60]: 
⎡       ⎛     4           3             2                                 ⎞⎤
⎣CRootOf⎝424⋅x  + 192765⋅x  + 76946010⋅x  + 4530610700⋅x - 542584529000, 1⎠⎦

In [61]: xsol = [r for r in real_roots(eqx) if r > 0]

In [75]: xsol[0].evalf()
Out[75]: 56.6225231688573
```
Finally for each positive root we can solve the remaining equations which are now linear because the Groebner basis fully isolated all variables:
```python
In [76]: xval = xsol[0].evalf()

In [77]: solve([eqc, eqp, x_n-xval])
Out[77]: [{vp_c: 1.00656308634739, vpₛ: 2.01548035330581, xₙ: 56.6225231688573}]
```
Really what you should be trying to use sympy here for though is to do as much of this as possible symbolically ahead of time. If you take the values that you want to substitute into the equations as symbols and then compute the Groebner basis in terms of those symbols then you can then reuse that and substitute values for the symbols just before calling `real_roots`.

**Comment by smichr** [comment]
I just saw that this was answered here, too, after I wrote an [answer at SO](https://stackoverflow.com/a/71271550/1089161)
