### ISSUE TITLE
Probability returns different outputs

### ISSUE THREAD

**Issue by KuldeepBorkar** [sympy/sympy#23230]
If we consider an example of rolling a single Die then, 
Probability for a particular value should be 1/6 and not 0.
Also probability of not being a certain value should be 5/6 and not 1

In a die there is no such thing like float values so,
```
from sympy.stats import P, Die
X = Die('X', 6)
P(X>5) == P(X==6)
```
The above code should return True but it returns False.

Hopefully, it works just fine if we don't use python operators directly.
If we use `sympy.Ne, sympy.Eq, sympy.Gt` then above things returns exact output.

Example:
```
from sympy.stats import P, Die
from sympy import Eq, Ne
X = Die('X', 6)
P(Ne(X, 6)), P(Eq(X, 6))
```
returns (5/6, 1/6)
but if we directly use python operators,
```
P(X!=6), P(X==6)
```
returns (1, 0)

Similarly,
```
P(Gt(X, 5)) == P(Eq(X, 6))
```
returns True
but with operators > and ==
```
P(X>5) == P(X==6)
```
returns False

(I suppose we can get exactly the same results if we convert python operators to something that works well with SymPy like;
if P(X!=6) is used then it can be internally converted to P(Ne(X, 6)) this way we will always get same results)

Note: In the documentation we can see python operators are directly used like P(X>5) instead of P(Gt(X, 5))
therefore, I guess user won't be using sympy.Gt at first.

**Comment by ThePauliPrinciple** [comment]
In SymPy, the `==` operator tests for structural equality, meaning that the tree structure used to represent the mathematical object is equal, however, objects can be mathematically equal eventhough their tree structure is different. e.g. `2*(a+b)` and `2*a + 2*b` are equal mathematically, but represented as a different tree (multiply first, then add vs. add first then multiply).

You are absolutely right that `==` can be made to test for mathematical equality instead, but that means that the entire library needs to be rewritten because we are currently using `==` to test for structural equality.

So in this particular case, the `X==6` is returning `False` and you are effectively comparing `P(X>5) == P(False)`.

**Comment by oscargus** [comment]
Also, see the first point (after Introduction) in  https://docs.sympy.org/latest/explanation/gotchas.html

I'm closing this.

**Comment by KuldeepBorkar** [comment]
Thank you for the clarification : )

**Comment by KuldeepBorkar** [comment]
Thank you for the clarification : )
