### ISSUE TITLE
Lambdify with latex symbols

### ISSUE THREAD

**Issue by Davide-sd** [sympy/sympy#23374]
I have a complicated expression that needs to be evaluated. If the evaluation fails with numpy, than it switches to sympy. My symbols contains latex syntax.

This is the simplest reproducible example I could come up with:

```python
from sympy import *
import inspect
x1, x2 = symbols("x_{1} x_2")

f1 = lambdify([x1, x2], cos(x1**2 + x2**2))
print(inspect.getsource(f1))

# def _lambdifygenerated(x_1, x_2):
#     return cos(x_2**2 + x_1**2) 
```
So far so good. Note that `x1` was processed to `x_1`. Now, let's switch to SymPy:

```python
f2 = lambdify([x1, x2], cos(x1**2 + x2**2), modules="sympy")
print(inspect.getsource(f2))
```

```text
Traceback (most recent call last):

  File "/home/davide/Documents/Development/envs/sympy_plot/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "/tmp/ipykernel_82217/2465285261.py", line 8, in <module>
    f2 = lambdify([x1, x2], cos(x1**2 + x2**2), modules="sympy")

  File "/home/davide/Documents/Development/envs/sympy_plot/lib/python3.9/site-packages/sympy/utilities/lambdify.py", line 900, in lambdify
    c = compile(funcstr, filename, 'exec')

  File "<lambdifygenerated-12>", line 2
    return cos(x_2**2 + x_{1}**2)
                          ^
SyntaxError: invalid syntax
```

Note that no processing is applied to `x1`, so curl brackets end up in the expression to be executed.

**Comment by oscargus** [comment]
This should probably be fixed in the SymPy-printer (and all printers...) similar to https://github.com/sympy/sympy/pull/20806

**Comment by oscargus** [comment]
Probably the best place is to change here:
https://github.com/sympy/sympy/blob/68c37df362e8585d72fc7ef490013bb8eff16e3e/sympy/printing/codeprinter.py#L397-L408

In that way, all code printers would benefit from it (under the assumption that {} cannot be part of a variable name in any supported language).

**Comment by oscargus** [comment]
This also means that at least the `_print_Symbol` method added in  https://github.com/sympy/sympy/pull/20806 can be removed (actually that method is exactly what the above should be replaced with). Possibly this holds for other printers as well.

**Comment by Anika-Roy** [comment]
is this issue still open?

**Comment by oscargus** [comment]
Sort of. However, there is a PR solving it that is not yet merged. So if
you want to work on something there are probably better issues.

**Comment by gjain-7** [comment]
> actually that method is exactly what the above should be replaced with
replacing the function actually resolves error. 
So is this a solution for this issue or are there any other conditions remaining to be checked upon ?

**Comment by asmeurer** [comment]
Related to this issue https://github.com/sympy/sympy/issues/12463. Ideally this should be handled automatically by the dummify flag.

**Comment by gjain-7** [comment]
After having a look at all related PRs and issues (i.e. pertaining to dummify and lamdify), I have came to the conclusion that we should let `dummify=False` by default, but if the variable name is invalid (`.isidentifier()==False`) then `dummfiy=True` should be overridden.
Am I correct till here ?

Another altogether different thought of mine is that `dummify` option should not be there because we use dummify only if we _have to_. If there is no need for dummification then why would any user want to dummify its variables.
So should it be removed ?

**Comment by asmeurer** [comment]
There might be situations where dummification is needed but we don't correctly identify it. So I would keep the option.

**Comment by gjain-7** [comment]
I think maybe I found the problem, while creating the lambda function there are two things `args` and `expr`.
So in case of `args` , they are getting passed through the `_print_Symbol` of `PythonCodePrinter` in pycode.py
https://github.com/sympy/sympy/blob/0c4cc831ab88b6ba39685540f74d9551544d06e5/sympy/printing/pycode.py#L564-L577
so the `x_{1}` changes to `x_1` and therefore the `_is_safe_ident` is passed in
https://github.com/sympy/sympy/blob/0c4cc831ab88b6ba39685540f74d9551544d06e5/sympy/utilities/lambdify.py#L1189-L1190
and the control doesn't enter `if` block.
However the `expr` (when `modules=sympy`) doesn't gets passed through `_print_Symbol` of `PythonCodePrinter` in pycode.py and as a result it remains `x_{1}` which then raises error on compiling.

On removing the code that removes "{}" from variables, the `_is_safe_ident` check is failed and as a result that argument is dummified.
```diff
 def _print_Symbol(self, expr): 
  
     name = super()._print_Symbol(expr) 
  
     if name in self.reserved_words: 
         if self._settings['error_on_reserved']: 
             msg = ('This expression includes the symbol "{}" which is a ' 
                    'reserved keyword in this language.') 
             raise ValueError(msg.format(name)) 
         return name + self._settings['reserved_word_suffix'] 
-     elif '{' in name:   # Remove curly braces from subscripted variables 
-         return name.replace('{', '').replace('}', '') 
     else: 
         return name 
```

So after the changes, this will be the output of above example
```python
>>> from sympy import *
>>> import inspect
>>> x1, x2 = symbols("x_1 x_{2}")
>>> f1 = lambdify([x1, x2], cos(x1**2 + x2**2))
>>> print(inspect.getsource(f1))
def _lambdifygenerated(x_1, Dummy_22):
    return cos(Dummy_22**2 + x_1**2)

>>> f2 = lambdify([x1, x2], cos(x1**2 + x2**2), modules="sympy")
>>> print(inspect.getsource(f2))
def _lambdifygenerated(x_1, Dummy_23):
    return cos(Dummy_23**2 + x_1**2)
```
which is the desired the output ? Any thoughts ?

**Comment by ThePauliPrinciple** [comment]
Not really related to the issue, but you can print the source code from the docstring:
```python
from sympy import *
import inspect
x1, x2 = symbols("x_1 x_{2}")
f1 = lambdify([x1, x2], cos(x1**2 + x2**2))
print(f1.__doc__)
```

**Comment by oscargus** [comment]
If that change is implemented it will work for lambdify, but I am quite sure that someone will complain about that the PyCode-printer generates invalid Python... See #20762

So I guess that there is no fully "correct" solution, just have to pick between two bad ones.

The main "problem" is that people tend to use "LaTeX-symbols" when they are not really required, as in this case. `x1` and `x2` would be just fine and that will print nicely in LaTeX and generate correct code.

However, at the end of the day I guess that the better option is to enable `lambdify` to work correctly. The Python code generation is sort of more expected.

(I will just reiterate that there should be a section about variable naming somewhere, like in the gotchas. Any year now, I will write one...)

**Comment by oscargus** [comment]
If you go for a PR, make sure that there is a test for it so that it doesn't come back. We should probably also have a clear release note that this is reverted in the `pycode` printing so that it breaks earlier code.

**Comment by gjain-7** [comment]
One thing I wanna ask is that, does #20806 completely fixes #20762 ? I mean are "{}" the only problem while generating a latex expression to a python one ? Any there not any other cases. 
If there aren't then instead of dummifying variables in this case we might just wanna replace symbol with the brace-removed variable name in the expression, in this case `x_{1}` would change to `x_1` in the `expr` and there wouldn't be need for dummification.
i.e. it would be similar to https://github.com/sympy/sympy/blob/0c4cc831ab88b6ba39685540f74d9551544d06e5/sympy/utilities/lambdify.py#L1200, just there would be `s` to replace with instead of `dummy`. I am sure I was able to explain this with clarity

**Comment by asmeurer** [comment]
> If that change is implemented it will work for lambdify, but I am quite sure that someone will complain about that the PyCode-printer generates invalid Python... See https://github.com/sympy/sympy/issues/20762

It would be fine to move the dummify logic into the printers. The lambdify flag would just pass it through to the printer then. Regardless, the default should be changed to be `None`. Although one could maybe debate whether the printers themselves should try to be smart about this. Probably there are people hacking around the printers by putting whole expressions into Symbol names, so we would at least need to make sure the option can be disabled. 

> If there aren't, then instead of dummifying variables in this case we might just wanna replace symbol with the brace-removed variable name in the expression, in this case x_{1} would change to x_1 in the expr and there wouldn't be need for dummification.

There could be any character in the expression. You might be able to remove the non-valid characters with `re.replace`. Even so, it should use Dummy to handle the case when it would create two symbols with the same name. So this would really just be a feature of making the Dummy have a name that more closely corresponds to the original name, rather than just a random one.

**Comment by gjain-7** [comment]
>The lambdify flag would just pass it through to the printer then. Regardless, the default should be changed to be `None`

You mean the `dummify` flag right ? I think even if initialising to `None`, it should always act as if initialised to `False` because that's the default behaviour i.e. 'do nothing'.


> There could be any character in the expression. You might be able to remove the non-valid characters with re.replace. Even so, it should use Dummy to handle the case when it would create two symbols with the same name. So this would really just be a feature of making the Dummy have a name that more closely corresponds to the original name, rather than just a random one.

You mean something like this `x_{1}` ==> `Dummy1-x_1` ?
Also this should be done in both lambdify and code-printer or just the codeprinter ?
Finally, what is the final thing to do ?

**Comment by asmeurer** [comment]
> You mean the dummify flag right ? I think even if initialising to None, it should always act as if initialised to False because that's the default behaviour i.e. 'do nothing'.

No I mean the default should change, as discussed in #12463.

> You mean something like this x_{1} ==> Dummy1-x_1 ?

`Dummy` lets you provide a name, and two `Dummy`s with the same name are not equal.

```
>>> Dummy('x_1')
_x_1
>>> Dummy('x_1') == Dummy('x_1')
False
```

So my suggestion is to just use the stripped name as the argument to Dummy.

> Also this should be done in both lambdify and code-printer or just the codeprinter ?

We should implement it in the code printer so that both can use it. I think the default should change for lambdify, but we can debate whether the default should try to be smart for the code printers. It's also somewhat of a breaking change, so that's another reason to maybe not change the current behavior for the code printers.

**Comment by b4rlw** [comment]
Any progress with the suggested resolutions to this issue?

I'm relatively new to SymPy and I encountered this issue today when trying to parse an SMA function:
```python
latex_expression = r"{\frac{1}{k}}\sum_{i=n-k+1}^{n}p_{i}"
parsed_expression = rebuild(parse_latex(latex_expression))
```
Returns `Sum(p_{i}, (i, -k + n + 1, n))/k`, which of course `lambdify` doesn't like.

**Comment by chandra20500** [comment]
Hi I want to solve this issue please assign it to me.

**Comment by T-vaccari** [comment]
is this issue still open?

**Comment by HAWK1704** [comment]
> I have a complicated expression that needs to be evaluated. If the evaluation fails with numpy, than it switches to sympy. My symbols contains latex syntax.
> 
> This is the simplest reproducible example I could come up with:
> 
> ```python
> from sympy import *
> import inspect
> x1, x2 = symbols("x_{1} x_2")
> 
> f1 = lambdify([x1, x2], cos(x1**2 + x2**2))
> print(inspect.getsource(f1))
> 
> # def _lambdifygenerated(x_1, x_2):
> #     return cos(x_2**2 + x_1**2) 
> ```
> 
> So far so good. Note that `x1` was processed to `x_1`. Now, let's switch to SymPy:
> 
> ```python
> f2 = lambdify([x1, x2], cos(x1**2 + x2**2), modules="sympy")
> print(inspect.getsource(f2))
> ```
> 
> ```
> Traceback (most recent call last):
> 
>   File "/home/davide/Documents/Development/envs/sympy_plot/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3457, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
> 
>   File "/tmp/ipykernel_82217/2465285261.py", line 8, in <module>
>     f2 = lambdify([x1, x2], cos(x1**2 + x2**2), modules="sympy")
> 
>   File "/home/davide/Documents/Development/envs/sympy_plot/lib/python3.9/site-packages/sympy/utilities/lambdify.py", line 900, in lambdify
>     c = compile(funcstr, filename, 'exec')
> 
>   File "<lambdifygenerated-12>", line 2
>     return cos(x_2**2 + x_{1}**2)
>                           ^
> SyntaxError: invalid syntax
> ```
> 
> Note that no processing is applied to `x1`, so curl brackets end up in the expression to be executed.

Instead of passing: 
```python
x1, x2 = symbols("x_{1} x_2")
```

if we pass:
```python
x1, x2 = symbols(f"x_{1} x_2")
```

Then the output is not an error. Then can use it without any problem.
