### ISSUE TITLE
Random doctest failure (sympy.combinatorics.perm_groups.PermutationGroup.schreier_sims_random)

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#23467]
This doctest failure appears randomly on CI

```
____ sympy.combinatorics.perm_groups.PermutationGroup.schreier_sims_random _____
File "/home/runner/work/sympy/sympy/sympy/combinatorics/perm_groups.py", line 3697, in sympy.combinatorics.perm_groups.PermutationGroup.schreier_sims_random
Failed example:
    _verify_bsgs(S, base, strong_gens)
Expected:
    True
Got:
    False
```

**Comment by oscarbenjamin** [comment]
There should be a way to find out the seed for random tests like this. The seed shown from the test runner is useless because it's only the seed at the start of the test suite.

**Comment by asmeurer** [comment]
Maybe we should make the doctester reset the seed before each function.

**Comment by oscarbenjamin** [comment]
This can be reproduced by setting the seed to 74:
```python
from sympy.combinatorics.testutil import _verify_bsgs
from sympy.combinatorics.named_groups import SymmetricGroup
from sympy.core.random import seed

s = 74
seed(s)

S = SymmetricGroup(5)
base, strong_gens = S.schreier_sims_random(consec_succ=5)
print(s, _verify_bsgs(S, base, strong_gens))
```
Unfortunately `bin/doctest` doesn't have a `--seed` argument like `bin/test` does.

**Comment by oscarbenjamin** [comment]
What changed is 1299de41b which removed the doctest skip: https://github.com/sympy/sympy/pull/23083#discussion_r862480383

**Comment by oscarbenjamin** [comment]
I've readded the skip in #23684.

The docstring does say that the test is random and is expected to fail some of the time. It claims to fail with probability at most `2**-consec_succ`. Since `consec_succ` is set to 5 in the doctest we should therefore expect a failure rate of around 3% or less. That's consistent with what I found e.g. when setting the seed to 1 through 100 there were 3 fails.
