### ISSUE TITLE
FiniteSet documentation inconsistent with usage in sympy

### ISSUE THREAD

**Issue by eendebakpt** [sympy/sympy#23585]
The documentation for `FiniteSet` (https://github.com/sympy/sympy/blob/master/sympy/sets/sets.py#L1886) states that the `FiniteSet`: `Represents a finite set of discrete numbers.`.

But in sympy itself the `FiniteSet` is used with non-integer arguments. Statements like `FiniteSet('a', 'd', 'c')` run fine.

**Comment by ritikBhandari** [comment]
Yes if that's the case it should be something like `Represents a finite set of discrete elements of a particular type` ig?

**Comment by oscarbenjamin** [comment]
There isn't really any "particular type". A FiniteSet is just a finite set of SymPy expressions. The set is uniquified through `Eq` bit the elements don't need to have any common type.

**Comment by asmeurer** [comment]
`FiniteSet('a', 'd', 'c')` actually creates a set of symbols because it is using string parsing. To create a set of strings you would need to have a symbolic expression type representing a string (we do have a `Str` class but I think it's only meant for internal use). 

You're right though that set objects shouldn't be restricted to holding just numbers, or even just Expr, although perhaps it would be useful to make sets restricted a single kind of object at a time by default so that you can use `FiniteSet.kind`.
