### ISSUE TITLE
`is_zero` broken for integer/float comparison

### ISSUE THREAD

**Issue by tbennun** [sympy/sympy#23731]
Not sure if this is a recent regression, but comparing an integer-assumption symbol to a Float (or a non-integer to an `Integer`) returns the wrong value:

```python
>>> i = Symbol('x', integer=True)
>>> Eq(i, 1.0)
False
>>> Eq(i, 1)
Eq(x, 1)

>>> ni = Symbol('x', integer=False)
>>> Eq(ni, 1)
False
>>> Eq(ni, 1.0)
Eq(x, 1.0)
```

Upon further inspection, it has to do with the difference being checked in `is_eq`: `_dif.is_zero` returns False, even though that should not always be true.

**Comment by asmeurer** [comment]
`None` is probably the best. Floats can have properties that might break the assumptions, e.g., `x + 1 == x` is possible for Float `x`. That was probably the motivation for making it `False`, but `None` is better since some floats do behave like integers in some contexts.

**Comment by tbennun** [comment]
Maybe it's unrelated, but after some playing around I found that even an arbitrary symbol with integer=False is assumed as nonzero:
```python
>>> sp.Symbol('x', integer=False).is_zero
False
```

Is that intended?

**Comment by oscarbenjamin** [comment]
> an arbitrary symbol with integer=False is assumed as nonzero

Zero is an integer so if `integer=False` then `zero=False`.

**Comment by tbennun** [comment]
Alright, makes sense. This should not naturally happen in our usage because integer is never explicitly set to False, only None or True.

**Comment by asmeurer** [comment]
I tried setting Float.is_integer to None at https://github.com/sympy/sympy/pull/25856 to see what happens. 

If it breaks too many things, then we should try to be more precise, specifically, return True when the Float exactly represents an integer (like 3.0), False when it has a nonzero fractional part, and None when it is too large to represent the integer exactly (like 1e20). I do worry that strange things could happen around the boundaries of exactly representable integers if we do this, though.

**Comment by smichr** [comment]
`is_integer` was intended to be the symbolic equivalent of `is_Integer`. With the improved behavior of `==` (that discriminates between 1 and 1.0 and reports them as unequal since they are not structurally the same) we are now faced with decisions like the one of this issue: should `Eq(1, 1.0)` be True? I would argue that we should *not* allow this to be True and cite *import this*, line 2:

> Explicit is better than implicit.

Conceptually, Float is used as an approximation of Reals in a given range whereas Rational represents an exact value that is real. If one wishes to treat Float as Rational for some purpose, let them explicitly do so and replace `n` with `int(n)` if `int_valued(n)` is True or replace `n` with `Rational(n)` if `(r:=Float(1.125)%1) and r._mpf_[1]==1` (i.e. if the number has a fractional part that is in the form 1/2**x).

A fix for the current behavior of `Equality` is to replace any Floats with a Dummy that has `rational=True` assumptions.

```
>>> i = var('i',integer=1)
>>> Eq(i/2, S.Half)
Eq(i/2, 1/2) 
>>> Eq(i/2, .5)
Eq(i/2, 0.5)
>>> Eq(i, 1.0)
Eq(i, 1.0)

>>> ni = var('ni',integer=0)
>>> Eq(ni, 1.0)
Eq(ni, 1.0)
>>> Eq(ni, 1)
False
```

diff --git a/sympy/core/relational.py b/sympy/core/relational.py
index cce1dfe76c..ae2233c611 100644
--- a/sympy/core/relational.py
+++ b/sympy/core/relational.py
@@ -4,7 +4,9 @@
 from .sorting import ordered
 from .evalf import EvalfMixin
 from .function import AppliedUndef
+from .numbers import Float
 from .singleton import S
+from .symbol import Dummy
 from .sympify import _sympify, SympifyError
 from .parameters import global_parameters
 from .logic import fuzzy_bool, fuzzy_xor, fuzzy_and, fuzzy_not
@@ -619,7 +621,18 @@ def __new__(cls, lhs, rhs, **options):
         lhs = _sympify(lhs)
         rhs = _sympify(rhs)
         if evaluate:
-            val = is_eq(lhs, rhs)
+            # while 1 != 1.0, Eq(1, 1.0) should not be True
+            # but is_eq will treat them as equal.
+            # So, for purpose of evaluation, replace Floats
+            # with rational symbols before evaluation
+            reps = {}
+            for f in lhs.atoms(Float)|rhs.atoms(Float):
+                if f not in reps:
+                    reps[f] = Dummy(rational=True)
+            val = is_eq(lhs.xreplace(reps), rhs.xreplace(reps))
             if val is None:
                 return cls(lhs, rhs, evaluate=False)
             else:

**Comment by tbennun** [comment]
Thank you for merging #25875 @smichr. How does the None return value change the original expressions I posted?
