### ISSUE TITLE
sympy can't handle symbolic Sum of JzKets

### ISSUE THREAD

**Issue by James471** [sympy/sympy#23820]
I tried to create a linear combination of sympy.physics.quantum.spin.JzKets using
`state = sm.Sum((2**m)*qt.spin.JzKet(J, m), (m, -J, J))` and tried to find it's norm using
`(sympy.physics.quantum.qapply(qt.Dagger(state)*state).doit())`
The output is 
![image](https://user-images.githubusercontent.com/56861963/180604904-8909308f-9d22-4a62-8e56-ebaeb8bef7fe.png)
which is clearly incorrect. Cleary qapply() doesn't understand a Sum object.

**Comment by oscarbenjamin** [comment]
Can you show a complete code example to reproduce this including imports? What should the correct answer be?

It might be a bug in Sum rather than qapply.

The quantum module is currently unmaintained. Feel free to submit a PR to fix this.

**Comment by kushagrasachan** [comment]
Following are the imports I used to reproduce this issue:

```py
import sympy as sp
from sympy.abc import k,m,J

import sympy.physics.quantum as qt

import sympy.concrete.summations as sm
```

The OP's statement `state = sm.Sum((2**m)*qt.spin.JzKet(J, m), (m, -J, J))` produces the output to be:
<img width="500" alt="Screenshot 2023-05-15 at 6 47 43 PM" src="https://github.com/sympy/sympy/assets/68713597/ee37d2cf-3133-43b1-9fb3-a34f3d6f1fed">
which, while "looks" correct to our expectation, *is not*, as is indicated by:
<img width="209" alt="Screenshot 2023-05-15 at 6 51 36 PM" src="https://github.com/sympy/sympy/assets/68713597/eddca325-62b1-42d2-be90-45268e7306c4">

This shows that the object is not behaving as a quantum state, but instead the $\sum_m 2^m$ chunk of the expression is being interpreted by sympy as a separate, geometric summation. The kets $|J,m\rangle$ ought to be part of the summation as well.

**Hence, I do believe that it's an inadequacy of Sum, as suggested—an incompatibility of Sum and Quantum objects' implementations.**

Above,`state` is a `<class 'sympy.concrete.summations.Sum'>` object, while one would expect a correct implementation to return an object of perhaps some subclass of `<class 'sympy.physics.quantum.state'>`.

These seem to be the reasons (or more) for the OP's issue, hereby seen reproduced with a slight deviation (suspected to be from some update ever since):
<img width="625" alt="Screenshot 2023-05-15 at 7 37 48 PM" src="https://github.com/sympy/sympy/assets/68713597/cd30a2cd-3077-4558-9ebe-2c5511be56f2">

Attempting to calculate OP's desired norm expression by alternatively using the `innerproduct` method, hints that we should perhaps somehow try to implement returning a `sympy.physics.quantum.state.KetBase` object.
<img width="1188" alt="Screenshot 2023-05-15 at 8 03 50 PM" src="https://github.com/sympy/sympy/assets/68713597/bdd5e1f2-8f02-420f-9c83-114aa46b1dfd">

**Comment by travlight** [comment]
I am wondering if this issue can be solved, because I also confront the same problem when I want to define a thermal state in Fock basis.
![image](https://github.com/sympy/sympy/assets/158588356/81aae0be-ed8f-43ba-a2ad-2d4c92dc17e6)
The problem here is that the summation function cannot recognize the dummy index inside the braket notation like sum over k for  |k><k>.
