### ISSUE TITLE
The value of bernoulli(1)

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#23866]
There are two conventions for the Bernoulli numbers, specifically $B_1$ can be defined to be 1/2 or -1/2 (see https://en.wikipedia.org/wiki/Bernoulli_number), depending on whether it is defined using the exponential generating function $\frac{x}{e^x-1}$ or $\frac{xe^x}{e^x - 1}$. SymPy uses the -1/2 definition.

Donald Knuth has recently written that he's been convinced that the -1/2 definition is wrong and historically inaccurate, and he updated *Concrete Mathematics* accordingly (https://www-cs-faculty.stanford.edu/~knuth/news22.html):

> The sequence of Bernoulli numbers plays a prominent role in mathematics, especially in connection with asymptotic expansions related to Euler's summation formula. When I learned about this fascinating sequence, during my undergraduate days, I was taught that $B_1$ is equal to minus one-half. So I duly taught the same to my students, and went on to write books that explained what I thought Bernoulli and Euler had done.
>
> But last year I took a close look at Peter Luschny's [Bernoulli manifesto](http://luschny.de/math/zeta/The-Bernoulli-Manifesto.html), where he gives more than a dozen good reasons why the value of $B_1$ should really be plus one-half. He explains that some mathematicians of the early 20th century had unilaterally changed the conventions, because some of their formulas came out a bit nicer when the negative value was used. It was their well-intentioned but ultimately poor choice that had led to what I'd been taught in the 1950s.
>
> Luschny's webpage cites, for example, recent treatments of the subject by leading mathematicians such as Terence Tao. And his most compelling argument, from my personal perspective, is the way he unveils the early publications: I learned from him that my own presentation of the story, in [The Art of Computer Programming](https://www-cs-faculty.stanford.edu/~knuth/taocp.html) and much more extensively in [Concrete Mathematics](https://www-cs-faculty.stanford.edu/~knuth/gkp.html), was a violation of history! I had put words and thoughts into Bernoulli and Euler's minds that were not theirs at all. This hurt, because I've always tried to present the evolution of ideas faithfully; in this case I'd fooled myself, by trying to conform what they wrote to what I'd learned.
>
> By now, hundreds of books that use the “minus-one-half” convention have unfortunately been written. Even worse, all the major software systems for symbolic mathematics have that 20th-century aberration deeply embedded. Yet Luschny convinced me that we have all been wrong, and that it's high time to change back to the correct definition before the situation gets even worse.
>
> Therefore I changed the definition of $B_1$ in all printings of The Art of Computer Programming during the latter half of 2021. And the new (34th) printing of Concrete Mathematics, released in January 2022, contains the much more extensive changes that are needed to tell a more comprehensive story.

Here is Luschny's page he cites http://luschny.de/math/zeta/The-Bernoulli-Manifesto.html.

So maybe we should reconsider SymPy's definition of `bernoulli`. At the very least, I think there should be a way to specify which convention is used, $B^+_n$ or $B^-_n$.

As an aside, [the docs for `bernoulli`](https://docs.sympy.org/dev/modules/functions/combinatorial.html#sympy.functions.combinatorial.numbers.bernoulli) state that the defining recurrence relation is $$0 = \sum_{k=0}^n \binom{n+1}{k} B_k$$ but for the -1/2 definition it should actually be $$\delta_{m,0} = \sum_{k=0}^n \binom{n+1}{k} B_k$$ (for the +1/2 definition it's $$n + 1 = \sum_{k=0}^n \binom{n+1}{k} B_k,$$ see https://en.wikipedia.org/wiki/Bernoulli_number#Recursive_definition).

**Comment by Parcly-Taxel** [comment]
This is the eternal, unquestionable truth:
>For any software, defining $B_1=-\frac12$ is  a **critical** bug.

Therefore, rather than letting the user choose, we should simply fix $B_1=+\frac12$ in the code and leave the user to reconcile this **only correct definition** with other incorrect formulae in the literature (that are incorrect solely because they assume $B_1=-\frac12$).

The relevant line of code that defines $B_1$ in SymPy is https://github.com/sympy/sympy/blob/77f1d79c705da5e9b3dee456a14b1b4e92dd620c/sympy/functions/combinatorial/numbers.py#L492-L499

All that's needed on the code side is to remove the minus sign in line 497.

----

For the documentation I suggest using as the primary definition Luschny's definition of Bernoulli numbers as a sequence extended by an analytic function à la factorials and the gamma function:

$$B(n)=\begin{cases}-n\zeta(1-n)&n>0\\
1&n=0\end{cases}$$

The secondary definition (and the one I personally like the most) will then be "the sequence with generating function $\frac t{1-e^{-t}}$".

----

When $B_1$ has been corrected please tell Luschny about it so he can boast about it.

**Comment by oscarbenjamin** [comment]
> Therefore, rather than letting the user choose, we should simply fix B1=+12 in the code and leave the user to reconcile this **only correct definition** with other incorrect formulae in the literature (that are incorrect solely because they assume B1=−12).

I don't necessarily disagree with this suggestion but it's important to be clear here that there is no "correct" or "incorrect" in this situation. There are two possible conventional choices for the value of B1. SymPy currently uses one convention but could be changed to use another.

However we don't know what people are already using SymPy's `bernoulli` function for. The current behaviour of `bernoulli` is documented and is implemented correctly per the documentation.

The document linked above suggests that it would have been better to choose the other convention in the first place. That is a different question from what to do now given that all previous releases of SymPy have not used that convention.

**Comment by Parcly-Taxel** [comment]
>It's important to be clear here that there is no "correct" or "incorrect" in this situation. There are two possible conventional choices for the value of $B_1$.

Totally false. Luschny's manifesto states that **a good definition supersedes all conventions**:
>_Why is there still no canonical representation of the Bernoulli numbers_ even though they are so central as Mazur writes. It is this question which should really worry us because it points to a _theoretical deficit_, a lack of understanding.
>
>It is my belief that this can be overcome. Consider how Euler proceeded in the similar case of the factorial numbers: He has introduced a _definition_, that of the gamma function, which to this day is the canonical way to interpolate the factorial numbers _because it has more advantages than possible alternative definitions_.
>
>**This approach characterizes progress at the highest mathematical level, which is the level of definitions. If a definition is successful it makes conventions superfluous.** This objective can be achieved here as well — by introducing the Bernoulli function. Below we will give an analytic definition independent from the zeta function. This will be our _substantive_ definition, as we called it above, in contrast to the controversial formal definitions via generating functions. 

The definition of the Bernoulli function in Luschny's manifesto is a good definition, as is the gamma function. Once such definition has been made, we can say which conventions are correct or incorrect; here the definition proves that $B_1=-\frac12$ as SymPy currently has it **is incorrect**.

**Comment by oscarbenjamin** [comment]
> The definition of the Bernoulli function in Luschny's manifesto is a good definition,

I don't disagree but making overstated simplistic statements about things being true, false, correct or incorrect (which Luschny rightly refrains from) does not help to make your case. It also does not allow us to simply sidestep the issue of compatibility with previous versions of SymPy, with other CASs, with libraries that SymPy depends on and with much of the existing mathematical literature e.g.:
https://dlmf.nist.gov/24.2

As I said before I don't necessarily disagree with making a backwards incompatible change here but there needs to be some consideration of what the impact of that is which means thinking about how anyone might already be using the existing `bernoulli` function. Similarly the need to maintain compatibility with other systems and sources that use $B_{-}$ suggests that at least SymPy should provide a `bernoulli_minus` function even if `bernoulli` itself is changed.

On the question of dependencies consider that SymPy uses libraries such as mpmath and scipy for numerical evaluation which both use $B_{-}$ e.g.:
```python
In [14]: scipy.special.bernoulli(10)
Out[14]: 
array([ 1.        , -0.5       ,  0.16666667,  0.        , -0.03333333,
        0.        ,  0.02380952,  0.        , -0.03333333,  0.        ,
        0.07575758])

In [16]: mpmath.bernoulli(1)
Out[16]: mpf('-0.5')
```
Adopting the definition suggested by Luschny makes it possible to extend the `bernoulli` function to non-integer and non-real values which are currently not supported by SymPy's `bernoulli` function. That would imply also adding support for `evalf` which cannot directly use mpmath's `bernoulli` function since that uses $B_{-}$ and computes only integer values after flooring its argument.

Also any existing usage of `bernoulli` within SymPy's own codebase needs to be reviewed (`git grep bernoulli`). We need to check that `evalf`, `lambdify` (with mpmath, scipy, ...) etc are consistent with SymPy's symbolic evaluation. Looks like lambdify with scipy is just broken (it returns a sequence rather than a number) which I guess makes it easier to change:
```python
In [6]: lambdify(x, bernoulli(x), 'scipy')(1)
Out[6]: array([ 1. , -0.5])

In [7]: lambdify(x, bernoulli(x), 'mpmath')(1)
Out[7]: mpf('-0.5')
```

**Comment by asmeurer** [comment]
I didn't think about mpmath. We might want to discuss changing it there too if we are going to change SymPy, but either way we need to account for it being different.

**Comment by Parcly-Taxel** [comment]
https://github.com/fredrik-johansson/mpmath/pull/639, once merged, will set $B_1=+\frac12$ in that package, allowing us to not (really) worry about compatibility with mpmath. We might need to ping @fredrik-johansson and tell about this project of ours though.

**Comment by oscarbenjamin** [comment]
> allowing us to not (really) worry about compatibility with mpmath

We don't know when that change would be released so we do still need to worry about compatibility with mpmath. Also probably we should for evalf use Lushcny's formula to make `bernoulli` a function defined on the complex numbers.

**Comment by Parcly-Taxel** [comment]
> Also probably we should for evalf use Lushcny's formula to make `bernoulli` a function defined on the complex numbers.

Does that mean allowing non-nonnegative-integer input to `bernoulli()` itself as opposed to merely replacing it with $-s\zeta(1-s)$ for `evalf()`'s purposes?

This Bernoulli function $B(s)$ is also not quite wholesale replaceable by $-s\zeta(1-s)$. We know well that $\zeta$ has a pole at argument 1 ($s=0$); as Luschny notes, multiplying by $-s$ cancels the pole and makes $B(s)$ entire with $B(0)=1$. The same applies for what Luschny calls the generalised Bernoulli function: $B(s,a)=-s\zeta(1-s,a)$ with $B(0,a)=1$ for any $a$.

**Comment by oscarbenjamin** [comment]
> Does that mean allowing non-nonnegative-integer input to `bernoulli()` itself as opposed to merely replacing it with −sζ(1−s) _for `evalf()`'s purposes only_?

Yes, I think so. Luschny's definition makes `B` a holomorphic function if I understand correctly. If we're adopting that definition then I think `bernoulli` should allow any complex number as input. Since mpmath does not currently implement that complex function SymPy will need some code to make evalf work and handle the `s=0` case.

**Comment by Parcly-Taxel** [comment]
>Luschny's definition makes `B` a holomorphic function if I understand correctly. If we're adopting that definition then I think `bernoulli` should allow any complex number as input.

There I run into a problem. If I define the most general case of the Bernoulli function as (essentially) $-n\zeta(1-n,a)$ I get a circular import error since `zeta` relies on `bernoulli` to evaluate for certain arguments. The most logical way to solve this would be to move the entire Bernoulli function to the same file `zeta` is in.

Should I proceed with that?

**Comment by oscarbenjamin** [comment]
Maybe there should be a non-symbolic function in ntheory for calculating the numbers in the bernoulli sequence. Then it could be used by both zeta and also bernoulli.

If the zeta function currently uses bernoulli then it should be checked that it still gives correct results after changing the convention used for bernoulli.

**Comment by Parcly-Taxel** [comment]
> Maybe there should be a non-symbolic function in ntheory for calculating the numbers in the bernoulli sequence. Then it could be used by both zeta and also bernoulli.

[I eventually decided on having a new `bernoulli_entire()` function in the same file as `zeta()`.](https://github.com/sympy/sympy/pull/23926/commits/cb5fc97680d6bb77dd6620443f5634f3a380de94) Something similar happens with the factorial function and the gamma function, so it should be fine.

> If the zeta function currently uses bernoulli then it should be checked that it still gives correct results after changing the convention used for bernoulli.

Yes, it still gives correct results. Indeed I've made it even more correct by aligning its behaviour with Luschny's Intro to $\operatorname B(s,a)$:

* $\zeta(s,a)$ for $a$ a nonpositive integer is undefined unless $s$ is a nonpositive integer itself.
* $\operatorname B(s,a)$ for $a$ a nonpositive integer is undefined unless $s$ is a nonnegative integer.

**Comment by Parcly-Taxel** [comment]
**Done.** All that remains is to merge my pull request into SymPy 1.11.

**Comment by Parcly-Taxel** [comment]
@oscarbenjamin #23973

**Comment by fchapoton** [comment]
This is a **very wrong move** and should be undone. You have been tricked to do that by people with no authority whatsoever. This is not good to try changing the stable convention used by the large majority of mathematical papers.

**Comment by oscarbenjamin** [comment]
I don't think there is any such thing as people with "authority" in cases like this. It's not uncommon to find different sources using different conventions for defining things e.g. conflicts between DLMF and Abromowitz and Stegun etc. The question is what convention or definition is most useful.

Generally SymPy works with functions defined over complex valued arguments where possible. Choosing $B_1=\frac{1}{2}$ permits a natural generalisation of the Bernoulli numbers to a function over the reals and complex numbers e.g.:
https://arxiv.org/pdf/math/9812143.pdf

What advantage does choosing $B_1=-\frac{1}{2}$ have?

**Comment by edgarcosta** [comment]
As suggested in #23984, I moved the discussion here.

First of all, here are the other places where the same discussion is happening:
https://github.com/wbhart/flint2/pull/1179
https://github.com/fredrik-johansson/mpmath/pull/639
https://groups.google.com/g/sage-devel/c/G4sbKoibXK4
https://trac.sagemath.org/ticket/34521


I agree with @oscarbenjamin, this is not about which definition is right or wrong, they are mathematical equivalent.
If you were just now adding Bernoulli numbers, it would be irrelevant which one you pick.
However, it seems you made a choice more than a decade ago that B_1 = -1/2, and given that you are a popular library, I would avoid changing such a convention without some careful thought.
As it implies that not only you must change a bunch of code, but every code that depends on the previous convention must also change, and that might be a lot of work for a lot of people.

In my opinion, the benefit of improving some definitions does not outweigh the cost of the change.

**Comment by oscarbenjamin** [comment]
> As it implies that not only you must change a bunch of code, but every code that depends on the previous convention must also change, and that might be a lot of work for a lot of people.

Possibly. I'm finding it hard to find significant places where the actual value of `bernoulli(1)` really matters for anything. I suspect that the fact that it has been given arguably the "wrong" value for so long is precisely because in most situations it just doesn't matter.
