### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'ImmutableDenseNDimArray' and 'Symbol'

### ISSUE THREAD

**Issue by bhavini-jeloka** [sympy/sympy#23876]
I am trying to add two sympy (version 1.10.1) matrices using the following code:

```
AQ = Matrix(A)*Q
BR = Matrix(B)*R

print(type(AQ), type(BR))

AQBR = AQ + BR
```

Here A (2 x 2) and B (2 x 1) are numpy arrays with floating point numbers (which are converted to sympy matrices using the Matrix function) whereas Q and R are matrices defined using sympy symbols.

```
variables = symbols('q1 q2 q3 r1 r2')
q1, q2, q3, r1, r2 = variables     
Q = Matrix([[q1, q2], [q2, q3]])
R = Matrix([[r1, r2]])
```

I have checked the type of AQ and BR and both are objects of <class 'sympy.matrices.dense.MutableDenseMatrix'>. Both matrices are 2 x 2. Yet I am getting the following error:

TypeError: unsupported operand type(s) for +: 'ImmutableDenseNDimArray' and 'Symbol'

**Comment by oscarbenjamin** [comment]
There is probably a mistake in your code somewhere but you haven't shown complete code. When I run the code above I don't see the error you report. Most likely you've mixed up your variables somehow.

I'm going to close this because GitHub issues are not for asking for help with using SymPy. Please use the mailing list or stackoverflow for that.
