### ISSUE TITLE
Modulo infinitiy behaviour

### ISSUE THREAD

**Issue by bjodah** [sympy/sympy#23911]
What should the following return?
```python
>>> Mod(Symbol('x', real=True, finite=True), oo)
nan
```
I would have expected to get `x` back, but perhaps I'm missing some precondition, but currently this returns sympy's `NaN`.

**Comment by oscarbenjamin** [comment]
This doesn't seem very well defined to me. The general definition of modulo is through Euclidean division. With dividend $x$ and divisor $d$ we have $$x = q\times d + r$$ where $q$ is the quotient and $r$ the remainder and $0 \le r < d$. Here you are looking for $q$, $r$ so that $$x = q\times \infty + r$$ but the product $q\times\infty$ is not going to be well defined for any value of $q$.

**Comment by bjodah** [comment]
I see, that's a good point. Closing this.
Thanks!
