### ISSUE TITLE
`solve_undetermined_coeffs` does not respect `dict=True`.

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#23927]
This is a regression in master since SymPy 1.10.1 (due to #23877).

The `solve_determined_coeffs` function no longer respects the `dict=True` option.

With 1.10.1:
```python
In [1]: a, b, c = symbols('a, b, c')

In [2]: solve_undetermined_coeffs(a*x + b-1, [a, b], [x])
Out[2]: {a: 0, b: 1}

In [3]: solve_undetermined_coeffs(a*x + b-1, [a, b], [x], dict=True)
Out[3]: [{a: 0, b: 1}]
```
With master:
```python
In [1]: a, b, c = symbols('a, b, c')

In [2]: solve_undetermined_coeffs(a*x + b-1, [a, b], [x])
Out[2]: {a: 0, b: 1}

In [3]: solve_undetermined_coeffs(a*x + b-1, [a, b], [x], dict=True)
Out[3]: {a: 0, b: 1}   <---- should be a list of dicts
```

**Comment by oscarbenjamin** [comment]
CC @smichr

**Comment by smichr** [comment]
This can be considered a bug fix since the documentation says that it returns a dictionary (not a list with a dictionary). Getting a list back is something that was a byproduct of adding that option to solve (and passing all args to solve). If it is to be a free standing function, one shouldn't have to know the flags for solve to control the function. 

It currently/recently returned tuples, too. That is another "accidental design issue" that went against the docstring that said it was for solving a linear system of equations for coefficients on common generators.
```python
>>> solve_undetermined_coeffs(a**2*x-4*x, [a],x)
[(-2,), (2,)]
```
This was the purpose of #23925 (beyond making it multivariable capable). Using solve to get more than a single solution is no longer possible.

So the current target it to follow the docstring: single dict or None (or [] if there is no solution). And I keep running into recurr.py code that needs it to return [] (though it might be better to have it return {} instead).

**Comment by oscarbenjamin** [comment]
It's not possible for `solve_undetermined_coeffs` to always return a dict because there can be multiple solutions to the system of equations. It seems that the changes you have made prevent multiple solutions from being returned at all.

With SymPy 1.10.1:
```python
In [1]: a, b, x = symbols('a, b, x')

In [2]: solve_undetermined_coeffs((a**2 - 1)*x - b, [a, b],x)
Out[2]: [(-1, 0), (1, 0)]

In [3]: solve_undetermined_coeffs((a**2 - 1)*x - b, [a, b], x, dict=True)
Out[3]: [{a: -1, b: 0}, {a: 1, b: 0}]
```
With master after #23877:
```python
In [1]: a, b, x = symbols('a, b, x')

In [2]: solve_undetermined_coeffs((a**2 - 1)*x - b, [a, b],x)

In [3]: solve_undetermined_coeffs((a**2 - 1)*x - b, [a, b], x, dict=True)
```
That's another regression from #23877.

**Comment by smichr** [comment]
Again, this is an *accidental* feature not a *design* feature for this function. This was not the intention for this function as evidenced by the docstring claiming that "a dictionary is returned" -- in `solve` vernacular, that means the solution of a system of linear equations. 

Although I think this is a case of YAGNI, we could add a function -- and I had this at one point -- that extracts the coefficients off of common terms to assemble a system of equations to solve. And then `solve` can be called with whatever flags are of interest. But is there really a use case for this? I can't imagine someone trying to match coefficients in a way other than one that gives a single solution. The alternate form of a parabola in terms of h,p,k is a good example of a nonlinear coefficient system with a single solution:

https://github.com/sympy/sympy/blob/b1f35f8daf5efa9f801f905cf1037000d69b0278/sympy/solvers/tests/test_solvers.py#L157-L160

**Comment by oscarbenjamin** [comment]
> Again, this is an _accidental_ feature not a _design_ feature for this function. This was not the intention for this function as evidenced by the docstring claiming that "a dictionary is returned" -- in `solve` vernacular, that means the solution of a system of linear equations.

I'm not sure that anyone apart from you understands this "vernacular".

> Although I think this is a case of YAGNI, we could add a function -- and I had this at one point -- that extracts the coefficients off of common terms to assemble a system of equations to solve. And then this system can be passed to `solve` with any flags of interest.

This is basically what `solve_undetermined_coeffs` already did before the changes in #23877.

> I can't imagine someone trying to match coefficients in a way other than one that gives a single solution

It's not hard to imagine coefficient matching that leads to nonlinear equations:
```python
In [50]: A, B, r, phi = symbols('A, B, r, phi')

In [51]: eq = Eq(A*sin(t) + B*cos(t), r*sin(t - phi))

In [52]: eq
Out[52]: A⋅sin(t) + B⋅cos(t) = -r⋅sin(φ - t)

In [53]: eq.rewrite(Add).expand(trig=True).collect([cos(t), sin(t)])
Out[53]: (A - r⋅cos(φ))⋅sin(t) + (B + r⋅sin(φ))⋅cos(t)

In [54]: len(solve([A - r*cos(phi), B + r*sin(phi)], [r, phi]))
Out[53]: 2
```

**Comment by smichr** [comment]
The docstring clearly states that a single dictionary is returned. This implies that there is a single solution. The docstring does not state that the system must be linear in parameters. And as I much as I remember from differential equations, this is the normal sense of "undetermined coefficients": the coefficients form a linear set of equations to be solved to determine those coefficients.

The example you have given is far afield from the expectation of `solve_undetermined_coeffs` as evidenced by the code that is there (that does the collection of the coefficients). I suspect it would be more prudent to make a new function to handle such requests rather than to make `solve_undetermined_coeffs` try to handle them. I don't think it is a compelling reason to allow an accidental feature to continue to exist for this function.
