### ISSUE TITLE
Quantum Operators * their inverse become scalar 1 instead of IdentityOperator

### ISSUE THREAD

**Issue by Costor** [sympy/sympy#24153]
### Situation ###
Operator classes like `Matrix` or `MatrixSymbol` represent scalar results as multiple of their respective Identity operator, i.e. operator * operator -> operator (except for 0):
```
from sympy.matrices import *
M = MatrixSymbol('M', 3, 3)
print (M * M**-1, M * M.inv(), type(pow(M, 0)) 
#->  Identity(3)  Identity(3)  sympy.matrices.expressions.special.Identity
```
However operators from the `sympy.physics.quantum Operator` class return scalars, though they are also linear operators:
```
from sympy.physics.quantum import *
A = Operator('A')
print(A * A**-1, A * A.inv(),  type(pow(A, 0)))
#->  1   1    <class 'sympy.core.numbers.One'>
```
### Assessment ###
Mathematically speaking this is not relevant. 
However it is unusual - even in mathematical notation one typically writes A * A**-1 = I  - and it is inconsistent within SymPy: 
Since SymPy typically has `Identity.is_commutative==False`,  `args_cnc` keeps the Identity in the nc_part, so code can rely on that the product of two operators is again an operator type (except for 0). With quantum.Operators all expression handling code that directly or indirectly relies on args_cnc behaves differently, which is inconvenient. 
As another example today's output of _TensorProduct(A * A**-1, B * B.inv())_ -> _1 x 1_ is much less intuitive than the expected  _I x I_  .  
Furthermore: If it was decided that the result should be represented as _I x I_, the term _1 x 1_ would be reserved for _really_ scalar results like  _(<1| x <0| ) x (|1> x |0>) = 1 x 1 = 1_ .

### Proposition for Fix ###
Ensuring `pow(A, 0)==IdentityOperator()` gives consistent behaviour with mathematical usances and other Sympy packages.
I have checked this can be implemented with minimal effort by adding a `__pow__()` method to the `quantum.Operator`  class that just adds handling of the `exponent==0` case and can provide a PR if requested.

**Comment by oscarbenjamin** [comment]
> by adding a `__pow__()` method to the `quantum.Operator` class

It's better not to embed logic like this in `__pow__` because then it wouldn't be handled by things like `subs` etc e.g. `Pow(x, 2).subs(x, y)` will not call `y.__pow__`.

**Comment by Costor** [comment]
I'm not sure I see your point: 

As today I can see in the code that `Pow(x,2) -> Pow.__new(x, 2)` tries really hard to evaluate `x**2`, even might call `x._eval_power(2)`. If it happens to evalute x**2 to something it will do so, and if that something does not longer contain the symbol x, subs(x, y) won't do anything. 

As an example take the operator X(0). It satisfies X(0)*X(0)==IdentityOperator(0) resp. 1.
`Pow(X(0), 2)` actually finds that and returns 1:
```
from sympy.physics.quantum.gate import X
x, y = symbols("x y")
Pow(x, 2).subs(x,y) # -> Pow(y,2) as expected
x = X(0)
Pow(x, 2), Pow(x, 2).subs(x,y) # -> 1  1  no action of subs(x,y)
```
My proposed change would only affect exponents == 0, and in the last line the output would be `IdentityOperator()` instead of 1. The change intended is more or less cosmetic.

Where should I put the fix instead so that `pow(Operator, 0) == IdentityOperator() ` ?

**Comment by oscarbenjamin** [comment]
> Where should I put the fix instead so that `pow(Operator, 0) == IdentityOperator() ` ?

I'm not sure exactly because I don't know the quantum code but things like this should never be in `__pow__` because that's just a special method for dispatching the `**` operator and has no effect on symbolic powers.

**Comment by Costor** [comment]
Ok, I see... though I see classes that even do an overload of __mul__  (e.g. Operator, IdentityOperator). But there are ways to stay away of __pow__, see below. 

However I have found that no perfect solution is possible: This is because Pow(almost_anything, 0) returns S.One! This is true for MatrixSymbol, Operator and almost anything else, as Pow does a quick check on `exponent==0` and if yes, return S.One. 

Actually this is no correct behaviour: Pow should return the multiplicative neutral element from the ring where the base is from, instead just S.One. But I don't expect that Pow will be changed here; even the authors of Matrix accept the idiosyncrasy of `Pow(M, 0) == 1` and `M*M.inv() = Identity`.  Fun fact: In line with MatAdd, MatMul there is MatPow - but that returns `MatPow(M, 0) -> MatPow(M, 0)` unevaluated.

So I propose to work along the same lines: An approach would be to introduce Operator._pow()  which overloads Expr._pow(). This is in the call chain of Expr.__pow__(), so should work. For non-null exponents it's either Operator._pow() and/or to create Operator._eval_power() overloading Expr._eval_power(), since Self._eval_power(exponent) is called by the Pow constructor.  

So that should make Operator behave pretty much the same as Matrix in that respect.

**Comment by oscarbenjamin** [comment]
> Fun fact: In line with MatAdd, MatMul there is MatPow - but that returns `MatPow(M, 0) -> MatPow(M, 0)` unevaluated.

That's an intentional feature of the matrix expression classes. If created directly then they only evaluate with doit:
```python
In [21]: M = Matrix([[1, 2], [3, 4]])

In [22]: M**0
Out[22]: 
⎡1  0⎤
⎢    ⎥
⎣0  1⎦

In [23]: MatPow(M, 0)
Out[23]: 
      0
⎡1  2⎤ 
⎢    ⎥ 
⎣3  4⎦ 

In [24]: _.doit()
Out[24]: 
⎡1  0⎤
⎢    ⎥
⎣0  1⎦
```

> Pow should return the multiplicative neutral element from the ring where the base is from

There isn't always a ring associated with every expression. Ideally `kind` should be usable for this though.

> Ok, I see... though I see classes that even do an overload of **mul** (e.g. Operator, IdentityOperator).

There are some classes that do that but it's misguided because it only works with `a*b` rather than `Mul(a, b)`. I think this is basically how you end up needing `qapply`.

**Comment by Costor** [comment]
Ok, the Matrix class shows consistent behavior, also with symbols:
```
n = symbols("n")
M = MatrixSymbol('M', n, n)
MatMul(M, M.inv())  #-> M * M ** (-1)  unevaluated
_.doit() # -> Identity  (not 1)
MatPow(M, 0) # -> MatPow(M, 0) unevaluated
_.doit() # -> Identity (not 1)
#However the native functions:
Mul(M, M.inv()) # -> Identity (not 1)
Pow(M, 0) # -> 1  (not Identity)
```
So I'll try to make quantum Operator behave similar but without modifying Pow or Mul of course.

**Comment by rrodenbusch** [comment]
I have a proposal for how to handle the multiplicative identities which are not singletons (S.Zero).  I have been working with extending the pauli Sigma operators to add a SigmaI IdentityOperator so that I can model rotation gates decomposed to the pauli sigmas. Thus far a nice pythonic solution appears to be:

1. Override the core Add, Mul and Pow classes to enable the capture of any cases which differ from core processing. See:
https://github.com/rrodenbusch/sympy/blob/_add-pauli-SigmaI/sympy/physics/quantum/core.py
2. Inherit the new classes into the base operator class (in this case, SigmaOpBase) and implement the appropriate method (__pow__) to process these cases. See: https://github.com/rrodenbusch/sympy/blob/_add-pauli-SigmaI/sympy/physics/quantum/pauli.py   
3. Create the multiplicative identity if it doesn't exist (SigmaI() did not exist)

I estimate I am about 80% complete in my test cases and this addresses most of the comments here (except TensorProduct maintaining the hermitian attribute, which is a different issue).  See: https://github.com/rrodenbusch/sympy/blob/_add-pauli-SigmaI/sympy/physics/quantum/tests/test_pauli.py
This passes all regression tests with the exception of:
    assert qsimplify_pauli(sx * sx) == 1
    assert qsimplify_pauli(sy * sy) == 1
    assert qsimplify_pauli(sz * sz) == 1

I am still pondering the appropriate way if/how to support the existing behavior and issue deprecation warnings.

There seem to be several associated issues which this can help address such as: https://github.com/sympy/sympy/issues/24348 and https://github.com/sympy/sympy/pull/24178

This creates a baseline to implement Op.doit(), Op.evalf(), Op.collect() and Op.simplify() to replace the special purpose functions such as qsimplify_pauli (or qapply in the case of Operator class).  As and example, I am working on a collect method for the Sigma operators, https://github.com/rrodenbusch/sympy/blob/_add-pauli-SigmaI/sympy/physics/quantum/collect.py.  Since the result of a series of rotation operators, decomposed to pauli operators, can not be collected with the sympy core collect because they are non-commutative, this method has been very useful to me.  The other methods should be similar implementations.

If this appears workable, assign me this issue (and others which may be related) and I can integrate this with the base Operator class and run regression tests to evaluate the impact.

**Comment by oscarbenjamin** [comment]
> 1. Override the core Add, Mul and Pow classes to enable the capture of any cases which differ from core processing.

In general we need a better solution for things like this. It shouldn't be necessary to create so many different classes but somehow the design of sympy's expression types forces us down this path.

**Comment by rrodenbusch** [comment]
The only other option that I see is to make changes in the core classes; core class changes could be quite complex and possibly conflict with other uses.  To the positive, these three subclasses appear to be the key to supporting many of the standard sympy methods we currently replace with specialized methods and functions such as qsimplify_pauli.

**Comment by oscarbenjamin** [comment]
> The only other option that I see is to make changes in the core classes

I know. We just really need a third option!

**Comment by ellisonbg** [comment]
Hi everyone, there are some fun questions here. A few random thoughts...

* When we were creating `sympy.quantum` originally, we did carefully weight the two approaches of 1) using the existing `Add,Mul,Pow` classes and 2) creating custom ones for operators. In the end, we decided that the builtin ones handle so many cases (that are hard to get right) and that it would be easier to re-use them. We were hopeful that over time the existing classes would become more extensible.
* Not all identify operators are the same. Because of this, we may need to enable operators (or maybe the Hilbert spaces they live in) to declare what the identity operator is for that space. Once we have that in place, we can always grab the appropriate identity for any operator or state and handle it appropriately.
* Being careful about what the identity operator is for a given Hilbert space would also allow us to represent that operator as a more-useful than one would expect sum of outer products such as `Eq(IdentityOperator(), Sum(Ket(n)*Bra(n),(n,0,oo)))`.

**Comment by ellisonbg** [comment]
I should note though that doing this well may involve breaking changes because of the current limitations of the `IdentityOperator`.

**Comment by ellisonbg** [comment]
I have some other ideas on how we can solve this by removing the dependency of the `IdentityOperator` on the dimensionality. If we can do that, then it is more straightforward to return the one and only identity operator.

**Comment by ellisonbg** [comment]
OK, have spent some time looking at the different parts of the code involved here. Some observations and a recommendation:

* It was a mistake when we first implemented `IdentityOperator` to include the dimension in the class itself. The dimension only comes into play when you are representing it. As such, the dimension should be passed as an option to `represent` – I even thought this at that the time, but don't remember why we went with the current design.
* However, it trying to get `IdentityOperator` to play well with the builtin logic of `Mul` and `Pow`, I have reached the conclusion that we should deprecate `IdentityOperator` and use `S.One` instead. The thinking here is the the identity is always defined relative to the binary multiplication operation, which in this case is `Mul`. IOW, the need for an `IdentityOperator` and a custom `OperatorMul` class should go hand in hand.
* Using `S.One` as the multiplicative identity for operators also closely follows the usage of `S.Zero` as the additive identity and how they are used in traditional physics notation.
* Everyone is aware of the challenges with the existing classes for multplication, addition, etc. not being fully extensible. Until those issues are tackled, I think we should do everything possible to live within the constraints of the existing classes.
* Trying to get a second multiplicative identity to work properly  `IdentityOperator` is basely used in the code base so this transition will be fairly easy.

**Comment by ellisonbg** [comment]
One note about how this works in tensor products. If you want to build the operator `I x I` getting rid of the identity operator means you have to write this as `1 x 1`. Even if you simplify this down to the scalar `1`, that is fine as the action of `I x I` is identical to that of the scalar `1` (using `Mul` for multplication`).
