### ISSUE TITLE
Regression in Singleton/Integer between sympy-1.8 and 1.9

### ISSUE THREAD

**Issue by bjodah** [sympy/sympy#24268]
When investigating an error reported by a third party user (using a library that depends on SymPy) I think I found what looks like a regression in SymPy:
```shell-session
$ python3 -c "import sympy; type(sympy.sympify(3))(3)"  # this always works
$ python3 -c "import sympy; type(sympy.sympify(1))(1)"  # this works for sympy<=1.8, but fails from 1.9
```
This is the relevant traceback
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: Singleton.__init__.<locals>.<lambda>() takes 1 positional argument but 2 were given
```
I bisected this to gh-21260. cc @oscarbenjamin, what do you think?

**Comment by oscarbenjamin** [comment]
Should that be expected to work?

**Comment by bjodah** [comment]
I'd say typically "yes". It's hard to write generic code if it doesn't
work. And Python's internal types works like this.

**Comment by oscarbenjamin** [comment]
> And Python's internal types works like this.

Maybe so but SymPy's symbolic expressions do not in general. We're talking here about a symbolic expression rather than a numeric type.

The failing code is `v != type(v)(int(v))`. The reason this fails is because it essentially assumes that an object can be reconstructed like `type(obj)(obj)` which does often work for numeric types in Python and also for SymPy's Rational/Float. This fails though for singletons like `S.One` because they do not expect any arguments to be passed to the constructor and have a no argument constructor that always returned the same object:
```
In [53]: type(S.One)() is type(S.One)()
Out[53]: True
```
There are many questionable design decisions in SymPy here but with those decisions having been made I'm not sure that the constraint `obj == type(obj)(obj)` really makes sense or is well defined for SymPy expressions:
```
In [54]: obj = exp(2)

In [55]: obj
Out[55]: 
 2
ℯ 

In [56]: type(obj)
Out[56]: exp

In [57]: type(obj)(obj)
Out[57]: 
 ⎛ 2⎞
 ⎝ℯ ⎠
ℯ 
```
If I was going to write `v != type(v)(int(v))` then I would probably just write `v != int(v)`. That at least seems to rely on documented behaviour from the numbers ABCs:
https://peps.python.org/pep-3141/#notes-for-type-implementors

I'm happy to be corrected but I don't think that anything anywhere says that `obj == type(obj)(obj)` is an invariant that should be expected in any context in Python or SymPy. If there is an expectation for that to be specified then the expectation needs to be spelled out fully.

**Comment by bjodah** [comment]
I can't remember why I wrote `v != type(v)(int(v))`, hopefully there was some good reason for doing so. I will try to do what you suggested here of course (I'd like to think I did try that first, but you never know...).

I know why the code is failing. But the fact that `sympify` turns 1 into a singleton and 2 into an `Integer` shouldn't be something that a user of SymPy should need to know in my humble opinion. And to the end user it looks inconsistent.

And no, `type(obj)(obj) == obj` cannot hold for SymPy types in general (and for `Tuple` it's even a `!=` relationship). But for `Integer` I do think it makes sense, especially since Python's `int` fulfills this invariant (and I think mimicking the builtin type when possible is desirable). For types which fulfill `.is_Atom` *maybe* a case could be made, but then again, there's no equivalence of `Symbol` in Python (and `Symbol` requires a string as its argument). I do note that `Float`, `BooleanFalse` and `BooleanTrue` support this behavior.

This isn't a huge issue, I should fix the code that was relying on this to be more robust. But I thought it might be worthwhile to report it here anyway.

**Comment by oscarbenjamin** [comment]
There have been other attempts to make SymPy's `Integer/Rational` more compatible with other numeric types e.g. conforming to the numbers ABCs. There needs to be a clear scope though if we want to satisfy any invariant that cannot hold for general expressions. If e.g. `type(S.One)(1)` works then what happens for `type(S.One)(2)` and so on? What is the precise set of objects where it should hold?

These singletons have caused so many problems with pickling etc so beware that any changes here are quite risky.

**Comment by oscarbenjamin** [comment]
@bjodah I'm wondering if this issue can be closed.

**Comment by bjodah** [comment]
sure, thanks.
