### ISSUE TITLE
Optional dependency tests failing

### ISSUE THREAD

**Issue by bertiewooster** [sympy/sympy#24285]
All four optional dependency tests are failing for multiple pull requests (#24284 and #24283 which are documentation changes only), so I suspect there is some problem with the tests themselves. Specifically, in all of the logs (here's one [example log](https://github.com/sympy/sympy/actions/runs/3505971344/jobs/5872684560)), this one test is failing:

`sympy/external/tests/test_autowrap.py[16] sssssss........E                [FAIL]`

**Comment by eagleoflqj** [comment]
Same with #24282

**Comment by asmeurer** [comment]
autowrap uses distutils and numpy.distutils, which are both deprecated. We'll need to find an alternate solution. For now, we may just need to XFAIL these tests to fix the CI.

**Comment by oscarbenjamin** [comment]
See https://github.com/numpy/numpy/issues/22027

**Comment by oscarbenjamin** [comment]
The cause of this is the new setuptools release (65.6.0):
https://github.com/pypa/setuptools/issues/3693

**Comment by oscarbenjamin** [comment]
It isn't hard to fix this properly (rather than just XFAIL the tests). The description for how is in the linked numpy issue.

**Comment by oscarbenjamin** [comment]
More discussion about the cause of this can be found in this numpy issue https://github.com/numpy/numpy/issues/22623

**Comment by bertiewooster** [comment]
Bigger picture, is there a better way to manage our (testing) dependencies? It seems like every few weeks a case like this arises, leading to the sudden inability to merge branches, and potential confusion by the authors of multiple pull requests ("did my change cause this problem?").

Is there a better practice, for example pinning (fixing the version of) dependencies, then periodically upgrading the dependencies (perhaps monthly) and resolving any issues in a branch for that purpose?

**Comment by oscarbenjamin** [comment]
Your question supposes that this is a CI problem but it's actually only a CI problem because there is a bug. That bug will now be felt by users regardless of our CI and needs to be fixed. I don't think it is good for us to try to design a CI system that allows us to ignore that bug.

The way this has worked for a long time is that when these problems come up someone fixes the problem. In recent years that person has usually been me but I don't want to take sole responsibility for these things and for that reason I have not fixed this particular example even though it would not take long for me to do so. It also would not take long for someone else to fix this especially when I have pointed to a source that describes what the fix should be.

The fact that these things seem to go unfixed for some time recently is because I have decided that I will not personally drop what I'm doing to fix them and will instead wait to see what anyone else will do: if the situation is that no one other than me will take the time to apply a simple fix then that is an unsustainable state for the project as a whole.

**Comment by asmeurer** [comment]
The CI is functioning as intended. The point is to find bugs and it found one. The problem is that bugs like this that are caused by changes in upstream dependencies can show up completely unexpectedly. Requiring the CI to pass before merging prevents bugs from slipping into master, but it doesn't protect against bugs like this and rather hurts the situation because it makes bugs like this create situations like this out of nowhere.

I think the best fix here is to temporarily unrequire the optional dependencies build for merging PRs. That will make this a less of a pressing issue. It will need to be fixed before a release is made, and ideally sooner, but it shouldn't need to be fixed *now*. In the interim, please double check this build before merging anything to make sure nothing else is broken but this test. For full context, this is the test that fails:

```
________________________________________________________________________________
__________ sympy/external/tests/test_autowrap.py:test_ufuncify_numpy ___________
Traceback (most recent call last):
  File "/home/runner/work/sympy/sympy/sympy/core/cache.py", line 72, in wrapper
    retval = cfunc(*args, **kwargs)
TypeError: unhashable type: 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/sympy/sympy/sympy/utilities/autowrap.py", line 182, in _process_files
    retoutput = check_output(command, stderr=STDOUT)
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/opt/hostedtoolcache/Python/3.9.15/x64/bin/python', 'setup.py', 'build_ext', '--inplace']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/sympy/sympy/sympy/testing/runtests.py", line 1341, in _timeout
    function()
  File "/home/runner/work/sympy/sympy/sympy/external/tests/test_autowrap.py", line 313, in test_ufuncify_numpy
    runtest_ufuncify('C99', 'numpy')
  File "/home/runner/work/sympy/sympy/sympy/external/tests/test_autowrap.py", line 97, in runtest_ufuncify
    fabc = ufuncify([a, b, c], a*b + c, backend=backend)
  File "/home/runner/work/sympy/sympy/sympy/core/cache.py", line 76, in wrapper
    retval = func(*args, **kwargs)
  File "/home/runner/work/sympy/sympy/sympy/utilities/autowrap.py", line 1121, in ufuncify
    return code_wrapper.wrap_code(routines, helpers=helps)
  File "/home/runner/work/sympy/sympy/sympy/utilities/autowrap.py", line 844, in wrap_code
    self._process_files(routines)
  File "/home/runner/work/sympy/sympy/sympy/utilities/autowrap.py", line 184, in _process_files
    raise CodeWrapError(
sympy.utilities.autowrap.CodeWrapError: Error while executing command: /opt/hostedtoolcache/Python/3.9.15/x64/bin/python setup.py build_ext --inplace. Command output is:
Traceback (most recent call last):
  File "/tmp/tmpeb8m1jnj_sympy_compile/setup.py", line 13, in <module>
    from numpy.distutils.core import setup
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/numpy/distutils/__init__.py", line 26, in <module>
    from . import ccompiler
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/numpy/distutils/ccompiler.py", line 20, in <module>
    from numpy.distutils import log
  File "/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/numpy/distutils/log.py", line 4, in <module>
    from distutils.log import Log as old_Log
ImportError: cannot import name 'Log' from 'distutils.log' (/opt/hostedtoolcache/Python/3.9.15/x64/lib/python3.9/site-packages/setuptools/_distutils/log.py)
```


I can look into fixing this if no one else does first. Note that this week is the Thanksgiving holiday in the US and I am taking time off, so I may not actually be able to do so until next week, depending on what my week looks like.

**Comment by asmeurer** [comment]
I've unrequired the optional dependencies builds for merging. Once they are passing again, we should re-require them (but not be afraid to do this again if a similar issue arises in the future). 

If anyone with push access wants access to be able to do this, let me know. The page to do it is at https://github.com/sympy/sympy/settings/branch_protection_rules/18177.

**Comment by bertiewooster** [comment]
> The CI is functioning as intended. The point is to find bugs and it found one. The problem is that bugs like this that are caused by changes in upstream dependencies can show up completely unexpectedly.

Fair enough. The confusion arises when a bug arises apparently in a pull request, and it's not clear if the pull request changes themselves are causing the failure, or an upstream dependency.

Is there some way to run CI checks on the master branch, so we can confirm that a failure is due to an upstream dependency? It would be nice to be able to run CI checks on the master branch either:

- On demand, for example when a PR fails and we suspect it's due to an upstream dependency
- Periodically, for example weekly or monthly, to learn about a failure due to an upstream dependency ideally before it starts causing PRs to fail

**Comment by oscarbenjamin** [comment]
CI checks already run on the master branch. See the red cross here:
https://github.com/sympy/sympy

If you click the number of commits button just to the right of the cross (which currently reads  52,503) then you can see this page:
https://github.com/sympy/sympy/commits/master

The crosses and ticks from there will show tou the CI runs.

**Comment by oscarbenjamin** [comment]
This has been fixed upstream in setuptools.

**Comment by oscarbenjamin** [comment]
(Although SymPy should still stop using `numpy.distutils`)
