### ISSUE TITLE
No easy way to convert primitive expression to a number

### ISSUE THREAD

**Issue by blackyblack** [sympy/sympy#24365]
```python
expr = Expr(Integer(5))
int(expr)
```

Expected result:
```
5
```

Actual result:
```python
TypeError: Expected a number but got Expr:
```

It is virtually impossible to unwrap Integer from Expression. The only way to do it is to parse `expr.args`.

**Comment by oscarbenjamin** [comment]
This is to be expected. Expr is not supposed to be used directly like that but rather it should be subclassed and then the subclass should have some meaning that generally would not be as trivial as `ExprSubclass(obj) == obj`. Would you expect `int(cos(5))` to return `5`?

Whatever you are trying to do by using `Expr` like this should be done in a different way.

> It is virtually impossible to unwrap Integer from Expression. The only way to do it is to parse `expr.args`.

Parsing expr.args is precisely what you should do if you want to get the args of an expression. Using `expr.args[0]` is hardly "virtually impossible".

**Comment by blackyblack** [comment]
Why cannot an expression be as simple as `5`. Integer class in sympy is a subclass of `AtomicExpr`, so it seems it is an expression indeed.
And why we cannot convert expression to number, if `is_number` returns True? `5` obviously can be converted to number and I do not see any obstacles doing so. Also, for some reason `Expr` class has `__int__` method that obviously should return 5 for `5` expression. Why should it fail on such an input?

**Comment by oscarbenjamin** [comment]
You're missing the point: why are you using `Expr(Integer(5))` rather than just `Integer(5)`? What do you hope to achieve by doing that?

`Expr` is not supposed to be used like that. It has an `__int__` method that is intended to be inherited by subclasses such as `Integer` that are expected to be used directly. Those subclasses are supposed to define `is_number` and `evalf` so that the `__int__` method can work or otherwise override the `__int__` method as `Integer` does.

> Why should it fail on such an input?

Again you are missing the point: the question is why should it "succeed"? You are using `Expr` incorrectly. Why are you using it like that at all?

It absolutely does not make sense for `Expr` to have an `__int__` method that returns any of the arguments of the object because `Expr` is a superclass of many other classes that inherit this `__int__` method and returning `.args[0]` would be wrong for almost all of those subclasses.

**Comment by blackyblack** [comment]
> why are you using Expr(Integer(5)) rather than just Integer(5)? What do you hope to achieve by doing that?
I am implementing the scalar field functionality, so each element of field is defined as an expression. Eventually, when point is applied to a field, every expression will be substituted with point coordinates. So every element of a field should be of `Expr` type. As I get input as Python types, I expected to convert the input to expression simply by `expr = Expr(input)`. So here is why I expected `Expr` to behave the way I described.

> Expr is a superclass of many other classes that inherit this __int__ method and returning .args[0] would be wrong for almost all of those subclasses.
I didn't say that you should return `.args[0]`. Somehow `Expr` could detect that it is `is_number` so I believe it can tell me, what number it is. And if subclass is not happy with default __int__ implementation, there is always an option to override it.

**Comment by ThePauliPrinciple** [comment]
I think you are looking for `sympify`, or the more stricter version `_sympify` (which should generally be used when writing library code). This would convert a python type into one related to SymPy, or give an error when this is not possible.

```python
>>> from sympy import sympify
>>> type(sympify(1))
sympy.core.numbers.One
>>> int(sympify(1))
1
```

**Comment by blackyblack** [comment]
> I think you are looking for sympify

It actually sounds like a good idea, thank you. But still my concern about not being able to construct valid expression from a number persists.

**Comment by blackyblack** [comment]
On a second thought, if you think about `sympify` as a proper way of constructing expression, instead of `Expr` constructor (as I expected), it perfectly solves my concern.
I guess this issue can be closed then.
