### ISSUE TITLE
Are matrix equations with symbolic matrices solvable?

### ISSUE THREAD

**Issue by andreichalapco** [sympy/sympy#24507]
I tried the following code:

```python
from sympy import *
n = 2
A = MatrixSymbol('A', n, n)
x = MatrixSymbol('x', n, 1)
b = MatrixSymbol('b', n, 1)
solve(A*x-b, x)
```
and expected someting like x = A**(-1) *b
but instead I was trown an error

```shell
TypeError: First argument of MatrixElement should be a matrix
```

**Comment by oscarbenjamin** [comment]
The answer to the question is no. I don't think that `solve` should be made to handle this either. There could be a separate function for this sort of thing but `solve` should probably just raise an error if the user asks to solve for symbols that are not `NumberKind`.

**Comment by andreichalapco** [comment]
So there is no solution in sympy to solve symbolic equations with symbolic matrices and vectors ... Does no one need this functionality?

**Comment by ThePauliPrinciple** [comment]
This gives the answer you requested (but does not explicitly make use of matrices).

```python
>>> from sympy import *
>>> A = Symbol('A', commutative=False)
>>> x = Symbol('x', commutative=False)
>>> b = Symbol('b', commutative=False)
>>> solve(A*x-b, x)
[A**(-1)*b]
```

**Comment by oscarbenjamin** [comment]
Your equation is trivially easy to solve:
```
In [5]: expand(A**-1 * (A*x - b))
Out[5]: 
  -1      
-A  ⋅b + x
```
I expect that there could be an algorithm to solve trivial equations but I doubt that there would be any general complex algorithm for handling arbitrary equations involving matrix symbols. There is no point in adding a solver that only handles trivial things though as it just gives the misleading impression that it might be possible to do something more complicated.

If anyone knows of an algorithm that is nontrivial and handles a meaningful class of problems then that can be added as a new function in SymPy. Otherwise this issue should be closed as won't fix because adding the functionality to only solve trivial problems would be a mistake.

**Comment by andreichalapco** [comment]
Thank you! I thought there is another method besied commutative False ...
My initial idea was to solve larger equations ...
