### ISSUE TITLE
"Expression is problematic. Please submit this as a bug."

### ISSUE THREAD

**Issue by Kuratius** [sympy/sympy#24524]
![image](https://user-images.githubusercontent.com/47481645/212464896-79d7bf3a-70f8-4ebf-8656-c74b0646abad.png)
```
import sympy as sp
n=sp.Symbol('n')

def f(n):
    return 1/(1+sp.exp(-n))

T=50
x=sp.Symbol('x')

def expit(x):
    return sp.Sum(f(T*(x-n)),(n,0,3))

sp.plot(expit(x), (x,0,3))

```

**Comment by MohitKumar020291** [comment]
Hello @Kuratius , the issue will be simply solve by using `summation` instead of  `sum`.

**Comment by Kuratius** [comment]
@MohitKumar020291 Please read the error message. You misunderstood why I opened this issue.

**Comment by MohitKumar020291** [comment]
thanks @Kuratius for your response. It is the problem because you have not imported `expit()` function , for importing it you should know that there should be a `PYTHONPATH` in which you must have a file defining `expit()` so , you are getting error because you are using it in **jupyter notebook** , these are general error when you use **jupyter notebook** as it does have all directories or file to progress. 
secondly, `failback` method means your solution is not efficient , it does not means to inaccurate and it is showing your solution is not efficient because it has taken `expit()` for use from `expit_module.py` which is a user defined not `inbuilt`.
I hope that helps.
Please free to ask me and make me more correct.

**Comment by Kuratius** [comment]
You don't understand how python namespaces work.

**Comment by MohitKumar020291** [comment]
@Kuratius Yes , I do not know Python namespaces even and using chatbot. Asking questions to AI is not a good practice? How did you get to know that , did you used it also?

**Comment by oscarbenjamin** [comment]
> Asking questions to AI is not a good practice?

No, it is not a good practice. Feel free to talk to the chatbot yourself but if you're going to talk to people on this platform then you should write messages yourself.

**Comment by oscarbenjamin** [comment]
@Kuratius thanks for reporting this. This is a common problem and relates to the plotting module's use of `experimental_lambdify` rather than actual `lambdify`.

**Comment by MohitKumar020291** [comment]
Can @Kuratius can you please elaborate the issue , I mean why did you opened this.

**Comment by SamLubelsky** [comment]
This warning no longer appears because of the switch from experimental_lambdify to lambdify, looks like this issue can be safely closed.
![Capture](https://github.com/sympy/sympy/assets/78610785/92b182a1-3545-45f8-b097-d580b10c68db)
