### ISSUE TITLE
memory leak, not a cache issue

### ISSUE THREAD

**Issue by Shigerman** [sympy/sympy#24581]
Hello

I have the following code that uses the latest sympy (1.11.1) tested with python 3.8.10 on Windows 10 and with python 3.11.1 on macOS 13.1, the memory is constantly growing. Any ideas why?

```
from sympy import Point, Ray, Circle
while True:
    circle = Circle(Point(0.0, 0.0), 0.5)
    ray = Ray(Point(0.2, 0.3), Point(0.3, 0.2))
    res = circle.intersection(ray)
```

NOTE: the growth in geometry has been addressed, but the scope of the issue is greater than that module so the issue is still open.

**Comment by oscarbenjamin** [comment]
I can reproduce this but no idea why it happens. Clearing the cache doesn't help. Calling `gc.collect` doesn't help.

**Comment by oscarbenjamin** [comment]
With this diff the memory usage stays constant:
```diff
diff --git a/sympy/geometry/ellipse.py b/sympy/geometry/ellipse.py
index 0c1c5d0..35d92af 100644
--- a/sympy/geometry/ellipse.py
+++ b/sympy/geometry/ellipse.py
@@ -14,7 +14,7 @@
 from sympy.core.logic import fuzzy_bool
 from sympy.core.numbers import Rational, oo
 from sympy.core.sorting import ordered
-from sympy.core.symbol import Dummy, uniquely_named_symbol, _symbol
+from sympy.core.symbol import Symbol, Dummy, uniquely_named_symbol, _symbol
 from sympy.simplify import simplify, trigsimp
 from sympy.functions.elementary.miscellaneous import sqrt, Max
 from sympy.functions.elementary.trigonometric import cos, sin
@@ -664,8 +664,8 @@ def intersection(self, o):
         [Point2D(-17/5, -12/5), Point2D(-17/5, 12/5), Point2D(7/5, -12/5), Point2D(7/5, 12/5)]
         """
         # TODO: Replace solve with nonlinsolve, when nonlinsolve will be able to solve in real domain
-        x = Dummy('x', real=True)
-        y = Dummy('y', real=True)
+        x = Symbol('x', real=True)
+        y = Symbol('y', real=True)
 
         if isinstance(o, Point):
             if o in self:
```
So what is happening is that every time `intersection` is called two new `Dummy` symbols are created. Somewhere there is some sort of cache that grows without bound if more and more symbols are created.

**Comment by oscarbenjamin** [comment]
It's here (and a similar one in fields.py):
https://github.com/sympy/sympy/blob/f8e33851e174bd686ac8dc88d75f955cf5dc8eeb/sympy/polys/rings.py#L194
This cache grows without bound every time a polynomial ring with new symbols is used.

A fix could be to use `lru_cache` instead of a global cache.

I am not entirely sure that this is only a cache though because it also associates with a particular PolyElement class and it is possible that that class needs to be globally unique.

**Comment by asmeurer** [comment]
Can't that be solved by using a WeakDictionary? 

I've never been a huge fan of this class design in the polys FWIW.

**Comment by oscarbenjamin** [comment]
I think that a WeakValue dictionary could work but it would probably not achieve the performance benefits intended by the cache in the first place. The point is that this second call is faster:
```python
In [1]: %time K = QQ[x,y]
CPU times: user 4 ms, sys: 0 ns, total: 4 ms
Wall time: 2.38 ms

In [2]: %time K = QQ[x,y]
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 89.6 µs
```
Usually these rings are created transiently as part of an operation like `factor`, `cancel` etc. Since the ring is only a temporary object there will probably not be many in existence at any one time so with a WeakValue dictionary the ring will always disappear. In that case we would be better off just not having any cache. On the other hand of many operations like `factor`, `cancel` etc are used as part of a complex operation it is likely that the same ring will be reconstructed many times so keeping a cache can save time on that.

I think that probably a LRU cache is good here but given the size of these rings it should probably be kept quite small:
```python
diff --git a/sympy/polys/fields.py b/sympy/polys/fields.py
index a3f239c..cdb079a 100644
--- a/sympy/polys/fields.py
+++ b/sympy/polys/fields.py
@@ -6,6 +6,7 @@
 
 from operator import add, mul, lt, le, gt, ge
 
+from sympy.core.cache import __cacheit as _cacheit
 from sympy.core.expr import Expr
 from sympy.core.mod import Mod
 from sympy.core.numbers import Exp1
@@ -99,11 +100,11 @@ def sfield(exprs, *symbols, **options):
     else:
         return (_field, fracs)
 
-_field_cache: dict[Any, Any] = {}
 
 class FracField(DefaultPrinting):
     """Multivariate distributed rational function field. """
 
+    @_cacheit(10)
     def __new__(cls, symbols, domain, order=lex):
         from sympy.polys.rings import PolyRing
         ring = PolyRing(symbols, domain, order)
@@ -113,7 +114,7 @@ def __new__(cls, symbols, domain, order=lex):
         order = ring.order
 
         _hash_tuple = (cls.__name__, symbols, ngens, domain, order)
-        obj = _field_cache.get(_hash_tuple)
+        obj = None
 
         if obj is None:
             obj = object.__new__(cls)
@@ -138,8 +139,6 @@ def __new__(cls, symbols, domain, order=lex):
                     if not hasattr(obj, name):
                         setattr(obj, name, generator)
 
-            _field_cache[_hash_tuple] = obj
-
         return obj
 
     def _gens(self):
diff --git a/sympy/polys/rings.py b/sympy/polys/rings.py
index 0db1897..3a56486 100644
--- a/sympy/polys/rings.py
+++ b/sympy/polys/rings.py
@@ -7,6 +7,7 @@
 from functools import reduce
 from types import GeneratorType
 
+from sympy.core.cache import __cacheit as _cacheit
 from sympy.core.expr import Expr
 from sympy.core.numbers import igcd, oo
 from sympy.core.symbol import Symbol, symbols as _symbols
@@ -191,11 +192,11 @@ def _parse_symbols(symbols):
 
     raise GeneratorsError("expected a string, Symbol or expression or a non-empty sequence of strings, Symbols or expressions")
 
-_ring_cache: dict[Any, Any] = {}
 
 class PolyRing(DefaultPrinting, IPolys):
     """Multivariate distributed polynomial ring. """
 
+    @_cacheit(10)
     def __new__(cls, symbols, domain, order=lex):
         symbols = tuple(_parse_symbols(symbols))
         ngens = len(symbols)
@@ -203,7 +204,7 @@ def __new__(cls, symbols, domain, order=lex):
         order = OrderOpt.preprocess(order)
 
         _hash_tuple = (cls.__name__, symbols, ngens, domain, order)
-        obj = _ring_cache.get(_hash_tuple)
+        obj = None
 
         if obj is None:
             if domain.is_Composite and set(symbols) & set(domain.symbols):
@@ -257,8 +258,6 @@ def __new__(cls, symbols, domain, order=lex):
                     if not hasattr(obj, name):
                         setattr(obj, name, generator)
 
-            _ring_cache[_hash_tuple] = obj
-
         return obj
 
     def _gens(self):
```
In the long run the best solution would be to make the ring objects lighter weight and faster to construct.

**Comment by smichr** [comment]
> With this diff the memory usage stays constant:

Those two Dummy symbols should be created at the top of ellipse.py and then used the 4 times when needed in the various classes -- there is no need to keep creating new Dummy symbols.

**Comment by oscarbenjamin** [comment]
To be clear plenty of other operations can cause this cache to grow and even to grow more quickly:
```
while True:
    cancel(Dummy('x') + 1)
```

**Comment by asmeurer** [comment]
I thought the point was that these objects break if they aren't singletonized? I seem to remember that sort of thing being the case for these classes in the polys, but correct me if I am wrong. If that's the case, you'd need a version of lru_cache that also acts like a weak dictionary (i.e., least recently used items aren't removed from the cache if they are also referenced somewhere).

**Comment by asmeurer** [comment]
> Those two Dummy symbols should be created at the top of ellipse.py and then used the 4 times when needed in the various classes -- there is no need to keep creating new Dummy symbols.

Wouldn't that change the semantics? A dummy symbol is supposed to be unequal to everything except for itself. Two separate intersections should have dummies that are unequal, but reusing the same Dummy would make them equal.

**Comment by oscarbenjamin** [comment]
> I thought the point was that these objects break if they aren't singletonized?

Yes, actually they do. I just tried removing the cache and a bunch of poly tests failed. The problem is e.g. this:
https://github.com/sympy/sympy/blob/f8e33851e174bd686ac8dc88d75f955cf5dc8eeb/sympy/polys/rings.py#L419
Each ring dynamically creates a class for its elements and distinct copies of the same ring would have different classes.

I've opened #24585 which for now removes the ring cache altogether so we can see if there's a noticeable impact on performance and if the need for the ring cache is gone.

Longer term I would like to remove the dynamic class generation altogether. Also we should just make the construction of rings faster.

**Comment by asmeurer** [comment]
I'm +1 to removing the metaprogramming there. I remember trying to do something to that code once and giving up because of the dynamic class creation (I don't remember why. I was trying to fix pickling or something like that). I tried to do it via maintaining backwards compatibility and doing what it's doing in a more sane way with a metaclass, but I failed. If we can just break compatibility and have a more sane set of classes without metaprogramming that would be better (hopefully without breaking performance too much).

**Comment by smichr** [comment]
> Wouldn't that change the semantics?

Since no other symbol will be the same as these dummies in any expression created by a user, the disambiguation is persistent after only one creation of the needed symbols. It would only be a problem if these symbols were used to recursively create a geometric object during the action of a routine.

**Comment by sylee957** [comment]
This should also happen with custom function

```
import tracemalloc
from itertools import count
from sympy import *

counter = count()
tracemalloc.start()

while True:
    i = next(counter)
    Function(f'f_{i}')
    if not i % 100:
        print(tracemalloc.get_traced_memory())
        
    if i == 10000:
        break
```
because of sympy `BasicMeta` keeping every classes that are generated dynamically

**Comment by oscarbenjamin** [comment]
This issue should not be closed yet. Quoting from above:

> To be clear plenty of other operations can cause this cache to grow and even to grow more quickly:
> 
> ```
> while True:
>     cancel(Dummy('x') + 1)
> ```

**Comment by Shigerman** [comment]
Thank you so much for the fix. May I ask you when a new version with this fix will be available on pypi?

**Comment by oscarbenjamin** [comment]
I'm not sure exactly when the next release will be yet but it should be soon.
