### ISSUE TITLE
Put feature to determine max result value

### ISSUE THREAD

**Issue by michalmicpaw** [sympy/sympy#24629]
Hi 
Is it possibile to create ability to limit max value of number as result od calculation over which calculations will not be even started?

I.e.

2**999999999999999 will hang process. I've spoken here how to achieve it.

https://github.com/sympy/sympy/issues/21579

Is it posibble to give config var with max val of result over which calculations will not be started?

Thank you

**Comment by oscarbenjamin** [comment]
> Is it posibble to give config var with max val of result over which calculations will not be started?

No it is not right now. It would be good to have some configuration for this but currently that is not possible because that configuration has not been implemented. As mentioned in the issue you referenced (#21579) there are other issues for this (e.g. https://github.com/sympy/sympy/issues/6835 https://github.com/sympy/sympy/pull/20668) so we don't need a new issue which is why I'm going to close this.

If you want to submit a pull request with some potential improvements then go ahead. If you want to discuss the idea first then please use the existing issues rather than creating a new one. If you think that #21579 should not have been closed then we can reopen it to continue discussion about your ideas there.

**Comment by michalmicpaw** [comment]
Hello, I'd like to please to reopen the https://github.com/sympy/sympy/issues/21579 issue that I could discuss.

Thanks
Mike.

**Comment by oscarbenjamin** [comment]
We already have #6835 for this. We don't need to have multiple issues open for the same thing. You can just add your comments to the existing issue (after reading what is already discussed there and looking at some of the many other issues that are referenced from there).
