### ISSUE TITLE
TypeError:  Incompatible use of binary symbol `A` as a real variable in `A >= oo`

### ISSUE THREAD

**Issue by canvas7** [sympy/sympy#24650]
I'm trying to solve a differential equation.  Code as follows:

```
from sympy import Function, dsolve, Eq, Derivative, symbols
from sympy.abc import t, sigma

A, B, C, D = symbols('A,B,C,D')
f = Function('f')(t)
expr = Eq(Derivative(f, t) + 2 * (A/(B+t)) * f, sigma**2/2*(A/(B+t))**2)

dsolve(expr)
```

The program failed while I have checked with Wolfram Alpha that this equation is solvable.  Error as follows:
```
Traceback (most recent call last):
  File "C:\Users\Ping\PycharmProjects\pythonProject\spline.py", line 8, in <module>
    dsolve(expr)
  File "C:\Users\Ping\mambaforge\lib\site-packages\sympy\solvers\ode\ode.py", line 640, in dsolve
    return _helper_simplify(eq, hint, hints, simplify, ics=ics)
  File "C:\Users\Ping\mambaforge\lib\site-packages\sympy\solvers\ode\ode.py", line 690, in _helper_simplify
    rv = _remove_redundant_solutions(eq, rv, order, func.args[0])
  File "C:\Users\Ping\mambaforge\lib\site-packages\sympy\solvers\ode\ode.py", line 2627, in _remove_redundant_solutions
    if is_special_case_of(soln1, soln2):
  File "C:\Users\Ping\mambaforge\lib\site-packages\sympy\solvers\ode\ode.py", line 2622, in is_special_case_of
    return _is_special_case_of(soln1, soln2, eq, order, var)
  File "C:\Users\Ping\mambaforge\lib\site-packages\sympy\solvers\ode\ode.py", line 2693, in _is_special_case_of
    constant_solns = solve(eqns, constants2)
  File "C:\Users\Ping\mambaforge\lib\site-packages\sympy\solvers\solvers.py", line 924, in solve
    fi = fi.rewrite(Add, evaluate=False)
  File "C:\Users\Ping\mambaforge\lib\site-packages\sympy\core\basic.py", line 1894, in rewrite
    return self._rewrite(pattern, rule, method, **hints)
  File "C:\Users\Ping\mambaforge\lib\site-packages\sympy\core\basic.py", line 1899, in _rewrite
    args = [a._rewrite(pattern, rule, method, **hints)
  File "C:\Users\Ping\mambaforge\lib\site-packages\sympy\core\basic.py", line 1899, in <listcomp>
    args = [a._rewrite(pattern, rule, method, **hints)
  File "C:\Users\Ping\mambaforge\lib\site-packages\sympy\core\basic.py", line 1899, in _rewrite
    args = [a._rewrite(pattern, rule, method, **hints)
  File "C:\Users\Ping\mambaforge\lib\site-packages\sympy\core\basic.py", line 1899, in <listcomp>
    args = [a._rewrite(pattern, rule, method, **hints)
  File "C:\Users\Ping\mambaforge\lib\site-packages\sympy\core\basic.py", line 1899, in _rewrite
    args = [a._rewrite(pattern, rule, method, **hints)
  File "C:\Users\Ping\mambaforge\lib\site-packages\sympy\core\basic.py", line 1899, in <listcomp>
    args = [a._rewrite(pattern, rule, method, **hints)
  File "C:\Users\Ping\mambaforge\lib\site-packages\sympy\core\basic.py", line 1899, in _rewrite
    args = [a._rewrite(pattern, rule, method, **hints)
  File "C:\Users\Ping\mambaforge\lib\site-packages\sympy\core\basic.py", line 1899, in <listcomp>
    args = [a._rewrite(pattern, rule, method, **hints)
  File "C:\Users\Ping\mambaforge\lib\site-packages\sympy\core\basic.py", line 1899, in _rewrite
    args = [a._rewrite(pattern, rule, method, **hints)
  File "C:\Users\Ping\mambaforge\lib\site-packages\sympy\core\basic.py", line 1899, in <listcomp>
    args = [a._rewrite(pattern, rule, method, **hints)
  File "C:\Users\Ping\mambaforge\lib\site-packages\sympy\core\basic.py", line 1913, in _rewrite
    return self.func(*args)
  File "C:\Users\Ping\mambaforge\lib\site-packages\sympy\core\operations.py", line 512, in __new__
    _args = frozenset(cls._new_args_filter(args))
  File "C:\Users\Ping\mambaforge\lib\site-packages\sympy\logic\boolalg.py", line 766, in _new_args_filter
    args = BooleanFunction.binary_check_and_simplify(*args)
  File "C:\Users\Ping\mambaforge\lib\site-packages\sympy\logic\boolalg.py", line 507, in binary_check_and_simplify
    raise TypeError(filldedent('''
TypeError: 
Incompatible use of binary symbol `A` as a real variable in `A <= -oo`
```

**Comment by ThePauliPrinciple** [comment]
Looks like a regression. This does not give an error on sympy 1.7.1 
Can you give any details about the version of sympy that you are using?

**Comment by canvas7** [comment]
>

**Comment by canvas7** [comment]
sympy 1.11.1




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sympy/sympy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月3日(星期五) 下午5:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sympy/sympy] TypeError:  Incompatible use of binary symbol `A` as a real variable in `A &gt;= oo` (Issue #24650)





 
Looks like a regression. This does not give an error on sympy 1.7.1
 Can you give any details about the version of sympy that you are using?

**Comment by hanspi42** [comment]
Trying to debug, I found some strange behaviour: I added one `print` line in `class Or(LatticeOp, BooleanFunction):` in the file `boolalg.py`:

```
    def _new_args_filter(cls, args):
        newargs = []
        rel = []
        print('**********', list(args))
        args = BooleanFunction.binary_check_and_simplify(*args)
```

The `args` coming in is a generator, and `list(args)` converts it to a list such that I can look at it.

However, if I do that, then the `TypeError` does not appear anymore. Is it possible that the SymPy caching for that kind of generators is messed up?

**Comment by hanspi42** [comment]
Also, this `print` line is only called twice.

If I replace it by `print('**********', args)`, which does not trigger the generator, it is called around fity times until I get the `TypeError`

**Comment by hanspi42** [comment]
More info;

We have this here:

https://github.com/sympy/sympy/blob/52735726299e2d4b49083397cceca74c189e239b/sympy/core/operations.py#L505-L515

It is what it is causing trouble once it gets here:

https://github.com/sympy/sympy/blob/52735726299e2d4b49083397cceca74c189e239b/sympy/logic/boolalg.py#L762-L777

The two together cause the incoming generator to cause the error above unless the generator has been activated once before it gets to line 766 of `boolalg.py`

However, this is where I have to stop, I do not really understand what is being done here, why a frozenset is used on a generator, and what happens if I change anything.

**Comment by asmeurer** [comment]
The problem is this:

```py
>>> Eq(x, 0).rewrite(Add)
x
```

The Boolean constructor has a check that a variable isn't being used as both a boolean and real variable, and the rewrite causes something like `Eq(x, 0) | (x <= -oo)` to become `x | (x <= -oo)`, which triggers the error. 

The problem is that `Eq(x, y).rewrite(Add)` means return `x - y`. But these two expressions are not really mathematically equivalent. They're just equivalent as SymPy syntatictic convenience in some functions. This rewrite happens in solve as part of preprocessing. 

A possible fix would be to not do this rewrite deeply in `solve`:

```diff
diff --git a/sympy/solvers/solvers.py b/sympy/solvers/solvers.py
index 56fba469cd..b0d908e937 100644
--- a/sympy/solvers/solvers.py
+++ b/sympy/solvers/solvers.py
@@ -921,7 +921,7 @@ def _sympified_list(w):
                             is True or False.
                         '''))
                 else:
-                    fi = fi.rewrite(Add, evaluate=False)
+                    fi = fi.rewrite(Add, evaluate=False, deep=False)
             f[i] = fi

         if fi.is_Relational:
```

since it's only trying to canonicalize the inputs, so it shouldn't rewrite Eqs that are deeper in an expression (in this case, in a Piecewise). But I haven't checked if this breaks anything else.

**Comment by hanspi42** [comment]
> But I haven't checked if this breaks anything else.

I have, it doesn't.

**Comment by sylee957** [comment]
I'm not obvious why `evaluate=False` object is needed or `deep=False` should be a correct guard. 
If there is a cross over type issues between expression and boolean, I assume there should be something else responsible for it

**Comment by asmeurer** [comment]
The evaluate=False is so things don't cancel. Presumably it's because of something like `solve(Eq(x + 1/x, 1/x))` which would return `0` if you navely cancelled the `1/x`. 

deep=False is clearer. It should only rewrite the equality if the expression itself is an equality. It should rewrite equalities deeper in the expression, like in a Piecewise. 

Of course, both of these could be added as comments in the code.

> If there is a cross over type issues between expression and boolean, I assume there should be something else responsible for it

It's true that rewrite doing this mathematically questionable rewrite is problematic. But solve needs to turn Eq(x, y) into x - y one way or another, whether that's through a rewrite method or through a direct `replace`. And no matter how it does it, it needs to do it with deep=False so that it only replaces the top-level expression if it is an Eq. 

So in that sense this is sort of a secondary issue.

**Comment by oscarbenjamin** [comment]
> It's true that rewrite doing this mathematically questionable rewrite is problematic. But solve needs to turn Eq(x, y) into x - y one way or another, whether that's through a rewrite method or through a direct `replace`. And no matter how it does it, it needs to do it with deep=False so that it only replaces the top-level expression if it is an Eq.

I don't think that `Eq.rewrite(Add)` really makes sense as a feature at all because it turns a Boolean into an Expr which is not really a "rewrite". In SymPy usually `e.rewrite(A)` should generate an object that is mathematically equivalent to `e` but somehow in a different form that involves `A`. Replacing an equation with an expression does not meet that and leads to the problem above. If the `rewrite` method only ever returned equivalent objects then with or without `deep=False` there would be no error from a Boolean becoming an Expr in a context where only Boolean is allowed.

Why shouldn't this be written as:
```python
fi = Add(fi.lhs, -fi.rhs, evaluate=False)
```
Of course if we want a special method like `Eq.to_expr(evaluate=False)` then we can add that instead but I think that the root of the bug here is the misuse of `rewrite` by allowing it to return non-interchangeable objects.

**Comment by asmeurer** [comment]
The `Equality._eval_rewrite_as_Add` method handles some corner cases that that doesn't, but in general I do agree this should be done in rewrite.

The best would probably be to move this logic into a method of Eq distinct from `rewrite` like `to_expr` or `to_Add`, and which doesn't do any deep processing.

**Comment by asmeurer** [comment]
Or even better would be if `solve` preprocessed out the common lhs and rhs terms first (they're only needed for the `check` step, like in my example above, right?), and just do `fi.lhs - fi.rhs`. That way there's no fiddling with unevaluated Adds either.

**Comment by oscarbenjamin** [comment]
I think as you say the idea is not to cancel terms that might invalidate the solution. I'm not sure how you'd keep track of that in solve otherwise given that it is generally a bit of a mess. Ideally checking would be done against the original equations before any manipulation or rewrites etc but I know that's not what happens and I've seen bugs as a result.
