### ISSUE TITLE
Replacing uses of `type(i)` with `isinstance`

### ISSUE THREAD

**Issue by michelececcacci** [sympy/sympy#24705]
While discussing #24690 this point was raised by @asmeurer. 
>Although I will say that code like this line should be using isinstance regardless. type(i) is ... is bad practice in general.

Can i start working on it? (opening an issue to reference this in PRs)

**Comment by hanspi42** [comment]
This is done in at least 24 files, but sure, you can start working on it. I don't think, though, that it would make a lot of sense to change only that in all files. https://peps.python.org/pep-0008/#programming-recommendations gives a whole list of programming recomendations. Maybe it would be better to tidy up all of it in one file a piece.

**Comment by michelececcacci** [comment]
Ok,   i will start committing single files. Thanks a lot!

**Comment by theWiseAman** [comment]
@michelececcacci Can you close this issue if things were sorted?

**Comment by theWiseAman** [comment]
@michelececcacci Can I collaborate then?

**Comment by michelececcacci** [comment]
yeah, sure. I'll also work on some files.

**Comment by theWiseAman** [comment]
@michelececcacci Ok after going through the exact details of the issue I will inform beforehand the files I would be editing to avoid any clashes. Hope it works.

**Comment by michelececcacci** [comment]
Thanks, that is amazing. I will do the same.

**Comment by Skylion007** [comment]
We can lint this by enabling the E721 check in flake8/ruff.

**Comment by asmeurer** [comment]
I would indeed be careful with this change. One place where it is actually correct to test type() exactly is in tests, where you want to check that the type of something is exactly some type, and not a subtype. It is also possible (although rare) that this sort of thing could legitimately happen in function logic.

**Comment by ThePauliPrinciple** [comment]
Might also be problematic when checking if an expression is a function, since mathematical functions in sympy are classes: `type(expr) == cos`. There might be some code that wants to check if something is exactly a certain function and not a subclass of that.

Identifying places where `type(i)` is actually used incorrectly and changing it to `isinstance` seems like a good idea, but just having a linter replace all seems like risky business that might introduce multiple weirdly interacting bugs in the same PR.

**Comment by oscarbenjamin** [comment]
I'm going to close this issue. I don't disagree with the idea but I also don't think there is any need to keep an open ticket for this because it is discussing a mostly stylistic point and does not identify any particular bug.

If anyone wants to submit a PR with improvements to the codebase then go ahead. A PR does not need to be directly connected to an issue though so just open the PR if there are changes that can be made.
