### ISSUE TITLE
'(-8)**(2/3)' the answer is not 4, it's normal?

### ISSUE THREAD

**Issue by ChisenZhang** [sympy/sympy#24907]
the exp is '(-8)\*\*(2/3)', let tmp='(-8)\*\*(2/3)';
call simplify(tmp)  then the answer is 4*(-1)**(2/3),
and simplify(tmp).evalf(), the answer is -2.0 + 3.46410161513775*I, it's noraml?  
the value of this exp is equal to 4

**Comment by 1e9abhi1e10** [comment]
The exp (-8)**(2/3) can be written as (8*(-1))**(2/3). Since 8 is a perfect cube, we can simplify this to 8**(2/3)*(-1)**(2/3).

Now, the cube root of 8 is 2, so 8**(2/3) can be replaced by 4. Then we can write it as we have (-8)**(2/3) = 4*(-1)**(2/3).
The expression (-1)**(2/3) is a complex number, which can be represented in terms of the complex cube roots of unity.

**Comment by TiloRC** [comment]
This might be helpful:
https://math.stackexchange.com/questions/317528/how-do-you-compute-negative-numbers-to-fractional-powers

**Comment by oscarbenjamin** [comment]
There is `real_root` if you want the real root of negative numbers:
```python
In [80]: real_root(-8, 3)**2
Out[80]: 4
```

**Comment by asmeurer** [comment]
We should write something about this somewhere in the docs, if there isn't something already.
