### ISSUE TITLE
Matrix multiplication with big-O raises a RuntimeError

### ISSUE THREAD

**Issue by ThibaultLejemble** [sympy/sympy#24947]
This matrix multiplication raises a `RuntimeError`
```python
from sympy import *

a = Symbol('a')
b = Symbol('b')
x = Symbol('x')

A = Matrix([
	[0, 0, 0, -1/2], 
	[0, 1, 0, 0], 
	[0, 0, 1, 0], 
	[-1/2, 0, 0, 0]])

B = Matrix([
	[pi*x**2, 0, pi*b*x**4/8 + pi*a*x**4/8 + O(x**5), pi*x**4/2 + pi*b**2*x**6/32 + pi*a*b*x**6/48 + pi*a**2*x**6/32 + O(x**7)],
	[0, pi*x**4/4, O(x**6), O(x**8)], 
	[pi*b*x**4/8 + pi*a*x**4/8 + O(x**5), O(x**6), pi*b**2*x**6/32 + pi*a*b*x**6/48 + pi*a**2*x**6/32 + O(x**7), pi*b*x**6/12 + pi*a*x**6/12 + O(x**7)], 
	[pi*x**4/2 + pi*b**2*x**6/32 + pi*a*b*x**6/48 + pi*a**2*x**6/32 + O(x**7), O(x**8), pi*b*x**6/12 + pi*a*x**6/12 + O(x**7), pi*x**6/3 + 3*pi*b**2*x**8/64 + pi*a*b*x**8/32 + 3*pi*a**2*x**8/64 + O(x**9)]])

C = A * B
```
with the following call stack
```
Traceback (most recent call last):
  File "/home/.../.../.../file.py", line 26, in <module>
    C = A * B
  File "/usr/lib/python3/dist-packages/sympy/core/decorators.py", line 136, in binary_op_wrapper
    return func(self, other)
  File "/usr/lib/python3/dist-packages/sympy/matrices/common.py", line 2763, in __mul__
    return self.multiply(other)
  File "/usr/lib/python3/dist-packages/sympy/matrices/common.py", line 2790, in multiply
    m = self._eval_matrix_mul(other)
  File "/usr/lib/python3/dist-packages/sympy/matrices/repmatrix.py", line 236, in _eval_matrix_mul
    return classof(self, other)._fromrep(self._rep * other._rep)
  File "/usr/lib/python3/dist-packages/sympy/polys/matrices/domainmatrix.py", line 711, in __mul__
    return A.matmul(B)
  File "/usr/lib/python3/dist-packages/sympy/polys/matrices/domainmatrix.py", line 961, in matmul
    return A.from_rep(A.rep.matmul(B.rep))
  File "/usr/lib/python3/dist-packages/sympy/polys/matrices/sdm.py", line 481, in matmul
    C = sdm_matmul(A, B, A.domain, m, o)
  File "/usr/lib/python3/dist-packages/sympy/polys/matrices/sdm.py", line 923, in sdm_matmul
    return sdm_matmul_exraw(A, B, K, m, o)
  File "/usr/lib/python3/dist-packages/sympy/polys/matrices/sdm.py", line 1005, in sdm_matmul_exraw
    raise RuntimeError
RuntimeError
```
where it is written in a comment
```python
# Not sure how we could get here but let's raise an
# exception just in case.
raise RuntimeError
```

It comes from the big-O expressions, because when I manually remove them the error is gone.

Maybe it is related to theses other issues with big-O 
- https://github.com/sympy/sympy/issues/24913
- https://github.com/sympy/sympy/issues/24477

The core issue seems to be this: "An Order inside an Add inside a Mul does not behave as expected during subtraction" https://github.com/sympy/sympy/issues/24477#issuecomment-1374825840

**Comment by oscarbenjamin** [comment]
So we're looking at this code:
https://github.com/sympy/sympy/blob/b06cedf99ffae2a4a4f6b0c8d5684ea3318fecbd/sympy/polys/matrices/sdm.py#L1022-L1035
The intention of this code is to find any `Bkj` that do not respect the usual `0*x = 0` rule and the compute the implications of that in the matrix product (zero entries are otherwise skipped during the matrix multiplication for efficiency).

We know that each `Cij` should have a term like `Aik * Bkj`. The previous loops will have skipped computing this as `Aik = 0` so we come back looking for each `Aik` that is zero. Now here `Cij  = O(0)` and `Aik = 0` and `Bkj = O(0)`. The curious arithmetic that the code rejects is this:
```python
In [11]: inf = O(0)

In [12]: inf
Out[12]: O(0)

In [13]: 0*inf
Out[13]: O(0)

In [14]: inf + inf
Out[14]: 0

In [15]: 0*inf == 0
Out[15]: False

In [16]: inf + inf == 0
Out[16]: True
```
The intention of this code was to pick up on infinities because they don't behave as intended under zero multiplication. I guess it seems natural to assume that any such infinities could not also add to zero.

The question is what exactly should this `O(0)` do? What should its arithmetic be? I would have thought that we should just have `0*O(0) -> 0`.

Of course other things can happen:
```python
In [17]: 0*(1 + O(0))
Out[17]: 0

In [18]: 0*1 + 0*O(0)
Out[18]: O(0)
```
