### ISSUE TITLE
What is the difference between `_polynomial_congruence_prime` and `csolve_prime`?

### ISSUE THREAD

**Issue by haru-44** [sympy/sympy#25034]
Both `sympy.ntheory.residue_ntheory._polynomial_congruence_prime` and `sympy.polys.galoistools.csolve_prime` are functions that solve congruent equations. The `csolve_prime` one even works for prime powers. Is it necessary to use `_polynomial_congruence_prime`?

The same can be said for `sympy.ntheory.residue_ntheory.polynomial_congruence` and `sympy.polys.galoistools.gf_csolve`. Since the types are different, how about wrapping them and doing the following?

```python
def polynomial_congruence(expr, m):
    coefficients = _valid_expr(expr)
    gf_csolve(coefficients, m)
```

**Comment by asmeurer** [comment]
I agree it would be nice to have public API versions of a lot of functions in ntheory and the polys internals. Some of the duplication that exists between them is just historical, because the ntheory one existed first but the galoistools implementation was done separately so that it was part of the polynomials machinery. I don't think the duplication needs to continue to exist, and for functions like `_polynomial_congruence_prime` that start with an underscore we can just delete them.

**Comment by haru-44** [comment]
Thank you. The remove of `_polynomial_congruence_prime` has been merged.
