### ISSUE TITLE
simplify sometimes does not respect non-commutativity

### ISSUE THREAD

**Issue by akhmerov** [sympy/sympy#25086]
The following code:
```python
import sympy

a, b = sympy.symbols("a, b", commutative=False)
(sympy.exp(sympy.I * a).adjoint() * sympy.exp(sympy.I * b)).simplify()
```
produces `sympy.exp(sympy.I * b) * sympy.exp(-sympy.I * a.adjoint())`, which is a different expression because `a` and `b` are not commutative.

**Comment by varunseth5788** [comment]
(sympy.exp(sympy.I * a).adjoint() * sympy.exp(sympy.I * b)).simplify(noncommutative=True)
i cannot find repository

**Comment by akhmerov** [comment]
Indeed, calling `simplify(noncommutative=True)` produces a correct result. Shouldn't this be the default and the only behavior with noncommutative symbols though?

**Comment by oscarbenjamin** [comment]
> Indeed, calling `simplify(noncommutative=True)` produces a correct result.

No it doesn't:
```python
In [4]: expr.simplify()
Out[4]: 
          †
 ⅈ⋅b  -ⅈ⋅a 
ℯ   ⋅ℯ     

In [5]: expr.simplify(noncommutative=True)
Out[5]: 
          †
 ⅈ⋅b  -ⅈ⋅a 
ℯ   ⋅ℯ 
```
The problem is that here `simplify` calls `.normal()`:
https://github.com/sympy/sympy/blob/ec13c21505bdb192e99653d6c68a73be33cfbcc0/sympy/simplify/simplify.py#L642
That switches the order:
```python
In [6]: expr
Out[6]: 
     †     
 -ⅈ⋅a   ⅈ⋅b
ℯ     ⋅ℯ   

In [7]: expr.normal()
Out[7]: 
          †
 ⅈ⋅b  -ⅈ⋅a 
ℯ   ⋅ℯ 
```
I'm not sure what the purpose of `normal` is but it uses `as_numer_denom()`:
https://github.com/sympy/sympy/blob/ec13c21505bdb192e99653d6c68a73be33cfbcc0/sympy/core/expr.py#L2183-L2201
Either `normal` or `as_numer_denom` should not split apart non-commutatives like this:
```python
In [8]: expr.as_numer_denom()
Out[8]: 
⎛          †⎞
⎜ ⅈ⋅b   ⅈ⋅a ⎟
⎝ℯ   , ℯ    ⎠
```
The notion of numerator and denominator only makes sense in a commutative context because it implies that we do not need to consider the ordering of multiplication. All non-commutatives should be kept in the numerator by `as_numer_denom`. The `Pow.as_numer_denom` method handles that correctly but `exp.as_number_denom()` does not.

The fix is:
```diff
diff --git a/sympy/functions/elementary/exponential.py b/sympy/functions/elementary/exponential.py
index 722c6181fe..5a695850b1 100644
--- a/sympy/functions/elementary/exponential.py
+++ b/sympy/functions/elementary/exponential.py
@@ -63,12 +63,13 @@ def as_numer_denom(self):
         """
         # this should be the same as Pow.as_numer_denom wrt
         # exponent handling
-        exp = self.exp
-        neg_exp = exp.is_negative
-        if not neg_exp and not (-exp).is_negative:
-            neg_exp = exp.could_extract_minus_sign()
-        if neg_exp:
-            return S.One, self.func(-exp)
+        if self.is_commutative:
+            exp = self.exp
+            neg_exp = exp.is_negative
+            if not neg_exp and not (-exp).is_negative:
+                neg_exp = exp.could_extract_minus_sign()
+            if neg_exp:
+                return S.One, self.func(-exp)
         return self, S.One
 
     @property
```
