### ISSUE TITLE
symplify_logic raises TypeError when encountering Contains with FiniteSet

### ISSUE THREAD

**Issue by Flauschbaellchen** [sympy/sympy#25115]
I'm trying to compare a Symbol against a set of pre-defined Strings.
In pure Python I  would write:
```python
x = "something"
y = ["foo", "bar", "baz"]
condition = x in y
```
In sympy I've wrote:
```python
x = Symbol("x")
y = FiniteSet("foo", "bar", "baz")
condition = Contains(x, y)
#=> Contains(x, {bar, baz, foo})
```

This works, however, if I additionally want to simplify this condition (as it is part of a bigger one), the following error is thrown:
```python
>>> simplify_logic(Contains(x, y))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../logic/boolalg.py", line 2841, in simplify_logic
    truthtable = _get_truthtable(v, expr, c)
  File ".../logic/boolalg.py", line 2858, in _get_truthtable
    return [const + k[1] for k in _get_tt([[expr, []]]) if k[0]]
  File ".../logic/boolalg.py", line 2854, in _get_tt
    tab = [[i[0].xreplace({v: false}), [0] + i[1]] for i in inputs if i[0] is not false]
  File ".../logic/boolalg.py", line 2854, in <listcomp>
    tab = [[i[0].xreplace({v: false}), [0] + i[1]] for i in inputs if i[0] is not false]
  File ".../core/basic.py", line 1187, in xreplace
    value, _ = self._xreplace(rule)
  File ".../core/basic.py", line 1209, in _xreplace
    return self.func(*args), True
  File ".../core/cache.py", line 70, in wrapper
    retval = cfunc(*args, **kwargs)
  File ".../core/function.py", line 309, in __new__
    evaluated = cls.eval(*args)
  File ".../sets/contains.py", line 33, in eval
    raise TypeError('expecting Set, not %s' % func_name(s))
TypeError: expecting Set, not BooleanFalse
```

I would have expected to return the statement unchanged (in this case) as it cannot be more simplified.
I've tested it against sympy version 1.11.1 and 1.12rc1.

I'm new to sympy so it is possible that I used the wrong functions to implement my use-case. In this case, please point me to the right direction. Any help is greatly appreciated :bow:

**Comment by oscarbenjamin** [comment]
This is a bug in `simplify_logic`. It thinks that the set `y` is a "variable" that can be replaced by `False` but a set cannot be replaced by a boolean. The problem is here:
https://github.com/sympy/sympy/blob/e0235b4b2681bf8aff8cdf1d1e456653b21dacbd/sympy/logic/boolalg.py#L2743-L2752
Here `Contains` is a `BooleanFunction` so its args are treated as booleans.

There are two possible solutions to this:

1. Make the `_find_predicates` function more sophisticated.
2. Make `Contains` not be a subclass of `BooleanFunction`.

Here is a list of BooleanFunction subclasses:
```console
$ git grep BooleanFunction | grep class
sympy/logic/boolalg.py:class BooleanFunction(Application, Boolean):
sympy/logic/boolalg.py:class And(LatticeOp, BooleanFunction):
sympy/logic/boolalg.py:class Or(LatticeOp, BooleanFunction):
sympy/logic/boolalg.py:class Not(BooleanFunction):
sympy/logic/boolalg.py:class Xor(BooleanFunction):
sympy/logic/boolalg.py:class Nand(BooleanFunction):
sympy/logic/boolalg.py:class Nor(BooleanFunction):
sympy/logic/boolalg.py:class Xnor(BooleanFunction):
sympy/logic/boolalg.py:class Implies(BooleanFunction):
sympy/logic/boolalg.py:class Equivalent(BooleanFunction):
sympy/logic/boolalg.py:class ITE(BooleanFunction):
sympy/logic/boolalg.py:class Exclusive(BooleanFunction):
sympy/sets/contains.py:class Contains(BooleanFunction):
```
Apart from `Contains` it is clear that these all have boolean arguments and are standard boolean functions as described here:
https://en.wikipedia.org/wiki/Boolean_function

The docstring for BooleanFunction is not exactly clear about its meaning:
https://github.com/sympy/sympy/blob/e0235b4b2681bf8aff8cdf1d1e456653b21dacbd/sympy/logic/boolalg.py#L463-L467

I think that the fix is this:
```diff
diff --git a/sympy/sets/contains.py b/sympy/sets/contains.py
index 997a4d8e16..41b91172a8 100644
--- a/sympy/sets/contains.py
+++ b/sympy/sets/contains.py
@@ -1,11 +1,11 @@
 from sympy.core import S
 from sympy.core.relational import Eq, Ne
-from sympy.logic.boolalg import BooleanFunction
+from sympy.logic.boolalg import Boolean
 from sympy.utilities.misc import func_name
 from .sets import Set
 
 
-class Contains(BooleanFunction):
+class Contains(Boolean):
     """
     Asserts that x is an element of the set S.
 
```
