### ISSUE TITLE
Backwards compatibility of future sympy 2.0

### ISSUE THREAD

**Issue by bjodah** [sympy/sympy#25145]
Every now and then there's talk about fixing some outstanding issues in SymPy's design in a future 2.0 release (e.g. @asmeurer comment [here](https://github.com/sympy/sympy/pull/25103#issuecomment-1533863941))

Personally I think it's fine, and even desirable to completely break backwards compatibility in a 2.0 relase since it allows us to simplify the code base (and we should probably already keep a laundry list of things we intend to fix).

But breaking users code is no small thing, and often research projects don't see updates particularly often, making backwards compatible changes even trickier (breakage go unnoticed until some poor PhD student is tasked with reviving the code). I think that there are two possible remedies:

 - either: the new package is named sympy2 (i.e. pip install sympy2 and `import sympy2`)
 - or: we publish a package on PyPI called `sympy1` (i.e. pip install sympy1) **years before** breaking "sympy".

In both approaches it would allow a single environment to have two different installations of sympy installed in parallel and it would allow the user to install legacy packages requiring the old version of sympy as well as newer packages requiring the latest version of sympy.

The pros/cons are from my perspecitve:
1. The first option require no action among down stream projects (and would get my vote as the preferred option). But puts a burden on future teachability/marketing, and it might be confusing that "pip install sympy" installs a legacy version.
2. The second option avoids having to update tutorials etc. to reference `sympy2` instead of `sympy`, but it requires downstream users of the library to start importing `sympy2` instead of `sympy` well ahead of the breaking release. And this will invariably lead to some breaking of user's code, or require people to set version constraints `<2.0` (which eventually leads to version conflicts, and is of little help in my opinion).

I'm opening this ticket now because I think it would be ideal to give a heads up regardless of what the future approach will be (and my suggested option 2 would require action long before the actual 2.0 release). Now I'm interested in hearing what you think: do you agree, or do you think version constraints are enough?

**Comment by sylee957** [comment]
I think that it may better to think of different name than picking sympy2 though.

**Comment by moorepants** [comment]
The only reason to have pypi packages sympy1 and sympy2 as different packages is if someone wants to install both in the same environment. Is that something we would really need to support? Most Python packages don't seem to support such a use case.

**Comment by oscarbenjamin** [comment]
It is always possible to install older versions of sympy to be used with older code if needed. There is no benefit in introducing either sympy1 for "old sympy" or sympy2 for "new sympy" unless we intend to maintain two versions of sympy in parallel. I don't think that we have the capacity to maintain two versions so I suggest that if there is a sympy 2.0 then it is still just called sympy and if someone needs older sympy then they just have to install older sympy.

I think that it is bad PR to put out the idea that there is any intention of having a compatibility breaking version of sympy without a clear idea of what at least some of those changes would be. The new assumptions debacle should make clear that we should not give the impression that anything will happen if we are not very clear that it is possible to complete the implementation. I think this means that any changes should be mostly implemented already before any decision is made that suggests anyone might even consider changing downstream code.

I do agree that sympy will at some point need a 2.0 version but we are miles away from being ready to do it. It is not worth making a big compatibility break just to fix a bunch of small things especially if most of the problems can be resolved without breaking compatibility in a big way. The motivation for a 2.0 version needs to be that there are some fundamental things that cannot otherwise be fixed and we need to be reasonably sure that we are fixing most of the fundamental things that we want to fix so that it should not be necessary to have a 3.0 release that entails similar breakage in future.

Let's take some concrete examples to see what I mean:

The solve function has a badly designed API. It does not have consistent semantics and its return types are value-dependent. There are many ways in which it does not do what users might want but changing it would break compatibility. It would be great to fix solve but:

- We can fix all of the problems with solve just by introducing a new function with a new name like `solve_equations` and where necessary a separate implementation.
- The benefit of a sympy 2.0 would be that at some point we could make it so that `sympy.solve` means the new function rather than the old one so that code that still uses `solve` can benefit from the improvements (if its usage is not broken by the change).
- To be ready to make that transition the new solve function needs to exist already.
- Most of the work to make the new implementation can happen without any compatibility break but until it does happen we are not ready to make this change in sympy 2.0.
- We can (And should) eliminate all usage of `solve` in sympy itself and change the docs to suggest `solve_equations` without breaking compatibility.

By the time that we have done all of these things listed above the question is: what benefit would changing solve in sympy 2.0 bring? If we already have a `solve_equations` function and it works well and is used throughout the codebase and recommended to users then changing the behaviour of solve really just means being precious about the function name. I would say that this is the sort of change that could be made during a sympy 2.0 transition but it does not provide a strong argument for having the 2.0 transition in the first place.

Another example is the design of Basic itself. There are all kinds of problems with the design of Basic and all of the methods that it has and so on. I would like to redesign the whole thing with major changes like not using classes for expression heads and I think that there could be significant benefits from doing so. This sort of change would be significant enough to justify having a big 2.0 release with a compatibility break. However it takes a long time to develop a new implementation of all of these things and so that process needs to take place slowly for a long time before the 2.0 release comes along. Until an alternative implementation exists and is used and tested we are not ready to make that transition in a 2.0 release.

Another example would be `sympify/parse_expr` and the fact that they parse strings in an insecure way. The fact that most sympy functions call `sympify` and it parses strings unsafely is a major problem but it can't be fixed without breaking compatibility for at least some users. This could also be a good justification for a 2.0 release but at the same time I think that it is serous enough that we could fix it without having a 2.0 release. Whether or not we have a 2.0 release is irrelevant though until someone actually writes the new safer parser which could be added as `parse_expr_safe` right now in any case.

To make the 2.0 release a number of things need to be in place:

1. A clear list of some important things that cannot be fixed without a compatibility break.
2. The new behaviour should be implemented so that the 2.0 transition is like flipping a switch.
3. Wherever possible the changes should be provided ahead of time so that new code can opt in to the new behaviour.
4. We need to be reasonably confident that we have collected enough things that should be fixed that we are not just looking at needing a 3.0 release a few years down the line.

Until we have some things meeting the criteria above I don't think we should give any public signal that there is any plan to have a compatibility breaking release.

**Comment by asmeurer** [comment]
Oscar is right that we would first need to have a lengthy discussion about what sorts of things that we would like to actually do in a potential SymPy 2.0. We need a concrete list so that we can understand how reasonable it would be to actually implement the various things, and how important certain changes would be that would require a compatibility break. 

Personally I think the prime focus should be on the core. Other submodules and individual functions can be changed more slowly without hard breaks. The core is also the hardest thing to change, so we really need to decide what we want to do and figure out if it's in any way feasible. It may also, I suspect, require us obtaining some funding to achieve the work.

I'm -1 to adding a number to the package name (sympy2). Whenever I've seen packages do that, they've ended up regretting it (see for instance pymc2, which is now just pymc again). The problem you're describing is exactly the one that version numbers are designed to solve, so we should just indicate the difference using a version number.

It's a good idea to take a look at the current discussions happening in NumPy and SciPy to move to 2.0 versions (with some compatibility breaks and cleanups). I am following both and will be interested to see just how successful they are.

**Comment by moorepants** [comment]
Is the only reason to do sympy1 and sympy2 so you can install them both in the same environment? It would be nice to see a use case where that is needed before forgoing using normal versioning.

**Comment by bjodah** [comment]
I did not know that "pymc2" naming scheme was abandoned by that project (looks like there's pymc2 & pymc3, and now with version 4 it's called pymc again).

@moorepants, yes, my idea was that allowing parallel installs would allow for a graceful transition. But given @oscarbenjamin's vision (especially point 2 & 3) I think I've been persuaded that multiple PyPI packages aren't necessary.

@asmeurer regarding that this is what version numbers is "designed to solve", I do agree, but that means that some projects might have to put upper constraints (which some consider to be [bad practice](https://iscinumpy.dev/post/bound-version-constraints/)) during a transition period . But if there's a transition period where downstream packages can test "sympy-2.0" behavior (e.g. by setting some environment variable), then perhaps most projects can reassure themselves that they need not specify any such constraints, and those who will need it will have time to get a release out with the constraint set (`sympy<2`).

Thank you for your input. From my point of view, we can close this issue.
