### ISSUE TITLE
Incorrect evaluation of integer and real equality.

### ISSUE THREAD

**Issue by ysiraichi** [sympy/sympy#25146]
```python
>>> f = Symbol("f", real=True)
>>> i = Symbol("i", integer=True)

>>> Eq(f, 3.0)
Eq(f, 3.0)

>>> Eq(i, 3.0)
False
```

Isn't the last one also supposed to be: `Eq(i, 3.0)`?

Version: 1.11.1

**Comment by asmeurer** [comment]
We have

```py
>>> S(3.0).is_integer
False
```

which supports this. But I'm not sure if it's a good idea. We also have

```py
>>> S(0.0).is_zero
True
```

which would seem to contradict this. 

It leads to things like

```py
>>> Eq(Symbol("x", integer=True) / 6, 0.5)
False
```

But note that the equality is true if `x` is `3`. It does it because the rhs is a float, but we also have

```py
>>> Eq(S(1)/2, 0.5)
True
```

**Comment by asmeurer** [comment]
This is also tied to the whole https://github.com/sympy/sympy/issues/11707 mess. 

We also explicitly set is_rational to None for all floats, but integer -> rational. We even have

```py
>>> print(S(0.0).is_rational)
None
>>> print(S(0.0).is_integer)
True
```

which seems bad (it is manually bypassing the assumptions deductions). 

I remember a lot of discussions about how setting Float.is_rational to None was to avoid invalid deductions, but it seems to me that making explicitly integral floats not is_integer also leads to invalid deductions. 

And special-casing 0.0 is also contradictory, and leads to problems. For example, 

```py
>>> x = Symbol('x', integer=True)
>>> (x - 3.0).is_zero
False
>>> (x - 3.0).subs(x, 3).is_zero
True
```

This also doesn't touch the question of floats that are integral but do not represent an exact integer due to their magnitude being larger than their precision (e.g., `Float(1e100, 15)`).

**Comment by asmeurer** [comment]
This was fixed with https://github.com/sympy/sympy/pull/25875
