### ISSUE TITLE
Series expansion not working

### ISSUE THREAD

**Issue by RagonEbker** [sympy/sympy#25165]
Hello,

In our project we use very large functions and a lot of series expansions throw a "not implemented error". I managed to extract a relatively simple case:

`(1/sqrt(( - y + 1)**2 + (y - 0.23)**4)).series(y,x0=0,n=5)`

When using `apart()` the series expansion works: 

`apart((1/sqrt(( - y + 1)**2 + (y - 0.23)**4))).series(y,x0=0,n=5)`

sadly its not that easy with our larger functions. Any ideas or am I missing something fundamental? 

The error is: 

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.local/lib/python3.10/site-packages/sympy/core/expr.py", line 3026, in series
    rv = self.subs(x, xpos).series(xpos, x0, n, dir, logx=logx, cdir=cdir)
  File "/home/user/.local/lib/python3.10/site-packages/sympy/core/expr.py", line 3034, in series
    s1 = self._eval_nseries(x, n=n, logx=logx, cdir=cdir)
  File "/home/user/.local/lib/python3.10/site-packages/sympy/core/power.py", line 1758, in _eval_nseries
    raise NotImplementedError()
NotImplementedError`

**Comment by anutosh491** [comment]
Hey @RagonEbker thanks for reporting this issue. We actually have the necessary tools to address the above case. 

The problem lies here https://github.com/sympy/sympy/blob/aa6db7c688855c181e020929dd34b9639dec64ad/sympy/core/power.py#L1581-L1586

Let's say we want to calculate the series for `(1/sqrt(( - y + 1)**2 + (y - 0.6)**4))`

Hence we encounter a terms `g` which is the following 
```
>>> g
0.885269121813031*(y - 1)**2 + 0.885269121813031*(y - 0.6)**4 - 1.0
```

If we look at this term the constant term here is S.Zero or rather there is no constant term
```
>>> g = 0.885269121813031*(y - 1)**2 + 0.885269121813031*(y - 0.6)**4 - 1.0
>>> (0.885269121813031*(y - 1)**2).expand()
0.885269121813031*y**2 - 1.77053824362606*y + 0.885269121813031
>>> (0.885269121813031*(y - 0.6)**4).expand()
0.885269121813031*y**4 - 2.12464589235127*y**3 + 1.91218130311615*y**2 - 0.764872521246459*y + 0.114730878186969
>>> 0.885269121813031 + 0.114730878186969 - 1.0
0.0
```

But if we calculate the leading term for `g`, we get a constant due to a rounding off error.
```
>>> g.as_leading_term(y)
-2.22044604925031e-16
```
This leads to the wrong answer. @oscarbenjamin what can be done here ? We have all the tools necessary. We just need to expand/simplify `g` such that the constant terms goes to 0 rather than returning a float

**Comment by oscarbenjamin** [comment]
I think that `nsimplify` is being called in the wrong place. It is already too late because rounding errors have already happened and so after `nsimplify` the constant term is still not found to be zero.

If this is going to use `nsimplify` to handle floats then it needs to be done right at the beginning of the calculation. Otherwise everything needs to be designed to handle floats throughout.

**Comment by anutosh491** [comment]
cc @arnabnandikgp 
As you've been contributing to the series module these days, you might be interested in picking up this issue. We have all the tools required to solve this though we are making some mistakes with simplyfing things.

**Comment by arnabnandikgp** [comment]
Since the soul purpose of the following code 
https://github.com/sympy/sympy/blob/aa6db7c688855c181e020929dd34b9639dec64ad/sympy/core/power.py#L1581-L1586 
is to make sure that the constant term is removed if haven't been removed already as intended here
https://github.com/sympy/sympy/blob/aa6db7c688855c181e020929dd34b9639dec64ad/sympy/core/power.py#L1535
but as realised that rounding off error and use of nsimplify() is complicating things with floats thus I tried the following simple diff as a way to directly negate the constant term followed by division thus not requiring the code block so as to ensure removal of constant term.
```
diff --git a/sympy/core/power.py b/sympy/core/power.py
index 2298520926..8ad36547ff 100644
--- a/sympy/core/power.py
+++ b/sympy/core/power.py
@@ -1532,7 +1532,8 @@ def _eval_nseries(self, x, n, logx, cdir=0):
                 return res
 
         f = b.as_leading_term(x, logx=logx)
-        g = (b/f - S.One).cancel(expand=False)
+        g=(b.expand()-f).simplify()
+        g=(g/f)
         if not m.is_number:
             raise NotImplementedError()
         maxpow = n - m*e
@@ -1578,12 +1579,7 @@ def mul(d1, d2):
                 return f**e + e*f**e*g  # first term of binomial series
             else:
                 raise NotImplementedError()
-        if c.is_Float and d == S.Zero:
-            # Convert floats like 0.5 to exact SymPy numbers like S.Half, to
-            # prevent rounding errors which can induce wrong values of d leading
-            # to a NotImplementedError being returned from the block below.
-            from sympy.simplify.simplify import nsimplify
-            _, d = nsimplify(g).leadterm(x, logx=logx)

```
I ran all the tests locally and everything is fine(along with all the expected results for this issue).

**Comment by arnabnandikgp** [comment]
I was toggling through the git history of the associated lines and realised that the code block 
https://github.com/sympy/sympy/blob/aa6db7c688855c181e020929dd34b9639dec64ad/sympy/core/power.py#L1581-L1586 
was added through #22213  in order to handle the very same negation problems that we are trying to handle in this case but it worked then as the failing test cases weren't beyond the limits of nsimplify(which is 10**-15) but in this example we presumably exceeded that causing us problems.

**Comment by smichr** [comment]
`nsimplify` should not be used unconditionally like this (at lines 1581ff). Instead a replacement of only floats representable as fractions with a power of 2 denominator should be replaced (as expressed in the inline): `expr.replace(lambda x: x.is_Float and x.is_same(Rational(x), equal_valued), lambda x: Rational(x))`. If you don't do this then a high precision float might be converted to a close exact transcendental expression.
