### ISSUE TITLE
Timeout for solve(Eq((x - 5)**(-8), 3), x)

### ISSUE THREAD

**Issue by satels** [sympy/sympy#25176]
```python
from sympy import Symbol, solve, Eq

x = Symbol('x')
solve(Eq((x - 5)**(-8), 3), x)
```

version of sympy is 1.12

**Comment by satels** [comment]
But

```python
solve(Eq(x**(-8), 3), x)
```

has result and is fast:

```python
[-3**(7/8)/3, 3**(7/8)/3, -3**(7/8)*I/3, 3**(7/8)*I/3, -sqrt(2)*3**(7/8)/6 - sqrt(2)*3**(7/8)*I/6, -sqrt(2)*3**(7/8)/6 + sqrt(2)*3**(7/8)*I/6, sqrt(2)*3**(7/8)/6 - sqrt(2)*3**(7/8)*I/6, sqrt(2)*3**(7/8)/6 + sqrt(2)*3**(7/8)*I/6]

```

**Comment by oscarbenjamin** [comment]
This hangs in `Mul.flatten`:
```python
sqrt(-4*3**(S(3)/4)*I/3)
```
It seems to go into an infinite loop here:
https://github.com/sympy/sympy/blob/e2cadc140cc969fea038240a39961a66a2f3dd6d/sympy/core/mul.py#L579-L622

I'm not sure why the code in that loop is so complicated. If I understand its purpose then I think that there should be a much simpler way to write it. I think it's basically the factor basis from https://github.com/sympy/sympy/issues/22852#issuecomment-1013996890 except with rationals instead of integers.

**Comment by oscarbenjamin** [comment]
The example from gh-24146 is the same bug:
```
(25*3**(S.One/3)/4)**(S.One/4)  # hangs in Mul.flatten
```
