### ISSUE TITLE
Weird inaccuracies when `real=True`

### ISSUE THREAD

**Issue by 25pwn** [sympy/sympy#25209]
```py
import sympy

def involute(
		c : sympy.S = sympy.Matrix([]), 
):
	t = sympy.Symbol('t')
	w = sympy.Symbol('w')
	a = sympy.Symbol('a')

	C = c - c.diff(t) / c.diff(t).norm() * sympy.integrate( c.subs(t, w).diff(w).norm() , (w, a, t) )

	return C

def param():
	f_t = sympy.S("Matrix([cos(t), sin(t)])")

	print(sympy.latex(involute(f_t)))

param()
```
When run, this returns $$\left[\begin{matrix}\cos{\left(t \right)} + \frac{\sin{\left(t \right)} \int\limits_{a}^{t} \sqrt{\left|{\sin{\left(w \right)}}\right|^{2} + \left|{\cos{\left(w \right)}}\right|^{2}}\, dw}{\sqrt{\left|{\sin{\left(t \right)}}\right|^{2} + \left|{\cos{\left(t \right)}}\right|^{2}}}\\\sin{\left(t \right)} - \frac{\cos{\left(t \right)} \int\limits_{a}^{t} \sqrt{\left|{\sin{\left(w \right)}}\right|^{2} + \left|{\cos{\left(w \right)}}\right|^{2}}\, dw}{\sqrt{\left|{\sin{\left(t \right)}}\right|^{2} + \left|{\cos{\left(t \right)}}\right|^{2}}}\end{matrix}\right]$$

However, when I add `real=True` to the symbols:
```py
import sympy

def involute(
		c : sympy.S = sympy.Matrix([]), 
):
	t = sympy.Symbol('t', real=True)
	w = sympy.Symbol('w', real=True)
	a = sympy.Symbol('a', real=True)

	C = c - c.diff(t) / c.diff(t).norm() * sympy.integrate( c.subs(t, w).diff(w).norm() , (w, a, t) )

	return C

def param():
	f_t = sympy.S("Matrix([cos(t), sin(t)])")

	print(sympy.latex(involute(f_t)))

param()
```
it returns 
$$\left[\begin{matrix}\cos{\left(t \right)}\\\sin{\left(t \right)}\end{matrix}\right]$$
which is obviously not right. It should be 

$$\begin{align*}
& \left[\begin{matrix}\cos{\left(t \right)} + \frac{\sin{\left(t \right)} \int\limits_{a}^{t} \sqrt{\left|{\sin{\left(w \right)}}\right|^{2} + \left|{\cos{\left(w \right)}}\right|^{2}}\, dw}{\sqrt{\left|{\sin{\left(t \right)}}\right|^{2} + \left|{\cos{\left(t \right)}}\right|^{2}}}\\\sin{\left(t \right)} - \frac{\cos{\left(t \right)} \int\limits_{a}^{t} \sqrt{\left|{\sin{\left(w \right)}}\right|^{2} + \left|{\cos{\left(w \right)}}\right|^{2}}\, dw}{\sqrt{\left|{\sin{\left(t \right)}}\right|^{2} + \left|{\cos{\left(t \right)}}\right|^{2}}}\end{matrix}\right] \\

& =\left[\begin{matrix}\cos{\left(t \right)} + \left( t - a \right)\sin(t)\\\sin{\left(t \right)} - \left(t - a \right)\cos(t)\end{matrix}\right]

\end{align*}$$

Why does this happen?

**Comment by asmeurer** [comment]
The problem is that you are creating the expression `Matrix([cos(t), sin(t)])` as a string. When you do this, it creates symbols for all the unknown variables in the expression without any assumptions. So the `t` created in this expression does not have the `real` assumptions, meaning SymPy treats it as a distinct symbol from `Symbol('t', real=True)`. 

I recommend avoiding creating expressions from strings. It is better to define your symbols once, and create all expressions using those symbols, like

```py
t = sympy.Symbol('t', real=True)
w = sympy.Symbol('w', real=True)
a = sympy.Symbol('a', real=True)

def involute(c): 
	C = c - c.diff(t) / c.diff(t).norm() * sympy.integrate( c.subs(t, w).diff(w).norm() , (w, a, t) )

	return C

involute(Matrix([cos(t), sin(t)]))
```

This returns (after simplification):

$$\left[\begin{matrix}\left(- a + t\right) \sin{\left(t \right)} + \cos{\left(t \right)}\\\\ \left(a - t\right) \cos{\left(t \right)} + \sin{\left(t \right)}\end{matrix}\right]$$

If you must create an expression from a string, you will need to pass in a dictionary of the symbols you want to be used, like

```py
sympify("Matrix([cos(t), sin(t)])", {"a": a, "w": w, "t": t})
```
