### ISSUE TITLE
Get solve to solve a simple set of equalities

### ISSUE THREAD

**Issue by epa095** [sympy/sympy#25250]
I am trying to use sympy solve to handle a case where I have a set of equalities, and for different situations I know varying number of variables, and want to see if I can use the set of equalities to solve for the missing variables. 

For example
```python
equalities =  [Eq(x, y*1.7), Eq(y * 1.7, z/5), Eq(z/5, x)]
solve( equalities, [x,z], dict=True)
```
gives 
` [{x: 1.7*y, z: 8.5*y}]` which is nice.

But
```python
equalities =  [Eq(x, y*1.7), Eq(y * 1.7, z/5), Eq(z/5, x)]
solve( equalities, [z], dict=True)
```
gives `[]`, even though z can be expressed in terms of the other variables. So how to express the case where I know x and y, but not z, and want to solve the set of equations to get a solution for z? Am I maybe using it wrong?

**Comment by oscarbenjamin** [comment]
> So how to express the case where I know x and y, but not z, and want to solve the set of equations to get a solution for z?

What does it mean that you "know x and y"? If you know concrete values for x and y then you can substitute those in and then the equations will be known to be consistent:
```python
In [24]: eqs =  [Eq(x, y*1.7), Eq(y * 1.7, z/5), Eq(z/5, x)]

In [25]: xval = 1.7

In [26]: yval = 1

In [27]: eqs2 = [eq.subs({x:xval, y:yval}) for eq in eqs]

In [28]: for eq in eqs2: print(eq)
True
Eq(1.7, z/5)
Eq(z/5, 1.7)

In [29]: solve(eqs2, z)
Out[29]: {z: 8.5}
```
If you mean that you want to keep x and y as symbols then what should the answer for z be? There is not a unique answer because of the implied relationship between x and y:
```python
In [30]: solve(eqs[1], z)
Out[30]: [8.5⋅y]

In [31]: solve(eqs[2], z)
Out[31]: [5⋅x]
```
Which of those would you want?

If you allow either x or y to be one of the unknowns then you can get an answer for z in terms of the other as you noted:
```python
In [32]: solve(eqs, [x, z])
Out[32]: {x: 1.7⋅y, z: 8.5⋅y}

In [33]: solve(eqs, [y, z])
Out[33]: {y: 0.588235294117647⋅x, z: 5.0⋅x}
```

**Comment by epa095** [comment]
Thanks for your great answers @oscarbenjamin ! While I am trying to fully comprehend the first, I can answer the very concrete questions in the last!

I do not have concrete values for x and y, I want to keep them as symbols. But I want to generate a forumla for `z` which I can use later when I DO have concrete values for x and y (I will then be in a context where I can not use sympy). So I want to generate a formula for z in terms of x and y. 

This is only an example though, in general I have 
1: A bunch of truths $eqs$, all **equalities** between formulas of some variable set $var$ 
2: I have two sets, $var_{known} \subseteq var$, and $var_{unknown} \subseteq var$ where $var_{known} \cap var_{unknown} = \emptyset$ and  $var_{known} \cup var_{unknown} = var$.

And I am trying to figure out, for each $var \in  var_{unknown}$ **if** it can be expressed as some forumla using only variables from $var_{known}$, and if so, I want one of those forumlas (I dont care which one).

In the last example above, we have that $var_{known} = \\{ x,y\\}$ and $var_{unknown} =  \\{ z\\}$. 

If I can use the function `solve`, which I thought I did, I have problems figuring out what parameters to use in the generall case where $eqs$ can be many equations, and $var$ is larger than 3.

**Comment by oscarbenjamin** [comment]
What you haven't said is anything about the form of the equations. Your examples are very simple two term linear equalities with float coefficients (it would be better to avoid floats for a problem like this though). More generally are the equations linear? Or are they polynomial? (Note that linear equations are also a special case of polynomial equations.)

Assuming that your equations are all polynomial in all variables then I would approach this using Groebner bases. A Groebner basis is a way of rearranging and reducing some polynomial equations rather than directly attempting to solve explicitly for the variables.

A Groebner basis is constructed from some polynomials with respect to an ordering of the variables. The ordering is used to determine which variables should be expressed in terms of which others. For example:
```python
In [52]: for p in groebner(eqs, [x, y, z]): pprint(Eq(p, 0))
1.0⋅x - 0.2⋅z = 0
1.0⋅y - 0.117647058823529⋅z = 0
```
Here the first equation expresses x in terms of y and z. Then the second equation expresses y in terms of z. If you want to express z in terms of x and y then z should be the first symbol in the ordering:
```python
In [53]: for p in groebner(eqs, [z, x, y]): pprint(Eq(p, 0))
-8.5⋅y + 1.0⋅z = 0
1.0⋅x - 1.7⋅y = 0
```
Now the first equation gives z in terms of x and y. In this case x does not appear because it can be eliminated.

The ordering that you would want will be to have the "unknown" variables followed by the "known" variables.

To avoid floats:
```python
In [55]: eqs2 = [nsimplify(eq) for eq in eqs]

In [56]: eqs2
Out[56]: 
⎡    17⋅y  17⋅y   z  z    ⎤
⎢x = ────, ──── = ─, ─ = x⎥
⎣     10    10    5  5    ⎦

In [57]: for p in groebner(eqs2, [z, y, x]): pprint(Eq(p, 0))
-5⋅x + z = 0
  10⋅x        
- ──── + y = 0
   17  
```
You can split the output of the Groebner basis into two parts. The first part is all of the equations that involve the "unknown" variables. Typically this will be the first n equations where n is the number of unknown variables but if the equations are underdetermined then this might not be the case. Those first equations are the ones that you are interested in and can be solved (e.g. with solve, linsolve etc) for the unknowns in terms of the other variables. 

The second part is the equations involving only the "known" variables. Those express consistency conditions for the values of those known variables. If the consistency conditions are not satisfied then there are no possible values of the "unknown" variables that could satisfy the equations. It is up to you whether you want to keep or discard these equations.

A possible approach then looks like this:
```python
In [58]: eqs =  [Eq(x, y*Rational('1.7')), Eq(y * Rational('1.7'), z/5), Eq(z/5, x)]

In [59]: eqs
Out[59]: 
⎡    17⋅y  17⋅y   z  z    ⎤
⎢x = ────, ──── = ─, ─ = x⎥
⎣     10    10    5  5    ⎦

In [60]: unknowns = [z]

In [61]: knowns = [x, y]

In [62]: gb = groebner(eqs, unknowns + knowns)

In [63]: gb
Out[63]: 
             ⎛⎡  17⋅y          17⋅y⎤                              ⎞
GroebnerBasis⎜⎢- ──── + z, x - ────⎥, z, x, y, domain=ℚ, order=lex⎟
             ⎝⎣   2             10 ⎦                              ⎠

In [64]: eqs_unknowns = [eq for eq in gb if eq.has(*unknowns)]

In [65]: eqs_unknowns
Out[65]: 
⎡  17⋅y    ⎤
⎢- ──── + z⎥
⎣   2      ⎦

In [66]: solve(eqs_unknowns, unknowns, dict=True)
Out[66]: 
⎡⎧   17⋅y⎫⎤
⎢⎨z: ────⎬⎥
⎣⎩    2  ⎭⎦
```

**Comment by smichr** [comment]
> You can split the output of the Groebner basis into two parts. The first part is all of the equations that involve the "unknown" variables. 

That's an important concept that we should be sure is in the documentation. It might be worth having a flag so this separation can be done automatically.

**Comment by epa095** [comment]
Thanks @oscarbenjamin , great explanation. It seems like the combination of groebner and solve will do the trick. Thanks!
