### ISSUE TITLE
Quaternions in version 12

### ISSUE THREAD

**Issue by singladur** [sympy/sympy#25254]
Dear friends,
I have detected a problem when multiplying Quaternions using the * to do the product between two.  It also fails when using q.mul(p).  In my case, one of the quaternions was obtained by the "from Axis angle". This code gives me problems:

`p= Quaternion(1,0,1,0);
q = Quaternion.from_axis_angle((1,1,1), 3*np.pi/4);
qi =q.inverse();
p1= q*p*qi `

The error is not there for any previous versions 11.x.

Many thanks for considering my request.

**Comment by oscarbenjamin** [comment]
CC @evbernardes 

```python
In [3]: p= Quaternion(1,0,1,0); q = Quaternion.from_axis_angle((1,1,1), 3*np.pi/4); qi =q.inverse()

In [4]: q*p
---------------------------------------------------------------------------
ValueError: Incompatible value for norm.
```

**Comment by evbernardes** [comment]
Hello @singladur. I think the bug itself comes from `3*np.pi/4` line, since the used value or `pi` is the numerical value from `numpy`. Changing it to `3*sympy.pi/4` would solve it.

This shouldn't be a big deal though though, so I'd say it's more of a **design fault from my part**.

To remove this problem from the `Sympy` source, this:
```python
def norm(self):
    if self._norm is None:  # check if norm is pre-defined
        q = self
        self._norm = sqrt(trigsimp(q.a**2 + q.b**2 + q.c**2 + q.d**2))

    return self._norm
```
Can be changed to this:

```python
def norm(self):
    if self._norm is None:  # check if norm is pre-defined
        q = self
        return sqrt(trigsimp(q.a**2 + q.b**2 + q.c**2 + q.d**2))

    return self._norm
```
Since removing this lazy calculation and storage of the norm value would avoid forcing the `norm` attritube in every `Quaternion`, except when explicitly asked.

@oscarbenjamin If this is okay for you as an edit I can push this, except if you plan on something else, like removing the norm system entirely, like we were discussing some months ago.
