### ISSUE TITLE
How to print x*dx + (x - y)*dy as is

### ISSUE THREAD

**Issue by satels** [sympy/sympy#25289]
Now:
![image](https://github.com/sympy/sympy/assets/220572/4fd1bf4b-463b-4a65-a17c-f62ae4464a32)

Can i ask similar questions via other way of types of communication ?

**Comment by smichr** [comment]
look for any issue with keywords "custom printer print order"

**Comment by oscarbenjamin** [comment]
> Can i ask similar questions via other way of types of communication ?

You can use the mailing list. It is not useful to have an open GitHub issue unless it is clear that something in SymPy should be changed.

**Comment by sylee957** [comment]
Unfortunately, I don't think that sympy Expr should be responsible for ordering of printers.

If you need differential form, you need to look features like diffgeom, vectors or define customized objects with printers, rather than expecting SymPy to do work for you (even if it does, it won't be reliable than designing what is dedicated for that by yourself)
