### ISSUE TITLE
The signs of real Gaunt coefficients are not consistent with the given documentation

### ISSUE THREAD

**Issue by jinzx10** [sympy/sympy#25321]
The documentation of real_gaunt (https://docs.sympy.org/latest/modules/physics/wigner.html) says the definition of real spherical harmonics follows

Some Properties of the Coupling Coefficients of Real Spherical Harmonics and Their Relation to Gaunt Coefficients’, H. H. H. Homeier and E. O. Steinborn J. Mol. Struct., Volume 368, pp. 31-37 (1996)

where the real spherical harmonics Z(l,m) is defined as

Z(l,m)   
= sqrt(2) * Re Y(l, |m|)   if m > 0
= Y(l,0)                          if m = 0
= sqrt(2) * Im Y(l, |m|)   if m < 0

Following this definition, 

Z(1, -1) = sqrt(2) * (-sqrt(3/2/pi) / 2) * sin(theta) * sin(phi)
Z(1,  1) = sqrt(2) * (-sqrt(3/2/pi) / 2) * sin(theta) * cos(phi)
Z(2, -2) = sqrt(2) * ( sqrt(15/2/pi) / 4) * [sin(theta)]^2 * sin(2*phi)

and the real Gaunt coeffcient of the above three is calculated to be sqrt(15/pi) / 10. However, the result from sympy has an extra minus sign:

```
>>> from sympy.physics.wigner import real_gaunt
>>> real_gaunt(1,1,2,-1,1,-2)
-sqrt(15)/(10*sqrt(pi))
>>>
```

Similar problem happens to many real Gaunt coefficients with 2 negative m's.  Is there a bug or do I misunderstand something?

**Comment by Sunethan** [comment]
I have similar observations. The calculation results seem to be incorrect.

<img width="1040" alt="Screenshot 2023-08-11 at 6 22 08 PM" src="https://github.com/sympy/sympy/assets/32844256/a0b66f4e-4d9f-49f6-ba3c-fe6ef0bd8f0e">

This function is based on the formula shown above. As you can see on the right, the red box doesn't look correct. That should be the blue box below in the "Some Properties of the Coupling Coefficients of Real Spherical Harmonics and Their Relation to Gaunt Coefficients’, H. H. H. Homeier and E. O. Steinborn J. Mol. Struct., Volume 368, pp. 31-37 (1996)".
<img width="910" alt="Screenshot 2023-08-11 at 6 25 34 PM" src="https://github.com/sympy/sympy/assets/32844256/64f57da1-9615-4ede-b3d8-bc7ff7dc4733">

```
kron_del = lambda i, j: 1 if i == j else 0
s = lambda e: -1 if e % 2 else 1  #  (-1)**e to give +/-1, avoiding float when e<0
A = lambda a, b: (-kron_del(a, b)*s(a-b) + kron_del(a, -b)* s(b)) if b < 0 else 0
```

The term `kron_del(a,b)*s(a-b)` is strange, because it is simply one if a equals b and if so, then why don't we simply write `kron_del(a,b)`? So I think there is something wrong with the code. 

Below is my source code based on the (complex) gaunt of Sympy. 

```
def Real_Gaunt_v2(l1, l2, l3, mu1, mu2, mu3, prec=3):
    kron_del = lambda i, j: 1 if i == j else 0
    s = lambda e: -1 if e % 2 else 1  # (-1)**e to give +/-1, avoiding float when e<0
    t = lambda x: 1 if x > 0 else 0
    A = lambda mu, m: t(-mu) * (s(m) * kron_del(m, mu) - kron_del(m, -mu))
    B = lambda mu, m: t(mu) * (kron_del(m, mu) + s(m) * kron_del(m, -mu))
    U = lambda mu, m: kron_del(abs(mu), abs(m)) * (kron_del(mu, 0) * kron_del(m, 0) + (B(mu, m) + 1j * A(mu, m))/np.sqrt(2))

if (l1 + l2 + l3) % 2:
        return 0  ## if odd then zero
    if sum(1 for i in (mu1, mu2, mu3) if i < 0) % 2:
        return 0  # odd number of negative m
    ugnt = 0
    for m1 in range(-l1, l1 + 1):
        U1 = U(mu1, m1)
        for m2 in range(-l2, l2 + 1):
            U2 = U(mu2, m2)
            U3 = U(mu3, -m1 - m2)
            ugnt = ugnt + (U1 * U2 * U3).real * gaunt(l1, l2, l3, m1, m2, -m1 - m2, prec)
    return ugnt
```
Below are the discrepancies between these two codes. Most of the results are the same except for ones like below.
```
Old: -2.185e-01, New: 2.185e-01 (l1: 1, l2: 1, l3: 2, m1: -1, m2: 1, m3: -2)
Old: -2.185e-01, New: 2.185e-01 (l1: 1, l2: 2, l3: 1, m1: -1, m2: -2, m3: 1)
Old: -2.185e-01, New: 2.185e-01 (l1: 1, l2: 1, l3: 2, m1: 1, m2: -1, m3: -2)
Old: -2.185e-01, New: 2.185e-01 (l1: 1, l2: 2, l3: 1, m1: 1, m2: -2, m3: -1)
Old: -2.185e-01, New: 2.185e-01 (l1: 2, l2: 1, l3: 1, m1: -2, m2: -1, m3: 1)
Old: -2.185e-01, New: 2.185e-01 (l1: 2, l2: 1, l3: 1, m1: -2, m2: 1, m3: -1)
Old: -1.561e-01, New: 1.561e-01 (l1: 2, l2: 2, l3: 2, m1: -2, m2: -1, m3: 1)
Old: -1.561e-01, New: 1.561e-01 (l1: 2, l2: 2, l3: 2, m1: -2, m2: 1, m3: -1)
Old: -1.561e-01, New: 1.561e-01 (l1: 2, l2: 2, l3: 2, m1: -1, m2: -2, m3: 1)
Old: -1.561e-01, New: 1.561e-01 (l1: 2, l2: 2, l3: 2, m1: -1, m2: 1, m3: -2)
Old: -1.561e-01, New: 1.561e-01 (l1: 2, l2: 2, l3: 2, m1: 1, m2: -2, m3: -1)
Old: -1.561e-01, New: 1.561e-01 (l1: 2, l2: 2, l3: 2, m1: 1, m2: -1, m3: -2)
```

**Comment by strawpants** [comment]
OK, although this is more than a year old, I also encountered similar problems when using sympy as a validation for another real Gaunt implementation. 

I've used parts of your code @Sunethan to create the above pull request for sympy. 

There is a possibility to add more tests, in case you know more cases for which you know the analytical answer. The case from @jinzx10 was actually already included in the test cases but with the wrong sign.
