### ISSUE TITLE
Integral((a/sqrt(x**2+a**2))**3,(x)) returns incorrect/improper form

### ISSUE THREAD

**Issue by WGNettles** [sympy/sympy#2537]
Solving a distributed uniform line charge electric field problem in electrostatics yields the integral 
`Integral((a/sqrt(x**2+a**2))**3,(x,-l,l))`  where the line charge of length 2l is on the x-axis, centered at the origin and the point of interest is at (0,a).  When running this integral the value returned is 0, which is incorrect.

When I run `Integral((a/sqrt(x**2+a**2))**3,(x))` the return is
`a/sqrt(a**2/x**2 + 1)`. This is totally incorrect. There should be an a in the denominator. When I run `a*Integral((1/sqrt(x**2+a**2))**3,(x))`  I get `1/(a*sqrt(a**2/x**2 + 1))` which might seem algebraically correct, but it is an incorrect form for evaluating the integral at the limits due to the possibility of differing signs in the limits of the integral. The correct form should be
`x/(a*sqrt(x**2+a**2)`.

Code:

``` py
from sympy import *
x,a,l=symbols('x a l')

fieldy=Integral((a/sqrt(x**2+a**2))**3,(x,-l,l))
print fieldy.doit() #this is the wrong answer

fieldy=Integral((a/sqrt(x**2+a**2))**3,(x))
print fieldy.doit() #this is incorrect completely

fieldy=a*Integral((1/sqrt(x**2+a**2))**3,(x))
print fieldy.doit() #this form will not evaluate properly at limits

```

**Comment by Shekharrajak** [comment]
@asmeurer ,Do you have any suggestions/ideas to solve this ?

**Comment by jksuom** [comment]
The indefinite integral given by the development version is ``1/(a*sqrt(a**2/x**2 + 1))``, which is formally correct. To compute definite integrals, one has to take the negative branch of the square root for negative arguments and the positive branch for positive arguments ``x``.

**Comment by Shekharrajak** [comment]
Thanks @jksuom

**Comment by jksuom** [comment]
Perhaps I should add that this is a manifestation of a general problem in the computation of definite integrals. In many cases, an indefinite integral is multivalued. To compute definite integrals one has to be able to choose suitable branches of such functions. There does not seem to be an easy way to do this in general.There is currently no algorithm for this in SymPy. 

In some cases it may be possible to express an indefinite integral in terms of the same multivalued functions that are in the original integrand. Then it may be possible to use the same branches both for the integrand and the indefinite integral. For example, in this particular case one can rewrite the indefinite integral in the form ``x/(a*sqrt(x**2 + a**2))``, and the same positive principal branch of the square root can be used.

However, in many cases the integral function may be multivalued with infinitely many branches even if the integrand is single-valued. For example,
```
>>> integrate(1/(2 + cos(x)), x)
-sqrt(3)*I*log(tan(x/2) - sqrt(3)*I)/3 + sqrt(3)*I*log(tan(x/2) + sqrt(3)*I)/3
```
Here the logarithms have an infinite number of branches that differ from each other by multiples of ``2*pi*I``. (The result can be expressed in terms of real-valued inverse trigonometric functions, but it appears that SymPy's integrator does not currently do this.) It is hard to choose correct branches for computing definite integrals. One solution might be splitting the integration interval into small pieces so that the same branch could be used at both end points of each piece, and then combining the parts.

**Comment by asmeurer** [comment]
There is work in the literature on avoiding branch cuts in the integral that didn't exist in the integrand, at least for the Risch algorithm.

**Comment by Shekharrajak** [comment]
```
>>> from sympy import *
>>> x,a,l=symbols('x a l')
>>> fieldy=Integral((a/sqrt(x**2+a**2))**3,(x,-l,l))
>>> print fieldy.doit()
0
```
 Ans should be :  (2*a)/(sqrt(a**2+1))
```
>>> fieldy=Integral((a/sqrt(x**2+a**2))**3,(x))
>>> print fieldy.doit()
a/sqrt(a**2/x**2 + 1)
```
 Ans should be : (a*x)/(sqrt(a**2+x**2))

```
>>> fieldy=a*Integral((1/sqrt(x**2+a**2))**3,(x))
>>> print fieldy.doit()
1/(a*sqrt(a**2/x**2 + 1))
```
 Ans should be : a*(a*x)/(sqrt(a**2+x**2))


It seems it is executing for : 
```
Integral(a**3/(a**2 + x**2)**(3/2), x) rahter than 1/sqrt(x**2+a**2))**3
```
It seems little difficult.I didn't understand how it is executing and why it becomes `a**3/(a**2 + x**2)**(3/2)` in between.
