### ISSUE TITLE
How to solve for value as function changes behavior

### ISSUE THREAD

**Issue by faze-geek** [sympy/sympy#25370]
This is not an issue but a doubt.
I have a a function which behaves as follows -
![image](https://github.com/sympy/sympy/assets/90216905/1a07ecda-fa48-4267-9f14-5446295a7523)

I am working on an method which finds frequency value when phase is (-180).
```
print(phase)
print(phase.subs({_w:0.99999999999}).n())
print(phase.subs({_w:1}).n())

180*arg(1/(_w*(-_w**2*I - 2*_w + I)))/pi
-179.999999999427
180.000000000000
```
As you can see by the graph that the value -180 will arrive just at 1 but at the same point the behavior changes. I would like to know if I can get it by using solve/solveset.
```
sol = solveset(phase + 180,_w, domain=S.Reals)
ConditionSet(_w, Eq(arg(1/(_w*(-_w**2*I - 2*_w + I))) + pi, 0), Reals)
```

**Comment by faze-geek** [comment]
I realise that the sudden change in behavior is because of the principal range set as (-180,180]. Hence we can never reach -180 but use the point at which 180 is obtained.

**Comment by faze-geek** [comment]
I would still like to know how to get the point though.
It is clear than at `omega = 1 `we get `180 deg` phase. Is there any workaround with solvers which can help with the point here ?

```
>>> solveset(phase-180,w,domain=S.Reals)
ConditionSet(w, Eq(arg(1/(w*(-I*w**2 - 2*w + I))) - pi, 0), Reals)
```

**Comment by faze-geek** [comment]
>It is clear than at `omega = 1 `we get `180 deg` phase. Is there any workaround with solvers which can help with the point here ?

@oscarbenjamin Can you have a look when you get time. Thanks in advance !

**Comment by oscarbenjamin** [comment]
If I understand correctly then what you want is basically this:
```python
In [11]: w = symbols('w', real=True)

In [12]: f = 1/(w*(-I*w**2 - 2*w + I))

In [13]: f
Out[13]: 
         1          
────────────────────
  ⎛     2          ⎞
w⋅⎝- ⅈ⋅w  - 2⋅w + ⅈ⎠

In [14]: f.as_real_imag()
Out[14]: 
⎛                          2           ⎞
⎜      -2                 w  - 1       ⎟
⎜────────────────, ────────────────────⎟
⎜               2    ⎛               2⎞⎟
⎜   2   ⎛     2⎞     ⎜   2   ⎛     2⎞ ⎟⎟
⎝4⋅w  + ⎝1 - w ⎠   w⋅⎝4⋅w  + ⎝1 - w ⎠ ⎠⎠

In [15]: f.as_real_imag()[1].cancel()
Out[15]: 
     2       
    w  - 1   
─────────────
 5      3    
w  + 2⋅w  + w

In [16]: numer(f.as_real_imag()[1].cancel())
Out[16]: 
 2    
w  - 1

In [17]: all_roots(numer(f.as_real_imag()[1].cancel()))
Out[17]: [-1, 1]
```
I guess you are only looking for the positive root.

The above technique works only because your function is a rational function with rational coefficients (and `I`) but it will *always* work for any `f` satisfying those conditions:
```python
In [27]: f = 1/(w*(-I*w**2 - 2*w + I)**10 + 1)

In [28]: print(numer(f.as_real_imag()[1].cancel()))
-20*w**20 + 1140*w**18 - 15504*w**16 + 77520*w**14 - 167960*w**12 + 167960*w**10 - 77520*w**8 + 15504*w**6 - 1140*w**4 + 20*w**2

In [29]: print(all_roots(numer(f.as_real_imag()[1].cancel())))
[CRootOf(x**4 + 4*x**3 - 14*x**2 + 4*x + 1, 0), CRootOf(x**4 - 10*x**2 + 5, 0), CRootOf(x**4 - 4*x**3 - 14*x**2 - 4*x + 1, 0), CRootOf(5*x**4 - 10*x**2 + 1, 0), -1, CRootOf(x**4 - 10*x**2 + 5, 1), CRootOf(x**4 - 4*x**3 - 14*x**2 - 4*x + 1, 1), CRootOf(5*x**4 - 10*x**2 + 1, 1), CRootOf(x**4 + 4*x**3 - 14*x**2 + 4*x + 1, 1), 0, 0, CRootOf(x**4 - 4*x**3 - 14*x**2 - 4*x + 1, 2), CRootOf(5*x**4 - 10*x**2 + 1, 2), CRootOf(x**4 + 4*x**3 - 14*x**2 + 4*x + 1, 2), CRootOf(x**4 - 10*x**2 + 5, 2), 1, CRootOf(5*x**4 - 10*x**2 + 1, 3), CRootOf(x**4 + 4*x**3 - 14*x**2 + 4*x + 1, 3), CRootOf(x**4 - 10*x**2 + 5, 3), CRootOf(x**4 - 4*x**3 - 14*x**2 - 4*x + 1, 3)]

In [30]: print([r.n(3) for r in all_roots(numer(f.as_real_imag()[1].cancel())) if r > 0])
[0.158, 0.325, 0.510, 0.727, 1.00, 1.38, 1.96, 3.08, 6.31]
```
If the function is a rational function but the coefficients in the numerator are not all rationals or floats then you can use `nroots` instead of `all_roots` but `nroots` can sometimes fail to converge.

If the function might not be a rational function (if the numerator might not be a polynomial) then you might need to use something like `solveset` or `solve` but you would be better off doing it like this:
```python
In [48]: f = 1/(w*(-I*w**2 - 2*w + I))

In [49]: solveset(numer(f.as_real_imag()[1].cancel()), w, Interval(0, oo))
Out[49]: {1}
```
Note that the above techniques are solving for `im(f) = 0` which is not exactly the same as `arg(f) = pi` since we also need `re(f) < 0`. If the roots are exact and numeric then it should be possible to test for that.

Alternatively can eliminate `w` from the real part using the numerator polynomial of the imaginary part: we have a polynomial equation for `w` so `w` can be eliminated from any other polynomial equation. Often I would use resultants for this but since we have a rational function it is more convenient to use `ratsimpmodprime`:
```python
In [89]: fre, fim = f.as_real_imag()

In [90]: fim_numer = numer(fim.cancel())

In [91]: fim_numer
Out[91]: 
 2    
w  - 1

In [92]: fre
Out[92]: 
      -2        
────────────────
               2
   2   ⎛     2⎞ 
4⋅w  + ⎝1 - w ⎠ 

In [93]: ratsimpmodprime(fre, [fim_numer])
Out[93]: -1/2

In [94]: [fre.subs(w, r) for r in all_roots(fim_numer)]
Out[94]: [-1/2, -1/2]
``` 
If it is possible that different roots for `w` in `fim_numer` would lead to different values of `fre` then `ratsimpmopdrime` would not be able to fully reduce this though:
```python
In [95]: ratsimpmodprime(w**2/(2 + w**3), [fim_numer])
Out[95]: 
  1  
─────
w + 2
```
Another approach using resultants:
```python
In [96]: fre_numer, fre_denom = fre.cancel().as_numer_denom()

In [97]: f_r = symbols('f_r')

In [98]: fre_denom * f_r - fre_numer
Out[98]: 
   ⎛ 4      2    ⎞    
fᵣ⋅⎝w  + 2⋅w  + 1⎠ + 2

In [100]: resultant(fre_denom * f_r - fre_numer, fim_numer, w)
Out[100]: 
     2            
16⋅fᵣ  + 16⋅fᵣ + 4

In [101]: resultant(fre_denom * f_r - fre_numer, fim_numer, w).factor()
Out[101]: 
            2
4⋅(2⋅fᵣ + 1) 

In [102]: all_roots(_)
Out[102]: [-1/2, -1/2]
```

**Comment by faze-geek** [comment]
Thanks, `solveset(numer(f.as_real_imag()[1].cancel()), w, Interval(0, oo, left_open = True))` this is what I was looking for.

**Comment by Davide-sd** [comment]
I'm not sure what your goal is, but if your goal is to get the second visualization:

![image](https://github.com/sympy/sympy/assets/9921777/e7cde020-6c5a-4962-99d1-d2a245e5fd47)

Then you should take a look at [numpy's `unwrap` function](https://numpy.org/doc/stable/reference/generated/numpy.unwrap.html).
