### ISSUE TITLE
the unitary transformation give error

### ISSUE THREAD

**Issue by muhib007** [sympy/sympy#25407]
I am trying analytical calculations using sympy.physics.mechanics. When it comes to unitary transformation, it doesn't work. I tried to find an alternative but failed. If anyone can help, I would appreciate.

**Comment by oscarbenjamin** [comment]
I'm going to close this because GitHub issues are not for asking with help with using SymPy. You can open a "discussion" instead in GitHub but I think it is better to use the mailing list:
https://groups.google.com/g/sympy

You will need to provide more information and show at least some code or I don't think that anyone will be able to offer any useful help.
