### ISSUE TITLE
Lack of is_real attribute for Mul class

### ISSUE THREAD

**Issue by HarryMountain** [sympy/sympy#25612]
Both of these return None when they should return False
atanh(-S(2)).is_real
acoth(S(-1) / 2).is_real

They generate Mul objects that represent -atanh(2) and -acoth(1/2) respectively and the Mul class only implements _eval_is_real_extended() not _eval_is_real().

**Comment by oscarbenjamin** [comment]
It is not necessary to implement `_eval_is_real` if both `_eval_is_extended_real` and `_eval_is_finite` are implemented because the assumptions system uses implication rules like:
https://github.com/sympy/sympy/blob/69f98fb2b0d845e76874067a381dba37b577e8c5/sympy/core/assumptions.py#L254-L256
Actually is is best to implement the smallest number of handlers possible so if `real` is always deducible from `extended_real` and `finite` then it is better *not* to add an `_eval_is_real` handler which is why `Mul` does not have one.

I don't know if you have read this guide that explains the core assumptions system in detail:
https://docs.sympy.org/latest/guides/assumptions.html
This section briefly explains that we do not need to implement all handlers:
https://docs.sympy.org/latest/guides/assumptions.html#implementing-assumptions-handlers
