### ISSUE TITLE
lcm(-1,1) and  lcm(Poly(-1,x), Poly(1,x)) gives different output

### ISSUE THREAD

**Issue by dianetc** [sympy/sympy#25624]
Mostly, the title. Discovered the discrepancy while testing the distributive property of `lcm` and `gcd`. [Found here](https://github.com/sympy/sympy/pull/25517#discussion_r1303412856)

Using hypothesis, we discovered that `lcm(-1,1) = 1`, which is correct, yet `lcm(Poly(-1,x), Poly(1,x)) = Poly(-1,x)` which is not . 

Is this a bug or am I missing something?

Edit: This bug only occurs when the polynomial is defined with domain "ZZ" @asmeurer

**Comment by sylee957** [comment]
The LCM may not be unique by value, but unique up to the divisibility
(if `a` is LCM and `a` divides `b` and `b` divides `a`, then `b` can also be LCM) 
so it's possible to call `-1` as the answer of `lcm(-1,1)`, instead of `1`.

**Comment by dianetc** [comment]
I believe by definition `lcm` should return a positive integer

**Comment by asmeurer** [comment]
How does this break the distributive property?

**Comment by dianetc** [comment]
The following error :
```
E       AssertionError
E       Falsifying example: test_lcm_gcd(
E           f=Poly(-1, x, domain='ZZ'),
E           g=Poly(0, x, domain='ZZ'),
E           h=Poly(1, x, domain='ZZ'),
E       )
```
was thrown when testing `lcm(f, gcd(g, h)) == gcd(lcm(f, g), lcm(f, h)`.
since  the LHS returns `Poly(-1,x)`, while the RHS returns `Poly(1,x)`

**Comment by asmeurer** [comment]
I wonder how this generalizes to nonconstant polynomials. It might be an issue with the way lcm is defined for the ZZ domain as opposed to QQ. In QQ, the resulting polynomial is always monic.

**Comment by oscarbenjamin** [comment]
This is handled here:
https://github.com/sympy/sympy/blob/2562dad9ccb162c48d1fb56227f6c087dfda3386/sympy/polys/euclidtools.py#L1645-L1653
The contents will both be 1 and so will their lcm because content ignores units:
```python
(Pdb) p fc, gc
(1, 1)
(Pdb) p c
1
```
The product `f*g` will be -1:
```python
(Pdb) f
[-1]
(Pdb) g
[1]
(Pdb) dup_mul(f, g, K)
[-1]
```
That is correct as expected. Their gcd will be 1 because gcd is canonical with respect to units:
```python
(Pdb) dup_gcd(f, g, K)
[1]
(Pdb) dup_gcd(g, f, K)
[1]
```
So then the quotient takes the sign of the product which is `-1`.

The formula here suggests that the sign of the numerator should be made canonical:
https://en.wikipedia.org/wiki/Least_common_multiple#Using_the_greatest_common_divisor
Alternatively if the sign of the gcd is assumed canonical then it is only the sign of the final lcm that should be made canonical. I checked wikipedia there because I was wondering whether we should preserve something like `gcd(a, b)*lcm(a, b) = a*b` but maybe that should be expected to hold only up to units of the ring.

We also need to be careful about Gaussian integers so the notion of "sign" should be that the LC is "canonical with respect to multiplication by units" e.g. we have the same problem there:
```python
In [1]: lcm(Poly(I,x), Poly(-1,x))
Out[1]: Poly(-I, x, domain='ZZ_I')
```
A fix is
```diff
diff --git a/sympy/polys/euclidtools.py b/sympy/polys/euclidtools.py
index a0bf6d147f..0f476e6010 100644
--- a/sympy/polys/euclidtools.py
+++ b/sympy/polys/euclidtools.py
@@ -1650,7 +1650,11 @@ def dup_rr_lcm(f, g, K):
     h = dup_quo(dup_mul(f, g, K),
                 dup_gcd(f, g, K), K)
 
-    return dup_mul_ground(h, c, K)
+    h = dup_mul_ground(h, c, K)
+
+    u = K.canonical_unit(dup_LC(h, K))
+
+    return dup_mul_ground(h, u, K)
 
 
 def dup_ff_lcm(f, g, K):
```
Perhaps there should be a `dup_canonical_LC` function or something as an anlogue of `monic` but for rings rather than fields.

**Comment by oscarbenjamin** [comment]
You can see where the same is handled for gcd:
https://github.com/sympy/sympy/blob/2562dad9ccb162c48d1fb56227f6c087dfda3386/sympy/polys/euclidtools.py#L991-L998
