### ISSUE TITLE
can not reduce log inequalities

### ISSUE THREAD

**Issue by vitrun** [sympy/sympy#25697]
```
>>> reduce_inequalities([log(x,3)<=2], x)
...
File .../sympy/solvers/inequalities.py:555, in solve_univariate_inequality.<locals>.valid(x)
    553     return expr.func(v, 0)
    554 # not comparable or couldn't be evaluated
--> 555 raise NotImplementedError(
    556     'relationship did not evaluate: %s' % r)

NotImplementedError: relationship did not evaluate: -2 + log(9)/log(3) <= 0
```
sympy version: 1.12. 

It seems that when `v` is almost zero, say `0.e-110`, `v.is_comparable` is False: 

```python
                  v = v.n(2)
                  if v.is_comparable:
                      return expr.func(v, 0)
                  raise NotImplementedError(
                       'relationship did not evaluate: %s' % r)
```

**Comment by oscarbenjamin** [comment]
It is correct that `is_comparable` should give False here because `is_comparable=True` implies that the expression can be numerically evaluated to a definite positive or negative number and in this case the expression is exactly zero:
```python
In [4]: simplify(-2 + log(9)/log(3))
Out[4]: 0
```
Possibly `reduce_inequalities` should do something different rather than raise an error though. I would have thought that in the worst case `reduce_inequalities` should return the original inequalities. It is not completely clear to me what `reduce_inequalities` is defined to do in general. The docstring says

> Reduce a system of inequalities with rational coefficients.

I suppose that `log(x,3) <= 2` is not an inequality "with rational coefficients" but that should be stated more precisely anyway.

I think the intention of the docstring is to say that `reduce_inequalities` should be able to handle inequalities where both sides are linear in the unknown symbols and all coefficients are explicit rational numbers. If that is the intended behaviour though then `log(x, 2)` should be rejected outright as invalid because it is nonlinear in `x`.

**Comment by smichr** [comment]
> It is correct that `is_comparable` should give False here because `is_comparable=True` implies that the expression can be numerically evaluated to a definite positive or negative number and in this case the expression is exactly zero:
> 

Rather, a number with precision. In this case, without simplification, it can only compute that it is very close to zero. If simplify were applied -- and it shouldn't be -- then the comparable, exact, `S.Zero` would be obtained.

**Comment by smichr** [comment]
Expressions need not be linear (though I am not sure off the top of my head what the criteria are):
![image](https://github.com/sympy/sympy/assets/90703/04fe5804-2f26-44aa-8fd0-6196b9b4de21)

**Comment by vitrun** [comment]
> Expressions need not be linear (though I am not sure off the top of my head what the criteria are)

It seems that `reduce_inequalities` is more capable than what is stated in its docstring. It uses `solve_univariate_inequality` underneath, which has limitations due to `sympy.solvers.solveset.solvify` per the docstring of `solve_univariate_inequality` :

>   Currently, we cannot solve all the inequalities due to limitations in
    :func:`sympy.solvers.solveset.solvify`. Also, the solution returned for trigonometric inequalities
    are restricted in its periodic interval.

Some quick tests:
```
In [448]: reduce_inequalities(sin(x)<1/2)
Out[448]: (0 <= x) & (x < 2*pi)

In [449]: reduce_inequalities(2**(x+1)<1)
Out[449]: x < -1
```

Regarding the issue of `log`. Without the aid of `simplify`, a possible fix is `v = v.n(2, chop=True)` which yields the correct answer of `(x <= 9) & (0 < x)`
