### ISSUE TITLE
Exclusive or (XOR) of a bool symbol and its negation should return True

### ISSUE THREAD

**Issue by adrianperezkeilty** [sympy/sympy#25827]
When using `simplify` we obtain the following basic simplications:
```
>>> from sympy import *
>>> a = symbols('a') 
>>> simplify(a&~a) 
False
>>> simplify(a|~a) 
True
>>> simplify(a^~a) 
a ^ ~a
```
But it is straightforward that `simplify(a^~a) == True` regardless of `a` being `True` or `False`.

Digging a bit into `sympy\logic\boolalg.py` it seems that the function `Xor` does not recognize the immediate simplification either, despite evaluating `a^a` correctly:
```
>>> from sympy import *
>>> a = symbols('a') 
>>> Xor(a, ~a)       
a ^ ~a
>>> Xor(a,a)           
False
```

**Comment by asmeurer** [comment]
The function you want is `simplify_logic`:

```py
>>> simplify_logic(a^~a)
True
```

Not sure what function simplify() is calling that is simplifying those other expressions if not that. 

I disagree that the Xor class should do this simplification automatically.

**Comment by sylee957** [comment]
In the [documentation](https://docs.sympy.org/latest/modules/logic.html) 

There is a note that 

> SymPy’s [simplify()](https://docs.sympy.org/latest/modules/simplify/simplify.html#sympy.simplify.simplify.simplify) function can also be used to simplify logic expressions to their simplest forms.

I think that `simplify` could handle some logic where the simplist form is not ambiguous.

**Comment by adrianperezkeilty** [comment]
> The function you want is `simplify_logic`:
> 
> ```python
> >>> simplify_logic(a^~a)
> True
> ```
> 
> Not sure what function simplify() is calling that is simplifying those other expressions if not that.
> 
> I disagree that the Xor class should do this simplification automatically.

Thank you @asmeurer for pointing out an alternative. 

Still I believe that for consistency, if `Xor(a^a)` returns `False` then `Xor(a^~a)` should return `True`. 

The description of the `Xor` function says the following:
```
    Logical XOR (exclusive OR) function.


    Returns True if an odd number of the arguments are True and the rest are
    False.

    Returns False if an even number of the arguments are True and the rest are
    False.
```
So, if we stick to these requirements then `Xor(a^a)` should return `a^a` instead of `False`, in which case it would make sense to me that  `Xor(a^~a)` returns  `a^~a`. Seems that `Xor` is limited to canceling out duplicates but this should easily be extended for canceling out negations as well... shouldn't it?

**Comment by asmeurer** [comment]
Looks like simplify works on the other expression because of _eval_simplify. The problem is that `Xor._eval_simplify` doesn't call `super()._eval_simplify`, unlike `And._eval_simplify` and `Or._eval_simplify`, which calls simplify_logic. This should be easy to fix.

> So, if we stick to these requirements then Xor(a^a) should return a^a instead of False, in which case it would make sense to me that Xor(a^~a) returns a^~a. Seems that Xor is limited to canceling out duplicates but this should easily be extended for canceling out negations as well... shouldn't it?

Ideally only very minimal things should happen in the automatic simplification stage. I'm not even sure if automatically cancelling out duplicates should be done there. Note that neither And nor Or simplify here either. The more advanced simplification should be left to the various simplification functions. 

Too much automatic evaluation makes the library slow, and it makes certain expressions impossible to represent (see https://docs.sympy.org/dev/explanation/best-practices.html#avoid-too-much-automatic-evaluation for more discussion about this). SymPy is already doing too much automatic evaluation, but we are trying to lessen it.

**Comment by adrianperezkeilty** [comment]
Thanks @asmeurer for the clarification. Also it's my first opened issue. Shall I close it? Or leave it opened until that small fix is made?

**Comment by asmeurer** [comment]
No we should keep this open for the _eval_simplify fix I mentioned above.

**Comment by sylee957** [comment]
I think that algebraic normal form solves this problem `(a^~a).to_anf()`

**Comment by Abhishekjsr283204** [comment]
@sylee957 @asmeurer SIR is its issue done? actually, i want to work to this issue please clarify

**Comment by SamLubelsky** [comment]
# as standard simplify uses simplify_logic which writes things as
# And and Or, we only simplify the partial expressions before using
# patterns

This seems to be why Xor isn't currently making a super call to _eval_simplify_ as it doesn't want to convert everything to ANDs and ORs.

If you try to make a call to the superclass,

`Xor(x` >= y, x <= y)` no longer simplifies to Ne(x, y) because the superclass call simplifies the expression to 
`((x >= y) & (x > y)) | ((x <= y) & (x < y))`
 and the xor simplification function doesn't know how to simplify this.

I agree that the desired result can be achieved using .to_anf() instead.
