### ISSUE TITLE
ratint(e,x).diff().equals(e) is not always True (terms lost)

### ISSUE THREAD

**Issue by ivigili** [sympy/sympy#25896]
```
>>> integrate((2*x+1)/(x**2+1),x)
log(x**2 + 1) + atan(x)
>>> integrate(1/x,x)
log(x)
>>> integrate((2*x+1)/(x**2+1)+1/x,x)
log(x) #wrong
```

**Comment by oscarbenjamin** [comment]
Seems to be a bug in risch somewhere:
```python
In [13]: e = (2*x+1)/(x**2+1)+1/x

In [14]: integrate(e, x)
Out[14]: log(x)

In [15]: integrate(e, x, risch=False)
Out[15]: 
            ⎛ 2    ⎞          
log(x) + log⎝x  + 1⎠ + atan(x)
```

**Comment by smichr** [comment]
`risch` docstring says that it only handles `log` and `exp` (and docstring examples show it handling `x**x`). It also says, "The algebraic case, e.g., functions containing roots, is much more difficult and is not implemented yet." Shouldn't the failing expression raise a NotImplemented right from the start in `risch_integrate`?

**Comment by smichr** [comment]
It fails after re-arranging terms as a rational function:
```python
>>> (2*x+1)/(x**2+1)+1/x
(2*x + 1)/(x**2 + 1) + 1/x
>>> cancel(_)
(3*x**2 + x + 1)/(x**3 + x)
>>> integrate(_,x,risch=False)
log(x)
```

**Comment by smichr** [comment]
It is a failure of `ratint`:
```python
>>> from sympy.integrate.rationaltools import ratint
>>> ratint((3*x**2 + x + 1)/(x**3 + x), x)
log(x)
```

**Comment by smichr** [comment]
Here are some other expressions that fail the test `ratint(e, x).diff().equals(e)`:
```python
(4*x + 7)/(3*(x**2 + 4*x + 6)) + 2/(3*x)
(8*x - 7)/(3*(2*x**2 - 4*x + 3)) + 2/(3*x)
-4*(x + 1)/(2*x**2 - 4*x + 3) - 1/x
(2*x + 1)/(x**2 + 4*x + 6) + 1/x
```

**Comment by smichr** [comment]
Based on the commit referenced above, the issue happens when there are no roots for C and the routine continues as though there *are* roots:
```diff
diff --git a/sympy/integrals/rationaltools.py b/sympy/integrals/rationaltools.py
index 844dcc5feb..1429ffb97a 100644
--- a/sympy/integrals/rationaltools.py
+++ b/sympy/integrals/rationaltools.py
@@ -382,7 +382,7 @@ def log_to_real(h, q, x, t):
         C = Poly(c.subs({u: r_u}), v)
         R_v = roots(C, filter='R')

-        if len(R_v) != C.count_roots():
+        if len(R_v) != C.count_roots():  # what if C == 0?
             return None

         R_v_paired = [] # take one from each pair of conjugate roots
```

**Comment by oscarbenjamin** [comment]
Why does setting `risch=False` disable `ratint`?

**Comment by oscarbenjamin** [comment]
The situation here is that we want to loop over the roots of `q` and distinguish which are real vs which are not or something like that. We first write `q(u + I*v) = c(u,v) + I*d(u, v)`:
https://github.com/sympy/sympy/blob/6501403d06cd26c491069c0c85a8c5786a39b8d2/sympy/integrals/rationaltools.py#L363-L370
The complex roots of `q(z) = 0` are the real solutions for u and v in `c(u,v)=0` and `d(u,v)=0`. The polynomial `R(u) = resultant(c(u,v), d(u,v), v)` is obtained by eliminating `v` to obtain only an equation for `u`. Then `R(u)` is a polynomial whose real roots give the real parts of the roots for `z` in `q(z)=0`:
https://github.com/sympy/sympy/blob/6501403d06cd26c491069c0c85a8c5786a39b8d2/sympy/integrals/rationaltools.py#L372-L386

For each `r_u` we substitute into `c(u,v)` to obtain a polynomial `C(v)` whose real roots would give the corresponding imaginary parts `r_v`. It might be that doing so sets `c(u,v)` to zero but we also need to know if it would set `d(u,v)` to zero.

I'm not sure about the whole approach of using resultants here. The advantage of resultants in a system like `c(u,v)=0`, `d(u,v)=0` is that if you only want one of `u` or `v` then you can eliminate the other to obtain e.g. `p(u)` whose roots will be exactly the possible values of `u` for the solutions of the original system `c`, `d`. If you want to also find `v` though then it is awkward to work back from solving for `u` from `p(u)` back to the full solutions for `u` and `v` of the original system. In this case we have:
```python
In [15]: c = -4*u**3 + 12*u**2 + 12*u*v**2 - 13*u - 12*v**2 + 5

In [16]: d = -12*u**2*v + 24*u*v + 4*v**3 - 13*v

In [17]: print(resultant(c, d, v))
-65536*u**9 + 589824*u**8 - 2383872*u**7 + 5677056*u**6 - 8775936*u**5 + 9129216*u**4 - 6388288*u**3 + 2898624*u**2 - 773568*u + 92480

In [18]: print(real_roots(resultant(c, d, v)))
[1, 1, 1]

In [19]: print(c.subs(u, 1))
0

In [20]: print(d.subs(u, 1))
4*v**3 - v
```
The problem here comes from only checking by substituting the solution for `u` into `c` and not into `d`.

When you do want to solve for both `u` and `v` it is better to use a Groebner basis rather than resultants:
```python
In [29]: _, [(c1,_),(c2,_)] = factor_list(c)

In [30]: _, [(d1,_),(d2,_)] = factor_list(d)

In [31]: gb = groebner([c1, d1], [v, u])

In [32]: for p in gb: print(p)
v
u - 1

In [33]: gb = groebner([c1, d2], [v, u])

In [34]: for p in gb: print(p)
4*v**2 - 1
u - 1

In [35]: gb = groebner([c2, d1], [v, u])

In [36]: for p in gb: print(p)
v
4*u**2 - 8*u + 5

In [37]: gb = groebner([c2, d2], [v, u])

In [38]: for p in gb: print(p)
16*v**2 - 1
16*u**2 - 32*u + 17
```
Even without a Groebner basis factorising like this reveals the solutions more easily. The original polynomial `q` factorises in this case.

**Comment by smichr** [comment]
> Why does setting `risch=False` disable `ratint`?

If `risch` is False then the function is not written in cancelled form (by risch) and the Add-form is integrated in parts. When True, `risch` exits and returns `integrate(cancel(e), x)` which fails in `ratint`.

**Comment by oscarbenjamin** [comment]
> > Why does setting `risch=False` disable `ratint`?
> 
> If `risch` is False then the function is not written in cancelled form (by risch) and the Add-form is integrated in parts. When True, `risch` exits and returns `integrate(cancel(e), x)` which fails in `ratint`.

That logic all sounds like it should be changed.

**Comment by smichr** [comment]
I think the logic is fine: try risch but it is not in the right form try something else. The logic that is bad has to do with `ratint` that is doing the wrong thing with a rational function. And (of course) it should not matter if a polynomial is passed as factored, cancelled, or expanded form. We now know that the cancelled form will fail in `ratint` unless a different approach (groebner, perhaps) is used.

**Comment by asmeurer** [comment]
Maybe I'm misunderstanding what you said, but both risch and ratint are more efficient if given the entire expression rather than integrating term-by-term, so neither should have its input split on an Add (the rest of the algorithms are for the most part better off integrating term-by-term).
