### ISSUE TITLE
The symbolic expression simplification function of sympy package is quite poor, and it is often impossible to simplify or even wrong. 

### ISSUE THREAD

**Issue by Gritbadger** [sympy/sympy#25921]
The symbolic expression simplification function of sympy package is quite poor, and it is often impossible to simplify or even wrong. 

For example, if I enter "binomial (n-1, s-1) * n/s is binomial (n, s)", the result is "false", but I execute "combsimp (binomial (n, s)/binomial (n-1, s-1))" , return "n/s"，this is right. 

For another example, I input "binomial (n, s) is binomial (n-1, s)+binomial (n-1, s-1)", the result is "false", but as long as we calculate by hand, we know that they should be equal.

How can I improve the combinatorial operation and simplify the results?

**Comment by oscarbenjamin** [comment]
You should not use `is` at all unless you understand what the Python `is` operator means. Instead `==` would be more appropriate in general in Python.

In this case though you want to test for mathematical equality rather than structural equality so you should be using something like `simplify` or `.equals` e.g.:
```
In [56]: n, s = symbols('n, s')

In [57]: (binomial(n-1, s-1) * n/s).equals(binomial(n, s))
Out[57]: True

In [58]: binomial(n, s).equals(binomial(n-1, s)+binomial (n-1, s-1))
Out[58]: True
```
