### ISSUE TITLE
Cleaning up symbolic version functions in `ntheory`

### ISSUE THREAD

**Issue by haru-44** [sympy/sympy#26034]
Currently, there are several symbolic version functions in `ntheory` that are inherited from `Function`. Conversely, there are functions in `functions` that need not be symbolic versions. I don't think there is a common view on the relationship between `ntheory` and `functions`, but I think that only purely numeric functions should be placed in `ntheory`.

For example, for the number of partitions, there are currently two functions `sympy.functions.combinatorial.numbers.partitions` and `sympy.ntheory.partitions_.npartitions`. It is hard to see what the difference is, and `npartitions` calls `partition`, which complicates the code. I think it would be clearer to make `partition` a symbolic version function and `npartitions` a numeric calculation function, so that when `partition` needs to calculate a numeric value, it calls `npartitions` to clarify its role.

Functions that are suppose to be cleaned up

* `ntheory.factor_.totient`
* `ntheory.factor_.reduce_totient`
* `ntheory.factor_.divisor_sigma`
* `ntheory.factor_.udivisor_sigma`
* `ntheory.factor_.primenu`
* `ntheory.factor_.primeomega`
* `ntheory.generate.primepi`
* `ntheory.residue_ntheory.mobius`
* `sympy.functions.combinatorial.numbers.partition` and `sympy.ntheory.partitions_.npartitions`
* `sympy.functions.combinatorial.numbers.carmichael`

**Comment by oscarbenjamin** [comment]
> I think that only purely numeric functions should be placed in `ntheory`.

I agree. Ideally ntheory should not have any dependence on functions or even on core. Moving the symbolic functions to `sympy.functions` would eliminate most of that dependence.

**Comment by asmeurer** [comment]
Most of the nonsymbolic ntheory functions should be symbolic. They just haven't been implemented yet. The only ones that don't make sense to make symbolic are the ones that return a list like `primerange`. Some of them aren't symbolic because they wouldn't really do anything interesting, but we shouldn't exclude the possibility that we might want to make them symbolic in the future. 

We should be careful about any function that isn't exported in `__init__.py` (I'm not sure how many there are) because moving it would break anything that imports it directly. For anything else, it's just an internal code organization question. 

I agree that it would be good to move anything that depends on the core out of ntheory, and conversely, any purely algorithmic function that doesn't depend on the core should be moved into ntheory (e.g., there are some such functions in sympy.functions.combinatorial.numbers). ntheory could also then be made to use the polys ground types for integers rather than SymPy integers, with only the end-user visible functions making the conversion to Integer. 

I would say that for most users, they should use the symbolic variant that automatically calls the numeric algorithm, so the functions that compute the numeric algorithms in ntheory should be considered private APIs. In other words, the numeric algorithm functions should mostly be functions that start with underscores. 

> For example, for the number of partitions, there are currently two functions sympy.functions.combinatorial.numbers.partitions and sympy.ntheory.partitions_.npartitions. It is hard to see what the difference is, and npartitions calls partition, which complicates the code. I think it would be clearer to make partition a symbolic version function and npartitions a numeric calculation function, so that when partition needs to calculate a numeric value, it calls npartitions to clarify its role.

Do these functions compute the same thing? At any rate, `partitions` is not exported to the top-level namespace and `npartitions` is, so I would suggest making `npartitions` the symbolic function, and naming the numeric version `_npartitions` (and putting the core numeric algorithm code in `ntheory` with the symbolic stuff in `functions`).

**Comment by haru-44** [comment]
> we shouldn't exclude the possibility that we might want to make them symbolic in the future.

There is no intent to discourage making it symbolic. Why not keep the numeric functions in `ntheory` and add symbolic functions in `functions`?

The discussion in this issue is about where symbolic functions should be placed. I think your opinion is that both symbolic and numeric functions should be placed in `ntheory`, with numeric functions being private functions. But is there any danger of circular references in that policy?

**Comment by asmeurer** [comment]
Just to be clear, I am in support of this plan, to put symbolic things in functions and algorithmic things in ntheory. Having this separation of concerns will indeed remove circular references, and also make it easier to make the algorithmic functions operate directly on faster integer types like mpz. 

I am just saying that as we do this, the ntheory version should be private because for end-users, the dual symbolic-numeric version is all they will need. That will also allow doing things like removing unnecessary type checking form the ntheory functions. This is similar to how the low level and high level functions work in the polys.

**Comment by haru-44** [comment]
> I am just saying that as we do this, the ntheory version should be private because for end-users, the dual symbolic-numeric version is all they will need. That will also allow doing things like removing unnecessary type checking form the ntheory functions. This is similar to how the low level and high level functions work in the polys.

As you say, a numeric function called from a symbolic function could be a private function.
