### ISSUE TITLE
Square root product problem

### ISSUE THREAD

**Issue by olcc** [sympy/sympy#26101]
Hello, I boiled down my problem to:
```
var("x, y", positive=True) ; var("z", real=True) 
qx = I*x + z ; qy = I*y + z
simplify(sqrt(qx*qy) - sqrt(qx)*sqrt(qy))
```
The result is:
```
  _____________________     _________   _________
╲╱ (ⅈ⋅x + z)⋅(ⅈ⋅y + z)  - ╲╱ ⅈ⋅x + z ⋅╲╱ ⅈ⋅y + z
```
Is there a mathematical reason why the result is not zero? Am I supposed to be satisfied by this "simplification"? How can I get a "better" simplification?

**Comment by oscarbenjamin** [comment]
Here is a counterexample:
```python
In [62]: e
Out[62]: 
  _____________________     _________   _________
╲╱ (ⅈ⋅x + z)⋅(ⅈ⋅y + z)  - ╲╱ ⅈ⋅x + z ⋅╲╱ ⅈ⋅y + z 

In [63]: e.subs({x:1,y:1,z:-1})
Out[63]: 2 - 2⋅ⅈ
```
More generally given two complex numbers we can say that `sqrt(a*b) = sqrt(a)*sqrt(b)` only if `-pi < arg(a) + arg(b) <= pi`. In principle then if `z` is assumed nonnegative this simplification would apply but the evaluation system does not try to distinguish that case so that would not simplify either.

You can ask `powsimp` to ignore the potential non-validity and just do the seemingly obvious simplification:
```python
In [71]: powsimp(e)
Out[71]: 
  _____________________     _________   _________
╲╱ (ⅈ⋅x + z)⋅(ⅈ⋅y + z)  - ╲╱ ⅈ⋅x + z ⋅╲╱ ⅈ⋅y + z 

In [72]: powsimp(e, force=True)
Out[72]: 0
```
Use `force=True` at your own risk.

**Comment by olcc** [comment]
Thank you. I didn't remember the position of the branch cut in the definition of sqrt(). Sorry.
