### ISSUE TITLE
matrix of vectors destroys vector type

### ISSUE THREAD

**Issue by oe1rsa** [sympy/sympy#26121]
from sympy.matrices import Matrix
    from sympy.vector import CoordSys3D, Vector

    Sys = CoordSys3D('Sys')
    O = Sys.origin

    # The row matrix of unit vectors
    E = Matrix([Sys.i, Sys.j, Sys.k]).T

    # A Column matrix of coordinates
    a = Matrix([1, 2, 3])

    # Obtain the matrix product
    av = E*a

    # The following does not work! Why is av[0] not a vector anymore? 
    # Is this a bug? Am I missing something important?
    A = O.locate_new('A', av[0])

**Comment by oscarbenjamin** [comment]
It is because:
```python
In [61]: type(Add(Sys.i, Sys.j))
Out[61]: sympy.core.add.Add

In [62]: type(Sys.i + Sys.j)
Out[62]: sympy.vector.vector.VectorAdd
```
The Matrix code assumes that it can add things with `Add` but there is no mechanism that makes this work with vectors.

Ideally the `.kind` would be used for this so that `Add` can dispatch to `VectorAdd` or something like that. Currently `.kind` is undefined for vectors though.

**Comment by shishir-11** [comment]
Do you think we can handle it any other way like checking the type and removing the vector part initially and adding them like scalars and adding them back later.

**Comment by oscarbenjamin** [comment]
This sort of problem arises any time `Add(a, b)` is not the same as `a + b`. The vector code defines `__add__` and it is basically always a problem for an Expr class to define `__add__`. Instead what is needed is a way to make it so that `Add(a, b)` can do whatever should be done in the case of vectors.

**Comment by shishir-11** [comment]
> Ideally the .kind would be used for this so that Add can dispatch to VectorAdd or something like that. Currently .kind is undefined for vectors though.

What would you suggest on how to make these changes ,  I tried looking into it but it seems like it is connected to many different files and classes .

```
>>> E = Matrix([Sys.i, Sys.j, Sys.k]).T
>>> E[0].kind
UndefinedKind
>>> E.kind
MatrixKind(UndefinedKind)
```
is what we currently get . Do you think it should be changed so that `.kind` gives something like `VectorAdd` . 

> An expression representing a matrix may not be an instance of
     the Matrix class, but it will have kind ``MatrixKind``:

Sorry for any unnecessary questions but can't we make vectors work the same way ? So they can always have Something like `Vector` as its kind

**Comment by oscarbenjamin** [comment]
Yes, ideally the kind of all vector objects would VectorKind.

**Comment by shishir-11** [comment]
Where would we need to make the changes to ensure the `.kind` gives the desired result for vectors .

**Comment by JotacBravo** [comment]
Hi, I would like to work on this issue.

**Comment by Henrique-S123** [comment]
Once one had implemented the VectorKind, what would be the next step to ensure that Add could dispatch to VectorAdd?

**Comment by oscarbenjamin** [comment]
I'm not sure. Maybe look at how it works for MatrixKind.
