### ISSUE TITLE
Comparing PythonMPQ with floats and decimals

### ISSUE THREAD

**Issue by sylee957** [sympy/sympy#26204]
```
from sympy import QQ
from decimal import Decimal

QQ(2, 3) < 0.666
QQ(2, 3) < Decimal('0.666')
```

raises errors `AttributeError: 'float' object has no attribute 'denominator'`

**Comment by oscarbenjamin** [comment]
I'm not sure if this should be fixed.

I deliberately did not add all features to PythonMPQ because most are not needed. If QQ is used properly there should never be any reason for PythonMPQ to interact with anything other than maybe `int`.

Maybe QQ is too public to be so restrictive though.

**Comment by sylee957** [comment]
I'm aware that this had got me into some type problems on comparing PythonMPQ with roots,
however, if it is better not add some branching cases in PythonMPQ, maybe I can close this

**Comment by samithkavishke** [comment]
These are the data types that are eligible to compare at this moment `PythonMPQ`, `int`, `decimal.Decimal` and  `fraction.Fraction`.
Since this comparison logic is completely based on common denominator and comparing the numerators, need to add the logic in order to compare the `float` data type. But, since it is not that urgent usage we can ignore it.

**Comment by sylee957** [comment]
Well, I also pointed out that decimal is listed as comparable objects, but does not work
