### ISSUE TITLE
`sympy.logic.inference.satisfiable` is a function that returns a satisfiable variable assignment, correct?

### ISSUE THREAD

**Issue by oscarbenjamin** [sympy/sympy#26320]
`sympy.logic.inference.satisfiable` is a function that returns a satisfiable variable assignment, correct?

```python
>>> from sympy.logic import satisfiable
>>> from sympy import symbols

>>> x, y, z = symbols('x y z')
>>> satisfiable(x & y | z)
{z: True, x: True, y: True}
```

I don't think that determining satisfiability would be in line with the other algorithms.

```python
>>> satisfiable(x & y | z, algorithm="z3")
True
```

_Originally posted by @haru-44 in https://github.com/sympy/sympy/issues/25436#issuecomment-1941382575_

**Comment by oscarbenjamin** [comment]
This needs to be fixed before sympy 1.13.

**Comment by oscarbenjamin** [comment]
CC @TiloRC

**Comment by TiloRC** [comment]
Oops I did not mean to modify the milestone

**Comment by TiloRC** [comment]
Maybe this should be using `.model()` rather than `.check()` or otherwise it should use the `solve` function:
```python
In [12]: from z3 import *

In [13]: x = Bool('x')

In [14]: y = Bool('y')

In [15]: z = Bool('z')

In [16]: s = Solver()

In [17]: s.add(x & y | z)

In [18]: s
Out[18]: [Or(And(x, y), z)]

In [19]: s.check()
Out[19]: sat

In [20]: s.model()
Out[20]: [z = False, y = True, x = True]

In [21]: solve(x & y | z)
[z = False, y = True, x = True]
```

_Originally posted by @oscarbenjamin in https://github.com/sympy/sympy/issues/25436#issuecomment-1941458858_

**Comment by TiloRC** [comment]
`.model()` raises an exception when a model is not found (see the [documentation](https://z3prover.github.io/api/html/classz3py_1_1_solver.html#a67729337459dbcfb86f875493d928e10))

I'm not sure under what circumstances this happens. I remember it coming up as a problem and maybe that's why I implemented things such that `satisfiable` returned True instead of a model. It's possible that this won't be an issue at all though and we should always be able to get a model.

It's possible that this is a very easy fix and simply calling `.model()` and returning the model formatted in the appropriate way will work.
