### ISSUE TITLE
Two docstring style guides

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#26387]
There seems to be two docstring style guides in the dev documentation:
![image](https://github.com/sympy/sympy/assets/276007/7409529d-5229-4718-bd93-37c79b6c145e)
First:
![image](https://github.com/sympy/sympy/assets/276007/e6f7f856-e088-4ab8-92e4-371d0b633388)
Second:
![image](https://github.com/sympy/sympy/assets/276007/139cda5a-e59a-4f73-b18c-457b4ebca94e)

**Comment by Abhishekjsr283204** [comment]
@moorepants Good evening sir should we remove the one in the docstring style guide or anything else please clear more specifically this issue. how to tackle this issue sir ?

**Comment by moorepants** [comment]
I don't know how to tackle it. Maybe figure out who added them both as ask them about it.

**Comment by Shreya111111** [comment]
@moorepants can I work on this issue I think docstring style guide comes under general guidelines

**Comment by sylee957** [comment]
It can be from

https://github.com/sympy/sympy/blob/master/doc/src/contributing/documentation-style-guide.rst
https://github.com/sympy/sympy/blob/master/doc/src/contributing/docstring.rst

**Comment by sylee957** [comment]
I think that they were added in the PR https://github.com/sympy/sympy/pull/21894, so they could be intentional

**Comment by asmeurer** [comment]
The two guides have separate information. The second guide is misleadingly named because it primarily deals with things for RST files, not docstrings. The filename is more accurate. Although much of what is in it also applies to docstrings. 

https://github.com/sympy/sympy/pull/21894 did intentionally split  did intentionally split this, but I don't know if it's been helpful. Perhaps we should merge the two guides, and just be clear about which parts do not apply to docstrings (for example, docstrings currently cannot be written in Markdown).

**Comment by moorepants** [comment]
So maybe the fix is "Documentation Style Guide" and "Docstring Style Guide" as the two names.
