### ISSUE TITLE
Wrong limit result for Abs((-n/(n+1))**n)

### ISSUE THREAD

**Issue by satels** [sympy/sympy#26513]
```python
import sympy

from sympy import S, Symbol, limit, oo

print('sympy version:', sympy.__version__)

n = Symbol('n', real=True)

expr = (n/(n+1))**n
print(limit(expr, n, oo))  # Success

expr = (-n/(n+1))**n
print(limit(expr, n, oo))  # Wrong

expr = Abs((-n/(n+1))**n)
print(limit(expr, n, oo))  # Wrong
```

The result:
```python
sympy version: 1.12
exp(-1)
0
0
```

**Comment by anutosh491** [comment]
Thanks for raising this. We do perform poorly when it comes to limits (bi-directional, or at infinities too ... you can easily find similar errors for `-oo` too ) involving the abs function.

**Comment by arnabnandikgp** [comment]
It seems that the result for the third limit (the one with abs) is being returned correctly by gruntz but not for the second one
```
In [6]: gruntz((-n/(n+1))**n, n, oo)
Out[6]: 0

In [7]: gruntz(abs((-n/(n+1))**n), n, oo)
Out[7]: exp(-1)

```
though for the second one(negative one) we get value 0 though the expression (-n/(n+1))**n is not well defined at infinity, it seems the problem stems from the following lines:
https://github.com/sympy/sympy/blob/2565eb35e255f0fee2267f20e9065b0f5eedf562/sympy/series/limits.py#L266-L286
since gruntz returns wrong value for (-n/(n+1))**n i.e 0 the computation for Abs one also gets messed up.

**Comment by anutosh491** [comment]
Ok these are my thoughts here 
1) So technically the gruntz is responsible for all 3 outputs here, which means instead of limit we can straight up call gruntz and if we get it to work, we are done.
2) Talking about the 3rd limit

So the code flow tries to solve `limit(Abs((-n/(n+1))**n), n, oo)` through 2 approaches 
i) calcualte `limit((-n/(n+1))**n), n, oo)` and then make a decision
ii) calculate `gruntz(Abs((-n/(n+1))**n), n, oo)`

Now as we can see, we don't solve `limit((-n/(n+1))**n), n, oo)` correctly and return `0` for the same, hence the case adding Abs goes wrong too

3) So now we need to solve `limit((-n/(n+1))**n), n, oo)` which further depends on `gruntz((-n/(n+1))**n), n, oo)` which currently returns `0`.

4) Hence `gruntz((-n/(n+1))**n), n, oo)` is the whole issue here. Once that is solved we can backtrack and all other limits would work by themselves. Now we return 0 here but the expression is not well defined at infinity. I think we just need to return self here.
```
>>> limit((-n/(n+1))**n), n, oo)
Limit((-x/(x + 1))**x, x, oo)
```

**Comment by arnabnandikgp** [comment]
>Hence gruntz((-n/(n+1))**n), n, oo) is the whole issue here. Once that is solved we can backtrack and all other limits would work by themselves. Now we return 0 here but the expression is not well defined at infinity. I think we just need to return self here.

Yes exactly!

**Comment by arnabnandikgp** [comment]
It seems that the following lines are the cause of the problem 
https://github.com/sympy/sympy/blob/3377fbd8311512529c6d014fd60055d8aab5274b/sympy/series/gruntz.py#L417-L418
the function sign(e,x) computes the sign of e as x tends to infinity.
In master sign(log(-n/(n+1), n) computes to -1 which is wrong and should have been I.
It seems the above lines were added with the context that taylor series expansion of `log(x+1)` around 0  is `  x -x**2/2+ ...' but since here we are trying to find the sign of expression as  x tends to oo so maybe this conditional isn't the right thing to do here.
Removing the conditional altogether solves the issue as sign of log expressions are calculated correctly using coefficient obtained from mrv_leadterm, here
https://github.com/sympy/sympy/blob/3377fbd8311512529c6d014fd60055d8aab5274b/sympy/series/gruntz.py#L421-L422

**Comment by oscarbenjamin** [comment]
> the function sign(e,x) computes the sign of e as x tends to infinity.
> In master sign(log(-n/(n+1), n) computes to -1 which is wrong and should have been I.

Is this `sign` function supposed to be able to handle non-real inputs?

It gets this wrong:
```python
In [12]: from sympy.series.gruntz import sign

In [13]: sign(exp(I*x), x)
Out[13]: 1
```
Is it that somewhere higher up such non-real expressions should be rejected?

**Comment by arnabnandikgp** [comment]
Yeah, since scenarios which will require computation of `sign(exp(I*x), x)` will be simply arise from things like `limit(exp(I*x), x,oo)`and in `limitinf` we use the `sign()` on the coefficient(using mrv_leadterm) of rewritten(rewrite in mrv_leadterm) term where it will raise error, 
https://github.com/sympy/sympy/blob/da2d56142230563bcfe50c564980e7d07fcc0cc9/sympy/series/gruntz.py#L646-L648
even in case of nested exponentiation or power tower scenarios, routines in `mrv` ensure that we dont end up getting exp or logs in exponents. Nevertheless we will never come to the point of having to use this sign function on exponents directly I believe.
