### ISSUE TITLE
Not all time derivatives are replaced when forming Kane's equations

### ISSUE THREAD

**Issue by moorepants** [sympy/sympy#26751]
Taken from https://github.com/pydy/pydy/issues/501:

```python
from sympy import symbols, solve
from sympy.physics.mechanics import *
import numpy as np
from pydy.system import System

# Reference frames and Points
# ---------------------------
N = ReferenceFrame('N')  # Inertial Frame
B = ReferenceFrame('B')  # Drone after X (roll) rotation (Final rotation)
C = ReferenceFrame('C')  # Drone after Y (pitch) rotation
D = ReferenceFrame('D')  # Drone after Z (yaw) rotation (First rotation)

No = Point('No')
Bcm = Point('Bcm')  # Drone's center of mass


# Variables
# ---------------------------
# x, y and z are the drone's coordinates in the inertial frame, expressed with the inertial frame
# u, v and w are the drone's velocities in the inertial frame, expressed with the drone's frame
# phi, theta and psi represents the drone's orientation in the inertial frame, expressed with a ZYX Body rotation
# p, q and r are the drone's angular velocities in the inertial frame, expressed with the drone's frame

x, y, z, u, v, w = dynamicsymbols('x y z u v w')
phi, theta, psi, p, q, r = dynamicsymbols('phi theta psi p q r')

# First derivatives of the variables
xd, yd, zd, ud, vd, wd = dynamicsymbols('x y z u v w', 1)
phid, thetad, psid, pd, qd, rd = dynamicsymbols('phi theta psi p q r', 1)

# Constants
# ---------------------------
mB, g, IBxx, IByy, IBzz = symbols('mB g IBxx IByy IBzz')

# Rotation ZYX Body
# ---------------------------
D.orient(N, 'Axis', [psi, N.z])
C.orient(D, 'Axis', [theta, D.y])
B.orient(C, 'Axis', [phi, C.x])

# Origin
# ---------------------------
No.set_vel(N, 0)

# Translation
# ---------------------------
Bcm.set_pos(No, x*N.x + y*N.y + z*N.z)
Bcm.set_vel(N, u*B.x + v*B.y + w*B.z)

# Inertia Dyadic
# ---------------------------
IB = inertia(B, IBxx, IByy, IBzz)

# Create Bodies
# ---------------------------
BodyB = RigidBody('BodyB', Bcm, B, mB, (IB, Bcm))
BodyList = [BodyB]

# Forces and Torques
# ---------------------------
Grav_Force = (Bcm, mB*g*N.z)


ForceList = [Grav_Force]

# Kinematic Differential Equations
# ---------------------------
kd = [xd - dot(Bcm.vel(N), N.x),
      yd - dot(Bcm.vel(N), N.y),
      zd - dot(Bcm.vel(N), N.z),
      p - dot(B.ang_vel_in(N), B.x),
      q - dot(B.ang_vel_in(N), B.y),
      r - dot(B.ang_vel_in(N), B.z)]

# Kane's Method
# ---------------------------
KM = KanesMethod(N, q_ind=[x, y, z, phi, theta, psi], u_ind=[u, v, w, p, q, r], kd_eqs=kd)
(fr, frstar) = KM.kanes_equations(BodyList, ForceList)
````

```
In [2]: import sympy.physics.mechanics as me

In [3]: me.find_dynamicsymbols(KM.forcing)
Out[3]: 
{Derivative(phi(t), t),
 Derivative(theta(t), t),
 p(t),
 phi(t),
 q(t),
 r(t),
 theta(t),
 u(t),
 v(t),
 w(t)}
```
`Derivative(phi(t), t)` and `Derivative(theta(t), t)` should be replaced internally in KanesMethod. They come from forming fr_star. So a replacement is being missed somewhere.

**Comment by Peter230655** [comment]
For what it is worth: I ran the program above, and got this output:

sympy version 1.13.0rc2
fr + frstar DS {phi(t), q(t), w(t), Derivative(p(t), t), Derivative(r(t), t), u(t), Derivative(q(t), t), Derivative(v(t), t), r(t), theta(t), v(t), Derivative(u(t), t), Derivative(w(t), t), p(t)}
forcing vector DS {phi(t), q(t), w(t), u(t), r(t), theta(t), v(t), psi(t), p(t)}

simply added the line to pri8nt my sympy version

```
from sympy import symbols, solve
from sympy.physics.mechanics import *
import numpy as np
from pydy.system import System

# Reference frames and Points
# ---------------------------
N = ReferenceFrame('N')  # Inertial Frame
B = ReferenceFrame('B')  # Drone after X (roll) rotation (Final rotation)
C = ReferenceFrame('C')  # Drone after Y (pitch) rotation
D = ReferenceFrame('D')  # Drone after Z (yaw) rotation (First rotation)

No = Point('No')
Bcm = Point('Bcm')  # Drone's center of mass


# Variables
# ---------------------------
# x, y and z are the drone's coordinates in the inertial frame, expressed with the inertial frame
# u, v and w are the drone's velocities in the inertial frame, expressed with the drone's frame
# phi, theta and psi represents the drone's orientation in the inertial frame, expressed with a ZYX Body rotation
# p, q and r are the drone's angular velocities in the inertial frame, expressed with the drone's frame

x, y, z, u, v, w = dynamicsymbols('x y z u v w')
phi, theta, psi, p, q, r = dynamicsymbols('phi theta psi p q r')

# First derivatives of the variables
xd, yd, zd, ud, vd, wd = dynamicsymbols('x y z u v w', 1)
phid, thetad, psid, pd, qd, rd = dynamicsymbols('phi theta psi p q r', 1)

# Constants
# ---------------------------
mB, g, IBxx, IByy, IBzz = symbols('mB g IBxx IByy IBzz')

# Rotation ZYX Body
# ---------------------------
D.orient(N, 'Axis', [psi, N.z])
C.orient(D, 'Axis', [theta, D.y])
B.orient(C, 'Axis', [phi, C.x])

# Origin
# ---------------------------
No.set_vel(N, 0)

# Translation
# ---------------------------
Bcm.set_pos(No, x*N.x + y*N.y + z*N.z)
Bcm.set_vel(N, u*B.x + v*B.y + w*B.z)

# Inertia Dyadic
# ---------------------------
IB = inertia(B, IBxx, IByy, IBzz)

# Create Bodies
# ---------------------------
BodyB = RigidBody('BodyB', Bcm, B, mB, (IB, Bcm))
BodyList = [BodyB]

# Forces and Torques
# ---------------------------
Grav_Force = (Bcm, mB*g*N.z)


ForceList = [Grav_Force]

# Kinematic Differential Equations
# ---------------------------
kd = [xd - dot(Bcm.vel(N), N.x),
      yd - dot(Bcm.vel(N), N.y),
      zd - dot(Bcm.vel(N), N.z),
      p - dot(B.ang_vel_in(N), B.x),
      q - dot(B.ang_vel_in(N), B.y),
      r - dot(B.ang_vel_in(N), B.z)]

# Kane's Method
# ---------------------------
KM = KanesMethod(N, q_ind=[x, y, z, phi, theta, psi], u_ind=[u, v, w, p, q, r], kd_eqs=kd)
(fr, frstar) = KM.kanes_equations(BodyList, ForceList)

print('sympy version', sympy.__version__)
print('fr + frstar DS', find_dynamicsymbols(fr + frstar))
print('forcing vector DS', find_dynamicsymbols(KM.forcing_full))
```

**Comment by moorepants** [comment]
My output above is from the latest release of SymPy (1.12.1), which is likely what the person in the PyDy issue is using. You are running with the latest release candidate. When I run with the master branch I get:

```
In [2]: import sympy.physics.mechanics as me

In [3]: me.find_dynamicsymbols(KM.forcing)
Out[3]: {p(t), phi(t), q(t), r(t), theta(t), u(t), v(t), w(t)}
```

So it does seem this is resolved and will behave correctly for SymPy >= 1.13.

**Comment by oscarbenjamin** [comment]
I think it's always worth bisecting something like this to see if you think the problem really was fixed. In this case the change was a7acced150248b96ae2dbc964b5ff266648b898f from gh-24890. To me that does look like the direct fix for this issue although I don't this part of the codebase well.

Btw Jason I notice that pydy does not provide any wheels:
https://pypi.org/project/pydy/#files
The maintainers of pip and related packaging tools would like to transition to a future in which `pip install foo` fails by default if there are no wheels for `foo` (https://github.com/pypa/pip/issues/9140). You can test what this looks like by passing `--only-binary :all:` to pip:
```console
$ pip install --only-binary :all: pydy
ERROR: Could not find a version that satisfies the requirement pydy (from versions: none)
ERROR: No matching distribution found for pydy
```
For a pure Python project like pydy it is easy enough to provide wheels. The conditional dependency should be expressed using a marker rather than as a setup.py check:
https://github.com/pydy/pydy/blob/5106a1f78178502d810d68c23a6f3cc1214c64d7/setup.py#L37-L38

**Comment by moorepants** [comment]
> I think it's always worth bisecting something like this to see if you think the problem really was fixed.

That's fine, but I don't always have unlimited time to do so. Thanks for taking the time to do it for us.

> The maintainers of pip and related packaging tools would like to transition to a future in which pip install foo fails by default if there are no wheels

That seems like a very poor choice given that wheels will likely never provide a general solution for  for non-Python dependencies. If I'm forced to do it in the future, I will, but I have no interest in wheels for the projects I maintain at the moment.

**Comment by oscarbenjamin** [comment]
> That seems like a very poor choice given that wheels will likely never provide a general solution for for non-Python dependencies.

If you can't make a wheel then do you expect building from sdist to succeed on someone else's computer?

Why should pip try to build an sdist that has non-Python dependencies such that the build will almost certainly fail for the end user?

This is precisely why they don't want pip to build sdist by default. There are for the most part two types of Python packages:

1. Simple pure Python packages that are easy to build and can easily provide a wheel (e.g. SymPy, PyDy).
2. Complicated packages with external non-Python dependencies where the build would almost certainly fail for an end user (e.g. NumPy, python-flint). Most pip users have no hope of installing these packages unless wheels are provided.

In case 1 there is no reason for the project not to provide a wheel. In case 2 it is bad UX for users if `pip install numpy` even attempts to build the sdist: the project should provide wheels or pip should refuse to install it by default.

Building a wheel is trivial for PyDy:
```console
$ pip install build wheel
$ python -m build
$ ls dist/
pydy-0.8.0.dev0-py3-none-any.whl  pydy-0.8.0.dev0.tar.gz
$ twine upload dist/*
```
In future I expect that installers will refuse to build PyDy from sdist by default (this might not even be pip but something like uv).

Regardless of providing wheels the conditional dependency logic in PyDy's setup.py should be fixed to use an environment marker rather than an `if`. Otherwise it breaks any tool that tries to make a cross-platform lock file involving PyDy.

**Comment by moorepants** [comment]
Dear Oscar, I am not interested in debating anything about wheels. If you have the time an energy to make a PR that builds and uploads wheels of PyPi via CI for PyDy, then I will accept that PR. Most of us are already giving more volunteer time on these things than is sane. Every moment I spend on these extra bits and bobs costs me other things in my career and personal life. In OSS, we all get to maintain our projects however we like. For example, I don't even have to upload sdists to PyPi at all. We already know that you and I have differing opinions on various aspects of Python. Maybe one day we'll get to discuss them at the pub. Sincerely, Jason

**Comment by oscarbenjamin** [comment]
Fair enough.

> If you have the time and energy to make a PR that builds and uploads wheels of PyPi via CI for PyDy, then I will accept that PR.

It is not hard to do but it is not just a case of a PR. Settings need to be enabled both in PyPI and in the GitHub repo to make trusted publishing work and you need to decide what event should trigger deployment (e.g. pushing a tag). The code needed is just this except the download/copy parts should be replaced with checking out the repo and running `python -m build`:
https://github.com/sympy/sympy/blob/f6b14550eaba2fee6b8e995dcdf5a43a71480900/.github/workflows/release.yml#L116-L142

The PyPI settings need to have trusted publishing enabled:
https://docs.pypi.org/trusted-publishers/adding-a-publisher/

The GitHub repo needs to have an "environment" added:
https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment

The sympy/sympy "pypi" environment has me and Aaron as required reviewers which means that after a tag is pushed we both get an email and one of us has to go into Github and sign off before the release gets uploaded to PyPI. The job shows who approved it:
https://github.com/sympy/sympy/actions/runs/9681838591

**Comment by moorepants** [comment]
Uploading wheels as a Actions artifact is also sufficient.

**Comment by oscarbenjamin** [comment]
I think you might be overestimating the difficulty of building a wheel. It is easier to build the wheel than it is to download it from GitHub Actions. This builds both sdist and wheel and uploads both to PyPI:
```console
$ pip install build wheel
$ python -m build
$ ls dist/
pydy-0.8.0.dev0-py3-none-any.whl  pydy-0.8.0.dev0.tar.gz
$ twine upload dist/*
```
I assume that you already do something very similar to this to upload the sdist. The difference is just that you ask to build a wheel as well as an sdist. The `python -m build` command defaults to building both because that is typically what you want when uploading to PyPI.

The Windows conditional dependency would need to be changed to use an environment marker like:
https://peps.python.org/pep-0496/#examples
