### ISSUE TITLE
GF __call__ broken with Integer after fmpz_mod change

### ISSUE THREAD

**Issue by J08nY** [sympy/sympy#26789]
After https://github.com/sympy/sympy/pull/25663 the following code is broken:

```python
from sympy import FF, Integer
K = FF(11)
i = Integer(3)
K(i)
```
Gives:
```python-traceback
Traceback (most recent call last):
  File "virt/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-15-3b3e64f7369f>", line 4, in <module>
    K(i)
  File "virt/lib/python3.11/site-packages/sympy/polys/domains/domain.py", line 381, in __call__
    return self.new(*args)
           ^^^^^^^^^^^^^^^
  File "virt/lib/python3.11/site-packages/sympy/polys/domains/domain.py", line 372, in new
    return self.dtype(*args)
           ^^^^^^^^^^^^^^^^^
  File "virt/lib/python3.11/site-packages/sympy/polys/domains/finitefield.py", line 49, in <lambda>
    ctx = lambda x: flint.nmod(x, mod)
                    ^^^^^^^^^^^^^^^^^^
  File "src/flint/types/nmod.pyx", line 55, in flint.types.nmod.nmod.__init__
TypeError: cannot create nmod from object of type <class 'sympy.core.numbers.Integer'>
```

While previously it worked and gave a `SymmetricModularIntegerMod11(3)`.

**Comment by oscarbenjamin** [comment]
> ```python
> from sympy import FF, Integer
> K = FF(11)
> i = Integer(3)
> K(i)
> ```

It's fine to fix this but why do you need this to work?

Generally the way to convert from a SymPy expression to a domain element is to use the `from_sympy` method:
```python
In [19]: FF(11).from_sympy(Integer(3))
Out[19]: 3
```
The particular case of integers is a bit different because there are established conversion methods for general integer types in Python. Possibly python-flint should be able to accept `Integer` here by using `__index__`.

**Comment by J08nY** [comment]
> It's fine to fix this but why do you need this to work?

Well, because it used to work and now doesn't. The docs do not really say it shouldn't work either.

**Comment by oscarbenjamin** [comment]
> Well, because it used to work and now doesn't.

It would have been better if this was always an error.

> The docs do not really say it shouldn't work either.

https://docs.sympy.org/latest/modules/polys/domainsintro.html#domain-elements-vs-sympy-expressions

GF etc are part of a lower-level subsystem that is for the most part internal to sympy. In the domain system explicit conversions should be used rather than depending on implicit ones. The existing code is not very consistent about this so there are some things that seem to work but that should not really be used.
