### ISSUE TITLE
Problem with complex vectors

### ISSUE THREAD

**Issue by MarkDPhysics** [sympy/sympy#27094]
I'm trying to use vector coordinates in sympy.  I'm working with complex vectors.  This code illustrates the problem:

from sympy import symbols, I, conjugate
from sympy.vector import CoordSys3D
N = CoordSys3D('N')
V1 = I * N.i
V3 = I * N.i + (1 + I) * N.j + 2 * N.k
Vout1 = conjugate(V1)
print("conjugate V1 = ",Vout1)
Vout3 = conjugate(V3)
print("conjugate V3 = ",Vout3)

The result of running this code is:

conjugate V1 =  -I*conjugate(N.i)
conjugate V3 =  0

What is going on here? I should be getting:
conjugate V1 =  -I*N.i
conjugate V3 = -I * N.i + (1 - I) * N.j + 2 * N.k

**Comment by Davide-sd** [comment]
A workaround that should allow you to continue your work:

```py
from sympy.vector import Vector

def applyfunc(v, func):
    return sum([func(component) * unit_vec for (unit_vec, component) in v.components.items()], start=Vector.zero)

print(applyfunc(V1, conjugate))
# (-I)*N.i
print(applyfunc(V3, conjugate))
# (-I)*N.i + (1 - I)*N.j + 2*N.k
```

I'm quite surprised that `Vector` doesn't implement this function out of the box. After all, matrices do, as well as vector from the physics module.

**Comment by oscarbenjamin** [comment]
The first problem is that `conjugate` doesn't understand vectors:
```python
In [1]: from sympy import symbols, I, conjugate
   ...: from sympy.vector import CoordSys3D
   ...: N = CoordSys3D('N')
   ...: V1 = I * N.i
   ...: V3 = I * N.i + (1 + I) * N.j + 2 * N.k

In [2]: conjugate(I*N.i)
Out[2]:
   ___
-ⅈ⋅i_N

In [3]: print(conjugate(I*N.i))
-I*conjugate(N.i)
```
The next problem is that `BasisDependentAdd` ignores terms that it does not recognise giving zero when it should give an error at least.

Adding `_eval_conjugate` makes it so that the conjugate is actually computed:
```diff
diff --git a/sympy/vector/basisdependent.py b/sympy/vector/basisdependent.py
index 618977bc0f..7fcc0a0da5 100644
--- a/sympy/vector/basisdependent.py
+++ b/sympy/vector/basisdependent.py
@@ -203,9 +203,11 @@ def __new__(cls, *args, **options):
             if arg == cls.zero:
                 continue
             # Else, update components accordingly
-            if hasattr(arg, "components"):
+            elif hasattr(arg, "components"):
                 for x in arg.components:
                     components[x] = components.get(x, 0) + arg.components[x]
+            else:
+                raise TypeError(f"Invalid vector term: {arg}")

         temp = list(components.keys())
         for x in temp:
diff --git a/sympy/vector/vector.py b/sympy/vector/vector.py
index 7847a9f01f..0294fe7933 100644
--- a/sympy/vector/vector.py
+++ b/sympy/vector/vector.py
@@ -422,6 +422,9 @@ def _sympyrepr(self, printer):
     def free_symbols(self):
         return {self}

+    def _eval_conjugate(self):
+        return self
+

 class VectorAdd(BasisDependentAdd, Vector):
     """
```
That leads to some test failures though that need further investigation.

Here is one test failure:
https://github.com/sympy/sympy/blob/1e56b3fb44e5398a3ef8a3cdd25dd7a7b87cd762/sympy/vector/tests/test_integrals.py#L98
What does `C.i*C.y - C.z` mean? Am I being stupid or is that adding a vector and a scalar?

**Comment by oscarbenjamin** [comment]
Another bug:
```python
In [18]:         v1 = C.x * C.i + C.z * C.z * C.j
    ...:         v2 = C.x * C.i + C.y * C.j + C.z * C.k

In [19]: Cross(v1, v2)
Out[19]:
(            ⎛   2⎞     )×((x_N) i_N + (y_N) j_N + (z_N) k_N)
 (x_N) i_N + ⎝z_N ⎠ j_N

In [20]: Cross(v1, v2) + v1
Out[20]:
            ⎛   2⎞
(x_N) i_N + ⎝z_N ⎠ j_N

In [21]: v1
Out[21]:
            ⎛   2⎞
(x_N) i_N + ⎝z_N ⎠ j_N
```
This is also because VectorAdd just silently drops terms if they don't have a `components` attribute:
https://github.com/sympy/sympy/blob/1e56b3fb44e5398a3ef8a3cdd25dd7a7b87cd762/sympy/vector/basisdependent.py#L183-L229

That is seriously bad code and comes from 12933f6 gh-13164 by @Upabjojr. That PR was self-merged without review on the same day that it was opened (no attempt to wait for a review). There are only a few sympy contributors who regularly do this and it is very common that such PRs end up being a source of bugs.
