### ISSUE TITLE
measure_all_oneshot of Qubit(0) yields |01>

### ISSUE THREAD

**Issue by groncarolo** [sympy/sympy#27092]
If I `measure_all_oneshot` a Qubit like |0>, |1>, or a superposition of the two
I get
`|01>`
or
`|11>`

Here's a minimal example
```
from sympy.physics.quantum.qubit import Qubit, measure_all, measure_all_oneshot
q = Qubit(0)
measure_all_oneshot(q)
|01>
```
while if I do a `measure_all`
```
measure_all(q)
[(|0>, 1)]
```
if I change the code and add `nqubits` on line quibit.py line 807 
like so 
`return Qubit(IntQubit(result, nqubits=int(math.log(max(m.shape), 2) + .1))) `

I get 
`|0>`
or
`|1>`

If this fix is reasonable I can push the code in a PR :)

**Comment by hkve** [comment]
Yes, this fix gives the expected behavior. With the proposed change, the `measure_all_oneshot` call above yields `|0>` always since the state is initialized to `|0>` (This is probably what you meant @groncarolo?). Testing with some superpositions and multi qubit  states also seems to give expected behavior.

`sympy/physics/quantum/tests/test_qubit.py` is also missing `measure_all_oneshot` tests, which would be nice to add:)

**Comment by groncarolo** [comment]
@hkve Yes, I did mean that :)

I will push shortly a PR
