### ISSUE TITLE
round raises ZeroDivisionError

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#27165]
`Float('7.7049746683385389568125907632517700101003891634262762146306861466228051e-1417').round(15)`

**Comment by Abhinav00077** [comment]
is this issue open to work? i want to work on it

**Comment by oscarbenjamin** [comment]
Yes, anyone can work on it.

**Comment by nighteous** [comment]
Hey @Abhinav00077 
This issue of my interest so do you mind me getting it done for you?

Thanks for understanding.

**Comment by nighteous** [comment]
Changes done @haru-44 :

https://github.com/sympy/sympy/commit/5cc84cd6b7a0642d4f369a1484874362d5ad9860#diff-a15f315db0810853399c55dcf22cda2e6861949dbf511f8b2296bbecbc48a488R4040-R4046



```bash
fix-round-zero-division-error> python -c "import sympy as sp; print(sp.Float('7.7049746683385389568125907632517700101003891634262762146306861466228051e-1417').round(15)"
math domain error
mag_first_dig value:  -1416
mag_first_dig value:  -1
mag_first_dig value:  -1
mag_first_dig value:  0
mag_first_dig value:  0
mag_first_dig value:  0
mag_first_dig value:  0
0.0
```

So there is a `math domain error` (I believe it has been taking care by the try and except error but thought it would be good to report because input is smaller that `sys.float_info.min`) and the end result seems to be `0.0` after removing `int` typecasting.

**Comment by haru-44** [comment]
The key point of the change is to avoid using Python's built-in types.

```python
10**-1000 # 0.0
```

Since both `10` and `-1000` are `int`, Python tries to perform the calculation using `float`, which resulted in raising a `ZeroDivisionError`.

If at least one of `10` or `-1000` were a `sympy` type, it would attempt to calculate the exact value.

```python
10**S(-1000)
```
or
```python
S(10)**-1000
```

Upon further consideration, changing `mag_first_dig` from `int` to `Integer` would modify the return type of `_mag`, so we need to be cautious about where that could have an impact. Instead, it seems better to limit the scope of the change by modifying `10**mag_first_dig` to `S(10)**mag_first_dig`. This would reduce the potential areas of impact.
