### ISSUE TITLE
Memory Leak in `sympy.lambdify`

### ISSUE THREAD

**Issue by psaegert** [sympy/sympy#27216]
Hi there,

I'm working with an [algorithm](https://github.com/SymposiumOrganization/NeuralSymbolicRegressionThatScales) that relies on calling `sympy.lambdify` hundreds of millions of times (~200M) and noticed the memory usage of the process steadily creeping up and eventually crashing the program.

I was able to trace the problem to the following (see **Demo** below).

Notably, the memory usage still increases despite
1. lambdifying the same equation again
2. "deleting" the lambdified equation

**System Information:**
WSL2 (Windows 10.0.22631 Build 22631)

```
> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```
```
> python --version
Python 3.11.10
```
```
> pip freeze
mpmath==1.3.0
psutil==6.1.0
sympy==1.13.3
```

### Demo:

```python
# sympy_memory.py
import argparse
import psutil

import sympy


if __name__ == '__main__':
    # Parse command line arguments
    parser = argparse.ArgumentParser(description='Run equation n times')
    parser.add_argument('-n', type=int, default=1, help='Number of repetitions')
    args = parser.parse_args()

    # Get the current process to monitor memory usage
    process = psutil.Process()

    # Parse an example equation
    equation_str = 'x'
    parsed_equation = sympy.sympify(equation_str)

    print("Memory Usage:")

    for i in range(args.n):
        # Lambdifying the (same) equation in each iteration
        lambdified_equation = sympy.lambdify('x', parsed_equation)

        # Print memory usage every 10000 iterations
        if i % 10000 == 0:
            mem_usage = process.memory_info().rss / 1024 / 1024  # Convert to MB
            print(f"{i}/{args.n}: {mem_usage:.2f} MB")

        # "Deleting" the lambdified equation
        del lambdified_equation
```

```
> python sympy_memory.py -n 100000
Memory Usage:
0/100000: 49.91 MB
10000/100000: 54.29 MB
20000/100000: 59.27 MB
30000/100000: 64.17 MB
40000/100000: 68.04 MB
50000/100000: 72.05 MB
60000/100000: 75.91 MB
70000/100000: 79.78 MB
80000/100000: 83.45 MB
90000/100000: 89.08 MB
```

**Observation:** The memory usage increases by about ~~+390KB~~ (correction: 390B https://github.com/sympy/sympy/issues/27216#issuecomment-2453168997) per lambdified equation, totalling +39MB over 100k lambdifications and deletions.

### Control (to exclude external factors):

```diff
    parsed_equation = sympy.sympify(equation_str)
+    lambdified_equation = sympy.lambdify('x', parsed_equation)

    print("Memory Usage:")

    for i in range(args.n):
-        # Lambdifying the (same) equation in each iteration
-        lambdified_equation = sympy.lambdify('x', parsed_equation)

        # Print memory usage every 10000 iterations
        if i % 10000 == 0:
            mem_usage = process.memory_info().rss / 1024 / 1024  # Convert to MB
            print(f"{i}/{args.n}: {mem_usage:.2f} MB")

-        # "Deleting" the lambdified equation
-        del lambdified_equation
```

```
> python sympy_memory.py -n 100000
Memory Usage:
0/100000: 49.91 MB
10000/100000: 49.91 MB
20000/100000: 49.91 MB
30000/100000: 49.91 MB
40000/100000: 49.91 MB
50000/100000: 49.91 MB
60000/100000: 49.91 MB
70000/100000: 49.91 MB
80000/100000: 49.91 MB
90000/100000: 49.91 MB
```

**Observation:** The memory usage does not increase.

**Comment by oscarbenjamin** [comment]
> The memory usage increases by about +390KB per lambdified equation

I assume you mean per 10000 lambdified equations so it is about 400 bytes per lambdified equation.

**Comment by oscarbenjamin** [comment]
My guess is that each call to lambdify creates a Dummy and then something creates a polynomial ring with that dummy and the polynomial ring never gets deleted.

**Comment by oscarbenjamin** [comment]
The memory leak is from this line:
https://github.com/sympy/sympy/blob/d293133e81194adc11177729af91c970f092a6e7/sympy/utilities/lambdify.py#L908

**Comment by oscarbenjamin** [comment]
I assume that the purpose of the line is something to do with tracebacks but I don't know lambdify so well.

**Comment by psaegert** [comment]
> > The memory usage increases by about +390KB per lambdified equation
> 
> I assume you mean per 10000 lambdified equations so it is about 400 bytes per lambdified equation.

Correct, (89.08MB - 49.91MB) / 100,000 is about 390B per equation.

**Comment by psaegert** [comment]
I experimented with wrapping the function in an object that would clear the cache upon deletion of the function which significantly reduces the accumulated memory.

### Current:
https://github.com/sympy/sympy/blob/d293133e81194adc11177729af91c970f092a6e7/sympy/utilities/lambdify.py#L933

### Experimental:
``` diff
    func.__doc__ = (
        "Created with lambdify. Signature:\n\n"
        "{sig}\n\n"
        "Expression:\n\n"
        "{expr}\n\n"
        "Source code:\n\n"
        "{src}\n\n"
        "Imported modules:\n\n"
        "{imp_mods}"
        ).format(sig=sig, expr=expr_str, src=src_str, imp_mods='\n'.join(imp_mod_lines))

-    return func
+    return DeletableLambdaFunction(func)
+
+class DeletableLambdaFunction:
+    def __init__(self, func):
+        self.func = func
+
+    def __call__(self, *args, **kwargs):
+        return self.func(*args, **kwargs)
+    
+    def __del__(self):
+        linecache.clearcache()
+        del self.func
+
+    def __doc__(self):
+        return self.func.__doc__

def _module_present(modname, modlist):
    if modname in modlist:
        return True
    for m in modlist:
        if hasattr(m, '__name__') and m.__name__ == modname:
            return True
    return False
```

```
> python sympy_memory.py -n 100000
Memory Usage:
0/100000: 49.80 MB
10000/100000: 50.06 MB
20000/100000: 51.12 MB
30000/100000: 51.12 MB
40000/100000: 51.12 MB
50000/100000: 51.12 MB
60000/100000: 51.38 MB
70000/100000: 51.38 MB
80000/100000: 51.46 MB
90000/100000: 51.46 MB
```

**Comment by oscarbenjamin** [comment]
First question is whether there is a good reason to add to linecache at all.

**Comment by oscarbenjamin** [comment]
It was added in 8a892b2 from gh-14739

**Comment by oscarbenjamin** [comment]
A simple solution would be an option for `lambdify` to disable adding to linecache like `lambdify(..., linecache=False)`.

**Comment by asmeurer** [comment]
I don't see how lazycache would solve this issue. lazycache lets you delay computation of the lines (the idea is to avoid unnecessary I/O in linecache). But for lambdify that would either mean just storing the lines elsewhere in the function closure, or recomputing lambdify in it. The latter could be bug prone if any part of lambdify relied on some state that changed since the original call. 

I think it should be possible to fix this by using `weakref.finalize` https://docs.python.org/3/library/weakref.html#weakref.finalize to clear the linecache entry whenever the function is garbage collected. (it would also be nice if linecache supported this directly; maybe someone can open an issue/PR to CPython)

**Comment by asmeurer** [comment]
Turns out clearing it automatically with `weakref.finalize` is pretty easy. Fix at https://github.com/sympy/sympy/pull/27223

**Comment by asmeurer** [comment]
For reference, adding the source to the linecache does at least 3 things:

1. It allows `inspect.showsource` (and its friend `??` in Jupyter/IPython) to show the source code. 
2. It allows Jupyter tracebacks to show the source code:

    ```py

   In [1]: from sympy import *

   In [2]: x = symbols('x')

   In [3]: f = lambdify(x, tan(x) - sin(x))

   In [4]: f('x')
   ---------------------------------------------------------------------------
   TypeError                                 Traceback (most recent call last)
   Cell In[4], line 1
   ----> 1 f('x')

   File <lambdifygenerated-1>:2, in _lambdifygenerated(x)
         1 def _lambdifygenerated(x):
   ----> 2     return -sin(x) + tan(x)

   TypeError: ufunc 'sin' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
   ```

  (unfortunately this doesn't happen for tracebacks in the normal interpreter because those don't use the linecache and they are impossible to hook into)
3. As noted, it allows you to step into lambdified functions in a debugger, and see the source code of them as you are debugging.

**Comment by oscarbenjamin** [comment]
> 1. It allows `inspect.showsource` (and its friend `??` in Jupyter/IPython) to show the source code.

Why don't we just attach the code to the function?

> 2\. It allows Jupyter tracebacks to show the source code:

Personally I've never found this useful because usually the error is name not found and there is no way to see the import statements in inspect.getsource or the traceback.

As a reminder I offered a simple robust solution above: https://github.com/sympy/sympy/issues/27216#issuecomment-2454768086

**Comment by asmeurer** [comment]
> Why don't we just attach the code to the function?

As far as I know you have to use the linecache if you want the above features to work.

**Comment by asmeurer** [comment]
Anecdotally I've found the `??` aspect to be the most helpful because sometimes it isn't obvious how the lambdify printers translate a given function. And to be clear, we do also put the source string in the docstring of the function. Maybe that's what you meant.

**Comment by oscarbenjamin** [comment]
The code for the function can just be in the docstring rather than in two places:
```
In [113]: f = lambdify(x, x**2 + 1)

In [114]: ??f
Signature: f(x)
Docstring:
Created with lambdify. Signature:

func(x)

Expression:

x**2 + 1

Source code:

def _lambdifygenerated(x):
    return x**2 + 1


Imported modules:
Source:   
def _lambdifygenerated(x):
    return x**2 + 1
File:      /stuff/current/active/sympy/<lambdifygenerated-3>
Type:      function
```

**Comment by oscarbenjamin** [comment]
Neither of the two shows the import statements:
```
In [124]: f = lambdify(x, meijerg([1], [2], [3], [4], x))

In [125]: ??f
Signature: f(x)
Docstring:
Created with lambdify. Signature:

func(x)

Expression:

meijerg(((1,), (2,)), ((3,), (4,)), x)

Source code:

def _lambdifygenerated(x):
    return meijerg(((1,), (2,)), ((3,), (4,)), x)


Imported modules:
Source:   
def _lambdifygenerated(x):
    return meijerg(((1,), (2,)), ((3,), (4,)), x)
File:      /stuff/current/active/sympy/<lambdifygenerated-6>
Type:      function

In [126]: f(1)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In[126], line 1
----> 1 f(1)

File <lambdifygenerated-6>:2, in _lambdifygenerated(x)
      1 def _lambdifygenerated(x):
----> 2     return meijerg(((1,), (2,)), ((3,), (4,)), x)

NameError: name 'meijerg' is not defined
```
How do I debug that?

**Comment by bjodah** [comment]
I find that adding the source to `linecache` is very helpful when debugging, so much so that I routinely do the same thing when I create some "lambdify-like" function. Last time I found it useful was when investigating floating point errors in some subexpressions (`cse=True`), and when floating point exceptions are set to raise in numpy, the use of `linecache` offer nice tracebacks.

As for the `meijerg` example: that looks like a bug?

I think @oscarbenjamin suggestion of adding a keyword argument might be the fastest way forward, given the race condition under pypy.

**Comment by oscarbenjamin** [comment]
> As for the `meijerg` example: that looks like a bug?

It is a bug but the point is I can't analyse the bug because the problem is related to the imports. Really lambdify should generate code with imports in that can be copy-pasted to run the code. Then you could easily debug it by copy-pasting the code and running it normally. Also you can see why the code does not work by looking at the imports.

As for meijerg I think only mpmath has this function. An error should be shown by `lambdify` if the modules don't support the function.

**Comment by asmeurer** [comment]
I agree that somehow being able to tell what namespaces the names come from would also be useful. We don't want to literally add `import` lines to the function, because that would be an unnecessary runtime performance hit. Maybe we could add it somehow to the docstring or elsewhere. Right now, the best way to tell what's going on is to step into the lambdified function in a debugger (which again is easier when the debugger can "see" the source) and analyze the namespace interactively. Ideally you'd want to see the code as something like

```
from numpy import *

def lambdifygenerated(x):
    return ...
```

since this is more or less what's actually happening. I don't know if the linecache lets you add a whole module's source code, but maybe this can be done. 

(as a complete aside: I wonder if the runtime performance is affected by the fact that lambdify adds all possible names to the globals instead of just the ones it needs. Maybe worth playing around with)

**Comment by oscarbenjamin** [comment]
> We don't want to literally add `import` lines to the function, because that would be an unnecessary runtime performance hit.

The import lines could at least be shown outside the function:
```python
from numpy import cos

def lambdify1(a):
    return cos(a)
```
That could be shown in the `__doc__` or somewhere.

**Comment by asmeurer** [comment]
I split that off into another issue https://github.com/sympy/sympy/issues/27244

**Comment by asmeurer** [comment]
My concern with adding a `linecache` option to `lambdify` is similar to my concerns at https://github.com/sympy/sympy/pull/24754. I'm not a fan of adding a bunch of flags to lambdify that are effectively controlling implementation details, especially ones that could in principle be fixed in a way that makes the flag unnecessary. If we do end up adding it, we should make it private so that it isn't a problem to remove it later. Another way to do that sort of thing is with a global `sympy.utilities.lambdify._USE_LINECACHE` variable that people can set to `False` (the advantage of that is it can be removed without breaking compatibility).

**Comment by asmeurer** [comment]
Just to close the loop here, the issue was fixed upstream in PyPy, and I believe also reported upstream in CPython as well (the code I added could in principle cause issues in CPython under threading).
