### ISSUE TITLE
a possible problem with equals method

### ISSUE THREAD

**Issue by jfdelosrios** [sympy/sympy#27224]
hello.

I think I find a problem with the next code

```
from sympy import *

x, a = symbols('x a')

y = diff(
     x * sqrt(a**2 - x**2) + a**2 * asin(x/a),
     x
)

print(y.equals(2 * sqrt(a**2 - x**2)))
```

should the output be a boolean?

**Comment by oscarbenjamin** [comment]
As the docstring says:
```
Return True if self == other, False if it does not, or None.
```
In this case the expressions are equal for some values of the symbols but are not for others e.g. if `x` and `a` are negative. It seems that `.equals` cannot figure that out so it returns `None` meaning that the expressions may or may not be equal.

It is expected that in some cases `.equals` will not be able to determine a True or False result because in general there is no algorithm that can prove that two expressions are equivalent.

**Comment by jfdelosrios** [comment]
ok,

Thank you

other two questions 

1. do you know how to change xtick of a plot in sympy? I have been looking for in the web site this, but I have not looked for it.
2. If I have a doubt about , where can I ask it? are there a community?
