### ISSUE TITLE
'Xor' is printed as 'a ^ b', but is recognized by Sympy as Power: Xor(a, b) -> (a ^ b) -> (a**b)

### ISSUE THREAD

**Issue by ducktalez** [sympy/sympy#27336]
I wanted to use xor-expresions in sympify, but it did not work.

Not really a bug, but I realized I could not load `Xor` with `a ^ b` in sympify, as it is interpreted as `a**b`.

Is this intentional? 

```
import sympy

print(sympy.sympify('Xor(a, b)'))
print(sympy.sympify('a ^ b'))
print(sympy.sympify('a**b'))
```

**Comment by bjodah** [comment]
I doubt it's intentional, but at the same time, it's hard to change at this point (it would be a breaking change). Do note however, that using `sympify` to create an expression from a string is discouraged. Try to use `parse_expr` instead:
```python
>>> srepr(parse_expr("a^b"))
"Xor(Symbol('a'), Symbol('b'))"
```

**Comment by asmeurer** [comment]
I wish we could deprecate and remove these non-Python things from sympify parsing.

**Comment by oscarbenjamin** [comment]
I think that a lot of people prefer `x^2` to be interpreted as a power. It seems like a reasonable default to me. Most uses of parsing don't really want to parse "Python code" as such but rather string representations of "mathematical expressions".

**Comment by Ytemiloluwa** [comment]
In terms of backward compatibility, would it make sense to revisit the default behavior of sympify to prioritize convert_xor=False, aligning with XOR's logical use, while offering an explicit option for users who prefer ^ as Power?

**Comment by oscarbenjamin** [comment]
I think more users would be happy with the current behaviour:
```python
In [1]: sympify('a*x^2 + b*x + c')
Out[1]: 
   2          
a⋅x  + b⋅x + c
```
Note that this affects everything because `sympify` is used everywhere:
```python
In [2]: cos('a*x^2 + b*x + c')
Out[2]: 
   ⎛   2          ⎞
cos⎝a⋅x  + b⋅x + c⎠
```
The use of caret for exponentiation is standard for encoding mathematical expressions in ASCII. Using caret for xor is a convention that is specific to a few programming languages including Python but I am not sure that most users expect parsing expression strings to be like parsing Python code.

There is an option for `sympify` to control this and more generally if you want to customise parsing it is recommended to use `parse_expr`.

**Comment by Ytemiloluwa** [comment]
> I think more users would be happy with the current behaviour:
> 
> In [1]: sympify('a*x^2 + b*x + c')
> Out[1]: 
>    2          
> a⋅x  + b⋅x + c
> Note that this affects everything because `sympify` is used everywhere:
> 
> In [2]: cos('a*x^2 + b*x + c')
> Out[2]: 
>    ⎛   2          ⎞
> cos⎝a⋅x  + b⋅x + c⎠
> The use of caret for exponentiation is standard for encoding mathematical expressions in ASCII. Using caret for xor is a convention that is specific to a few programming languages including Python but I am not sure that most users expect parsing expression strings to be like parsing Python code.
> 
> There is an option for `sympify` to control this and more generally if you want to customise parsing it is recommended to use `parse_expr`.

That makes sense, especially given how widely sympify is used. Would it then be worth improving the documentation or examples to guide users toward parse_expr for more custom parsing needs, like using XOR?

**Comment by bjodah** [comment]
I think the situation is more nuanced than "caret being standard ascii representation" (see this excellent answer for example https://softwareengineering.stackexchange.com/a/331392/300252).

The [documentation](https://docs.sympy.org/latest/modules/core.html#module-sympy.core.sympify) of `sympify` clearly states that it parses the text as python syntax, and that the user should use `parse_expr` when deviating from python compatible syntax.

>To parse non-Python syntax, use parse_expr from sympy.parsing.sympy_parser

I think it could be valuable to add an example using `^` to the docstring of sympify, since the treatment of this character clearly deviates from this rule (and the keyword argument is confusingly named `convert_xor` rather than "caret_is_exponentiation").

**Comment by oscarbenjamin** [comment]
I'm not sure if there is anything to be done here:

- There is an option to sympify that controls this and it is documented.
- There is also parse_expr which has this and other options.
- Changing this would be a significant compatibility break without really bringing any big improvement.
- I'm sure a lot of people prefer the current behaviour anyway.

If you go back through the history it has been like this since f260582 which introduced this behaviour deliberately 14 years ago. The change is so old it predates GitHub but the relevant issue was migrated to gh-4134.

**Comment by asmeurer** [comment]
Yes, to be clear, this would be a significant backwards compatibility break and it's not clear if it's actually worth doing. `sympify` used to be the only function that parsed strings into SymPy expressions, but then `parse_expr` was added, which also included a lot of support for non-Python syntax. Since then, it's been clearer that non-Python parsing things really belong in `parse_expr`, not `sympify`. Of course, things like xor parsing have been there since the beginning so actually doing this breaks things.

(with that being said, I do think it would be a good idea to remove the factorial and repeated decimal parsing from `sympify`, see https://github.com/sympy/sympy/issues/20625)

**Comment by oscarbenjamin** [comment]
There are lots of issues with sympify. I would say that using eval tops the list by far.

In the meantime though I think this issue should be closed so I will close it. If anyone disagrees then reopen but if so then propose something concrete that should be done. Changing the parsing for `x^2` does not seem reasonable to me.
