### ISSUE TITLE
__eq__ doesn't behave as expected with some expressions

### ISSUE THREAD

**Issue by andresliszt** [sympy/sympy#27363]
Maybe this is the intended behavior, but things like this return `False`

```python
from sympy import Symbol

x = Symbol('x')
>>> (x + 1)**2 == x**2 + 2*x + 1
False

```

Should the user call `expand()` method to get the proper result?

```python
from sympy import Symbol

x = Symbol('x')
>>> ((x + 1)**2).expand() == x**2 + 2*x + 1
True

```

Or should this method be called in the `__eq__` method. I took a look in the method and basically it's comparing `self._hashable_content`  with `other._hashable_content`. The example I put fails because `Pow._hashable_content` (for `(x + 1)**2`) is different from `Add._hashable_content` (for `x**2 + 2*x + 1`).

**Comment by oscarbenjamin** [comment]
This is expected behaviour:
https://docs.sympy.org/latest/explanation/gotchas.html#double-equals-signs

Comparing expressions with `==` compares whether they are the exact same expression not whether they are mathematically equivalent.

You suggested to use `.expand()` which is enough in some cases but not in all. In general deciding on the equivalence of symbolic expressions is impossible:
https://en.wikipedia.org/wiki/Richardson%27s_theorem

Instead `==` is for quick exact comparison of expressions and is used for things like `dict` and `set`. If you want to try some function like `expand` then you can do that explicitly.
