### ISSUE TITLE
pylint score

### ISSUE THREAD

**Issue by sympy-issue-migrator** [sympy/sympy#3148]
bc.. pylint is a tool for checking code quality in python code. 

I attach the log of running pylint in sympy. While sometimes he says
nonsense, in some cases he is right and we should follow what he says. 

currently our score is 0.55 / 10 mainly because of missing docstrings,
style issues and circular dependencies (this last thing will hardly be
corrected). 

I propose with this issue to achieve at least a score of 5/10

p. Original issue for "#3148":https://github.com/sympy/sympy/issues/3148: "http://code.google.com/p/sympy/issues/detail?id=49":http://code.google.com/p/sympy/issues/detail?id=49

p. Original author: "https://code.google.com/u/103948515893177094863/":https://code.google.com/u/103948515893177094863/

**Comment by oscarbenjamin** [comment]
Is pylint still desired?

We currently have a number of code quality tests. Probably pylint can replace most of those and also do other things...

**Comment by asmeurer** [comment]
I personally am more interested in tools that catch logic errors than style errors (for instance pyflakes). It would be awesome if we could have SymPy have no pyflakes errors. Other tools like pylint are useful too, so long as there is a way to turn off errors we don't care about. But they also tend to have a lot of false positives (pyflakes has very few false positives by design).

**Comment by oscarbenjamin** [comment]
SymPy now passes under flake8 which is used in CI
