### ISSUE TITLE
evaluate keyword from old core

### ISSUE THREAD

**Issue by thegedge** [sympy/sympy#3373]
bc.. I've currently modified code so that non-assumption keywords can be passed
into any subclass of Basic without worry. I've also implemented
evaluate=False for some things, specifically functions.

One issue I noticed with allowing this keyword is that a fair amount of
extra code will have to be written to compensate for a potentially
unevaluated entity. For example, log(1, evaluate=False) will remain as
log(1) instead of becoming an instance of Basic.Zero(). Now if one wanted
to check this unevaluated log(1) for the is_zero property, _eval_zero()
would have to be implemented in ApplyLog. Similarly, this can apply to
other assumption related items. One possible way to reduce code is to
create a set of default _eval_is_xxx methods that would call _eval_apply
and then apply the is_xxx property to the evaluated form.

I'd love to hear thoughts on what I've mentioned above, and just in general
on the evaluate keyword.

p. Original issue for "#3373":https://github.com/sympy/sympy/issues/3373: "http://code.google.com/p/sympy/issues/detail?id=274":http://code.google.com/p/sympy/issues/detail?id=274

p. Original author: "https://code.google.com/u/inferno1386/":https://code.google.com/u/inferno1386/

**Comment by oscarbenjamin** [comment]
Personally I think that the automatic evaluation model discussed above was the biggest mistake that sympy made. Using evaluate=False is a kludge but that's because the real problem is automatic evaluation in the first place. Automatic evaluation makes it impossible to put expressions into different forms and also makes it impossible to control the efficiency of elementary operations.

The basic model of sympy is that `obj = obj.func(*obj.args)` where calling `obj.func` applies the evaluation routines. The routines are supposed to be simple but inevitably once evaluation is the place where elementary rewrites happen more and more gets added there because there is no other obvious place to put that code and that's where users expect it to be.

Having a way to control evaluation e.g. `doit` is a great idea. Unfortunately doit was not implemented in a consistent way across the codebase https://github.com/sympy/sympy/issues/17280 and does not provide the kind of control that is actually needed. `Basic.rewrite` is better but still very limited. It would have been better to make a suite of different functions for controlling different ways of rewriting.

Automatic evaluation also makes it hard for both users and contributors to understand the performance implications of anything which has in turn contributed significantly to sympy being slow. Explicit evaluation makes it clear where the computational cost is and also that there can be more than one way to "evaluate" something. If evaluation in sympy was explicit then I expect that over time exactly what evaluation was being used in different places would have evolved. Once you have automatic evaluation though it is impossible to remove.

In any case I don't think that we need to keep this old issue open.
