### ISSUE TITLE
"pretty printing"  and KDE-Konsole

### ISSUE THREAD

**Issue by sympy-issue-migrator** [sympy/sympy#4154]
bc.. well..  I have KDE running and sympy and everything works just fine (I
have sympy version 5.8):

[URL= https://addons.mozilla.org/firefox/1174][IMG]http://img213.imageshack.us/img213/7189/snapshot1gp3.png[/IMG][/URL] here is a little screenshot of the imho problem with unicode fonts in konsole

p. Original issue for "#4154":https://github.com/sympy/sympy/issues/4154: "http://code.google.com/p/sympy/issues/detail?id=1055":http://code.google.com/p/sympy/issues/detail?id=1055

p. Original author: "https://code.google.com/u/103512544351805436176/":https://code.google.com/u/103512544351805436176/

**Comment by oscarbenjamin** [comment]
I think this can be closed now

**Comment by smichr** [comment]
What changed since Aaron marked this as valid?

**Comment by oscarbenjamin** [comment]
I don't know what has changed since then. The referenced issue https://github.com/sympy/sympy/issues/3546 was already fixed in https://github.com/sympy/sympy/pull/562

This issue doesn't have enough information for me to be able to see what it is apart from looking at those other issues which are closed/fixed. The link to the screenshot in the OP no longer works.

I commented to give people a chance to respond if it is still an issue but marked it as "could close" so we can remember to come back and close it later.

**Comment by smichr** [comment]
thx
