### ISSUE TITLE
simplify(x**2-x**2.0) does not yield 0.

### ISSUE THREAD

**Issue by ghost** [sympy/sympy#4473]
bc.. >>> x**2.0-x**2
-x**2 + x**2.00000000000000

> > > simplify(x**2.0-x**2)
> > > -x**2 + x**2.00000000000000

This bug is related to bug 1274 .

p. Original issue for "#4473":https://github.com/sympy/sympy/issues/4473: "http://code.google.com/p/sympy/issues/detail?id=1374":http://code.google.com/p/sympy/issues/detail?id=1374

p. Original author: "https://code.google.com/u/107935137289803450816/":https://code.google.com/u/107935137289803450816/

**Comment by oscarbenjamin** [comment]
I still get:
```julia
In [9]: simplify(x**2 - x**2.0)                                                                                                                
Out[9]: 
 2    2.0
x  - x 
```
Should this actually simplify though? I tend to think that we can't be sure the floating point 2.0 really is 2.

**Comment by smichr** [comment]
> So this is very inconsistant.

Although it's ok to have the terms not cancel, we should look into this:
```python
>>> (x**2.0 == x**2, x**1.0 == x**1)
(True, False)
>>> 1.0 == 1
True
>>> 2.0 == 2
True
```

**Comment by oscarbenjamin** [comment]
Since `x**1` gives `x` this is the result of comparing `x` with a `Pow(x, 1.0)`. The same happens with 1 if the Pow is unevaluated:
```julia
In [6]: x == Pow(x, 1)                                                                                                                                                                                             
Out[6]: True

In [7]: x == Pow(x, 1, evaluate=False)                                                                                                                                                                             
Out[7]: False

In [8]: x == Pow(x, 1.0, evaluate=False)                                                                                                                                                                           
Out[8]: False
```

**Comment by vks** [comment]
I think this can be closed then.

**Comment by oscarbenjamin** [comment]
With the last couple of comments I don't think it should be closed as a new issue has emerged with `__eq__`

**Comment by vks** [comment]
What behavior of `__eq__` would you expect?

**Comment by oscarbenjamin** [comment]
> What behavior of `__eq__` would you expect?

Oh of course since `==` is for structural equality it is expected that `x == Pow(x, 1, evaluate=False)` gives False when they are not structurally equal.

But then is it reasonable to say that these are "structurally equal":
```
In [21]: x**2 == x**2.0                                                                                                                                                                                            
Out[21]: True
```

**Comment by asmeurer** [comment]
The x part is a distraction. It's a question of

```py
>>> S(2) == S(2.0)
True
```

See the discussions at https://github.com/sympy/sympy/issues/11707 and linked issues. 

I think we agreed that floats and rationals should compare equal if they are exactly equal. Right now that comparison is loose, for instance 

```py
>>> S(0.1) == S(1)/10
True
>>> Rational(S(0.1))
3602879701896397/36028797018963968
```

But `Rational(S(2.0))` gives `Integer(2)`, so this case would still work like it does now. 

Another option would be for floats and non-floats to always compare unequal. This would fit with the "structural equality" but would be surprising to people, and it could cause some issues with the inherent nontransitivity due to native Python ints and floats comparing equal to one another.

For `x**1` vs. `x**1.0` see https://github.com/sympy/sympy/issues/12942. 

I would suggest closing this as a duplicate of https://github.com/sympy/sympy/issues/11707. There are already too many disparate discussions about float equality and it's hard to keep track of them all.

**Comment by oscarbenjamin** [comment]
If we consider that 2==2.0 and hence that `x**2==x**2.0` then the headline problem in this seems valid: `simplify(x**2-x**2.0)` should be 0.

**Comment by czgdp1807** [comment]
```python
>>> x**2.0-x**2
   2    2.0
- x  + x   
>>> simplify(x**2.0-x**2)
   2    2.0
- x  + x   
>>> 2 == 2.0
True
```
The issue is not fixed.
