### ISSUE TITLE
alternative hosting

### ISSUE THREAD

**Issue by vks** [sympy/sympy#4901]
I just read this: http://sourceforge.net/blog/clarifying-sourceforgenets-denial-of-site-access-for-certain-persons-in-accordance-with-us-law/ For Google code it's the same. So I would like to make sure that people
from these "evil" countries can contribute to sympy. Ondrej, your server is
in Czech republic and thus free of such censorship obligations?

Alternatively it could be possible to use a proxy.

Original issue for #4901: http://code.google.com/p/sympy/issues/detail?id=1802
Original author: https://code.google.com/u/Vinzent.Steinberg@gmail.com/
Original owner: https://code.google.com/u/Vinzent.Steinberg@gmail.com/

**Comment by oscarbenjamin** [comment]
I think now that SymPy is hosted in Github this issue is no longer relevant

**Comment by asmeurer** [comment]
We have no immediate plans to move hosting or create any mirrors. As far as I understand, GitHub is not censored in China (don't know about other countries), and GitHub the company is not as open to working with the Chinese government to censor content as other companies such as Google. This is just what I've heard, so it could be wrong. Also the SymPy repo most likely does not contain content that would be censored, so it would only become inaccessible due to a blanket block.

**Comment by asmeurer** [comment]
Actually this was apparently about censorship to countries like Iran and Cuba that are embargoed by the US. I have no idea if GitHub can be accessed in those countries. Most likely for someone in such a country a method that allows access to all of GitHub (say a VPN or a global mirror) would be more appropriate than a SymPy specific mirror, which we would have to maintain.
