### ISSUE TITLE
poly.subs doesn't work well with mpmath findroot

### ISSUE THREAD

**Issue by memmett** [sympy/sympy#5536]
Defining a symbolic polynomial and using this within mpmath's findroot function doesn't work as expected.

```python
import sympy
import mpmath

mpmath.mp.dps = 45

x = sympy.var('x')
p = (5.0/2.0*x**3 - 3.0/2.0*x).as_poly()

print 'subs:  ', mpmath.findroot(lambda xi: p.subs(x, xi), 1.0)
print 'lambda:', mpmath.findroot(lambda x: 5.0*x**3/2.0 - 3.0*x/2.0, 1.0)
print 'exact: ', mpmath.sqrt(mpmath.mpf('3.0')/mpmath.mpf('5.0'))
```

The output is:
```
subs:   0.77459666924148342341315597798728447146706553
lambda: 0.774596669241483377035853079956479922166584341
exact:  0.774596669241483377035853079956479922166584341
```

Original issue for #5536: http://code.google.com/p/sympy/issues/detail?id=2437
Original author: https://code.google.com/u/104347478710900386258/

**Comment by johanbluecreek** [comment]
Why is this not expected behaviour? The polynomial defined via

```
In [x]: p = (5.0/2.0*x**3 - 3.0/2.0*x).as_poly()
```

do not know about `mpmath`, and the domain for this polynomial will have `dps` accordingly

```
In [x]: p.domain.dps
Out[x]: 15
```

since all coefficients are given as normal floats. To me it would seem odd that a polynomial with `dps=15` give answers at `dps=45`, or that it should respect `mpmath.mp.dps=45` when it has not been told to.

If you give all input numbers to the coefficients as mpmath floats it would get the desired `dps`

```
In [x]: pn = (mpmath.mpf('2.5')*x**3 - mpmath.mpf('1.5')*x).as_poly()

In [x+1]: pn.domain.dps
Out[x+1]: 45
```

that is a bit tedious, so one can also:

```
In [x]: pn = (5.0/2.0*x**3 - 3.0/2.0*x).as_poly(domain=RealField(dps=mpmath.mp.dps))

In [x+1]: pn.domain.dps
Out[x+1]: 45
```

and with this polynomial it works as it should

```
In [x]: print(mpmath.findroot(lambda xi: pn.subs(x, xi), 1.0))
0.774596669241483377035853079956479922166584341
```

To me this appears to be expected behaviour. If not, let me know why and I can have another look.

**Comment by memmett** [comment]
@johanbluecreek great explanation! Thank you. I wasn't aware that you can pass a domain.
