### ISSUE TITLE
epsilon_eq() should be implemented for all Numbers

### ISSUE THREAD

**Issue by renatocoutinho** [sympy/sympy#5599]
```
>>> Float(1).epsilon_eq
AttributeError: 'One' object has no attribute 'epsilon_eq'

>>> Float(2).epsilon_eq
AttributeError: 'Integer' object has no attribute 'epsilon_eq'

Since Float() calls may return objects that are not instances of Float, we should support all methods of Floats in Number class.
```
Original issue for #5599: http://code.google.com/p/sympy/issues/detail?id=2500
Original author: https://code.google.com/u/115599828448622896355/
Original owner: https://code.google.com/u/115599828448622896355/

**Comment by prakash09** [comment]
I am trying to solve this issue. I am getting 
In [3]: Float(1).epsilon_eq
Out[3]: \<bound method Float.epsilon_eq of 1.00000000000000>

In [4]: Float(2).epsilon_eq
Out[4]: \<bound method Float.epsilon_eq of 2.00000000000000>

Can you explain what do you mean by "support all methods of Floats in Number class"? Since Float class is inheriting Number class, so all its methods are already available in Float class.

**Comment by renatocoutinho** [comment]
Back then, Float(1) returned S.One (the same as Integer(1)), but neither Number nor Integer classes have epsilon_eq(). Since Float(1) now is kept as a float, I think this issue can be closed.
