### ISSUE TITLE
Wrong result from residue

### ISSUE THREAD

**Issue by raoulb** [sympy/sympy#5654]
```
Just a simply wrong result from "residue"

In [3]: residue(exp(1/z), z, 0)
Out[3]: 0

See also the bugreport for the Maxima CAS: http://bugs.launchpad.net/ubuntu/+source/maxima/+bug/323221
```

Original issue for #5654: http://code.google.com/p/sympy/issues/detail?id=2555
Original author: https://code.google.com/u/107490137238222069432/

**Comment by cknoll** [comment]
Just for the record: I found another example where `sp.residue` fails. Terms like this arise in Z-Transformation of Inverse-Laplace-Tranformations (quite common in signal processing.)

    import sympy as sp
    s, z, k = sp.symbols("s, z, k")

    sp.residue(      (1)/s*1/(z-sp.exp(s)), s, -0) # gives 1/(z-1)
    sp.residue((1 + k)/s*1/(z-sp.exp(s)), s, -0) # wrong: gives 0

**Comment by sachin-4099** [comment]
On the current master, this evaluates correctly:
```
In [1]: s, z, k = symbols("s, z, k")
In [2]: residue((1 + k)/s*1/(z-exp(s)), s, -0)
Out[2]:
  k       1
----- + -----
z - 1   z - 1
```

**Comment by naveensaigit** [comment]
OP still remains unsolved. On master (1.9 dev), I get an error -
``` python
In [1]: residue(exp(1/x), x, 0)
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-10-7890e0a0035a> in <module>
----> 1 residue(exp(1/x), x, 0)

~\sympy\sympy\series\residues.py in residue(expr, x, x0)
     65         m = Mul(*m)
     66         if not (m == 1 or m == x or (m.is_Pow and m.exp.is_Integer)):
---> 67             raise NotImplementedError('term of unexpected form: %s' % m)
     68         if m == 1/x:
     69             res += c

NotImplementedError: term of unexpected form: exp(1/x)
```

**Comment by asmeurer** [comment]
Before closing this I would like some confirmation that `residue` really is being smarter than it was before, so that it cannot be so easily fooled by limitations of the series algorithms.

> OP still remains unsolved. On master (1.9 dev), I get an error -

An error is better than a wrong answer, although we could look into the unevaluated residue idea from above. It could be interesting if we could write Residue (and ResidueSum) as unevaluated expressions. Although even if we have a robust `residue` I don't know if that necessarily helps do things like improve integration, as there are other complications.
