### ISSUE TITLE
Diagonalizing floating point matrices fails

### ISSUE THREAD

**Issue by aplund** [sympy/sympy#5734]
```
>>> import sympy
>>> a = sympy.Matrix( ((0, 1, 0, 0), (1, 0, 0, 0.002), (0.002, 0, 0, 1), (0, 0, 1, 0)) )
>>> a.diagonalize()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lund/local/lib/python2.6/site-packages/sympy/matrices/matrices.py", line 2345, in diagonalize
    if not self.is_diagonalizable(reals_only, False):
  File "/home/lund/local/lib/python2.6/site-packages/sympy/matrices/matrices.py", line 2406, in is_diagonalizable
    self._eigenvects = self.eigenvects()
  File "/home/lund/local/lib/python2.6/site-packages/sympy/matrices/matrices.py", line 2138, in eigenvects
    raise NotImplementedError("Can't evaluate eigenvector for eigenvalue %s" % r)
NotImplementedError: Can't evaluate eigenvector for eigenvalue -1.00099950049938


(Please excuse my broken setup, but recreating this should be possible with a sanely installed sympy).
```

Original issue for #5734: http://code.google.com/p/sympy/issues/detail?id=2635
Original author: https://code.google.com/u/111408767815219685794/

**Comment by siefkenj** [comment]
This appeared to be resolved in master.

**Comment by jksuom** [comment]
It seems that the acute floating point issues have been resolved in master, probably after floats were converted to rationals by https://github.com/sympy/sympy/pull/1169. But that will only work as long as the eigenvalues can be computed exactly (quite often, fortunately). Otherwise, no solution is obtained as noted in https://github.com/sympy/sympy/issues/11309. Maybe some kind of fallback procedure using floats should be applied in that case even if there are no floats in the original matrix.
