### ISSUE TITLE
Package the latest version of SymPy for the major distributions

### ISSUE THREAD

**Issue by vperic** [sympy/sympy#5895]
Most distributions have old versions of SymPy packaged (or none at all, eg. openSUSE). These should be updated to the latest version of SymPy (0.7.1 as of now). Ideally, the scripts used to generate these packages should also be saved and uploaded somewhere, so it will be easier to update them to newer versions. I'm marking this for Code-In, but consider that each major distro could be a separate task.

This most likely means deleting the bundled mpmath/ and making SymPy play nice with the distro-provided version.

Original issue for #5895: http://code.google.com/p/sympy/issues/detail?id=2796
Original author: https://code.google.com/u/108713607268198052411/

**Comment by oscarbenjamin** [comment]
Is this still relevant? The latest release is available in platform neutral ways (pip/conda) so is there a need to create these packages?

**Comment by asmeurer** [comment]
Most of the old code in tasks should be closed. Many of them were made just to have something the students could do. 

For this, I don't think we (the project) should maintain anything other than the official pip release and conda-forge (conda forge only because I use it personally and am OK with maintaining it). Packages for other distribution should be maintained by whomever wants to do it, but not officially by the project (which isn't to say we won't help if there are some issues).
