### ISSUE TITLE
divmod() should work for polynomial expressions

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#6301]
```
We have:

In [306]: divmod(Poly(x**2 + 1), Poly(x))
Out[306]: (Poly(x, x, domain='ZZ'), Poly(1, x, domain='ZZ'))

In [307]: divmod(x**2 + 1, x)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/Users/aaronmeurer/Documents/Python/sympy/sympy/<ipython-input-307-e54fef570ce4> in <module>()
----> 1 divmod(x**2 + 1, x)

TypeError: unsupported operand type(s) for divmod(): 'Add' and 'Symbol'

The latter should return (x, 1).
```

Original issue for #6301: http://code.google.com/p/sympy/issues/detail?id=3202
Original author: https://code.google.com/u/asmeurer@gmail.com/

**Comment by 1e9abhi1e10** [comment]
@asmeurer it works fine on `master` should it need a test to close ?
``` python
>>> from sympy import *
>>> x = Symbol('x')
>>> divmod(Poly(x**2 + 1), Poly(x))
(Poly(x, x, domain='ZZ'), Poly(1, x, domain='ZZ'))
>>> divmod(x**2 + 1, x)
(floor((x**2 + 1)/x), Mod(x**2 + 1, x))

**Comment by vprayag2005** [comment]
Here’s the updated message for you to copy:


---

Hello Aaron Meurer and the SymPy team,

I’m Prayag, and I’m new to open-source contributions. I recently joined SymPy and am eager to contribute to the project. I’m particularly interested in the issue about implementing divmod() for polynomial expressions.

Since I’m just starting out, could you please guide me on how to approach this? Any advice or support would be greatly appreciated. Thank you for your time, and sorry if this is inconvenient.

Best regards,
Prayag


---

This version directly addresses Aaron and the SymPy team.

**Comment by vprayag2005** [comment]
Here’s the updated message for you to copy:


---

Hello Aaron Meurer and the SymPy team,

I’m Prayag, and I’m new to open-source contributions. I recently joined SymPy and am eager to contribute to the project. I’m particularly interested in the issue about implementing divmod() for polynomial expressions.

Since I’m just starting out, could you please guide me on how to approach this? Any advice or support would be greatly appreciated. Thank you for your time, and sorry if this is inconvenient.

Best regards,
Prayag


---

This version directly addresses Aaron and the SymPy team.

**Comment by vprayag2005** [comment]
---

Hello Aaron Meurer and the SymPy team,

I’m Prayag, and I’m new to open-source contributions. I recently joined SymPy and am eager to contribute to the project. I’m particularly interested in the issue about implementing divmod() for polynomial expressions.

Since I’m just starting out, could you please guide me on how to approach this? Any advice or support would be greatly appreciated. Thank you for your time, and sorry if this is inconvenient.

Best regards,
Prayag


---

**Comment by oscarbenjamin** [comment]
This was fixed a long time ago. I don't think a test even needs to be added because there almost certainly is a test for this somewhere.
