### ISSUE TITLE
refactor long functions and long files.

### ISSUE THREAD

**Issue by Krastanov** [sympy/sympy#6384]
```
This is for a future GoogleCodeIn if we ever participate (or for everybody that wants to start contributing).

Find a function that is long (eg more than 200 lines of code without the comments and docstrings) and refactor it in smaller private function (each with its own docstring and possibly a doctest). Probably you will also need to move the function to another file (very long files (eg more than 1000~2000 lines) are just as bad as long functions).

I have made this report after seeing solve and _solve with all their nested conditionals. Even if someone is against specifically refactoring solve there are plenty other functions that need such refactoring.
```

Original issue for #6384: http://code.google.com/p/sympy/issues/detail?id=3285
Original author: https://code.google.com/u/100157245271348669141/

**Comment by mihir-w** [comment]
Hi! I am interested in contributing. Can anyone help me by pointing towards some long functions/files ?
Thank you.

**Comment by yoongkang** [comment]
I'd volunteer to take on solve() and/or _solve(), but I'd like to know if the community is open to refactoring this function first before I spend days on it. It seems to me like the test harness is adequate.

**Comment by asmeurer** [comment]
A lot has changed since this issue was opened. Most of the community effort these days is going into solveset, which is a redesigned version of solve.

**Comment by yoongkang** [comment]
Thanks for that, I'll leave solve() alone then. Solveset seems to be a candidate for refactoring too -- although it doesn't have any particular long functions there seems to be a lot of reliance on type-checking. 

I'd discuss a proposal, but I'm not sure if this is the right place. Sorry if this was written somewhere but do design discussions go on Github or the mailing list? Thanks.

**Comment by asmeurer** [comment]
You can do either place.

**Comment by jus1tin** [comment]
This seems like a good way to start contributing and get to know the sympy code. Is this still something that is needed? I noticed the issue is a little old.

**Comment by asmeurer** [comment]
I'm going to close this issue because it's too open ended. Google CodeIn is long over. 

You are still free to open pull requests refactoring the code. I'm only closing the issue because there's no clear goal that would indicate that it is completed. Code cleanups in general are something we can always do and don't need a broad issue for.

**Comment by jus1tin** [comment]
I guess you're right! I'll find something else usefull to do. I have a question though. I cloned the repository and ran the tests, other than that I didn't do anything yet but for some reason there is are a couple of failing tests and my terminal is telling me I shouldn't commit. I didn't change anything though, some of the failures seem to be caused by python2/python3 issues (integer division) but the rest are AssertionErrors without explanation. Is this normal? I haven't noticed anything not working or anything.
