### ISSUE TITLE
Squaring of large linear functions -- speed issue

### ISSUE THREAD

**Issue by pythonmobile** [sympy/sympy#6431]
L is a symbol list of 1000 variables. `(sum(L)**2).expand()` -- hangs (or takes long time). Perhaps this can be fixed?

Original issue for #6431: http://code.google.com/p/sympy/issues/detail?id=3332
Original author: https://code.google.com/u/107605304178788142628/

**Comment by smichr** [comment]
The optimization that @asmeurer mentioned has been committed. It is not easy to get significant improvement except for an unevaluated expansion since one must check for terms that have factors that simplify and perhaps combine in the new sum, e.g. (sqrt(2) + sqrt(3))**2 is `2 + 3 + 2*sqrt(6) = 5 + 2*sqrt(6)`. Checking for such situations and handling them is overhead that makes improvements beyond about 25% doubtful, IMO. In `power._eval_expand_multinomial`
```python
p = other_terms
if n == 2:
    return Add._from_args([i**2 for i in p] + [2*p[i]*p[j]
        for i in range(len(p))
        for j in range(i + 1, len(p))])
```
but
```python
>>> Add._from_args(Tuple(2,3,sqrt(6)*2))
2 + 3 + 2*sqrt(6)
```
