### ISSUE TITLE
subset is wrong for ImageSet

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#6475]
```
In [58]: a = TransformationSet(Lambda(x, x**2), Interval(0, 1))

In [59]: a.subset(Interval(0, 1))
Out[59]: False

In [60]: Interval(0, 1).subset(a)
Out[60]: False
```
But in fact, a is equal to Interval(0, 1).  subset just applies an intersection and checks if it is structurally equal.  Clearly, it should use some smarter methods, and try to be aware of when it doesn't know the answer either way.

Original issue for #6475: http://code.google.com/p/sympy/issues/detail?id=3376
Original author: https://code.google.com/u/asmeurer@gmail.com/

**Comment by kshitij10496** [comment]
I think the issue lies in the `reduce` method of the `Intersection` class, especially in [this](https://github.com/sympy/sympy/blob/master/sympy/sets/sets.py#L1555) code.
The `_handle_finite_sets` handles the case of `FiniteSet` and gives the desired output.
However, in other cases, it is giving `False`.
I think, in particular, there is some issue with the handling of `Interval`

```
In [ ]: a = ImageSet(Lambda(x, x**2), Interval(0, 1))

In [ ]: Interval(0, 1).is_subset(a)
Out[ ]: False

In [ ]: Union(Interval(0, 0.25), Interval(0.75, 1)).is_subset(a)  
Out[ ]: False

In [ ]: FiniteSet(0, 1).is_subset(a)
Out[ ]: True
```

**Comment by oscarbenjamin** [comment]
It's not just a problem for ImageSet. The `is_subset` method is broken in the main `Set` class. I've discussed this in #17550 

You can easily see the brokenness from this code and comment:
https://github.com/sympy/sympy/blob/4b93506a88cb924785a0e1dc98bb15205d2d45b8/sympy/sets/sets.py#L373-L381
and then e.g. this in the `simplify_intersection` function:
https://github.com/sympy/sympy/blob/4b93506a88cb924785a0e1dc98bb15205d2d45b8/sympy/sets/sets.py#L2182
