### ISSUE TITLE
SymPy Stats should assume expressions are equal to zero

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#6700]
```
If you have something like

X = Die("X", 6)
P(Eq(X, 3))

It's a little annoying that you have to use Eq (unlike, e.q., P(X > 3)).  Most places in SymPy solve this problem by automatically assuming that expressions are equal to zero, (like solve(x**2 - 2, x) instead of solve(Eq(x**2, 2), x)).  So functions in SymPy Stats like P() that usually take in boolean expressions should assume non-booleans are equal to zero.
```

Original issue for #6700: http://code.google.com/p/sympy/issues/detail?id=3601
Original author: https://code.google.com/u/asmeurer@gmail.com/

**Comment by Shaswat27** [comment]
@asmeurer Is the PR still open? Would like to work on it.

(Just starting out)

**Comment by asmeurer** [comment]
Was there are PR for this? I don't see it linked here.

**Comment by Shaswat27** [comment]
Sorry, this issue.

**Comment by asmeurer** [comment]
Yes. You can check yourself in SymPy master:

```
In [554]: from sympy.stats import *

In [555]: X = Die("X", 6)

In [557]: P(X - 3)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-557-c64c9fb67768> in <module>()
----> 1 P(X - 3)

/Users/aaronmeurer/Documents/Python/sympy/sympy/sympy/stats/rv.py in probability(condition, given_condition, numsamples, evaluate, **kwargs)
    625     if not isinstance(condition, (Relational, Boolean)):
    626         raise ValueError("%s is not a relational or combination of relationals"
--> 627                 % (condition))
    628     if condition is S.true:
    629         return S.One

ValueError: X - 3 is not a relational or combination of relationals
```

**Comment by Lakshya1605** [comment]
Is the issue still open? Would like to work on it.

**Comment by Lakshya1605** [comment]
Is this still open? I'll take it if so

**Comment by lgallindo** [comment]
Progress?

**Comment by Upabjojr** [comment]
I suggest closing this issue. `P(X)` is not the same as `P(X == 0)`.

While `X == 0` clearly defines a measurable subset of the probability space (which can be passed to _P_ to get the probability), does `P(X)` have a clearly defined meaning?

`P(X)` could be interpreted as a function, where `P(X)(x) == P(X == x)`, which means that `P(X)` is the `pdf` (probability density function).

Reasoning: `X: set of events ---> real numbers`, in this case `P(X(omega))` doesn't really make sense, because `X(omega)` is a real number. But we could use an additional definition extension, then `P(X)(omega) == P(X == X(omega))`, where `omega` is an event. We don't really have a representation for the events, so we can define `P(X)(x) == P(X == x)`.

A similar reasoning is on Wikipedia for the [conditional probability function](https://en.wikipedia.org/wiki/Conditional_probability#Conditioning_on_a_random_variable).

**Comment by asmeurer** [comment]
The comments above seem to agree with this, although it wasn't a consensus that P(X) giving the PDF was a good idea.
