### ISSUE TITLE
subs should recognize powers with exponent 1

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#6976]
```
In [31]: (sqrt(x)**3 + sqrt(x) + x + x**2).subs(sqrt(x), y)
Out[31]:
     4    3
x + y  + y  + y

Every term but x is replaced. This is because x is not a power, so the subs power logic is not applied to it.
```

Original issue for #6976: http://code.google.com/p/sympy/issues/detail?id=3877
Original author: https://code.google.com/u/asmeurer@gmail.com/

**Comment by normalhuman** [comment]
The logic of `Pow._eval_subs` is pretty complicated: a bunch of cases to check based on the exponents and assumptions on symbols. I fixed yet another bug there just a few days ago. So I don't think this logic should be reimplemented in `Symbol._eval_subs`. 

The following is a modification of @smichr's suggestion: (a) there is no need to handle `self==old` here, it's done higher up if this method returns None; (b) it's better to call `Pow._eval_subs` because if substitution is impossible, we want to return None, not the temporary `Pow`.  (c) using `_eval_subs` also avoids infinite recursion from `Pow.subs` invoking `Symbol.subs` because it's a subterm.   
 
```
 def _eval_subs(self, old, new):
     from sympy.core.power import Pow
     if old.is_Pow:
         return Pow(self, S.One, evaluate=False)._eval_subs(old, new)
```

But it seems that some manual integration routines are saved from infinite recursion only by the current behavior of `subs`, so I stashed this for now.
