### ISSUE TITLE
Getting simplify to simplify \integral 0

### ISSUE THREAD

**Issue by gibiansky** [sympy/sympy#7971]
I have the following expression:

```
\frac{1}{\sqrt{\pi}} \int_{0}^{\frac{x}{2 \sqrt{t}}} 0\, ds
```

Feeding this to simplify does nothing, even though this is a definite integral of 0, which should trivially be evaluated to zero. Why doesn't simplify simplify this to zero? Am I missing some assumptions?

**Comment by smichr** [comment]
`Integral(x, (x, 1, 1))` should not evaluate to 0 because we allow for unevaluated expressions. Someone might want to show what a trivial integral looks like. Even without using `doit` (which is a separate and referenced issue) simplify should be able to return the trivial 0 by just checking to see if `expr.is_zero` is true...and in this case it is:
```python
>>> Integral(x, (x, 1, 1)).is_zero
True
```
