### ISSUE TITLE
Remove deprecated assumptions: bounded/unbounded, infinitesimal

### ISSUE THREAD

**Issue by skirpichev** [sympy/sympy#8071]
For is_bounded/is_unbounded: use instead is_finite/is_infinite, see #7947
For is_infintesimal: use instead zero, see #7995

**Comment by divyanshu132** [comment]
Is this issue still open??

**Comment by asmeurer** [comment]
Apparently the attributes are gone, but the warning is still there if you set it on Symbol creation:

```
>>> x.is_infintesimal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Symbol' object has no attribute 'is_infintesimal'
>>> Symbol('x', infinitesimal=True)
./sympy/core/symbol.py:191: SymPyDeprecationWarning:

infinitesimal assumption has been deprecated since SymPy 0.7.6. Use
zero instead. See https://github.com/sympy/sympy/issues/8071 for more
info.

  deprecated_since_version="0.7.6").warn()
x
```

0.7.6 was a long time ago, I think this can be removed.

**Comment by asmeurer** [comment]
See https://github.com/sympy/sympy/wiki/Deprecating-policy

**Comment by asmeurer** [comment]
This is an interesting case, because unknown assumptions pass through without any error. So if we removed the warnings, `Symbol('x', infinitesimal=True)` would continue to work, but wouldn't do anything with regard to the usual assumptions (right now it sets `zero=True`). But maybe that is what we should do, since it has been deprecated long enough that no one should be using it.
