### ISSUE TITLE
Matrix multiplication is slow

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#8236]
See http://stackoverflow.com/questions/26246674/how-to-accelerate-slow-matrix-multiplication-in-sympy. Something like

```
In [1]: from sympy import *

In [2]: A = Matrix(500, 500, lambda i,j: 2 + abs(i-j) if i-j in [-1, 0, 1] else 0)

In [3]: A*A
```

is really slow, even though it's just an integer matrix. I think it's probably because matrix multiplication implements the naive algorithm.

**Comment by oscarbenjamin** [comment]
The current status is that the internal representation of matrices is always sparse:
```python
In [12]: A = Matrix(10, 10, lambda i,j: 2 + abs(i-j) if i-j in [-1, 0, 1] else 0)

In [13]: A._rep
Out[13]: DomainMatrix({0: {0: 2, 1: 3}, 1: {0: 3, 1: 2, 2: 3}, 2: {1: 3, 2: 2, 3: 3}, 3: {2: 3, 3: 2, 4: 3}, 4: {3: 3, 4: 2, 5: 3}, 5: {4: 3, 5: 2, 6: 3}, 6: {5: 3, 6: 2, 7: 3}, 7: {6: 3, 7: 2, 8: 3}, 8: {7: 3, 8: 2, 9: 3}, 9: {8: 3, 9: 2}}, (10, 10), ZZ)
```
Also for pure integer matrices the internal representation is a DomainMatrix with the elements represented in the `ZZ` domain (i.e. plain `int` or `gmpy2.mpz` if gmpy2 is installed).

The matrix multiplication is optimised for sparse matrices:
https://github.com/sympy/sympy/blob/e8ffcf40a6148235667ed75b811bdc1f953466e9/sympy/polys/matrices/sdm.py#L1246-L1287
It could be further optimised like using `A.keys()` instead of `set(A)` but otherwise it is hard to do better than this from pure Python. We can leverage python_flint for faster multiplication of *dense* matrices but I don't know of an easily available C implementation of sparse exact matrices that SymPy could use. Note that if the elements of the matrix are any kind of symbolic expression rather than just integers then the overhead of using a sparse representation is dwarfed by the cost of the arithmetic itself and I don't think that anything like FFT etc can be used to help that.

The OP example now takes 10ms:
```python
In [14]: A = Matrix(500, 500, lambda i,j: 2 + abs(i-j) if i-j in [-1, 0, 1] else 0)

In [15]: %time ok = A*A
CPU times: user 14.8 ms, sys: 0 ns, total: 14.8 ms
Wall time: 13.8 ms
```
The OP does not say how slow this was but I imagine it was a lot slower because the dense implementation was previously used.

This issue is fixed now.
