### ISSUE TITLE
Simplification of Relational and BooleanFunction

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8373]
Consider the following:

``` python
In [6]: x = Symbol('x', real=True)

In [7]: simplify(Or(x<1, x>= 1))
Out[7]: Or(x < 1, x >= 1)
```

I'd expect the result to be `True` or somehow else to designate "all `x`".

Even if I force the symbol to be a positive integer, this does not simplify:

``` python
In [3]: r = Symbol('r', integer=True, positive=True)

In [4]: Or(r<1, r>= 1)
Out[4]: Or(r < 1, r >= 1)

In [5]: simplify(Or(r<1, r>= 1))
Out[5]: Or(r < 1, r >= 1)
```

which is a bit odd. All of this causes over-complicated outputs sometimes. For example, trying to sum the PMF of a negative binomial distribution with `p=1/2`, I get

``` python
In [3]: k = Symbol('k', integer=True, nonnegative=True)

In [4]: r = Symbol('r', integer=True, positive=True)

In [5]: Sum(binomial(k+r-1,k)*(S.Half)**r*S.Half**k, (k, 0, oo)).doit()
Out[5]: Piecewise((1, Or(r < 1, r >= 1)), (Sum(2**(-k)*2**(-r)*binomial(k + r - 1, k), (k, 0, oo)), True))
```

**Comment by pelegm** [comment]
@smichr, `Or(x < 1, x >= 1)` now simplifies to `True`, that's good. However, `Or(x <= 1, x >= 1)` does not simplify at all, nor does `Or(x < 1, x > -1)`. Should that become a new bug report?

**Comment by smichr** [comment]
Reminder to check if `Or(x <= 1, x >= 1)`  and `Or(x < 1, x > -1)` simplify correctly. If they don't, the complementary args should be updated like `Le: (Gt, Ge), Ge: (Lt, Le)`, etc...

**Comment by smichr** [comment]
In closed #12579 the following was written:

> Maybe some of these expressions should be left unchanged. Or(x >= 0, x <= 0) is True if and only if x is real or oo or -oo, or, in other words, when Q.extended_real(x) is True. But for nonreal arguments Q.extended_real(x) does not raise an error. So, strictly speaking, the two expressions are not functionally equivalent. I have no clear view of what should be done (other than that a plain True does not seem appropriate).

I have been revisiting this issue and now understand better the nuances that @jksuom was talking about. An expression `x > 0` is not the same as `Q.positive(x)`; it is `Q.positive(x)` & `Q.real(x)`.

Here are some situations that need special care:

1. `x**2 < 0` cannot return `False` ... and that will happen if set simplification is used on this expression because the sets assume that x is real. This relationship is true if `x` is `I`.
1. `And(x<1, x>1)` cannot become False nor can it be `Ne(x, 1)` since neither of those imposes the requirement that x be real. The result should be `Ne(x, 1) & Eq(im(x), 0)`
1. Only relationals for which the periodicity is None or 0 can be converted. The following inequality has an infinite number of regions in which it is true:
```
>>> (sin(x) < 1).as_set().as_relational(x)
((0 <= x) & (x < pi/2)) | ((x <= 2*pi) & (pi/2 < x))
```

4. relationals *can* be converted via sets if they are univariate in some symbol, x, and the numerator and denominator are linear in x.
1. any use of set conversion must take care to keep the original sense wrt +/-oo. e.g. 
```
>>> foo(x*(x - 1) <= x**2 - x)  # rejects oo but can't be Ne(x, oo) -- see 2 above
x < oo
>>> foo(x*(x + 1) <= x**2 + x)  # rejects -oo
x > -oo
```
6. the args of `And` and `Or` can be separated into "eigensets" of relationals that satisfy the above conditions, e.g. `And(y, x< 1, x < 3)` can become `And(y, x < 1)`
7. some attention may be needed wrt assigning `count_ops` for Relationals.
```
>>> Eq(x, 1).count_ops()  # should probably be 1
0
```

breadcrumbs: #12579 and my pwargs2 branch contain work that was headed towards relational simplification

**Comment by asmeurer** [comment]
Boolean logic is designed around the idea that everything is either true or false. The best way to make sense of `x > 0` for nonreal x is to just set it to False. That is, `a > b` is equivalent to `Q.positive(a - b)`. You'll notice that `ask(Q.positive(I))` gives `False`. 

This leads to some things that you have to be careful about. You don't have that `x > 0` and `x <= 0` are exhaustive, but they are exclusive. In other words, we don't have the double implication `Equivalent(x > 0, Not(x <= 0))` but you do have `Implies(x > 0, Not(x <= 0))` (*).

1. Agree

2. `And(x < 1, x > 1)` actually is False. There's no value for `x` that can make both `x < 1` and `x > 1` True, and `And` is True iff all arguments are True. Another way to think of this is that we do have that the implication `Implies(x < 1, Not(x > 1))` is True (if x is less than 1, then it is not greater than 1). (**)

3. `(sin(x) < 1).as_set()` itself is wrong (has nothing to do with relationals). It doesn't say anything in the docstring, but I would expect `as_set` to return an exhaustive set. `as_relational` is returning the right thing for the set its given. 

4. There are probably more cases as well. solveset() should be used here. 

5. I'm not clear what `foo` is, but if you plug in `oo` to `x**2 - x` you get `nan`. Although this does remind me of some of my worries that if we allow `<`/is_positive to include infinities then we might end up reducing our computational power just to be careful that things are still correct with infinities. 

6. Yes, using the above, there are certain implications (but not necessarily double implications) that are always true for inequalities. `Implies(a > b, Not(a <= b))` is one. `Implies(And(a > b, b > c), a > c)` is another (if we combine these with the implicit fact that 3 > 1 then we get `Implies(And(x > 1, x > 3), x > 3)`). https://en.wikipedia.org/wiki/Ordered_field#Properties_of_ordered_fields is probably an exhaustive list of relevant logical facts for inequalities from which the rest can be derived. This is important because if we can teach the assumptions system (e.g., `satask`) about these facts, then simplifications like `And(y, x< 1, x < 3)` -> `And(y, x< 1)` could be derived automatically.

7. I don't understand the logic in count_ops. Shouldn't it work purely structurally, simply counting the number of non-leaf nodes in the expression tree? 

(*) In SymPy actually `Not(x < 0)` returns `x >= 0`, which results in a lot of convenient things when the boolean functions simplify using Not (like to_cnf and so on). But it's also only technically true if x is real. This obviously makes things simplify quite nicely in a lot of cases, but it's wrong from the above idea, since both could be False if `x` is not real. I don't really know what to do about this. 

(**) Apparently `ask` doesn't work on pure logical expressions for some reason. If it did, you could verify this with `ask(And(a, b), Implies(a, Not(b)))`. For now, you'll have to be content with `satisfiable(And(And(a, b), Implies(a, Not(b))))` (it returns `False`).

**Comment by oscargus** [comment]
I was pointed here by @smichr (thanks again!) after #15912 (also, #15905 is relevant).

Here are my 2 cents:
```
>>> from sympy import symbols, I
>>> x = symbols('x')
>>> (x < 1+I)
Traceback (most recent call last):

  File "<ipython-input-3-9df5ba1a88ec>", line 1, in <module>
    (x < 1+I)

  File "C:\Users\Oscar\sympy\sympy\core\expr.py", line 358, in __lt__
    raise TypeError("Invalid comparison of complex %s" % me)

TypeError: Invalid comparison of complex 1 + I
```

My conclusion from this is that relations are only valid for reals. Hence `x**2 < 0` is False by definition. If not, the above comparison should also be valid, since is valid (as a valid comparison, not True) for any x with -I as imaginary unit.

I realize that there are some potential issues with simplifications and +/-oo, but the question is how much effort should be put in keeping them there for the rare cases that it actually matters. I think that most people use sympy to compute and simplify stuff. There is clearly a trade-off of "mathematical sloppiness" here, but it would be quite helpful if things can be simplified further than they are today.

**Comment by oscargus** [comment]
After some more thinking. It should be possible to apply most of the "problematic" simplifications discussed above for the case of Piecewise segments, right?

For 5. One just need to make sure that oo is the first segment etc. (Although one could also wonder if that type of expression actually shows up unless hand written and I guess one can always write things that tricks the system, somehow I guess that with the knowledge of that type expression also means that one know how to write it in a simpler way). Hence, it would make sense to, at least, either have a specific method for these simplifications in general, as discussed elsewhere, or at least allow them as simplifications for Piecewise.

**Comment by oscargus** [comment]
I've added patterns to cover these cases in #17330. However, not sure if I want to close the issue since there's a good discussion in it.

**Comment by smichr** [comment]
> only valid for reals. Hence `x**2 < 0` is False by definition

I think the question is how to represent an answer to something that is indeterminant such as `eq = x**2 < 0` because `eq.subs(x, 1 + I)` is not valid. So we can't conclude that `eq == True` since it could have an invalid value for x. On the other hand, we allow `x - x` to go to 0 even though `x` could be oo...

Since `oo - oo == nan` we could say `x - x == Piecewise((0, Ne(1/x, 0)), (nan, True))`; for inequalities we would have `(x**2 < 0) == Piecewise((False, Eq(im(x**2), 0)), (nan, True))`.

**Comment by smichr** [comment]
I raised this question on the [mailing list](https://groups.google.com/forum/#!topic/sympy/Bm5U9PIspNU).

**Comment by oscargus** [comment]
What about `y/x >= constant | x/y >= constant`? Assuming all are (extended) real, is it OK to say that this is always True? (Possible problem is of course if x or y (or both) are zero.) Similar, but slightly simpler for `y/x <=a | x/y <= a`, where it should be OK at least if one is zero.

This can of course be generalizes to <, > and &, but I guess the reasoning can be generalized to those cases.

These types of expressions show up in some stats integrals if nothing else.

**Comment by czgdp1807** [comment]
Currently, 
```python
>>> x = Symbol('x', real=True)
>>> simplify(Or(x<1, x>= 1))
True
>>> r = Symbol('r', integer=True, positive=True)
>>> Or(r<1, r>= 1)
True
>>> simplify(Or(r<1, r>= 1))
True
>>> k = Symbol('k', integer=True, nonnegative=True)
>>> r = Symbol('r', integer=True, positive=True)
>>> Sum(binomial(k+r-1,k)*(S.Half)**r*S.Half**k, (k, 0, oo)).doit()
1
```
May be this can be closed.

**Comment by czgdp1807** [comment]
The discussion after opening this issue can be transferred to a different issue for highlighting them to new contributors.

**Comment by oscarbenjamin** [comment]
> My conclusion from this is that relations are only valid for reals. Hence `x**2 < 0` is False by definition.

We need to be careful here that saying that the two sides of the inequality must be (extended) real is not the same as saying that all symbols are real. For example if `x = I` then both sides of the inequality are real and the inequality is True:
```python
In [5]: (x**2 < 0).subs(x, I)
Out[5]: True
```
