### ISSUE TITLE
summation produces polar_exp in result

### ISSUE THREAD

**Issue by smichr** [sympy/sympy#8404]
Because of the exp_polar in the result, the result cannot be evaluated. Is it suppose to give exp_polar or should the be replaced with exp?

```
>>> Sum(1/(3*i+1)**2,(i,0,oo)).n(4)
1.122
>>> Sum(1/(3*i+1)**2,(i,0,oo)).doit().n(4)
-0.1667*polylog(2, exp_polar(4*I*pi/3)) + 0.2887*I*polylog(2, exp_polar(4*I*pi/3
)) + 0.835 + 0.04551*I
>>> _.replace(exp_polar, exp).n(4)
1.122 - 3.22e-7*I
```

**Comment by asmeurer** [comment]
A related example:

```
In [4]: summation((-1)**(n + 1)/n**2, (n, 1, oo))
Out[4]:
        ⎛    ⅈ⋅π⎞
-polylog⎝2, ℯ   ⎠

In [5]: summation((-1)**(n + 1)/n**2, (n, 1, oo)).replace(exp_polar, exp)
Out[5]:
 2
π
──
12

```

(see also https://math.stackexchange.com/questions/2067911/can-a-mathematician-review-my-t-shirt-design)

**Comment by jksuom** [comment]
It seems that exp_polar could always be replaced with exp when computing hypergeometric sums.

_eval_sum_hyper [calls hyperexpand](https://github.com/sympy/sympy/blob/master/sympy/concrete/summations.py#L1037) on a simple hypergeometric series h = hyper(ap, bq, x). hyperexpand [polarifies](https://github.com/sympy/sympy/blob/master/sympy/simplify/hyperexpand.py#L1954) the argument x and attempts to unpolarify it again at exit by [calling powdenest](https://github.com/sympy/sympy/blob/master/sympy/simplify/hyperexpand.py#L2041). However, [unpolarify](https://github.com/sympy/sympy/blob/master/sympy/simplify/powsimp.py#L591) is careful not to touch the arguments of branched functions such as polylog, so an expression with exp_polar is returned.

This issue only appears in case len(ap) == len(bq) + 1.  If len(ap) <= len(bq), then the series h is convergent everywhere; there is no branching and unpolarify should succeed. (If len(ap) > len(bq) + 1, the series is divergent, and there is no result.)

However, if len(ap) == len(bq) + 1, the series is divergent for |x| > 1, and its analytic continuation is branched at x = 1. Since there is no branching at x = 0, it is safe to replace the exp_polar argument with a plain complex number. (Besides, the series is divergent in the area where branching matters.)
