### ISSUE TITLE
oo.is_prime is not False

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#8487]
`oo.is_prime` should be False, I guess, and same with `zoo.is_prime`.

**Comment by toolforger** [comment]
Is there even a mathematically useful definition of primality for infinities?
I'd expect is_prime to throw an exception for them.

This might be worth discussing in the mailing list.
And/or trying out that exception-throwing route, to find those parts of the test suite that even make assumptions about the primality of infinities.

**Comment by skirpichev** [comment]
> I'd expect is_prime to throw an exception for them.
>
> This might be worth discussing in the mailing list.

No.  It should be either True/False or None.  None vs False (in case if assumption doesn't make sense) was discussed already, try to search over bugtracker.

**Comment by toolforger** [comment]
Okay, if these properties are used in assertions then an exception would not be right.
I'd still stick with None here. Primality isn't defined for infinities as far as I know.

**Comment by pelegm** [comment]
Is it defined for imaginary numbers? For negative numbers?

I guess not. For all of these, `is_prime` returns False.

**Comment by toolforger** [comment]
Maybe these are incorrect, too.

**Comment by skirpichev** [comment]
On Thu, Jan 08, 2015 at 12:57:29PM -0800, Joachim Durchholz wrote:
>    I'd still stick with None here.

None stands for "I don't know".  False - for "no" or "doesn't make sense".

**Comment by skirpichev** [comment]
On Thu, Jan 08, 2015 at 01:21:48PM -0800, Joachim Durchholz wrote:
>    Maybe these are incorrect, too.

Or maybe you should first read previous discussions
on the subject, right?

**Comment by asmeurer** [comment]
It should return False, because oo is not in the set of prime numbers. Fixing the infinity issues from https://github.com/sympy/sympy/pull/8134 will fix this automatically, because the assumptions system will know `prime -> integer -> real` and `infinite -> !real`.

**Comment by toolforger** [comment]
Am 08.01.2015 um 22:33 schrieb Sergey B Kirpichev:
> On Thu, Jan 08, 2015 at 01:21:48PM -0800, Joachim Durchholz wrote:
>>     Maybe these are incorrect, too.
>
> Or maybe you should first read previous discussions
> on the subject, right?

Wrong.
I did.
Maybe you should give a useful reference.

**Comment by skirpichev** [comment]
On Thu, Jan 08, 2015 at 01:54:08PM -0800, Joachim Durchholz wrote:
>    Maybe you should give a useful reference.

Sure, I'll try to do.  AFAIR is was recent @smichr's issue (or PR).

**Comment by pelegm** [comment]
> Fixing the infinity issues from #8134 will fix this automatically, because the assumptions system will know prime -> integer -> real and infinite -> !real

@asmeurer, so you say #8778 is redundant? I think that anyway it's good, at least for the meanwhile...

**Comment by skirpichev** [comment]
@toolforger, best I've found so far is #8045.

BTW, we should document this (i.e. in core/assumptions.py).

**Comment by toolforger** [comment]
I'm not sure that I follow Chris' logic there, but essentially it boils down to the question what callers expect of the is_* functions.
These questions can be surprisingly hairy. For Integer(5).is_prime it's clear that it should return True. For Rational(5,1), Rational(10, 2), and Complex(5, 0) one could argue that it's all the same old 5 number and should return True as well, or one could argue that it's numbers from the wrong domain and the answer should be None (or an exception because Rational and Complex numbers do not have a concept of primality, and asking them about that property indicates a logic error somewhere).
Essentially, it boils down to what's what SymPy code expects: if it expects e.g. 5 to be equal to 5+0i, and sometimes even substitutes one for the other, then we should apply the "is the same number" logic; if it keeps Rationals and Complex numbers strictly separate (and makes use of that separation), then is_prime should probably throw an exception.
I gather from Chris' words that it's the former, and then is_prime should probably return False for infinities as well.
What makes me a bit cautious is that Chris does not explicitly refer to an established policy decision to consider same values to be the same regardless of domain. If we do not have such an explicit decision, some people might do type testing before value comparison, which means they'll get failures if they test their code with Rationals and somebody suddenly uses Complex numbers with a zero imaginary part; more similar situations can be constructed.

**Comment by skirpichev** [comment]
> For Rational(5,1), Rational(10, 2), and Complex(5, 0) one could argue that it's all the same old 5 number and should return True as well, or one could argue that it's numbers from the wrong domain and the answer should be None

No.  None means "I don't know", not the wrong domain.

> Rational and Complex numbers do not have a concept of primality

Coerced expression (i.e. Integer) has.  BTW, we don't have Complex Number's yet.

> if it expects e.g. 5 to be equal to 5+0i

We have mathematical (Eq, and they are same) and structural (==, they are not same) equality.

> is_prime should probably throw an exception.

No, we don't want that logical inference will blow up in random places.  If some property doesn't make sense - we can return False.

> What makes me a bit cautious is that Chris does not explicitly refer to an established policy decision to consider same values to be the same regardless of domain.

Please refer to the tutorial about equality.

**Comment by toolforger** [comment]
Am 10.01.2015 um 00:09 schrieb Sergey B Kirpichev:
>> For Rational(5,1), Rational(10, 2), and Complex(5, 0) one could argue that it's all the same old 5 number and should return True as well, or one could argue that it's numbers from the wrong domain and the answer should be None
>
> No.  None means "I don't know", not the wrong domain.

In general, None has no fixed definition. It could be "don't know", or 
"invalid question", or "don't care", or whatever the software package 
assumes.
If "I don't know" is the proper definition here, then that should be 
documented, e.g. in a docstring. Is it? (I haven't checked, too many 
other things to do.)

>> Rational and Complex numbers do not have a concept of primality
>
> Coerced expression (i.e. Integer) has.

Sure. If coercion is normal, then it's useful to have primality.
I was talking in general terms.

 > BTW, we don't have Complex Number's yet.

How do we represent complex numbers then?

>> if it expects e.g. 5 to be equal to 5+0i
>
> We have mathematical (Eq, and they are same) and structural (==, they are not same) equality.

Okay.

>> is_prime should probably throw an exception.
>
> No, we don't want that logical inference will blow up in random places.

You snipped the conditions under which I placed that statement, so it 
became meaningless.

>> What makes me a bit cautious is that Chris does not explicitly refer to an established policy decision to consider same values to be the same regardless of domain.
>
> Please refer to the tutorial about equality.

Link?

**Comment by skirpichev** [comment]
On Sat, Jan 10, 2015 at 02:16:19AM -0800, Joachim Durchholz wrote:
>    If "I don't know" is the proper definition here, then that should be
>    documented, e.g. in a docstring. Is it?

It is.

> I haven't checked, too many other things to do.

Next time, please do.  Sympy bugtracker - wrong place to
read documentation.

>    How do we represent complex numbers then?

As Add(Number, Mul(ImaginaryUnit, Number))

>    >> What makes me a bit cautious is that Chris does not explicitly refer to
>    an established policy decision to consider same values to be the same
>    regardless of domain.
>    >
>    > Please refer to the tutorial about equality.
> 
>    Link?

http://docs.sympy.org/dev/tutorial/index.html

**Comment by toolforger** [comment]
>>     > Please refer to the tutorial about equality.
>>
>>     Link?
>
> http://docs.sympy.org/dev/tutorial/index.html

Overgeneral to the point of being useless.

**Comment by skirpichev** [comment]
I'm sorry, but for me, it looks you should read all tutorial, not just gotchas section (about equality).

**Comment by toolforger** [comment]
Am 10.01.2015 um 12:48 schrieb Sergey B Kirpichev:
> I'm sorry,  but for me, it looks you should read all tutorial, not just gotchas 
section (about equality).

You made a very specific claim, namely that the docs define value equality.
The section about equality was indeed what I read, but as you noticed, 
it's not what we're discussing.
So do me the favour and give a link to the section in question. I 
already said why I can't read everything, but you keep ignoring that 
(which is a kind of passive-aggressive behavour that I'm currently going 
beyond my normal patience to ignore, but I will not keep that up 
indefinitely; beware or face the effects).

**Comment by skirpichev** [comment]
> The section about equality was indeed what I read, but as you noticed, it's not what we're discussing.

I'm just explain for you the difference between structural and mathematical equality in the SymPy.

> So do me the favour and give a link to the section in question.

http://docs.sympy.org/latest/tutorial/gotchas.html#equals-signs

**Comment by toolforger** [comment]
Am 10.01.2015 um 13:39 schrieb Sergey B Kirpichev:
>> The section about equality was indeed what I read, but as you noticed, it's not what we're discussing.
>
> I'm just explain for you the difference between structural and mathematical equality in the SymPy.

Nope, you're claiming I'm wrong and unable to prove the point.

>> So do me the favour and give a link to the section in question.
>
> http://docs.sympy.org/latest/tutorial/gotchas.html#equals-signs

That's exactly the section you just said I should not restrict myself to 
reading.
Also, it's the section I actually read, and concluded that it does not 
even define value equality.

Please do try to read why I write. If I'm unclear, please ask.
But *do not assume that I do not know what I'm writing about*.
That's insulting, and worse, it's a waste of time because it forces us 
into looping around that question without making progress.

**Comment by skirpichev** [comment]
@pelegm, I sorry for this noise in you bugreport.

**Comment by asmeurer** [comment]
@pelegm yes it will be. See what I did on that other pull request. Ideally objects won't have redundant assumptions defined on them, because it's just confusing. If oo is set as just `infinite = True` and `positive = True` then that is very clear that it's just those two assumptions that define the object.

**Comment by pelegm** [comment]
@asmeurer, I see, but the #8134 is closed, so perhaps we'll merge #8778 at least until either #8134 will be reopened/merged or when a proper substituion for #8134 will be merged?

**Comment by asmeurer** [comment]
#8134 is closed because as-is, it cannot be merged, and I don't have the time to finish it myself (and leaving it open would just give the illusion that I might). What needs to be done is to cherry-pick the commits from that PR that haven't already been cherry-picked into master, and all the issues fixed. 

#8778 is mostly harmless, but whenever we do clean that up we should remove redundant assumptions on objects and only put those on it that are really needed to define what the object is.

**Comment by skirpichev** [comment]
> What needs to be done is to cherry-pick the commits from that PR that haven't already been cherry-picked into master, and all the issues fixed. 

What about changes in assumptions.py.  Should we discuss them again?

**Comment by asmeurer** [comment]
Yes. Those are more or less what that pull request *is* (there were some other changes, but they've all been included in https://github.com/sympy/sympy/pull/8293). The rest is just fixing the code to match them. We need to figure out what assumptions definitions make sense, particularly for real and positive.
