### ISSUE TITLE
sympy.physics.wigner: wigner_9j is broken for certain combinations of half-integer arguments

### ISSUE THREAD

**Issue by hydeik** [sympy/sympy#8747]
Hi. 

I found that `wigner_9j` raises unexpected ValueError for certain combinations of half-integer arguments like

```
>>> wigner_9j(0,0,0, 0,0.5,0.5, 0,0.5,0.5) # should return 1/2
...
ValueError: j values must be integer or half integer and fulfill the triangle relation
```

In the example above, the summation 

```
for kk in range(imin, int(imax) + 1):
```

should be taken for `kk` half-integer (1/2,3/2,...) rather than integer.

**Comment by fretchen** [comment]
I can confirm the error. Did anyone find a fix ?

**Comment by Rufflewind** [comment]
Can confirm too.

~~~py
wigner_9j(0, 0, 0, 0, .5, .5, 0, .5, .5)
~~~

This gives an error, when it should be `.5`.  The problem is due to [this section](https://github.com/sympy/sympy/blob/646c6909546ba1d24c56888ceaba912b0bf7f584/sympy/physics/wigner.py#L536-L540) of the code.  It wrongfully assumes that `kk` is an integer, when it can in fact be a half-integer under some circumstances.
