### ISSUE TITLE
parse "=" inside sympy.parsing.sympy_parser.parse_expr

### ISSUE THREAD

**Issue by pointhi** [sympy/sympy#8844]
I have searched through the documentation and didn't find any possibility to parse the equal sign inside strings.

The [doc](http://docs.sympy.org/0.7.5/gotchas.html) is explaining that the equal sign in python is a assignement, what is logical. But I think this shouldn't be a problem in the [parse_expr](http://docs.sympy.org/dev/modules/parsing.html) function to implement it as a transformation or something similar.

For example:

```python
from sympy.parsing.sympy_parser import parse_expr
parse_expr("Eq(1*2,x)") 
```

should also be writable as:

```python
from sympy.parsing.sympy_parser import parse_expr
parse_expr("1*2=x") 
```

**Comment by paramsingh** [comment]
Hi, @pointhi. I have made a pull request adding the feature you requested here : #9026. However the community seems to be split on whether `=` should be parsed or not. Please elaborate on your use case and why you asked for this feature, so we can decide if `=` should be parsed or not.

**Comment by pointhi** [comment]
thanks for your work @paramsingh,

I'm one of the developer of [searx](https://github.com/asciimoo/searx), which is an open source metasearchengine. We have introduced a plugin system recently, which allows us to serve server-created results like math equations. I would implement something like http://gamma.sympy.org inside searx to allowing solving of mathematic equations, and also more complex things like integral or differential.

I think at least solving mathematic equations should work for users without knowing about the underlying system. The main purpose of searx is being a search-engine, and the Computer algebra system should be a benefit for the user. I think most users never used a CAS, and the CAS system I'm working regular is supporting ```=``` since my first usage.

Furthermore, users can use equations in a more natural manner inside sympy (I was wondering first time using sympy, why it was not working like expected).

thx, pointhi

**Comment by paramsingh** [comment]
@pointhi, I think that you should join the discussions at #9255 and #9026.

**Comment by toolforger** [comment]
Ah I see.
I think #9026 tried to add the feature in the wrong spot, but the feature as such is indeed useful (though slightly outside SymPy's mission statement, which is "doing symbolic math in Python" - but we do support a variety of parsers, and this one would not be an exception).

Solving this would require a new parser - reusing a lot of existing parsers, no doubt, but still separate from the other parsers.
The question being: What would be a "more natural manner"? Sure, ```=``` for equations (instead of assignment) would work, but what do we use for assignment instead? Where do we draw the inspiration for the syntax to use for equality, assignment, and the various other tricky cases that don't have a straightforward translation (anything 2D, essentially: fractions, overlines that extend the root symbol or stand on their own for various meanings of "inverted", matrices, exponentiation, to name things off the top of my head).
I'm too much into technical details to have an answer to that question; do you have one? Or a way how to approach the question?
