### ISSUE TITLE
Totient of any non-integer number

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#8875]
According to the Totient function definition on [wikipedia](http://en.wikipedia.org/wiki/Euler%27s_totient_function), the totient of non-integer numbers is not there. But in sympy:

```
>>> totient(2.3)
totient(2.3)
```

the value is returned, instead of an error.

**Comment by whitten** [comment]
From the wikipedia article you cited:

In number theory <http://en.wikipedia.org/wiki/Number_theory>, *Euler's
totient* or *phi function*, φ(*n*), is an arithmetic function
<http://en.wikipedia.org/wiki/Arithmetic_function> that counts the totatives
<http://en.wikipedia.org/wiki/Totative> of *n*, that is, the positive
integers less than or equal to *n* that are relatively prime
<http://en.wikipedia.org/wiki/Relatively_prime> to *n*. Thus, if *n*
is a positive
integer <http://en.wikipedia.org/wiki/Positive_integer>, then φ(*n*) is the
number of integers *k* in the range 1 ≤ *k* ≤ *n* for which the greatest
common divisor gcd <http://en.wikipedia.org/wiki/Greatest_common_divisor>(
*n*, *k*) = 1.[1]
<http://en.wikipedia.org/wiki/Euler%27s_totient_function#cite_note-1>[2]
<http://en.wikipedia.org/wiki/Euler%27s_totient_function#cite_note-2> The
totient function is a multiplicative function
<http://en.wikipedia.org/wiki/Multiplicative_function>, meaning that if two
numbers *m* and *n* are relatively prime (with respect to each other), then
φ(*mn*) = φ(*m*)φ(*n*).[3]
<http://en.wikipedia.org/wiki/Euler%27s_totient_function#cite_note-3>[4]
<http://en.wikipedia.org/wiki/Euler%27s_totient_function#cite_note-4>

It looks like the issue is the "relatively prime" requirement, since it is
only defined for integers ( http://en.wikipedia.org/wiki/Coprime_integers
). Certainly, getting a list of integers less than or equal to n doesn't
require n to be a real number.
The requirement to get the number of integers k in the range 1 ≤ k ≤ n
doesn't require n to be an integer. I don't know if calculating the
greatest common divisor is defined for non-integers.  I'm unclear about the
efficacy or applicability of the totient function being a multiplicative
function.

David

**Comment by gxyd** [comment]
I don't get you completely, but The wolframalpha also raise an error, http://www.wolframalpha.com/input/?i=totient%282.3%29

**Comment by darkcoderrises** [comment]
In number theory, Euler's totient or phi function, φ(n), is an arithmetic function that counts the totatives of n,
and In number theory, a totative of a given positive integer n is an integer k

And in sympy/ntheory/factor_.py toitent class is also defined this way
class totient(Function):
    """
    Calculate the Euler totient function phi(n)

    >>> from sympy.ntheory import totient
    >>> totient(1)
    1
    >>> totient(25)
    20

    See Also
    ========

    divisor_count
    """
    @classmethod
    def eval(cls, n):
        n = sympify(n)
        if n.is_Integer:
            if n < 1:
                raise ValueError("n must be a positive integer")
            factors = factorint(n)
            t = 1
            for p, k in factors.items():
                t *= (p - 1) * p**(k - 1)
            return t
it checks if n is a integer

So i think that gxyd is right
and if u also think so we will just have to add else to that if.

**Comment by gxyd** [comment]
@smichr  plz. take a look at this issue, i think earlier you were discussing about the totient function's output but i think the input to the function should only be a positive integer.

**Comment by gxyd** [comment]
@darkcoderrises i think adding the code you are suggesting i.e.(else: raise ValueError("n must be positive") would not work, since this totient function should still be returned unevaluated for an instance of Symbol. Ex.
>>> x = Symbol('x')
>>> totient(x)
totient(x)              # should be returned as it is
>>> totient(oo)    # should raise an error

**Comment by darkcoderrises** [comment]
@gxyd Ya sorry for that we can do something like elif n is number(real and complex)

**Comment by gxyd** [comment]
@smichr  please have a look at the reference i have given for this issue( #8875 ) .

**Comment by aka001** [comment]
I have added test cases for this as well.
Please review it.
https://github.com/sympy/sympy/pull/8923
