### ISSUE TITLE
`Trace(X) + Trace(X)` where `X` MutableDenseMatrix fails "unhashable type"

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#9043]
Perhaps a sympify is missing somewhere?

````
>>> X = Matrix([[1, 2], [3, 4]])
>>> Trace(X) + Trace(X)
TypeError: unhashable type: 'MutableDenseMatrix'
````
versus:
````
>>> X = sympfy(X)   # or ImmutableMatrix(...)
>>> Trace(X) + Trace(X)
2*Trace(Matrix([
[1, 2],
[3, 4]]))

>>> Trace(X) + Trace(2*X)
Trace(Matrix([
[1, 2],
[3, 4]])) + Trace(Matrix([
[2, 4],
[6, 8]]))
````

**Comment by lokeshh** [comment]
I have many questions before diving into this. If some are answered, the journey would be easy. Here they are:

What's the function of `sympfy` in general?

And why does `ImmutableMatrix` works but `MutableDenseMatrix` fails. Is it a bug or designed this way?

Further, `trace(X) + trace(X)` works irrespective of whether X is `ImmutableMatrix` or `MutableDenseMatrix`. How come this be true since `trace(X)` finally gets converted to `Trace(X)`?

To fix the issue, would converting `X` to `ImmutableMatrix(X)` every time `Add` is called upon `Trace(X)` as arguments, a good idea?

**Comment by cbm755** [comment]
Perhaps you'll need to do some reading to understand these things... starting with reading `simpify?` Some of these I cannot answer, still learning too.

>> And why does ImmutableMatrix works but MutableDenseMatrix fails. Is it a bug or designed this way?

Clearly *I* think this is a bug, that's why I reported it (!)

I said what I thought the problem was (missing `sympify` which would make the MutableDenseMatrix into Immutable).  I have not tried to look further yet.

**Comment by lokeshh** [comment]
I have made an attempt to solve this making use of `sympify` here #9072.
