### ISSUE TITLE
`MatMul(2, Matrix(...)).doit()` doesn't do it

### ISSUE THREAD

**Issue by cbm755** [sympy/sympy#9053]
```
X = Matrix([[1, 2], [3, 4]])
assert MatMul(2, X).doit() == 2*X
```

needs fix to canonicalize bits?

**Comment by cbm755** [comment]
Bit more info:
````
X = ImmutableMatrix([[1, 2], [3, 4]])
w = MatMul(2, X)
w.doit()

Out[51]: 
2*Matrix([
[1, 2],
[3, 4]])

q = MatAdd(X, MatMul(2, X))
q.doit()

Out[52]: 
Matrix([
[3,  6],
[9, 12]])

````
Looking at the steps taken by the code, it seems to be the `canonicalize` routine of *MatAdd* that does this latter result.  Whereas *MatMul*'s `canonicalize` apparently cannot.

**Comment by kevinventullo** [comment]
MatAdd's `canonicalize`  uses `glom(matrix_of, factor_of, combine)`. The `combine` functions takes the object `MatMul(2,X)`, pulls apart its arguments `2` and `X`, then combines them as `2*X`. The difference being that `2*X` returns `[[2,4],[6,8]]` rather than a MatMul.

Anyway, I think adding a similar `glom` to the rules in MatMul should fix this. I'll issue a PR in the morning if no one else has.

**Comment by cbm755** [comment]
Sounds good to me.  There is an XFAIL test in #9031.

**Comment by oscarbenjamin** [comment]
I get no AssertionError from
```
In [9]: X = Matrix([[1, 2], [3, 4]]) 
   ...: assert MatMul(2, X).doit() == 2*X                                                                                                      

In [10]: X                                                                                                                                     
Out[10]: 
⎡1  2⎤
⎢    ⎥
⎣3  4⎦
```
Not sure from the decsription but was that the issue? Is it now fixed then?

**Comment by cbm755** [comment]
l'm OP, looks fixed, thanks for the nudge
