### ISSUE TITLE
limit(floor(atan(x)), x, oo) fails to simplify

### ISSUE THREAD

**Issue by pelegm** [sympy/sympy#9158]
This is probably related to #8485. I'd expect

``` python
>>> limit(floor(atan(x)), x, oo)
```

to return 1. Instead, it does not simplify, even after `.evalf()`, as it injects `zoo` into `atan` for some unknown reason. The same happens with ceiling.

**Comment by anutosh491** [comment]
yeah all expressions of the type `limit(floor( f(x), x, oo))` where f(x) stands for `inverse trig ` functions work perfectly except this one due to some wrong substitution taking place into `atan` ( might be `zoo` as pointed above) !
Even something like the log rewrite of the expression works fine ,
```
>>> limit(floor(atan(x).rewrite(log)), x, oo)
1
```
