### ISSUE TITLE
Sympy Web Hybrid Application like KAlgebra

### ISSUE THREAD

**Issue by Chitrank-Dixit** [sympy/sympy#9208]
I was trying to work on Sympy project as a GSoC student , but I was not able to submit my proposal and that was not my fault. I was trying 25 minutes before the deadline but still My Proposal was not uploaded there. And unfortunately this was my last year to apply. No Problem Howsoever. But I have written one proposal and want to work on this proposal volunteerily if someone guide me like the mentor, please read out my proposal and let me know, If someone is really going to provide me the guidance during my proposed project.

Please have a look at this link

[Chitrank Dixit GSoC 2015 Proposal](https://github.com/sympy/sympy/wiki/GSoc-2015-Application-Chitrank-Dixit--Sympy-Web-Hybrid-Application-like-KAlgebra)

**Comment by moorepants** [comment]
@Chitrank-Dixit Unfortunately there is nothing we can do for GSoC. Google does not grant exceptions even if Melange doesn't work. That's why we recommend submitting to Melange early even before you've finalized your proposal.

Glad to hear that you want to participate anyways. Also send a mail to the SymPy email list to discuss your proposal.

**Comment by oscarbenjamin** [comment]
I hope this worked out in the end.

This issue doesn't seem to represent something to be fixed in SymPy though so should probably be closed.

**Comment by czgdp1807** [comment]
Closing this for now in reference to the above comment. Thanks for the contributions and efforts. Please let us know if someone wants to re-open it.
