### ISSUE TITLE
Maximum recursion depth exceeded in printer

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#9216]
expr = Pow(1,-1,evaluate=False)
latex(expr)

**Comment by cbm755** [comment]
Possibly related, `e = Pow(3,-2,evaluate=False)` does give an answer but it is evaluated.

**Comment by jksuom** [comment]
I think this is what happens: latex starts printing a Pow, but then [switches over to Mul]
(https://github.com/sympy/sympy/blob/master/sympy/printing/latex.py#L420) since the exponent
is rational and negative. Mul  notices that the [denominator is one]
(https://github.com/sympy/sympy/blob/master/sympy/printing/latex.py#L347) and after finding out
that the expression is not a Mul at all [restarts the whole process]
(https://github.com/sympy/sympy/blob/master/sympy/printing/latex.py#L320).

I don't know printing well enough to suggest a fix.
