### ISSUE TITLE
Expression incorrectly evaluated

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#9263]
```
>>> (-12 + (-2 + 2*sqrt(2))**2 + 8*sqrt(2)) == 0  # returns False
>>> (-12 + (-2 + 2*sqrt(2))**2 + 8*sqrt(2)).evalf() # gives -1*10^(-126)
```

Should be 0.

**Comment by debugger22** [comment]
This seems fine to me.
```
In [6]: (-12 + (-2 + 2*sqrt(2))*2 + 8*sqrt(2))
Out[6]: -16 + 12*sqrt(2)
In [7]: (-12 + (-2 + 2*sqrt(2))*2 + 8*sqrt(2)).evalf()
Out[7]: 0.970562748477141
```

**Comment by debugger22** [comment]
I think you meant `(-12 + (-2 + 2*sqrt(2))**2 + 8*sqrt(2))`. I've fixed the formatting.

**Comment by debugger22** [comment]
`simplify` seems to work fine.

```
In [3]: (-12 + (-2 + 2*sqrt(2))**2 + 8*sqrt(2)).simplify()
Out[3]: 0
```

**Comment by skirpichev** [comment]
@debugger22, can you read your [tutorial](http://docs.sympy.org/dev/tutorial/gotchas.html#equals-signs) eventually?  Looks really odd for core team member...

I have no idea how you "fixed the formatting" (@proy87, is that correct?), but now the bug description doesn't have problem at all.  The ``==`` is for structural equality in the SymPy, it wont do non-trivial simplifications.

And why evalf label?

**Comment by debugger22** [comment]
> @debugger22, can you read your tutorial eventually? Looks really odd for core team member...

I think you didn't get the context. It was not about `==`.

> I have no idea how you "fixed the formatting"

The code part was not surrounded by backticks while made `**` disappear(Check your email client).

> The == is for structural equality in the SymPy, it wont do non-trivial simplifications.

Agree but the actual bug being discussed in the issue is something else.

> And why evalf label?

Don't you think `(-12 + (-2 + 2*sqrt(2))**2 + 8*sqrt(2))` should give `0`?

**Comment by skirpichev** [comment]
> I think you didn't get the context. It was not about ==.

To me, it's not clear what is an issue for @proy87.  Most likely, it's confusion about `==` behavior.  Why not ask first?

> Don't you think (-12 + (-2 + 2*sqrt(2))**2 + 8*sqrt(2)).evalf() should give 0? 

Why it should?  Zero is an exact number.  But `evalf()` just evaluates formula to a given accuracy,
nothing more.  Why do you expect an exact answer?

```python
In [1]: Add(1, -1, evaluate=False).evalf()
Out[1]: 0.e-125

In [2]: (-12 + (-2 + 2*sqrt(2))**2 + 8*sqrt(2)).evalf()
Out[2]: -0.e-126
```

**Comment by debugger22** [comment]
>  But evalf() just evaluates formula to a given accuracy, nothing more. Why do you expect an exact answer?

Oh. This is some new knowledge for me. I knew that it evaluates the expression to a given accuracy but I never expected it to give something else where exact 0 can be expected.

If that's an expected behavior, I don't think there's an issue at all. Maybe, it could be closed once @proy87 confirms what he actually meant.

**Comment by skirpichev** [comment]
> I never expected it to give something else where exact 0 can be expected.

Why do you expect this?  This is not clear from the expression (c.f. ``1 - 1``) and involves non-trivial symbolic manipulations (polynomial expansion, etc).  `evalf()` do numerical evaluation, it's not for simplifications.

**Comment by debugger22** [comment]
Perhaps, this should be documented somewhere with the examples you quoted. It's not clear, at least to me, from [this](http://docs.sympy.org/latest/modules/evalf.html) page.

**Comment by toolforger** [comment]
It says: "By default, numerical evaluation is performed to an accuracy of 15 decimal digits."
It does imply that it's inexact, though I'll admit that it requires very careful reading to notice that.

**Comment by toolforger** [comment]
Re the idea that calculating whether something is zero should be exact: No, it's just the same difficulty.
Calculating a near-zero value from a difference is actually dangerous because the relative error of the difference tends to be much larger than the relative error of the individual expressions (particularly nasty if the difference goes into a denominator).

**Comment by skirpichev** [comment]
> Perhaps, this should be documented somewhere

Yes, if you think that the sympy docs must be a replacement for freshmen-level textbooks (else phrase "numerical evaluation" - should be enough).

**Comment by debugger22** [comment]
> ```>>> (-12 + (-2 + 2*sqrt(2))**2 + 8*sqrt(2)).evalf() # gives -1*10^(-126)
Should be 0.```

You do notice that few others also think so? :)

**Comment by skirpichev** [comment]
That's a guess.

**Comment by proy87** [comment]
You can close the issue if it expected behaviour.
IMHO, it is very unnatural, though.

**Comment by toolforger** [comment]
@proy87 `evalf` applies floating-point arithmetic. Square roots and similar do not have exact representation with that, and you cannot rely on the associative law to predict the outcome.
Simplification, on the other hand, is always exact because it's just term transformation. And in fact using `simplify` instead of `evalf` does give the expected zero result (I just checked).

**Comment by skirpichev** [comment]
> You can close the issue if it expected behaviour.

Could you explain what is "it"?  `evalf()` behavior (second line of your example) or `==`?

Regarding `evalf()` - it works exactly like other CAS, e.g. Mathematica (SymPy has different precision defaults, of course):
```
In[1]:= N[-12 + (-2 + 2*2^(1/2))^2 + 8*2^(1/2)]
Out[1]= 
          -15
1.11022 10
```

Regarding `==`, there is a good documentation of "how it is" (i.e. referenced above tutorial).  But yes, probably you may wonder why it is so (i.e. `==` doesn't work like mathematical equality).

**Comment by asmeurer** [comment]
@skirpichev please stop being disrespectful to people. Now. 

@proy87 the behavior of `==` is described at http://docs.sympy.org/latest/tutorial/gotchas.html#equals-signs. This is done because structural equality is used far more often than mathematical equality, and also mathematical equality is typically very expensive to calculate and in general [impossible](https://en.wikipedia.org/wiki/Richardson%27s_theorem). To calculate mathematical equality to 0 it's best to use `simplify()` on the expression and see if it reduces to 0. 

As for evalf, floating point numbers are inexact, and so they won't give exactly zero for zero equivalent expressions quite often. This is due to very fundamentally difficult issues with the way floating point numbers are (you can read https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html and http://perso.ens-lyon.fr/jean-michel.muller/Intro-to-TMD.htm to get a taste of why this is). A simpler answer is that if you get a very small number, say smaller than the precision (`10**15` by default in SymPy), you can assume that it is probably zero. Using `evalf(chop=True)` will automatically replace small floating point numbers with 0.

**Comment by skirpichev** [comment]
On Sun, Apr 12, 2015 at 11:34:12AM -0700, Aaron Meurer wrote:
>    [1]@skirpichev please stop being disrespectful to people. Now.

Ask someone else to obey your orders.
