### ISSUE TITLE
Probability of an event in sympy.stats

### ISSUE THREAD

**Issue by wolfgang-302** [sympy/sympy#9265]
The following code leads to an error in python3:

```
from sympy.stats import P, Die
d = Die('d',6)
print(P(d < 2)) # works as expected
print(P(d in {2,3,5})) # leads to an error
```

This is the error message:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-16a9a6f190a5> in <module>()
      4 d = Die('d',6)
      5 print(P(d < 2))
----> 6 print(P(d in {2,3,5}))

/Users/wolfgang/ipythonenv/lib/python3.4/site-packages/sympy/stats/rv.py in probability(condition, given_condition, numsamples, evaluate, **kwargs)
    615 
    616     # Otherwise pass work off to the ProbabilitySpace
--> 617     result = pspace(condition).probability(condition, **kwargs)
    618     if evaluate and hasattr(result, 'doit'):
    619         return result.doit()

AttributeError: 'NoneType' object has no attribute 'probability'
```

I am using osx 10.9.5, 

```
wolfgang$ ipython
Python 3.4.1 (v3.4.1:c0e311e010fc, May 18 2014, 00:54:21) 
IPython 3.1.0 -- An enhanced Interactive Python.

In [1]: import sympy

In [2]: sympy.__version__
Out[2]: '0.7.6'

```

**Comment by wolfgang-302** [comment]
I think, this behavior is related to the following:
```
from sympy import Symbol
from sympy.stats import Die

a = 2
x = Symbol('x')
d = Die('d',6)

1 <= a < 3 # evaluates to: True
a in {1,2} # evaluates to: True
a < 3      # evaluates to: True

1 <= x < 3 # Throws an TypeError
x in {1,2} # evaluates to: False
x < 3      # evaluates to: x < 3

1 <= d < 3 # throws an TypeError
d in {1,2} # evaluates to: False
d < 3      # evaluates to: d < 3
```

for me, the remaining question is:
If e is an event (in the case of a finite samplespace), then e is a subset of the samplespace.
Why should  P(d in e) not evaluate to the probability of e?
But then, d in e must not evaluate to False.

**Comment by stanleyjs** [comment]
This bug is still here!  P(x>=int) evaluates, but P(x == int) or P(x is int) returns 
'NoneType' object has no attribute 'probability'

**Comment by stanleyjs** [comment]
Okay, so I am chewing on this a little bit, but I am new to contributing to these sorts of projects.  I have discovered the problem with this issue: namely, if you pass P(dist <conditional>) any conditional that evaluates to a boolean, it will evaluate it instead of passing it and taking the density of it. 

EG

```
a = St.Binomial('x',5,0.7)
St.P(a >= 2)
```
returns a proper value and, using the terminal to output the conditional:

`X>=2`

However, when 
```
a = St.Binomial('x',5,0.7)
St.P(a == 2)
```
We get the nonetype error and the conditional prints:
`False`

Similarly, 
`St.P(a != 2)`
prints 
`True` but does not evaluate.


So, how does sympy pass the non-equality conditionals without them evaluating to bool first? How can I force the equality conditionals to not immediately evaluate?

**Comment by stanleyjs** [comment]
I updated to the git version and seems to be working now.

**Comment by Smit-create** [comment]
> The following code leads to an error in python3:
> 
> ```
> from sympy.stats import P, Die
> d = Die('d',6)
> print(P(d < 2)) # works as expected
> print(P(d in {2,3,5})) # leads to an error
> ```

It is because, the equality for sympy symbols/random variables is defined using `Eq(d, 3)`.., so d in {2,3,5} would not work as it will evaluate to boolean object.
The following will produce the expected results:
```python
>>> from sympy.stats import *
>>> from sympy import Eq
>>> D = Die('D', 6)
>>> P(D < 2)
1/6
>>> P(Eq(D, 2) | Eq(D, 3) | Eq(D, 4)) 
1/2 

```
> However, when
> 
> ```
> a = St.Binomial('x',5,0.7)
> St.P(a == 2)
> ```
> 
> We get the nonetype error and the conditional prints:
> `False`

Similarly, instead of a==2, `Eq(a, 2)` should be used:
```python
>>> B = Binomial('B', 5, 0.7)
>>> P(B>=2)
0.969220000000000
>>> P(Eq(B, 2))
0.132300000000000
```
@wolfgang-302 @stanleyjs Does this solves the issue?
