### ISSUE TITLE
Solve function involving Real inequality with Complex Number solution

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#9365]
```
>>> a = symbols( 'a' )
>>> solve( a**2 + a < -3 )
∅
```
But the equation possess the general solution as ``` re( a ) = -1/2 and ( im( b ) )**2 > 11/4 ```

**Comment by gxyd** [comment]
Perhaps we have 
```
>>> x = Symbol( 'x' )
>>> print( Or( x-I < 0 , x < 2) )                  # here `I` is the complex number 'iota'
Or(x - I < 0, x < 2)

>>> print( Or( x < I, x < 2 ) )

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-f86c46bc7701> in <module>()
----> 1 Or(x<I, x<3)

/usr/local/lib/python3.4/dist-packages/sympy/core/expr.py in __lt__(self, other)
    297             if (me.is_complex and me.is_real is False) or \
    298                     me.has(S.ComplexInfinity):
--> 299                 raise TypeError("Invalid comparison of complex %s" % me)
    300             if me is S.NaN:
    301                 raise TypeError("Invalid NaN comparison")

TypeError: Invalid comparison of complex I
```

@asmeurer  perhaps the two comments completely seems opposite of each other. One satisfying that  in second comment `eq.lhs - eq.rhs` be real,  while the first comments considers `eq.lhs` and `eq.rhs`  as each of its terms `a**2`, `a` as being real.
Please tell about the final stand on `complex number` comparison on gitter. As you asked @hargup as well.

**Comment by hargup** [comment]
I would continue to keep comparisons of complex numbers illegal therefore `Or(x - I < 0, x < 2)` not raising an error is a bug. This also means that solving for inequalities like `a**2 + a < -3` with complex variables should raise an error. The main cause of the problem here is that `solve` often confuses between real and complex domains and it is often hard to determine the expected answer. To mitigate this problem we have seperated the real and complex solvers in `solveset_real` and `solveset_complex` for the `solveset` module. So, the solution you expect should be given by `solveset_complex(re(a**2 + a )< -3, a) `. This which currently raises a `NotImplementedError` and I invite you to complete the implementation. @aktech is working on a `Complex` class in https://github.com/sympy/sympy/pull/9463 you are also invited to join this discussion and probably you can also collaborate with him.

**Comment by hargup** [comment]
Since we don't want the "Solve function involving Real inequality with Complex Number solution" in the form described I'm closing the issue. If anyone else disagree, please feel free to reopen the issue.
