### ISSUE TITLE
Circularity in assumptions of products

### ISSUE THREAD

**Issue by jksuom** [sympy/sympy#9413]
Running ``(2*z).is_complex`` with SYMPY_USE_CACHE=no leads to
```
RuntimeError: maximum recursion depth exceeded
```
This also happens with other assumptions (except ``is_commutative``).

**Comment by toolforger** [comment]
There are several bugs like that; we neglected to run the test suite with caching off (because it is ultra-slow), and infinite recursion issues started to slip in.
We discussed whether we should simply require that the cache be always on, or fix things so that they work without cache (that would mean making the test suite work without caching, and add a test run for that on Travis).
@asmeurer @certik opinions?
