### ISSUE TITLE
simplify does not reduce atan2(0, -x+y)  to 0

### ISSUE THREAD

**Issue by jfosorio** [sympy/sympy#9440]
I found that Simplify does not reduce a function to zero that should  be reduced
```python 
from sympy import simplify, atan2, symbols
x,y = symbols('x,y', positive=True)
simplify(atan2(0, -x+y))
>> atan2(0, -x + y)
```
It is clear to me that in this case simplify should reduce this expression to zero given that atan2(0, x) is always zero independently of the sign of x.

**Comment by jfosorio** [comment]
In the same way the function refine does not reduce refine(atan2(0,-y+x))  to zero
```python
from sympy import simplify, atan2, symbols
x,y = symbols('x,y', positive=True)
refine(atan2(0, -x+y))
>> atan2(0, -x + y)
```

**Comment by leosartaj** [comment]
> it is clear to me that in this case simplify should reduce this expression to zero given that atan2(0, x) is always zero independently of the sign of x

Well, this is not the case. On SymPy master
```
>>> x = Symbol('x', positive=True)
>>> y = Symbol('y', negative=True)
>>> atan2(0, x)
0
>>> atan2(0, y)
pi
```
Purpose of using two arguments instead of one is to be able to return the correct quadrant of the computed angle.  As sign of ``(y - x)`` in your example is unknown, therefore, more simplification is certainly not possible.

See SymPy [docs] (http://docs.sympy.org/latest/modules/functions/elementary.html?highlight=atan2) on ``atan2`` for more information.

**Comment by jfosorio** [comment]
Sorry this is embarrassing mistake from my side. This can be closed.
