### ISSUE TITLE
Solving very slow in a strange situation

### ISSUE THREAD

**Issue by cheneave** [sympy/sympy#9515]
I want to solve an equation like 100000/2**(x/1000)-10000==0
It can be done by 

    solve('100000/2**(x/1000)-10000', 'x'), 

and it's very very slow.
However, 

    solve('100000/2**(x/100)-10000', 'x') 

is much faster, and 

    solve('100000/2**(x/10)-10000', 'x') 

is really fast.

I don't think there is really difference among these equations.

**Comment by aktech** [comment]
@cheneave 

Can you please describe, how are you measuring it's performance?
For me, it takes almost the same time, using `timeit`.

```python
In [3]: k = 100000/2**(x/1000)-10000

In [5]: k
Out[5]: 
                 -x  
                 ────
                 1000
-10000 + 100000⋅2    

In [6]: l = 100000/2**(x/100)-10000

In [7]: l
Out[7]: 
                 -x 
                 ───
                 100
-10000 + 100000⋅2   

In [8]: m = 100000/2**(x/10)-10000

In [9]: m
Out[9]: 
                 -x 
                 ───
                  10
-10000 + 100000⋅2   

In [10]: solve(k)
Out[10]: 
⎡1000⋅log(10)⎤
⎢────────────⎥
⎣   log(2)   ⎦

In [11]: solve(l)
Out[11]: 
⎡100⋅log(10)⎤
⎢───────────⎥
⎣   log(2)  ⎦

In [12]: solve(m)
Out[12]: 
⎡10⋅log(10)⎤
⎢──────────⎥
⎣  log(2)  ⎦

In [13]: timeit solve(k)
10 loops, best of 3: 107 ms per loop

In [14]: timeit solve(l)
10 loops, best of 3: 108 ms per loop

In [15]: timeit solve(m)
10 loops, best of 3: 108 ms per loop
```

**Comment by cheneave** [comment]
For me, the first equation do not show results in more than 10 seconds and the other two gave result almost instantly.

**Comment by aktech** [comment]
> For me, the first equation do not show results in more than 10 seconds and the other two gave result almost instantly.

Which version of SymPy are you using?

**Comment by cheneave** [comment]
The version of SymPy is 0.7.6 from pip.
And i'm using python3.4.3

**Comment by cheneave** [comment]
Is it some issue already fixed in master brunch?

**Comment by aktech** [comment]
> Is it some issue already fixed in master brunch?

Here are the results of the pip version 0.7.6

```python
In [11]: timeit solve('100000/2**(x/1000)-10000', 'x')
1 loops, best of 3: 1.66 s per loop

In [12]: timeit solve('100000/2**(x/100)-10000', 'x') 
10 loops, best of 3: 94.5 ms per loop

In [13]: timeit solve('100000/2**(x/10)-10000', 'x') 
10 loops, best of 3: 89.6 ms per loop
```
First one is almost twice as fast as third, but still gives result is less than a couple of seconds,
I can't figure out, why it's taking 10 seconds for you.

**Comment by cheneave** [comment]
And if x is divided by a larger number, 100000 for example, it's even slower. It seems the time cost is related to the the number x is divided. Not only the cpu usage goes up, the ram usage goes up too.

**Comment by toolforger** [comment]
I can confirm that in SymPy 0.7.6 with Python 2.6.9,

 >>> solve('100000/2**(x/1000)-10000', 'x')

takes 6-7 seconds, and that both

 >>> solve('100000/2**(x/100)-10000', 'x')
 >>> solve('100000/2**(x/10)-10000', 'x')

are somewhere around 0.5 seconds, running them a second time gives an 
almost-instantaneous answer.
Higher performance on the second run is not surprising, as SymPy caches 
internal intermediate results.

With current master, the first equation behaves just like the other two, 
so the issue seems solved.

**Comment by cheneave** [comment]
It's more than half a year since 0.7.6 and it's not strange the issue have been found by someone before and fixed. Which one is more recommended to daily use? Master brunch or the latest release?

**Comment by aktech** [comment]
> With current master, the first equation behaves just like the other two,
so the issue seems solved.

Yeah it looks like.
See [here](https://github.com/sympy/sympy/issues/9515#issuecomment-111675830), time taken is almost same: `10 loops, best of 3: 108 ms per loop`

**Comment by aktech** [comment]
> Which one is more recommended to daily use? Master brunch or the latest release?

I would recommend the Master one, as it's always better than the previous release.
Latest release, version is basically for other naive users, who don't prefer updating with the master, more frequently.

**Comment by cheneave** [comment]
Thanks

**Comment by toolforger** [comment]
Heh. Actually it's not a question of being naive.
Master is the current development version, so it can change behaviour rather abruptly. Very rarely, master is broken - we try very hard to avoid that so it's very rare and usually quickly fixed.
So... if you have a problem that's fixed in master, you can use master. Just run the full test suite (`bin/test` and `bin/test --slow`) to be on the safe side. (Note that the `test_kane3` test is currently taking hours, and may fail. We're assuming that that's a problem in the test, not in SymPy; just Ctrl-C is while it's running, the test suite will continue with the next test if you Ctrl-C.)
