### ISSUE TITLE
Zero detection fails when it should be guaranteed

### ISSUE THREAD

**Issue by roboloni** [sympy/sympy#9529]
The below code fails, saying (among others) "This may indicate a bug in SymPy or the domain is user defined". Since there is nothing user defined I assume it's a bug then.

```python
from sympy import *
n, r, rp, rm, rmin, rmax, dmin, dmax = symbols('n r rp rm rmin rmax dmin dmax')
integrate(
    integrate(
        integrate(
            r / (rp-rm) * 1 / (1/2 * (rmax-rmin)**2 * (rp-rm))
            ,(r,rm,rp))
        ,(rp,dmax,rmax))
    ,(rm,rmin,dmin))
```

**Comment by jksuom** [comment]
Python will interpret 1/2 as the floating point number 0.5 before feeding it to SymPy (as explained [here] (http://docs.sympy.org/latest/tutorial/gotchas.html#two-final-notes-and)).

The final integration is performed by the ``risch`` module which does not work with floating point numbers.
After changing 1/2 to ``S(1)/2`` the integration will succeed. (Or else, instead of ``1/2 * (rmax-rmin)**2 * (rp-rm)`` one could write ``(rmax-rmin)**2 * (rp-rm)/2``.)

**Comment by roboloni** [comment]
I see, thanks for the explanation! I'm new to sympy -- great library btw! -- and that's a gotcha I definitely misst :-)
