### ISSUE TITLE
Bug with limit

### ISSUE THREAD

**Issue by proy87** [sympy/sympy#9558]
`limit(sin(x)**15,x,0,'+')` works
`limit(sin(x)**15,x,0,'-')` hangs

**Comment by zanzibar7** [comment]
`limit(sin(0-1/x)**15,x,oo)` also hangs. although `limit(sin(0-1/x)**13,x,oo)` completes successfully but slowly.  Feels like this might be an issue with recursion reaching it's limitations.  Approaching from the positive side is probably working better because on the negative side, powers of negatives force us into the complex plane in general (though not when the power is an integer!).
