### ISSUE TITLE
Inconsistency in invert_real() for Trigonometric functions

### ISSUE THREAD

**Issue by aktech** [sympy/sympy#9586]
``` python
In [2]: from sympy.solvers.solveset import invert_real

In [5]: invert_real(sin(x), y, x)
Out[5]: (sin(x), {y})

In [6]: invert_real(csc(x), y, x)
Out[6]: (csc(x), {y})

In [7]: invert_real(sec(x), y, x)
Out[7]: (sec(x), {y})

In [8]: invert_real(cos(x), y, x)
Out[8]: (cos(x), {y})

In [9]: invert_real(tan(x), y, x)
Out[9]: (x, ImageSet(Lambda(_n, _n*pi + atan(y)), Integers()))

In [10]: invert_real(cot(x), y, x)
Out[10]: (x, ImageSet(Lambda(_n, _n*pi + acot(y)), Integers()))

```

It inverts correctly only for `tan` and `cot`.

**Comment by gxyd** [comment]
I think it is correct `not` to invert the `sin` and `cos` since it is `invert_real` which is supposed to work around only when we have defined ` - 1<= y <= 1` (otherwise expression to be returned as it is ) since only then the real value of `x` is possible. I am not sure about the `tan` and `cot` cases but i guess even they should not be evaluated, i guess.
@aktech  correct me if i am wrong.

**Comment by toolforger** [comment]
Am 29.06.2015 um 20:09 schrieb Gaurav Dhingra:
> I think it is correct `not` to invert the `sin` and `cos` since it is `invert_real` which is supposed to work around only when we have defined ` - 1<= y <= 1` (otherwise expression to be returned as it is ) since only then the real value of `x` is possible. I am not sure about the `tan` and `cot` cases but i guess even they should not be evaluated, i guess.

What is `invert_real` doing for squares?
It has to deal with the same problems (noninvertible values, 
ambiguities), so I'd copy whatever policy it's applying there.

**Comment by aktech** [comment]
@gxyd 
Your concern is right, Perhaps It should return the information regarding the validity of `invert` i.e. like the interval. Though we must `invert`, since currently our assumption system doesn't allows us imposing an interval assumption on a symbol.

@toolforger 
```python
In [9]: invert_real(sin(x)**2, y, x)
Out[9]: (sin(x), {-sqrt(y), sqrt(y)})

In [10]: invert_real((x)**2, y, x)
Out[10]: (x, {-sqrt(y), sqrt(y)})
```

**Comment by gxyd** [comment]
Thanks for the clarification both of you, I agree that the  current problem is that, we are not being able to define symbols in an interval.

**Comment by smichr** [comment]
> we are not being able to define symbols in an interval

But we can return a ConditionSet involving an interval, like `ConditionSet(y, y >= 0, S.Reals)` to say that `y` must be nonnegative, for example, in the solution of `solve(x**2 - y, x)`. If you look at the code for solving an inequality involving abs, there's a collection of conditions that are made as `Abs` are encountered in the expression. I think something like that could/should be applied to `solveset` so that along with the returned result is a set of conditions which must also be true. In many cases, maybe those conditions will resolve to True or False, but those that don't make it clear in what domain the solution is valid.

**Comment by oscarbenjamin** [comment]
Looks correct for the other examples on master:
```julia
In [9]: from sympy.solvers.solveset import invert_real                                                   

In [10]: invert_real(sin(x), y, x)                                                                       
Out[10]: 
⎛   ⎧    n                      ⎫⎞
⎜x, ⎨(-1) ⋅asin(y) + n⋅π | n ∊ ℤ⎬⎟
⎝   ⎩                           ⎭⎠

In [11]: invert_real(csc(x), y, x)                                                                       
Out[11]: 
⎛   ⎧    n                      ⎫⎞
⎜x, ⎨(-1) ⋅acsc(y) + n⋅π | n ∊ ℤ⎬⎟
⎝   ⎩                           ⎭⎠

In [12]: invert_real(sec(x), y, x)                                                                       
Out[12]: (x, {2⋅n⋅π + (asec(y) mod 2⋅π) | n ∊ ℤ} ∪ {2⋅n⋅π + ((-asec(y)) mod 2⋅π) | n ∊ ℤ})

In [13]: invert_real(cos(x), y, x)                                                                       
Out[13]: (x, {2⋅n⋅π + (acos(y) mod 2⋅π) | n ∊ ℤ} ∪ {2⋅n⋅π + ((-acos(y)) mod 2⋅π) | n ∊ ℤ})

In [14]: invert_real(tan(x), y, x)                                                                       
Out[14]: (x, {n⋅π + (atan(y) mod π) | n ∊ ℤ})

In [15]: invert_real(cot(x), y, x)                                                                       
Out[15]: (x, {n⋅π + (acot(y) mod π) | n ∊ ℤ})
```
