### ISSUE TITLE
Inverse trig functions don't evaluate trig functions nicely

### ISSUE THREAD

**Issue by mattgiamou** [sympy/sympy#9638]
For example, `sin(asin(x))` will evaluate to `x` when `x` is a symbolic variable while `asin(sin(x))`  does not. Is this an intentional design choice because of `asin`'s limited domain and range? There is code in sympy/elementary/functions/trigonometric.py that checks for identities involving inverse trigonometric functions when evaluating `sin`, `cos`, and `tan` but nothing for the other direction.

**Comment by Gadal** [comment]
Since sin isn't onto, so asin(sin(x)) isn't true for -pi/2 > x > pi/2.  In practice, when sin(x) is reducible by one of the existing production rules (like sin(0) -> 0), asin(sin(x)) -> x will be the result you end up with.

Since it's liable to be more like asin(sin(f(x))) -> f(x) that the user is going for, determining that f(x) is in [-pi/2, pi/2] may be really non-trivial.  (also, I don't see any production rules in trigonometry.py that require more than one step of look ahead)

**Comment by davidlowryduda** [comment]
I think Gadal's explanation is the correct one. Perhaps this issue should be closed?

**Comment by normalhuman** [comment]
Perhaps... On the other hand,
```
>>> simplify(asin(sin(x)))
x
```
so one can say there is still an issue with asin(sin()), though not exactly the same as stated.

**Comment by gschintgen** [comment]
The additional issue noted by @normalhuman seems to be fixed in 1.4:
```
>>> asin(sin(x))
asin(sin(x))
```
This issue could be closed then?

**Comment by oscarbenjamin** [comment]
It does seem to be fixed on master:
```julia
In [1]: simplify(asin(sin(x)))                                                                                                    
Out[1]: asin(sin(x))
```
I don't see anything else to fix here but I also don't see a test for this. The most closely related one I found is here:
https://github.com/sympy/sympy/blob/26aa686a20234f1f511c0f558d27665d0f95a21c/sympy/simplify/tests/test_simplify.py#L727

This can be closed if a test is added.

**Comment by gschintgen** [comment]
> This can be closed if a test is added.

I've just submitted a (very minor) PR adding the test.
