### ISSUE TITLE
Wrong result for solveset(tan(x) > 0, x)

### ISSUE THREAD

**Issue by hargup** [sympy/sympy#9642]
```python
In [28]: x = Symbol('x', real=True)
. . .    from sympy.solvers.solveset import solveset
. . .    solveset(tan(x) > 0, x)
Out[28]:(0,∞)
```

**Comment by hargup** [comment]
@aktech can you have a look at that?

**Comment by aktech** [comment]
Since `solveset` uses `solve_univariate_inequality`, which  is still [dependent on old **`solve`** :](https://github.com/sympy/sympy/blob/master/sympy/solvers/inequalities.py#L405)

Due to which this wrong result is evident.
```python
In [4]: solve(tan(x)  > 0, x).as_set()
Out[4]: (0, oo)

In [5]: solveset(tan(x)  > 0, x)
Out[5]: (0, oo)
```

Naively replacing the `solve` with `solveset` will not work there, as it would not recognize the returned `ImageSet` object. An appropriate change needs to be done in the `solve_univariate_inequality` function as well.

**Comment by hargup** [comment]
duplicate of https://github.com/sympy/sympy/issues/9721
