### ISSUE TITLE
combsimp doesn't work on factorials

### ISSUE THREAD

**Issue by asmeurer** [sympy/sympy#9699]
combsimp only works on gamma, not factorial:

```
In [1]: combsimp(factorial(n)*(n+1) )
Out[1]: (n + 1)⋅n!

In [5]: combsimp((factorial(n)*(n+1)).rewrite(gamma)).rewrite(factorial)
Out[5]: (n + 1)!
```

It should be easy to make it work by doing the rewrites automatically inside of combsimp.

**Comment by gxyd** [comment]
Both the issues can be closed now #8531 and this. Closed by #9711

**Comment by asmeurer** [comment]
Cool. In the future, add "fixes #9699" to the commit message and the issue should close automatically when the pull request is merged.

**Comment by jksuom** [comment]
I think this issue is now taken care of, but combsimp could benefit from a reorganization. Its use of ``_rf`` is hard to understand. In addition to its standard role as ``rf``, it is also used to represent ``gamma(n)``  as ``_rf(1, n - 1)``. If ``n`` is an integer, then ``rf(1, n - 1) = gamma(n)/gamma(1) = gamma(n)``, but it is also used for non-integers. The simplification rules for ``_rf`` are direct consequences of those of ``gamma``. It seems that one could use ``gamma`` as the basis for simplification and then rewrite the result in terms of ``factorial`` etc. if that would be expected.

**Comment by gxyd** [comment]
That sounds good.

**Comment by asmeurer** [comment]
Can you open a new issue.
