### ISSUE TITLE
Heaviside(0) should be undefined

### ISSUE THREAD

**Issue by zanzibar7** [sympy/sympy#9907]
I am working on an optimal-control problem that involves the derivative of a Max(0,x) function, which gives Heaviside(x) as it's derivative.  In the subsequent analysis, any line `y=mx` is tangent to Max(0,x) at x=0, so long as m is in [0,1].  Thus, in the subsequent analysis, it's very useful to treat Heaviside(x) as a generalized function where Heaviside(0) returns the whole interval [0,1].

Currently, Heaviside(0) returns 1/2, and some justification of this case is given.  However, reasonable 
arguements have been made for Heaviside(0) = 1 or 0 as well, and my example above provides a 4th possibility.  The situation reminds me of the argument we had some-time back over how to evaluate 1**oo, which we decided to leave as nan because there was no universally satisfactory convention.

I propose leaving Heaviside(0) as un-defined.  This is the conservative choice, and avoids possibly incorrect assumptions.  A `.subs(Heaviside(0),k)` can then be used if a specific value is desired.

**Comment by jksuom** [comment]
I think leaving Heaviside(0) undefined could be a justified choice. The Heaviside function is most often used to simply cut the domain of a function defined on the real line to the interval ``(0, oo)``, Its value at 0 is not relevant for this purpose.

In more technical terms, if ``\lambda`` is the Lebesgue measure on the real line, and ``\mu`` is its restriction to ``(0, oo)``, then Heaviside is the density of the  [pushforward]( https://en.wikipedia.org/wiki/Pushforward_measure) of ``\mu`` with respect to ``\lambda``. As a density, it need not be defined everywhere.

Instead of the open interval ``(0, oo)`` one could use ``[0, oo)`` as well. That will not chance the pushforward of the restriction, since the single point set ``{0}`` has (Lebesgue) measure zero. In particular, the density will be the same. 

In fact, one could think of Heaviside itself as a measure, the pushforward of ``\mu``. That would be in line with Dirac delta as the derivative of Heaviside. Dirac delta is often called a "function", but actually it is a measure, namely the pushforward of the unit measure at 0.  Then the derivative could be defined in the sense of [distributions](https://en.wikipedia.org/wiki/Distribution_(mathematics)#Derivatives_of_distributions). (Measures are a subclass of distributions.)
