### ISSUE TITLE
Order(n*log(n) + sin(n), (n, oo)) does not remove sin(n)

### ISSUE THREAD

**Issue by gxyd** [sympy/sympy#9910]
```
>>> O(n*log(n) + sin(n), (n, oo))
O(n*log(n) + sin(n), (n, oo))
```

rather `O(n*log(n), (n, oo))` should be returned.

**Comment by meghana1995** [comment]
The problem seems to be that in extract_leading_order(), sin(x) is not removed, it is considered a leading order term ( even though it should not be in the above case ).
In extract_leading_term https://github.com/sympy/sympy/blob/master/sympy/series/order.py#L213, there is a check to see whether a term is contained in the other terms to determine whether it is a leading term or not.
The problem seems to be that whenever contains() is called with sin(x) and another function, sin(x) never appears to be contained in another function because contain() uses the limit of the ratio of the functions. https://github.com/sympy/sympy/blob/master/sympy/series/order.py#L372 Hence, it is also considered a leading term.
One approach I thought would work would be to include a separate case for trigonometry function after extract_leading_order which would further filter the sin terms which are not leading terms . It appears hackish though. Should I create another pull request which does that or do you have any suggestions ?

**Comment by mijo2** [comment]
Since the issue is not fixed, I would give a try to work on it.

**Comment by mijo2** [comment]
@sachin-4099 is already working on the issue and seems like minor conflicts have to be dealt with.

**Comment by sachin-4099** [comment]
On master:
```
In [1]: O(n*log(n) + sin(n), (n, oo))
Out[1]: O(n*log(n); n -> oo)
```
This issue seems resolved.

**Comment by evatiwari** [comment]
On trying to write a test for this, ```assert O(x*log(x)+sin(x), (x, oo)) == O(x*log(x), (x, oo))```, I get an AssertionError. On trying ```O(n*log(n) + sin(n), (n, oo))```  on sympy live and jupyter notebook, using the latest version of sympy, I get ```O(n*log(n) + sin(n); n->oo)```. Please let me know where I am going wrong. If not,  I would like to work on this.
